var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,a,c){b instanceof String&&(b=String(b));for(var d=b.length,e=0;e<d;e++){var f=b[e];if(a.call(c,f,e,b))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,c){b!=Array.prototype&&b!=Object.prototype&&(b[a]=c.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};
$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,a,c,d){if(a){c=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var e=b[d];e in c||(c[e]={});c=c[e]}b=b[b.length-1];d=c[b];a=a(d);a!=d&&null!=a&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:a})}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6-impl","es3");
var sparkConfig={gateway:null,servers:null,users:null,config:function(b,a,c,d,e,f){b=b+"/CONF?type="+a+"&action="+c;f&&(b+=f);(a=document.getElementById("gwPwd").value)&&(b+="&gwPwd="+encodeURIComponent(a));hi5.tool.openWebSocket(b,e,d)},formatDate:function(b){if(!b)return"";b=new Date(b);return b.getFullYear()+"-"+(b.getMonth()+1)+"-"+b.getDate()+" "+b.getHours()+":"+b.getMinutes()},parseDate:function(b){var a=b.split(" ");b=a[0].split("-");a=a[1].split(":");if(3!=b.length||2!=a.length)throw"Date format must be yyyy-MM-dd hh:mm";
return new Date(b[0],b[1]-1,b[2],a[0],a[1])},showMessage:function(b){document.getElementById("message").innerHTML=b},checkError:function(b){if(b.error){var a=__svi18n.errorCode["S"+b.name];b.message&&(a+=b.message);setTimeout(function(){alert(a)},0);return!0}return!1},refreshServers:function(){function b(a){a=sparkConfig.servers.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),"servers","remove",c,null,"&id="+a)}function a(a){a=this.getValue(0);sparkConfig.editServer(a)}function c(d){sparkConfig.servers=
d;var c=new hi5.DataTable(d),f=new hi5.DataGrid(document.getElementById("servers.rows"));f.dataTable=c;f.open();document.getElementById("servers.type").value=d.type;document.getElementById("servers.display").checked=d.display;f.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&c.perform(a)};c.addEvent("beforeremove",b);c.addEvent("onaction",a)}sparkConfig.config(sparkConfig.getGatewayAddr(),"servers","get",c)},refreshServerGroups:function(){function b(a){a=sparkConfig.serverGroups.getValue(0);
sparkConfig.config(sparkConfig.getGatewayAddr(),"serverGroups","remove",c,null,"&name="+a)}function a(a){a=this.getValue(0);sparkConfig.editServerGroup(a)}function c(d){sparkConfig.serverGroups=d;var c=new hi5.DataTable(d);d=new hi5.DataGrid(document.getElementById("serverGroups.rows"));d.dataTable=c;d.open();d.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&c.perform(a)};c.addEvent("beforeremove",b);c.addEvent("onaction",a)}sparkConfig.config(sparkConfig.getGatewayAddr(),"serverGroups",
"get",c)},refreshUserGroups:function(){function b(a){a=sparkConfig.userGroups.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),"userGroups","remove",c,null,"&name="+a)}function a(a){a=this.getValue(0);sparkConfig.editUserGroup(a)}function c(c){sparkConfig.userGroups=c;var d=new hi5.DataTable(c);c=new hi5.DataGrid(document.getElementById("userGroups.rows"));c.dataTable=d;c.open();c.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&d.perform(a)};d.addEvent("beforeremove",b);
d.addEvent("onaction",a)}sparkConfig.config(sparkConfig.getGatewayAddr(),"userGroups","get",c)},editServerGroup:function(b){var a=document.getElementById("serverGroups.view");a.reset();var c=hi5.$("serverGroup.server"),d=new hi5.Lightbox(a);d.onclose=function(){c.hide();sparkConfig.refreshServerGroups()};sparkConfig.showMessage("");d.show();a._dataAction="post";b&&(a._dataAction="put",b={name:b,servers:sparkConfig.serverGroups.getValue(1)},hi5.browser.objToForm(b,a));c.hide||new hi5.Select(c,!0);
sparkConfig.servers||sparkConfig.refreshServers();c.beforedropdown=function(){sparkConfig.initServerList(c)}},editUserGroup:function(b){var a=document.getElementById("userGroups.view");a.reset();var c=hi5.$("userGroup.server"),d=hi5.$("userGroup.user"),e=new hi5.Lightbox(a);e.onclose=function(){c.hide();d.hide();sparkConfig.refreshUserGroups()};sparkConfig.showMessage("");e.show();a._dataAction="post";b&&(a._dataAction="put",b={name:b,users:sparkConfig.userGroups.getValue(1),servers:sparkConfig.userGroups.getValue(2)},
hi5.browser.objToForm(b,a));c.hide||new hi5.Select(c,!0);d.hide||new hi5.Select(d,!0);sparkConfig.serverGroups||sparkConfig.refreshServerGroups();sparkConfig.users||sparkConfig.refreshUsers();c.beforedropdown=function(){var a=c.options,b=sparkConfig.serverGroups;if(b)for(var b=b.rows,d=a.length=0,e=b.length;d<e;d++)a[d]=new Option(b[d][0])};d.beforedropdown=function(){var a=d.options,b=sparkConfig.users;if(b)for(var b=b.rows,c=a.length=0,e=b.length;c<e;c++)a[c]=new Option(b[c][0])}},saveServerGroup:function(){var b=
document.getElementById("serverGroups.view");sparkConfig.showMessage("");var a=hi5.browser.formToObj(b);if(a.servers){for(var c=a.servers.split(","),d=c.length,e=0;e<d;e++)c[e]=c[e].trim();a.servers=c}sparkConfig.config(sparkConfig.getGatewayAddr(),"serverGroup",b._dataAction||"put",function(a){a.error?sparkConfig.showMessage(a.message):(b.reset(),b._dataAction="post")},JSON.stringify(a));return!1},saveUserGroup:function(){var b=document.getElementById("userGroups.view");sparkConfig.showMessage("");
var a=hi5.browser.formToObj(b);if(a.servers){var c=a.servers.split(",");var d=c.length;for(var e=0;e<d;e++)c[e]=c[e].trim();a.servers=c}if(a.users){c=a.users.split(",");d=c.length;for(e=0;e<d;e++)c[e]=c[e].trim();a.users=c}sparkConfig.config(sparkConfig.getGatewayAddr(),"userGroup",b._dataAction||"put",function(a){a.error?sparkConfig.showMessage(a.message):(b.reset(),b._dataAction="post")},JSON.stringify(a));return!1},refreshUsers:function(){function b(a){a=sparkConfig.users.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),
"users","remove",c,null,"&name="+a)}function a(a){a=this.getValue(0);sparkConfig.editUser(a)}function c(c){sparkConfig.users=c;var d=new hi5.DataTable(c);c=new hi5.DataGrid(document.getElementById("users.rows"));c.dataTable=d;c.open();c.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&d.perform(a)};d.addEvent("beforeremove",b);d.addEvent("onaction",a)}sparkConfig.config(sparkConfig.getGatewayAddr(),"users","get",c)},refreshSessions:function(){function b(a){a=sparkConfig.sessions.getValue(0);
sparkConfig.config(sparkConfig.getGatewayAddr(),"sessions","remove",c,null,"&id="+a)}function a(a){a=this.getValue(0);var c="join";switch(this.getValue(9)){case "RFB":c="joinvnc";break;case "SSH":c="joinssh";break;case "TELNET":c="jointelnet"}a=location.protocol+"//"+document.getElementById("gateway").value+"/"+c+".html?id="+a;window.open(a)}function c(c){sparkConfig.sessions=c;var d=new hi5.DataTable(c),f=new hi5.DataGrid(document.getElementById("sessions.rows"));d.beforeGetValue=function(a,c){return"thumbnail"==
d.cols[a].name?'<img src="'+c+'">':c};f.dataTable=d;f.open();f.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&d.perform(a)};d.addEvent("beforeremove",b);d.addEvent("onaction",a);document.getElementById("sessions.size").innerHTML=c.rows.length}sparkConfig.config(sparkConfig.getGatewayAddr(),"sessions","get",c)},updateSymlink:function(){var b=document.getElementById("symlinkAccess"),a=document.getElementById("symlink.id"),c=document.getElementById("symlink.password"),d=document.getElementById("symlink.server"),
e=document.getElementById("gateway").value,a=location.protocol+"//"+e+"/rdpdirect.html?symlink="+a.value+"&gateway="+e;c.value&&(a+="&pwd="+c.value);d.value&&(c=sparkConfig.servers.find(0,d.value))&&c[3]&&(a+="&startProgram=app");b.href=a},refreshSymlinks:function(){function b(a){a=sparkConfig.symlinks.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),"symlinks","remove",c,null,"&id="+a)}function a(a){a=this.getValue(0);sparkConfig.editSymlink(a)}function c(c){sparkConfig.symlinks=c;var d=
new hi5.DataTable(c);c=new hi5.DataGrid(document.getElementById("symlinks.rows"));c.dataTable=d;d.beforeGetValue=function(a,c){var b=d.cols[a].name;return"validFrom"==b||"validTo"==b?hi5.DateUtils.formatDate(c,!0):c};d.beforeSetValue=function(a,c){var b=d.cols[a].name;return"validFrom"==b||"validTo"==b?hi5.DateUtils.parseDate(c).getTime():c};c.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&d.perform(a)};c.open();d.addEvent("beforeremove",b);d.addEvent("onaction",a);c=document.getElementById("symlink.id");
var f=document.getElementById("symlink.password"),g=document.getElementById("symlink.server");f.onchange=c.onchange=g.onchange=sparkConfig.updateSymlink}sparkConfig.config(sparkConfig.getGatewayAddr(),"symlinks","get",c)},initUI:function(){function b(){var b="&sType="+a.value+"&display="+c.checked;sparkConfig.config(sparkConfig.getGatewayAddr(),"servers_h","put",function(){},null,b)}var a=document.getElementById("servers.type"),c=document.getElementById("servers.display");a.onchange=b;c.onchange=
b;document.getElementById("conf3").addEvent("ontabchange",function(a){sparkConfig.gateway.prop.webfeed&&(document.getElementById("servers.add").style.disabled=!0,document.getElementById("users.add").style.disabled=!0);switch(a){case 1:if(sparkConfig.servers)break;sparkConfig.refreshServers();break;case 2:if(sparkConfig.users)break;sparkConfig.refreshUsers();break;case 3:sparkConfig.servers||sparkConfig.refreshServers();if(sparkConfig.symlinks)break;sparkConfig.refreshSymlinks();break;case 4:if(sparkConfig.sessions)break;
sparkConfig.refreshSessions();break;case 5:sparkConfig.refreshServerGroups();break;case 6:sparkConfig.refreshUserGroups()}});var d=hi5.tool.queryToObj(),e=d.port,d=d.expect;if(e){var f=window.location.host,g=location.protocol;f||(f="localhost");document.getElementById("gateway").value=f;f=g+"//"+f;d&&(d=f+":"+d,document.getElementById("expectAddr").innerHTML=d,document.getElementById("expect").style.display="inline");if("http:"==g&&"80"!=e||"https:"==g&&"443"!=e)f+=":"+e;f="<a href='"+f+"'>"+f+"</a>";
document.getElementById("sparkAddr").innerHTML=f;document.getElementById("conf1").style.display="block"}else document.getElementById("gateway").value=location.host,document.getElementById("conf0").style.display="block";if(e=document.getElementById("rfxOpt"))e.onchange=function(a){a.target.checked&&(document.getElementById("colorOpt").selectedIndex=3)}},getGatewayAddr:function(){return("http:"==location.protocol?"ws:":"wss:")+"//"+document.getElementById("gateway").value},getAll:function(){sparkConfig.config(sparkConfig.getGatewayAddr(),
"gateway","get",function(b){if(!sparkConfig.checkError(b)){sparkConfig.gateway=b;b=b.prop;var a,c=document.getElementById("frmGateway").elements,d;for(d in b)if(a=c[d]){var e=a.type,f=b[d];"checkbox"==e?a.checked="true"===f:"file"!=e&&(a.value=f)}document.getElementById("conf3").style.display="block"}})},saveGateway:function(){function b(a){if(a.error){var c=__svi18n.errorCode["S"+a.name];a.message&&(c+=a.message)}else c=a.restart?__svi18n.info.restart:__svi18n.info.succeeded||"Operation succeeded.";
c&&hi5.notifications.notify(c)}(function(a,c,b){a=a.elements;for(var d=0,f=a.length;d<f;d++){var g=a[d];if(g){var k=g.value;if(""!==k&&!g.readonly){var l=g.type;"button"!=l&&"submit"!=l&&"file"!=l&&(c[g.name]="checkbox"==l?g.checked+"":k)}}}a=document.getElementById("licenseFile").files;0<a.length?hi5.file.readAsArrayBuffer(a[0],function(a){c.licenseFile=hi5.Base64.enc(a);b()}):b()})(document.getElementById("frmGateway"),sparkConfig.gateway.prop,function(){sparkConfig.config(sparkConfig.getGatewayAddr(),
"gateway","put",b,JSON.stringify(sparkConfig.gateway))})},editServer:function(b,a){function c(c){if(c.id){var b=c.rdp;b||(b={});b.isRDP=!!c.rdp;b.id=c.id;b.displayName=c.displayName;c.server&&(b.server=c.server);c.icon&&(b.icon=c.icon);if(b.mapDisk&&b.disks){for(var g=b.disks,k,l=Math.min(3,g.length),h=0;h<l;h++)b["dosName"+h]=g[h].dosName,b["devicePath"+h]=g[h].devicePath,k=g[h].actions,b["actRedirect"+h]=0!=(k&1),b["actDownload"+h]=0!=(k&2),b["actUpload"+h]=0!=(k&4);delete b.disks}if(c.vnc){g=c.vnc;
b["vnc.port"]="";b["vnc.password"]="";b.UseCopyRect=!1;b.share=!1;b["vnc.mapClipboard"]=!1;b["vnc.recording"]=0;for(h in g)"port"==h||"password"==h||"mapClipboard"==h||"color"==h||"sessionRecord"==h?b["vnc."+h]=g[h]:b[h]=g[h];b.isVNC=!0}if(c.ssh){g=c.ssh;b["ssh.mapClipboard"]=!1;b["ssh.fontSize"]="";b["ssh.port"]="";b["ssh.username"]="";b["ssh.recording"]=0;for(h in g)b["ssh."+h]=g[h];b.isSSH=!0}if(c.telnet){c=c.telnet;b["telnet.mapClipboard"]=!1;b["telnet.fontSize"]="";b["telnet.port"]="";b["telnet.recording"]=
0;for(h in c)b["telnet."+h]=c[h];b.isTELNET=!0}e=hi5.$("server.id").value;f=hi5.$("server.displayName").value;d.reset();hi5.browser.objToForm(b,d);a||(d._dataAction="put");e&&(hi5.$("server.id").value=e);f&&(hi5.$("server.displayName").value=f)}}var d=document.getElementById("servers.view"),e="",f="";a||d.reset();var g=d.visible?d:new hi5.Lightbox(d);g.onclose=function(){sparkConfig.refreshServers()};sparkConfig.showMessage("");g.visible()||g.show();d._dataAction="post";b&&sparkConfig.config(sparkConfig.getGatewayAddr(),
"server","get",c,null,"&id="+b);var k=hi5.$("server.server");k.hide||new hi5.Select(k);k.beforedropdown=function(){for(var a=k.options,b=sparkConfig.servers.rows,c=a.length=0,d=b.length;c<d;c++)a[c]=new Option(b[c][1],b[c][0])};k.onchange=function(){var a=k.value;sparkConfig.config(sparkConfig.getGatewayAddr(),"server","get",c,null,"&id="+a)}},initServerList:function(b){b=b.options;var a=sparkConfig.servers;if(a)for(var a=a.rows,c=b.length=0,d=a.length;c<d;c++)b[c]=new Option(a[c][1],a[c][0])},editUser:function(b){var a=
document.getElementById("users.view");a.reset();var c=hi5.$("user.server"),d=new hi5.Lightbox(a);d.onclose=function(){c.hide();sparkConfig.refreshUsers()};sparkConfig.showMessage("");d.show();a._dataAction="post";b&&(a._dataAction="put",b={name:b,password:sparkConfig.users.getValue(1),servers:sparkConfig.users.getValue(2),isDomainUser:sparkConfig.users.getValue(3),domainServer:sparkConfig.users.getValue(4),transferCredential:sparkConfig.users.getValue(5)},hi5.browser.objToForm(b,a));c.hide||new hi5.Select(c,
!0);sparkConfig.servers||sparkConfig.refreshServers();c.beforedropdown=function(){sparkConfig.initServerList(c)}},importUsers:function(){var b=hi5.$("adUser").value,a=hi5.$("adPwd").value,c=hi5.$("adDomain").value,d=hi5.$("adServer").value,e=hi5.$("adOU").value,f=hi5.$("adServers"),g=hi5.$("secProtocol").value;(f=f?f.value:"")&&(f="&servers="+encodeURIComponent(f));b&&a?sparkConfig.config(sparkConfig.getGatewayAddr(),"users","import",function(a){sparkConfig.checkError(a)||sparkConfig.refreshUsers()},
null,"&user="+encodeURIComponent(b)+"&pwd="+encodeURIComponent(a)+"&domain="+encodeURIComponent(c)+"&server="+d+"&ou="+encodeURIComponent(e)+f+"&secProtocol="+g):alert("Please enter credentials.")},saveServer:function(){var b=document.getElementById("servers.view");sparkConfig.showMessage("");var a=hi5.browser.formToObj(b);if(a.mapDisk){var c=0,d=[];a.dosName0&&(a.actRedirect0&&(c|=1),a.actDownload0&&(c|=2),a.actUpload0&&(c|=4),d.push({dosName:a.dosName0,devicePath:a.devicePath0,actions:c}),delete a.dosName0,
delete a.devicePath0);a.dosName1&&(c=0,a.actRedirect1&&(c|=1),d.push({dosName:a.dosName1,devicePath:a.devicePath1,actions:c}),delete a.dosName1,delete a.devicePath1);a.dosName2&&(c=0,a.actRedirect2&&(c|=1),d.push({dosName:a.dosName2,devicePath:a.devicePath2,actions:c}),delete a.dosName2,delete a.devicePath2);0<d.length&&(a.disks=d)}c={};c.id=a.id;c.displayName=a.displayName;a.server&&(c.server=a.server);a.icon&&(c.icon=a.icon);a.isRDP&&(c.rdp=a);a.isVNC&&(c.vnc={port:a["vnc.port"],password:a["vnc.password"],
encoding:a.encoding,quality:a.quality,compression:a.compression,color:a["vnc.color"],UseCopyRect:a.UseCopyRect,share:a.share,sessionRecord:a["vnc.sessionRecord"],mapClipboard:a["vnc.mapClipboard"]});a.isSSH&&(c.ssh={mapClipboard:a["ssh.mapClipboard"],fontSize:a["ssh.fontSize"],port:a["ssh.port"],username:a["ssh.username"],sessionRecord:a["ssh.sessionRecord"],password:a["ssh.password"],keyfile:a["ssh.keyfile"],keyfilePwd:a["ssh.keyfilePwd"],terminalType:a["ssh.terminalType"]||"xterm"});a.isTELNET&&
(c.telnet={mapClipboard:a["telnet.mapClipboard"],fontSize:a["telnet.fontSize"],sessionRecord:a["telnet.sessionRecord"],port:a["telnet.port"]});sparkConfig.config(sparkConfig.getGatewayAddr(),"server",b._dataAction||"put",function(a){a.error?sparkConfig.showMessage(a.message):(b.reset(),b._dataAction="post",sparkConfig.gateway.server||sparkConfig.getAll())},JSON.stringify(c));return!1},saveUser:function(){var b=document.getElementById("users.view");sparkConfig.showMessage("");var a=hi5.browser.formToObj(b);
if(a.servers){for(var c=a.servers.split(","),d=c.length,e=0;e<d;e++)c[e]=c[e].trim();a.servers=c}sparkConfig.config(sparkConfig.getGatewayAddr(),"user",b._dataAction||"put",function(a){a.error?sparkConfig.showMessage(a.message):(b.reset(),b._dataAction="post",sparkConfig.gateway.user||sparkConfig.getAll())},JSON.stringify(a));return!1},editSymlink:function(b){var a=document.getElementById("symlinks.view");a.reset();var c=new hi5.Lightbox(a);c.onclose=function(){sparkConfig.refreshSymlinks()};sparkConfig.showMessage("");
c.show();a._dataAction="post";b?(a._dataAction="put",hi5.browser.objToForm(sparkConfig.symlinks.getObject(),a)):document.getElementById("symlink.id").value=hi5.tool.uuid();document.getElementById("symlink.id").onchange();var d=hi5.$("symlink.server");d.hide||new hi5.Select(d);sparkConfig.servers||sparkConfig.refreshServers();d.beforedropdown=function(){sparkConfig.initServerList(d)};sparkConfig.updateSymlink()},saveSymlink:function(){var b=document.getElementById("symlinks.view");sparkConfig.showMessage("");
var a=hi5.browser.formToObj(b);a.validFrom&&(a.validFrom=hi5.DateUtils.parseDate(a.validFrom).getTime());a.validTo&&(a.validTo=hi5.DateUtils.parseDate(a.validTo).getTime());sparkConfig.config(sparkConfig.getGatewayAddr(),"symlink",b._dataAction||"put",function(a){a.error?sparkConfig.showMessage(a.message):(b.reset(),b._dataAction="post",document.getElementById("symlink.id").value=hi5.tool.uuid())},JSON.stringify(a));return!1},notify:function(b,a){sparkConfig.config(sparkConfig.getGatewayAddr(),"sessions",
"notify",null,null,"&msg="+b+"&sendTo="+(a||[]).join(","))}};window.addEventListener("load",sparkConfig.initUI,!1);
