var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(b,e,f){if(null==b)throw new TypeError("The 'this' value for String.prototype."+f+" must not be null or undefined");if(e instanceof RegExp)throw new TypeError("First argument to String.prototype."+f+" must not be a regular expression");return b+""};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,f){b!=Array.prototype&&b!=Object.prototype&&(b[e]=f.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,e,f,a){if(e){f=$jscomp.global;b=b.split(".");for(a=0;a<b.length-1;a++){var c=b[a];c in f||(f[c]={});f=f[c]}b=b[b.length-1];a=f[b];e=e(a);e!=a&&null!=e&&$jscomp.defineProperty(f,b,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("String.prototype.startsWith",function(b){return b?b:function(b,f){var a=$jscomp.checkStringArgs(this,b,"startsWith");b+="";for(var c=a.length,g=b.length,h=Math.max(0,Math.min(f|0,a.length)),l=0;l<g&&h<c;)if(a[h++]!=b[l++])return!1;return l>=g}},"es6-impl","es3");
function showTwoFAQR(b,e){var f=hi5.$("twofainfo");if(f){var a=hi5.$("barcodeDiv"),c=hi5.$("enableTwoFA"),g=hi5.$("disableTwoFA");e?(hi5.$("imgBarcode").src="data:image/png;base64,"+e,a.style.display="block",g.style.display="none",c.style.display="block"):(a.style.display="none",g.style.display="block",c.style.display="none");var h=new hi5.ui.Lightbox(f);h.show();hi5.$("faCode").focus();hi5.$("faCode").value="";c.onclick=g.onclick=function(a){var d=hi5.$("faCode").value;a=a.target==c?1:0;6!=d.length?
hi5.notifications.notify(__svi18n.info.digit6||"It must be a 6 digit number"):(b(d,a),h.dismiss())}}}
svGlobal.auth=new function(){function b(a){hi5.tool.enableInput();if(a.error)svGlobal.gatewayError(a.name,a.message);else{hi5.$("frmLogin").style.display="none";hi5.$("frmConn").style.display="block";for(var g=hi5.$("programs");g.hasChildNodes();)g.removeChild(g.firstChild);var c=a.servers;if(!a.accessNotInList){var d=hi5.$("anyconn");d&&(d.style.display="none")}d=svGlobal.auth.getUserName(hi5.$("user").value);window.__sparkUser={session:a.session,account:d,gateway:hi5.$("gateway").value,servers:c,
twoFA:a.twoFA,twoFAEnabled:a.twoFAEnabled,twoFAQR:a.twoFAQR};a=c.length;if(!(1>a)){for(var d="",b=0;b<a;b++){var r=c[b].server,k=c[b].id,r=c[b].displayName||k||r,n=c[b].icon;n||(n="rdp32.png");var q=document.createElement("div");q.className="icon";var p=document.createElement("img");p.src=n;p.id=k;p.alt=k;p.title=r;p.style.cursor="pointer";p.onclick=e;q.appendChild(p);q.appendChild(document.createElement("br"));q.appendChild(document.createTextNode(r));g.appendChild(q);hi5.appcfg.startup&&k===hi5.appcfg.startup.server&&
(d=k)}!d&&hi5.appcfg.startup&&(console.log("start up:"+hi5.appcfg.startup.server+" not found, use the first instead"),d=c[0].id);d&&f(d,!hi5.appcfg.startup.newWindow,!0)}}}function e(a){var g=a.target;g.onclick=null;setTimeout(function(){g.onclick=e},300);f(g.id)}function f(a,b,f){var d=window.__sparkUser,g=d.servers,l=g.length;d.server=null;window.sparkGateway=d.gateway;for(var k=0;k<l;k++){var n=g[k];if(a==n.id){n.gateway=d.gateway;n.session=d.session;n.account=d.account;d.server=n;break}}if(d.server){console.log("connecting to:"+
d.server.id);(a=hi5.$("touchpad"))&&a.checked&&(d.server.touchpad=!0);if(a=hi5.$("keyboard"))a=parseInt(a.options[a.selectedIndex].value),0<a&&(d.server.keyboard=a);if(svGlobal.auth.onconnect)svGlobal.auth.onconnect(d.server);a=d.server.rdp&&("app"==d.server.startProgram||d.server.rdp.remoteProgram);void 0==b&&(b=a);if(b){var e=svManager.getInstance();if(a&&e&&e.running())e.startApp(d.server.exe||d.server.rdp.remoteProgram,d.server.args||d.server.rdp.remoteArgs,""),c&&c.visible()&&c.dismiss();else{var h=
function(a){function d(){null==c&&(c=new hi5.ui.Lightbox(hi5.$("login")));c.visible()?c.dismiss():c.show()}var b=a.toolbar.querySelector("#__sv_btn_home");b||(b=a.toolbar.addButton(hi5.appcfg.img.home||"home.png",d),b.id="__sv_btn_home")},e=new Rdp2(d.server);hi5.$("login").style.display="none";var m=new svGlobal.LocalInterface;m.onremoteappicon=function(a,d){if(m.toolbar&&a.isMainWin()&&32==d.getWidth()){var b="win"+a.id;if(!m.toolbar.querySelector("#"+b)){h(m);var c=m.toolbar.addButton(d.getDataURL(),
function(){a.activate(1)});c.id=b;c.title=a.titleInfo;c.style.width="32px";c.style.height="32px";c.addEventListener("mouseover",function(){c.title=a.titleInfo},!1);setTimeout(function(){a.activate(1)},333)}}};m.onremoteappclose=function(a){m.toolbar&&(a=m.toolbar.querySelector("#win"+a.id))&&m.toolbar.removeChild(a)};e.addSurface(m);e.run();e.onclose=function(){if(f){window.__sparkUser=null;var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none"}else e.hide(),
hi5.$("login").style.display="block"}}}else b=document.getElementById("multiMon"),d.server.rdp?(b&&b.checked&&(d.server.rdp.multiMon="on"),window.open("rdpdirect.html")):d.server.vnc?window.open("vnc.html"):d.server.ssh?window.open("sshdirect.html"):d.server.telnet&&window.open("telnet.html")}else hi5.notifications.notify("Not a valid server")}var a=this,c=null;this.getLoginURL=function(){return("https:"==location.protocol?"wss://":"ws://")+hi5.$("gateway").value+"/LOGIN?"};this.showLogDlg=function(){window.__sparkUser=
null;var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none";(a=svManager.getInstance())&&a.running()&&a.close()};this.getUserName=function(a){hi5.appcfg&&hi5.appcfg.domain&&(a.toLowerCase().startsWith(hi5.appcfg.domain.toLowerCase()+"\\")||(a=hi5.appcfg.domain+"\\"+a));return a};this.login=function(c){function e(d,b){window.__sparkUser=null;if(!a.beforelogin||!a.beforelogin(d)){hi5.tool.disableInput();var c=new WebSocket(d.substring(0,d.indexOf("?"))+
"?_METHOD=post","login");c.onclose=function(d){g||(hi5.notifications.notify(__svi18n.errorCode.connection),a.showLogDlg());hi5.tool.enableInput();a.afterlogin&&a.afterlogin(g);g=!1};c.onopen=function(a){g=!0};c.onmessage=function(a){var e=a.data,g=e.substring(0,2);if("00"==g)c.send("00"+d.substring(d.indexOf("?")+1));else if("01"==g)switch(hi5.tool.enableInput(),e.substring(2,3)){case "0":if(a=hi5.$("twofacode")){var f=new hi5.ui.Lightbox(a);f.show();a=hi5.$("btnTwoFACode");var k=hi5.$("faAuthCode");
k.focus();k.value="";a.onclick=function(){c.send("code:"+k.value);f.dismiss()}}break;case "1":a=e.substring(4),showTwoFAQR(function(a,d){c.send("code:"+a)},a)}else a=JSON.parse(a.data),0===a.type&&(a.message||a.name)?svGlobal.gatewayError(a.name,a.message):(a.error||c.send("A1"+navigator.userAgent),b(a))}}}var g=!1,d=hi5.browser.cookie2Obj();d.svSession&&d.svEmail&&(c+="&svSession="+d.svSession+"&svEmail="+encodeURIComponent(d.svEmail));setTimeout(function(){e(c,b)},5);return!1}};
window.addEventListener("load",function(b){function e(){b.preventDefault();svGlobal.auth.beforesubmit&&svGlobal.auth.beforesubmit();var a=hi5.$("frmLogin").elements,c=svGlobal.auth.getUserName(a.user.value),e=a.pwd.value,c=svGlobal.auth.getLoginURL()+"user="+encodeURIComponent(c)+"&pwd="+encodeURIComponent(e);(a=a.sharedSecret)&&a.value&&(c+="&sharedSecret="+encodeURIComponent(a.value));return svGlobal.auth.login(c)}function f(a,c){var b=svGlobal.auth.getLoginURL()+"action=code",e=new WebSocket(b,
"login");e.onmessage=function(a){a=JSON.parse(a.data);a.error?svGlobal.gatewayError(a.name,a.message):hi5.notifications.notify(__svi18n.info.succeeded);e.close()};e.onopen=function(b){e.send("twof:"+a+"\t"+__sparkUser.account+"\t"+c+"\t"+__sparkUser.session)}}(function(){hi5.$("user").focus();hi5.$("frmLogin").onsubmit=e;var a=hi5.$("anyconn");a&&(a.onclick=function(){window.open("rdp.html?gateway="+hi5.$("gateway").value)});if(a=document.querySelector('input[name="showlogin"]'))a.onclick=svGlobal.auth.showLogDlg;
var a=hi5.browser.cookie2Obj(),c=-1!=document.cookie.indexOf("__SV_TOKEN_A"),b=hi5.tool.queryToObj();if(a.svEmail||a.user||c||b.autoLogin){var h=hi5.$("frmLogin").elements;h.user.value=a.svEmail||a.user||"";h.pwd.value=(a.svSession?"fake":a.pwd)||"_";a.gateway&&(h.gateway.value=a.gateway);(h.user.value&&h.pwd.value||a.autoLogin||c||b.autoLogin)&&setTimeout(e,30)}var a=hi5.$("settings"),l=hi5.$("settingsDiv");a&&(a.onclick=function(){if(l){(new hi5.ui.Lightbox(l)).show();hi5.$("currPwd").focus();var a=
hi5.$("btnTwoFA");a&&(a.onclick=function(){showTwoFAQR(f,window.__sparkUser.twoFAQR)},0==__sparkUser.twoFA&&a.parentNode.removeChild(a))}});if(a=hi5.$("frmSettings"))a.onsubmit=function(a){a.preventDefault();var b=a.target.elements;if(b.newPwd1.value!=b.newPwd2.value)hi5.notifications.notify(__svi18n.errorCode.pwdmatch);else{a=svGlobal.auth.getLoginURL()+"_METHOD=post&action=put";var c=new WebSocket(a,"login");c.onmessage=function(a){0==a.data.indexOf("00")?(c.send("00currPwd="+encodeURIComponent(b.currPwd.value)+
"&newPwd="+encodeURIComponent(b.newPwd1.value)+"&user="+encodeURIComponent(svGlobal.auth.getUserName(hi5.$("user").value))),hi5.$("frmSettings").reset()):(a=JSON.parse(a.data),a.error&&svGlobal.gatewayError(a.name,a.message))};l.dismiss&&l.dismiss();return!1}};a=hi5.$("gateway");(c=a.value)||(c=hi5.appcfg.defaultPort?window.location.hostname+":"+hi5.appcfg.defaultPort:window.location.host);0==c.length&&(c="localhost");a.value=c;a=hi5.$("touchpadmode");hi5.browser.isTouch&&(a.style.display="");(a=
hi5.$("user"))&&!a.value&&hi5.appcfg&&hi5.appcfg.domain&&!hi5.appcfg.hiddenDomain&&(a.value=hi5.appcfg.domain+"\\");(function(){var a=!1,b="";try{document.createElement("canvas").getContext("2d"),a=!0}catch(q){b="This browser does not support Canvas.\n\n"}var c=!("WebSocket"in window)&&!("MozWebSocket"in window),e=navigator.userAgent,f=-1!=e.indexOf("Firefox");c&&(b+="This browser doesn't support WebSocket.\n\n",f?b+="Please update to Firefox 6 or later.\n\n":-1!=e.indexOf("Opera")?b+="Please open 'opera:config#Enable WebSockets' (type it in the link field) make 'Enable WebSockets' selected and restart Opera.\n\n":
-1!=e.indexOf("MSIE")&&(b+="Please install Google Chrome Frame.\n\n"));0<b.length&&hi5.notifications.notify(b);return!c&&a})();(a=hi5.$("defPort"))&&hi5.appcfg.defaultPort&&(a.innerHTML=hi5.appcfg.defaultPort);(a=document.getElementById("frmConn"))&&(a=a.querySelector('select[name="keyboard"]'));a&&(c=svGlobal.Rdp.languageToKeyboard.detect())&&(a.value=c)})()},!1);
