var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(g,m,n){if(null==g)throw new TypeError("The 'this' value for String.prototype."+n+" must not be null or undefined");if(m instanceof RegExp)throw new TypeError("First argument to String.prototype."+n+" must not be a regular expression");return g+""};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(g,m,n){g!=Array.prototype&&g!=Object.prototype&&(g[m]=n.value)};
$jscomp.getGlobal=function(g){return"undefined"!=typeof window&&window===g?g:"undefined"!=typeof global&&null!=global?global:g};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(g,m,n,v){if(m){n=$jscomp.global;g=g.split(".");for(v=0;v<g.length-1;v++){var L=g[v];L in n||(n[L]={});n=n[L]}g=g[g.length-1];v=n[g];m=m(v);m!=v&&null!=m&&$jscomp.defineProperty(n,g,{configurable:!0,writable:!0,value:m})}};
$jscomp.polyfill("String.prototype.startsWith",function(g){return g?g:function(g,n){var m=$jscomp.checkStringArgs(this,g,"startsWith");g+="";for(var L=m.length,ga=g.length,sa=Math.max(0,Math.min(n|0,m.length)),da=0;da<ga&&sa<L;)if(m[sa++]!=g[da++])return!1;return da>=ga}},"es6-impl","es3");
$jscomp.polyfill("Array.prototype.fill",function(g){return g?g:function(g,n,v){var m=this.length||0;0>n&&(n=Math.max(0,m+n));if(null==v||v>m)v=m;v=Number(v);0>v&&(v=Math.max(0,m+v));for(n=Number(n||0);n<v;n++)this[n]=g;return this}},"es6-impl","es3");var svManager={getInstance:function(){var g=window.$ssh;return g&&g.running&&g.running()?g:null}};
function connvertServer(g){var m={};m.id=g.id;m.server=g.id;m.displayName=g.displayName||g.id;if(g=g.ssh){for(var n in g)m[n]=g[n];m.user=g.username||"";m.pwd=g.password||""}return m}
svGlobal.SSH=function(g,m,n,v){function L(a){return"on"==a||"true"==a||1==a}function ga(){var a=g.indexOf("://"),b=g.substring(a+3),a=b.indexOf("/");0<a&&(b=b.substring(0,a));return location.protocol+"//"+b}function sa(a){return ta?hi5.browser.httpGet(ga()+"/CLIP?s="+ta+"&t="+(new Date).getTime(),!1):""}function da(a,b){b&&(H=b);a&&(O=a,ua=(O-1)*h);Ja=1==H&&O==Math.floor(n/h)}function va(a,b,c,d){var e=a,g=b;d=d||Math.floor(g/h);b=c||Math.floor(e/t);a=null;c&&(e=M*t,g=P*h);y&&(a=k.getImageData(0,
0,Math.min(b*t,F),Math.min(d*h,P*h)));m=e;n=g;c=m;e=n;u.setSize(c,e);R.width=c;R.height=e;k.textBaseline="top";c=l.fontFamily||"Courier New";0<c.indexOf(" ")&&(c="'"+c+"'");k.font=l.fontSize+"px "+c;wa();a&&k.putImageData(a,0,0);P=d;M=b;F=M*t;da(Math.floor(n/h));z=new Ka(M,P);if(f.onresolutionchange)f.onresolutionchange(m,n)}function Ca(a){q.send(a)}function La(a,b,c){this.need=a;this.handler=b;this.repeat=c||1}function gb(a){S=new RecordingManager;S.setHeader({name:0<a.user.length?a.server+"_"+a.user:
a.server,width:a.width,height:a.height,color:a.fontSize,namesuffix:".sshv",filetag:"SSHV",duration:0})}function hb(a,b){var c=0,d=!1;this.width=a;this.interval=b;var e=0;this.start=function(){d||(d=!0,c=setInterval(function(){if(u&&y){var b=u.getThumbnail(a);b&&b.length!=e&&(q.send("8E7"+b),e=b.length)}},b))};this.stop=function(){clearInterval(c)}}function ib(a,b){!Q||Q.width==a&&Q.interval==b||(Q.stop(),Q=null);Q||(Q=new hb(a,b));Q.start()}function jb(a){y&&q.send("5D"+a.join("\t"));A=null}function Ma(){if(A){var a=
A.answer.length;a<A.prompt.length?(V(A.prompt[a]),Z(),ha()):(q.send("5D"+A.answer.join("\t")),A=null)}}function kb(a){y&&q.send("5B"+a)}function lb(a){var b=parseInt(a.substring(0,1),16),c=a.substring(1);a=!1;var d=f.sessionInfo.appInfo;switch(b){case 1:var e=JSON.parse(c);f.onsessionjoin&&(a=f.onsessionjoin(e));if(a)break;f.showMessage(__svi18n.info.joinsession.applyArgs([e.numericId,e.__ip,e.name]));break;case 2:e=JSON.parse(c);f.onsessionexit&&(a=f.onsessionexit(e));if(a)break;f.showMessage(__svi18n.info.exitsession.applyArgs([e.numericId,
e.__ip,e.name]));break;case 3:e=JSON.parse(c);d.joinMode!=e.mode&&(d.joinMode=e.mode,b=hi5.$("joinSelect"))&&(b.value=e.mode);if(d.hasControl)break;u.setReadOnly(!1);if(b=hi5.$("requestControl"))b.disabled=!0;f.ongivecontrol&&(a=f.ongivecontrol());if(a)break;f.showMessage(__svi18n.info.givecontrol);break;case 4:u.setReadOnly(!0);d.hasControl=!1;if(b=hi5.$("requestControl"))b.disabled=!1;f.ontakebackcontrol&&(a=f.ontakebackcontrol());if(a)break;f.showMessage(__svi18n.info.nocontrol);break;case 5:e=
JSON.parse(c);f.onrequirecontrol&&(a=f.onrequirecontrol(e));if(a)break;a=__svi18n.info.title.applyArgs([e.name,e.numericId,e.__ip]);f.showMessage({title:a,msg:__svi18n.info.recontrol,cbYes:function(){f.giveControl(e.numericId);this.destroy()},cbNo:function(){f.refuseControl(e.numericId);this.destroy()}});break;case 6:u.setTouchRemoting(!0);break;case 7:e=JSON.parse(c);e.width&&e.height&&va(0,0,e.cols,e.rows);break;case 8:e=JSON.parse(c);if(f.onrequestcredential&&f.onrequestcredential(e))break;u.requestCredential(e);
break;case 9:e=JSON.parse(c);0<e.interval&&0<e.width?ib(e.width,e.interval):Q&&(Q.stop(),Q=null);break;case 11:e=JSON.parse(c);f.onrequirejoin&&(a=f.onrequirejoin(e));if(a)break;a=__svi18n.info.title.applyArgs([e.name,e.numericId,e.__ip]);f.showMessage({title:a,msg:__svi18n.info.reqjoin,cbYes:function(){f.allowJoin(e.numericId,!0);this.destroy()},cbNo:function(){f.allowJoin(e.numericId,!1);this.destroy()}});break;case 12:Na=!0}}function mb(a){var b=w.page&&w.page.join||"";if(b.startsWith("http://")||
b.startsWith("https://"))return b;if(b.startsWith("/"))return location.origin+b;var c=location.href,d=c.lastIndexOf("/");if(b)return c.substring(0,d+1)+b;b=ga();c.toLowerCase().startsWith(b.toLowerCase())&&(b=c.substring(0,d));return b+"/"+a}function ia(a){ma.style.display=a?"none":"block"}function nb(a){svGlobal.logger.info("opened...");y=!0;q.send("87"+navigator.userAgent);if(f.onopen)f.onopen()}function ob(a){svGlobal.logger.warn(a)}function xa(a){svGlobal.logger.warn("closed ...");ia(!0);if(!y&&
((a=__svi18n.errorCode.connection)||(a="error connection"),f)){if(f.onerror)f.onerror({name:"connection",message:a});f.showMessage(a);0<svGlobal.log&&console.error(a)}na=y=!1;if(f&&f.onclose)f.onclose(Na);try{null!=S&&(S.exit(),S=null),u&&u.close()}catch(b){}ea&&(ea.release(),ea=null);R=k=null;q&&(q.onopen=null,q.onmessage=null,q.onclose=null,q=q.onerror=null);u=I=null;f&&(f=null);window&&window.$ssh&&(window.$ssh=null);null!=S&&(S.exit(),S=null)}function Oa(){10>l.fontSize&&(l.fontSize=10);13>l.fontSize?
h=l.fontSize+6:12<l.fontSize&&19>l.fontSize?h=l.fontSize+8:18<l.fontSize&&25>l.fontSize?h=l.fontSize+12:24<l.fontSize&&(h=l.fontSize+16);l.lineHeight&&(h=parseInt(l.lineHeight));Pa=(h-l.fontSize)/2|0;k.textBaseline="top";var a=l.fontFamily||"Courier New";0<a.indexOf(" ")&&(a="'"+a+"'");k.font=l.fontSize+"px "+a;t=k.measureText("X").width;P=parseInt(n/h);M=parseInt(m/t);F=M*t;da(parseInt(n/h));z=new Ka(M,P)}function Da(){wa();r=p=0;Oa();ma.style.width=t+"px";ma.style.height=h+"px";na=!0}function Z(){Qa||
Ra.drawImage(R,0,0)}function Sa(a){switch(a){case 0:break;case 5:break;case 7:break;case 8:Ea();break;case 9:a=p/t/8;a=parseInt(a)+1;p=8*a*t;ja();break;case 10:r+=h;ja(!0);break;case 11:r+=h;ja(void 0);break;case 12:break;case 13:Ta();break;case 14:break;case 15:break;default:console.log("Unknown C0 control:"+a)}}function pb(a){var b=a.getPosition();if(!T.parse(a))return a.setPosition(b-2),!1;a=T.count;b=T.parameters;switch(T.command){case 64:0==a&&(b[0]=1);a=b[0];for(var b="",c=a*t,d=k.getImageData(p,
r,F-p-c,h),e=0;e<a;e++)b+=" ";V(b);p-=c;k.putImageData(d,p+c,r);z.insertSpace(a,J(),G());break;case 65:0==a&&(b[0]=1);r-=(b[0]||1)*h;break;case 66:0==a&&(b[0]=1);r+=(b[0]||1)*h;break;case 67:0==a&&(b[0]=1);p+=(b[0]||1)*t;break;case 68:0==a&&(b[0]=1);p-=(b[0]||1)*t;break;case 69:0==a&&(b[0]=1);r+=b[0]*h;p=0;break;case 70:0==a&&(b[0]=1);r-=b[0]*h;p=0;break;case 71:0==a&&(b[0]=1);ya(0,b[0]);break;case 72:case 102:0==a&&(b[0]=b[1]=1);ya(b[0]||1,b[1]||1);break;case 74:a||(b[0]=0);switch(b[0]){case 0:k.fillStyle=
E;k.fillRect(p,r,F-p,P*h-r);k.fillStyle=C;z.clearEOS(J(),G());break;case 1:k.fillStyle=E;k.fillRect(0,0,p,r);k.fillStyle=C;z.clearBOS(J(),G());break;case 2:wa();r=p=0;z.cleanScreen();break;case 3:wa();r=p=0;z.cleanScreen();break;default:console.log("invalid CSI J:"+b[0])}break;case 75:a||(b[0]=0);switch(b[0]){case 0:Ua();break;case 1:k.fillStyle=E;k.fillRect(0,r,p,h);k.fillStyle=C;z.clearBOL(J(),G());break;case 2:k.fillStyle=E;k.fillRect(0,r,F,h);k.fillStyle=C;z.clearLine(G());break;default:console.log("invalid CSI K:"+
b[0])}break;case 76:case 84:a||(b[0]=1);Va(b[0]);break;case 77:case 83:a||(b[0]=1);Wa(b[0]);break;case 80:a||(b[0]=1);a=b[0];b=p+a*t;b=k.getImageData(b,r,F-b,h);Ua();k.putImageData(b,p,r);z.deleteChars(J(),G(),a);break;case 88:a||(b[0]=1);a=b[0];k.fillStyle=E;k.fillRect(p,r,a*t,h);k.fillStyle=C;z.eraseChars(J(),G(),a);break;case 90:a||(b[0]=1);p=8*((p/t/8|0)-b[0]+1)*t;ja();break;case 100:a||(b[0]=1);ya(b[0]);break;case 101:a||(b[0]=1);ya(G()+b[0]);break;case 104:if(63==T.mode)switch(b[0]){case 1:fa.setEscMode(1);
break;case 5:console.log("Reversal screen mode");break;case 6:console.log("Relative origion mode");break;case 7:console.log("wraparound mode on");oa=!0;break;case 25:ia(!1);break;case 45:console.log("reverse-wraparound mode on");break;case 1E3:case 1001:case 1002:case 1003:case 1005:case 1006:N=b[0];console.log("mouse tracking on:"+N);break;default:console.log("TODO: CSI ? Pm h, Ps:"+b[0])}break;case 108:if(63==T.mode)switch(b[0]){case 1:fa.setEscMode(0);break;case 2:fa.setEscMode(2);case 5:console.log("Normal screen mode");
break;case 6:console.log("Absolute origion mode");break;case 7:oa=!1;break;case 12:break;case 25:ia(!0);break;case 45:console.log("reverse-wraparound mode off");break;case 1E3:case 1001:case 1002:case 1003:case 1005:case 1006:N=0;break;default:console.log("TODO: CSI ? Pm l, Ps:"+b[0])}break;case 109:0==a&&(a=1,b[0]=0);for(c=0;c<a;c++)switch(b[c]){case 0:pa(7);qa(0);Fa(!1);break;case 1:Fa(!0);break;case 2:break;case 4:break;case 5:case 8:break;case 7:pa(0);qa(7);break;case 27:pa(7);qa(0);break;case 30:case 31:case 32:case 33:case 34:case 35:case 36:case 37:pa(b[c]-
30);break;case 38:return 2==b[c+1]&&(C="rgb("+b[c+2]+","+b[c+3]+","+b[c+4]+")",k.fillStyle=C),!0;case 39:pa(7);break;case 40:case 41:case 42:case 43:case 44:case 45:case 46:case 47:qa(b[c]-40);break;case 48:return 2==b[c+1]&&(E="rgb("+b[c+2]+","+b[c+3]+","+b[c+4]+")"),!0;case 49:qa(0);1==c&&39==b[0]&&Fa(!1);break;default:return console.log("TODO: SGR="+T.toString()),!0}break;case 110:6==b[0]?63==T.mode?D("\u001b[?"+G()+";"+J()+"R"):D("\u001b["+G()+";"+J()+"R"):5==b[0]&&D("\u001b[0n");break;case 114:T.mode||
da(b[1],b[0]);break;default:console.log("TODO: CSI="+T.toString())}return!0}function Va(a){a||(a=1);var b=(H-1)*h,c=k.getImageData(0,b,F,(O-H-a+1)*h);k.fillStyle=E;k.fillRect(0,b,F,h*a);k.putImageData(c,0,(H+a-1)*h);k.fillStyle=C;z.scrollUp(a,H,O)}function Wa(a){a||(a=1);var b=(H-1)*h,c=O*h,d=a*h,e=b+d,e=k.getImageData(0,e,F,c-e);k.fillStyle=E;k.fillRect(0,c-d,F,d);k.fillStyle=C;k.putImageData(e,0,b);z.scrollDown(a,H,O)}function ja(a){oa&&p>=F&&(p=0,r+=h);if((oa||a)&&r>ua){for(;r>ua;)r-=h;Ja?(k.drawImage(R,
0,-h),k.fillStyle=E,k.fillRect(0,ua,m,h),z.appendLines(1)):(a=k.getImageData(0,0+(H-0)*h,F,(O-H)*h),k.fillStyle=E,k.fillRect(0,(H-1)*h,F,(O-H+1)*h),k.putImageData(a,0,0+(H-1)*h));k.fillStyle=C}}function Ea(){p-=t;0>p&&(p=0)}function G(){return parseInt(r/h)+1}function J(){return parseInt(p/t)+1}function ya(a,b){b&&(p=(b-1)*t,0>p&&(p=0));a&&(r=(a-1)*h)}function qa(a){E=za[a];E||(E=l.bgColor||"black",console.log("xx colorIndex:"+a))}function pa(a){Xa=a;C=ra[a];C||(C=l.fgColor||"white",console.log("xx colorIndex:"+
a));k.fillStyle=C}function Fa(a){ra=a?Ya:za;C=ra[Xa]}function Ua(){k.fillStyle=E;k.fillRect(p,r,F-p,h);k.fillStyle=C;z.clearEOL(J(),G())}function wa(){k.fillStyle=E;k.fillRect(0,0,R.width,R.height);k.fillStyle=C}function ha(){ma.style.top=r+"px";ma.style.left=p+"px"}function V(a){K.on&&(a.startsWith(K.prompt)?(K.on=!1,setTimeout(K.process,30)):K.text+=a);var b=a.length,c=(p/t|0)+b-M;0<c?(b-=c,Za(a.substring(0,b),b),ja(),V(a.substring(b))):Za(a,b)}function Za(a,b){if(a){z.writeText(J(),G(),a);var c=
b*t;k.fillStyle=E;k.fillRect(Math.floor(p),r,Math.ceil(c),h);k.fillStyle=C;k.fillText(a,p,r+Pa);p+=c}}function qb(a,b){for(var c=a.getPosition(),d,e="",f=a.getEnd(),x=a.getData();c<f;)if(d=x[c++],d!=b)switch(d>>4){case 0:case 1:case 2:case 3:case 4:case 5:case 6:case 7:e+=String.fromCharCode(d);break;case 12:case 13:e+=String.fromCharCode((d&31)<<6|x[c++]&63);break;case 14:e+=String.fromCharCode((d&15)<<12|(x[c++]&63)<<6|(x[c++]&63)<<0)}else break;a.setPosition(c);return e}function $a(a){W+=a;aa?
(V(a),Z(),ha()):A&&A.echo[A.answer.length]&&(V(a),Z(),ha())}function Ta(){p=0;r>(O-1)*h&&(r=(O-1)*h)}function rb(a){if(y)return(a=a.getData("text/plain"))?(a=a.replace(/\r\n/g,"\n"),aa||A?$a(a):D(a),!0):!1}function ab(){if(U){var a=!!U.value;U.value=z.toString();a||(a=new hi5.ui.Lightbox(document.getElementById("copydialog")),a.show(),u&&u.setIgnorePaste(!1),a.onclose=function(){U.value=""});setTimeout(function(){U.scrollTop=U.scrollHeight},10)}}function bb(a){L(l.mapDisk)&&(B||(B=new hi5.file.UploadManager(new hi5.file.WsFileService(Ca),
!1),B.enabled=!0,B.canCopyFile=!1,B.addEvent("beforeupload",function(a,c,d){f.beforeupload&&f.beforeupload(a,c,d)}),B.addEvent("fileuploaded",function(a,c,d){if(f.onfileuploaded)f.onfileuploaded(a,c,d)}),B.addEvent("uploaded",function(a,c){if(f.onuploaded)f.onuploaded(a,c)}),B.addEvent("uploadingCancelled",function(){if(f.onuploadingCancelled)f.onuploadingCancelled()})),a.setFileHandler(B))}function D(a){if(a){a=unescape(encodeURIComponent(a));var b=a.length+1,c=new Uint8Array(b);c[0]=147;for(var d=
1;d<b;d++)c[d]=a.charCodeAt(d-1);q.send(c.buffer)}}function Ka(a,b,c){function d(){var b=Array(a);hi5.Arrays.fill(b,0,a," ");return b}var e=0,f=[];if(!c||10>c/b)c=10*b;this.writeText=function(a,b,c){b--;a--;var x=f[e+b];x||(x=d(),f[e+b]=x);b=0;for(var g=c.length;b<g;b++)x[b+a]=c[b]};this.appendLines=function(a){e+=a};this.scrollDown=function(a,b,c){c=e+c-1-a;for(b=e+b-1;b<=c;b++)f[b]=f[b+a];c++;for(b=0;b<a;b++)f[c+b]=d()};this.scrollUp=function(a,b,c){b=e+b-1+a;for(c=e+c-1;c>=b;c--)f[c]=f[c-a];b--;
for(c=0;c<a;c++)f[b-c]=d()};this.cleanScreen=function(){e=f.length;if(e>=c){var a=2*b;f.splice(0,a);e-=a}};this.clearEOS=function(d,c){c--;d--;for(var x=e+c,g,h,Ga=0,k=b-c;Ga<k;Ga++)if(h=f[x+Ga])for(g=d;g<a;g++)h[g]=" "};this.clearBOS=function(a,b){b--;a--;for(var d=e,c,x,g=0;g<b;g++)if(x=f[d+g])for(c=0;c<a;c++)x[c]=" "};this.clearLine=function(b){b--;(b=f[e+b])&&hi5.Arrays.fill(b,0,a," ")};this.clearBOL=function(a,b){b--;a--;var d=f[e+b];if(d)for(var c=0;c<a;c++)d[c]=" "};this.clearEOL=function(b,
d){d--;b--;var c=f[e+d];if(c)for(var x=b;x<a;x++)c[x]=" "};this.eraseChars=function(a,b,d){b--;a--;if(b=f[e+b]){var c=a;for(a+=d;c<a;c++)b[c]=" "}};this.deleteChars=function(a,b,d){b--;a--;(b=f[e+b])&&b.splice(a,d)};this.insertSpace=function(a,b,d){d--;b--;if(d=f[e+d]){for(var c=d.length-1;c>=b;c--)d[c+a]=d[c];for(c=0;c<a;c++)d[b+c]=" "}};this.getSingleLine=function(a,b,d){a--;b--;d--;var c="";if(a=f[e+a])for(;b<d;b++)c+=a[b];return c.trimRight()};this.getMultiLines=function(b,d,c,g){if(g<d)return this.getMultiLines(c,
g,b,d);var x=g-d+1;if(1>x)return null;if(1==x)return this.getSingleLine(d,b,c);b=this.getSingleLine(d,b,a);c=this.getSingleLine(g,1,c);x-=2;d+=e;for(var h=0;h<x;h++)b=(g=f[h+d])?b+("\r\n"+g.join("").trimRight()):b+"\r\n\r\n";return b+"\r\n"+c};this.toString=function(){for(var a="",b=0,d=f.length;b<d;b++)f[b]&&(a+=f[b].join("").trimRight()),a+="\r\n";return a}}var X=0,Y=null,Na=!1;this.displayMsg=!0;this.reconnectTimes=0;this.setTitle=this.openLink=!0;this.mode=0;this.reconnectOnResize=!0;var f=this;
this.getHistory=function(){return z.toString()};hi5.appcfg||(hi5.appcfg={img:{},toolbar:{fadable:!0},displayMsg:!0});var w=hi5.appcfg,K={on:!1,text:"",prompt:"",cmd:"",process:function(){var a=K.cmd.indexOf(" "),b=K.cmd.substring(a+1),a=b.lastIndexOf("."),c="";if(-1!=a)switch(b.substring(a+1).toLowerCase()){case "jpe":case "jpg":case "jpeg":c="image/jpeg";break;case "gif":c="image/gif";break;case "bmp":c="image/bmp";break;case "svg":c="image/svg+xml";break;case "png":c="image/png";break;case "webp":c=
"image/webp";break;case "ico":c="image/x-icon"}a="data:"+(c||"application/octet-stream")+";base64,"+K.text;K.text="";f.showMessage(c?{msg:'<img src="'+a+'" style="max-width:100%"/>'}:{msg:'<a download="'+b+'" href="'+a+'" target="_blank">'+b+"</a>"})}};void 0!=w.reconnectOnResize&&(this.reconnectOnResize=w.reconnectOnResize);var Ha="object"==typeof g?g:null,cb="object"==typeof g||0<g.indexOf("/PLAY?");cb?(this.mode=1,Ha&&(g=""),g+="&touchpad=on"):0<g.indexOf("/JOIN?")&&(this.mode=2,this.reconnectOnResize=
!1);var l=hi5.tool.queryToObj(g.substring(g.indexOf("?")+1));l.color||(l.color=32);var U=L(l.mapClipboard)?document.getElementById("copytextarea"):null,z=null;U&&(U.value="");this.server=l.server;this.port=parseInt(l.port,10);this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:!0,trueColor:!0};var u=null,y=!1,na=!1,Ia=0,ta="",N=0,B=null;w.copyDialog=!0;var p=0,r=0,t=0,h=18,Pa=0,za="#000 #cd0000 #00cd00 #cdcd00 #0000ee #cd00cd #00cdcd #e5e5e5".split(" "),Ya="#7f7f7f #ff0000 #00ff00 #ffff00 #5c5cff #ff00ff #00ffff #ffffff".split(" "),
ra=za,C=l.fgColor||ra[7],E=l.bgColor||ra[0],Xa=0,oa=!0;l.wraparoundMode&&(oa=L(l.wraparoundMode));var H=1,O=24,ua=0,Ja=!0,ma=document.getElementById("cursorID"),P=0,M=0,F=0,S=null;window.$ssh=this;var ea=new function(a){var b=0,c=0,d=new Uint8Array(a),e=this,f=new La(0,null,0);this.needMore=!1;this.release=function(){e=d=f=null};this.getHandler=function(){return f};this.getData=function(){return d};this.getPosition=function(){return b};this.setPosition=function(a){b=a};this.getEnd=function(){return c};
this.has=function(a){return c-b>=a};this.set=function(a){var e=a.length,f=c-b;if(1>f)c=e,d=a;else{var g=d.subarray(b,c);c=f+e;e=new Uint8Array(c);e.set(g);e.set(a,f);d=e}b=0};this.handle=function(){f.handler(e,f)};this.setHandler=function(a){a&&1>a.need&&svGlobal.logger.warn("need < 1");(f=a)&&c-b>=a.need&&a.handler(e,a)};this.getByte=function(){return d[b++]};this.peekByte=function(){return d[b]};this.getBE32=function(){return d[b++]<<24|d[b++]<<16|d[b++]<<8|d[b++]};this.getBE16=function(){return d[b++]<<
8|d[b++]};this.skip=function(a){b+=a};this.skipBack=function(a){b-=a};this.getBytes=function(a,e){if(e)for(var c=0;c<a;c++)e[c]=d[b++];else return c=b,b+=a,d.subarray(c,b)};this.copyToByteArray=function(a,b,e,c){hi5.Arrays.arraycopy(d,e,a,b,c)}}(4194304);this.__que=ea;this.running=function(){return y};this.setColorTable=function(a){za=a};this.setColorTableBright=function(a){Ya=a};this.loadbalanceToken=w.loadbalanceTokenName?w.loadbalanceTokenName+"="+hi5.tool.uuid():"";this.mapCmdToCtrl=!0;var q=
null;m||(m=window.innerWidth);l.width=m;g+="&width="+m;n||(n=window.innerHeight);l.height=n;g+="&height="+n;v=(v=v||l.fontSize)?parseInt(v):13;l.fontSize?(v=parseInt(l.fontSize,10),l.fontSize=v):(l.fontSize=v,g+="&fontSize="+v);var Ra,R=window.OffscreenCanvas?new OffscreenCanvas(m,n):document.createElement("canvas"),k;this.modifyURL=function(a){f.loadbalanceToken&&(a+="&"+f.loadbalanceToken);return a};this.__write=Ca;this.getFileUrl=function(a){return f.modifyURL(ga()+"/DOWNLOAD?s="+ta+"&f="+a)};
this.listFiles=function(a,b){B&&B.list(a,b)};this.reconnect=function(a,b){va(a,b);q.send("ED"+M+"\t"+P+"\t"+m+"\t"+n)};var I=new function(a){this.setJoinMode=a.setJoinMode;this.requestControl=a.requestControl;this.writeKeyComb=a.writeKeyComb;this.localLockFlags=0;this.checkLockFlags=!0;this.getAppMode=function(){return a.mode};this.send=function(b){"891"!=b&&y&&a.__write(b)};this.sendInput=function(b){a.writeRawInput(b);if(a.onactivity)a.onactivity(b)};var b=null;this.getAppInfo=function(){return a.sessionInfo.appInfo};
this.onresize=function(c){if(c=c.target.svSurface){c=c.getFreeSpace();var d=c.width,e=c.height;hi5.browser.isTouch||Math.abs(m-d)<t&&Math.abs(n-e)<h||!a.reconnectOnResize||!y||(b&&(clearTimeout(b),b=null),b=setTimeout(function(){va(d,e);q.send("ED"+M+"\t"+P+"\t"+m+"\t"+n)},555))}};this.onorientationchange=function(a){};this.getClipData=sa;this.onfocus=function(a){};this.getShareFiles=a.listFiles;this.getFile=function(b){var d=a.getFileUrl(b);a.ondownload&&a.ondownload({fileName:b,url:d})||window.open(d)};
this.getFileLink=a.getFileUrl;this.getGateway=function(){return g};this.reconnect=function(a,b,e){};this.sendKeyboardSyncFlags=function(a){return y?(this.remoteLockFlags=this.localLockFlags=a,!0):!1};this.setWorkDir=function(b,d){d&&a.writeText("cd "+d+"\n")}}(this);void 0!=w.displayMsg?this.displayMsg=w.displayMsg:w.displayMsg=this.displayMsg;void 0!=w.reconnectTimes&&(this.reconnectTimes=w.reconnectTimes);void 0!=w.openLink&&(this.openLink=w.openLink);void 0!=w.setTitle&&(this.setTitle=w.setTitle);
"boolean"==typeof w.useWSS&&(g=(w.useWSS?"wss":"ws")+g.substring(g.indexOf("://")));this.getURL=function(){return g};var sb=parseInt(l.server_bpp||l.color||24);this.getColor=function(){return sb};this.run=function(){if(!y){if(Ha)q=Ha,Da();else{Oa();var a=g+="&cols="+M+"&rows="+P;hi5.browser.binaryWS()&&(a+="&binary=on");var b=window.opener;if(b){var c=null;try{c=b.__sparkUser}catch(d){}c&&(b=c.account,c=c.session,b&&(a+="&account="+b),c&&(a+="&session="+c))}g=a+("&pasteCap="+(hi5.browser.isChrome&&
hi5.browser.isDesktop?3:0));a=0==f.mode&&w.wsPost?g.substring(0,g.indexOf("?"))+"?_METHOD=post":g;a=f.modifyURL(a);(c=hi5.browser.cookie.get("__SV_TOKEN_A"))&&(a+="&__SV_TOKEN_A="+encodeURIComponent(c));q=new WebSocket(a,"ssh");q.binaryType="arraybuffer"}q.onopen=nb;void 0!=l.recording&&"on"==l.recording&&gb(l);q.onmessage=function(a){a=a.data;if("string"!=typeof a){var b=new Uint8Array(a);null!=S&&S.add(new RecordingObj(b,0,a.byteLength));ea.set(b);ea.handle()}else{var c=parseInt(a.substring(0,2),
16),b=a.substring(2);switch(c){case 0:a=g.substring(g.indexOf("?")+1);q.send("00"+a);q.send("87"+navigator.userAgent);break;case 15:a=JSON.parse(b);q.send("8D");if(f){f.sessionInfo.protocolVersion=a.protocolVersion;if(f.onready)f.onready();if(f.onloggedin)f.onloggedin();w.pingInterval&&f.startPing(w.pingInterval);B&&(B.enabled=!0)}ia(!1);break;case 26:a=JSON.parse(b);if(a.name){svGlobal.logger.info("msg="+b);if(f.onerror)f.onerror(a);b=__svi18n.errorCode["S"+a.name]||"";b+=a.message||a.msg;f.showMessage(b)}else 0<
svGlobal.log&&console.erro("No error code for message:"+b);break;case 27:0!=w.drawLicense&&u.drawLicense(b);break;case 56:a=JSON.parse(b);ta=a.session;a.server=f.server;if(b=hi5.$("joinSelect"))b.value=a.joinMode;if(b=hi5.$("requestControl"))b.disabled=a.hasControl;var b=mb("joinssh.html")+"?id="+a.numericId,b=f.modifyURL(b),d=a.webAddress;d&&0<d.length&&(c=d.indexOf("://"),d=d.substring(c+3),c=d.indexOf("/"),0<c&&(d=d.substring(0,c)),d.toLowerCase()!=location.host.toLowerCase()&&(b+="&gateway="+
d));a.joinLink=b;f.sessionInfo.appInfo=a;a.ver&&a.ver!=svGlobal.version&&svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+a.ver);Da();if(f&&f.onsessionstart)f.onsessionstart(f.sessionInfo);break;case 58:if(B)if(a=parseInt(b.charAt(0),10),b=b.substring(1),5==a)B.notifyFiles(JSON.parse(b));else switch(b=b.split("\t"),a){case 1:B.confirmId(b[0],b[1],b[2]);break;case 2:B.read(b[0],parseInt(b[1],10),parseInt(b[2],10));break;case 4:B.close(b[0]);break;case 9:a='<a href="'+b[0]+'" download="'+
b[1]+'" target="_blank">'+__svi18n.info.fileReady+"</a>",surfaces.getFocused().showMessage({msg:a,title:__svi18n.info.download})}break;case 59:a=hi5.Base64.dec(b,0);Ia=a[3]<<24|a[2]<<16|a[1]<<8|a[0];Ia&64&&f.showMessage(__svi18n.info.recording);u.setFeature(Ia);break;case 61:a=JSON.parse(b);switch(a.type){case 0:l.fontSize=parseInt(a.fontSize);m=a.width;n=a.height;Da();u.setAutoScale(!0);va(0,0,M,P);if(b=a.server)f.server=a.server,f.setTitle&&(document.title=l.displayName||f.server);(b=a.mapDisk)&&
bb(u);ia(!1);db=a.length;if(f.onopened)f.onopened(a);break;case 1:a=a.duration;if(f.onprogress)f.onprogress(a,db);break;case 2:2==a.status?y=!0:((Qa=b=0==a.status)||Z(),a.warn&&f.showMessage(b?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed))}break;case 62:lb(b);break;case 91:na=!0;if(f.onusername)f.onusername(kb);else V(__svi18n.info.user||b),aa=!0,Z(),ha();break;case 93:A=JSON.parse(b);if(f.onauthprompt)f.onauthprompt(A,jb);else a=A.name||"",A.instruction&&(a+=A.instruction),a&&(r+=h,p=
0,V(a),ha()),A.answer=[],Ma();break;default:svGlobal.logger.warn("@TODO:"+a+"\n")}}};q.onclose=xa;q.onerror=ob;f.setTitle&&(document.title=l.displayName||f.server)}};this.setJoinMode=function(a){y&&q.send("8E1"+a)};this.refuseControl=function(a){y&&q.send("8E3"+a)};this.giveControl=function(a){y&&q.send("8E4"+a)};this.requestControl=function(){y&&q.send("8E2")};this.play=function(){q.send("F3")};this.pause=function(){q.send("F2")};this.scan=function(a){q.send("F4"+(a?"1":"0"))};this.seek=function(a){u&&
y&&q.send("F4"+(a?"1":"0")+"\t"+(a/u.getScale().x|0))};this.allowJoin=function(a,b){q.send("8EA"+a+"\t"+(b?1:0))};var Q=null,aa=!1,A=null,W="",db=0;this.hide=function(){u&&(ia(!0),u.hide())};this.showMessage=function(a,b){f.displayMsg&&a&&(u?u.showMessage(a,b):("string"==typeof a&&(a={msg:a,timeout:b||0}),hi5.notifications.notify(a)))};this.close=function(){if(q&&y)try{q.send("85"),q.close()}catch(a){}else xa()};hi5.browser.isChromeApp?chrome.runtime.onSuspend.addListener(xa):window.addEventListener("unload",
xa,!1);var tb=new La(1024,function(a){var b=p,c=r;for(a.needMore=!1;a.has(1);){var d=a.getByte();if(31>=d)if(27==d){a:if(d=a,d.has(1)){var e=d.getByte();switch(e){case 40:d.getByte();break;case 41:d.getByte();break;case 55:break;case 61:break;case 62:break;case 68:Wa();break;case 69:Ta();r+=h;ja(!0);break;case 77:Va();break;case 92:console.log("ST");break;case 93:console.log("OSC:"+qb(d,7));break;case 91:d=pb(d);break a;default:console.log("unkown cmd for ESC:"+e)}d=!0}else d.skipBack(1),d=!1;if(!d)return}else Sa(d);
else if(128<=d&&159>=d)switch(d){case 146:a.skip(2);break;default:console.log("C1:"+d)}else{a.skipBack(1);d=V;a:{for(var e=a,f=e.getPosition(),g,k="",l=e.getEnd(),m=e.getData();f<l;)if(g=m[f++],31<g&&(128>g||159<g)){if(177!=g)switch(g>>4){case 0:case 1:case 2:case 3:case 4:case 5:case 6:case 7:k+=String.fromCharCode(g);break;case 12:case 13:if(f<l)k+=String.fromCharCode((g&31)<<6|m[f++]&63);else{e.needMore=!0;e=k;break a}break;case 14:if(1<l-f)k+=String.fromCharCode((g&15)<<12|(m[f++]&63)<<6|(m[f++]&
63)<<0);else{e.needMore=!0;e=k;break a}}}else{f--;break}e.setPosition(f);e=k}d(e);if(a.needMore)return}}b==p&&c==r||ha();Z();Y&&Y.check()});ea.setHandler(tb);var Qa=!1;this.refreshOutput=Z;var T={mode:0,parameters:[0],count:0,trailing:0,command:0,toString:function(){var a="CSI, ";this.mode&&(a+="mode:"+String.fromCharCode(this.mode));0<this.count&&(a+=" parameters:"+this.parameters.slice(0,this.count).join(";"));this.trailing&&(a+=" trailing:"+String.fromCharCode(this.trailing));return a+=" cmd:"+
String.fromCharCode(this.command)},parse:function(a){var b=0,c=!1,d=a.getByte();if(!d)return!1;if(60<=d&&63>=d)this.mode=d,d=a.getByte();else if(this.mode=0,31>=d||128<=d&&159>=d)Sa(d),d=a.getByte();if(!d)return!1;for(this.count=0;48<=d&&57>=d||59==d;)if(59==d?(this.parameters[this.count]=c?b:null,this.count++,b=0,c=!1):(b=10*b+(d-48),c=!0),d=a.getByte(),!d)return!1;c?(this.parameters[this.count]=b,this.count++):0<this.count&&(this.parameters[this.count]=1,this.count++);if(32<=d&&47>=d){if(this.trailing=
d,d=a.getByte(),!d)return!1}else this.trailing=0;64<=d&&127>=d?this.command=d:(this.command="",console.log("Invalid CSI final char:"+String.fromCharCode(d)));return!0}};this.showHistory=ab;this.getUploadManager=function(){return B};this.addSurface=function(a){u=a;cb&&a.setPlayerMode();Ra=u.context;R.width=m;R.height=n;k=R.getContext("2d",{alpha:!1});a.forceTextArea=!0;a.alwaysPaste=!0;a.setAutoScale(0<f.mode);a.setSize(m,n);a.setController(I);a.setTouchpad(L(l.touchpad));a.setClipboard(L(l.mapClipboard));
bb(u);var b=void 0!=l.cmdToCtrl?L(l.cmdToCtrl):void 0!=w.cmdToCtrl?w.cmdToCtrl:f.mapCmdToCtrl;a.run(99997,!1,!0,b);a.onclipdata=rb};this.sendPing=function(a){a=new Uint8Array(2);a[0]=146;Ca(a.buffer)};this.startPing=function(a){Y||(Y=new hi5.tool.ResponseMonitor(function(){na&&f.sendPing()},function(){na&&Y.check(1)}));Y.setInterval(a,a);setTimeout(function(){Y.check()},1E3*a)};this.stopPing=function(){Y&&Y.stop()};this.writeText=D;this.writeScancode=function(a,b){D(fa.process(a,b,0))};var ub={" ":57,
space:57,pageup:201,pagedown:209,end:207,home:199,left:203,up:200,right:205,down:208,printscreen:183,insert:210,del:211,"delete":211,altgr:184,windows:219,windowsright:220,context:221,esc:1,backspace:14,tab:15,enter:28,meta:29,command:29,ctrl:29,shift:42,alt:56,capslock:58,f1:59,f2:60,f3:61,f4:62,f5:63,f6:64,f7:65,f8:66,f9:67,f10:68,f11:87,f12:88,numlock:69,scrolllock:70,add:78};this.writeKeyComb=function(a){a=a.split("+");var b=a.length;if(0!=b)for(var c=null,d=0;d<b;d++){var e=a[d];""==e&&""==c&&
(e="Add");if(""!=e){var c=e,g=ub[c.toLowerCase()];g?f.writeScancode(!0,g):console.log("Invalid key:"+c)}c=e}};var Aa=!1,ba=0,ca=0,Ba=0,ka=!1,eb=0,fb=0,la=null;this.writeRawInput=function(a){if(y){var b=parseInt(a.substring(0,2),16);a=a.substring(2).split("\t");switch(b){case 128:ba=parseInt(a[0]);ca=parseInt(a[1]);Ba=parseInt(a[2]);ka=!1;Aa=!0;eb=Math.floor(ba/t)*t;fb=Math.floor(ca/h)*h;1015==N?D("\u001b["+(parseInt(a[2])+32)+";"+(Math.floor(ba/t)+1)+";"+(Math.floor(ca/h)+1)+"M"):1006==N?D("\u001b[<"+
a[2]+";"+(Math.floor(ba/t)+1)+";"+(Math.floor(ca/h)+1)+"M"):N&&D("\u001b[M"+a[2]+String.fromCharCode(Math.floor(ba/t)+33)+String.fromCharCode(Math.floor(ca/h)+33));return;case 129:N&&(1015==N?D("\u001b["+(parseInt(a[2])+32)+";"+(Math.floor(ba/t)+1)+";"+(Math.floor(ca/h)+1)+"M"):1006==N?D("\u001b[<"+a[2]+";"+(Math.floor(parseInt(a[0])/t)+1)+";"+(Math.floor(parseInt(a[1])/h)+1)+"m"):N&&D("\u001b[M3"+String.fromCharCode(Math.floor(parseInt(a[0])/t)+33)+String.fromCharCode(Math.floor(parseInt(a[1])/h)+
33)));Ba=parseInt(a[2]);2==Ba&&Aa&&!ka?(U&&(U.value=""),setTimeout(ab,50)):ka&&(a=z.getMultiLines(Math.floor(ba/t)+1,Math.floor(ca/h+.1)+1,Math.floor(parseInt(a[0])/t+.4)+1,Math.floor(parseInt(a[1])/h-.4)+1))&&u&&u.copyToClip("text/plain;"+a);la&&(setTimeout(u.removeWhiteboard,333),la=null);ka=Aa=!1;return;case 130:if(Aa){b=parseInt(a[0]);a=parseInt(a[1]);if(!ka){if(3>Math.abs(b-ba)&&3>Math.abs(a-ca))return;ka=!0}if(0==Ba){if(!la){var c=u.initWhiteboard();c.style.opacity=.6;c=c.getContext("2d");la=
new hi5.canvas.TextSelect(c,h,w.selectionColor,"1px",m)}la.clear();la.draw(eb,fb,b,a)}}return;case 131:1006==N?D("\u001b[<"+("1"==a[2]?65:64)+";"+(Math.floor(parseInt(a[0])/t)+1)+";"+(Math.floor(parseInt(a[1])/h)+1)+"M"):N&&D("\u001b[M"+("1"==a[2]?5:4)+String.fromCharCode(Math.floor(parseInt(a[0])/t)+64)+String.fromCharCode(Math.floor(parseInt(a[1])/h)+64));return;case 132:c=0==a[0];b=parseInt(a[1]);if(aa||A)c&&(a=b,28==a?(r+=h,p=0,aa?(aa=!1,q.send("5B"+W),W=""):A&&(A.answer.push(W),W="",Ma())):14==
a&&0<W.length&&(W=W.substring(0,W.length-1),aa&&(Ea(),V(" "),Z(),Ea())));else if(D(fa.process(c,b,0)),28!=b)X||(X=J());else if(X){if(X&&(a=z.getSingleLine(G(),X,J()))){b=z.getSingleLine(G(),1,X);if(f.oncommand)f.oncommand(a,b);a.startsWith("cd /")?u.setDirectory(a.substring(3)):a.startsWith("base64 ")&&(K.on=!0,K.cmd=a,K.prompt=b)}X=0}return;case 139:b=parseInt(a[1]);c=0==a[0];D(fa.process(c,b,1));return;case 134:aa||A?$a(a[0]):(X||(X=J()),D(fa.process(!0,a[0],3)));return}svGlobal.logger.warn("Unknowncode: "+
a[1]+" type:"+b)}};var fa=new function(){var a=!1,b=!1,c=!1,d=0;this.setEscMode=function(a){d=a;console.log("Esc mode:"+a)};this.process=function(e,f,g){if(3==g)return f;if(0==g){switch(f){case 29:case 157:return a=e,"";case 56:case 184:return b=e,"";case 42:case 54:return c=e,""}if(e){switch(f){case 28:e="\r";break;case 200:e=0==d?"\u001b[A":"\u001bOA";break;case 208:e=0==d?"\u001b[B":"\u001bOB";break;case 205:e=0==d?"\u001b[C":"\u001bOC";break;case 203:e=0==d?"\u001b[D":"\u001bOD";break;case 59:e=
"\u001bOP";break;case 60:e="\u001bOQ";break;case 61:e="\u001bOR";break;case 62:e="\u001bOS";break;case 63:e="\u001b[15~";break;case 64:e="\u001b[17~";break;case 65:e="\u001b[18~";break;case 66:e="\u001b[19~";break;case 67:e="\u001b[20~";break;case 68:e="\u001b[21~";break;case 87:e="\u001b[23~";break;case 88:e="\u001b[24~";break;case 15:e="\t";break;case 209:e="\u001b[6~";break;case 201:e="\u001b[5~";break;case 199:e=0==d?"\u001b[H":"\u001bOH";break;case 207:e=0==d?"\u001b[F":"\u001bOF";break;case 14:e=
c?"\b":"\u007f";break;case 211:e="\u001b[3~";break;case 197:e="\u00ff\u00f3";break;case 210:e="\u001b[2~";break;case 1:e="\u001b";break;case 55:e="*";break;case 71:e=I.localLockFlags&2?"7":0==d?"\u001b[H":"\u001bOH";break;case 72:e=I.localLockFlags&2?"8":0==d?"\u001b[A":"\u001bOA";break;case 73:e=I.localLockFlags&2?"9":"\u001b[5~";break;case 74:e="-";break;case 75:e=I.localLockFlags&2?"4":0==d?"\u001b[D":"\u001bOD";break;case 76:e=I.localLockFlags&2?"5":"\u001bOu";break;case 77:e=I.localLockFlags&
2?"6":0==d?"\u001b[C":"\u001bOC";break;case 78:e="+";break;case 79:e=I.localLockFlags&2?"1":0==d?"\u001b[F":"\u001bOF";break;case 80:e=I.localLockFlags&2?"2":0==d?"\u001b[B":"\u001bOB";break;case 81:e=I.localLockFlags&2?"3":"\u001b[6~";break;case 82:e=I.localLockFlags&2?"0":"\u001b[2~";break;case 83:e=I.localLockFlags&2?".":"\u001b[3~";break;case 156:e="\r";break;case 181:e="/";break;default:return console.log("Invalid code:"+f),""}b&&(e="\u001b"+e);return e}return""}if(1==g&&e&&a){if(64<f&&91>f)return String.fromCharCode(f-
64);switch(f){case 54:return"\u001e";case 219:return"\u001b";case 220:return"\u001c";case 221:return"\u001d";case 32:return"\x00";case 192:return"\u001e";case 191:return"\u001f";default:return console.log("Invalid key code:"+f),""}}if(b)return"\u001b"+String.fromCharCode(f).toLowerCase()}}};
