svGlobal.auth=new function(){function q(d){hi5.tool.enableInput();if(d.error)hi5.notifications.notify(__svi18n.errorCode["S"+d.name]);else{hi5.$("frmConn").style.display="block";for(var c=hi5.$("programs");c.hasChildNodes();)c.removeChild(c.firstChild);var b=d.servers;if(!d.accessNotInList){var a=hi5.$("anyconn");a&&(a.style.display="none")}window.__sparkUser={session:d.session,account:d.name,gateway:svGlobal.auth.gateway,servers:b};d=b.length;if(!(1>d)){for(var a="",h=0;h<d;h++){var n=b[h].server,
k=b[h].id,n=b[h].displayName||k||n,l=b[h].icon;l||(l="rdp32.png");var f=document.createElement("div");f.className="icon";var m=document.createElement("img");m.src=l;m.id=k;m.alt=k;m.title=n;m.style.cursor="pointer";m.onclick=p;f.appendChild(m);f.appendChild(document.createElement("br"));f.appendChild(document.createTextNode(n));c.appendChild(f);hi5.appcfg.startup&&k===hi5.appcfg.startup.server&&(a=k)}!a&&hi5.appcfg.startup&&(console.log("start up:"+hi5.appcfg.startup.server+" not found, use the first instead"),
a=b[0].id);a&&e(a,!hi5.appcfg.startup.newWindow,!0)}}}function p(d){var b=d.target;b.onclick=null;setTimeout(function(){b.onclick=p},300);e(b.id)}function e(d,b,e){var a=window.__sparkUser,h=a.servers,n=h.length;a.server=null;window.sparkGateway=a.gateway;for(var k=0;k<n;k++){var l=h[k];if(d==l.id){l.gateway=a.gateway;l.session=a.session;l.account=a.account;a.server=l;break}}if(a.server){console.log("connecting to:"+a.server.id);(d=hi5.$("touchpad"))&&d.checked&&(a.server.touchpad=!0);if(d=hi5.$("keyboard"))d=
parseInt(d.options[d.selectedIndex].value),0<d&&(a.server.keyboard=d);if(svGlobal.auth.onconnect)svGlobal.auth.onconnect(a.server);d=a.server.rdp&&("app"==a.server.startProgram||a.server.rdp.remoteProgram);void 0==b&&(b=d);if(b){var f=svManager.getInstance();if(d&&f&&f.running())f.startApp(a.server.exe||a.server.rdp.remoteProgram,a.server.args||a.server.rdp.remoteArgs,""),c&&c.visible()&&c.dismiss();else{var m=function(a){function b(){null==c&&(c=new hi5.ui.Lightbox(hi5.$("login")));c.visible()?c.dismiss():
c.show()}var d=a.toolbar.querySelector("#__sv_btn_home");d||(d=a.toolbar.addButton(hi5.appcfg.img.home||"home.png",b),d.id="__sv_btn_home")},f=new Rdp2(a.server);hi5.$("login").style.display="none";var g=new svGlobal.LocalInterface;g.onremoteappicon=function(a,b){if(g.toolbar&&a.isMainWin()&&32==b.getWidth()){var d="win"+a.id;if(!g.toolbar.querySelector("#"+d)){m(g);var c=g.toolbar.addButton(b.getDataURL(),function(){a.activate(1)});c.id=d;c.title=a.titleInfo;c.style.width="32px";c.style.height="32px";
c.addEventListener("mouseover",function(){c.title=a.titleInfo},!1);setTimeout(function(){a.activate(1)},333)}}};g.onremoteappclose=function(a){g.toolbar&&(a=g.toolbar.querySelector("#win"+a.id))&&g.toolbar.removeChild(a)};f.addSurface(g);f.run();f.onclose=function(){if(e){window.__sparkUser=null;var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none"}else f.hide(),hi5.$("login").style.display="block"}}}else a.server.rdp?window.open("rdpdirect.html"):
a.server.vnc?window.open("vnc.html"):a.server.ssh?window.open("sshdirect.html"):a.server.telnet&&window.open("telnet.html")}else hi5.notifications.notify("Not a valid server")}var b=this,c=null;this.gateway="";this.login=function(d){function c(a,d){window.__sparkUser=null;if(!b.beforelogin||!b.beforelogin(a)){hi5.tool.disableInput();var c=new WebSocket(a.substring(0,a.indexOf("?"))+"?_METHOD=post","login");c.onclose=function(a){e||hi5.notifications.notify(__svi18n.errorCode.connection);hi5.tool.enableInput();
b.afterlogin&&b.afterlogin(e);e=!1};c.onopen=function(a){e=!0};c.onmessage=function(b){0==b.data.indexOf("00")?c.send("00"+a.substring(a.indexOf("?")+1)):(b=JSON.parse(b.data),0===b.type&&b.message?hi5.notifications.notify(b.message):(b.error||c.send("A1"+navigator.userAgent),d(b),c.close()))}}}var e=!1,a=hi5.browser.cookie2Obj();a.svSession&&a.svEmail&&(d+="&svSession="+a.svSession+"&svEmail="+encodeURIComponent(a.svEmail));setTimeout(function(){c(d,q)},5);return!1}};
window.addEventListener("load",function(q){function p(){q.preventDefault();svGlobal.auth.beforesubmit&&svGlobal.auth.beforesubmit();var e=location.search,b="",c="";e.length&&(e=e.substring(1),e=hi5.tool.queryToObj(e),b=e.gateway,e.port&&(c=e.port));b||(b=hi5.browser.getHost());!c&&hi5.appcfg.defaultPort&&(c=hi5.appcfg.defaultPort);c&&(b+=":"+c);c=("https:"==location.protocol?"wss://":"ws://")+b+"/SSO?";svGlobal.auth.gateway=b;return svGlobal.auth.login(c)}(function(){var e=hi5.$("anyconn");e&&(e.onclick=
function(){window.open("rdp.html?gateway="+hi5.$("gateway").value)});if(e=document.getElementById("keyboard")){var b=svGlobal.Rdp.languageToKeyboard.detect();b&&(e.value=b)}p()})()},!1);
