var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(e,k,t){if(null==e)throw new TypeError("The 'this' value for String.prototype."+t+" must not be null or undefined");if(k instanceof RegExp)throw new TypeError("First argument to String.prototype."+t+" must not be a regular expression");return e+""};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(e,k,t){e!=Array.prototype&&e!=Object.prototype&&(e[k]=t.value)};
$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(e,k,t,B){if(k){t=$jscomp.global;e=e.split(".");for(B=0;B<e.length-1;B++){var D=e[B];D in t||(t[D]={});t=t[D]}e=e[e.length-1];B=t[e];k=k(B);k!=B&&null!=k&&$jscomp.defineProperty(t,e,{configurable:!0,writable:!0,value:k})}};
$jscomp.polyfill("String.prototype.startsWith",function(e){return e?e:function(e,t){var k=$jscomp.checkStringArgs(this,e,"startsWith");e+="";for(var D=k.length,F=e.length,x=Math.max(0,Math.min(t|0,k.length)),W=0;W<F&&x<D;)if(k[x++]!=e[W++])return!1;return W>=F}},"es6-impl","es3");
$jscomp.polyfill("String.prototype.endsWith",function(e){return e?e:function(e,t){var k=$jscomp.checkStringArgs(this,e,"endsWith");e+="";void 0===t&&(t=k.length);for(var D=Math.max(0,Math.min(t|0,k.length)),F=e.length;0<F&&0<D;)if(k[--D]!=e[--F])return!1;return 0>=F}},"es6-impl","es3");var svGlobal=svGlobal||{logger:new hi5.Logger,util:{}};svGlobal.version="5.9.0";svGlobal.build="950";function cancelDefault(e){e.preventDefault&&e.preventDefault();e.stopPropagation&&e.stopPropagation();return!1}
function LocalInterface(e,k){function t(a){var b=a-hi5.browser.innerHeight;10<b&&22>b&&(a=hi5.browser.innerHeight);return a}function B(a){r.detectInput&&S&&Y&&(sa||"text"==Y.system||"none"==Y.system?setTimeout(function(){Va(!0)},5):setTimeout(function(){Va(!1)},5));if(document.activeElement!=a||!g.focused){for(var b=a,d,c=[];b.parentElement;)if(b=b.parentElement,d=getComputedStyle(b))d.getPropertyValue("overflow"),"block"==d.getPropertyValue("display")&&c.push([b,b.scrollTop,b.scrollLeft]);a.focus();
if(c.length){a=0;for(d=c.length;a<d;a++){b=c[a];if(b[0].scrollTop!=b[1]||b[0].scrollLeft!=b[2])b[0].scrollTop=b[1],b[0].scrollLeft=b[2];c[a]=null}c=null}}}function D(){var a=[];this.sent=0;this.types=[];var b=this;this.datas=a;this.setData=function(d,c){if("text/plain"==d||"text/html"==d)2<c.length&&"`\t`"==c.substring(0,3)&&(c=c.substring(3)),c=c.replace(/\r?\n/g,"\r\n");b.types.push(d);a.push(c)};this.getData=function(d){var c=a[b.types.indexOf(d)];c||"text/richtext"!=d||(c=a[b.types.indexOf("text/html")]||
a[b.types.indexOf("text/plain")]);return c};this.removeData=function(d){d=b.types.indexOf(d);-1!=d&&(b.types.splice(d,1),a.splice(d,1))};this.equals=function(a){if(!a||!hi5.Arrays.equals(b.types,a.types))return!1;for(var c,d,n=b.types,y=0,e=n.length;y<e;y++)if(c=n[y],d=b.getData(c),c=a.getData(c),d!=c)return!1;return!0}}function F(){Wa=!0;ta=!1;if(p){var a=p.element;a.removeEventListener("copy",q.onCopy,!1);a.removeEventListener("cut",q.onCopy,!1)}svGlobal.logger.info("Async clipboard enabled.")}
function x(a){function b(){return L?a.value:m.isFirefox?a.textContent:a.innerText}function d(){u&&(A="",u.setValue(""))}function c(a){h=a.keyCode;if(u.onkeydown)u.onkeydown(a)}function f(a){if(u.onkeyup)u.onkeyup(a);a=a.keyCode;(13==a||32==a&&32==h)&&setTimeout(d,100)}function n(a){if(u.onbackspace)for(var c=0;c<a;c++)u.onbackspace()}function y(c){if(!u.disableTextInput){c.stopPropagation();c=b();var f=c.length;if(c!=A){var y=A.length,L=c.indexOf(A);if(c&&0===L){if(c=c.substring(y),0<c.length&&u.ontextinput&&
(u.ontextinput({data:c,target:a}),"."==c)){d();return}}else if(L=A.indexOf(c),0===L)8!=h&&n(y-f);else if(m.isAndroid&&n(y),0<c.length&&u.ontextinput)u.ontextinput({data:c,target:a});""===b()&&setTimeout(d,100);A=b()}}}function e(a){if(!u.disableTextInput&&a.data&&(a.stopPropagation(),ba&&a.preventDefault(),u.ontextinput))u.ontextinput(a)}function g(a){if(u.oncomposition)u.oncomposition(a)}this.unicode=!1;var u=this,A="",h=0,L="INPUT"==a.nodeName||"TEXTAREA"==a.nodeName,k="DIV"==a.nodeName;this.setValue=
function(c){var b=u.disableTextInput;u.disableTextInput=!0;L?a.value=c:k&&(a.innerHTML=c);u.disableTextInput=b};this.init=d;this.disableTextInput=!1;d();a.addEventListener("keydown",c,!1);a.addEventListener("keyup",f,!1);a.addEventListener("keypress",function(a){if(u.onkeypress)u.onkeypress(a)},!1);m.isAndroid&&m.isChrome?(a.addEventListener("input",y,!1),a.addEventListener("mouseup",d,!1)):window.TextEvent?(a.addEventListener("textInput",e,!1),a.addEventListener("textinput",e,!1)):hi5.tool.hasProperty(InputEvent,
"data")?a.addEventListener("input",e,!1):(a.addEventListener("input",y,!1),a.addEventListener("mouseup",d,!1));a.addEventListener("compositionstart",g,!1);a.addEventListener("compositionend",g,!1);a.addEventListener("compositionupdate",g,!1);this.release=function(){u=null;a.removeEventListener("keydown",c,!1);a.removeEventListener("keyup",f,!1);a.removeEventListener("input",y,!1);a.removeEventListener("focus",d,!1);a.removeEventListener("textInput",e,!1);a.removeEventListener("textinput",e,!1);a=
null};this.select=function(){lb(a)}}function W(a,b,d){function c(a){var c=Ha(a);var d=a.deltaMode||0;var u=!!a.deltaX||!!a.wheelDeltaX;a.preventDefault();a.stopPropagation();if(1==d)b(-a.deltaY||-a.deltaX,c,u);else{var A="deltaY"in a?40:"wheelDelta"in a?120:0;if(A){d=Date.now();100<d-n&&(f=0);var e=-a.deltaY||-a.deltaX||a.wheelDelta;0!=e&&(f+=e,a=f/A|0,f%=A,0!==a&&b(a,c,u));n=d}else a=-a.detail,32768==Math.abs(a)&&(e=window.innerHeight/40|0,a=0>a?-e:e),b(a,c,!1)}}var f=0,n=0;a.addEventListener("DOMMouseScroll",
c,!0);a.addEventListener("mousewheel",c,!0)}function ua(a){function b(a){if(!n&&e.onmousedown)e.onmousedown(a)}function d(a){if(!n&&e.onmousemove)e.onmousemove(a)}function c(a){if(g&&g.focused)if(n)n=!1;else if(e.onmouseup)e.onmouseup(a)}function f(a){"touchstart"==a.type&&(n=!0);if(e.ontouch)e.ontouch(a)}var n=!1,e=this,h=navigator.pointerEnabled||navigator.msPointerEnabled||!1;"ontouchstart"in window||!h?(a.addEventListener("touchstart",f,!1),a.addEventListener("touchend",f,!1),a.addEventListener("touchmove",
f,!1),a.addEventListener("touchcancel",f,!1),document.addEventListener("mousemove",d,!1),a.addEventListener("mousedown",b,!1),document.addEventListener("mouseup",c,!1)):navigator.pointerEnabled?(a.addEventListener("pointerdown",f,!1),a.addEventListener("pointerup",f,!1),a.addEventListener("pointermove",f,!1),a.addEventListener("pointercancel",f,!1)):navigator.msPointerEnabled&&(a.addEventListener("MSPointerDown",f,!1),a.addEventListener("MSPointerUp",f,!1),a.addEventListener("MSPointerMove",f,!1),
a.addEventListener("MSPointerCancel",f,!1));this.release=function(){"ontouchstart"in window||!h?(a.removeEventListener("touchstart",f,!1),a.removeEventListener("touchend",f,!1),a.removeEventListener("touchmove",f,!1),a.removeEventListener("touchcancel",f,!1),document.removeEventListener("mousemove",d,!1),a.removeEventListener("mousedown",b,!1),document.removeEventListener("mouseup",c,!1)):navigator.pointerEnabled?(a.removeEventListener("pointerdown",f,!1),a.removeEventListener("pointerup",f,!1),a.removeEventListener("pointermove",
f,!1),a.removeEventListener("pointercancel",f,!1)):navigator.msPointerEnabled&&(a.removeEventListener("MSPointerDown",f,!1),a.removeEventListener("MSPointerUp",f,!1),a.removeEventListener("MSPointerMove",f,!1),a.removeEventListener("MSPointerCancel",f,!1));this.onmouseup=this.onmousemove=this.ontouch=this.onmousedown=null}}function Ia(){return ca?!0:!fa&&J<=window.innerWidth&&K<=window.innerHeight}function Vb(a){function b(a,b){for(var d,f=a.length,u=Array(f),A=0;A<f;A++){d=a[A];var n=Ja(d.clientX,
d.clientY,e),L=A;d=d.identifier;if(!(256>d)){var y=c.indexOf(d);-1!=y?d=y:(c.push(d),d=c.length-1)}u[L]={contactId:d,contactFlags:b,x:n.x,y:n.y}}return u}var d,c=[],f=!1;this.handle=function(n){var e=n.type,g=n.touches,h=n.changedTouches;cancelDefault(n);switch(e){case "touchstart":f=!1;d=n=b(g,25);break;case "touchmove":n=b(h,26);d||(d=b(g||h,25));g=!1;if(0<d.length&&1==n.length){a:{h=d.length;for(e=0;e<h;e++)if(d[e].contactId==n[0].contactId){h=e;break a}h=-1}-1!=h&&d[h].x==n[0].x&&d[h].y==n[0].y&&
(g=!0)}if(g)break;else 0<d.length&&(a.redirectTouches(d),d.length=0);a.redirectTouches(n);f=!0;break;case "touchend":if(f)n=b(h,4);else{a.redirectTouches(d);n=d.length;for(g=0;g<n;g++)d[g].contactFlags=4;n=d}a.redirectTouches(n);c.length=d.length=0;break;case "touchcancel":a.redirectTouches(b(h,34)),c.length=d.length=0}}}function mb(a){function b(a){var c=a[1].screenX-a[0].screenX;a=a[1].screenY-a[0].screenY;return Math.sqrt(c*c+a*a)}function d(a,d){var u=[],f=c(a,t[0].identifier)||c(d,t[0].identifier);
f&&u.push(f);(f=c(a,t[1].identifier)||c(d,t[1].identifier))&&u.push(f);f="";if(2!=u.length)return f;var A=b(u)-b(t);60>Math.abs(A)?80<u[0].screenX-t[0].screenX?f="RIGHT":80<t[0].screenX-u[0].screenX?f="LEFT":80<u[0].screenY-t[0].screenY?f="DOWN":80<t[0].screenY-u[0].screenY&&(f="UP"):f=0>A?"CLOSE":"OPEN";return f}function c(a,c){for(var b=0,d=a.length;b<d;b++)if(a[b].identifier==c)return a[b];return null}function f(a){this.identifier=a.pointerId;this.clientX=a.clientX;this.clientY=a.clientY;this.pageX=
a.pageX;this.pageY=a.pageY;this.screenX=a.screenX;this.screenY=a.screenY}var n=0,g=0,h=0,k=0,u=!1,A=0,Ga=0,L=0,q=0,l=!1,p=!1,r=3,v=!1;ba&&(r*=3);this.delay=!1;var t=[],m=this;this.handlePointer=function(a){if(a.pointerType==a.MSPOINTER_TYPE_MOUSE||"mouse"==a.pointerType)switch(a.type){case "MSPointerDown":case "pointerdown":Xa(a);break;case "pointermove":case "MSPointerMove":Ya(a);break;case "pointerup":case "MSPointerUp":Za(a)}else a.touches=a.changedTouches=[new f(a)],m.handle(a)};this.handle=function(b){var f=
b.type,y=b.touches;var C=b.changedTouches;var M=0,m=0;switch(f){case "touchstart":case "MSPointerDown":case "pointerdown":v=!1;g="touchstart"==f?y.length:g+1;p=!1;k=Date.now();u=1==g&&200>k-h;f=y[0];n=f.identifier;m=Ja(f.clientX,f.clientY,e);A=m.x|0;Ga=m.y|0;l=!0;2!=y.length?v=!1:(M=y[1].screenX-y[0].screenX,v=100<Math.abs(y[1].screenY-y[0].screenY)||350<Math.abs(M));(u||1<g&&!v)&&cancelDefault(b);if(3==g){f=m=M=0;C=9999;for(var w=0,x=y.length;w<x;w++)y[w].screenY>f&&(f=y[w].screenY,M=w),y[w].screenY<
C&&(C=y[w].screenY,m=w);t=[{screenX:y[m].screenX,screenY:y[m].screenY,identifier:y[m].identifier},{screenX:y[M].screenX,screenY:y[M].screenY,identifier:y[M].identifier}]}break;case "pointermove":case "MSPointerMove":if(1<g)break;case "touchmove":if(v)return;f=C[y.length-1];if(!f)break;if(f.identifier!=n&&(f=c(C,n),!f)){cancelDefault(b);return}m=Ja(f.clientX,f.clientY,e);M=m.x|0;m=m.y|0;if(l){if(0===M-A&&0===m-Ga)return;if(Math.abs(M-A)<r&&Math.abs(m-Ga)<r){cancelDefault(b);return}l=!1;C=Date.now()-
k;if((p=88>C)&&!Ia()&&1==g){v=!0;return}a.touchstart({x:A,y:Ga,flick:p,pointes:g,screenX:f.screenX,screenY:f.screenY,moved:!0,target:b.target})}cancelDefault(b);a.touchmove({x:M,y:m,flick:p,pointes:g,moved:!0,screenX:f.screenX,screenY:f.screenY,target:b.target});break;case "MSPointerUp":case "touchend":case "pointerup":if(v)return;if(3==C.length+y.length){a.touchend({x:M,y:m,flick:p,pointes:g,moved:!l,target:b.target,gesture:d(y,C)});g=0;break}else{if(2<g){g=0;break}if(f=c(C,n))y=Date.now(),m=Ja(f.clientX,
f.clientY,e),M=m.x|0,m=m.y|0,p?a.touchend({x:M,y:m,flick:!0,pointes:g,moved:!l,screenX:f.screenX,screenY:f.screenY,target:b.target}):(C=y-k,l?(h=y,u?cancelDefault(b):(L=M,q=m),500>C?(h=y,a.touchstart({x:L,y:q,flick:!1,pointes:g,screenX:f.screenX,screenY:f.screenY,moved:!1,target:b.target}),a.touchend({x:L,y:q,flick:!1,pointes:g,moved:!1,screenX:f.screenX,screenY:f.screenY,target:b.target})):a.longpress({x:M,y:m,flick:!1,pointes:g,moved:!1,screenX:f.screenX,screenY:f.screenY,target:b.target})):a.touchend({x:M,
y:m,flick:!1,pointes:g,moved:!0,screenX:f.screenX,screenY:f.screenY,target:b.target}))}g=0;break;case "MSPointerCancel":case "touchcancel":g=0}u&&cancelDefault(b)}}function Wb(){v(!0,14);v(!1,14)}function lb(a){try{a.select?a.select():m.selectEditable(a)}catch(b){svGlobal.logger.info(b)}}function nb(){function a(){f.focus()}function b(c,b){var d=document.createElement("a");d.href="#";d.accessKey=c;d.onfocus=a;d.style.position="absolute";d.style.width=1;d.style.height=1;d.style.left=0;d.style.top=
b+"px";d.style.pointerEvents="none";return d}var d=g.forceTextArea||ba,c=document.createElement(d?"textarea":"div"),f=this;this.element=c;this.setFontSize=function(a){c.style.fontSize=r.inputFontSize||a};d?(c.style.opacity=0,c.readOnly=S&&m.isMetro?!0:!1):c.contentEditable=!S||(m.isChrome||m.isFirefox)&&(m.isWindows||m.isCrOS)?!0:!1;c.setAttribute("autocomplete",m.isChrome?"new-password":"off");c.setAttribute("autocorrect","off");c.setAttribute("autocapitalize","off");c.setAttribute("spellcheck",
"false");c.accessKey="f";c.id="wsinput";c.tabIndex=1;c.style.opacity=0;c.style.resize="none";c.style.position="absolute";c.style.margin="0";c.style.border="none";c.style.outline="none";var n=hi5.tool.getPos(e,!0);c.style.left=n.x+"px";c.style.top=n.y+"px";c.style.paddingRight=0;c.style.paddingBottom=0;c.style.width="10px";c.style.height="10px";c.style.zIndex=88;c.style.cursor="default";c.style.fontWeight="normal";c.style.fonStyle="normal";c.style.overflow="hidden";S&&(c.style.fontSize="2em");m.isiOS?
(c.addEventListener("focus",function(a){setTimeout(function(){a.target.style.fontSize="0px"},333)},!1),c.addEventListener("blur",function(a){a.target.style.fontSize="1em"},!1)):m.isFirefox?c.style.fontSize=0:d?c.style.fontSize="1px":m.isChrome||(c.style.textIndent="-999em");G=new x(c);G.onbackspace=Wb;n=e.parentNode;n.appendChild(c);m.isIE&&(n.appendChild(b("E"),60),n.appendChild(b("V"),61),n.appendChild(b("A"),62),n.appendChild(b("T"),63),n.appendChild(b("H"),64));var h=c.style.opacity,C=c.style.textIndent||
0;this.resetCSS=function(){_fontSize=c.style.fontSize;h=c.style.opacity;c.style.opacity=0;c.style.textIndent=0};this.restoreCSS=function(){c.style.opacity=h;c.style.textIndent=C};this.getValue=function(){return d?c.value:c.innerHTML};this.setValue=function(a){G&&(G.disableTextInput=!0);d?c.value=a:c.innerHTML=a;G&&(G.disableTextInput=!1)};this.focus=function(){f.setValue(" ");B(c)};this.setContentEditable=function(a){d?(a="true"==a,c.readOnly==a&&(c.readOnly=!a)):c.setAttribute("contenteditable",
a)};this.isIMEMode=!1;this.adjust=function(a){var b=hi5.tool.getPos(e,!0);w.offX=b.x;w.offY=b.y;var d=g.railWin?Math.min(window.innerWidth-b.x,J):J,f=g.railWin?Math.min(window.innerHeight-b.y,K):K;if(S){var n=Math.max(window.pageXOffset+100,b.x);a=Math.max(window.pageYOffset+100,b.y)}else{var h=Math.min(window.innerHeight-b.y,K);n=Math.round(.7*Math.min(window.innerWidth-b.x,J));a=Math.round(h*(a?.99:.7))}d-=n;f-=a;r.disableAdjust&&(a=n=0,d=e.offsetWidth,f=e.offsetHeight);c.style.width=d+"px";c.style.height=
f+"px";c.style.paddingLeft=n+"px";c.style.paddingTop=a+"px";c.style.left=b.x+"px";c.style.top=b.y+"px"};this.remove=function(){G&&(G.release(),G=null);c.parentNode&&c.parentNode.removeChild(c);c=null};this.hide=function(){c.style.visibility="hidden"};this.getElement=function(){return c};this.select=function(){lb(c)}}function va(a){function b(){r.text||(r.text={});return r.text}function d(a,c,d,f,e){if(n){var u=b();a.fillStyle=u.backgroundFillStyle||"white";a.fillRect(c,d-e+2,f,e);a.fillStyle=u.fillStyle||
"#337788";a.textBaseline="bottom";a.fillText(n,c+3,d-2);a.strokeStyle=k.getColor(n);a.lineWidth=2;a.beginPath();a.moveTo(c,d);a.lineTo(c+f,d);a.stroke()}}function c(){var a=h.getContext("2d"),c=a.getImageData(0,0,h.cursorWidth,h.cursorHeight);if(n){a.font=b().font||"11px Arial";var f=1.2*(a.measureText("W").width+1)+4;h.width=Math.max(h.cursorWidth,a.measureText(n).width+4);h.height=h.cursorHeight+f;d(a,0,h.height-1,h.width,f)}else h.width=h.cursorWidth,h.height=h.cursorHeight;a.putImageData(c,0,
0)}if(!h){var f=e.parentNode,n="",g=0;h=f.querySelector('canvas[name="svImgCursor"]');if(!h){h=document.createElement("canvas");h.setAttribute("name","svImgCursor");h.style.position="absolute";h.style.left=90;h.style.top=90;h.scrX=0;h.scrY=0;h.hotX=0;h.hotY=0;h.width=h.height=32;h.__left=0;h.__top=0;h.__visible=!1;h.style.visibility="hidden";h.style.zIndex=87;var C=null;r.disableClickEffect||(C=document.createElement("div"),C.className="mouse-click-off",C.style.zIndex=89);var k={getColor:function(a){if(k[a])return k[a];
var c=hi5.graphic.colorTable.getNext();return k[a]=c}};h.setCursor=function(c){var u=c.width,f=c.height,e=c.rawData,g=0,y=0,C=h.getContext("2d");n&&(C.font=b().font||"11px Arial",g=C.measureText(n).width,y=1.2*(C.measureText("W").width+1)+4);if(a)if(n){if(a){h.cursorWidth=g;h.cursorHeight=y;h.hotX=c.hotX;h.hotY=-f;h.width=g;h.height=y+4;d(C,0,h.height-1,h.width,y);return}}else h.__setVisible(!1);if(e&&u&&f){var k=u*f,l=0,p=C.createImageData(u,f),m=p.data,q=c.hotX-h.hotX,r=c.hotY-h.hotY;h.cursorWidth=
u;h.cursorHeight=f;h.hotX=c.hotX;h.hotY=c.hotY;h.width=Math.max(u,g+4);h.height=f+y+4;n&&d(C,0,h.height-1,h.width,y);for(g=0;g<k;g++)c=e[g],m[l++]=c&255,m[l++]=c>>8&255,m[l++]=c>>16&255,m[l++]=c>>24&255;C.putImageData(p,0,0,0,0,u,f);h.__left-=q;h.__top-=r;h.style.left=h.__left+"px";h.style.top=h.__top+"px"}};h.__setVisible=function(a){h.__visible=a;h.style.visibility=a?"visible":"hidden"};Y&&Y.rawData?h.setCursor(Y):h.setCursor({rawData:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,
-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,-16777216,-16777216,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,-16777216,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],width:32,height:32,hotX:10,
hotY:10});h.moveCursor=function(a,b,d,f,e){var u=a-h.hotX,A=b-h.hotY;h.__left=u;h.__top=A;h.style.left=u+"px";h.style.top=A+"px";if(n!=d||g!=f)n=d,g=f,c();C&&e&32768&&(C.style.left=a-30+"px",C.style.top=b-30+"px",C.className="mouse-click-on",setTimeout(function(){C.className="mouse-click-off"},500))};f.appendChild(h);C&&f.appendChild(C)}}}function $a(a){if(!1!==r.disableScrollbars){var b=document.body;a?(ab=a,b.style.overflow=a):(ab=J<=window.innerWidth&&K<=window.innerHeight?"hidden":"visible",b.style.overflow=
ab)}}function wa(a){var b=e.parentNode,d=window.innerWidth,c=window.innerHeight;Math.max(J,K)<Math.max(d,c)&&Math.min(J,K)<Math.min(d,c)?1!=P&&(hi5.tool.scale(b,1),P=X=1):(document.body.style.overflow="hidden",P=X=a?Math.min(window.innerWidth/J,window.innerHeight/K):1,hi5.tool.scale(b,P,P))}function bb(){if(g.toolbar)g.toolbar.removeButton("svCloud");else{var a=hi5.$("svCloud");a&&a.parentNode.removeChild(a)}}function ob(){var a=chrome.app.window.current();a&&a.fullscreen()}function Xb(){xa=null;
ga&&(ga.release(),ga=null);if(document){if(p){var a=p.element;document.removeEventListener("mousemove",Ya,!1);a.removeEventListener("mousedown",Xa,!1);document.removeEventListener("mouseup",Za,!1);a.removeEventListener("mouseleave",Ka,!1);a.removeEventListener("mouseenter",Ka,!1);a.removeEventListener("paste",q.onPaste,!1);a.removeEventListener("copy",q.onCopy,!1);a.removeEventListener("cut",q.onCopy,!1);a.removeEventListener("focus",pb,!1);a.removeEventListener("blur",qb,!1)}q&&(document.removeEventListener("paste",
q.onPaste,!1),document.removeEventListener("copy",q.onCopy,!1),document.removeEventListener("cut",q.onCopy,!1))}if(window){window.removeEventListener("resize",rb,!1);window.removeEventListener("beforeunload",sb,!1);window.removeEventListener("unload",La,!1);Y=null;h&&(h.parentNode&&h.parentNode.removeChild(h),h=null);g&&g.toolbar&&(g.toolbar.setFadable=null,g.toolbar.startFade=null,g.toolbar.style.display="none",hi5.ui.clean(g.toolbar),g.toolbar=null);try{ya&&ya.parentNode&&(ya.parentNode.removeChild(ya),
ya=null),p&&(p.remove(),p=null)}catch(b){}}}function cb(a,b){var d=document.getElementById("_tmpEditable");a||(a="div");var c=document.body;d&&d.nodeName!=a.toUpperCase()&&(c.removeChild(d),d=null);d||(d=document.createElement(a),d.id="_tmpEditable","div"==a&&!1!==b&&(d.contentEditable=!0,ba&&(d.style.textIndent="-999px")),d.style.position="absolute",d.style.zIndex=9999,d.style.left=c.scrollLeft+50+"px",d.style.top=c.scrollTop+50+"px",d.style.width="4px",d.style.height="4px",d.tabIndex=2,d.style.outline=
"none",d.style.opacity=0,d.style.overflow="hidden",c.appendChild(d));return d}function pb(a){if(!g.focused){za.clearPDF();g.focused=!0;if(l)l.onfocus(a);g.focusTime=Date.now();Z&&(U=l.fromSyncedSurface?l.fromSyncedSurface(200):!1,U||(q&&(q.clipData=null),g.onreqpaste||Wa?l.send("8911"):q.read(function(a){a&&!a.equals(q.clipData)?(l.send("8911"),q.clipData=a):l.send("8910")})));l&&(l.checkLockFlags=!0);z.noKeyStuck||z.sendMissKey();z.ctrlDelayed&&(z.ctrlDelayed=!1)}}function sb(a){var b=__svi18n.remoteApp.close;
if(!tb&&g.railWin&&g.railWin.isRunning()&&b&&(a||(a=window.event),2!=l.getAppMode()))return g.showMessage(b),a&&(a.returnValue=b),b}function La(a){if(g&&(g.focused=!1,g.onunload))g.onunload()}function ub(){p&&(p.element.oncontextmenu=function(){return!1},ba||(p.element.onselectstart=function(){return!1}))}function rb(a){p&&p.adjust();if(oa)wa(!0);else if(!(fa&&2500>Date.now()-fa)){var b=m.isWindows&&!m.isMetro;if(!S||b&&!fa||m.isCrOS||m.isChromeApp)l.onresize(a)}}function qb(a){g&&(g.focused=!1,g.blurTime=
Date.now())}function Yb(){window.svSurface||(window.svSurface=g);window.addEventListener("resize",rb,!1);if(!ha){var a=!m.isChromeApp;a&&window.addEventListener("beforeunload",sb,!1);a?window.addEventListener("unload",La,!1):chrome.runtime.onSuspend.addListener(La);ub();p.element.addEventListener("focus",pb,!1);p.element.addEventListener("blur",qb,!1);m.isChromeApp&&!r.disableMaxFullScn&&chrome.app.window.current().onMaximized.addListener(ob);(a=hi5.$("saveSession"))&&a.addEventListener("change",
function(a){l.saveSession({save:a.target.checked})});if(a=hi5.$("reqFullscr"))a.onclick=function(a){g&&g.requestFullscreen(!0)}}}function vb(){if(!da){var a=hi5.$("touchGesture");a&&(a.style.display="block");if(a=hi5.$("extKBD"))a.onchange=function(a){g.setExtKeyboard(a.target.checked)};da=hi5.$("svTouchInput");try{window.parent==window||da||(da=window.parent.document.getElementById("svTouchInput"))}catch(b){}da&&"IMG"!=da.nodeName&&(a=document.createElement("img"),a.id="svTouchInput",a.src=r.img&&
r.img.kbd||"kbd.png",da.parentNode.replaceChild(a,da),da=a)}}function ia(a,b){function d(a,c){var d=document.createElement("span");d.data_path=a;d.className="path";d.innerHTML=c;d.onclick=function(){ia(this.data_path,b)};return d}function c(a){for(var c=f;c.hasChildNodes();)c.removeChild(c.firstChild);var b=d("/","&nbsp&nbsp&nbsp/");c.appendChild(b);if("/"!=a&&""!==a){a=a.split("/");for(var u="/",A=0,n=a.length;A<n;A++)b=a[A],""!==b&&(u=u+a[A]+"/",b=d(u,b+"/"),c.appendChild(b))}}var f=hi5.$("parentPath");
f.currentDir||(f.currentDir="/");"."==a?a=f.currentDir:f.currentDir=a;f.currentDir=a;b?b.visible()?hi5.tool.disableInput(hi5.$("filecontainer")):b.onopen=function(){hi5.tool.disableInput(hi5.$("filecontainer"))}:hi5.tool.disableInput();var n=new hi5.DataGrid(hi5.$("filelist"));n.clear();l.getShareFiles(a,function(a){function d(c){c||(c=n.getValue("Name"));var b=a.parent;if(""===b||"/"!=b.charAt(b.length-1))b+="/";if("."==c)return b;if(".."==c){if(1==b.length)return b;var d=b.lastIndexOf("/",b.length-
2);if(-1!=d)return b.substring(0,d+1)}return b+c}a.error&&__svi18n.file[a.error]&&g.showMessage(__svi18n.file[a.error]);var f=new hi5.DataTable(a);n.dataTable=f;var u=hi5.tool.bytesToSize;n.beforeDisplayValue=function(a,c){var b=f.cols[a].name;return"Date Modified"==b?(new Date(c)).toLocaleString():"Size"==b?u(c):"Type"==b&&"folder"==c?__svi18n.file.folder:"Name"==b?decodeURIComponent(c):c};n.onrowclick=function(c){var u=n.getValue("Name"),f=n.getValue("Type"),u=d(u);c=c.target.name;"delete"==c?(H.removeFile(u),
ia(a.parent,b)):"folder"==f?ia(u,b):("view"==c&&(u+="&action=view"),c&&l.getFile(u))};n.beforeAppendRow=function(a){var c;if("folder"==f.getValue(f.getColNo("Type"))){if(c=a.querySelector('img[name="download"]'))c.style.visibility="hidden"}else{c=n.getValue("Name");var b=d(c),b="application/octet-stream:"+c+":"+l.getFileLink(b);a.addEventListener("dragstart",function(a){a.dataTransfer.setData("DownloadURL",b)},!1);if(10<c.length&&".uploading"==c.substring(c.length-10)){if(c=a.querySelector('img[name="download"]'))c.style.visibility=
"hidden";if(c=a.querySelector('img[name="view"]'))c.style.visibility="hidden"}}};n.open();c(a.parent);var A=document.getElementById("__diskSpace");A&&(A.innerHTML=hi5.tool.bytesToSize(a.freeSpace)+"/"+hi5.tool.bytesToSize(a.totalSpace));b&&(b.__position="\\\\tsclient\\"+a.name+a.parent.replace(RegExp("/","g"),"\\"),b.__workdir=a.parent);hi5.tool.enableInput()})}function wb(a){H&&(a&&cancelDefault(a),a=hi5.$("filecontainer"),V=new hi5.ui.Lightbox(a),ia(".",V),V.show(),V.onclose=function(){hi5.tool.enableInput();
g.focus()},(a=document.getElementById("__sv_folder__"))&&H.mkdirs&&(a.onclick=function(){var a=document.getElementById("__sv_folder_name_");a&&a.value&&(H.mkdirs(a.value),ia(".",V),a.value="")}),a=document.getElementById("__sv_position__"))&&(a.onclick=function(){l.setWorkDir&&l.setWorkDir(V.__position,V.__workdir);V.dismiss()})}function xb(){var a=k.toolbar;if(a){for(var b=a.childNodes,d=!1,c=0,f=b.length;c<f;c++)if(1==b[c].nodeType&&-1==["svTouchInput","svCloud","svInfo"].indexOf(b[c].id)){d=!0;
break}if(b=hi5.$("appinfo"))b.className="h5-form";if(g.showToolbar||S||H||b||d){a.style.left=.45*window.innerWidth+"px";if(d=null===g.toolbar)g.toolbar=new hi5.Toolbar(a,r.toolbar.draggable,r.img.handle||"handle.png");S||(a=hi5.$("svTouchInput"))&&a.parentNode.removeChild(a);if(a=g.toolbar.getButton("svCloud"))H?(a.style.display="",a.onclick=wb):a.style.display="none";new hi5.Fadable(g.toolbar,r.toolbar.fadeDelay||5E3,p.element,"inline-block");a=r.toolbar.fadable;g.toolbar.setFadable(a);a&&(g.toolbar.style.display=
"none");if(a=g.toolbar.getButton("svInfo"))b?(a.style.display="",d&&(a.onclick=function(a){cancelDefault(a);g.showConnectonInfo()})):a.style.display="none";if(g.onloadtoolbar)g.onloadtoolbar(g.toolbar)}}}function yb(a){H.addFiles(a.target.files,!1);a=hi5.$("uploadfile");var b=a.cloneNode(!0);a.parentNode.replaceChild(b,a);b.addEventListener("change",yb,!1)}function Zb(){var a=p.element;ea&&ea.release();ea=new svGlobal.util.MapDisk(a,H,!0);hi5.$("filecontainer")&&(Ma=new svGlobal.util.MapDisk(hi5.$("filecontainer"),
H,!1),hi5.$("uploadfile").addEventListener("change",yb,!1))}function Ka(a){h&&h.__setVisible(!1)}function zb(a){var b;if(E){if(a-db>Ab)if(w.isMultiMon){if(b=Aa(w.left,w.top,w.right,w.bottom))E.putImageData(b.imgData,b.left-w.left,b.top-w.top,0,0,b.width,b.height),db=a}else if(b=Aa(0,0,w.right,w.bottom))E.putImageData(b.imgData,b.left,b.top,0,0,b.width,b.height),db=a;Na=requestAnimationFrame(zb)}}function Bb(a,b,d,c){h||va(r.cursorNameOnly);h.__visible||h.__setVisible(!0);a=h.scrX+a;b=h.scrY+b;0>a?
a=0:a>J&&(a=J-1);0>b?b=0:b>K&&(b=K-1);h.scrX=a;h.scrY=b;var f=a-h.hotX,n=b-h.hotY;ba&&(f=f/P|0,n=n/X|0);h.style.left=f+w.offX+"px";h.style.top=n+w.offY+"px";O&&!d&&l.sendInput("82"+a+"\t"+b);w.x=a;w.y=b;c&&(d=h.getBoundingClientRect(),3>d.top?window.scrollBy(0,-20):3>d.left?window.scrollBy(-20,0):d.bottom>window.innerHeight?window.scrollBy(0,20):d.right>window.innerWidth&&window.scrollBy(20,0))}function pa(a,b,d){a=a/P|0;b=b/X|0;g.moveCursor(a,b,d)}function Va(a){p?p.setContentEditable(a?"true":"false"):
document.getElementById("wsinput")&&input.setAttribute("contenteditable",a?"true":"false");fa=a?1:0;Q&&Q.setVisibility(a);if(g.toolbar){var b=g.toolbar.getButton("svTouchInput");b&&(b.className=a?"h5-img-btn-on":"h5-img-btn")}}function eb(){(sa=!sa)&&p&&p.adjust();Va(sa);p&&(p.element.blur(),p.element.focus())}function fb(a,b,d,c){switch(a){case "touchstart":gb=!1;0===h.scrX&&0===h.scrY&&pa(b-50,d-50);c&&(g.beforemousedown&&g.beforemousedown(h.scrX,h.scrY,0),l.sendInput("80"+h.scrX+"\t"+h.scrY+"\t0"));
break;case "touchmove":c=b-Oa;a=d-qa;if(0===c&&0===a)return;var f=5>Math.abs(Cb)&&5>Math.abs(Db)&&(7<Math.abs(c)||7<Math.abs(a));f||(Bb(c,a,!1,!0),gb=!0);Cb=c;Db=a;break;case "touchend":if(a=!gb&&!c)g.beforemousedown&&g.beforemousedown(h.scrX,h.scrY,0),l.sendInput("80"+h.scrX+"\t"+h.scrY+"\t0");if(a||c)l.sendInput("81"+h.scrX+"\t"+h.scrY+"\t0"),g.aftermouseup&&g.aftermouseup(h.scrX,h.scrY,0)}Oa=b;qa=d}function $b(a){O&&la&&(a.touches||a.changedTouches?la.handle(a):la.handlePointer(a))}function ac(a){if(!O)return!1;
if("false"==p.element.contentEditable&&(m.isiOS||m.isAndroid))return Eb(a);a.stopPropagation();z.check(a);var b=I.getKeyCode(a),d="keydown"==a.type;if(Fb(a,b,d))return cancelDefault(a);17!=b||d||(ma=!1,Pa&&z.preKey.down&&aa(!1,z.preKey.code,I.getScancodeByKeyCode(z.preKey.code)));var c=I.getScancode(a),f=I.isPrintableScancode(c,a);3==a.location&&(f=89==c?!0:!1);if(!f){z.afterComposition&&d&&(z.afterComposition=!1);if(z.onComposition||z.afterComposition&&!d)return!0;z["continue"](d,c,!0)&&v(d,c);if(17==
b||(T||a.metaKey)&&(86==b||67==b||88==b))return d&&(17==b&&ta&&p&&na&&(a.target==p.element?(p.setValue("Copying... Please try again"),p.select()):(R.setValue("Copying... Please try again"),R.select())),67==b||88==b)&&(ma=!0),17!=b||d||(ma=!1),!0;3==a.location?z.noUnicode=!0:d&&(z.noUnicode=!1);return cancelDefault(a)}(f=z.isAltGr(d))?ja=T=!1:z.noUnicode&&(z.noUnicode=!1);f=!f&&(a.ctrlKey||a.altKey||a.metaKey);if(a.altKey&&f&&70<c&&83>c&&74!=c&&78!=c){if(56==z.preScancode.code||184==z.preScancode.code)v(!0,
1),v(!1,1);f=!1}if(f)return(86!=b||!a.ctrlKey&&!a.metaKey||a.ctrlKey&&a.altKey||!Z)&&aa(d,b,I.getScancode(a)),d&&(Qa=b),17==b||(a.ctrlKey||a.metaKey)&&(86==b||67==b||88==b)?(!d||67!=b&&88!=b||(ma=!0),!0):a.altKey&&!a.ctrlKey||a.ctrlKey&&!a.altKey||a.metaKey?cancelDefault(a):!0;if(!(b!=Qa||d||a.ctrlKey&&a.altKey))return aa(!1,b,I.getScancode(a)),Qa=0,cancelDefault(a);Qa=0;return!0}function bc(a){z.onComposition="compositionend"!=a.type;z.afterComposition=!z.onComposition}function Fb(a,b,d){switch(b){case 8:case 35:if(!T&&
!a.metaKey||!a.altKey||r.disableShortcuts||3==a.location)return!1;v(d,211);break;case 33:if(!a.altKey||r.disableShortcuts||3==a.location)return!1;v(d,15);break;case 34:if(!a.altKey||r.disableShortcuts||3==a.location)return!1;d?(v(!0,42),v(!0,15)):(v(!1,15),v(!1,42));break;case 45:if(!a.altKey||r.disableShortcuts)return!1;v(d,1);break;case 36:if(!a.altKey||r.disableShortcuts||3==a.location)return!1;d?(v(!1,56),v(!0,29),v(!0,1)):(v(!1,1),v(!1,29));break;default:return!1}return!0}function Eb(a){if(!O)return!1;
z.check(a);var b=I.getKeyCode(a),d="keydown"==a.type,c=I.getScancode(a);if(Fb(a,b,d))return cancelDefault(a);var f=86==b&&(Gb&&!d||(a.ctrlKey||a.metaKey)&&!(a.ctrlKey&&a.altKey))&&Z;if(0<c)if(f)Ra&&d&&Ra.sendCtrlVLater();else if(z["continue"](d,c,!1)){if(44==b){d||(T||a.shiftKey?(v(!0,183),v(!1,183)):(v(!0,170),v(!0,183),v(!1,183),v(!1,170)));var n=!0}else n=!1;if(n)return cancelDefault(a);v(d,c)}17!=b&&(Gb=f);return 17==b||(T||a.metaKey)&&(86==b||67==b||88==b)?(d&&(17==b&&ta&&p&&na&&(p.setValue("Copying... Please try again"),
p.select()),67==b||88==b)&&(ma=!0),17!=b||d||(ma=!1),!0):144==b||16==b?!1:cancelDefault(a)}function cc(a){if(O)if(z.noUnicode)z.noUnicode=!1;else if(a=a.data,"`\t`"!=a){var b=T||ja;b&&(a=a.toLowerCase());a=a.replace(/\u00a0/g," ");if(g.onunicode){var d=g.onunicode(a);d&&(b=d.ctrl||d.alt)}r.scancode&&r.scancode[a]?(ka(!0,r.scancode[a]),ka(!1,r.scancode[a])):l.sendInput("86"+a+"\t"+(b||Hb?1:0));Q&&Q.resetModifier()}}function Ib(a,b){var d=a?a.getData(b):null;!d&&a&&(d=a.getData(a.types[0]));if(d&&"text/plain"==
b){for(var c=0,f="",n=d.length;c<n&&(f=d.charAt(c),"\r"==f||"\n"==f);c++);c&&(d=d.substring(c))}if(d)return l.send("881"+b+"\t"+d),a.sent=Date.now(),!0;if(g.onreqpaste)return g.onreqpaste(b,function(a){l.send("881"+b+"\t"+a)},function(){l.send("881ERROR\t")}),!0;l.send("881"+b+"\t");return!1}function Sa(){l.writeKeyComb("ctrl+v",20)}function dc(a){var b=0===a.types.length||a.equals(q.clipData),d=b?"":a.types.join(","),c=!0;if(!b){-1!=d.indexOf("text/html")&&-1==d.indexOf("text/richtext")&&(d+=",text/richtext");
var f=a.getData("text/plain"),f=f?f.hashCode():0;l.send("880"+d+"\t"+f);q.clipData=a}g.onclipdata&&(c=!g.onclipdata(a,b));c&&setTimeout(Sa,500)}function ka(a,b){if(58!=b||!G.unicode){if(g.onscancode){var d=g.onscancode(a,b);if(d){for(var c=0,f=d.length;c<f;c++)l.sendInput("84"+(d[c].down?0:49152)+"\t"+d[c].key);return}}l.sendInput("84"+(a?0:49152)+"\t"+b);z.preScancode.code=b;z.preScancode.down=a}}function v(a,b){if(O){switch(b){case 221:if(a&&!r.disableKbdSync){ka(!0,221);ka(!1,221);return}break;
case 58:if(a){if(Pa&&!r.disableKbdSync){ka(!0,58);ka(!1,58);return}l.localLockFlags^=4}break;case 69:a&&(l.localLockFlags^=2);break;case 70:a&&(l.localLockFlags^=1)}!z.isKeyDownSent(a,b)&&999<Date.now()-g.focusTime&&ka(!0,b);ka(a,b)}}function aa(a,b,d){if(O){var c="8B"+(a?0:49152)+"\t"+b;d&&(c+="\t"+d);z.ctrlDelayed&&(z.ctrlDelayed=!1,v(!0,29));l.sendInput(c);z.preKey.code=b;z.preKey.down=a}}function Ta(a,b){z.ctrlDelayed&&(z.ctrlDelayed=!1,v(!0,29));l.sendInput(a+b)}function Ba(a,b,d,c,f){if(!O)return!1;
B(p.element);c||(c=P);f||(f=X);xa[d]||(xa[d]=!0,a=(a/c|0)+w.left,b=(b/f|0)+w.top,g.beforemousedown&&g.beforemousedown(a,b,d),Ta("80",a+"\t"+b+"\t"+d))}function Xa(a){T||a.shiftKey||a.metaKey||a.altKey||z.sendMissKey();var b=Ha(a);Ba(b.x,b.y,a.button);return Jb?!0:cancelDefault(a)}function Kb(a,b,d,c){d||(d=P);c||(c=X);a=(a/d|0)+w.left;b=(b/c|0)+w.top;0>a&&(a=0);0>b&&(b=0);if(g.onmousemove)g.onmousemove(a,b);w.x=a;w.y=b;Ta("82",a+"\t"+b)}function Ya(a){if(!Lb||!p||a.target!=p.element&&!xa[a.button])return!1;
var b=Ha(a,p.element);!Ca||!m.isAndroid&&!m.isiOS&&Y&&Y.system?h&&h.__visible&&h.__setVisible(!1):pa(b.x,b.y,!0);Kb(b.x,b.y);return cancelDefault(a)}function Da(a,b,d,c,f){c||(c=P);f||(f=X);xa[d]=!1;a=(a/c|0)+w.left;b=(b/f|0)+w.top;0>a&&(a=0);0>b&&(b=0);Ta("81",a+"\t"+b+"\t"+d);g.aftermouseup&&g.aftermouseup(a,b,d);m.isChrome&&q&&"denied"==q.clipboardWrite&&q.waitForCopyContent();l.resumeAudio&&(l.resumeAudio(),l.resumeAudio=null)}function Za(a){if(!O)return!1;var b=Ha(a,p.element);Da(b.x,b.y,a.button);
return Jb?!0:cancelDefault(a)}function Mb(a,b,d,c,f){c||(c=P);f||(f=X);a=(a/c|0)+w.left;b=(b/f|0)+w.top;g.onmousewheel&&g.onmousewheel(a,b,d)||Ta("83",a+"\t"+b+"\t"+d)}function ec(a,b){if(!O)return!1;for(var d=Math.abs(a),c=0>a?1:0,f=0;f<d;f++)Mb(b.x,b.y,c);return!1}function fc(a){if(a.none)return"none";if(a.system)return a.system;if(Ca)return"none";var b;if(!(b=a.url)){var d=a.rawData;b=a.width;var c=a.height,f=document.createElement("canvas"),n=f.getContext("2d"),e=n.createImageData(b,c),g=e.data,
h=b*c,u=window.devicePixelRatio||1,A=0,k=0;f.width=b;for(f.height=c;A<h;A++){var L=d[A];g[k++]=L&255;g[k++]=L>>8&255;g[k++]=L>>16&255;g[k++]=L>>24&255}n.putImageData(e,0,0,0,0,b,c);1==u?b=f.toDataURL():f.toDataURLHD?b=f.toDataURLHD():(d=document.createElement("canvas"),n=d.getContext("2d"),d.width=b*u|0,d.height=c*u|0,n.scale(u,u),n.drawImage(f,0,0),b=d.toDataURL())}return"url("+b+") "+a.hotX+" "+a.hotY+", default"}function Nb(){document.fullscreenElement?navigator.keyboard&&navigator.keyboard.lock():
navigator.keyboard&&navigator.keyboard.unlock()}e||(e=hi5.$("remotectrl"));k||(k={});k.pcKey||(k.pcKey=hi5.$("pc_key"));k.toolbar||(k.toolbar=hi5.$("svToolbar"));k.frmLogin||(k.frmLogin=hi5.$("frmLogin"));var Ea=k.notifications||hi5.notifications;if(window.svSurface&&svSurface.canvas==e&&svSurface.railWin)return svSurface.railWin.mainWin=null,window.svSurface;var m=hi5.browser,S=m.isTouch,Fa=m.getChildByNameOrId,l=null,oa=!1,P=1,X=1,Ua=0,Ob=0,hb=!1;e.style.outline="none";var J=0,K=0,E=e.getContext("2d",
{alpha:!1}),G=null,R=null,T=!1,ja=!1,ra=!1,tb=!1,U=!1,H=null,Z=!0,na=!1,ib=!1,ma=!1,Gb=!1,Pb=0;this.context=E;this.fileProgress=null;this.focusTime=this.blurTime=0;var g=this,O=!0,ca=!1,ha=!1,Lb=!0,ya=null,Qb=null,V=null,h=null,Y=null,la=null,da=null,fa=0,Oa=-1,qa=-1,Cb=0,Db=0,gb=!1,ab=null,w={x:0,y:0,offX:0,offY:0,left:0,top:0,right:0,bottom:0,primary:!1,isMultiMon:!1},ea=null,Ma=null,db=0,Aa,jb=!1,Rb=0,Na=0,sa=!1,ga=null;this._cr=[82,69,77,79,84,69,83,80,65,82,75];window.svSurface=this;hi5.appcfg||
(hi5.appcfg={img:{},toolbar:{fadable:!0},displayMsg:!0});var r=hi5.appcfg;void 0==r.toolbar.draggable&&(r.toolbar.draggable=!0);var Jb=window.clipboardData?!0:!!r.defaultEvent,ba=m.isIE||m.isEdge,Ca=ba&&!r.disableCursor,Wa=m.isChromeApp||ba&&!m.isEdge||1==r.directClipAccess,Hb=!!r.forceScancode;this.setConfig=function(a){r=a};this.railWin=this.toolbar=null;this.showToolbar=this.focused=!1;this.canvas=e;this.forceTextArea=this.alwaysPaste=!1;"visible"in r.toolbar&&(this.showToolbar=r.toolbar.visible);
var Ha=m.getMousePos,Ja=m.calMousePos;this.getWindow=function(){return window};this.setImageCursor=function(a){Ca=a};this.setMonitor=function(a,b,d,c){w.left=a;w.top=b;w.right=d;w.bottom=c;w.primary=0==a&&0==b;0!=d&&0!=c&&(w.isMultiMon=!1,g.setSize(d-a+1,c-b+1),w.isMultiMon=!0,$a("hidden"),r.disableScrollbars=!0)};this.configMonitor=function(){var a=window.screenX&-4,b=window.screenY&-4;g.setMonitor(a,b,(screen.width&-4)+a-1,(screen.height&-4)+b-1)};this.isClipSynced=function(a){if(!U)return!1;var b=
Date.now()-g.blurTime;if(a&&b>a)return!1;svGlobal.logger.info("clip synced in "+b);return!0};this.getScale=function(){return{x:P,y:X}};var N=null,Q=null,ta=!m.isChromeApp&&!r.copyDialog&&!r.directClipAccess&&!m.isIE;this.getThumbnail=function(a){a=a||64;N||(N=document.createElement("canvas"));var b=Math.floor(e.height/e.width*a);N.width!=a&&(N.width=a);N.height!=b&&(N.height=b);N.getContext("2d").drawImage(e,0,0,e.width,e.height,0,0,a,b);return N.toDataURL()};this.getThumbnailBlob=function(a,b){a=
a||64;var d=Math.floor(e.height/e.width*a);N||(N=window.OffscreenCanvas?new OffscreenCanvas(a,d):document.createElement("canvas"));N.width!=a&&(N.width=a);N.height!=d&&(N.height=d);N.getContext("2d").drawImage(e,0,0,e.width,e.height,0,0,a,d);return N.toBlob(b)};this.initChat=function(a){var b=document.getElementById("chatWindow");hi5.Draggable(b);return new hi5.Chat(b,a)};this.equals=function(a){return e==a.canvas};this.getFreeSpace=function(){var a=hi5.tool.getPos(e),b=window.innerWidth-a.x,a=t(window.innerHeight)-
a.y;return{width:b,height:a}};var I=new function(){var a=1033,b=m.isFirefox,d=m.isMacOS||m.isiOS,c=[0],f=null;c[3]=197;c[8]=14;c[9]=15;c[12]=76;c[13]=28;c[16]=42;c[17]=29;c[18]=56;c[19]=197;c[20]=58;c[27]=1;c[32]=57;c[33]=201;c[34]=209;c[35]=207;c[36]=199;c[37]=203;c[38]=200;c[39]=205;c[40]=208;c[44]=55;c[45]=210;c[46]=211;c[48]=11;c[49]=2;c[50]=3;c[51]=4;c[52]=5;c[53]=6;c[54]=7;c[55]=8;c[56]=9;c[57]=10;c[65]=30;c[66]=48;c[67]=46;c[68]=32;c[69]=18;c[70]=33;c[71]=34;c[72]=35;c[73]=23;c[74]=36;c[75]=
37;c[76]=38;c[77]=50;c[78]=49;c[79]=24;c[80]=25;c[81]=16;c[82]=19;c[83]=31;c[84]=20;c[85]=22;c[86]=47;c[87]=17;c[88]=45;c[89]=21;c[90]=44;c[91]=219;c[92]=220;c[93]=221;c[96]=82;c[97]=79;c[98]=80;c[99]=81;c[100]=75;c[101]=76;c[102]=77;c[103]=71;c[104]=72;c[105]=73;c[106]=55;c[107]=78;c[109]=74;c[110]=83;c[111]=181;c[112]=59;c[113]=60;c[114]=61;c[115]=62;c[116]=63;c[117]=64;c[118]=65;c[119]=66;c[120]=67;c[121]=68;c[122]=87;c[123]=88;c[144]=69;c[145]=70;c[154]=183;c[166]=59;c[167]=60;c[168]=61;c[173]=
66;c[174]=67;c[175]=68;c[182]=63;c[183]=62;c[216]=64;c[217]=65;c[186]=39;c[187]=13;c[188]=51;c[189]=12;c[190]=52;c[191]=53;c[192]=41;c[219]=26;c[220]=43;c[221]=27;c[222]=40;c[224]=29;c[225]=184;c[226]=86;c[235]=123;c[255]=121;var n={Escape:1,Digit1:2,Digit2:3,Digit3:4,Digit4:5,Digit5:6,Digit6:7,Digit7:8,Digit8:9,Digit9:10,Digit0:11,Minus:12,Equal:13,Backspace:14,Tab:15,KeyQ:16,KeyW:17,KeyE:18,KeyR:19,KeyT:20,KeyY:21,KeyU:22,KeyI:23,KeyO:24,KeyP:25,BracketLeft:26,BracketRight:27,Enter:28,ControlLeft:29,
KeyA:30,KeyS:31,KeyD:32,KeyF:33,KeyG:34,KeyH:35,KeyJ:36,KeyK:37,KeyL:38,Semicolon:39,Quote:40,Backquote:41,ShiftLeft:42,Backslash:43,KeyZ:44,KeyX:45,KeyC:46,KeyV:47,KeyB:48,KeyN:49,KeyM:50,Comma:51,Period:52,Slash:53,ShiftRight:54,NumpadMultiply:55,AltLeft:56,Space:57,CapsLock:58,F1:59,F2:60,F3:61,F4:62,F5:63,F6:64,F7:65,F8:66,F9:67,F10:68,NumLock:69,ScrollLock:70,Numpad7:71,Numpad8:72,Numpad9:73,NumpadSubtract:74,Numpad4:75,Numpad5:76,Numpad6:77,NumpadAdd:78,Numpad1:79,Numpad2:80,Numpad3:81,Numpad0:82,
NumpadDecimal:83,IntlBackslash:86,F11:87,F12:88,NumpadEqual:89,F13:91,F14:92,F15:93,F16:99,F17:100,F18:101,F19:102,F20:103,F21:104,F22:105,F23:106,F24:107,KanaMode:112,Lang2:113,Lang1:114,IntlRo:115,Convert:121,NonConvert:123,IntlYen:125,NumpadComma:126,Paste:138,MediaTrackPrevious:144,Cut:151,Copy:152,MediaTrackNext:153,NumpadEnter:156,ControlRight:157,VolumeMute:160,AudioVolumeMute:160,LaunchApp2:161,MediaPlayPause:162,MediaStop:164,Eject:172,VolumeDown:174,AudioVolumeDown:174,VolumeUp:176,AudioVolumeUp:176,
BrowserHome:178,NumpadDivide:181,PrintScreen:183,AltRight:184,Help:187,Pause:197,Home:199,ArrowUp:200,PageUp:201,ArrowLeft:203,ArrowRight:205,End:207,ArrowDown:208,PageDown:209,Insert:210,Delete:211,OSLeft:219,MetaLeft:219,OSRight:220,MetaRight:220,ContextMenu:221,Power:222,BrowserSearch:229,BrowserFavorites:230,BrowserRefresh:231,BrowserStop:232,BrowserForward:233,BrowserBack:234,LaunchApp1:235,LaunchMail:236,LaunchMediaPlayer:237};this.isPrintableScancode=function(a,c){if(95<c.keyCode&&112>c.keyCode)return!0;
if(0==a&&c){var b=c["char"]||c.key;if(b&&1==b.length)return b=b.charCodeAt(0),!(31>=b||127==b||128<=b&&159>=b)}return c.altKey&&70<a&&83>a&&74!=a&&78!=a?!0:1<a&&14>a||15<a&&28>a||29<a&&42>a||42<a&&54>a||57==a||86==a||115==a||125==a};var e=function(a){a=a.keyCode;if(b)switch(a){case 173:return 189;case 61:return 187;case 59:return 186;case 224:return 17}return a};this.mapCmdToCtrl=this.converMacCtrl=!0;var g=d?function(a){switch(a){case 91:return I.mapCmdToCtrl?17:91;case 93:return I.mapCmdToCtrl?
17:93;case 17:return I.converMacCtrl?91:17;case 229:return 69}return 0}:null;this.setLayout=function(b){a=b;var d=null;b="K"+b;b in h&&(d=h[b]());null===d&&(d=c);f=d;null!==f&&svGlobal.logger.info("Keyboard layout: "+a)};this.getKeyCode=function(a){var c=0;g&&(c=g(a.keyCode));c||(c=e?e(a):a.keyCode);return c};this.getScancode=function(a){var c=0;if(a.code)c=n[a.code]||0;else{var b=I.getKeyCode(a);switch(b){case 16:c=2==a.location?54:42;break;case 17:c=2==a.location?157:29;break;case 18:c=2==a.location?
184:56;break;case 33:c=3==a.location?73:201;break;case 34:c=3==a.location?81:209;break;case 35:c=3==a.location?79:207;break;case 36:c=3==a.location?71:199;break;case 37:c=3==a.location?75:203;break;case 38:c=3==a.location?72:200;break;case 39:c=3==a.location?77:205;break;case 40:c=3==a.location?80:208;break;case 45:c=3==a.location?82:210;break;case 46:c=3==a.location?83:211;break;default:f&&(c=f[b]||0)}}if(d)switch(c){case 29:this.converMacCtrl&&(c=219);break;case 157:this.converMacCtrl&&(c=220);
break;case 219:this.mapCmdToCtrl&&(c=29);break;case 220:this.mapCmdToCtrl&&(c=157)}return c};this.getScancodeByKeyCode=function(a){return f?f[a]||0:0};this.getCodeTable=function(){return f};this.getLayoutCreator=function(){return h};var h=new function(){this.K3758162961=function(){var a=c.slice(0);a[244]=41;a[243]=41;a[189]=12;a[222]=13;a[220]=125;a[192]=26;a[219]=27;a[187]=39;a[186]=40;a[221]=43;a[188]=51;a[190]=52;a[191]=53;a[226]=115;a[29]=123;a[28]=121;a[240]=112;a[242]=112;b&&(a[173]=12,a[160]=
13,a[64]=26,a[59]=39,a[58]=40,e=function(a){return 220==a.keyCode&&"_"==a.key?226:a.keyCode});return a};this.K1034=this.K66570=this.K2058=this.K1040=this.K66576=function(){var a=c.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=26;a[187]=27;a[191]=43;a[192]=39;a[189]=53;a[226]=86;b&&(e=function(a){var c=a.keyCode;a=a.key;switch(c){case 0:if("\u00e8"==a||"\u00e9"==a||"["==a)return 186;if("\u00f2"==a||"\u00e7"==a||"@"==a)return 192;if("\u00e0"==a||"\u00b0"==a||"#"==a||"\u00f9"==a||"\u00a7"==a)return 222;
break;case 60:return 226;case 160:return 221;case 171:return 187;case 173:return 189;case 222:return 219}return c});return a};this.K2057=function(){var a=c.slice(0);a[223]=41;a[222]=43;a[192]=40;a[220]=86;b&&(a[192]=41,a[173]=12,a[61]=13,a[59]=39,a[222]=40,a[163]=43);return a};this.K1031=this.K4106=this.K5130=this.K6154=this.K7178=this.K8202=this.K9226=this.K10250=this.K11274=this.K12298=this.K13322=this.K14346=this.K15370=this.K16395=this.K17418=this.K18442=this.K19466=this.K20490=this.K99997=this.K66567=
this.K2952791047=function(){var a=c.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=26;a[187]=27;a[191]=43;a[192]=39;a[189]=53;a[226]=86;a[90]=21;a[89]=44;b?e=function(a){var c=a.keyCode,b=a.key;switch(c){case 60:return 226;case 160:return 220;case 63:return 219;case 192:return 221;case 171:return 187;case 163:return 191;case 173:return 189;case 0:if("\u00f6"==b||"\u00d6"==b&&a.shiftKey)return 192;if("\u00e4"==b||"\u00c4"==b&&a.shiftKey)return 222;if("\u00fc"==b||"\u00dc"==b&&a.shiftKey)return 186}return c}:
hi5.browser.isLinux&&(e=function(a){var c=a.keyCode;a=a.key;switch(c){case 187:if("Dead"==a)return 221;break;case 192:if("Dead"==a||"\u00b0"==a)return 220;break;case 220:return 226}return c});return a};this.K2070=function(){var a=c.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=27;a[187]=26;a[191]=43;a[192]=39;a[189]=53;a[226]=86;return a};this.K2060=this.K99998=this.K2067=function(){var a=c.slice(0);a[222]=41;a[219]=12;a[189]=13;a[221]=26;a[186]=27;a[77]=39;a[192]=40;a[188]=50;a[190]=51;a[191]=52;
a[187]=53;a[226]=86;a[65]=16;a[90]=17;a[81]=30;a[87]=44;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 60:return 226;case 169:return 219;case 173:return 189;case 160:return 221;case 164:return 186;case 165:return 192;case 59:return 190;case 58:return 191;case 61:return 187;case 0:if("\u00b2"==b||"\u00b3"==b&&a.shiftKey)return 222;if("\u00b5"==b||"`\u00b5"==b||"DeadGrave"==b||"\u00a3"==b&&a.shiftKey||("`"==b||"``"==b)&&a.ctrlKey&&a.altKey)return 220}return c});return a};this.K3084=this.K4105=
function(){var a=c.slice(0);a[222]=41;a[192]=40;a[226]=86;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00b0"==b||"\u00ac"==b&&a.ctrlKey&&a.altKey)return 222;if("\u00e7"==b||"\u00c7"==b&&a.shiftKey)return 221;if("\u00e0"==b||"DeadGrave"==b||"\u00c0"==b&&a.shiftKey)return 220;if("\u00e8"==b||"\u00c8"==b&&a.shiftKey)return 192;if("\u00e9"==b||"\u00c9"==b&&a.shiftKey)return 191;if("\u00f9"==b||"\u00d9"==b&&a.shiftKey)return 226;if("DeadTilde"==b)return 221;break;case 173:return 189;
case 61:return 187;case 160:return 219;case 59:return 186}return c});return a};this.K1036=function(){var a=c.slice(0);a[222]=41;a[219]=12;a[187]=13;a[221]=26;a[186]=27;a[220]=43;a[77]=39;a[192]=40;a[190]=51;a[191]=52;a[223]=53;a[226]=86;a[65]=16;a[90]=17;a[81]=30;a[87]=44;a[188]=50;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00b2"==b)return 222;if("\u00e7"==b||"\u00c7"==b&&a.shiftKey)return 221;if("\u00e0"==b||"\u00c0"==b&&a.shiftKey)return 220;if("\u00e8"==b||"\u00c8"==b&&a.shiftKey)return 192;
if("\u00e9"==b||"\u00c9"==b&&a.shiftKey)return 189;if("\u00f9"==b||"\u00d9"==b&&a.shiftKey)return 226;if("DeadTilde"==b)return 221;break;case 60:return 226;case 169:return 219;case 61:return 187;case 160:return 221;case 164:return 186;case 170:return 220;case 165:return 192;case 59:return 190;case 58:return 191;case 161:return 223}return c});return a};this.K4108=this.K2055=function(){var a=c.slice(0);a[191]=41;a[219]=12;a[221]=13;a[186]=26;a[192]=27;a[223]=43;a[222]=39;a[220]=40;a[188]=51;a[190]=
52;a[189]=53;a[226]=86;a[90]=21;a[89]=44;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00a7"==b||"\u00b0"==b&&a.shiftKey)return 191;if("\u00e0"==b||"\u00e4"==b&&a.shiftKey||"{"==b&&a.ctrlKey&&a.altKey)return 220;if("\u00e8"==b||"\u00fc"==b&&a.shiftKey||"["==b&&a.ctrlKey&&a.altKey)return 186;if("\u00e9"==b||"\u00f6"==b&&a.shiftKey)return 222;break;case 222:return 219;case 160:return 221;case 161:return 192;case 164:return 223;case 173:return 189;case 60:return 226}return c});return a};
this.K1044=this.K1083=this.K1030=function(){var a=c.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00e5"==b||"\u00c5"==b&&a.shiftKey)return 221;if("\u00f8"==b||"\u00d8"==b&&a.shiftKey||"\u00f6"==b&&a.ctrlKey&&a.altKey)return 192;if("\u00e6"==b||"\u00c6"==b&&a.shiftKey||"\u00e4"==b&&a.ctrlKey&&a.altKey)return 222;break;case 172:return 220;case 171:return 187;case 220:return 219;
case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return c});return a};this.K1039=function(){var a=c.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;b&&(e=function(a){var c=a.keyCode;a=a.key;switch(c){case 0:if("Dead"==a)return 220;if("\u00f6"==a||"\u00d6"==a||"\\"==a)return 187;if("\u00f0"==a||"\u00d0"==a)return 221;if("\u00e6"==a||"\u00c6"==a)return 192;if("\u00fe"==a||"\u00de"==a)return 189;break;case 173:return 219;
case 222:return"Dead"==a||"'"==a?222:186;case 171:return 191;case 60:return 226}return c});return a};this.K1053=function(){var a=c.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00a7"==b||"\u00bd"==b&&a.shiftKey)return 220;if("\u00e5"==b||"\u00c5"==b&&a.shiftKey)return 221;if("\u00f8"==b||"\u00d8"==b&&a.shiftKey||"\u00f6"==b&&a.ctrlKey&&a.altKey)return 192;if("\u00e4"==b||
"\u00c4"==b&&a.shiftKey)return 222;break;case 171:return 187;case 192:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return c});return a};this.K1055=function(){var a=c.slice(0);a[220]=52;a[223]=12;a[189]=13;a[191]=51;a[188]=43;a[190]=53;a[226]=86;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u011f"==b||"\u011e"==b&&a.shiftKey||a.ctrlKey&&a.altKey&&"BracketLeft"==a.code)return 219;if("\u00fc"==b||"\u00dc"==b&&a.shiftKey||a.ctrlKey&&a.altKey&&
"BracketRight"==a.code)return 221;if("\u015f"==b||"\u015e"==b&&a.shiftKey||a.ctrlKey&&a.altKey&&"Semicolon"==a.code)return 186;if("\u00f6"==b||"\u00d6"==b&&a.shiftKey)return 191;if("\u00e7"==b||"\u00c7"==b&&a.shiftKey)return 220;break;case 73:return 222;case 60:return 226;case 173:return 189;case 170:return 223;case 162:return 192}return c});return a};this.K6153=function(){var a=c.slice(0);a[223]=41;a[189]=12;a[187]=13;a[219]=26;a[221]=27;a[186]=39;a[192]=40;a[222]=43;a[220]=86;a[188]=51;a[190]=52;
a[191]=53;return a}}};this.getKeyboardMgr=function(){return I};var q=new function(){function a(a,c){var b=q.parseClipData(c);if(!(r.copyTextOnly&&"text/plain"!=b.type||q.processFileGroup(b)))if(m.isEdge&&"text/plain"!=b.type)p.resetCSS(),p.setValue(b.value),p.select(),setTimeout(function(){p.setValue("");R&&R.setValue("");p.restoreCSS();q.processImgCopy(b.value)},555);else{var d=b.value.startsWith("<img data-sv-img");if(d&&"denied"!=q.clipboardWrite&&navigator.clipboard.write)a.preventDefault(),setTimeout(function(){q.copyImageToClipboard(b.value)},
20);else{if("text/plain"!=b.type&&!d){var e=hi5.browser.html2text(b.value);e&&a.clipboardData.setData("text/plain",e)}d&&q.processImgCopy(b.value);a.clipboardData.setData(b.type,b.value);a.preventDefault()}}}function b(){q&&(q.copyContent&&(q.copyToClipboard(q.copyContent.type,q.copyContent.value),q.copyContent=null),q.waitingCopyContent=!1)}this.hasCopyCmd=document.queryCommandSupported("copy");this.hasPasteCmd=document.queryCommandSupported("paste");this.pasteEventFired=!1;this.clipboardWrite=this.clipboardRead=
"denied";this.init=function(){navigator.permissions&&(navigator.permissions.query({name:"clipboard-read"}).then(function(a){q&&(q.clipboardRead=a.state,a.onchange=function(){q.clipboardRead=a.state;"granted"==q.clipboardRead&&F();svGlobal.logger.info("clipboard-read change: "+q.clipboardRead)},"granted"==q.clipboardRead&&F(),svGlobal.logger.info("clipboard-read: "+q.clipboardRead))})["catch"](function(a){svGlobal.logger.info(a)}),navigator.permissions.query({name:"clipboard-write"}).then(function(a){q&&
(q.clipboardWrite=a.state,a.onchange=function(){q.clipboardWrite=a.state;svGlobal.logger.info("clipboard-write change: "+q.clipboardWrite)},svGlobal.logger.info("clipboard-write: "+q.clipboardWrite))})["catch"](function(a){svGlobal.logger.info(a)}))};this.release=function(){q.clipData=null};this.clipData=null;this.read=function(a){var c=new D;if("denied"!=q.clipboardRead)navigator.clipboard.read?navigator.clipboard.read().then(function(b){for(var d=b.length,f=0,e=0;e<d;e++){var g=b[e].types[0];b[e].getType(g).then(function(b){"text/plain"==
g||"text/html"==g||"text/rtf"==g?hi5.browser.blobToText(b,function(b){c.setData(g,b);f++;f==d&&a(c)}):"image/png"==g&&hi5.browser.blobToArray(b,function(b){b=hi5.Base64.enc(b);c.setData("image/png",b);f++;f==d&&a(c)})})["catch"](function(b){a(c);svGlobal.logger.warn(b.message)})}})["catch"](function(a){svGlobal.logger.warn(a.message)}):navigator.clipboard.readText&&navigator.clipboard.readText().then(function(b){c.setData("text/plain",b);a(c)})["catch"](function(b){a(null)});else if(window.clipboardData)c.setData("text/plain",
window.clipboardData.getData("Text")),a(c);else return a(null),!1;return!0};this.paste=function(a,b){var c=new D,d=0,e=null,g=window.clipboardData||b.clipboardData,h=window.clipboardData?g.getData("Text"):g.getData("text/plain"),k="",l="",k=0;g.types&&(l=g.getData("text/html"));l&&!h&&(h=hi5.browser.html2text(l));h&&c.setData("text/plain",h);if(r.pasteTextOnly)b.preventDefault(),a(c);else{var m=g.items;if(m)for(d=0,k=m.length;d<k;d++){if("image/png"==m[d].type){e=m[d].getAsFile();break}}else if(g.files)for(m=
g.files,d=0,k=m.length;d<k;d++)if(-1!=m[d].type.indexOf("image/png")){e=m[d];break}if(e)b.preventDefault(),hi5.browser.blobToArray(e,function(b){b=hi5.Base64.enc(b);c.setData("image/png",b);a(c)});else if(h){if(g.types){e=g.types.indexOf?-1!=g.types.indexOf("text/rtf"):g.types.contains("text/rtf");if(k=g.getData("text/rtf"))0==k.charCodeAt(k.length-1)&&(k=k.substring(0,k.length-1)),c.setData("text/richtext",k);l&&(d=l.lastIndexOf("</html>"),d+7<l.length&&(l=l.substring(0,d+7)),c.setData("text/html",
l));if(!hi5.browser.isEdge&&(!e||k||l)){b.preventDefault();a(c);return}}if("TEXTAREA"==b.target.nodeName)b.preventDefault(),document.queryCommandSupported("paste")&&(c=q.getClipContent(c)),a(c);else{G&&(G.disableTextInput=!0);R&&(R.disableTextInput=!0);b.target.innerHTML="";var p=b.target.style.opacity;b.target.style.opacity=0;setTimeout(function(){var d=b.target.innerHTML;d&&d!=h&&(c.setData("text/html","<body>"+d+"</body>"),G?G.init():b.target.innerHTML="");a(c);b.target.style.opacity=p;G&&(G.disableTextInput=
!1);R&&(R.disableTextInput=!1)},300)}}else b.preventDefault(),a(c)}};this.onCopy=function(b){if(b.target==p.element){O&&Z||cancelDefault(b);var c="copy"==b.type?46:45,d="copy"==b.type?67:88;ma||(v(!0,29),aa(!0,d,c),aa(!1,d,c),v(!1,29));m.isMacOS&&aa(!1,d,c);Z&&!Wa&&na&&(999<Date.now()-Pb&&(c=l.getClipData(b.type),a(b,c),q.clipData=null,U=!0),Pb=Date.now(),svGlobal.logger.info("clip synced: true"))}};this.onPaste=function(a){if(a.target==p.element){Ra&&Ra.cancelCtrlV();if(!O||!Z)return cancelDefault(a);
ib||(U=!0);if(!g.alwaysPaste&&U){var b=!0;g.onclipdata&&(b=!g.onclipdata(q.clipData,!0));b&&setTimeout(Sa,300);svGlobal.logger.info("Ctrl+V only");return cancelDefault(a)}U=!0;q.paste(dc,a);return!0}};this.parseClipData=function(a){var b=a.indexOf(";"),d=a.substring(0,b);a=a.substring(b+1);return{type:d,value:a}};this.getClipContent=function(a){if(!document.queryCommandSupported("paste"))return a;var b=cb(r.pasteTextOnly?"textarea":"div");b.focus();try{if(document.queryCommandEnabled("paste")&&document.execCommand("paste"))return a||
(a=new D),r.pasteTextOnly||a.setData("text/html","<body>"+b.innerHTML+"</body>"),-1==a.types.indexOf("text/plain")&&a.setData("text/plain",r.pasteTextOnly?b.value:b.innerText||b.innerHTML.replace(/<br>/gi,"\n").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&lt;/gi,"<").replace(/&gt;/gi,">")),a}finally{g.focused=!0,b.parentNode.removeChild(b),p&&p.focus()}return a};this.accessClip=function(a,b){if("denied"!=q.clipboardRead&&navigator.clipboard.readText&&"text/plain"==
b)return navigator.clipboard.readText().then(function(b){var c=new D;c.setData("text/plain",b);a(c)})["catch"](function(b){a(null)}),!0;document.queryCommandSupported("paste")||a(null);var c=cb(r.pasteTextOnly?"textarea":"div");c.focus();c.addEventListener("paste",function(b){b.stopPropagation();q.pasteEventFired=!0;q.paste(function(b){g.focused=!0;c.parentNode&&c.parentNode.removeChild(c);p&&p.focus();a(b)},b)},!1);q.pasteEventFired=!1;if(document.queryCommandEnabled("paste")&&document.execCommand("paste")&&
q.pasteEventFired)return!0;setTimeout(function(){U=!0;q.pasteEventFired||a(null);g.focused=!0;c.parentNode&&c.parentNode.removeChild(c);p&&p.focus()},55);return!1};this.getContent=function(){var a=q.getClipContent();p&&p.element.removeEventListener("click",q.getContent,!1);return a&&!a.equals(q.clipData)?(q.clipData=a,l.send("880text/plain,text/html\t0"),!0):!1};this.startPasteCmd=function(){p&&document.queryCommandSupported("paste")&&p.element.addEventListener("click",q.getContent)};this.waitingCopyContent=
!1;this.copyContent=null;this.waitForCopyContent=function(){q.waitingCopyContent=!0;setTimeout(b,700)};this.prePaste=function(){U||!document.queryCommandEnabled("paste")&&!window.clipboardData||q.accessClip(function(a){if(a){var b=0===a.types.length||a.equals(q.clipData),d=b?"":a.types.join(",");b||(-1!=d.indexOf("text/html")&&-1==d.indexOf("text/richtext")&&(d+=",text/richtext"),b=(b=a.getData("text/plain"))?b.hashCode():0,l.send("880"+d+"\t"+b),q.clipData=a,U=!0)}})};this.copyImageToClipboard=function(a){var b=
a.indexOf('src="')+5,d=a.indexOf('"',b);a=a.substring(b,d);fetch(a).then(function(a){if(a.ok)return a.blob();throw Error("Nework error, access "+stc);}).then(function(a){a=new ClipboardItem({"image/png":a});navigator.clipboard.write([a])})["catch"](function(a){svGlobal.logger.warn(a)})};this.copyToClipboard=function(a,b){var c="text/plain"==a?"textarea":"div",d=!1,e=b.startsWith("<img data-sv-img"),h="text/plain"==a;h&&(window.clipboardData?(window.clipboardData.setData("Text",b),d=!0):"denied"!=
q.clipboardWrite&&(navigator.clipboard.writeText(b)["catch"](function(a){svGlobal.logger.warn(a)}),d=!0));if(!h||!d)if(e&&"denied"!=q.clipboardWrite&&navigator.clipboard.write)q.copyImageToClipboard(b),d=!0;else{h=cb(c,!1);if("div"==c)if(h.innerHTML=b,h.focus(),e&&document.body.createControlRange){var k=document.body.createControlRange();k.add(h.childNodes[0]);e=!1}else m.selectEditable(h);else h.value=b,h.focus(),h.select();try{d=k?k.execCommand("Copy"):document.execCommand("copy",!1,null)}catch(u){}finally{g.focused=
!0,h.parentNode.removeChild(h),p&&p.focus()}}U=!0;if(!d&&g.beforeCopyDialog&&g.beforeCopyDialog(b,__svi18n.info.imgCopyDownload,a))return!0;c=e&&!d&&q.processImgCopy(b);d||!c&&__svi18n.info.userCopy&&g.showMessage({title:__svi18n.info.userCopy,msg:b,timeout:9999,select:!0,format:a});return d};this.processFileGroup=function(a){if("application/x-filegroup"==a.type){a=a.value.split("\r\n");var b="",d=0;a.forEach(function(a){a=a.split("\t");1<a.length&&(b&&(b+=","),b+=a[0],d+=parseInt(a[1],10))});28<
b.length&&(b=b.substring(0,28)+"...");b=b+"<br>Total: "+hi5.tool.bytesToSize(d)+" Qty:"+a.length;__svi18n.info.download&&g.showMessage({title:__svi18n.info.download,msg:b,timeout:9E3,cbYes:function(){this.destroy();H.download()},cbNo:function(){this.destroy()}});return!0}return!1};this.processImgCopy=function(a){return 0<a.indexOf("data-sv-img")&&__svi18n.info.imgCopyDownload?(g.showMessage({title:__svi18n.info.imgCopyDownload,msg:a,timeout:9999}),!0):!1}},Pa=m.isMacOS||m.isiOS,z=new function(){this.afterComposition=
this.onComposition=this.ctrlDelayed=this.noKeyStuck=!1;this.preKey={code:0,down:!1};this.preScancode={code:0,down:!1};var a=this.noUnicode=!1,b=!1,d=!1,c={};this.sendMissKey=function(){for(var a in c)c[a]&&v(!1,parseInt(a,10))};this.isKeyDown=function(a){return c[a]};this.isKeyDownSent=function(a,b){var d=!0;a||(d=c[b]);c[b]=a;return d};this.check=function(a){var b=I.getKeyCode(a),c="keydown"==a.type;if(l.checkLockFlags&&144!=b&20!=b&&145!=b&&c&&a.getModifierState&&l.sendKeyboardSyncFlags){var d=
0;a.getModifierState("CapsLock")&&(d|=4);Pa||m.isCrOS?d|=l.localLockFlags&2:a.getModifierState("NumLock")&&(d|=2);a.getModifierState("ScrollLock")&&(d|=1);a=d;l.checkLockFlags=!1;svGlobal.logger.info("sync lock key, current:"+a+" local:"+l.localLockFlags+" remote:"+l.remoteLockFlags);l.sendKeyboardSyncFlags(a)||(l.checkLockFlags=!0)}17==b&&(T=c)};this["continue"]=function(c,e,g){if(29==e&&c)return z.ctrlDelayed=!0,!1;if(z.ctrlDelayed||Pa&&c)if(184==e)z.ctrlDelayed=!1,d=b=!0;else if(z.ctrlDelayed)return z.ctrlDelayed=
!1,b||v(!0,29),!0;if(29==e){if(b&&!c)return!1}else if(184==e&&b)return c||(b=!1,a=!0,d&&g&&(v(!0,184),v(!1,184),d=!1)),g?!1:!0;return!0};this.isAltGr=function(c){return b?(d=!1,!0):a?(a=!1,c?!1:!0):!1}};this.requestCredential=function(a,b){r.closeOnDisconn=!1;var d=null,c=k.frmLogin;if(c)d=k.frmLogin;else{var f=__svi18n.template.login;if(!f){g.showMessage("No value for login template");return}d=document.createElement("div");d.className="appdlg";d.innerHTML=f;document.body.appendChild(d);c=hi5.$("frmLogin")}var e=
Fa(c,"loginDomain"),h="INPUT"==e.tagName.toUpperCase();e&&a.nbDomain&&(h?e.value=a.nbDomain:e.innerHTML=a.nbDomain);var l=new hi5.ui.Lightbox(d);l.onclose=function(){document.body.removeChild(d)};l.show();(f=Fa(c,"loginUser"))&&f.focus();c&&(c.onsubmit=function(){var a=Fa(c,"loginUser").value,d=Fa(c,"loginPassword").value,f=h?e.value:e.innerHTML;l.dismiss();setTimeout(function(){b(a,d,f)},5);return!1})};var p=null;if(S)vb();else{var kb=hi5.$("tmContainer");kb&&kb.parentNode.removeChild(kb)}S&&!r.toolbar.draggable&&
window.addEventListener("scroll",function(){setTimeout(function(){if(Q){var a=k.pcKey;a&&(a.style.top=window.pageYOffset+"px",a.style.left=window.pageXOffset+"px")}g.toolbar&&(g.toolbar.style.top=window.pageYOffset+"px",g.toolbar.style.left=window.pageXOffset+.45*window.innerWidth+"px")},200)},!1);this.setCaretPos=function(a,b){};this.showMessage=function(a,b){a&&r.displayMsg&&Ea.notify("string"==typeof a?{msg:a,timeout:b||0}:a)};this.hideWhenClose="hideWhenClose"in r?r.hideWhenClose:!0;this.setReadOnly=
function(a,b){Lb=(O=!a)||!0===b};this.setPlayerMode=function(){ha=!0;g.showToolbar=!1;g.setReadOnly(!0);g.hideWhenClose=!1};this.showTwoFAQR=function(){var a=l.getAppInfo(),b=hi5.$("twofainfo"),d=hi5.$("barcodeDiv"),c=hi5.$("enableTwoFA"),f=hi5.$("disableTwoFA");a.twoFAEnabled?(d.style.display="none",f.style.display="block",c.style.display="none"):(hi5.$("imgBarcode").src="data:image/png;base64,"+hi5.Base64.enc(a.twoFAQR),d.style.display="block",f.style.display="none",c.style.display="block");var e=
hi5.$("faCode");e.value="";var h=new hi5.ui.Lightbox(b);h.show();c.onclick=f.onclick=function(a){var b=e.value;a=a.target==c?1:0;l.onauthcoderesult=function(a,b){b?h.dismiss():(e.value="",g.showMessage(__svi18n.errorCode.S3021||"Wrong authentication code",5E3))};6!=b.length?hi5.notifications.notify(__svi18n.info.digit6||"It must be a 6 digit number"):l.authWithCode(b,a)}};this.showTwoFACode=function(){var a=hi5.$("twofacode");if(a){var b=new hi5.ui.Lightbox(a,{noClose:!0});b.show();var a=hi5.$("btnTwoFACode"),
d=hi5.$("faAuthCode");d.value="";a.onclick=function(){var a=d.value;6!=a.length?hi5.notifications.notify(__svi18n.info.digit6||"It must be a 6 digit number"):(l.onauthcoderesult=function(a,c){c?b.dismiss():(d.value="",g.showMessage(__svi18n.errorCode.S3021||"Wrong authentication code",5E3));l.onauthcoderesult=null},l.authWithCode(a,2))}}};this.setAutoScale=function(a){var b="autoScale"in r;b&&(a=r.autoScale);a?(wa(!0),$a("hidden")):b||wa(!1);oa=a};Ca&&va(r.cursorNameOnly);this.setTouchpad=function(a){ca=
a;var b=hi5.$("touchpadMode");b&&(b.checked=a,b.onchange=function(a){ca=a.target.checked});a&&(h||va(r.cursorNameOnly))};this.setExtKeyboard=function(a){if(S){p.adjust(!0);p.setContentEditable(a?"true":"false");fa=a?1:0;m.isChrome&&p.setFontSize("2em");a&&p.focus();var b=hi5.$("extKBD");b&&b.checked!=a&&(b.checked=a)}};this.focus=function(){p&&B(p.element)};this.getInputElement=function(){return p};this.scaleTo=function(a,b,d){Ua=a;Ob=b;hb=d;e&&50<J&&(a/=J,b/=K,hb?(P=a,X=b):X=P=b=a=Math.min(a,b),
hi5.tool.scale(e.parentNode,a,b))};this.setSize=function(a,b,d){w.isMultiMon||(w.right!=w.left+a-1&&(w.right=w.left+a-1,w.bottom=w.top+b-1),J=a,K=b,oa||$a(d),e.width=J,e.height=K,oa?wa(!0):Ua&&Ua!=a&&g.scaleTo(Ua,Ob,hb),S&&vb(),p||(p=new nb),p.adjust())};this.reposition=function(){p.adjust()};this.setController=function(a){l=a;Aa=a.draw;l.sendInput||(l.sendInput=l.send);S&&m.setOrientaionHandler(function(){window.innerWidth>window.innerHeight!=J>K&&(oa?wa(!0):(clearTimeout(Qb),Qb=setTimeout(function(){window.innerWidth>
window.innerHeight!=J>K&&(l.onorientationchange({svSurface:g,innerWidth:window.innerWidth,innerHeight:t(window.innerHeight)}),r.disableScoll||window.scrollTo(0,0))},555)))})};this.setFileHandler=function(a){"FileReader"in window||(a=null);if(a){if(!H&&!ha)if(H=a,H.addEvent("uploaded",function(a,b){!a&&hi5.$("filecontainer")&&Rb&16&&(hi5.$("__cancelUpload")&&(hi5.$("__cancelUpload").style.visibility="hidden"),g.fileProgress&&(g.fileProgress.maxValue=0,g.fileProgress.style.display="none"),g.refreshFiles(!V),
__svi18n.file.uploadDone&&b.size&&b.duration&&g.showMessage(__svi18n.file.uploadDone+" "+hi5.tool.bytesToSize(b.size/(b.duration/1E3))+"/s",5E3))}),H.addEvent("uploadstarted",function(a){a&&setTimeout(Sa,999)}),hi5.$("filecontainer")){hi5.$("filecontainer").className="h5-form";hi5.$("total")&&(g.fileProgress=new hi5.ProgressBar(hi5.$("total")));var b=hi5.$("__cancelUpload");b&&b.addEventListener("click",function(){H.cancelAll()},!1);H.addEvent("beforeupload",function(a,c,e){e||(b&&(b.style.visibility=
"visible"),g.fileProgress&&(g.fileProgress.style.display="block",g.fileProgress.maxValue+=a.size))});H.addEvent("progress",function(a){g.fileProgress&&g.fileProgress.setProgress(a)})}else bb()}else H=null,g.fileProgress=null,bb(),ea&&(ea.release(),ea=null);xb();Zb()};this.setFeature=function(a){Rb=a;var b,d=!(a&16),c=!(a&65536);(d||ha)&&bb();a&128&&(b=hi5.$("uploadfile"))&&(b.style.visibility="hidden");a&131072&&((b=hi5.$("__sv_download__"))&&b.parentNode.removeChild(b),(b=hi5.$("__sv_view__"))&&
b.parentNode.removeChild(b));a&256||(b=hi5.$("shadowing"))&&b.parentNode.removeChild(b);a&1024||(b=hi5.$("ssParent"))&&b.parentNode.removeChild(b);(c&&d||ha)&&g.setFileHandler(null)};var za=new function(){function a(){if(0===d.length){if(c=!1,!e){var a=hi5.$("_sv_pdf_parent");a&&g&&g.visible()&&g.dismiss();a&&a.parentNode&&setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},9999);m.isFirefox&&l&&l.restoreResize&&l.restoreResize()}}else b()}function b(){var b=d.shift();if(b){var f=
hi5.$("_sv_pdf_parent"),h=__svi18n.info.printready||"Your document is ready.",k=b.endsWith(".txt"),b=(e=!k&&(m.isAndroid||m.isiOS||!!r.showPDFLink))?'<p style="text-align:center;line-height:4em"><a href="'+b+'" target="_blank">'+h+"</a></p>":(m.isChromeApp?"<webview":"<iframe")+' src="'+b+'" width="100%" height="100%" id="_iFramePDF">'+(m.isChromeApp?"</webview>":"</iframe>");f&&f.visible&&f.visible()&&f.dismiss&&f.dismiss();f&&f.parentNode&&f.parentNode.removeChild(f);f=document.createElement("div");
f.style.backgroundColor="white";f.style.width=e?"30%":"70%";f.style.height=e?"4elm":"70%";f.id="_sv_pdf_parent";e?f.style.overflow="scroll":!k&&m.isFirefox&&l.saveResize&&l.saveResize(!1);f.innerHTML=b;document.body.appendChild(f);g=new hi5.ui.Lightbox(f,{close:{top:"-20px",right:"-15px"}});g.onclose=a;g.show();k&&(f=document.getElementById("_iFramePDF").contentWindow,f.focus(),f.print())}c=!0}var d=[],c=!1,e=!1,g=null;this.clearPDF=function(){a()};this.showPDF=function(a){d.push(a);c||b()}};this.close=
function(){jb=!1;svGlobal.logger.info("close ui...");O=!1;Na&&cancelAnimationFrame(Na);La();Xb();q&&(q.release(),q=null);Ma&&(Ma.release(),Ma=null);ea&&(ea.release(),ea=null);R&&(R.release(),R=null);l=Aa=la=Y=h=V=H=R=N=z=I=null;g.fileProgress=null;za&&za.clearPDF();za=null;oa&&g.setAutoScale(!1);Q&&(Q.setVisibility(!1),Q.release(),Q=null);"clearScreen"in r&&!r.clearScreen||E.fillRect(0,0,e.width,e.height);window.svSurface&&window.svSurface==g&&(window.svSurface=null);tb=!0;if(window&&!ha){try{if(0<
Ea.notifySize()){Ea.onempty=function(){g.close();Ea.onempty=null};return}if(r.closeOnDisconn)window.close();else if(this.hide(),m.isChromeApp){var a=chrome.app.window.current();a&&!r.disableMaxFullScn&&(a.onMaximized.removeListener(ob),a.isFullscreen()&&(a.restore(),a.restore()))}}catch(b){}g=e=E=g.context=null;svGlobal.logger.info("closed ui")}};this.setFastCopy=function(a){};this.drawLicense=function(a){if(0!=r.drawLicense){var b=a.charAt(0);E.save();E.font="12pt Arial";E.fillStyle="W"==b?"red":
"black";a=a.substring(1);E.fillText(a,10,K-24);E.restore()}};this.drawText=function(a){var b=r.text||{};E.save();var d=e.width,c=e.height;E.fillStyle=b.backgroundFillStyle||"white";E.fillRect(0,0,d,c);var f=20,g=50;"center"==b.textAlign&&(f=d/2,g=c/2);E.font=b.font||"18pt Arial";E.fillStyle=b.fillStyle||"black";b.textAlign&&(E.textAlign=b.textAlign);b.textBaseline&&(E.textBaseline=b.textBaseline);E.fillText(a,f,g);E.restore()};this.showPDF=function(a){za.showPDF(a)};this.hide=function(){g.hideWhenClose&&
(e.height=1,e.width=1);p&&p.hide()};var Sb=0;this.copyToClip=function(a,b){if(Z&&na){var d=q.parseClipData(a);if(!(r.copyTextOnly&&"text/plain"!=d.type||q.processFileGroup(d)))if(q.waitingCopyContent)q.copyContent=d;else{var c=d.value;(!r.copyDialog&&(!c.startsWith("<img data-sv-img")||navigator.clipboard&&navigator.clipboard.write)||q.hasCopyCmd||navigator.clipboard)&&q.copyToClipboard(d.type,c)}}};Q=new function(){function a(){d&&(T?hi5.html.addClass(d,"button_selected"):hi5.html.removeClass(d,
"button_selected"));c&&(ja?hi5.html.addClass(c,"button_selected"):hi5.html.removeClass(c,"button_selected"));f&&(ra?hi5.html.addClass(f,"button_selected"):hi5.html.removeClass(f,"button_selected"))}function b(b){b=b.target;var e=b.innerHTML,e=e.replace(/\u2190/g,"left").replace(/\u2191/g,"up").replace(/\u2192/g,"right").replace(/\u2193/g,"down");switch(e){case "Ctrl":d||(d=b);T?v(!1,29):v(!0,29);T=!T;a();break;case "Alt":c||(c=b);ja?v(!1,56):v(!0,56);ja=!ja;a();break;case "Shift":f||(f=b);ra?v(!1,
42):v(!0,42);ra=!ra;a();break;case "...":if(b=Fa(k.pcKey,"pc_key_more"))b.style.display="block"==b.style.display?"none":"block";break;case "Start":e="Ctrl+Esc";default:g.writeKeyComb(e),Q.resetModifier()}}var d=null,c=null,f=null,e={ctrl:!1,alt:!1,shift:!1};this.release=function(){e=null};this.setStickyKey=function(a){e=a};this.setVisibility=function(a){if(a){if(fa=Date.now(),a=k.pcKey)a.style.display="block",a.style.top=window.pageYOffset+"px",R&&(R.setValue("`\t`"),R.select())}else if(fa=0,a=k.pcKey)a=
hi5.$("shortcuts"),a&&a.checked||(h.style.display="none")};this.resetModifier=function(){ja&&!e.alt&&(ja=!1,v(!1,56));T&&!e.ctrl&&(T=!1,v(!1,29));ra&&!e.shift&&(ra=!1,v(!1,42));a()};var h=k.pcKey;if(h){var l=h.getElementsByTagName("span"),p=l.length,q=m.isFirefox?"mousedown":"touchstart";"ontouchstart"in window||(navigator.pointerEnabled?q="pointerdown":navigator.msPointerEnabled&&(q="MSPointerDown"));for(var r=0;r<p;r++){var t=l[r];t.className="button";t.addEventListener(q,b,!1);"mousedown"!=q&&
t.addEventListener("mousedown",b,!1)}h.style.position="absolute"}};this.setStickyKey=function(a){Q.setStickyKey(a)};var Tb=hi5.$("shortcuts");Tb&&Tb.addEventListener("change",function(a){Q.setVisibility(a.target.checked)});this.setKeysVisibility=function(a){Q&&Q.setVisibility(a)};this.setDirectory=function(a){var b=hi5.$("parentPath");b&&"."!=a&&(b.currentDir=a)};this.refreshFiles=function(a){a?(ia(".",null),(a=document.getElementById("__sv_folder__"))&&!a.onclick&&H.mkdirs&&(a.onclick=function(){var a=
document.getElementById("__sv_folder_name_");a&&a.value&&(H.mkdirs(a.value),ia(".",null),a.value="")})):V&&V.visible()?ia(".",V):wb(null)};this.showConnectonInfo=function(){var a=l.getAppInfo(),b=hi5.$("numericId");b&&(b.innerHTML=a.numericId);if(b=hi5.$("connectingTo"))b.innerHTML=a.server;if(b=hi5.$("joinLink"))b.href=b.innerHTML=a.joinLink;b=new hi5.ui.Lightbox(hi5.$("appinfo"));b.show();p&&(p.element.oncontextmenu=null,p.element.onselectstart=null);b.onclose=ub;b=hi5.$("btnTwoFA");hi5.$("twofainfo")&&
b&&(a.twoFAEnabled||a.twoFAQR?b.onclick=function(){g.showTwoFAQR()}:b.disabled=!0)};this.setupTwoFA=function(a){};this.processLink=function(a){function b(b){window.open(a);b.target.parentNode.removeChild(b.target)}if((!g.beforeOpenLink||!g.beforeOpenLink(a))&&g.toolbar){clearTimeout(Sb);var d=g.toolbar,c=d.getButton("_svLinkInfo");c?c.onclick=b:(c=d.addButton(r.img.link?r.img.link:"link.png",b),c.id="_svLinkInfo");c.title=a;d.startFade();Sb=setTimeout(function(){g.toolbar&&g.toolbar.removeButton("_svLinkInfo")},
1E4)}};this.setUnicode=function(a){p&&(!a&&S&&(m.isiOS||m.isAndroid)&&(a=!0),svGlobal.logger.info("Unicode:"+a),G.onkeydown=G.onkeyup=a?ac:Eb,G.ontextinput=a?cc:null,G.unicode=a)&&(G.oncomposition=bc)};this.forceScancode=function(a){Hb=a};this.setTouchRemoting=function(a){!0===a?(la=new Vb(g,e),svGlobal.logger.info("touch remoting"),__svi18n.info.touchremoting&&g.showMessage(__svi18n.info.touchremoting)):la=new mb(g)};this.setClipboard=function(a,b,d){(Z=a)?(na=void 0==b?!0:b,ib=void 0==d?!0:d,q.init()):
ib=na=!1;ta=a?!m.isChromeApp&&!r.copyDialog&&!r.directClipAccess&&!m.isIE:!1};this.setJoinMode=function(a){l.setJoinMode(a)};this.requestControl=function(){l.requestControl()};this.repaint=function(a,b,d,c){w.isMultiMon?(a<w.left&&(a=w.left),b<w.top&&(b=w.top),d>w.right&&(d=w.right),c>w.bottom&&(c=w.bottom),a<=w.right&&b<=w.bottom&&(a=l.refresh(a,b,d,c))&&E.putImageData(a.imgData,a.left-w.left,a.top-w.top,0,0,a.width,a.height)):(a=l.refresh(a,b,d,c))&&E.putImageData(a.imgData,a.left,a.top,0,0,a.width,
a.height)};this.running=function(){return jb};this.run=function(a,b,d,c){function f(a){a.target.removeEventListener("click",f,!1);l.send("884")}jb=!0;I.converMacCtrl=!1!==b;I.mapCmdToCtrl=!1!==c;z.noKeyStuck=!!d;!I.mapCmdToCtrl&&m.isMacOS&&F();p||(p=new nb);p.adjust();Ea.clearAll();3758162961!=a&&3758162962!=a||!p||p.setContentEditable("false");I.setLayout(a);a=-1!=[99997,99998,99999].indexOf(a);void 0==r.closeOnDisconn&&(r.closeOnDisconn=!!window.opener&&!m.isChromeApp);r.disableScoll||window.scrollTo(0,
0);xb();Yb();b=p.element;ha||(la=new mb(g),ga=new ua(b),ga.ontouch=$b,ga.onmousedown=Xa,ga.onmousemove=Ya,ga.onmouseup=Za,b.addEventListener("mouseleave",Ka,!1),b.addEventListener("mouseenter",Ka,!1),W(b,ec,!1),b.addEventListener("paste",q.onPaste,!1),Z&&ta&&na&&(b.addEventListener("copy",q.onCopy,!1),b.addEventListener("cut",q.onCopy,!1)));!1!==r.autoFocus&&B(b);g.setUnicode(a);this.drawText(__svi18n.wait);if(g.onstart)g.onstart(e);b.addEventListener("click",f,!1);Aa&&(Na=requestAnimationFrame(zb));
p.adjust();r.disableScoll||window.scrollTo(0,0)};var Ab=r.animation||42;m.isIE&&(Ab*=2);this.moveCursorBy=this.movCursorBy=Bb;this.moveCursor=function(a,b,d,c,e,g){a-=w.left;b-=w.top;0>a||0>b||a>=J||b>=K||(h||va(r.cursorNameOnly),h.__visible||h.__setVisible(!0),h.scrX=a,h.scrY=b,h.moveCursor(a+w.offX,b+w.offY,c,e,g),O&&!d&&l.sendInput("82"+a+"\t"+b),w.x=a,w.y=b)};this.switchSoftKeyboard=eb;this.isSoftKeyboardOn=function(){return sa};var Ub=hi5.$("svTouchInput");Ub&&Ub.addEventListener("click",function(){eb()},
!1);this.touchstart=function(a){switch(a.pointes){case 1:ca?(h||va(r.cursorNameOnly),fb("touchstart",a.screenX,a.screenY,!a.flick)):a.flick&&!Ia()||Ba(a.x,a.y,0);break;case 2:Oa=a.screenX,qa=a.screenY}};this.touchmove=function(a){switch(a.pointes){case 1:ca?fb("touchmove",a.screenX,a.screenY,!a.flick):a.flick&&!Ia()||Kb(a.x,a.y);break;case 2:19<Math.abs(a.screenY-qa)&&(Mb(a.x,a.y,0<a.screenY-qa?0:1),Oa=a.screenX,qa=a.screenY)}};this.touchend=function(a){switch(a.pointes){case 1:ca?fb("touchend",a.screenX,
a.screenY,!a.flick):(pa(a.x,a.y,!0),a.flick&&!Ia()||Da(a.x,a.y,0));break;case 2:if(!a.moved){var b=ca?h.scrX:a.x;a=ca?h.scrY:a.y;pa(b,a);Ba(b,a,2);Da(b,a,2)}break;case 3:if(a.gesture)switch(a.gesture){case "OPEN":v(!0,219);v(!0,200);v(!1,200);v(!1,219);break;case "CLOSE":v(!0,219);v(!0,208);v(!1,208);v(!1,219);break;case "LEFT":v(!0,56);v(!0,1);v(!1,1);v(!1,56);break;case "RIGHT":v(!0,42);v(!0,56);v(!0,1);v(!1,1);v(!1,56);v(!1,42);break;case "UP":v(!0,42);v(!0,219);aa(!0,77,50);aa(!1,77,50);v(!1,
219);v(!1,42);break;case "DOWN":v(!0,219),aa(!0,77,50),aa(!1,77,50),v(!1,219)}else eb()}};this.flick=function(a){switch(a.from){case 4:l.sendInput("840\t209");l.sendInput("8449152\t209");break;case 2:l.sendInput("840\t201"),l.sendInput("8449152\t201")}};this.longpress=function(a){ca&&(a.pointes=2);switch(a.pointes){case 1:var b=a.x;a=a.y;pa(b,a);Ba(b,a,2);Da(b,a,2);break;case 2:h&&(Ba(h.scrX,h.scrY,2,1),Da(h.scrX,h.scrY,2,1))}};this.redirectTouches=function(a){if(O){for(var b=a.length,d,c="90"+b,
e=0;e<b;e++)d=a[e],c=c+"\t"+d.contactId+";"+d.contactFlags+";"+Math.floor(d.x/P)+";"+Math.floor(d.y/X);l.send(c)}};var Qa=0;this.setIgnorePaste=function(a){U=a};this.processClipReq=function(a){if(!Z)return l.send("881ERROR\t"),!0;var b=q.clipData;return b||U?(Ib(b,a),!0):q.accessClip(function(b){Ib(b,a)},a)};var Ra=ba?new function(){var a;this.sendCtrlVLater=function(){a=setTimeout(Sa,333)};this.cancelCtrlV=function(){clearTimeout(a)};return this}:null,xa={};this.getMousePosition=function(){return w};
this.writeKeyComb=function(a){l.writeKeyComb(a)};this.setCursor=function(a){a&&!r.disableCursor&&(Y=a,h&&h.setCursor(a),h&&Ca&&!a.system&&(h.__setVisible(!0),pa(w.x,w.y,!0)),ha||(a.result||(a.result=r.cursorNameOnly?"none":fc(a)),p?p.element.style.cursor=a.result:e.style.cursor=a.result))};this.setVisible=function(a,b){var d=a?"visible":"hidden";"number"==typeof b?setTimeout(function(){e.style.visibility=d},b):e.style.visibility=d};this.initWhiteboard=function(a,b){var d=e.parentNode,c=d.querySelector('canvas[name="svWhiteboard"]');
if(!c){c=document.createElement("canvas");c.setAttribute("name","svWhiteboard");c.width=a||J;c.height=b||K;c.style.zIndex=80;var f=p.element;c.style.position=f.style.position;c.style.left=f.style.left;c.style.top=f.style.top;d.appendChild(c)}return c};this.removeWhiteboard=function(){var a=e.parentNode,b=a.querySelector('canvas[name="svWhiteboard"]');b&&a.removeChild(b)};this.requestFullscreen=function(a){document.fullscreenElement?(document.exitFullscreen(),document.removeEventListener("fullscreenchange",
Nb,!1)):(!1!==a&&document.addEventListener("fullscreenchange",Nb,!1),document.body.requestFullscreen())}}svGlobal.LocalInterface||(svGlobal.LocalInterface=LocalInterface);
svGlobal.rdpFile={loadRdpFile:function(e,k){var t=k.elements,B=e.split("\r\n");2>B.length&&(B=e.split("\n"));if(2>B.length)return!1;var D=hi5.$("gateway"),F=D.value;k.reset();D.value=F;D=0;for(F=B.length;D<F;D++){var x=B[D],W=x.indexOf(":"),ua=x.substring(0,W),x=x.substring(W+3),ua=ua.toLowerCase();switch(ua){case "full address":W=x.indexOf(":");0<W?(t.server.value=x.substring(0,W),t.port.value=x.substring(W+1)):t.server.value=x;break;case "username":t.user.value=x;break;case "domain":t.domain.value=
x;break;case "connect to console":t.useConsole.checked="0"!=x;break;case "desktopwidth":t.width.value=x;break;case "desktopheight":t.height.value=x;break;case "session bpp":t.server_bpp.value=x;break;case "audiomode":t.playSound.value=x;break;case "alternate shell":0<x.length&&(t.command.value=x,hi5.$("app").checked||(hi5.$("shell").checked=!0));break;case "shell working directory":t.directory=x;break;case "redirectclipboard":t.mapClipboard.checked="0"!=x;break;case "redirectprinters":t.mapPrinter.checked=
"0"!=x;break;case "server port":0<x.length&&(t.port.value=x);break;case "disable wallpaper":t.background.checked="0"==x;break;case "disable themes":t.styles.checked="0"==x;break;case "disable menu anims":t.animation.checked="0"==x;break;case "disable full window drag":t.contents.checked="0"==x;break;case "allow font smoothing":t.smoothfont.checked="0"!=x;break;case "allow desktop composition":t.composition.checked="0"!=x;break;case "bitmapcachepersistenable":t.bitmap.checked="0"!=x;break;case "remoteapplicationprogram":t.exe.value=
x;break;case "remoteapplicationcmdline":t.args.value=x;break;case "remoteapplicationmode":hi5.$("app").checked="1"==x;break;case "loadbalanceinfo":t.loadBalanceInfo.value=x}}return!0},handleFiles:function(e,k){if(1!=e.length)hi5.notifications.notify({msg:"Please one file only"});else{var t=e[0],B=t.name,D=B.length;if(4<D&&".rdp"==B.substring(D-4).toLowerCase()){var F=new FileReader,x=!1;F.onload=function(e){!(e=e.target.result)||svGlobal.rdpFile.loadRdpFile(e,k)||x||(x=!0,F.readAsText(t))};F.readAsText(t,
"UTF-16LE")}else hi5.notifications.notify({msg:"Sorry, Please .rdp file only"})}}};
function initDragDrop(e,k){function t(e){svGlobal.rdpFile.handleFiles(e.target.files,k)}if("FileReader"in window){var B=e.style.backgroundColor,D=hi5.$("rdpfile");D&&D.addEventListener("change",t,!1);e.addEventListener("dragover",function(k){cancelDefault(k);e.style.backgroundColor="yellow"},!1);e.addEventListener("dragleave",function(k){cancelDefault(k);e.style.backgroundColor=B},!1);e.addEventListener("drop",function(t){cancelDefault(t);e.style.backgroundColor=B;svGlobal.rdpFile.handleFiles(t.dataTransfer.files,
k)},!1)}}svGlobal.util.initDragDrop=initDragDrop;
svGlobal.util.initMapDisk=svGlobal.util.MapDisk=function(e,k,t){function B(t){cancelDefault(t);k&&("0.6"!=e.style.opacity&&(e.style.opacity="0.6"),e.style.backgroundColor="yellow")}function D(t){cancelDefault(t);k&&(e.style.opacity=e.__oldOpacity,e.style.backgroundColor=e.__oldColor)}function F(x){cancelDefault(x);if(k){e.style.opacity=e.__oldOpacity;e.style.backgroundColor=e.__oldColor;var B=hi5.file.getEntries(x);!B.length||"file:"==location.protocol&&!hi5.browser.isElectron&&hi5.browser.isChrome?
k.addFiles?k.addFiles(x.dataTransfer.files,t):k.addFile(x.dataTransfer.files[0]):hi5.file.getFilesFromEntries(B,function(e){k.addFiles?k.addFiles(e,t):k.addFile(e[0])})}}"FileReader"in window&&(e.__oldColor=e.style.backgroundColor,e.__oldOpacity=e.style.opacity,e.addEventListener("dragover",B,!1),e.addEventListener("dragleave",D,!1),e.addEventListener("drop",F,!1),this.release=function(){e.removeEventListener("dragover",B,!1);e.removeEventListener("dragleave",D,!1);e.removeEventListener("drop",F,
!1);e=k=null})};
svGlobal.util.getServerArgs=function(e){var k=window.opener;if(!e)try{k&&k.__sparkUser&&k.__sparkUser.server&&(e=k.__sparkUser.server),!e&&k.sparkServer&&(e=k.sparkServer)}catch(t){}e?(k=e.rdp||e.vnc||e.ssh||e.telnet||null)&&!e.server&&(k.gateway=e.gateway,k.session=e.session,k.account=e.account,k.server=e.id,k.displayName=e.displayName,k.shadowing=e.shadowing,k.user=k.username||"",k.pwd=k.password||"",k.useConsole=k.console||!1,k.server_bpp=k.color,k.legacyMode=k.leagacyMode||k.legacyMode||!1,k.exe=
k.remoteProgram||"",k.args=k.remoteArgs||"",k.startProgram=0<k.exe.length?"app":k.command&&0<k.command.length?"shell":"noapp",e.keyboard&&(k.keyboard=e.keyboard),e=k):e=hi5.browser.cookie2Obj();return e};(function(){function e(k){k=document.getElementsByClassName("ver");for(var t=k.length,B=0;B<t;B++)k[B].innerHTML=svGlobal.version;window.removeEventListener("load",e,!1)}window.addEventListener("load",e,!1)})();
svGlobal.gatewayError=function(e,k){var t=__svi18n.errorCode["S"+e];t?k&&(t+="; "+k):t=k;hi5.notifications.notify(t)};svGlobal.logger.info("ver:"+svGlobal.version);
