var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(c,a,d){c instanceof String&&(c=String(c));for(var b=c.length,e=0;e<b;e++){var f=c[e];if(a.call(d,f,e,c))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,a,d){if(c==Array.prototype||c==Object.prototype)return c;c[a]=d.value;return c};$jscomp.getGlobal=function(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var a=0;a<c.length;++a){var d=c[a];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(c,a){var d=$jscomp.propertyToPolyfillSymbol[a];if(null==d)return c[a];d=c[d];return void 0!==d?d:c[a]};
$jscomp.polyfill=function(c,a,d,b){a&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(c,a,d,b):$jscomp.polyfillUnisolated(c,a,d,b))};$jscomp.polyfillUnisolated=function(c,a,d,b){d=$jscomp.global;c=c.split(".");for(b=0;b<c.length-1;b++){var e=c[b];if(!(e in d))return;d=d[e]}c=c[c.length-1];b=d[c];a=a(b);a!=b&&null!=a&&$jscomp.defineProperty(d,c,{configurable:!0,writable:!0,value:a})};
$jscomp.polyfillIsolated=function(c,a,d,b){var e=c.split(".");c=1===e.length;b=e[0];b=!c&&b in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in b))return;b=b[g]}e=e[e.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?b[e]:null;a=a(d);null!=a&&(c?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:a}):a!==d&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(b,e,{configurable:!0,writable:!0,value:a})))};$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6","es3");
var sparkConfig={gateway:null,servers:null,users:null,config:function(c,a,d,b,e,f){c=c+"/CONF?type="+a+"&action="+d;f&&(c+=f);(a=document.getElementById("gwPwd").value)&&(c+="&gwPwd="+encodeURIComponent(a));hi5.tool.openWebSocket(c,e,b)},formatDate:function(c){if(!c)return"";c=new Date(c);return c.getFullYear()+"-"+(c.getMonth()+1)+"-"+c.getDate()+" "+c.getHours()+":"+c.getMinutes()},parseDate:function(c){var a=c.split(" ");c=a[0].split("-");a=a[1].split(":");if(3!=c.length||2!=a.length)throw"Date format must be yyyy-MM-dd hh:mm";
return new Date(c[0],c[1]-1,c[2],a[0],a[1])},showMessage:function(c){document.getElementById("message").innerHTML=c},checkError:function(c){if(c.error){var a=__svi18n.errorCode["S"+c.name];c.message&&(a+=c.message);setTimeout(function(){alert(a)},0);return!0}return!1},refreshServers:function(){function c(b){b=sparkConfig.servers.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),"servers","remove",d,null,"&id="+b)}function a(b){b=this.getValue(0);sparkConfig.editServer(b)}function d(b){sparkConfig.servers=
b;var e=new hi5.DataTable(b),f=new hi5.DataGrid(document.getElementById("servers.rows"));f.dataTable=e;f.open();document.getElementById("servers.type").value=b.type;document.getElementById("servers.display").checked=b.display;f.onrowclick=function(g){g=g.target;(g=g["data-action"]||g.name)&&e.perform(g)};e.addEvent("beforeremove",c);e.addEvent("onaction",a)}sparkConfig.config(sparkConfig.getGatewayAddr(),"servers","get",d)},refreshServerGroups:function(){function c(b){b=sparkConfig.serverGroups.getValue(0);
sparkConfig.config(sparkConfig.getGatewayAddr(),"serverGroups","remove",d,null,"&name="+b)}function a(b){b=this.getValue(0);sparkConfig.editServerGroup(b)}function d(b){sparkConfig.serverGroups=b;var e=new hi5.DataTable(b);b=new hi5.DataGrid(document.getElementById("serverGroups.rows"));b.dataTable=e;b.open();b.onrowclick=function(f){f=f.target;(f=f["data-action"]||f.name)&&e.perform(f)};e.addEvent("beforeremove",c);e.addEvent("onaction",a)}sparkConfig.config(sparkConfig.getGatewayAddr(),"serverGroups",
"get",d)},refreshUserGroups:function(){function c(b){b=sparkConfig.userGroups.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),"userGroups","remove",d,null,"&name="+b)}function a(b){b=this.getValue(0);sparkConfig.editUserGroup(b)}function d(b){sparkConfig.userGroups=b;var e=new hi5.DataTable(b);b=new hi5.DataGrid(document.getElementById("userGroups.rows"));b.dataTable=e;b.open();b.onrowclick=function(f){f=f.target;(f=f["data-action"]||f.name)&&e.perform(f)};e.addEvent("beforeremove",c);
e.addEvent("onaction",a)}sparkConfig.config(sparkConfig.getGatewayAddr(),"userGroups","get",d)},editServerGroup:function(c){var a=document.getElementById("serverGroups.view");a.reset();var d=hi5.$("serverGroup.server"),b=new hi5.Lightbox(a);b.onclose=function(){d.hide();sparkConfig.refreshServerGroups()};sparkConfig.showMessage("");b.show();a._dataAction="post";c&&(a._dataAction="put",c={name:c,servers:sparkConfig.serverGroups.getValue(1)},hi5.browser.objToForm(c,a));d.hide||new hi5.Select(d,!0);
sparkConfig.servers||sparkConfig.refreshServers();d.beforedropdown=function(){sparkConfig.initServerList(d)}},editUserGroup:function(c){var a=document.getElementById("userGroups.view");a.reset();var d=hi5.$("userGroup.server"),b=hi5.$("userGroup.user"),e=new hi5.Lightbox(a);e.onclose=function(){d.hide();b.hide();sparkConfig.refreshUserGroups()};sparkConfig.showMessage("");e.show();a._dataAction="post";c&&(a._dataAction="put",c={name:c,users:sparkConfig.userGroups.getValue(1),servers:sparkConfig.userGroups.getValue(2)},
hi5.browser.objToForm(c,a));d.hide||new hi5.Select(d,!0);b.hide||new hi5.Select(b,!0);sparkConfig.serverGroups||sparkConfig.refreshServerGroups();sparkConfig.users||sparkConfig.refreshUsers();d.beforedropdown=function(){var f=d.options,g=sparkConfig.serverGroups;if(g){g=g.rows;for(var h=f.length=0,l=g.length;h<l;h++)f[h]=new Option(g[h][0])}};b.beforedropdown=function(){var f=b.options,g=sparkConfig.users;if(g){g=g.rows;for(var h=f.length=0,l=g.length;h<l;h++)f[h]=new Option(g[h][0])}}},saveServerGroup:function(){var c=
document.getElementById("serverGroups.view");sparkConfig.showMessage("");var a=hi5.browser.formToObj(c);if(a.servers){for(var d=a.servers.split(","),b=d.length,e=0;e<b;e++)d[e]=d[e].trim();a.servers=d}sparkConfig.config(sparkConfig.getGatewayAddr(),"serverGroup",c._dataAction||"put",function(f){f.error?sparkConfig.showMessage(f.message):(c.reset(),c._dataAction="post")},JSON.stringify(a));return!1},saveUserGroup:function(){var c=document.getElementById("userGroups.view");sparkConfig.showMessage("");
var a=hi5.browser.formToObj(c);if(a.servers){for(var d=a.servers.split(","),b=d.length,e=0;e<b;e++)d[e]=d[e].trim();a.servers=d}if(a.users){d=a.users.split(",");b=d.length;for(e=0;e<b;e++)d[e]=d[e].trim();a.users=d}sparkConfig.config(sparkConfig.getGatewayAddr(),"userGroup",c._dataAction||"put",function(f){f.error?sparkConfig.showMessage(f.message):(c.reset(),c._dataAction="post")},JSON.stringify(a));return!1},refreshUsers:function(){function c(b){b=sparkConfig.users.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),
"users","remove",d,null,"&name="+b)}function a(b){b=this.getValue(0);sparkConfig.editUser(b)}function d(b){sparkConfig.users=b;var e=new hi5.DataTable(b);b=new hi5.DataGrid(document.getElementById("users.rows"));b.dataTable=e;b.open();b.onrowclick=function(f){f=f.target;(f=f["data-action"]||f.name)&&e.perform(f)};e.addEvent("beforeremove",c);e.addEvent("onaction",a)}sparkConfig.config(sparkConfig.getGatewayAddr(),"users","get",d)},refreshSessions:function(){function c(b){b=sparkConfig.sessions.getValue(0);
sparkConfig.config(sparkConfig.getGatewayAddr(),"sessions","remove",d,null,"&id="+b)}function a(b){b=this.getValue(0);var e="join";switch(this.getValue(9)){case "RFB":e="joinvnc";break;case "SSH":e="joinssh";break;case "TELNET":e="jointelnet"}b=location.protocol+"//"+document.getElementById("gateway").value+"/"+e+".html?id="+b;window.open(b)}function d(b){sparkConfig.sessions=b;var e=new hi5.DataTable(b),f=new hi5.DataGrid(document.getElementById("sessions.rows"));e.beforeGetValue=function(g,h){return"thumbnail"==
e.cols[g].name?'<img src="'+h+'">':h};f.dataTable=e;f.open();f.onrowclick=function(g){g=g.target;(g=g["data-action"]||g.name)&&e.perform(g)};e.addEvent("beforeremove",c);e.addEvent("onaction",a);document.getElementById("sessions.size").innerHTML=b.rows.length}sparkConfig.config(sparkConfig.getGatewayAddr(),"sessions","get",d)},updateSymlink:function(){var c=document.getElementById("symlinkAccess"),a=document.getElementById("symlink.id"),d=document.getElementById("symlink.password"),b=document.getElementById("symlink.server"),
e=document.getElementById("gateway").value;a=location.protocol+"//"+e+"/rdpdirect.html?symlink="+a.value+"&gateway="+e;d.value&&(a+="&pwd="+d.value);b.value&&(d=sparkConfig.servers.find(0,b.value))&&d[3]&&(a+="&startProgram=app");c.href=a},refreshSymlinks:function(){function c(b){b=sparkConfig.symlinks.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),"symlinks","remove",d,null,"&id="+b)}function a(b){b=this.getValue(0);sparkConfig.editSymlink(b)}function d(b){sparkConfig.symlinks=b;var e=
new hi5.DataTable(b);b=new hi5.DataGrid(document.getElementById("symlinks.rows"));b.dataTable=e;e.beforeGetValue=function(h,l){h=e.cols[h].name;return"validFrom"==h||"validTo"==h?hi5.DateUtils.formatDate(l,!0):l};e.beforeSetValue=function(h,l){h=e.cols[h].name;return"validFrom"==h||"validTo"==h?hi5.DateUtils.parseDate(l).getTime():l};b.onrowclick=function(h){h=h.target;(h=h["data-action"]||h.name)&&e.perform(h)};b.open();e.addEvent("beforeremove",c);e.addEvent("onaction",a);b=document.getElementById("symlink.id");
var f=document.getElementById("symlink.password"),g=document.getElementById("symlink.server");f.onchange=b.onchange=g.onchange=sparkConfig.updateSymlink}sparkConfig.config(sparkConfig.getGatewayAddr(),"symlinks","get",d)},initUI:function(){function c(){var h="&sType="+a.value+"&display="+d.checked;sparkConfig.config(sparkConfig.getGatewayAddr(),"servers_h","put",function(){},null,h)}var a=document.getElementById("servers.type"),d=document.getElementById("servers.display");a.onchange=c;d.onchange=
c;document.getElementById("conf3").addEvent("ontabchange",function(h){sparkConfig.gateway.prop.webfeed&&(document.getElementById("servers.add").style.disabled=!0,document.getElementById("users.add").style.disabled=!0);switch(h){case 1:if(sparkConfig.servers)break;sparkConfig.refreshServers();break;case 2:if(sparkConfig.users)break;sparkConfig.refreshUsers();break;case 3:sparkConfig.servers||sparkConfig.refreshServers();if(sparkConfig.symlinks)break;sparkConfig.refreshSymlinks();break;case 4:if(sparkConfig.sessions)break;
sparkConfig.refreshSessions();break;case 5:sparkConfig.refreshServerGroups();break;case 6:sparkConfig.refreshUserGroups()}});var b=hi5.tool.queryToObj(),e=b.port;b=b.expect;if(e){var f=window.location.host,g=location.protocol;f||(f="localhost");document.getElementById("gateway").value=f;f=g+"//"+f;b&&(b=f+":"+b,document.getElementById("expectAddr").innerHTML=b,document.getElementById("expect").style.display="inline");if("http:"==g&&"80"!=e||"https:"==g&&"443"!=e)f+=":"+e;f="<a href='"+f+"'>"+f+"</a>";
document.getElementById("sparkAddr").innerHTML=f;document.getElementById("conf1").style.display="block"}else document.getElementById("gateway").value=location.host,document.getElementById("conf0").style.display="block";if(e=document.getElementById("rfxOpt"))e.onchange=function(h){h.target.checked&&(document.getElementById("colorOpt").selectedIndex=3)}},getGatewayAddr:function(){return("http:"==location.protocol?"ws:":"wss:")+"//"+document.getElementById("gateway").value},getAll:function(){sparkConfig.config(sparkConfig.getGatewayAddr(),
"gateway","get",function(c){if(!sparkConfig.checkError(c)){sparkConfig.gateway=c;c=c.prop;var a,d=document.getElementById("frmGateway").elements,b;for(b in c)if(a=d[b]){var e=a.type,f=c[b];"checkbox"==e?a.checked="true"===f:"file"!=e&&(a.value=f)}document.getElementById("conf3").style.display="block"}})},saveGateway:function(){function c(a){if(a.error){var d=__svi18n.errorCode["S"+a.name];a.message&&(d+=a.message)}else d=a.restart?__svi18n.info.restart:__svi18n.info.succeeded||"Operation succeeded.";
d&&hi5.notifications.notify(d)}(function(a,d,b){a=a.elements;for(var e=0,f=a.length;e<f;e++){var g=a[e];if(g){var h=g.value;if(""!==h&&!g.readonly){var l=g.type;"button"!=l&&"submit"!=l&&"file"!=l&&(d[g.name]="checkbox"==l?g.checked+"":h)}}}a=document.getElementById("licenseFile").files;0<a.length?hi5.file.readAsArrayBuffer(a[0],function(k){d.licenseFile=hi5.Base64.enc(k);b()}):b()})(document.getElementById("frmGateway"),sparkConfig.gateway.prop,function(){sparkConfig.config(sparkConfig.getGatewayAddr(),
"gateway","put",c,JSON.stringify(sparkConfig.gateway))})},editServer:function(c,a){function d(l){if(l.id){var k=l.rdp;k||(k={});k.isRDP=!!l.rdp;k.id=l.id;k.displayName=l.displayName;l.server&&(k.server=l.server);l.icon&&(k.icon=l.icon);if(k.mapDisk&&k.disks){for(var n=k.disks,p,q=Math.min(3,n.length),m=0;m<q;m++)k["dosName"+m]=n[m].dosName,k["devicePath"+m]=n[m].devicePath,p=n[m].actions,k["actRedirect"+m]=0!=(p&1),k["actDownload"+m]=0!=(p&2),k["actUpload"+m]=0!=(p&4);delete k.disks}if(l.vnc){n=l.vnc;
k["vnc.port"]="";k["vnc.password"]="";k.UseCopyRect=!1;k.share=!1;k["vnc.mapClipboard"]=!1;k["vnc.recording"]=0;for(m in n)"port"==m||"password"==m||"mapClipboard"==m||"color"==m||"sessionRecord"==m?k["vnc."+m]=n[m]:k[m]=n[m];k.isVNC=!0}if(l.ssh){n=l.ssh;k["ssh.mapClipboard"]=!1;k["ssh.fontSize"]="";k["ssh.port"]="";k["ssh.username"]="";k["ssh.recording"]=0;for(m in n)k["ssh."+m]=n[m];k.isSSH=!0}if(l.telnet){l=l.telnet;k["telnet.mapClipboard"]=!1;k["telnet.fontSize"]="";k["telnet.port"]="";k["telnet.recording"]=
0;for(m in l)k["telnet."+m]=l[m];k.isTELNET=!0}e=hi5.$("server.id").value;f=hi5.$("server.displayName").value;b.reset();hi5.browser.objToForm(k,b);a||(b._dataAction="put");e&&(hi5.$("server.id").value=e);f&&(hi5.$("server.displayName").value=f)}}var b=document.getElementById("servers.view"),e="",f="";a||b.reset();var g=b.visible?b:new hi5.Lightbox(b);g.onclose=function(){sparkConfig.refreshServers()};sparkConfig.showMessage("");g.visible()||g.show();b._dataAction="post";c&&sparkConfig.config(sparkConfig.getGatewayAddr(),
"server","get",d,null,"&id="+c);var h=hi5.$("server.server");h.hide||new hi5.Select(h);h.beforedropdown=function(){for(var l=h.options,k=sparkConfig.servers.rows,n=l.length=0,p=k.length;n<p;n++)l[n]=new Option(k[n][1],k[n][0])};h.onchange=function(){var l=h.value;sparkConfig.config(sparkConfig.getGatewayAddr(),"server","get",d,null,"&id="+l)}},initServerList:function(c){c=c.options;var a=sparkConfig.servers;if(a){a=a.rows;for(var d=c.length=0,b=a.length;d<b;d++)c[d]=new Option(a[d][1],a[d][0])}},
editUser:function(c){var a=document.getElementById("users.view");a.reset();var d=hi5.$("user.server"),b=new hi5.Lightbox(a);b.onclose=function(){d.hide();sparkConfig.refreshUsers()};sparkConfig.showMessage("");b.show();a._dataAction="post";c&&(a._dataAction="put",c={name:c,password:sparkConfig.users.getValue(1),servers:sparkConfig.users.getValue(2),isDomainUser:sparkConfig.users.getValue(3),domainServer:sparkConfig.users.getValue(4),transferCredential:sparkConfig.users.getValue(5)},hi5.browser.objToForm(c,
a));d.hide||new hi5.Select(d,!0);sparkConfig.servers||sparkConfig.refreshServers();d.beforedropdown=function(){sparkConfig.initServerList(d)}},importUsers:function(){var c=hi5.$("adUser").value,a=hi5.$("adPwd").value,d=hi5.$("adDomain").value,b=hi5.$("adServer").value,e=hi5.$("adOU").value,f=hi5.$("adServers"),g=hi5.$("secProtocol").value;(f=f?f.value:"")&&(f="&servers="+encodeURIComponent(f));c&&a?sparkConfig.config(sparkConfig.getGatewayAddr(),"users","import",function(h){sparkConfig.checkError(h)||
sparkConfig.refreshUsers()},null,"&user="+encodeURIComponent(c)+"&pwd="+encodeURIComponent(a)+"&domain="+encodeURIComponent(d)+"&server="+b+"&ou="+encodeURIComponent(e)+f+"&secProtocol="+g):alert("Please enter credentials.")},saveServer:function(){var c=document.getElementById("servers.view");sparkConfig.showMessage("");var a=hi5.browser.formToObj(c);if(a.mapDisk){var d=0,b=[];a.dosName0&&(a.actRedirect0&&(d|=1),a.actDownload0&&(d|=2),a.actUpload0&&(d|=4),b.push({dosName:a.dosName0,devicePath:a.devicePath0,
actions:d}),delete a.dosName0,delete a.devicePath0);a.dosName1&&(d=0,a.actRedirect1&&(d|=1),b.push({dosName:a.dosName1,devicePath:a.devicePath1,actions:d}),delete a.dosName1,delete a.devicePath1);a.dosName2&&(d=0,a.actRedirect2&&(d|=1),b.push({dosName:a.dosName2,devicePath:a.devicePath2,actions:d}),delete a.dosName2,delete a.devicePath2);0<b.length&&(a.disks=b)}d={};d.id=a.id;d.displayName=a.displayName;a.server&&(d.server=a.server);a.icon&&(d.icon=a.icon);a.isRDP&&(d.rdp=a);a.isVNC&&(d.vnc={port:a["vnc.port"],
password:a["vnc.password"],encoding:a.encoding,quality:a.quality,compression:a.compression,color:a["vnc.color"],UseCopyRect:a.UseCopyRect,share:a.share,sessionRecord:a["vnc.sessionRecord"],mapClipboard:a["vnc.mapClipboard"]});a.isSSH&&(d.ssh={mapClipboard:a["ssh.mapClipboard"],fontSize:a["ssh.fontSize"],port:a["ssh.port"],username:a["ssh.username"],sessionRecord:a["ssh.sessionRecord"],password:a["ssh.password"],keyfile:a["ssh.keyfile"],keyfilePwd:a["ssh.keyfilePwd"],terminalType:a["ssh.terminalType"]||
"xterm"});a.isTELNET&&(d.telnet={mapClipboard:a["telnet.mapClipboard"],fontSize:a["telnet.fontSize"],sessionRecord:a["telnet.sessionRecord"],port:a["telnet.port"]});sparkConfig.config(sparkConfig.getGatewayAddr(),"server",c._dataAction||"put",function(e){e.error?sparkConfig.showMessage(e.message):(c.reset(),c._dataAction="post",sparkConfig.gateway.server||sparkConfig.getAll())},JSON.stringify(d));return!1},saveUser:function(){var c=document.getElementById("users.view");sparkConfig.showMessage("");
var a=hi5.browser.formToObj(c);if(a.servers){for(var d=a.servers.split(","),b=d.length,e=0;e<b;e++)d[e]=d[e].trim();a.servers=d}sparkConfig.config(sparkConfig.getGatewayAddr(),"user",c._dataAction||"put",function(f){f.error?sparkConfig.showMessage(f.message):(c.reset(),c._dataAction="post",sparkConfig.gateway.user||sparkConfig.getAll())},JSON.stringify(a));return!1},editSymlink:function(c){var a=document.getElementById("symlinks.view");a.reset();var d=new hi5.Lightbox(a);d.onclose=function(){sparkConfig.refreshSymlinks()};
sparkConfig.showMessage("");d.show();a._dataAction="post";c?(a._dataAction="put",hi5.browser.objToForm(sparkConfig.symlinks.getObject(),a)):document.getElementById("symlink.id").value=hi5.tool.uuid();document.getElementById("symlink.id").onchange();var b=hi5.$("symlink.server");b.hide||new hi5.Select(b);sparkConfig.servers||sparkConfig.refreshServers();b.beforedropdown=function(){sparkConfig.initServerList(b)};sparkConfig.updateSymlink()},saveSymlink:function(){var c=document.getElementById("symlinks.view");
sparkConfig.showMessage("");var a=hi5.browser.formToObj(c);a.validFrom&&(a.validFrom=hi5.DateUtils.parseDate(a.validFrom).getTime());a.validTo&&(a.validTo=hi5.DateUtils.parseDate(a.validTo).getTime());sparkConfig.config(sparkConfig.getGatewayAddr(),"symlink",c._dataAction||"put",function(d){d.error?sparkConfig.showMessage(d.message):(c.reset(),c._dataAction="post",document.getElementById("symlink.id").value=hi5.tool.uuid())},JSON.stringify(a));return!1},notify:function(c,a){sparkConfig.config(sparkConfig.getGatewayAddr(),
"sessions","notify",null,null,"&msg="+c+"&sendTo="+(a||[]).join(","))}};window.addEventListener("load",sparkConfig.initUI,!1);
