var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(q){var A=0;return function(){return A<q.length?{done:!1,value:q[A++]}:{done:!0}}};$jscomp.arrayIterator=function(q){return{next:$jscomp.arrayIteratorImpl(q)}};$jscomp.makeIterator=function(q){var A="undefined"!=typeof Symbol&&Symbol.iterator&&q[Symbol.iterator];return A?A.call(q):$jscomp.arrayIterator(q)};$jscomp.arrayFromIterator=function(q){for(var A,C=[];!(A=q.next()).done;)C.push(A.value);return C};
$jscomp.arrayFromIterable=function(q){return q instanceof Array?q:$jscomp.arrayFromIterator($jscomp.makeIterator(q))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(q){var A=function(){};A.prototype=q;return new A};
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(q,A,C){if(q==Array.prototype||q==Object.prototype)return q;q[A]=C.value;return q};$jscomp.getGlobal=function(q){q=["object"==typeof globalThis&&globalThis,q,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var A=0;A<q.length;++A){var C=q[A];if(C&&C.Math==Math)return C}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(q,A){var C=$jscomp.propertyToPolyfillSymbol[A];if(null==C)return q[A];C=q[C];return void 0!==C?C:q[A]};
$jscomp.polyfill=function(q,A,C,Q){A&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(q,A,C,Q):$jscomp.polyfillUnisolated(q,A,C,Q))};$jscomp.polyfillUnisolated=function(q,A,C,Q){C=$jscomp.global;q=q.split(".");for(Q=0;Q<q.length-1;Q++){var R=q[Q];if(!(R in C))return;C=C[R]}q=q[q.length-1];Q=C[q];A=A(Q);A!=Q&&null!=A&&$jscomp.defineProperty(C,q,{configurable:!0,writable:!0,value:A})};
$jscomp.polyfillIsolated=function(q,A,C,Q){var R=q.split(".");q=1===R.length;Q=R[0];Q=!q&&Q in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var Da=0;Da<R.length-1;Da++){var Ja=R[Da];if(!(Ja in Q))return;Q=Q[Ja]}R=R[R.length-1];C=$jscomp.IS_SYMBOL_NATIVE&&"es6"===C?Q[R]:null;A=A(C);null!=A&&(q?$jscomp.defineProperty($jscomp.polyfills,R,{configurable:!0,writable:!0,value:A}):A!==C&&($jscomp.propertyToPolyfillSymbol[R]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(R):$jscomp.POLYFILL_PREFIX+
R,R=$jscomp.propertyToPolyfillSymbol[R],$jscomp.defineProperty(Q,R,{configurable:!0,writable:!0,value:A})))};
$jscomp.getConstructImplementation=function(){function q(){function C(){}new C;Reflect.construct(C,[],function(){});return new C instanceof C}if($jscomp.TRUST_ES6_POLYFILLS&&"undefined"!=typeof Reflect&&Reflect.construct){if(q())return Reflect.construct;var A=Reflect.construct;return function(C,Q,R){C=A(C,Q);R&&Reflect.setPrototypeOf(C,R.prototype);return C}}return function(C,Q,R){void 0===R&&(R=C);R=$jscomp.objectCreate(R.prototype||Object.prototype);return Function.prototype.apply.call(C,R,Q)||
R}};$jscomp.construct={valueOf:$jscomp.getConstructImplementation}.valueOf();$jscomp.underscoreProtoCanBeSet=function(){var q={a:!0},A={};try{return A.__proto__=q,A.a}catch(C){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(q,A){q.__proto__=A;if(q.__proto__!==A)throw new TypeError(q+" is not extensible");return q}:null;
$jscomp.inherits=function(q,A){q.prototype=$jscomp.objectCreate(A.prototype);q.prototype.constructor=q;if($jscomp.setPrototypeOf){var C=$jscomp.setPrototypeOf;C(q,A)}else for(C in A)if("prototype"!=C)if(Object.defineProperties){var Q=Object.getOwnPropertyDescriptor(A,C);Q&&Object.defineProperty(q,C,Q)}else q[C]=A[C];q.superClass_=A.prototype};$jscomp.polyfill("Reflect",function(q){return q?q:{}},"es6","es3");$jscomp.polyfill("Reflect.construct",function(q){return $jscomp.construct},"es6","es3");
$jscomp.polyfill("Reflect.setPrototypeOf",function(q){if(q)return q;if($jscomp.setPrototypeOf){var A=$jscomp.setPrototypeOf;return function(C,Q){try{return A(C,Q),!0}catch(R){return!1}}}return null},"es6","es5");svGlobal.DCVC_EXTENSION||(svGlobal.DCVC_EXTENSION={});
svGlobal.DCVC_EXTENSION.GFX=function(q,A){function C(){function d(){var v=[];this.cursor=0;this.init=function(h,w){var b=v[h];b?b.length=w:(b=Array(w),v[h]=b);return b};this.get=function(h){return v[h]};return this}var l=new rdpcodecs.NSCodec,t=l.process,u=hi5.Arrays.arraycopy,F=[0,0,1,1,2,2,2,2,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7],g=[0,1,3,7,15,31,63,127,255],O=new d,H=new d,D=new d;this.decode=function(v,h,w,b,L,f,n,y){var z,m,E=0;n=L+h;y=f+w;var I,r=v.getData();v.getPosition();var aa=v.getByte();var k=v.getByte();v.getPosition();if(65535<
h||65535<w)return-1004;if(k!=k)return-1005;aa&4&&(H.cursor=0,D.cursor=0);if(aa&2&&!(aa&1))return-1006;if(aa&1){if(1048576<h*w)return-1007;E=v.getLittleEndian16();v.getPosition();if(4E3<=E)return-1009;if(aa&2){v=O.get(E);if(!v)return-1010;if(h*w>v.length)return-1011;var B=0;for(m=f;m<y;m++){var V=b[m];for(z=L;z<n;z++)V[z]=v[B++]}return 1}}if(!v.has(12))return-1012;var S=v.getLittleEndian32();var ea=v.getLittleEndian32();var la=v.getLittleEndian32();var ha=v.getPosition();if(0<S){if(!v.has(S))return-1013;
var G=0;var T=h*w;z=L;m=f;V=b[m];k=v.getPosition();for(I=k+S;k<I;){if(4>I-k)return-1015;var P=4278190080|r[k++]<<16|r[k++]<<8|r[k++];var K=r[k++];if(255<=K){if(2>I-k)return-1016;K=r[k++]|r[k++]<<8;if(65535<=K){if(4>I-k)return-1017;K=r[k++]|r[k++]<<8|r[k++]<<16|r[k++]<<24}}if(G+K>T)return-1018;for(B=0;B<K;B++)z>=n&&(z=L,m++,V=b[m]),V[z++]=P;G+=K}ha+=S;v.skipPosition(S);v.getPosition()!=ha&&console.log("xxx postion")}if(0<ea){k=ha;if(!v.has(ea))return-1020;for(I=ha+ea;k<I;){T=0;var fa=0;if(11>I-k)return-1021;
z=r[k++]|r[k++]<<16;xEnd=r[k++]|r[k++]<<16;V=r[k++]|r[k++]<<16;yEnd=r[k++]|r[k++]<<16;var ka=4278190080|r[k++]<<16|r[k++]<<8|r[k++];if(xEnd<z)return-1022;if(yEnd<V)return-1023;var Y=xEnd-z+1;for(B=0;B<Y;B++){m=!1;if(2>I-k)return-1024;G=r[k++]|r[k++]<<8;S=yEnd-V+1;if(52<S)return-1025;if(16384==(G&49152)){G&=16383;if(16384<=G)return-1026;if(1>I-k)return-1027;T=r[k++];G=D.get(G);if(!G)return-1028;fa=G.length;m=!0}else if(0==(G&49152)){T=G&255;m=G>>8&63;if(m<T)return-1029;fa=m-T;if(52<fa)return-1030;
if(I-k<3*fa)return-1031;if(16384<=D.cursor)return-1032;G=D.init(D.cursor,fa);for(m=P=0;m<fa;m++)G[P++]=4278190080|r[k++]<<16|r[k++]<<8|r[k++];D.cursor=(D.cursor+1)%16384;m=!0}else if(32768==(G&32768)){G&=32767;if(32768<=G)return-1034;var ca=H.get(G)}else return-1035;if(m){if(32768<=H.cursor)return-1036;ca=H.init(H.cursor,S);m=P=0;G=T;for(m+G>S&&(G=S>m?S-m:0);G--;)ca[P++]=ka;m=T;G=fa;m+G>S&&(G=S>m?S-m:0);K=m-T;u(ca,K,ca,P,G);P+=G;m=T+fa;for(G=S>m?S-m:0;G--;)ca[P++]=ka;H.cursor=(H.cursor+1)%32768}S=
L+z;m=f+V;K=0;G=yEnd-V+1;if(ca.length!=G)return-1038;for(G=m+G;m<G;m++)b[m][S]=ca[K++]}}ha+=ea;v.skipPosition(ea)}if(0<la){if(!v.has(la))return-1039;k=ha;for(I=ha+la;k<I;){if(13>I-k)return-1040;z=r[k++]|r[k++]<<8;V=r[k++]|r[k++]<<8;K=r[k++]|r[k++]<<8;P=r[k++]|r[k++]<<8;ca=r[k++]|r[k++]<<8|r[k++]<<16|r[k++]<<24;B=r[k++];if(I-k<ca)return-1041;S=L+z;m=f+V;if(K>h)return-1042;if(P>w)return-1043;G=m+P;ea=S+K;if(0==B){if(ca!=K*P*3)return-1045;for(T=k;m<G;m++)for(V=b[m],z=S;z<ea;z++)V[z]=4278190080|r[T++]<<
16|r[T++]<<8|r[T++]}else if(1==B)for(v.setPosition(k),t(v,32,K,P),B=l.getData(),T=0;m<G;m++)for(V=b[m],z=S;z<ea;z++)V[z]=B[T++];else if(2==B){fa=new Uint32Array(128);ka=r[k];T=k+1;Y=T+3*ka;if(127<ka)return-1047;for(B=0;B<ka;B++)fa[B]=4278190080|r[T++]<<16|r[T++]<<8|r[T++];G=0;T=K*P;var qa=F[ka-1]+1;var oa=k+ca;z=S;for(V=b[m];Y<oa;){if(2>oa-Y)return-1048;P=r[Y]&g[qa];var ra=r[Y]>>qa&g[8-qa];B=P-ra;Y++;K=r[Y++];if(255<=K){if(2>oa-Y)return-1049;K=r[Y++]|r[Y++]<<8;if(65535<=K){if(4>oa-Y)return-1050;K=
r[Y++]|r[Y++]<<8|r[Y++]<<16|r[Y++]<<24}}if(B>=ka)return-1051;if(P>=ka)return-1052;var ta=B;P=fa[ta];if(G+K>T)return-1053;for(B=0;B<K;B++)z>=ea&&(z=S,m++,V=b[m]),V[z++]=P;G+=K;if(G+(ra+1)>T)return-1054;for(B=0;B<=ra;B++)z>=ea&&(z=S,m++,V=b[m]),V[z++]=fa[ta++];G+=ra+1}if(G!=T)return-1055}else return-1056;k+=ca}v.setPosition(ha+la)}if(aa&1)for(v=O.init(E,h*w),B=0,m=f;m<y;m++)for(V=b[m],z=L;z<n;z++)v[B++]=V[z];return 1};this.reset=function(){H.cursor=0;D.cursor=0;return 1}}function Q(d,l,t){function u(){for(;D;){if(y.updating){D=
!1;break}var E=H.shift();if(!E)break;try{y.appendBuffer(E),v=0}catch(I){if("QuotaExceededError"==I.name&&!O(!0)){console.log("QuotaExceededError: not recoverable");if(h.onerror)h.onerror(I);else h.close();break}v++;H.unshift(E);console.error("Failed to append segment to the video source buffer, retry "+v,I);if(2<v){if(h.onerror)h.onerror(I);break}}}}function F(){D=!0;u()}function g(){y=n.addSourceBuffer(w);y.mode="sequence";y.addEventListener("update",F);y.addEventListener("error",function(E){console.error(E)});
D=!0;h.play(!1);u()}function O(E){var I=9E4*Math.min(d.played.end(0),y.buffered.end(0))|0,r=0,aa=f.length,k=!1;if(1<aa){for(var B=aa-2;r<aa;){if(f[r]>I){B=r-2;break}r++}if(0<=B){I=(f[B]+1E3)/9E4;try{y.remove(0,I),f.splice(0,B+1),k=!0}catch(V){console.log("Remote "+I+" failed, retry")}}}E||(L=setTimeout(O,18E4));return k}var H=[],D=!1,v=0,h=this,w="",b=null,L=0,f=[],n=null,y=null,z=null,m=null;d.muted=!0;d.autoplay=!0;this.getKeyFrames=function(){return f};z=new Da(!1);z.ondata=function(E){H.push(E);
u()};m=new R(z);m.onkeyframe=function(E){f.push(E.timestamp)};m.oncodec=function(E,I){var r="video/mp4;codecs=";r=E?r+E:r+"avc1.420028";if(r==w&&null!=b&&b.width==I.width&&b.height==I.height)console.log("oncodec, not changed: "+E+" width: "+I.width+" height: "+I.height,I);else if(console.log("oncodec, changed: "+E+" width: "+I.width+" height: "+I.height,I),w=r,b=I,D=!1,y=null,n=new MediaSource,n.addEventListener("sourceopen",g),d.src=URL.createObjectURL(n),h.onsps)h.onsps(I)};l.onvideoframe=function(E){m.parseH264Data(E)};
l.onendofstream=function(){h.reset()};this.play=function(E){d.play().catch(function(I){console.error(I);if(!E&&h.onplayerror)h.onplayerror(I)})};this.reset=function(){console.log("Reset player");L&&(clearTimeout(L),L=0);f.length=0;D=!1;w="";b=null;l&&l.reset&&l.reset();m&&m.reset();H.length=0};this.close=function(){h&&(h.reset(),n&&(n.endOfStream(),d.src=null),m&&m.close(),z&&z.close(),h=null)};d.addEventListener("ended",function(E){console.warn(".... ended");L&&(clearTimeout(L),L=0)});d.addEventListener("emptied",
function(E){console.warn(".... emptied");D=!!y});d.addEventListener("pause",function(E){console.warn(".... paused");D=!!y;d.play().catch(function(I){console.error(I)})});d.addEventListener("waiting",function(E){D=!!y});d.addEventListener("playing",function(E){0==d.played.length&&console.log("played.length == 0, not possible");t&&(L=setTimeout(O,18E4))})}function R(d){function l(){this.height=this.width=0;this.codec="";this.pps=this.sps=null;this.frameDuration=3E3;this.samples=[];this.sequence=this.unitNum=
this.totalByteLength=0;this.clear=function(){this.unitNum=this.totalByteLength=this.samples.length=0}}function t(){this.units=H;this.unitsLength=D;this.timestamp=F;this.hasIDR=g}function u(){var b=!1;if(O){var L=new t;F+=h.frameDuration||3E3;h.samples.push(L);h.totalByteLength+=D;h.unitNum+=H.length;h.sequence++;b=!0;if(L.hasIDR&&w.onkeyframe)w.onkeyframe(L)}O=g=!1;H=[];D=0;return b}var F=0,g=!1,O=!1,H=[],D=0,v=lb.searchStartCode,h=null,w=this;h=new l;this.reset=function(){F=0;g=!1;H=[];D=0;h=new l;
d&&d.reset()};this.close=function(){w&&(w.reset(),w=null)};this.parseH264Data=function(b){for(var L=[],f=0,n,y,z,m=[0,0];f<b.byteLength;){m[0]=f;v(b,m);var E=m[0];if(-1==E)break;f=m[1];f=E+f;z=b[f];z&=31;n&&(n={type:y,data:b.subarray(n,E)},L.push(n));n=f;y=z}n&&(n={type:y,data:b.subarray(n,b.byteLength)},L.push(n));for(b=0;b<L.length;b++)switch(m=L[b],f=m.type,f){case 1:case 2:case 3:case 4:H.push(m);D+=m.data.byteLength;O=!0;break;case 5:O=g=!0;H.push(m);D+=m.data.byteLength;break;case 6:break;case 7:n=
m.data;f="avc1."+(0==n[1]?"00":n[1].toString(16));f+=0==n[2]?"00":n[2].toString(16);f+=0==n[3]?"00":n[3].toString(16);n=new Ja(m.data);n=n.readSPS();h.width=n.width;h.height=n.height;h.codec=f;h.sps=m.data;n.fps&&(h.frameDuration=9E4/n.fps|0);H.push(m);D+=m.data.byteLength;if(w.oncodec)w.oncodec(f,n);break;case 8:h.pps=m.data;H.push(m);D+=m.data.byteLength;break;case 9:u();break;default:console.log("Ignore NAL unit with type = "+f)}u()&&(d.remux(h),h.clear())}}function Da(d){function l(a,c,e){c[e]=
a>>24&255;c[e+1]=a>>16&255;c[e+2]=a>>8&255;c[e+3]=a&255}function t(a,c){var e=a.length;c=new Uint8Array(c?e+1:e);for(var p=0;p<e;p++)c[p]=a.charCodeAt(p);return c}var u=new Uint8Array([0,0,0,0]),F=new Uint8Array([255,255,255,255]),g={avc1:[],avcC:[],btrt:[],dinf:[],dref:[],esds:[],ftyp:[],hdlr:[],mdat:[],mdhd:[],mdia:[],mfhd:[],minf:[],moof:[],moov:[],mp4a:[],mvex:[],mvhd:[],sdtp:[],stbl:[],stco:[],stsc:[],stsd:[],stsz:[],stts:[],tfdt:[],tfhd:[],traf:[],trak:[],trun:[],trex:[],tkhd:[],vmhd:[],smhd:[],
mehd:[]},O=this,H=1,D=d?48E3:9E4,v=1,h=!1,w=null;this.initTypes=function(){for(var a in g)g[a]=[a.charCodeAt(0),a.charCodeAt(1),a.charCodeAt(2),a.charCodeAt(3)];g.url=[117,114,108,32]};O.initTypes();this.reset=function(){h=!1;v=H=1};this.close=function(){O&&(O.reset(),O=null)};this.remux=function(a){a.id=H;a.isAudio=d;a.timeScale=d?a.firstHeader.sampleRate:D;if(!h){var c=new L(d),e=new f(a);w=new Uint8Array(c.data.length+e.data.length);w.set(c.data,0);w.set(e.data,c.data.length);h=!0}a.sequenceNumber=
v++;c=new ra(a);e=new wa(a);a=new Uint8Array(c.data.length+e.data.length);a.set(c.data,0);a.set(e.data,c.data.length);w&&(c=new Uint8Array(w.length+a.length),c.set(w,0),c.set(a,w.length),a=c,w=null);if(O.ondata)O.ondata(a)};var b=function(a){this.type=a;this.data=null};b.prototype.setData=function(){var a=Array.prototype.slice.call(arguments,0),c=a.length,e=8,p;for(p=0;p<c;p++)e+=a[p].byteLength;this.data=new Uint8Array(e);l(e,this.data,0);this.data.set(this.type,4);e=8;for(p=0;p<c;p++)this.data.set(a[p],
e),e+=a[p].byteLength};var L=function(a){var c=b.call(this,g.ftyp)||this;var e=t("mp42"),p=t("mp41"),x=t("isom"),J=t("avc1"),M=t("iso5"),U=new Uint8Array([0,0,2,0]);a?c.setData(e,U,e,p,x,M):c.setData(x,U,x,p,M,J);return c};$jscomp.inherits(L,b);var f=function(a){var c=b.call(this,g.moov)||this;var e=new n(a),p=new y(a);a=new qa(a);c.setData(e.data,p.data,a.data);return c};$jscomp.inherits(f,b);var n=function(a){a=b.call(this,g.mvhd)||this;var c=new Uint8Array([0]),e=new Uint8Array([0,0,0]),p=new Uint8Array([0,
0,0,0]),x=new Uint8Array([0,0,0,0]),J=new Uint8Array(4);l(1E3,J,0);var M=new Uint8Array([0,1,0,0]),U=new Uint8Array([1,0]),W=new Uint8Array(10),N=new Uint8Array(36);N[1]=1;N[17]=1;N[32]=64;var Z=new Uint8Array(24),X=new Uint8Array([255,255,255,255]);a.setData(c,e,p,x,J,u,M,U,W,N,Z,X);return a};$jscomp.inherits(n,b);var y=function(a){var c=b.call(this,g.trak)||this;var e=new z(a);a=new m(a);c.setData(e.data,a.data);return c};$jscomp.inherits(y,b);var z=function(a){var c=b.call(this,g.tkhd)||this;var e=
new Uint8Array([0]),p=new Uint8Array([0,0,7]),x=new Uint8Array([0,0,0,0]),J=new Uint8Array([0,0,0,0]),M=new Uint8Array(4);l(a.id,M,0);var U=new Uint8Array(4),W=new Uint8Array(8),N=new Uint8Array([0,0]),Z=new Uint8Array([0,0]),X=a.isAudio?new Uint8Array([1,0]):new Uint8Array([0,0]),ba=new Uint8Array(2),da=new Uint8Array(36);da[1]=1;da[17]=1;da[32]=64;var ia=new Uint8Array(4);ia[0]=a.width>>8&255;ia[1]=a.width&255;ia[2]=0;ia[3]=0;var ma=new Uint8Array(4);ma[0]=a.height>>8&255;ma[1]=a.height&255;ma[2]=
0;ma[3]=0;c.setData(e,p,x,J,M,U,u,W,N,Z,X,ba,da,ia,ma);return c};$jscomp.inherits(z,b);var m=function(a){var c=b.call(this,g.mdia)||this;var e=new E(a),p=new I(a);a=new r(a);c.setData(e.data,p.data,a.data);return c};$jscomp.inherits(m,b);var E=function(a){var c=b.call(this,g.mdhd)||this;var e=new Uint8Array([0]),p=new Uint8Array([0,0,0]),x=new Uint8Array([0,0,0,0]),J=new Uint8Array([0,0,0,0]),M=new Uint8Array(4);l(a.timeScale,M,0);a=new Uint8Array([85,196]);var U=new Uint8Array(2);c.setData(e,p,x,
J,M,u,a,U);return c};$jscomp.inherits(E,b);var I=function(a){var c=b.call(this,g.hdlr)||this;var e=new Uint8Array([0]),p=new Uint8Array([0,0,0]),x=new Uint8Array(4);a=a.isAudio?t("soun"):t("vide");var J=new Uint8Array(12),M=t("Remote Spark Handler",!0);c.setData(e,p,x,a,J,M);return c};$jscomp.inherits(I,b);var r=function(a){var c=b.call(this,g.minf)||this;var e=new aa,p=new k,x=new B,J=new ea(a);a.isAudio?c.setData(p.data,x.data,J.data):c.setData(e.data,x.data,J.data);return c};$jscomp.inherits(r,
b);var aa=function(){var a=b.call(this,g.vmhd)||this;var c=new Uint8Array([0]),e=new Uint8Array([0,0,1]),p=new Uint8Array([0,0]),x=new Uint8Array(6);a.setData(c,e,p,x);return a};$jscomp.inherits(aa,b);var k=function(){var a=b.call(this,g.smhd)||this;var c=new Uint8Array([0]),e=new Uint8Array([0,0,0]),p=new Uint8Array([0,0]),x=new Uint8Array(2);a.setData(c,e,p,x);return a};$jscomp.inherits(k,b);var B=function(){var a=b.call(this,g.dinf)||this;var c=new V;a.setData(c.data);return a};$jscomp.inherits(B,
b);var V=function(){var a=b.call(this,g.dref)||this;var c=new Uint8Array([0]),e=new Uint8Array([0,0,0]),p=new Uint8Array([0,0,0,1]),x=new S;a.setData(c,e,p,x.data);return a};$jscomp.inherits(V,b);var S=function(){var a=b.call(this,g.url)||this;var c=new Uint8Array([0]),e=new Uint8Array([0,0,1]);a.setData(c,e);return a};$jscomp.inherits(S,b);var ea=function(a){var c=b.call(this,g.stbl)||this;a=new la(a);var e=new fa,p=new ka,x=new Y,J=new ca;c.setData(a.data,e.data,p.data,x.data,J.data);return c};
$jscomp.inherits(ea,b);var la=function(a){var c=b.call(this,g.stsd)||this;var e=new Uint8Array([0]),p=new Uint8Array([0,0,0]),x=new Uint8Array([0,0,0,1]);a.isAudio?(a=new ha(a),c.setData(e,p,x,a.data)):(a=new T(a),c.setData(e,p,x,a.data));return c};$jscomp.inherits(la,b);var ha=function(a){var c=b.call(this,g.mp4a)||this;var e=new Uint8Array(6),p=new Uint8Array([0,1]),x=new Uint8Array(8),J=new Uint8Array([0,2]),M=new Uint8Array([0,16]),U=new Uint8Array([0,0]),W=new Uint8Array(2),N=a.firstHeader.sampleRate,
Z=new Uint8Array(4);Z[0]=N>>8&255;Z[1]=N&255;Z[2]=0;Z[3]=0;a=new G(a);c.setData(e,p,x,J,M,U,W,Z,a.data);return c};$jscomp.inherits(ha,b);var G=function(a){var c=b.call(this,g.esds)||this;var e=new Uint8Array([0]),p=new Uint8Array([0,0,0]),x=new Uint8Array([3]),J=new Uint8Array([25]),M=new Uint8Array([0,0]),U=new Uint8Array([0]),W=new Uint8Array([4]),N=new Uint8Array([17]),Z=new Uint8Array([64]),X=new Uint8Array([21]),ba=new Uint8Array(3),da=a.bufferSizeDB;ba[0]=da>>16&255;ba[1]=da>>8&255;ba[2]=da&
255;da=new Uint8Array(4);l(a.bitRate,da,0);var ia=new Uint8Array(4);l(a.bitRate,ia,0);var ma=new Uint8Array([5]),Ka=new Uint8Array([2]),xa=a.firstHeader.frequencyIdx,Ea=a.firstHeader.channelConfig;a=new Uint8Array(2);a[0]=16|xa>>1&7;a[1]=(xa&1)<<7|Ea<<3;xa=new Uint8Array([6]);Ea=new Uint8Array([1]);var ya=new Uint8Array([2]);c.setData(e,p,x,J,M,U,W,N,Z,X,ba,da,ia,ma,Ka,a,xa,Ea,ya);return c};$jscomp.inherits(G,b);var T=function(a){var c=b.call(this,g.avc1)||this;var e=new Uint8Array(6),p=new Uint8Array([0,
1]),x=new Uint8Array([0,0]),J=new Uint8Array(2),M=new Uint8Array(12),U=new Uint8Array(2);U[0]=a.width>>8&255;U[1]=a.width&255;var W=new Uint8Array(2);W[0]=a.height>>8&255;W[1]=a.height&255;var N=new Uint8Array([0,72,0,0]),Z=new Uint8Array([0,72,0,0]),X=new Uint8Array(4),ba=new Uint8Array([0,1]),da=t("SparkStreamPlayer"),ia=new Uint8Array(32);ia[0]=da.length;ia.set(da,1);da=new Uint8Array([0,24]);var ma=new Uint8Array([255,255]);a=new P(a);c.setData(e,p,x,J,M,U,W,N,Z,X,ba,ia,da,ma,a.data);return c};
$jscomp.inherits(T,b);var P=function(a){var c=b.call(this,g.avcC)||this;var e=new Uint8Array([1]),p=new Uint8Array([a.sps[1]]),x=new Uint8Array([a.sps[2]]),J=new Uint8Array([a.sps[3]]),M=new Uint8Array([255]),U=new Uint8Array([225]),W=new Uint8Array(2),N=a.sps.byteLength;W[0]=N>>8&255;W[1]=N&255;N=new Uint8Array(a.sps);var Z=new Uint8Array([1]),X=new Uint8Array(2),ba=a.pps.byteLength;X[0]=ba>>8&255;X[1]=ba&255;a=new Uint8Array(a.pps);c.setData(e,p,x,J,M,U,W,N,Z,X,a);return c};$jscomp.inherits(P,b);
var K=function(){var a=b.call(this,g.btrt)||this;var c=new Uint8Array([0,28,156,128]),e=new Uint8Array([0,45,198,192]),p=new Uint8Array([0,45,198,192]);a.setData(c,e,p);return a};$jscomp.inherits(K,b);var fa=function(){var a=b.call(this,g.stts)||this;var c=new Uint8Array([0]),e=new Uint8Array([0,0,0]),p=new Uint8Array([0,0,0,0]);a.setData(c,e,p);return a};$jscomp.inherits(fa,b);var ka=function(){var a=b.call(this,g.stsc)||this;var c=new Uint8Array([0]),e=new Uint8Array([0,0,0]),p=new Uint8Array([0,
0,0,0]);a.setData(c,e,p);return a};$jscomp.inherits(ka,b);var Y=function(){var a=b.call(this,g.stsz)||this;var c=new Uint8Array([0]),e=new Uint8Array([0,0,0]),p=new Uint8Array([0,0,0,0]),x=new Uint8Array([0,0,0,0]);a.setData(c,e,p,x);return a};$jscomp.inherits(Y,b);var ca=function(){var a=b.call(this,g.stco)||this;var c=new Uint8Array([0]),e=new Uint8Array([0,0,0]),p=new Uint8Array([0,0,0,0]);a.setData(c,e,p);return a};$jscomp.inherits(ca,b);var qa=function(a){var c=b.call(this,g.mvex)||this;a=new oa(a);
c.setData(a.data);return c};$jscomp.inherits(qa,b);K=function(a){a=b.call(this,g.mehd)||this;var c=new Uint8Array([0]),e=new Uint8Array([0,0,0]);a.setData(c,e,F);return a};$jscomp.inherits(K,b);var oa=function(a){var c=b.call(this,g.trex)||this;var e=new Uint8Array([0]),p=new Uint8Array([0,0,0]),x=new Uint8Array(4);l(a.id,x,0);a=new Uint8Array([0,0,0,1]);var J=new Uint8Array([0,0,0,0]),M=new Uint8Array([0,0,0,0]),U=new Uint8Array([0,0,0,0]);c.setData(e,p,x,a,J,M,U);return c};$jscomp.inherits(oa,b);
var ra=function(a){var c=b.call(this,g.moof)||this;ta.setSequenceNumber(a.sequenceNumber);a=new na(a);c.setData(ta.data,a.data);return c};$jscomp.inherits(ra,b);K=function(a){var c=b.call(this,g.mfhd)||this;var e=new Uint8Array([0]),p=new Uint8Array([0,0,0]),x=new Uint8Array(4);l(a,x,0);c.setData(e,p,x);return c};$jscomp.inherits(K,b);K.prototype.setSequenceNumber=function(a){l(a,this.data,12)};var ta=new K(1),na=function(a){var c=b.call(this,g.traf)||this;za.setTrackId(a.id);za.setSampleDuration(a.frameDuration);
Aa.setBaseMediaDecodeTime(a.samples[0].timestamp);var e=32+za.data.length+Aa.data.length;if(a.isAudio)a=new ua(a,null,e);else{for(var p=[],x=0;x<a.samples.length;x++){var J=a.samples[x];p.push({size:J.unitsLength+4*J.units.length,duration:a.frameDuration||3E3,compositionTimeOffset:0,flags:{isLeading:0,dependsOn:J.hasIDR?2:1,isDependedOn:0,hasRedundancy:0,isNonSync:J.hasIDR?0:1,degradationPriority:0}})}a=new ua(a,p,e)}c.setData(za.data,Aa.data,a.data);return c};$jscomp.inherits(na,b);K=function(a,
c){var e=b.call(this,g.tfhd)||this;e.isAudio=c;var p=new Uint8Array([0]),x=c?new Uint8Array([2,0,10]):new Uint8Array([2,0,40]),J=new Uint8Array(4);l(a,J,0);c?(a=new Uint8Array([0,0,0,1]),c=new Uint8Array(4),l(1024,c,0),e.setData(p,x,J,a,c)):(a=new Uint8Array([0,0,2,0,1,1,0,0]),e.setData(p,x,J,a));return e};$jscomp.inherits(K,b);K.prototype.setTrackId=function(a){l(a,this.data,12)};K.prototype.setSampleDuration=function(a){this.isAudio?l(a,this.data,20):l(a,this.data,16)};var za=new K(0,d);K=function(a){var c=
b.call(this,g.tfdt)||this;var e=new Uint8Array([0]),p=new Uint8Array([0,0,0]),x=new Uint8Array(4);l(a,x,0);c.setData(e,p,x);return c};$jscomp.inherits(K,b);K.prototype.setBaseMediaDecodeTime=function(a){l(a,this.data,12)};var Aa=new K(0),ua=function(a,c,e){var p=b.call(this,g.trun)||this;var x=new Uint8Array([0]),J=a.isAudio?new Uint8Array([0,2,1]):new Uint8Array([0,15,1]),M=a.isAudio?4:16;e+=M*(c?c.length:a.samples.length)+28;var U=new Uint8Array(4);a.isAudio?l(a.samples.length,U,0):l(c.length,U,
0);var W=new Uint8Array(4);l(e,W,0);if(a.isAudio){e=new Uint8Array(M*a.samples.length);for(var N=0;N<a.samples.length;N++)l(a.samples[N].aacData.byteLength,e,M*N)}else for(e=new Uint8Array(M*c.length),N=0;N<c.length;N++){a=c[N];var Z=M*N;l(a.duration,e,Z);l(a.size,e,Z+4);var X=a.flags,ba=new Uint8Array(4);ba[0]=X.isLeading<<2|X.dependsOn;ba[1]=X.isDependedOn<<6|X.hasRedundancy<<4|0|X.isNonSync;ba[2]=X.degradationPriority&61440;ba[3]=X.degradationPriority&15;e.set(ba,Z+8);l(a.compositionTimeOffset,
e,Z+12)}p.setData(x,J,U,W,e);return p};$jscomp.inherits(ua,b);K=function(a){var c=b.call(this,g.sdtp)||this;for(var e=new Uint8Array([0]),p=new Uint8Array([0,0,0]),x=new Uint8Array(a.length),J=0;J<a.length;J++){var M=a[J].flags;x[J]=M.isLeading<<6|M.dependsOn<<4|p.isDependedOn<<2|p.hasRedundancy}c.setData(e,p,x);return c};$jscomp.inherits(K,b);var wa=function(a){var c=b.call(this,g.mdat)||this;if(a.isAudio){for(var e=new Uint8Array(a.totalByteLength),p=0,x=0;x<a.samples.length;x++){var J=a.samples[x].aacData;
e.set(J,p);p+=J.byteLength}c.setData(e)}else{e=new Uint8Array(4*a.unitNum+a.totalByteLength);for(x=p=0;x<a.samples.length;x++){J=a.samples[x];for(var M=0;M<J.units.length;M++){var U=J.units[M],W=U.data.byteLength;l(W,e,p);p+=4;e.set(U.data,p);p+=W}}c.setData(e)}return c};$jscomp.inherits(wa,b)}function Ja(d){function l(){if(0==H)throw Error("no data available");var h=0,w=O-H;for(D=0;w<O;){var b=d[w];if(3!=b||0!=d[w-1]||0!=d[w-2])D=D<<8|b,h++;w++;if(4<=h)break}4>h&&(D<<=4-h);v=8*h;H=O-w}function t(h){if(!(v>
h)){h-=v;var w=h>>3;h-=w>>3;H-=w;l()}D<<=h;v-=h}function u(h){var w=Math.min(v,h),b=D>>>32-w;32<h&&logger.error("Read more than 32 bits:"+h);v-=w;0<v?D<<=w:0<H&&l();w=h-w;return 0<w?b<<w|u(w):b}function F(){var h;for(h=0;h<v;++h)if(0!==(D&2147483648>>>h))return D<<=h,v-=h,h;l();return h+F()}function g(){t(1+F())}var O=d.byteLength,H=O,D=0,v=0;this.readUEG=function(){var h=F();return u(h+1)-1};this.readEG=function(){var h=this.readUEG();return 1&h?1+h>>>1:-1*(h>>>1)};this.readBool=function(){return 1===
u(1)};this.readU8=function(){return u(8)};this.readU16=function(){return u(16)};this.readU32=function(){return u(32)};this.skipScalingList=function(h){var w=8,b=8,L;for(L=0;L<h;L++)0!==b&&(b=this.readEG(),b=(w+b+256)%256),w=0===b?w:b};this.readSPS=function(){var h=0,w=0,b=0,L=0,f=1,n,y=0,z=!0,m=this.readU8();var E=this.readU8();u(5);t(3);this.readU8();g();if(100===E||110===E||122===E||244===E||44===E||83===E||86===E||118===E||128===E||138===E||139===E||134===E||135===E){var I=this.readUEG();3===I&&
t(1);g();g();t(1);if(this.readBool()){var r=3!==I?8:12;for(n=0;n<r;n++)this.readBool()&&(6>n?this.skipScalingList(16):this.skipScalingList(64))}}g();n=this.readUEG();if(0===n)this.readUEG();else if(1===n)for(t(1),t(1+F()),t(1+F()),r=this.readUEG(),n=0;n<r;n++)t(1+F());g();t(1);n=this.readUEG();r=this.readUEG();var aa=u(1);0===aa&&t(1);t(1);this.readBool()&&(h=this.readUEG(),w=this.readUEG(),b=this.readUEG(),L=this.readUEG());if(this.readBool()){if(this.readBool()){switch(this.readU8()){case 1:var k=
[1,1];break;case 2:k=[12,11];break;case 3:k=[10,11];break;case 4:k=[16,11];break;case 5:k=[40,33];break;case 6:k=[24,11];break;case 7:k=[20,11];break;case 8:k=[32,11];break;case 9:k=[80,33];break;case 10:k=[18,11];break;case 11:k=[15,11];break;case 12:k=[64,33];break;case 13:k=[160,99];break;case 14:k=[4,3];break;case 15:k=[3,2];break;case 16:k=[2,1];break;case 255:k=[this.readU8()<<8|this.readU8(),this.readU8()<<8|this.readU8()]}k&&(f=k[0]/k[1])}this.readBool()&&t(1);this.readBool()&&(t(4),this.readBool()&&
t(24));this.readBool()&&(g(),g());this.readBool()&&(y=this.readU32(),k=this.readU32(),z=this.readBool(),y=k/(2*y))}return{width:Math.ceil((16*(n+1)-2*h-2*w)*f),height:(2-aa)*(r+1)*16-(aa?2:4)*(b+L),configVer:m,profileIdc:E,chromaFormatIdc:I,frameCropLeftOffset:h,frameCropRightOffset:w,frameCropTopOffset:b,frameCropBottomOffset:L,fps:y,fixedFrameRate:z}};this.readSliceType=function(){this.readU8();this.readUEG();return this.readUEG()}}function mb(d,l,t,u){this.pixels=d;this.width=l;this.height=t;this.key=
u}function nb(){this.flags=this.bottom=this.right=this.top=this.left=0;this.read=function(d){this.left=d.getLittleEndian32();this.top=d.getLittleEndian32();this.right=d.getLittleEndian32();this.bottom=d.getLittleEndian32();this.flags=d.getLittleEndian32()};this.toString=function(){return"left: "+this.left+" top: "+this.top+" right: "+this.right+" bottom: "+this.bottom+" flags: "+this.flags}}function Fa(d,l){Ga||(Ga=document.createElement("video"),ja.setDrawable(Ga),pa=new Q(Ga,sa),pa.onsps=function(F){F.fps&&
q.setFPS(F.fps)},pa.onerror=function(F){svGlobal.logger.info("Decoding error",F);q.reconnect(ja.width,ja.height,!0)},pa.onplayerror=function(F){"AbortError"!=F.name&&q.showMessage({msg:"Please click Yes to continue.<br>"+F,cbYes:function(){pa.play(!0);this.destroy()}})},q.player=pa);var t=d.getPosition(),u=d.getLittleEndian32();d.skipPosition(10*u);return d.getBytes(l-(d.getPosition()-t))}function $a(d,l,t){t=d.getLittleEndian32();var u=t>>>30;t&=1073741823;switch(u){case 0:var F=Fa(d,t);Fa(d,l-t-
4);break;case 1:F=Fa(d,t);break;case 2:l=d.getEnd()-d.getPosition();Fa(d,l);break;default:throw Error("Invalid LC: "+u);}if(F)sa.onvideoframe(F)}Q.isSupported="MediaSource"in window&&MediaSource.isTypeSupported('video/mp4; codecs="avc1.42E01E, mp4a.40.2"');var lb={searchStartCode:function(d,l){for(var t=l[0]+2,u=d.length,F;t<u;)if(F=d[t],1==F){if(0==d[t-1]&&0==d[t-2]){l[1]=0==d[t-3]?4:3;l[0]=t-l[1]+1;return}t+=3}else 0==F?t++:t+=3;l[0]=-1}},La=new function(){function d(f,n,y,z,m){this.len=f;this.code=
n;this.valueBits=y;this.type=z;this.vbase=m}function l(f){var n=25E5-g,y=f.length;if(n>=y)F.set(f,g),g=n>y?g+y:0;else if(25E5>=y)F.set(f.subarray(0,n),g),F.set(f.subarray(n),0),g=y-n;else{n=(y-n)%25E5;var z=y-n,m=f.subarray(z);f=f.subarray(y-25E5,z);F.set(f,25E5-f.length);F.set(m,0);g=n}}function t(f){for(;h<f;)v<<=8,w<L?v+=b[w++]:console.log("--- end"),h+=8;D-=f;h-=f;f=v>>h;v&=(1<<h)-1;return f}var u=[new d(1,0,8,0,0),new d(5,17,5,1,0),new d(5,18,7,1,32),new d(5,19,9,1,160),new d(5,20,10,1,672),
new d(5,21,12,1,1696),new d(5,24,0,0,0),new d(5,25,0,0,1),new d(6,44,14,1,5792),new d(6,45,15,1,22176),new d(6,52,0,0,2),new d(6,53,0,0,3),new d(6,54,0,0,255),new d(7,92,18,1,54944),new d(7,93,20,1,317088),new d(7,110,0,0,4),new d(7,111,0,0,5),new d(7,112,0,0,6),new d(7,113,0,0,7),new d(7,114,0,0,8),new d(7,115,0,0,9),new d(7,116,0,0,10),new d(7,117,0,0,11),new d(7,118,0,0,58),new d(7,119,0,0,59),new d(7,120,0,0,60),new d(7,121,0,0,61),new d(7,122,0,0,62),new d(7,123,0,0,63),new d(7,124,0,0,64),new d(7,
125,0,0,128),new d(8,188,20,1,1365664),new d(8,189,21,1,2414240),new d(8,252,0,0,12),new d(8,253,0,0,56),new d(8,254,0,0,57),new d(8,255,0,0,102),new d(9,380,22,1,4511392),new d(9,381,23,1,8705696),new d(9,382,24,1,17094304)],F=new Uint8Array(25E5),g=0,O=new Uint8Array(65536),H=0,D=0,v=0,h=0,w=0,b=null,L=0;this.toPDU=function(){var f=new Uint8Array(2500008);f[0]=29;f[2]=1;f[3]=10;f[4]=g;f[5]=g>>8;f[6]=g>>16;f[7]=g>>24;f.set(F,8);return f};this.fromStream=function(f){g=f.getLittleEndian32();F.set(f.getSubarray(25E5))};
this.decompress=function(f,n){if(n){b=f;L=b.length-1;D=8*L-b[L];for(H=w=h=v=0;0<D;)for(var y=n=0,z=0;z<u.length;z++){for(f=u[z];n<f.len;)y=(y<<1)+t(1),n++;0>y&&console.log("xxx inPrefix");if(y==f.code){if(0==f.type)f=f.vbase+t(f.valueBits),(0>f||255<f)&&console.log("xxx do c"),f&=255,F[g]=f,25E5==++g&&(g=0),O[H++]=f;else if(n=t(f.valueBits),n=f.vbase+n,0>n&&console.log("xxx distance"),0!=n){if(0==t(1))f=3;else{f=4;for(y=2;1==t(1);)f*=2,y++;f+=t(y)}n=25E5-n+g;n%=25E5;y=n+f;if(Math.abs(g-n)>=f&&25E5>
y&&25E5>g+f)n=F.subarray(n,y),F.set(n,g),g+=f,O.set(n,H),H+=f;else for(;0<f;)y=F[n],25E5==++n&&(n=0),F[g]=y,25E5==++g&&(g=0),O[H++]=y,f--}else f=t(15),D-=h,v=h=0,n=b.subarray(w,w+f),l(n),O.set(n,H),w+=f,H+=f,D-=8*f;break}}65536<H&&console.error("xx outputIndex:"+H);return O.subarray(0,H)}l(f);return f}},ob=new function(){this.process=function(d){var l=d.getByte();if(224==l){var t=0!=(d.getByte()&32);var u=d.getPosition(),F=d.getEnd();l=La.decompress(d.getData().subarray(u,F),t);d.setPosition(F)}else{225!=
l&&console.log("Invalid descriptor:"+l);F=d.getLittleEndian16();var g=d.getLittleEndian32();l=new Uint8Array(g);for(var O=0,H,D=0;D<F;D++)H=d.getLittleEndian32(),t=0!=(d.getByte()&32),H--,u=d.getPosition(),t=La.decompress(d.getData().subarray(u,u+H),t),l.set(t,O),O+=t.length,d.skipPosition(H);O!=g&&console.error("wrong size, actual:"+O+" expected:"+g)}return new RdpBuffer(l,0,l.length)}},Ga=null,Ha=null,ja=q.getDesktop(),pb=new rdpcodecs.RemoteFX(!1),pa=null,sa=new q.DynamicChannel;sa.name="Microsoft::Windows::RDS::Graphics";
sa.process=function(d){for(var l=ob.process(d);l.has(8);){var t=l.getLittleEndian16();l.getLittleEndian16();var u=l.getLittleEndian32(),F=l.getPosition()+u-8;switch(t){case 1:var g=l,O=g.getLittleEndian16(),H=g.getLittleEndian16();g.getByte();var D=g.getLittleEndian16(),v=g.getLittleEndian16(),h=g.getLittleEndian16(),w=g.getLittleEndian16(),b=h-D,L=w-v,f=g.getLittleEndian32(),n=g.getPosition()+f,y=va[O]||ja;switch(H){case 0:var z=rdpcodecs.bitmap.byte2int(g.getData(),f,g.getPosition());y.setRGBs(D,
v,b,L,z,0,b);break;case 3:for(var m=pb.decode(g,f),E=m.getRects(),I=m.getTiles(),r=m.getTileSize(),aa=m.getRectSize(),k=0;k<r;k++){var B=I[k];if(aa)for(var V=B.x+64,S=B.y+64,ea=0;ea<aa;ea++){var la=E[ea],ha=la.x+la.width,G=la.y+la.height;V<=ha?S<=G?y.setRGBs(B.x+D,B.y+v,64,64,B.data,0,64):y.setRGBs(B.x+D,B.y+v,64,G-B.y,B.data,0,64):S<=G?y.setRGBs(B.x+D,B.y+v,ha-B.x,64,B.data,0,64):y.setRGBs(B.x+D,B.y+v,ha-B.x,G-B.y,B.data,0,64)}else y.setRGBs(B.x,B.y,64,64,B.data,0,4)}break;case 8:Ha||(Ha=new C);
Ha.decode(g,b,L,y.getData(),D,v,y.width);break;case 10:svGlobal.logger.info("...PLANAR");break;case 11:var T=Fa(g,f);sa.onvideoframe(T);break;case 12:svGlobal.logger.info("...ALPHA");break;case 14:$a(g,f,!1);break;case 15:$a(g,f,!0);break;default:svGlobal.logger.warn("Invalid codec:"+H)}g.setPosition(n);y.postPaint(D,v,b,L);break;case 2:svGlobal.logger.info("RDPGFX_WIRE_TO_SURFACE_PDU_2");break;case 3:svGlobal.logger.info("RDPGFX_CMDID_DELETEENCODINGCONTEXT");break;case 4:for(var P=l,K=P.getLittleEndian16(),
fa=-16777216|P.getByte()<<16|P.getByte()<<8|P.getByte()|P.getByte()<<24,ka=P.getLittleEndian16(),Y=va[K]||ja,ca=0;ca<ka;ca++){var qa=P.getLittleEndian16(),oa=P.getLittleEndian16(),ra=P.getLittleEndian16()-qa,ta=P.getLittleEndian16()-oa;Y.fillRect(qa,oa,ra,ta,fa);Y.postPaint(qa,oa,ra,ta)}break;case 5:for(var na=l,za=na.getLittleEndian16(),Aa=na.getLittleEndian16(),ua=na.getLittleEndian16(),wa=na.getLittleEndian16(),a=na.getLittleEndian16()-ua,c=na.getLittleEndian16()-wa,e=na.getLittleEndian16(),p=
va[za]||ja,x=va[Aa]||ja,J=za==Aa?null:p.getRGBs(ua,wa,a,c),M=0;M<e;M++){var U=na.getLittleEndian16(),W=na.getLittleEndian16();J?x.setRGBs(U,W,a,c,J,0,a):p.moveArea(ua,wa,a,c,U-ua,W-wa)}break;case 6:var N=l,Z=N.getLittleEndian16(),X=N.getLittleEndian32().toString(16),ba=N.getLittleEndian32();0<ba&&(X=ba.toString(16)+X);var da=N.getLittleEndian16(),ia=N.getLittleEndian16(),ma=N.getLittleEndian16(),Ka=N.getLittleEndian16()-ia,xa=N.getLittleEndian16()-ma,Ea=(va[Z]||ja).getRGBs(ia,ma,Ka,xa);Va[da]=new mb(Ea,
Ka,xa,X);break;case 7:for(var ya=l,qb=ya.getLittleEndian16(),rb=ya.getLittleEndian16(),sb=ya.getLittleEndian16(),Ma=Va[qb],tb=va[rb]||ja,ab=0;ab<sb;ab++){var ub=ya.getLittleEndian16(),vb=ya.getLittleEndian16();tb.setRGBs(ub,vb,Ma.width,Ma.height,Ma.pixels,0,Ma.width)}break;case 8:var wb=l.getLittleEndian16();Va[wb]=null;break;case 9:var Na=l,Wa=Na.getLittleEndian16(),bb=Na.getLittleEndian16(),cb=Na.getLittleEndian16(),Oa=ja;Oa.id=Wa;Oa.pixelFormat=Na.getByte();va[Wa]=Oa;q.setResolution(bb,cb);svGlobal.logger.info("create surface id:"+
Wa+" w:"+bb+" h:"+cb+" pixelFmt:"+Oa.pixelFormat);break;case 10:var db=l.getLittleEndian16();va[db]=null;svGlobal.logger.info("delete surface id:"+db);break;case 11:var eb=l;eb.getLittleEndian32();eb.getLittleEndian32();break;case 12:var xb=l.getLittleEndian32();if(0==Xa){var fb=new Uint8Array(20),Ba=new RdpBuffer(fb);Ba.setLittleEndian16(13);Ba.setLittleEndian16(0);Ba.setLittleEndian32(20);Ba.setLittleEndian32(4294967295);Ba.setLittleEndian32(xb);Xa++;Ba.setLittleEndian32(Xa);0==q.mode&&sa.send(fb)}break;
case 14:var Pa=l,gb=Pa.getLittleEndian32(),hb=Pa.getLittleEndian32(),ib=Pa.getLittleEndian32();svGlobal.logger.info("reset graphic, w:"+gb+" h:"+hb+" monitors:"+ib);ja&&ja.resize(gb,hb);pa&&pa.reset();for(var Ya=0;Ya<ib;Ya++){var jb=new nb;jb.read(Pa);svGlobal.logger.info("MonitorDef "+Ya+": "+jb.toString())}break;case 15:var Qa=l;Ra=Qa.getLittleEndian16();Qa.skipPosition(2);Sa=Qa.getLittleEndian32();Ta=Qa.getLittleEndian32();svGlobal.logger.info("surface output map: id:"+Ra+" x:"+Sa+" y:"+Ta);break;
case 17:svGlobal.logger.info("TODO: DPGFX_CACHE_IMPORT_REPLY_PDU");break;case 19:var Za=l,kb=Za.getLittleEndian32(),yb=Za.getLittleEndian32(),Ia=Za.getLittleEndian32(),Ua=!1;switch(kb){case 524292:Ua=!1;0==(Ia&1)&&(Ha=new C);break;case 524549:(Ua=0!=(Ia&16))||0!=(Ia&1)||(Ha=new C);break;default:Ua=0==(Ia&32)}svGlobal.logger.info("Gfx Cap, Ver:"+kb.toString(16)+" len:"+yb+" flags:"+Ia+" h264:"+Ua);break;case 21:svGlobal.logger.info("mapSurfaceToWin");break;case 22:break;case 23:var Ca=l;Ra=Ca.getLittleEndian16();
Ca.skipPosition(2);Sa=Ca.getLittleEndian32();Ta=Ca.getLittleEndian32();var zb=Ca.getLittleEndian32(),Ab=Ca.getLittleEndian32();svGlobal.logger.info("mapSurfaceToScaledOutput, outputSurfaceId:"+Ra+" outX:"+Sa+" outY:"+Ta+" targetW:"+zb+" targetH:"+Ab);break;case 24:svGlobal.logger.info("mapSurfaceToScaledWin");break;default:svGlobal.logger.warn("xxx gfx:"+t);return}l.setPosition(F)}};sa.onopen=function(){svGlobal.logger.info("GFX Open, remotefx:"+A);var d=A?2:8,l=120*d,t=new Uint8Array(l),u=new RdpBuffer(t);
u.setLittleEndian16(18);u.setLittleEndian16(0);u.setLittleEndian32(l);u.setLittleEndian16(d);u.setLittleEndian32(524292);u.setLittleEndian32(4);u.setLittleEndian32(1);u.setLittleEndian32(524549);u.setLittleEndian32(4);u.setLittleEndian32(19);A||(u.setLittleEndian32(655362),u.setLittleEndian32(4),u.setLittleEndian32(0),u.setLittleEndian32(655872),u.setLittleEndian32(4),u.setLittleEndian32(0),u.setLittleEndian32(656129),u.setLittleEndian32(4),u.setLittleEndian32(0),u.setLittleEndian32(656384),u.setLittleEndian32(4),
u.setLittleEndian32(0),u.setLittleEndian32(656642),u.setLittleEndian32(4),u.setLittleEndian32(0),u.setLittleEndian32(656896),u.setLittleEndian32(4),u.setLittleEndian32(0));u.markEnd();0==q.mode&&sa.send(t)};sa.onclose=function(){ja.setDrawable(null);pa&&(pa.close(),pa=null);Ga=q.player=null};var va={},Xa=0,Ra=0,Sa=0,Ta=0,Va=[];ja.onGetGfxHistory=function(d,l){var t=La.toPDU();d(t);l(t.buffer);svGlobal.logger.info("Get GFX Histroy")};ja.onSetGfxHistory=function(d,l){svGlobal.logger.info("Set GFX Histroy");
10==d?La.fromStream(l):svGlobal.logger.error("Invalid GFX histroy type: "+d)};return sa};
