var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,f){if(a==Array.prototype||a==Object.prototype)return a;a[c]=f.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var f=a[c];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var f=$jscomp.propertyToPolyfillSymbol[c];if(null==f)return a[c];f=a[f];return void 0!==f?f:a[c]};$jscomp.polyfill=function(a,c,f,h){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,f,h):$jscomp.polyfillUnisolated(a,c,f,h))};
$jscomp.polyfillUnisolated=function(a,c,f,h){f=$jscomp.global;a=a.split(".");for(h=0;h<a.length-1;h++){var e=a[h];if(!(e in f))return;f=f[e]}a=a[a.length-1];h=f[a];c=c(h);c!=h&&null!=c&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,f,h){var e=a.split(".");a=1===e.length;h=e[0];h=!a&&h in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var t=0;t<e.length-1;t++){var d=e[t];if(!(d in h))return;h=h[d]}e=e[e.length-1];f=$jscomp.IS_SYMBOL_NATIVE&&"es6"===f?h[e]:null;c=c(f);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:c}):c!==f&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(h,e,{configurable:!0,writable:!0,value:c})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},c={};try{return c.__proto__=a,c.a}catch(f){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,c){this.nextAddress=c;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,c){a=$jscomp.makeIterator(a);var f=a.next();$jscomp.generator.ensureIteratorResultIsObject_(f);if(f.done)this.yieldResult=f.value,this.nextAddress=c;else return this.yieldAllIterator_=a,this.yield(f.value,c)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,c){this.catchAddress_=a;void 0!=c&&(this.finallyAddress_=c)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,c){this.nextAddress=a;this.catchAddress_=c||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,c,f){f?this.finallyContexts_[f]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=c||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,c){c=this.finallyContexts_.splice(c||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var c in a)this.properties_.push(c);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var c=this.context_.yieldAllIterator_;if(c)return this.yieldAllStep_("return"in c?c["return"]:function(f){return{value:f,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,c,f){try{var h=a.call(this.context_.yieldAllIterator_,c);$jscomp.generator.ensureIteratorResultIsObject_(h);if(!h.done)return this.context_.stop_(),h;var e=h.value}catch(t){return this.context_.yieldAllIterator_=null,this.context_.throw_(t),this.nextStep_()}this.context_.yieldAllIterator_=null;f.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(c){this.context_.yieldResult=void 0,this.context_.throw_(c)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(c){return a.next_(c)};this.throw=function(c){return a.throw_(c)};this.return=function(c){return a.return_(c)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,c){c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(c));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function c(h){return a.next(h)}function f(h){return a.throw(h)}return new Promise(function(h,e){function t(d){d.done?h(d.value):Promise.resolve(d.value).then(c,f).then(t,e)}t(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var c=function(e,t){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:t})};c.prototype.toString=function(){return this.$jscomp$symbol$id_};var f=0,h=function(e){if(this instanceof h)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+f++,e)};return h},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var c="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),f=0;f<c.length;f++){var h=$jscomp.global[c[f]];"function"===typeof h&&"function"!=typeof h.prototype[a]&&$jscomp.defineProperty(h.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function c(){this.batch_=null}function f(d){return d instanceof e?d:new e(function(g,m){g(d)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;c.prototype.asyncExecute=function(d){if(null==this.batch_){this.batch_=[];var g=this;this.asyncExecuteFunction(function(){g.executeBatch_()})}this.batch_.push(d)};
var h=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(d){h(d,0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var g=0;g<d.length;++g){var m=d[g];d[g]=null;try{m()}catch(r){this.asyncThrow_(r)}}}this.batch_=null};c.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var e=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var g=this.createResolveAndReject_();
try{d(g.resolve,g.reject)}catch(m){g.reject(m)}};e.prototype.createResolveAndReject_=function(){function d(r){return function(b){m||(m=!0,r.call(g,b))}}var g=this,m=!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};e.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof e)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var g=null!=d;break a;case "function":g=!0;break a;default:g=!1}g?this.resolveToNonPromiseObj_(d):
this.fulfill_(d)}};e.prototype.resolveToNonPromiseObj_=function(d){var g=void 0;try{g=d.then}catch(m){this.reject_(m);return}"function"==typeof g?this.settleSameAsThenable_(g,d):this.fulfill_(d)};e.prototype.reject_=function(d){this.settle_(2,d)};e.prototype.fulfill_=function(d){this.settle_(1,d)};e.prototype.settle_=function(d,g){if(0!=this.state_)throw Error("Cannot settle("+d+", "+g+"): Promise already settled in state"+this.state_);this.state_=d;this.result_=g;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};e.prototype.scheduleUnhandledRejectionCheck_=function(){var d=this;h(function(){if(d.notifyUnhandledRejection_()){var g=$jscomp.global.console;"undefined"!==typeof g&&g.error(d.result_)}},1)};e.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var d=$jscomp.global.CustomEvent,g=$jscomp.global.Event,m=$jscomp.global.dispatchEvent;if("undefined"===typeof m)return!0;"function"===typeof d?d=new d("unhandledrejection",{cancelable:!0}):
"function"===typeof g?d=new g("unhandledrejection",{cancelable:!0}):(d=$jscomp.global.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.result_;return m(d)};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=0;d<this.onSettledCallbacks_.length;++d)t.asyncExecute(this.onSettledCallbacks_[d]);this.onSettledCallbacks_=null}};var t=new c;e.prototype.settleSameAsPromise_=function(d){var g=this.createResolveAndReject_();
d.callWhenSettled_(g.resolve,g.reject)};e.prototype.settleSameAsThenable_=function(d,g){var m=this.createResolveAndReject_();try{d.call(g,m.resolve,m.reject)}catch(r){m.reject(r)}};e.prototype.then=function(d,g){function m(n,k){return"function"==typeof n?function(q){try{r(n(q))}catch(p){b(p)}}:k}var r,b,l=new e(function(n,k){r=n;b=k});this.callWhenSettled_(m(d,r),m(g,b));return l};e.prototype.catch=function(d){return this.then(void 0,d)};e.prototype.callWhenSettled_=function(d,g){function m(){switch(r.state_){case 1:d(r.result_);
break;case 2:g(r.result_);break;default:throw Error("Unexpected state: "+r.state_);}}var r=this;null==this.onSettledCallbacks_?t.asyncExecute(m):this.onSettledCallbacks_.push(m);this.isRejectionHandled_=!0};e.resolve=f;e.reject=function(d){return new e(function(g,m){m(d)})};e.race=function(d){return new e(function(g,m){for(var r=$jscomp.makeIterator(d),b=r.next();!b.done;b=r.next())f(b.value).callWhenSettled_(g,m)})};e.all=function(d){var g=$jscomp.makeIterator(d),m=g.next();return m.done?f([]):new e(function(r,
b){function l(q){return function(p){n[q]=p;k--;0==k&&r(n)}}var n=[],k=0;do n.push(void 0),k++,f(m.value).callWhenSettled_(l(n.length-1),b),m=g.next();while(!m.done)})};return e},"es6","es3");$jscomp.findInternal=function(a,c,f){a instanceof String&&(a=String(a));for(var h=a.length,e=0;e<h;e++){var t=a[e];if(c.call(f,t,e,a))return{i:e,v:t}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(c,f){return $jscomp.findInternal(this,c,f).v}},"es6","es3");
svGlobal.DCVC_EXTENSION=svGlobal.DCVC_EXTENSION||{};
svGlobal.DCVC_EXTENSION.DRIVE=function(a){function c(b){for(var l=g.length,n=0;n<l;n++)if(g[n].deviceId==b)return g[n]}function f(b){var l=new hi5.DataBuffer(new Uint8Array(17+(b.data?b.data.length:0)));l.setByte(0);l.setLittleEndian32(b.type);l.setAsciiString(b.dosName,8);b.data&&(l.setLittleEndian32(b.data.length),l.setBytes(b.data));l.markEnd();d.send(l)}function h(b){b.getByte();var l=b.getLittleEndian32(),n=b.getLittleEndian32(),k=b.getUnicodeString(n);g.find(function(q){return(q.printName||
q.dosName)==k}).deviceId=l;c(l).operation.attach(l,k)}function e(b,l,n,k,q){this.type=4;this.dosName="PRN2";this.operation=q;this.driverName=b;this.printName=l;this.deviceId=0;n=n?2:0;k&&(n|=16);k=b?2*(b.length+1):0;q=2*(l.length+1);var p=new hi5.DataBuffer(new Uint8Array(24+k+q));p.setLittleEndian32(n);p.skipPosition(8);p.setLittleEndian32(k);p.setLittleEndian32(q);p.skipPosition(4);b&&p.setUnicodeString(b+"\x00");p.setUnicodeString(l+"\x00");this.data=p.getData()}function t(b){var l=0,n=0;this.attach=
function(k,q){var p=2*q.length,u=new hi5.DataBuffer(new Uint8Array(10+p));u.setByte(6);u.setByte(2);u.setLittleEndian32(k);u.setLittleEndian32(p);u.setUnicodeString(q);u.markEnd();l=k;b.onagentmessage(u.getData())};this.create=function(k,q,p,u,w,x){k=new hi5.DataBuffer(new Uint8Array(6));k.setByte(6);k.setByte(3);k.setLittleEndian32(l);k.markEnd();b.onagentmessage(k.getData());r++;n=r;return[0,n]};this.close=function(k){k=new hi5.DataBuffer(new Uint8Array(6));k.setByte(6);k.setByte(5);k.setLittleEndian32(l);
k.markEnd();(n=r)&&r--;b.onagentmessage(k.getData());return 0};this.write=function(k,q,p,u){k=new hi5.DataBuffer(new Uint8Array(q+6));k.setByte(6);k.setByte(4);k.setLittleEndian32(l);k.setBytes(u);k.markEnd();b.onagentmessage(k.getData());return 0}}var d=new a;d.name="DRIVESTB";var g=[],m=!1,r=99999;d.onopen=function(){if(!m&&(m=!0,0<g.length))for(var b=0,l=g.length;b<l;b++)f(g[b])};d.process=function(b){switch(b.getByte()){case 1:h(b);break;case 2:var l=b.getLittleEndian32(),n=b.getLittleEndian32(),
k=b.getLittleEndian32(),q=b.getLittleEndian32();b.getLittleEndian32();var p=c(l).operation;switch(q){case 0:q=b.getBigEndian32();b.skipPosition(8);n=b.getLittleEndian32();var u=b.getLittleEndian32(),w=b.getLittleEndian32(),x=b.getLittleEndian32(),v=b.getLittleEndian32(),y="";0<v&&256>v/2&&(y=b.getUnicodeString(v));p=p.create(q,n,u,w,x,y);b=new hi5.DataBuffer(new Uint8Array(22));b.setByte(3);b.setLittleEndian16(17522);b.setLittleEndian16(18755);b.setLittleEndian32(l);b.setLittleEndian32(k);b.setLittleEndian32(p[0]);
b.setLittleEndian32(p[1]);b.setByte(0);b.markEnd();d.send(b);break;case 2:b.skipPosition(32);p=p.close(n);b=new hi5.DataBuffer(new Uint8Array(22));b.setByte(3);b.setLittleEndian16(17522);b.setLittleEndian16(18755);b.setLittleEndian32(l);b.setLittleEndian32(k);b.setLittleEndian32(p);b.skipPosition(5);b.markEnd();d.send(b);break;case 3:b.getLittleEndian32();u=b.getLittleEndian64();b.skipPosition(20);p.read(n,dataLen,u,reading,0);break;case 4:q=b.getLittleEndian32();u=b.getLittleEndian64();b.skipPosition(20);
p=p.write(n,q,u,b.getBytes(q));b=new hi5.DataBuffer(new Uint8Array(22));b.setByte(3);b.setLittleEndian16(17522);b.setLittleEndian16(18755);b.setLittleEndian32(l);b.setLittleEndian32(k);b.setLittleEndian32(p);b.setLittleEndian32(q);b.setByte(0);b.markEnd();d.send(b);break;case 5:break;case 6:break;case 10:break;case 12:break;case 14:break;case 17:break;default:svGlobal.logger.warn("Inlvaid IORequest: "+q)}}};d.attachDevice=function(b){g.push(b);m&&f(b)};d.attachPrinter=function(b,l){l=new t(l);b=new e(b.driver,
b.name,b.isDefault,b.isXPS,l);d.attachDevice(b)};return d};
