var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,k,r){if(f==Array.prototype||f==Object.prototype)return f;f[k]=r.value;return f};
$jscomp.getGlobal=function(f){f=["object"==typeof globalThis&&globalThis,f,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var k=0;k<f.length;++k){var r=f[k];if(r&&r.Math==Math)return r}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(f,k){var r=$jscomp.propertyToPolyfillSymbol[k];if(null==r)return f[k];r=f[r];return void 0!==r?r:f[k]};$jscomp.polyfill=function(f,k,r,A){k&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(f,k,r,A):$jscomp.polyfillUnisolated(f,k,r,A))};
$jscomp.polyfillUnisolated=function(f,k,r,A){r=$jscomp.global;f=f.split(".");for(A=0;A<f.length-1;A++){var v=f[A];if(!(v in r))return;r=r[v]}f=f[f.length-1];A=r[f];k=k(A);k!=A&&null!=k&&$jscomp.defineProperty(r,f,{configurable:!0,writable:!0,value:k})};
$jscomp.polyfillIsolated=function(f,k,r,A){var v=f.split(".");f=1===v.length;A=v[0];A=!f&&A in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var K=0;K<v.length-1;K++){var p=v[K];if(!(p in A))return;A=A[p]}v=v[v.length-1];r=$jscomp.IS_SYMBOL_NATIVE&&"es6"===r?A[v]:null;k=k(r);null!=k&&(f?$jscomp.defineProperty($jscomp.polyfills,v,{configurable:!0,writable:!0,value:k}):k!==r&&($jscomp.propertyToPolyfillSymbol[v]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(v):$jscomp.POLYFILL_PREFIX+v,v=
$jscomp.propertyToPolyfillSymbol[v],$jscomp.defineProperty(A,v,{configurable:!0,writable:!0,value:k})))};$jscomp.underscoreProtoCanBeSet=function(){var f={a:!0},k={};try{return k.__proto__=f,k.a}catch(r){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(f,k){f.__proto__=k;if(f.__proto__!==k)throw new TypeError(f+" is not extensible");return f}:null;
$jscomp.arrayIteratorImpl=function(f){var k=0;return function(){return k<f.length?{done:!1,value:f[k++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};$jscomp.makeIterator=function(f){var k="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];return k?k.call(f):$jscomp.arrayIterator(f)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(f){if(!(f instanceof Object))throw new TypeError("Iterator result "+f+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(f){this.yieldResult=f};
$jscomp.generator.Context.prototype.throw_=function(f){this.abruptCompletion_={exception:f,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(f){this.abruptCompletion_={return:f};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(f){this.abruptCompletion_={jumpTo:f};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(f,k){this.nextAddress=k;return{value:f}};
$jscomp.generator.Context.prototype.yieldAll=function(f,k){f=$jscomp.makeIterator(f);var r=f.next();$jscomp.generator.ensureIteratorResultIsObject_(r);if(r.done)this.yieldResult=r.value,this.nextAddress=k;else return this.yieldAllIterator_=f,this.yield(r.value,k)};$jscomp.generator.Context.prototype.jumpTo=function(f){this.nextAddress=f};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(f,k){this.catchAddress_=f;void 0!=k&&(this.finallyAddress_=k)};$jscomp.generator.Context.prototype.setFinallyBlock=function(f){this.catchAddress_=0;this.finallyAddress_=f||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(f,k){this.nextAddress=f;this.catchAddress_=k||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(f){this.catchAddress_=f||0;f=this.abruptCompletion_.exception;this.abruptCompletion_=null;return f};$jscomp.generator.Context.prototype.enterFinallyBlock=function(f,k,r){r?this.finallyContexts_[r]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=f||0;this.finallyAddress_=k||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(f,k){k=this.finallyContexts_.splice(k||0)[0];if(k=this.abruptCompletion_=this.abruptCompletion_||k){if(k.isException)return this.jumpToErrorHandler_();void 0!=k.jumpTo&&this.finallyAddress_<k.jumpTo?(this.nextAddress=k.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=f};$jscomp.generator.Context.prototype.forIn=function(f){return new $jscomp.generator.Context.PropertyIterator(f)};
$jscomp.generator.Context.PropertyIterator=function(f){this.object_=f;this.properties_=[];for(var k in f)this.properties_.push(k);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var f=this.properties_.pop();if(f in this.object_)return f}return null};$jscomp.generator.Engine_=function(f){this.context_=new $jscomp.generator.Context;this.program_=f};
$jscomp.generator.Engine_.prototype.next_=function(f){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,f,this.context_.next_);this.context_.next_(f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(f){this.context_.start_();var k=this.context_.yieldAllIterator_;if(k)return this.yieldAllStep_("return"in k?k["return"]:function(r){return{value:r,done:!0}},f,this.context_.return);this.context_.return(f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(f){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],f,this.context_.next_);this.context_.throw_(f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(f,k,r){try{var A=f.call(this.context_.yieldAllIterator_,k);$jscomp.generator.ensureIteratorResultIsObject_(A);if(!A.done)return this.context_.stop_(),A;var v=A.value}catch(K){return this.context_.yieldAllIterator_=null,this.context_.throw_(K),this.nextStep_()}this.context_.yieldAllIterator_=null;r.call(this.context_,v);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var f=this.program_(this.context_);if(f)return this.context_.stop_(),{value:f.value,done:!1}}catch(k){this.context_.yieldResult=void 0,this.context_.throw_(k)}this.context_.stop_();if(this.context_.abruptCompletion_){f=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(f.isException)throw f.exception;return{value:f.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(f){this.next=function(k){return f.next_(k)};this.throw=function(k){return f.throw_(k)};this.return=function(k){return f.return_(k)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(f,k){k=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(k));$jscomp.setPrototypeOf&&f.prototype&&$jscomp.setPrototypeOf(k,f.prototype);return k};
$jscomp.asyncExecutePromiseGenerator=function(f){function k(A){return f.next(A)}function r(A){return f.throw(A)}return new Promise(function(A,v){function K(p){p.done?A(p.value):Promise.resolve(p.value).then(k,r).then(K,v)}K(f.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(f){return $jscomp.asyncExecutePromiseGenerator(f())};$jscomp.asyncExecutePromiseGeneratorProgram=function(f){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(f)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(f){if(f)return f;var k=function(v,K){this.$jscomp$symbol$id_=v;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:K})};k.prototype.toString=function(){return this.$jscomp$symbol$id_};var r=0,A=function(v){if(this instanceof A)throw new TypeError("Symbol is not a constructor");return new k("jscomp_symbol_"+(v||"")+"_"+r++,v)};return A},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(f){if(f)return f;f=Symbol("Symbol.iterator");for(var k="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),r=0;r<k.length;r++){var A=$jscomp.global[k[r]];"function"===typeof A&&"function"!=typeof A.prototype[f]&&$jscomp.defineProperty(A.prototype,f,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return f},"es6",
"es3");$jscomp.iteratorPrototype=function(f){f={next:f};f[Symbol.iterator]=function(){return this};return f};
$jscomp.polyfill("Promise",function(f){function k(){this.batch_=null}function r(p){return p instanceof v?p:new v(function(y,F){y(p)})}if(f&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return f;k.prototype.asyncExecute=function(p){if(null==this.batch_){this.batch_=[];var y=this;this.asyncExecuteFunction(function(){y.executeBatch_()})}this.batch_.push(p)};
var A=$jscomp.global.setTimeout;k.prototype.asyncExecuteFunction=function(p){A(p,0)};k.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var p=this.batch_;this.batch_=[];for(var y=0;y<p.length;++y){var F=p[y];p[y]=null;try{F()}catch(L){this.asyncThrow_(L)}}}this.batch_=null};k.prototype.asyncThrow_=function(p){this.asyncExecuteFunction(function(){throw p;})};var v=function(p){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var y=this.createResolveAndReject_();
try{p(y.resolve,y.reject)}catch(F){y.reject(F)}};v.prototype.createResolveAndReject_=function(){function p(L){return function(P){F||(F=!0,L.call(y,P))}}var y=this,F=!1;return{resolve:p(this.resolveTo_),reject:p(this.reject_)}};v.prototype.resolveTo_=function(p){if(p===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(p instanceof v)this.settleSameAsPromise_(p);else{a:switch(typeof p){case "object":var y=null!=p;break a;case "function":y=!0;break a;default:y=!1}y?this.resolveToNonPromiseObj_(p):
this.fulfill_(p)}};v.prototype.resolveToNonPromiseObj_=function(p){var y=void 0;try{y=p.then}catch(F){this.reject_(F);return}"function"==typeof y?this.settleSameAsThenable_(y,p):this.fulfill_(p)};v.prototype.reject_=function(p){this.settle_(2,p)};v.prototype.fulfill_=function(p){this.settle_(1,p)};v.prototype.settle_=function(p,y){if(0!=this.state_)throw Error("Cannot settle("+p+", "+y+"): Promise already settled in state"+this.state_);this.state_=p;this.result_=y;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};v.prototype.scheduleUnhandledRejectionCheck_=function(){var p=this;A(function(){if(p.notifyUnhandledRejection_()){var y=$jscomp.global.console;"undefined"!==typeof y&&y.error(p.result_)}},1)};v.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var p=$jscomp.global.CustomEvent,y=$jscomp.global.Event,F=$jscomp.global.dispatchEvent;if("undefined"===typeof F)return!0;"function"===typeof p?p=new p("unhandledrejection",{cancelable:!0}):
"function"===typeof y?p=new y("unhandledrejection",{cancelable:!0}):(p=$jscomp.global.document.createEvent("CustomEvent"),p.initCustomEvent("unhandledrejection",!1,!0,p));p.promise=this;p.reason=this.result_;return F(p)};v.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var p=0;p<this.onSettledCallbacks_.length;++p)K.asyncExecute(this.onSettledCallbacks_[p]);this.onSettledCallbacks_=null}};var K=new k;v.prototype.settleSameAsPromise_=function(p){var y=this.createResolveAndReject_();
p.callWhenSettled_(y.resolve,y.reject)};v.prototype.settleSameAsThenable_=function(p,y){var F=this.createResolveAndReject_();try{p.call(y,F.resolve,F.reject)}catch(L){F.reject(L)}};v.prototype.then=function(p,y){function F(R,U){return"function"==typeof R?function(X){try{L(R(X))}catch(aa){P(aa)}}:U}var L,P,ba=new v(function(R,U){L=R;P=U});this.callWhenSettled_(F(p,L),F(y,P));return ba};v.prototype.catch=function(p){return this.then(void 0,p)};v.prototype.callWhenSettled_=function(p,y){function F(){switch(L.state_){case 1:p(L.result_);
break;case 2:y(L.result_);break;default:throw Error("Unexpected state: "+L.state_);}}var L=this;null==this.onSettledCallbacks_?K.asyncExecute(F):this.onSettledCallbacks_.push(F);this.isRejectionHandled_=!0};v.resolve=r;v.reject=function(p){return new v(function(y,F){F(p)})};v.race=function(p){return new v(function(y,F){for(var L=$jscomp.makeIterator(p),P=L.next();!P.done;P=L.next())r(P.value).callWhenSettled_(y,F)})};v.all=function(p){var y=$jscomp.makeIterator(p),F=y.next();return F.done?r([]):new v(function(L,
P){function ba(X){return function(aa){R[X]=aa;U--;0==U&&L(R)}}var R=[],U=0;do R.push(void 0),U++,r(F.value).callWhenSettled_(ba(R.length-1),P),F=y.next();while(!F.done)})};return v},"es6","es3");$jscomp.findInternal=function(f,k,r){f instanceof String&&(f=String(f));for(var A=f.length,v=0;v<A;v++){var K=f[v];if(k.call(r,K,v,f))return{i:v,v:K}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.findIndex",function(f){return f?f:function(k,r){return $jscomp.findInternal(this,k,r).i}},"es6","es3");
$jscomp.polyfill("Array.prototype.find",function(f){return f?f:function(k,r){return $jscomp.findInternal(this,k,r).v}},"es6","es3");$jscomp.polyfill("Object.is",function(f){return f?f:function(k,r){return k===r?0!==k||1/k===1/r:k!==k&&r!==r}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(f){return f?f:function(k,r){var A=this;A instanceof String&&(A=String(A));var v=A.length;r=r||0;for(0>r&&(r=Math.max(r+v,0));r<v;r++){var K=A[r];if(K===k||Object.is(K,k))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(f,k,r){if(null==f)throw new TypeError("The 'this' value for String.prototype."+r+" must not be null or undefined");if(k instanceof RegExp)throw new TypeError("First argument to String.prototype."+r+" must not be a regular expression");return f+""};$jscomp.polyfill("String.prototype.includes",function(f){return f?f:function(k,r){return-1!==$jscomp.checkStringArgs(this,k,"includes").indexOf(k,r||0)}},"es6","es3");svGlobal.DCVC_EXTENSION=svGlobal.DCVC_EXTENSION||{};
svGlobal.DCVC_EXTENSION.WEBUSB=function(f){function k(a,b,d,c,e,l,g,n){this.bLength=9;this.bDescriptorType=2;this.wTotalLength=a;this.bNumInterfaces=b;this.bConfigurationValue=d;this.iConfiguration=c;this.bmAttributes=e;this.maxPower=l;this.msInterfaces=g;this.configurationHandle=4294901760|n;this.serialize=function(){var h=new hi5.DataBuffer(new Uint8Array(this.wTotalLength));h.setByte(9);h.setByte(2);h.setLittleEndian16(this.wTotalLength);h.setByte(this.bNumInterfaces);h.setByte(this.bConfigurationValue);
h.setByte(this.iConfiguration);h.setByte(this.bmAttributes);h.setByte(this.maxPower);for(var q=0;q<this.bNumInterfaces;q++){var u=this.msInterfaces[q];h.setByte(9);h.setByte(4);h.setByte(u.bInterfaceNumber);h.setByte(u.bAlternateSetting);h.setByte(u.bNumEndpoints);h.setByte(u.bInterfaceClass);h.setByte(u.bInterfaceSubClass);h.setByte(u.bInterfaceProtocol);h.setByte(u.iInterface);for(var m=0;m<u.bNumEndpoints;m++){var w=u.msPipes[m];h.setByte(7);h.setByte(5);h.setByte(w.bEndpointAddress);h.setByte(w.bmAttributes);
h.setLittleEndian16(w.wMaxPacketSize);h.setByte(w.bInterval)}}return h.getData()};this.getInterfaceByInterfaceNumber=function(h){for(var q=0;q<this.bNumInterfaces;q++){var u=this.msInterfaces[q];if(u.bInterfaceNumber==h)return u}}}function r(a,b,d,c,e,l,g,n,h){this.bLength=9;this.bDescriptorType=4;this.bInterfaceNumber=a;this.bAlternateSetting=b;this.bNumEndpoints=d;this.bInterfaceClass=c;this.bInterfaceSubClass=e;this.bInterfaceProtocol=l;this.iInterface=g;this.numberOfPipesExpected=void 0;this.msPipes=
n;this.interfaceHandle=4294901760|h}function A(a,b,d,c,e){this.bLength=7;this.bDescriptorType=5;this.bEndpointAddress=a;this.bmAttributes=b;this.wMaxPacketSize=d;this.bInterval=c;this.pipeType=this.bmAttributes&3;this.pipeFlags=this.maximumTransferSize=void 0;this.pipeHandle=4294901760|e}function v(a,b){b=a.map(function(d){return d.bInterfaceNumber}).indexOf(b);return 0<=b?a[b]:null}function K(a,b){this.device=a;this.port=b;this.msVendorCode=this.configurationDescriptor=this.requestCompletionInterface=
this.deviceInterfaceId=void 0;this.unclaimableInterfaceNumbers=[];this.setDeviceInterfaceId=function(d){this.deviceInterfaceId=d};this.registerRequestCallback=function(d){this.requestCompletionInterface=d};this.setConfigurationDescriptor=function(d){this.configurationDescriptor=d};this.setMsVendorCode=function(d){this.msVendorCode=d}}function p(a,b){b=a.map(function(d){return d.deviceInterfaceId}).indexOf(b);return 0<=b?a[b]:null}function y(a){switch(a){case 0:var b="device";break;case 1:b="interface";
break;case 2:b="endpoint";break;case 3:b="other";break;default:svGlobal.logger.warn("Unknown recipient of URB_Func: "+a)}return b}function F(a){switch(a){case 0:var b="vendor";break;case 1:b="class";break;default:svGlobal.logger.warn("Unknown vendorOrClass request type of URB_Func: "+a)}return b}function L(a){a&=31;switch(a){case 0:var b="device";break;case 1:b="interface";break;case 2:b="endpoint";break;case 3:b="other";break;default:svGlobal.logger.warn("Could not get recipient from bmRequestType, D4..0 =  "+
a)}return b}function P(a){a=(a&96)>>5;switch(a){case 0:var b="standard";break;case 1:b="class";break;case 2:b="vendor";break;default:svGlobal.logger.warn("Could not get request type from bmRequestType, D6..5 =  "+a)}return b}function ba(){navigator.usb.onconnect=null;navigator.usb.ondisconnect=null;for(var a=0;a<H.length;a++){var b=H[a];b.device.opened&&b.device.close().then(function(){svGlobal.logger.debug('USB device "'+b.device.productName+'" gets closed.')}).catch(function(d){svGlobal.logger.warn("Failed to close usb device:",
d)})}ma=Y=H.length=0;ka=2;na=oa=pa=la=0}function R(a,b,d){svGlobal.logger.info("CANCEL_REQUEST to cancel outstanding IO request.")}function U(){var a=new hi5.DataBuffer(new Uint8Array(12));a.setLittleEndian32(1073741825);a.setLittleEndian32(la++);a.setLittleEndian32(256);J.send(a)}function X(a){var b=("0000"+a.vendorId.toString(16).toUpperCase()).slice(-4),d=("0000"+a.productId.toString(16).toUpperCase()).slice(-4);a=("0000"+(a.serialNumber||"REMOTESPARK20101").hashCode().toString(16).toUpperCase()).slice(-4);
b="V"+b+"&P"+d+"\\"+a;d=[];for(a=0;a<b.length;a++){var c=("00"+Number(b.charCodeAt(a)).toString(16).toUpperCase()).slice(-2);d.push(c);3!=a&&5!=a&&7!=a&&9!=a||d.push("-")}return d.join("")}function aa(a,b,d,c){var e,l,g,n,h,q,u,m,w,z,t,E,x;return $jscomp.asyncExecutePromiseGeneratorProgram(function(I){if(e=p(H,b))if(l=a.getLittleEndian32(),g=a.getByte(),a.skipPosition(3),0!=g){for(var D=n=a.getLittleEndian32(),B=e.configurationDescriptor,G=0;G<D;G++){a.skipPosition(2);var M=a.getLittleEndian16(),
W=a.getByte();a.skipPosition(3);var V=a.getLittleEndian32();W=B.getInterfaceByInterfaceNumber(W);W.numberOfPipesExpected=M;for(M=0;M<V;M++){a.skipPosition(4);var ea=a.getLittleEndian32(),fa=a.getLittleEndian32(),ca=W.msPipes[M];ca.maximumTransferSize=ea;ca.pipeFlags=fa}}a.skipPosition(2);D=a.getLittleEndian16();a.skipPosition(D-4);h=a.getLittleEndian32();q=void 0!=e.requestCompletionInterface?e.requestCompletionInterface:b;u=za(e.configurationDescriptor);m=new hi5.DataBuffer(new Uint8Array(u));m.setLittleEndian32(q|
1073741824);m.setLittleEndian32(d);m.setLittleEndian32(258);m.setLittleEndian32(l);w=u-28;m.setLittleEndian32(w);m.setLittleEndian16(w);m.setLittleEndian16(c);m.setLittleEndian32(0);m.setLittleEndian32(e.configurationDescriptor.configurationHandle);m.setLittleEndian32(n);for(z=0;z<n;z++)for(t=e.configurationDescriptor.msInterfaces[z],m.setLittleEndian16(16+20*t.bNumEndpoints),m.setByte(t.bInterfaceNumber),m.setByte(t.bAlternateSetting),m.setByte(t.bInterfaceClass),m.setByte(t.bInterfaceSubClass),
m.setByte(t.bInterfaceProtocol),m.setByte(0),m.setLittleEndian32(t.interfaceHandle),m.setLittleEndian32(t.bNumEndpoints),E=0;E<t.bNumEndpoints;E++)x=t.msPipes[E],m.setLittleEndian16(x.wMaxPacketSize),m.setByte(x.bEndpointAddress),m.setByte(x.bInterval),m.setLittleEndian32(x.pipeType),m.setLittleEndian32(x.pipeHandle),m.setLittleEndian32(x.maximumTransferSize),m.setLittleEndian32(x.pipeFlags);m.setLittleEndian32(0);m.setLittleEndian32(h);J.send(m)}else svGlobal.logger.warn("Failed to select configuration of USB device: USB_CONFIGURATION_DESCRIPTOR missed."),
C(q,d,c,l,2147484928,0);else svGlobal.logger.warn("Could not find web USB device with the given interface id: "+b);I.jumpToEnd()})}function za(a){var b=44;a.msInterfaces.forEach(function(d){b+=16;b+=20*d.bNumEndpoints});return b}function Aa(a,b,d,c){var e,l,g,n,h,q,u,m,w,z,t,E,x,I,D,B;return $jscomp.asyncExecutePromiseGeneratorProgram(function(G){switch(G.nextAddress){case 1:e=p(H,b);if(!e){svGlobal.logger.warn("Could not find web USB device with the given interface id: "+b);G.jumpTo(0);break}l=a.getLittleEndian32();
a.getLittleEndian32();a.getLittleEndian16();a.getLittleEndian16();g=a.getByte();n=a.getByte();a.skipPosition(2);h=a.getLittleEndian32();for(q=0;q<h;q++)a.skipPosition(12);u=void 0!=e.requestCompletionInterface?e.requestCompletionInterface:b;m=a.getLittleEndian32();G.setCatchFinallyBlocks(3);return G.yield(e.device.selectAlternateInterface(g,n),5);case 5:G.leaveTryBlock(4);break;case 3:return w=G.enterCatchBlock(),svGlobal.logger.warn("Error: failed to select interface: "+w),C(u,d,c,l,2147484928,0),
G.return();case 4:z=e.configurationDescriptor;if(t=v(z.msInterfaces,g)){E=52+20*t.bNumEndpoints;x=new hi5.DataBuffer(new Uint8Array(E));x.setLittleEndian32(u|1073741824);x.setLittleEndian32(d);x.setLittleEndian32(258);x.setLittleEndian32(l);I=E-28;x.setLittleEndian32(I);x.setLittleEndian16(I);x.setLittleEndian16(c);x.setLittleEndian32(0);x.setLittleEndian16(16+20*t.bNumEndpoints);x.setByte(t.bInterfaceNumber);x.setByte(t.bAlternateSetting);x.setByte(t.bInterfaceClass);x.setByte(t.bInterfaceSubClass);
x.setByte(t.bInterfaceProtocol);x.setByte(0);x.setLittleEndian32(t.interfaceHandle);x.setLittleEndian32(t.bNumEndpoints);for(D=0;D<t.bNumEndpoints;D++)B=t.msPipes[D],x.setLittleEndian16(B.wMaxPacketSize),x.setByte(B.bEndpointAddress),x.setByte(B.bInterval),x.setLittleEndian32(B.pipeType),x.setLittleEndian32(B.pipeHandle),x.setLittleEndian32(B.maximumTransferSize),x.setLittleEndian32(B.pipeFlags);x.setLittleEndian32(0);x.setLittleEndian32(m);J.send(x)}else svGlobal.logger.warn("Error: could not find interface with the given interface number: "+
g),C(u,d,c,l,2147484928,0);G.jumpToEnd()}})}function ha(a,b,d,c,e){var l=p(H,b);if(l){var g=void 0!=l.requestCompletionInterface?l.requestCompletionInterface:b;var n=a.getLittleEndian32(),h=a.getLittleEndian32(),q=a.getLittleEndian32();a=Ba(h);var u=a&15;switch(e){case 0:l.device.controlTransferIn({requestType:"standard",recipient:"endpoint",request:3,value:0,index:a},q).then(function(m){var w=m.status;"ok"==w.toLowerCase()?(svGlobal.logger.warn("Succeed to process pipe_cancel request"),m=new Uint8Array(m.data.buffer),
S(b,d,c,n,0,q,m)):(svGlobal.logger.warn("Failed to process pipe_cancel request, status = "+w),C(g,d,c,n,2147483648,0))}).catch(function(m){svGlobal.logger.warn("Failed to process pipe_cancel request: "+m);C(g,d,c,n,2147483648,0)});break;case 1:l.device.clearHalt(0==(a&128)>>7?"out":"in",u).then(function(m){var w=m.status;"ok"==w.toLowerCase()?(svGlobal.logger.info('Succeed to clear halt on endpoint "'+u+'".'),m=new Uint8Array(m.data.buffer),S(b,d,c,n,0,q,m)):(svGlobal.logger.warn('Failed to clear halt on endpoint "'+
u+'", status = '+w),C(g,d,c,n,2147483648,0))}).catch(function(m){svGlobal.logger.warn('Failed to clear halt on endpoint "'+u+'": '+m);C(g,d,c,n,2147483648,0)});break;case 2:svGlobal.logger.warn("Failed to process pipe request: unsupported pipe operation: REQUEST_PIPE_OPT_CLEAR");C(g,d,c,n,2147483648,0);break;default:svGlobal.logger.warn("Failed to process pipe request: unknown pipe operation: "+e),C(g,d,c,n,2147483648,0)}}else svGlobal.logger.warn("Could not find web USB device with the given interface id: "+
b)}function ia(a,b,d,c,e,l){var g=p(H,b);if(g){var n=void 0!=g.requestCompletionInterface?g.requestCompletionInterface:b;var h=a.getLittleEndian32();a.getLittleEndian32();a.getLittleEndian32();1==e&&a.getLittleEndian32();var q=a.getByte();e=a.getByte();var u=a.getLittleEndian16(),m=a.getLittleEndian16();a.getLittleEndian16();var w=a.getLittleEndian32(),z=P(q);q=L(q);e={requestType:z,recipient:q,request:e,value:u,index:m};1==l?g.device.controlTransferIn(e,w).then(function(t){"ok"==t.status.toLowerCase()?
(t=new Uint8Array(t.data.buffer),S(b,d,c,h,0,w,t)):C(n,d,c,h,2147483648,0)}).catch(function(t){svGlobal.logger.warn("Failed to perform control transfer: "+t);C(n,d,c,h,2147483648,0)}):(a=a.getBytes(w),g.device.controlTransferOut(e,a).then(function(t){"ok"==t.status.toLowerCase()?C(n,d,c,h,0,w):C(n,d,c,h,2147483648,0)}).catch(function(t){svGlobal.logger.warn("Failed to perform control transfer: "+t);C(n,d,c,h,2147483648,0)}))}else svGlobal.logger.warn("Could not find web USB device with the given interface id: "+
b)}function qa(a,b,d,c,e){var l=p(H,b);if(l){var g=void 0!=l.requestCompletionInterface?l.requestCompletionInterface:b;var n=a.getLittleEndian32(),h=a.getLittleEndian32();a.getLittleEndian32();var q=a.getLittleEndian32(),u=ra(l,h);u?(svGlobal.logger.debug("Perform bulk or interrupt transfer on endpoint: "+u),1==e?l.device.transferIn(u,q).then(function(m){var w=m.status;"ok"==w.toLowerCase()?(svGlobal.logger.info("Succeed to perform bulk or interrupt transfer in request"),m=new Uint8Array(m.data.buffer),
S(b,d,c,n,0,q,m)):(svGlobal.logger.warn("Failed to perform bulk or interrupt transfer, status = "+w),C(g,d,c,n,2147483648,0))}).catch(function(m){svGlobal.logger.warn("Failed to perform bulk or interrupt transfer (endpointNumber = "+u+"): "+m);C(g,d,c,n,2147483648,0)}):(a=a.getBytes(q),l.device.transferOut(u,a).then(function(m){m=m.status;"ok"==m.toLowerCase()?(svGlobal.logger.info("Succeed to perform bulk or interrupt transfer out request"),C(g,d,c,n,0,q)):(svGlobal.logger.warn("Failed to perform bulk or interrupt transfer, status = "+
m),C(g,d,c,n,2147483648,0))}).catch(function(m){svGlobal.logger.warn("Failed to perform bulk or interrupt transfer: "+m);C(g,d,c,n,2147483648,0)}))):(svGlobal.logger.warn("Failed to perform bulk or interrupt transfer: could not find endpoint number from the pipeHandle: "+h),C(g,d,c,n,2147483648,0))}else svGlobal.logger.warn("Could not find web USB device with the given interface id: "+b)}function ra(a,b){var d=void 0;if(a=a.configurationDescriptor)for(var c=0;c<a.msInterfaces.length;c++)for(var e=
a.msInterfaces[c],l=0;l<e.bNumEndpoints;l++){var g=e.msPipes[l];g.pipeHandle==b&&(d=g.bEndpointAddress&15)}return d}function Ba(a,b){var d=void 0;if(a=a.configurationDescriptor)for(var c=0;c<a.msInterfaces.length;c++)for(var e=a.msInterfaces[c],l=0;l<e.bNumEndpoints;l++){var g=e.msPipes[l];g.pipeHandle==b&&(d=g.bEndpointAddress)}return d}function sa(a,b,d,c,e){var l=p(H,b);if(l){var g=void 0!=l.requestCompletionInterface?l.requestCompletionInterface:b;var n=a.getLittleEndian32(),h=n&2147483647,q=
(n&2147483648)>>31;n=a.getLittleEndian32();n=ra(n);a.getLittleEndian32();for(var u=a.getLittleEndian32(),m=a.getLittleEndian32(),w=a.getLittleEndian32(),z=Array(m),t=0;t<m;t++){a.getLittleEndian32();var E=a.getLittleEndian32();a.getLittleEndian32();z[t]=E}var x=a.getLittleEndian32();1==e?l.device.isochronousTransferIn(n,z).then(function(I){if(!q){var D=new Uint8Array(I.data.buffer),B=new hi5.DataBuffer(new Uint8Array(48+x+12*m));B.setLittleEndian32(b|1073741824);B.setLittleEndian32(d);B.setLittleEndian32(257);
B.setLittleEndian32(h);B.setLittleEndian32(20+12*m);B.setLittleEndian16(20+12*m);B.setLittleEndian16(c);B.setLittleEndian32(0);B.setLittleEndian32(u);B.setLittleEndian32(m);B.setLittleEndian32(w);var G=48+12*m;I=I.packets;for(var M=0;M<I.length;M++){var W=I[M];B.setLittleEndian32(G);var V=W.data.byteLength;B.setLittleEndian32(V);G+=V;V=W.status;"ok"==V.toLowerCase()?B.setLittleEndian32(0):"stall"==V.toLowerCase()?B.setLittleEndian32(3221225476):"babble"==V.toLowerCase()&&B.setLittleEndian32(3221225490)}B.setLittleEndian32(0);
B.setLittleEndian32(x);B.setBytes(D);J.send(B)}}).catch(function(I){svGlobal.logger.warn("Failed to perform ISOCH transfer in: "+I);C(g,d,c,h,2147483648,0)}):(a=a.getBytes(x),l.device.isochronousTransferOut(n,a,z).then(function(I){if(!q){var D=new hi5.DataBuffer(new Uint8Array(48+12*m));D.setLittleEndian32(b|1073741824);D.setLittleEndian32(d);D.setLittleEndian32(258);D.setLittleEndian32(h);D.setLittleEndian32(20+12*m);D.setLittleEndian16(20+12*m);D.setLittleEndian16(c);D.setLittleEndian32(0);D.setLittleEndian32(u);
D.setLittleEndian32(m);D.setLittleEndian32(w);var B=48+12*m;I=I.packets;for(var G=0;G<I.length;G++){var M=I[G];D.setLittleEndian32(B);D.setLittleEndian32(M.bytesWritten);M=M.status;"ok"==M.toLowerCase()?D.setLittleEndian32(0):"stall"==M.toLowerCase()?D.setLittleEndian32(3221225476):"babble"==M.toLowerCase()&&D.setLittleEndian32(3221225490)}D.setLittleEndian32(0);D.setLittleEndian32(0);J.send(D)}}).catch(function(I){svGlobal.logger.warn("Failed to perform ISOCH transfer out: "+I);C(g,d,c,h,2147483648,
0)}))}else svGlobal.logger.warn("Could not find web USB device with the given interface id: "+b)}function T(a,b,d,c,e,l){var g,n,h,q,u,m,w,z,t,E,x,I,D;return $jscomp.asyncExecutePromiseGeneratorProgram(function(B){switch(B.nextAddress){case 1:g=p(H,b);if(!g){svGlobal.logger.warn("Could not find web USB device with the given interface id: "+b);B.jumpTo(0);break}n=void 0!=g.requestCompletionInterface?g.requestCompletionInterface:b;h=y(e);q=a.getLittleEndian32();u=a.getByte();m=a.getByte();w=m<<8|u;
z=a.getLittleEndian16();t=a.getLittleEndian32();if(1!=l){E=a.getBytes(t);x={requestType:"standard",recipient:h,request:7,value:w,index:z};g.device.controlTransferOut(x,E).then(function(G){"ok"==G.status.toLowerCase()?C(n,d,c,q,0,t):C(n,d,c,q,2147483648,0)}).catch(function(G){svGlobal.logger.warn("Failed to set descriptor: "+G);C(n,d,c,q,2147483648,0)});B.jumpTo(0);break}if(2!=m){x={requestType:"standard",recipient:h,request:6,value:w,index:z};g.device.controlTransferIn(x,t).then(function(G){"ok"==
G.status.toLowerCase()?(G=new Uint8Array(G.data.buffer),S(b,d,c,q,0,t,G)):C(n,d,c,q,2147483648,0)}).catch(function(G){svGlobal.logger.warn("Failed to get descriptor: "+G);C(n,d,c,q,2147483648,0)});B.jumpTo(0);break}if(g.configurationDescriptor){B.jumpTo(5);break}B.setCatchFinallyBlocks(6);I=g;return B.yield(Ca(g,h),8);case 8:I.configurationDescriptor=B.yieldResult;B.leaveTryBlock(5);break;case 6:return D=B.enterCatchBlock(),svGlobal.logger.warn("Failed to get configuration descriptor: "+D),C(n,d,
c,q,2147483648,0),B.return();case 5:E=g.configurationDescriptor.serialize(),S(b,d,c,q,0,t,E),B.jumpToEnd()}})}function Ca(a,b){var d,c,e,l,g,n,h,q,u,m,w,z,t,E,x,I,D,B,G,M,W,V,ea,fa,ca,Z,da,ta,ua,va;return $jscomp.asyncExecutePromiseGeneratorProgram(function(Q){switch(Q.nextAddress){case 1:return d={requestType:"standard",recipient:b,request:6,value:512,index:0},Q.yield(a.device.controlTransferIn(d,9),2);case 2:return c=Q.yieldResult,e=new hi5.DataBuffer(new Uint8Array(c.data.buffer)),e.skipPosition(2),
l=e.getLittleEndian16(),e.skipPosition(5),Q.yield(a.device.controlTransferIn(d,l),3);case 3:c=Q.yieldResult;e=new hi5.DataBuffer(new Uint8Array(c.data.buffer));e.skipPosition(2);l=e.getLittleEndian16();g=e.getByte();n=e.getByte();h=e.getByte();q=e.getByte();u=e.getByte();m=[];for(w=0;w<g;w++){e.skipPosition(2);z=e.getByte();t=e.getByte();E=e.getByte();x=e.getByte();I=e.getByte();D=e.getByte();B=e.getByte();G=[];for(M=0;M<E;M++)e.skipPosition(2),W=e.getByte(),V=e.getByte(),ea=e.getLittleEndian16(),
fa=e.getByte(),ca=new A(W,V,ea,fa,na++),G[M]=ca;Z=new r(z,t,E,x,I,D,B,G,oa++);m[w]=Z}return Q.yield(a.device.selectConfiguration(n),4);case 4:da=[],w=0;case 5:if(!(w<m.length)){Q.jumpTo(7);break}Z=m[w];Q.setCatchFinallyBlocks(8);return Q.yield(a.device.claimInterface(Z.bInterfaceNumber),10);case 10:Q.leaveTryBlock(6);break;case 8:Q.enterCatchBlock(),svGlobal.logger.warn('Could not claim the interface with interfaceNumber "'+Z.bInterfaceNumber+'", filtered it out from the configuration.'),da.push(Z.bInterfaceNumber);
case 6:w++;Q.jumpTo(5);break;case 7:return ta=Da(l,m,da),ua=g-da.length,va=m.filter(function(Ea){return!da.includes(Ea.bInterfaceNumber)}),Q.return(new k(ta,ua,n,h,q,u,va,pa++))}})}function Da(a,b,d){for(var c=0;c<b.length;c++){var e=b[c];if(d.includes(e.bInterfaceNumber)){a-=9;for(var l=0;l<e.bNumEndpoints;l++)a-=7}}return a}function N(a,b,d,c,e,l){var g=p(H,b);if(g){var n=void 0!=g.requestCompletionInterface?g.requestCompletionInterface:b;c=y(c);var h=a.getLittleEndian32(),q=a.getLittleEndian16(),
u=a.getLittleEndian16(),m=a.getLittleEndian32();1==l?(e={requestType:"standard",recipient:c,request:e,value:q,index:u},g.device.controlTransferIn(e,m).then(function(w){var z=w.status;"ok"==z.toLowerCase()?(svGlobal.logger.log("Succeed to perform control feature with transfer in"),w=new Uint8Array(w.data.buffer),S(b,d,urbFunction,h,0,m,w)):(svGlobal.logger.warn("Failed to perform control feature with transfer in, status = "+z),C(n,d,urbFunction,h,2147483648,0))}).catch(function(w){svGlobal.logger.warn("Failed to perform control feature with transfer in: "+
w);C(n,d,urbFunction,h,2147483648,0)})):(a=a.getBytes(m),e={requestType:"standard",recipient:c,request:e,value:q,index:u},g.device.controlTransferOut(e,a).then(function(w){w=w.status;"ok"==w.toLowerCase()?(svGlobal.logger.log("Succeed to perform control feature with transfer out"),C(n,d,urbFunction,h,0,m)):(svGlobal.logger.warn("Failed to perform control feature with transfer out, status = "+w),C(n,d,urbFunction,h,2147483648,0))}).catch(function(w){svGlobal.logger.warn("Failed to perform control feature with transfer out: "+
w);C(n,d,urbFunction,h,2147483648,0)}))}else svGlobal.logger.warn("Could not find web USB device with the given interface id: "+b)}function ja(a,b,d,c,e){var l=p(H,b);if(l){var g=void 0!=l.requestCompletionInterface?l.requestCompletionInterface:b;var n=a.getLittleEndian32(),h=a.getLittleEndian16();a.skipPosition(2);var q=a.getLittleEndian32();a={requestType:"standard",recipient:y(c),request:0,value:0,index:h};l.device.controlTransferIn(a,q).then(function(u){"ok"==u.status.toLowerCase()?(u=new Uint8Array(u.data.buffer),
S(b,d,e,n,0,q,u)):C(g,d,e,n,2147483648,0)}).catch(function(u){svGlobal.logger.warn("Failed to get status: "+u)})}else svGlobal.logger.warn("Could not find web USB device with the given interface id: "+b)}function O(a,b,d,c,e,l,g){var n=p(H,b);if(n){var h=void 0!=n.requestCompletionInterface?n.requestCompletionInterface:b;var q=a.getLittleEndian32();a.getLittleEndian32();a.getByte();var u=a.getByte(),m=a.getLittleEndian16(),w=a.getLittleEndian16();a.skipPosition(2);var z=a.getLittleEndian32();e=F(e);
l=y(l);u={requestType:e,recipient:l,request:u,value:m,index:w};1==g?n.device.controlTransferIn(u,z).then(function(t){var E=t.status;"ok"==E.toLowerCase()?(svGlobal.logger.warn("Succeed to process ControlVendorOrClassRequest with TransferIn"),t=new Uint8Array(t.data.buffer),S(b,d,c,q,0,z,t)):(svGlobal.logger.warn("Failed to process ControlVendorOrClassRequest with TransferIn, status = "+E),C(h,d,c,q,2147483648,0))}).catch(function(t){svGlobal.logger.warn("Failed to process ControlVendorOrClassRequest with TransferIn: "+
t);C(h,d,c,q,2147483648,0)}):(a=a.getBytes(z),n.device.controlTransferOut(u,a).then(function(t){t=t.status;"ok"==t.toLowerCase()?(svGlobal.logger.warn("Succeed to process ControlVendorOrClassRequest with TransferOut"),C(h,d,c,q,0,z)):(svGlobal.logger.warn("Failed to process ControlVendorOrClassRequest with TransferOut, status = "+t),C(h,d,c,q,2147483648,0))}).catch(function(t){svGlobal.logger.warn("Failed to process ControlVendorOrClassRequest with TransferOut: "+t);C(h,d,c,q,2147483648,0)}))}else svGlobal.logger.warn("Could not find web USB device with the given interface id: "+
b)}function Fa(a,b,d,c){var e=p(H,b);if(e){var l=void 0!=e.requestCompletionInterface?e.requestCompletionInterface:b;var g=a.getLittleEndian32(),n=a.getLittleEndian32();e.device.controlTransferIn({requestType:"standard",recipient:"device",request:8,value:0,index:0},n).then(function(h){var q=h.status;"ok"==q.toLowerCase()?(svGlobal.logger.warn("Succeed to process ControlGetConfigurationRequest"),h=new Uint8Array(h.data.buffer),S(b,d,c,g,0,n,h)):(svGlobal.logger.warn("Failed to process ControlGetConfigurationRequest, status = "+
q),C(l,d,c,g,2147483648,0))}).catch(function(h){svGlobal.logger.warn("Failed to process ControlGetConfigurationRequest: "+h);C(l,d,c,g,2147483648,0)})}else svGlobal.logger.warn("Could not find web USB device with the given interface id: "+b)}function Ga(a,b,d,c){var e=p(H,b);if(e){var l=void 0!=e.requestCompletionInterface?e.requestCompletionInterface:b;var g=a.getLittleEndian32(),n=a.getLittleEndian16();a.skipPosition(2);var h=a.getLittleEndian32();e.device.controlTransferIn({requestType:"standard",
recipient:"device",request:10,value:0,index:n},h).then(function(q){var u=q.status;"ok"==u.toLowerCase()?(svGlobal.logger.warn("Succeed to process ControlGetInterfaceRequest"),q=new Uint8Array(q.data.buffer),S(b,d,c,g,0,h,q)):(svGlobal.logger.warn("Failed to process ControlGetInterfaceRequest, status = "+u),C(l,d,c,g,2147483648,0))}).catch(function(q){svGlobal.logger.warn("Failed to process ControlGetInterfaceRequest: "+q);C(l,d,c,g,2147483648,0)})}else svGlobal.logger.warn("Could not find web USB device with the given interface id: "+
b)}function wa(a,b,d,c){var e,l,g,n,h,q,u,m,w,z,t;return $jscomp.asyncExecutePromiseGeneratorProgram(function(E){switch(E.nextAddress){case 1:e=p(H,b);if(!e){svGlobal.logger.warn("Could not find web USB device with the given interface id: "+b);E.jumpTo(0);break}l=void 0!=e.requestCompletionInterface?e.requestCompletionInterface:b;g=a.getLittleEndian32();n=a.getByte()>>3;h=y(n);q=a.getByte();u=a.getByte();m=a.getLittleEndian16();a.skipPosition(3);w=a.getLittleEndian32();if(void 0!=e.msVendorCode){E.jumpTo(3);
break}return E.yield(Ha(e.device),4);case 4:z=E.yieldResult;if(void 0!=z){E.jumpTo(5);break}return E.yield(Ia(e.device),6);case 6:z=E.yieldResult;case 5:if(void 0!=z)e.setMsVendorCode(z),svGlobal.logger.warn("Set MS vendor code: "+z);else return svGlobal.logger.warn("Failed to get MS Vendor Code."),C(l,d,c,g,2147484928,0),E.return();case 3:t={requestType:"vendor",recipient:h,request:e.msVendorCode,value:q<<8|u,index:m>>8},e.device.controlTransferIn(t,w).then(function(x){status=x.status;"ok"==status.toLowerCase()?
(x=new Uint8Array(x.data.buffer),S(b,d,c,g,0,w,x)):(svGlobal.logger.warn("Failed to get OS feature descriptor, status = "+status),C(l,d,c,g,2147484928,0))}).catch(function(x){svGlobal.logger.warn("Failed to get OS feature descriptor: "+x);C(l,d,c,g,2147484928,0)}),E.jumpToEnd()}})}function Ha(a){var b,d,c,e,l,g,n,h;return $jscomp.asyncExecutePromiseGeneratorProgram(function(q){switch(q.nextAddress){case 1:return b=void 0,d={requestType:"standard",recipient:"device",request:6,value:1006,index:0},q.setCatchFinallyBlocks(2),
q.yield(a.controlTransferIn(d,18),4);case 4:c=q.yieldResult;q.leaveTryBlock(3);break;case 2:return q.enterCatchBlock(),q.return(b);case 3:e=c.status;if("ok"==e.toLowerCase()){l=c.data;g=new hi5.DataBuffer(new Uint8Array(l.buffer));g.getByte();n=g.getByte();if(3!=n)return svGlobal.logger.warn("Failed to parse os feature descriptor, type = "+n+", expected 0x03."),q.return(b);h=g.getUnicodeString(14,!1);if("MSFT100"!=h.toUpperCase())return svGlobal.logger.warn("Failed to parse os feature descriptor, signature = "+
h+', expected "MSFT100".'),q.return(b);b=g.getByte();g.skipPosition(1)}return q.return(b)}})}function Ia(a){var b,d,c,e,l,g,n,h,q,u,m,w;return $jscomp.asyncExecutePromiseGeneratorProgram(function(z){switch(z.nextAddress){case 1:return b=void 0,d={requestType:"standard",recipient:"device",request:6,value:3840,index:0},z.setCatchFinallyBlocks(2),z.yield(a.controlTransferIn(d,5),4);case 4:c=z.yieldResult;z.leaveTryBlock(3);break;case 2:return z.enterCatchBlock(),z.return(b);case 3:e=c.status;if("ok"!=
e.toLowerCase()){z.jumpTo(5);break}l=c.data;g=new hi5.DataBuffer(new Uint8Array(l.buffer));g.getByte();g.getByte();n=g.getLittleEndian16();g.getByte();d={requestType:"standard",recipient:"device",request:6,value:3840,index:0};z.setCatchFinallyBlocks(6);return z.yield(a.controlTransferIn(d,n),8);case 8:c=z.yieldResult;z.leaveTryBlock(7);break;case 6:return z.enterCatchBlock(),z.return(b);case 7:if(e=c.status,"ok"==e.toLowerCase())for(l=c.data,g=new hi5.DataBuffer(new Uint8Array(l.buffer));g.has(2);)if(h=
g.getByte(),q=g.getByte(),16!=q)g.skipPosition(h-2);else if(u=g.getByte(),5!=u)g.skipPosition(h-3);else if(g.skipPosition(1),m=g.getBytes(16),w=m.length==xa.length&&m.every(function(t,E){return t===xa[E]})){g.getLittleEndian32();n=g.getLittleEndian16();b=g.getByte();g.skipPosition(1);break}else g.skipPosition(h-20);case 5:return z.return(b)}})}function S(a,b,d,c,e,l,g){var n=new hi5.DataBuffer(new Uint8Array(36+l));n.setLittleEndian32(a|1073741824);n.setLittleEndian32(b);n.setLittleEndian32(257);
n.setLittleEndian32(c);n.setLittleEndian32(8);n.setLittleEndian16(8);n.setLittleEndian16(d);n.setLittleEndian32(e);0==e?n.setLittleEndian32(0):n.setLittleEndian32(2147942450);if(g.length<=l)n.setLittleEndian32(g.length),n.setBytes(g);else for(n.setLittleEndian32(l),a=0;a<l;a++)n.setByte(g[a]);J.send(n)}function C(a,b,d,c,e,l){var g=new hi5.DataBuffer(new Uint8Array(36));g.setLittleEndian32(a|1073741824);g.setLittleEndian32(b);g.setLittleEndian32(258);g.setLittleEndian32(c);g.setLittleEndian32(8);
g.setLittleEndian16(8);g.setLittleEndian16(d);g.setLittleEndian32(e);0==e?g.setLittleEndian32(0):g.setLittleEndian32(2147942450);g.setLittleEndian32(l);J.send(g)}var ya=!1,J=new f;J.name="URBDRC";J.onopen=function(){svGlobal.logger.debug("UsbChannel onOpen")};J.onclose=function(){svGlobal.logger.debug("UsbChannel onClose");ba()};J.process=function(a){var b=a.getLittleEndian32(),d=a.getLittleEndian32(),c=b>>>30;b&=1073741823;var e=a.getLittleEndian32();svGlobal.logger.debug("USB DEVICE channel received data: interfaceId = "+
b+", messageId = "+d+", functionId = 0x"+e.toString(16)+", mask = "+c);switch(e){case 1:svGlobal.logger.info("RIMCALL_RELEASE, to release the interface ID: "+b);break;case 2:svGlobal.logger.info("RIMCALL_QUERYINTERFACE, to query a new interface ID: "+b);break;case 256:switch(b){case 0:0==c?(a=a.getLittleEndian32(),svGlobal.logger.debug("Exchange capability, cap = "+a),1!=a&&(svGlobal.logger.warn("Unexpected USB capability value: "+a),a=1),c=new hi5.DataBuffer(new Uint8Array(16)),c.setLittleEndian32(b|
0),c.setLittleEndian32(d),c.setLittleEndian32(a),c.setLittleEndian32(0),J.send(c)):R(a,b,d);break;case 2:svGlobal.logger.debug("Channel Created, interfaceId = "+b+", messageId = "+d);b=a.getLittleEndian32();c=a.getLittleEndian32();a=a.getLittleEndian32();1!=b&&(svGlobal.logger.warn("Unexpected USB redirection major version:"+b),b=1);0!=c&&(svGlobal.logger.warn("Unexpected USB redirection minor version:"+c),c=0);0!=a&&(svGlobal.logger.warn("Unexpected USB redirection capability:"+a),a=0);e=new hi5.DataBuffer(new Uint8Array(24));
e.setLittleEndian32(1073741827);e.setLittleEndian32(d);e.setLittleEndian32(256);e.setLittleEndian32(b);e.setLittleEndian32(c);e.setLittleEndian32(a);J.send(e);if(ya){svGlobal.logger.debug("A Channel for one USB device is created. Add device...");a=H[Y];c=a.device;d=ma++;a.setDeviceInterfaceId(d);a=X(c);b=[];e=("0000"+c.vendorId.toString(16).toUpperCase()).slice(-4);var l=("0000"+c.productId.toString(16).toUpperCase()).slice(-4);b[1]="USB\\VID_"+e+"&PID_"+l;b[0]=b[1]+"&REV_0100";e=[];l=1==c.configurations.length&&
1<c.configurations[0].interfaces.length&&0==c.deviceClass?!0:239==c.deviceClass&&2==c.deviceSubclass&&1==c.deviceProtocol?!0:!1;if(l)e[3]="USB\\COMPOSITE",e[2]="USB\\DevClass_00",e[1]=e[2]+"&SubCalss_00",e[0]=e[1]+"&Prot_00";else{l=("00"+c.deviceClass.toString(16).toUpperCase()).slice(-2);var g=("00"+c.deviceSubclass.toString(16).toUpperCase()).slice(-2),n=("00"+c.deviceProtocol.toString(16).toUpperCase()).slice(-2);e[2]="USB\\Class_"+l;e[1]=e[2]+"&SubCalss_"+g;e[0]=e[1]+"&Prot_"+n}l=e[0].length+
1+e[1].length+1+e[2].length+1+(void 0==e[3]?0:e[3].length+1)+1;g="{"+X(c)+"}";c=2==c.usbVersionMajor?512:1==c.usbVersionMajor&&1==c.usbVersionMinor?272:256;n=512==c?1:0;var h=new hi5.DataBuffer(new Uint8Array(2*l+324));h.setLittleEndian32(1073741825);h.setLittleEndian32(la++);h.setLittleEndian32(257);h.setLittleEndian32(1);h.setLittleEndian32(d);h.setLittleEndian32(37);h.setNullTerminatedUnicodeString(a);h.setLittleEndian32(54);h.setNullTerminatedUnicodeString(b[0]);h.setNullTerminatedUnicodeString(b[1]);
h.setByte(0);h.setByte(0);h.setLittleEndian32(l);h.setNullTerminatedUnicodeString(e[0]);h.setNullTerminatedUnicodeString(e[1]);h.setNullTerminatedUnicodeString(e[2]);e[3]&&h.setNullTerminatedUnicodeString(e[3]);h.setByte(0);h.setByte(0);h.setLittleEndian32(39);h.setNullTerminatedUnicodeString(g);h.setLittleEndian32(28);h.setLittleEndian32(2);h.setLittleEndian32(1536);h.setLittleEndian32(c);h.setLittleEndian32(0);h.setLittleEndian32(n);h.setLittleEndian32(80);J.send(h);Y++;Y<H.length&&U()}else svGlobal.logger.debug("Control channel for all USB devices is created. Add channel for each usb device now..."),
ya=!0,0<H.length&&Y<H.length&&U();break;default:R(a,b,d)}break;case 257:c=a.getLittleEndian32();(d=p(H,b))?1<=c&&(a=a.getLittleEndian32(),d.registerRequestCallback(a),svGlobal.logger.debug('REGISTER_REQUEST_CALLBACK: requestCompletionInterfaceID "'+a+'" is registered.')):svGlobal.logger.warn("Could not register callbck for the USB device: could not find WebUsbDevice with the given USB interface id: "+b);break;case 258:svGlobal.logger.debug("IO control reqeust: interfaceId = "+b+", messageId = "+d);
if(c=p(H,b)){b=void 0!=c.requestCompletionInterface?c.requestCompletionInterface:b;c=a.getLittleEndian32();e=a.getLittleEndian32();0==e||a.getBytes(e);e=a.getLittleEndian32();a=a.getLittleEndian32();switch(c){case 2228231:svGlobal.logger.warn("IOCTL_INTERNAL_USB_RESET_PORT request is not supported.");break;case 2228243:svGlobal.logger.warn("IOCTL_INTERNAL_USB_GET_PORT_STATUS request is not supported.");break;case 2228251:svGlobal.logger.warn("IOCTL_INTERNAL_USB_GET_HUB_COUNT request is not supported.");
break;case 2228255:svGlobal.logger.warn("IOCTL_INTERNAL_USB_CYCLE_PORT request is not supported.");break;case 2228256:svGlobal.logger.warn("IOCTL_INTERNAL_USB_GET_HUB_NAME request is not supported.");break;case 2229280:svGlobal.logger.warn("IOCTL_INTERNAL_USB_GET_BUS_INFO request is not supported.");break;case 2229284:svGlobal.logger.warn("IOCTL_INTERNAL_USB_GET_CONTROLLER_NAME request is not supported.")}c=new hi5.DataBuffer(new Uint8Array(28+e));c.setLittleEndian32(b|1073741824);c.setLittleEndian32(d);
c.setLittleEndian32(256);c.setLittleEndian32(a);c.setLittleEndian32(0);c.setLittleEndian32(e);c.setLittleEndian32(e);d=new Uint8Array(e);c.setBytes(d);J.send(c)}else svGlobal.logger.warn("Could not find web USB device with the given interface id: "+b);break;case 259:c=b;svGlobal.logger.debug("Internal IO control reqeust: interfaceId = "+c+", messageId = "+d);(e=p(H,c))?(b=a.getLittleEndian32(),l=a.getLittleEndian32(),0==l||a.getBytes(l),a.getLittleEndian32(),a=a.getLittleEndian32(),c=void 0!=e.requestCompletionInterface?
e.requestCompletionInterface:c,2244608==b?(b=Date.now(),e=new hi5.DataBuffer(new Uint8Array(32)),e.setLittleEndian32(c|1073741824),e.setLittleEndian32(d),e.setLittleEndian32(256),e.setLittleEndian32(a),e.setLittleEndian32(0),e.setLittleEndian32(4),e.setLittleEndian32(4),e.setLittleEndian32(b),J.send(e)):svGlobal.logger.warn("Unsupported USB Internal IO Control Code: "+b)):svGlobal.logger.warn("Could not find web USB device with the given interface id: "+c);break;case 260:svGlobal.logger.debug("Query Device Text: interfaceId = "+
b+", messageId = "+d);c=a.getLittleEndian32();a=a.getLittleEndian32();1033!=a&&svGlobal.logger.warn("Could not query text for the USB device using other locale except English-USA: unsupported localeId: "+a);a=0;(e=p(H,b))?0==c?(l=e.device.productName,e=l.length+1,c=new hi5.DataBuffer(new Uint8Array(2*e+16)),c.setLittleEndian32(b|-2147483648),c.setLittleEndian32(d),c.setLittleEndian32(e),c.setNullTerminatedUnicodeString(l)):1==c?(l="Port_#"+("0000"+e.port.toString(16)).slice(-4)+".Hub_#0001",e=21,
c=new hi5.DataBuffer(new Uint8Array(2*e+16)),c.setLittleEndian32(b|-2147483648),c.setLittleEndian32(d),c.setLittleEndian32(e),c.setNullTerminatedUnicodeString(l)):(svGlobal.logger.warn("Could not query text for the USB device: unknown text type: "+c),a=87,c=new hi5.DataBuffer(new Uint8Array(16)),c.setLittleEndian32(b|-2147483648),c.setLittleEndian32(d),c.setLittleEndian32(0)):(svGlobal.logger.warn("Could not query text for the USB device: could not find WebUsbDevice with the given USB interface id: "+
b),a=87,c=new hi5.DataBuffer(new Uint8Array(16)),c.setLittleEndian32(b|-2147483648),c.setLittleEndian32(d),c.setLittleEndian32(0));c.setLittleEndian32(a);J.send(c);break;case 261:c=b;a.getLittleEndian32();a.getLittleEndian16();b=a.getLittleEndian16();switch(b){case 0:svGlobal.logger.info("URB_Func: URB_FUNCTION_SELECT_CONFIGURATION");aa(a,c,d,b);break;case 1:svGlobal.logger.info("URB_Func: URB_FUNCTION_SELECT_INTERFACE");Aa(a,c,d,b);break;case 2:svGlobal.logger.info("URB_Func: URB_FUNCTION_ABORT_PIPE");
ha(a,c,d,b,0);break;case 3:svGlobal.logger.warn("Obsoleted URB_Func: URB_FUNCTION_TAKE_FRAME_LENGTH_CONTROL");break;case 4:svGlobal.logger.warn("Obsoleted URB_Func: URB_FUNCTION_RELEASE_FRAME_LENGTH_CONTROL");break;case 5:svGlobal.logger.warn("Obsoleted URB_Func: URB_FUNCTION_GET_FRAME_LENGTH");break;case 6:svGlobal.logger.warn("Obsoleted URB_Func: URB_FUNCTION_SET_FRAME_LENGTH");break;case 7:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_CURRENT_FRAME_NUMBER");(e=p(H,c))?(c=void 0!=e.requestCompletionInterface?
e.requestCompletionInterface:c,e=a.getLittleEndian32(),a=a.getLittleEndian32(),l=Date.now(),g=new hi5.DataBuffer(new Uint8Array(40)),g.setLittleEndian32(c|1073741824),g.setLittleEndian32(d),g.setLittleEndian32(258),g.setLittleEndian32(e),g.setLittleEndian32(12),g.setLittleEndian16(12),g.setLittleEndian16(b),g.setLittleEndian32(0),g.setLittleEndian32(l),g.setLittleEndian32(0),g.setLittleEndian32(a),J.send(g)):svGlobal.logger.warn("Could not find web USB device with the given interface id: "+c);break;
case 8:svGlobal.logger.info("URB_Func: URB_FUNCTION_CONTROL_TRANSFER");ia(a,c,d,b,0,1);break;case 9:svGlobal.logger.info("URB_Func: URB_FUNCTION_BULK_OR_INTERRUPT_TRANSFER");qa(a,c,d,b,1);break;case 10:svGlobal.logger.info("URB_Func: URB_FUNCTION_ISOCH_TRANSFER");sa(a,c,d,b,1);break;case 11:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_DESCRIPTOR_FROM_DEVICE");T(a,c,d,b,0,1);break;case 12:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_DESCRIPTOR_TO_DEVICE");T(a,c,d,b,0,1);break;case 13:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_FEATURE_TO_DEVICE");
N(a,c,d,0,3,1);break;case 14:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_FEATURE_TO_INTERFACE");N(a,c,d,1,3,1);break;case 15:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_FEATURE_TO_ENDPOINT");N(a,c,d,2,3,1);break;case 16:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLEAR_FEATURE_TO_DEVICE");N(a,c,d,0,1,1);break;case 17:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLEAR_FEATURE_TO_INTERFACE");N(a,c,d,1,1,1);break;case 18:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLEAR_FEATURE_TO_ENDPOINT");
N(a,c,d,2,1,1);break;case 19:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_STATUS_FROM_DEVICE");ja(a,c,d,0,b);break;case 20:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_STATUS_FROM_INTERFACE");ja(a,c,d,1,b);break;case 21:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_STATUS_FROM_ENDPOINT");ja(a,c,d,2,b);break;case 22:svGlobal.logger.warn("URB_Func: URB_FUNCTION_RESERVED_0X0016");break;case 23:svGlobal.logger.info("URB_Func: URB_FUNCTION_VENDOR_DEVICE");O(a,c,d,b,0,0,1);break;case 24:svGlobal.logger.info("URB_Func: URB_FUNCTION_VENDOR_INTERFACE");
O(a,c,d,b,0,1,1);break;case 25:svGlobal.logger.info("URB_Func: URB_FUNCTION_VENDOR_ENDPOINT");O(a,c,d,b,0,2,1);break;case 26:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLASS_DEVICE");O(a,c,d,b,1,0,1);break;case 27:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLASS_INTERFACE");O(a,c,d,b,1,1,1);break;case 28:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLASS_ENDPOINT");O(a,c,d,b,1,2,1);break;case 29:svGlobal.logger.warn("URB_Func: URB_FUNCTION_RESERVE_0X001D");break;case 30:svGlobal.logger.info("URB_Func: URB_FUNCTION_SYNC_RESET_PIPE_AND_CLEAR_STALL");
ha(a,c,d,b,1);break;case 31:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLASS_OTHER");O(a,c,d,b,1,3,1);break;case 32:svGlobal.logger.info("URB_Func: URB_FUNCTION_VENDOR_OTHER");O(a,c,d,b,0,3,1);break;case 33:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_STATUS_FROM_OTHER");ja(a,c,d,3,b);break;case 34:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLEAR_FEATURE_TO_OTHER");N(a,c,d,3,1,1);break;case 35:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_FEATURE_TO_OTHER");N(a,c,d,3,3,1);break;case 36:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_DESCRIPTOR_FROM_ENDPOINT");
T(a,c,d,b,2,1);break;case 37:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_DESCRIPTOR_TO_ENDPOINT");T(a,c,d,b,2,1);break;case 38:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_CONFIGURATION");Fa(a,c,d,b);break;case 39:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_INTERFACE");Ga(a,c,d,b);break;case 40:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_DESCRIPTOR_FROM_INTERFACE");T(a,c,d,b,1,1);break;case 41:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_DESCRIPTOR_TO_INTERFACE");T(a,c,d,b,
1,1);break;case 42:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_MS_FEATURE_DESCRIPTOR");wa(a,c,d,b);break;case 43:svGlobal.logger.warn("URB_Func: URB_FUNCTION_RESERVE_0X002B");break;case 44:svGlobal.logger.warn("URB_Func: URB_FUNCTION_RESERVE_0X002C");break;case 45:svGlobal.logger.warn("URB_Func: URB_FUNCTION_RESERVE_0X002D");break;case 46:svGlobal.logger.warn("URB_Func: URB_FUNCTION_RESERVE_0X002E");break;case 47:svGlobal.logger.warn("URB_Func: URB_FUNCTION_RESERVE_0X002F");break;case 48:svGlobal.logger.info("URB_Func: URB_FUNCTION_SYNC_RESET_PIPE");
ha(a,c,d,b,1);break;case 49:svGlobal.logger.info("URB_Func: URB_FUNCTION_SYNC_CLEAR_STALL");ha(a,c,d,b,2);break;case 50:svGlobal.logger.info("URB_Func: URB_FUNCTION_CONTROL_TRANSFER_EX");ia(a,c,d,b,1,1);break;default:svGlobal.logger.info("Unknown URB_Func in TransferInRequest: "+b)}break;case 262:svGlobal.logger.debug("TRANSFER_OUT_REQUEST: interfaceId = "+b+", messageId = "+d);a.getLittleEndian32();a.getLittleEndian16();c=a.getLittleEndian16();switch(c){case 8:svGlobal.logger.info("URB_Func: URB_FUNCTION_CONTROL_TRANSFER");
ia(a,b,d,c,0,0);break;case 9:svGlobal.logger.info("URB_Func: URB_FUNCTION_BULK_OR_INTERRUPT_TRANSFER");qa(a,b,d,c,0);break;case 10:svGlobal.logger.info("URB_Func: URB_FUNCTION_ISOCH_TRANSFER");sa(a,b,d,c,0);break;case 11:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_DESCRIPTOR_FROM_DEVICE");T(a,b,d,c,0,0);break;case 12:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_DESCRIPTOR_TO_DEVICE");T(a,b,d,c,0,0);break;case 13:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_FEATURE_TO_DEVICE");N(a,b,d,
0,3,0);break;case 14:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_FEATURE_TO_INTERFACE");N(a,b,d,1,3,0);break;case 15:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_FEATURE_TO_ENDPOINT");N(a,b,d,2,3,0);break;case 16:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLEAR_FEATURE_TO_DEVICE");N(a,b,d,0,1,0);break;case 17:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLEAR_FEATURE_TO_INTERFACE");N(a,b,d,1,1,0);break;case 18:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLEAR_FEATURE_TO_ENDPOINT");N(a,
b,d,2,1,0);break;case 23:svGlobal.logger.info("URB_Func: URB_FUNCTION_VENDOR_DEVICE");O(a,b,d,c,0,0,0);break;case 24:svGlobal.logger.info("URB_Func: URB_FUNCTION_VENDOR_INTERFACE");O(a,b,d,c,0,1,0);break;case 25:svGlobal.logger.info("URB_Func: URB_FUNCTION_VENDOR_ENDPOINT");O(a,b,d,c,0,2,0);break;case 26:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLASS_DEVICE");O(a,b,d,c,1,0,0);break;case 27:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLASS_INTERFACE");O(a,b,d,c,1,1,0);break;case 28:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLASS_ENDPOINT");
O(a,b,d,c,1,2,0);break;case 31:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLASS_OTHER");O(a,b,d,c,1,3,0);break;case 32:svGlobal.logger.info("URB_Func: URB_FUNCTION_VENDOR_OTHER");O(a,b,d,c,0,3,0);break;case 34:svGlobal.logger.info("URB_Func: URB_FUNCTION_CLEAR_FEATURE_TO_OTHER");N(a,b,d,3,1,0);break;case 35:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_FEATURE_TO_OTHER");N(a,b,d,3,3,0);break;case 36:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_DESCRIPTOR_FROM_ENDPOINT");T(a,b,d,c,2,0);break;
case 37:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_DESCRIPTOR_TO_ENDPOINT");T(a,b,d,c,2,0);break;case 40:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_DESCRIPTOR_FROM_INTERFACE");T(a,b,d,c,0,0);break;case 41:svGlobal.logger.info("URB_Func: URB_FUNCTION_SET_DESCRIPTOR_TO_INTERFACE");T(a,b,d,c,1,0);break;case 42:svGlobal.logger.info("URB_Func: URB_FUNCTION_GET_MS_FEATURE_DESCRIPTOR");wa(a,b,d,c);break;case 50:svGlobal.logger.info("URB_Func: URB_FUNCTION_CONTROL_TRANSFER_EX");ia(a,b,d,c,1,0);
break;default:svGlobal.logger.info("Unknown URB_Func in TransferOutRequest: "+c)}break;case 263:break;default:svGlobal.logger.warn("Unrecognized functionId: "+e)}};J.onDeviceConnect=function(a){if(-1===H.findIndex(function(d){return d.device.serialNumber==a.serialNumber&&d.device.vendorId==a.vendorId&&d.device.productId==a.productId})){var b=new K(a,ka++);H.push(b);U()}else svGlobal.logger.warn("The plugged in USB device has been added already")};J.onDeviceDisconnect=function(a){var b=H.findIndex(function(d){return d.device.serialNumber==
a.serialNumber&&d.device.vendorId==a.vendorId&&d.device.productId==a.productId});-1<b&&(H.splice(b,1),Y--)};var xa=[223,96,221,216,137,69,199,76,156,210,101,157,158,100,138,159];K.prototype.equals=function(a){return this.device.serialNumber==a.device.serialNumber&&this.device.vendorId==a.device.vendorId&&this.device.productId==a.device.productId};var H=[],Y=0,ma=0,ka=2,la=0,pa=0,oa=0,na=0;J.openDevices=function(a){a.forEach(function(b){var d=new K(b,ka++);H.find(function(c){return c.equals(d)})||
d.device.open().then(function(){H.push(d);svGlobal.logger.info("Open "+d)}).catch(function(c){hi5.notifications.notify("Failed to open "+c)})});navigator.usb.onconnect=function(b){b=b.device;svGlobal.logger.info("ondisconnect() Device is unplugged. event.device: "+b);J.onDeviceDisconnect(b)};navigator.usb.ondisconnect=function(b){b=b.device;svGlobal.logger.info("ondisconnect() Device is unplugged. event.device: "+b);J.onDeviceDisconnect(b)}};return J};
