var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,g){if(a==Array.prototype||a==Object.prototype)return a;a[b]=g.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var g=a[b];if(g&&g.Math==Math)return g}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var g=$jscomp.propertyToPolyfillSymbol[b];if(null==g)return a[b];g=a[g];return void 0!==g?g:a[b]};$jscomp.polyfill=function(a,b,g,l){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,g,l):$jscomp.polyfillUnisolated(a,b,g,l))};
$jscomp.polyfillUnisolated=function(a,b,g,l){g=$jscomp.global;a=a.split(".");for(l=0;l<a.length-1;l++){var e=a[l];if(!(e in g))return;g=g[e]}a=a[a.length-1];l=g[a];b=b(l);b!=l&&null!=b&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,g,l){var e=a.split(".");a=1===e.length;l=e[0];l=!a&&l in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var q=0;q<e.length-1;q++){var c=e[q];if(!(c in l))return;l=l[c]}e=e[e.length-1];g=$jscomp.IS_SYMBOL_NATIVE&&"es6"===g?l[e]:null;b=b(g);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==g&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(l,e,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(g){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var g=a.next();$jscomp.generator.ensureIteratorResultIsObject_(g);if(g.done)this.yieldResult=g.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(g.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,g){g?this.finallyContexts_[g]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(g){return{value:g,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,g){try{var l=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(l);if(!l.done)return this.context_.stop_(),l;var e=l.value}catch(q){return this.context_.yieldAllIterator_=null,this.context_.throw_(q),this.nextStep_()}this.context_.yieldAllIterator_=null;g.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(l){return a.next(l)}function g(l){return a.throw(l)}return new Promise(function(l,e){function q(c){c.done?l(c.value):Promise.resolve(c.value).then(b,g).then(q,e)}q(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(e,q){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:q})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var g=0,l=function(e){if(this instanceof l)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+g++,e)};return l},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),g=0;g<b.length;g++){var l=$jscomp.global[b[g]];"function"===typeof l&&"function"!=typeof l.prototype[a]&&$jscomp.defineProperty(l.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function g(c){return c instanceof e?c:new e(function(h,m){h(c)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(c){if(null==this.batch_){this.batch_=[];var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})}this.batch_.push(c)};
var l=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(c){l(c,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=this.batch_;this.batch_=[];for(var h=0;h<c.length;++h){var m=c[h];c[h]=null;try{m()}catch(d){this.asyncThrow_(d)}}}this.batch_=null};b.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var e=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var h=this.createResolveAndReject_();
try{c(h.resolve,h.reject)}catch(m){h.reject(m)}};e.prototype.createResolveAndReject_=function(){function c(d){return function(k){m||(m=!0,d.call(h,k))}}var h=this,m=!1;return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};e.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof e)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var h=null!=c;break a;case "function":h=!0;break a;default:h=!1}h?this.resolveToNonPromiseObj_(c):
this.fulfill_(c)}};e.prototype.resolveToNonPromiseObj_=function(c){var h=void 0;try{h=c.then}catch(m){this.reject_(m);return}"function"==typeof h?this.settleSameAsThenable_(h,c):this.fulfill_(c)};e.prototype.reject_=function(c){this.settle_(2,c)};e.prototype.fulfill_=function(c){this.settle_(1,c)};e.prototype.settle_=function(c,h){if(0!=this.state_)throw Error("Cannot settle("+c+", "+h+"): Promise already settled in state"+this.state_);this.state_=c;this.result_=h;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};e.prototype.scheduleUnhandledRejectionCheck_=function(){var c=this;l(function(){if(c.notifyUnhandledRejection_()){var h=$jscomp.global.console;"undefined"!==typeof h&&h.error(c.result_)}},1)};e.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var c=$jscomp.global.CustomEvent,h=$jscomp.global.Event,m=$jscomp.global.dispatchEvent;if("undefined"===typeof m)return!0;"function"===typeof c?c=new c("unhandledrejection",{cancelable:!0}):
"function"===typeof h?c=new h("unhandledrejection",{cancelable:!0}):(c=$jscomp.global.document.createEvent("CustomEvent"),c.initCustomEvent("unhandledrejection",!1,!0,c));c.promise=this;c.reason=this.result_;return m(c)};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var c=0;c<this.onSettledCallbacks_.length;++c)q.asyncExecute(this.onSettledCallbacks_[c]);this.onSettledCallbacks_=null}};var q=new b;e.prototype.settleSameAsPromise_=function(c){var h=this.createResolveAndReject_();
c.callWhenSettled_(h.resolve,h.reject)};e.prototype.settleSameAsThenable_=function(c,h){var m=this.createResolveAndReject_();try{c.call(h,m.resolve,m.reject)}catch(d){m.reject(d)}};e.prototype.then=function(c,h){function m(n,r){return"function"==typeof n?function(p){try{d(n(p))}catch(t){k(t)}}:r}var d,k,f=new e(function(n,r){d=n;k=r});this.callWhenSettled_(m(c,d),m(h,k));return f};e.prototype.catch=function(c){return this.then(void 0,c)};e.prototype.callWhenSettled_=function(c,h){function m(){switch(d.state_){case 1:c(d.result_);
break;case 2:h(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?q.asyncExecute(m):this.onSettledCallbacks_.push(m);this.isRejectionHandled_=!0};e.resolve=g;e.reject=function(c){return new e(function(h,m){m(c)})};e.race=function(c){return new e(function(h,m){for(var d=$jscomp.makeIterator(c),k=d.next();!k.done;k=d.next())g(k.value).callWhenSettled_(h,m)})};e.all=function(c){var h=$jscomp.makeIterator(c),m=h.next();return m.done?g([]):new e(function(d,
k){function f(p){return function(t){n[p]=t;r--;0==r&&d(n)}}var n=[],r=0;do n.push(void 0),r++,g(m.value).callWhenSettled_(f(n.length-1),k),m=h.next();while(!m.done)})};return e},"es6","es3");$jscomp.findInternal=function(a,b,g){a instanceof String&&(a=String(a));for(var l=a.length,e=0;e<l;e++){var q=a[e];if(b.call(g,q,e,a))return{i:e,v:q}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,g){return $jscomp.findInternal(this,b,g).v}},"es6","es3");
svGlobal.DCVC_EXTENSION=svGlobal.DCVC_EXTENSION||{};
svGlobal.DCVC_EXTENSION.DRIVE=function(a){function b(d){for(var k=h.length,f=0;f<k;f++)if(h[f].deviceId==d)return h[f]}function g(d){var k=1+d.getSize();k=new hi5.DataBuffer(new Uint8Array(k));k.setByte(0);d.toBuffer(k);k.markEnd();c.send(k)}function l(d){d.getByte();var k=d.getLittleEndian32(),f=d.getLittleEndian32(),n=d.getUnicodeString(f);d=h.find(function(r){return(r.printName||r.dosName)==n});d.deviceId=k;b(k).operation.attach(k,n,d)}function e(d,k,f,n,r){this.type=4;this.dosName="PRN2";this.operation=
r;this.driverName=d;this.printName=k;this.deviceId=0;f=f?2:0;n&&(f|=16);n=d?2*(d.length+1):0;r=2*(k.length+1);var p=new hi5.DataBuffer(new Uint8Array(24+n+r));p.setLittleEndian32(f);p.skipPosition(8);p.setLittleEndian32(n);p.setLittleEndian32(r);p.skipPosition(4);d&&p.setUnicodeString(d+"\x00");p.setUnicodeString(k+"\x00");this.data=p.getData();this.toBuffer=function(t){t.setLittleEndian32(this.type);t.setLittleEndian32(this.deviceId);t.setAsciiString(this.dosName,8);this.data&&(t.setLittleEndian32(this.data.length),
t.setBytes(this.data))};this.getSize=function(){var t=20;this.data&&(t+=this.data.length);return t}}function q(d){this.attach=function(k,f,n){k=2+n.getSize();k=new hi5.DataBuffer(new Uint8Array(k));k.setByte(7);k.setByte(1);n.toBuffer(k);k.markEnd();d.onagentmessage(k.getData())};this.ioRequest=function(k){var f=new hi5.DataBuffer(new Uint8Array(2+k.length));f.setByte(7);f.setByte(2);f.setBytes(k);f.markEnd();d.onagentmessage(f.getData())}}var c=new a;c.name="DRIVESTB";var h=[],m=!1;c.onopen=function(){if(!m&&
(m=!0,0<h.length))for(var d=0,k=h.length;d<k;d++)g(h[d])};c.process=function(d){switch(d.getByte()){case 1:l(d);break;case 2:var k=d.getLittleEndian32(),f=b(k).operation;if(f instanceof q)d.skipPosition(-4),k=d.getBytes(d.getEnd()-d.getPosition()),f.ioRequest(k);else{var n=d.getLittleEndian32(),r=d.getLittleEndian32(),p=d.getLittleEndian32();d.getLittleEndian32();switch(p){case 0:p=d.getBigEndian32();d.skipPosition(8);n=d.getLittleEndian32();var t=d.getLittleEndian32(),w=d.getLittleEndian32(),x=d.getLittleEndian32(),
u=d.getLittleEndian32(),v="";0<u&&256>u/2&&(v=d.getUnicodeString(u));d=f.create(p,n,t,w,x,v);f=new hi5.DataBuffer(new Uint8Array(22));f.setByte(3);f.setLittleEndian16(17522);f.setLittleEndian16(18755);f.setLittleEndian32(k);f.setLittleEndian32(r);f.setLittleEndian32(d[0]);f.setLittleEndian32(d[1]);f.setByte(0);f.markEnd();c.send(f);break;case 2:d.skipPosition(32);d=f.close(n);f=new hi5.DataBuffer(new Uint8Array(22));f.setByte(3);f.setLittleEndian16(17522);f.setLittleEndian16(18755);f.setLittleEndian32(k);
f.setLittleEndian32(r);f.setLittleEndian32(d);f.skipPosition(5);f.markEnd();c.send(f);break;case 3:d.getLittleEndian32();t=d.getLittleEndian64();d.skipPosition(20);f.read(n,dataLen,t,reading,0);break;case 4:p=d.getLittleEndian32();t=d.getLittleEndian64();d.skipPosition(20);d=f.write(n,p,t,d.getBytes(p));f=new hi5.DataBuffer(new Uint8Array(22));f.setByte(3);f.setLittleEndian16(17522);f.setLittleEndian16(18755);f.setLittleEndian32(k);f.setLittleEndian32(r);f.setLittleEndian32(d);f.setLittleEndian32(p);
f.setByte(0);f.markEnd();c.send(f);break;case 5:break;case 6:break;case 10:break;case 12:break;case 14:break;case 17:break;default:svGlobal.logger.warn("Inlvaid IORequest: "+p)}}}};c.attachDevice=function(d){h.push(d);m&&g(d)};c.attachPrinter=function(d,k){k=new q(k);d=new e(d.driver,d.name,d.isDefault,d.isXPS,k);c.attachDevice(d)};c.onagentresp=function(d){};return c};
