var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,e,f){d instanceof String&&(d=String(d));for(var k=d.length,g=0;g<k;g++){var q=d[g];if(e.call(f,q,g,d))return{i:g,v:q}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,e,f){if(d==Array.prototype||d==Object.prototype)return d;d[e]=f.value;return d};$jscomp.getGlobal=function(d){d=["object"==typeof globalThis&&globalThis,d,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var e=0;e<d.length;++e){var f=d[e];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(d,e){var f=$jscomp.propertyToPolyfillSymbol[e];if(null==f)return d[e];f=d[f];return void 0!==f?f:d[e]};
$jscomp.polyfill=function(d,e,f,k){e&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(d,e,f,k):$jscomp.polyfillUnisolated(d,e,f,k))};$jscomp.polyfillUnisolated=function(d,e,f,k){f=$jscomp.global;d=d.split(".");for(k=0;k<d.length-1;k++){var g=d[k];if(!(g in f))return;f=f[g]}d=d[d.length-1];k=f[d];e=e(k);e!=k&&null!=e&&$jscomp.defineProperty(f,d,{configurable:!0,writable:!0,value:e})};
$jscomp.polyfillIsolated=function(d,e,f,k){var g=d.split(".");d=1===g.length;k=g[0];k=!d&&k in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var q=0;q<g.length-1;q++){var t=g[q];if(!(t in k))return;k=k[t]}g=g[g.length-1];f=$jscomp.IS_SYMBOL_NATIVE&&"es6"===f?k[g]:null;e=e(f);null!=e&&(d?$jscomp.defineProperty($jscomp.polyfills,g,{configurable:!0,writable:!0,value:e}):e!==f&&($jscomp.propertyToPolyfillSymbol[g]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(g):$jscomp.POLYFILL_PREFIX+g,g=
$jscomp.propertyToPolyfillSymbol[g],$jscomp.defineProperty(k,g,{configurable:!0,writable:!0,value:e})))};$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(e,f){return $jscomp.findInternal(this,e,f).v}},"es6","es3");svGlobal.DCVC_EXTENSION=svGlobal.DCVC_EXTENSION||{};
svGlobal.DCVC_EXTENSION.DRIVE=function(d){function e(a){for(var c=r.length,b=0;b<c;b++)if(r[b].deviceId==a)return r[b]}function f(a){var c=1+a.getSize();c=new hi5.DataBuffer(new Uint8Array(c));c.setByte(0);a.toBuffer(c);c.markEnd();p.send(c)}function k(a){a.getByte();var c=a.getLittleEndian32(),b=a.getLittleEndian32(),h=a.getUnicodeString(b);a=r.find(function(l){return(l.printName||l.dosName)==h});a.deviceId=c;e(c).operation.attach(c,h,a)}function g(a,c,b,h,l){this.type=4;this.dosName="PRN2";this.operation=
l;this.driverName=a;this.printName=c;this.deviceId=0;b=b?2:0;h&&(b|=16);h=a?2*(a.length+1):0;l=2*(c.length+1);var m=new hi5.DataBuffer(new Uint8Array(24+h+l));m.setLittleEndian32(b);m.skipPosition(8);m.setLittleEndian32(h);m.setLittleEndian32(l);m.skipPosition(4);a&&m.setUnicodeString(a+"\x00");m.setUnicodeString(c+"\x00");this.data=m.getData();this.toBuffer=function(n){n.setLittleEndian32(this.type);n.setLittleEndian32(this.deviceId);n.setAsciiString(this.dosName,8);this.data?(n.setLittleEndian32(this.data.length),
n.setBytes(this.data)):n.setLittleEndian32(0)};this.getSize=function(){var n=20;this.data&&(n+=this.data.length);return n}}function q(a){this.attach=function(c,b,h){c=2+h.getSize();c=new hi5.DataBuffer(new Uint8Array(c));c.setByte(7);c.setByte(1);h.toBuffer(c);c.markEnd();a.onagentmessage(c.getData())};this.ioRequest=function(c){var b=new hi5.DataBuffer(new Uint8Array(2+c.length));b.setByte(7);b.setByte(2);b.setBytes(c);b.markEnd();a.onagentmessage(b.getData())}}function t(a,c){var b=a.name;this.type=
8;this.deviceId=0;this.dosName=8<b.length?a.name.substr(0,8):b;var h=(a.name+"\x00").toUTF8();this.deviceId=0;this.dirHandle=a;this.operation=c;this.toBuffer=function(l){l.setLittleEndian32(8);l.setLittleEndian32(this.deviceId);l.setAsciiString(this.dosName,8);l.setLittleEndian32(h.length);l.setBytes(h)};this.getSize=function(){return 20+h.length}}function x(a){this.attach=function(c,b,h){};this.create=function(c,b,h,l,m,n){};this.close=function(c){};this.read=function(c,b,h,l,m){};this.write=function(c,
b,h,l,m){};this.deviceControl=function(c,b,h,l,m){}}var p=new d;p.name="DRIVESTB";var r=[],u=!1;p.onopen=function(){if(!u&&(u=!0,0<r.length))for(var a=0,c=r.length;a<c;a++)f(r[a])};p.process=function(a){switch(a.getByte()){case 1:k(a);break;case 2:var c=a.getLittleEndian32(),b=e(c).operation;if(b instanceof q)a.skipPosition(-4),c=a.getBytes(a.getEnd()-a.getPosition()),b.ioRequest(c);else{var h=a.getLittleEndian32(),l=a.getLittleEndian32(),m=a.getLittleEndian32();a.getLittleEndian32();switch(m){case 0:m=
a.getBigEndian32();a.skipPosition(8);h=a.getLittleEndian32();var n=a.getLittleEndian32(),y=a.getLittleEndian32(),z=a.getLittleEndian32(),v=a.getLittleEndian32(),w="";0<v&&256>v/2&&(w=a.getUnicodeString(v));a=b.create(m,h,n,y,z,w);b=new hi5.DataBuffer(new Uint8Array(22));b.setByte(3);b.setLittleEndian16(17522);b.setLittleEndian16(18755);b.setLittleEndian32(c);b.setLittleEndian32(l);b.setLittleEndian32(a[0]);b.setLittleEndian32(a[1]);b.setByte(0);b.markEnd();p.send(b);break;case 2:a.skipPosition(32);
a=b.close(h);b=new hi5.DataBuffer(new Uint8Array(22));b.setByte(3);b.setLittleEndian16(17522);b.setLittleEndian16(18755);b.setLittleEndian32(c);b.setLittleEndian32(l);b.setLittleEndian32(a);b.skipPosition(5);b.markEnd();p.send(b);break;case 3:a.getLittleEndian32();n=a.getLittleEndian64();a.skipPosition(20);b.read(h,dataLen,n,reading,0);break;case 4:m=a.getLittleEndian32();n=a.getLittleEndian64();a.skipPosition(20);a=b.write(h,m,n,a.getBytes(m));b=new hi5.DataBuffer(new Uint8Array(22));b.setByte(3);
b.setLittleEndian16(17522);b.setLittleEndian16(18755);b.setLittleEndian32(c);b.setLittleEndian32(l);b.setLittleEndian32(a);b.setLittleEndian32(m);b.setByte(0);b.markEnd();p.send(b);break;case 5:break;case 6:break;case 10:break;case 12:break;case 14:break;case 17:break;default:svGlobal.logger.warn("Inlvaid IORequest: "+m)}}}};p.attachDevice=function(a){r.push(a);u&&f(a)};p.attachPrinter=function(a,c){c=new q(c);a=new g(a.driver,a.name,a.isDefault,a.isXPS,c);p.attachDevice(a)};p.attachDirectory=function(a,
c){c=new x(c);a=new t(a,c);p.attachDevice(a)};p.onagentresp=function(a){};return p};
