svGlobal.FileService=function(k){function t(){var a=b.gateway;b.ongetgatewayaddress&&(a=b.ongetgatewayaddress(a));return a}function u(a){e.send(a)}function x(a){f||(f=new hi5.file.UploadManager(new hi5.file.WsFileService(u),!1),f.enabled=!0,f.canCopyFile=!1,f.addEvent("beforeupload",function(a,d,p){b.beforeupload&&b.beforeupload(a,d,p)}),f.addEvent("fileuploaded",function(a,d,p){if(b.onfileuploaded)b.onfileuploaded(a,d,p)}),f.addEvent("uploaded",function(a,d){if(b.onuploaded)b.onuploaded(a,d)}),f.addEvent("uploadingCancelled",
function(){if(b.onuploadingCancelled)b.onuploadingCancelled()}),a.setFileHandler(f))}function y(a){svGlobal.logger.info("opened...");l=!0;e.send("87"+navigator.userAgent);if(b.onopen)b.onopen()}function z(a){svGlobal.logger.warn(a)}function q(a){svGlobal.logger.warn("closed ...");l||error("connection");document.getElementById("filecontainer").style.display="none";r=l=!1;if(b&&b.onclose)b.onclose(v);try{h&&h.close()}catch(g){}e&&(e.onopen=null,e.onmessage=null,e.onclose=null,e=e.onerror=null);h=m=
null;b&&(b=null);window&&window.$file&&(window.$file=null)}var e=null,l=!1,n=hi5.appcfg||{img:{},toolbar:{fadable:!0}},h=null,f=null,r=!1,v=!1,b=this;this.sessionInfo={domain:"",userName:"",sessionId:0,joinedSessions:[],suppressOutput:!1,appInfo:null};this.loadbalanceToken=n.loadbalanceTokenName?n.loadbalanceTokenName+"="+hi5.tool.uuid():"";this.displayMsg=void 0!=n.displayMsg?n.displayMsg:!0;this.modifyURL=function(a){b.loadbalanceToken&&(a+="&"+b.loadbalanceToken);return a};this.gateway=function(){var a=
k.lastIndexOf("/FILE?");return k.substring(0,a).replace(/wss\:\/\//ig,"https://").replace(/ws\:\/\//ig,"http://")}();svGlobal.logger.warn("Ver:"+svGlobal.version+" build:"+svGlobal.build);var w="/DOWNLOAD?";this.setLinks=function(a){a.download&&(w=a.download)};this.getGatewayAddr=t;this.run=function(){var a=k,g=window.opener;if(g){var d=null;try{d=g.__sparkUser}catch(p){}d&&(g=d.account,d=d.session,g&&(a+="&account="+g),d&&(a+="&session="+d))}a=0==b.mode&&n.wsPost?k.substring(0,k.indexOf("?"))+"?_METHOD=post":
k;a=b.modifyURL(a);(d=hi5.browser.cookie.get("__SV_TOKEN_A"))&&(a+="&__SV_TOKEN_A="+encodeURIComponent(d));e=new WebSocket(a,"file");e.binaryType="arraybuffer";e.onopen=y;e.onclose=q;e.onerror=z;e.onmessage=function(a){a=a.data;var c=parseInt(a.substring(0,2),16);a=a.substring(2);switch(c){case 26:c=JSON.parse(a);if(c.name){svGlobal.logger.info("msg="+a);if(b.onerror)b.onerror(c);a=__svi18n.errorCode["S"+c.name]||"";a+=c.message||c.msg;b.showMessage(a)}else 0<svGlobal.log&&console.erro("No error code for message:"+
a);break;case 56:a=JSON.parse(a);sessionId=a.session;b.sessionInfo.appInfo=a;a.ver&&a.ver!=svGlobal.version&&svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+a.ver);r=!0;if(b.onready)b.onready();if(b.onsessionstart)b.onsessionstart(b.sessionInfo);if(b.onloggedin)b.onloggedin();x(h);a=document.getElementById("filecontainer");a.style.display="block";a.style.margin="2em";h.refreshFiles(!0);window.$file=b;break;case 58:c=a;if(f)if(a=parseInt(c.charAt(0),10),c=c.substring(1),5==a)f.notifyFiles(JSON.parse(c));
else switch(c=c.split("\t"),a){case 1:f.confirmId(c[0],c[1],c[2]);break;case 2:f.read(c[0],parseInt(c[1],10),parseInt(c[2],10));break;case 4:f.close(c[0]);break;case 9:a='<a href="'+c[0]+'" download="'+c[1]+'" target="_blank">'+__svi18n.info.fileReady+"</a>",surfaces.getFocused().showMessage({msg:a,title:__svi18n.info.download})}break;case 62:a:switch(c=parseInt(a.substring(0,1),16),a=a.substring(1),c){case 0:c=JSON.parse(a);restoreVar();l=!0;a=c.width;c=c.height;if(a==widthRdp&&c==heightRdp)break;
setResolution(a,c,!1,!1);break;case 7:c=JSON.parse(a);c.width&&c.height&&setResolution(c.width,c.height,!0,rdpArgs.monitorDef&&0<=rdpArgs.monitor?!0:!1);c.color&&(setBpp(c.color,!0),svGlobal.logger.warn("Color depth changed to:"+c.color));c.version&&(b.sessionInfo.protocolVersion=c.version);break;case 8:c=JSON.parse(a);reqCredential=!0;if(b.onrequestcredential&&b.onrequestcredential(c,m.reconnect))break a;if(b.onautherror&&b.onautherror(c,m.reconnect))break a;surfaces.getFocused().requestCredential(c,
m.reconnect);break;case 12:v=!0}}}};this.showMessage=function(a){b.displayMsg&&a&&hi5.notifications.notify({msg:a})};this.writeRawInput=function(a){if(r){u(a);if(b.onactivity)b.onactivity(a);return!0}return!1};this.getFileUrl=function(a){var g=t(),d=w,e=d.indexOf("://"),g=(0<e&&11>e?d:g+d)+"s="+sessionId+"&f="+a;return b.modifyURL(g)};this.listFiles=function(a,b){f&&r&&f.list(a,b)};var m=new function(a){this.localLockFlags=0;this.checkLockFlags=!0;this.send=a.writeRawInput;this.sendInput=function(b){a.writeRawInput(b)};
this.getAppInfo=function(){return a.sessionInfo.appInfo};this.onresize=function(a){};this.onorientationchange=function(a){};this.onfocus=function(a){};this.getShareFiles=a.listFiles;this.getFile=function(b){var d=a.getFileUrl(b);a.ondownload&&a.ondownload({fileName:b,url:d})||window.open(d)};this.getFileLink=a.getFileUrl;this.getGateway=function(){return k};this.reconnect=function(a,b,e){}}(this);this.addSurface=function(a){h=a;a.setClipboard(!1);a.setReadOnly(!0);a.setController(m);a.setFeature(65552);
a.run(1033)};this.hide=function(){h||h.hide()};this.close=function(){if(e&&l)try{e.send("85"),e.close()}catch(a){}else q()};hi5.browser.isChromeApp?chrome.runtime.onSuspend.addListener(q):window.addEventListener("unload",q,!1)};
