svGlobal.FileService=function(l){function t(){var a=d.gateway;d.ongetgatewayaddress&&(a=d.ongetgatewayaddress(a));return a}function u(a){g.send(a)}function x(a){h||(h=new hi5.file.UploadManager(new hi5.file.WsFileService(u),!1),h.enabled=!0,h.canCopyFile=!1,h.addEvent("beforeupload",function(e,f,b){d.beforeupload&&d.beforeupload(e,f,b)}),h.addEvent("fileuploaded",function(e,f,b){if(d.onfileuploaded)d.onfileuploaded(e,f,b)}),h.addEvent("uploaded",function(e,f){if(d.onuploaded)d.onuploaded(e,f)}),h.addEvent("uploadingCancelled",
function(){if(d.onuploadingCancelled)d.onuploadingCancelled()}),a.setFileHandler(h))}function y(a){svGlobal.logger.info("opened...");m=!0;g.send("87"+navigator.userAgent);if(d.onopen)d.onopen()}function z(a){svGlobal.logger.warn(a)}function q(a){svGlobal.logger.warn("closed ...");m||error("connection");document.getElementById("filecontainer").style.display="none";r=m=!1;if(d&&d.onclose)d.onclose(v);try{k&&k.close()}catch(e){}g&&(g.onopen=null,g.onmessage=null,g.onclose=null,g=g.onerror=null);k=n=
null;d&&(d=null);window&&window.$file&&(window.$file=null)}var g=null,m=!1,p=hi5.appcfg||{img:{},toolbar:{fadable:!0}},k=null,h=null,r=!1,v=!1,d=this;this.sessionInfo={domain:"",userName:"",sessionId:0,joinedSessions:[],suppressOutput:!1,appInfo:null};this.loadbalanceToken=p.loadbalanceTokenName?p.loadbalanceTokenName+"="+hi5.tool.uuid():"";this.displayMsg=void 0!=p.displayMsg?p.displayMsg:!0;this.modifyURL=function(a){d.loadbalanceToken&&(a+="&"+d.loadbalanceToken);return a};this.gateway=function(){var a=
l.lastIndexOf("/FILE?");return l.substring(0,a).replace(/wss:\/\//ig,"https://").replace(/ws:\/\//ig,"http://")}();svGlobal.logger.warn("Ver:"+svGlobal.version+" build:"+svGlobal.build);var w="/DOWNLOAD?";this.setLinks=function(a){a.download&&(w=a.download)};this.getGatewayAddr=t;this.run=function(){var a=l,e=window.opener;if(e){var f=null;try{f=e.__sparkUser}catch(b){}f&&(e=f.account,f=f.session,e&&(a+="&account="+e),f&&(a+="&session="+f))}a=0==d.mode&&p.wsPost?l.substring(0,l.indexOf("?"))+"?_METHOD=post":
l;a=d.modifyURL(a);(f=hi5.browser.cookie.get("__SV_TOKEN_A"))&&(a+="&__SV_TOKEN_A="+encodeURIComponent(f));g=new WebSocket(a,"file");g.binaryType="arraybuffer";g.onopen=y;g.onclose=q;g.onerror=z;g.onmessage=function(b){b=b.data;var c=parseInt(b.substring(0,2),16);b=b.substring(2);switch(c){case 26:c=JSON.parse(b);if(c.name){svGlobal.logger.info("msg="+b);if(d.onerror)d.onerror(c);b=__svi18n.errorCode["S"+c.name]||"";b+=c.message||c.msg;d.showMessage(b)}else 0<svGlobal.log&&console.erro("No error code for message:"+
b);break;case 56:b=JSON.parse(b);sessionId=b.session;d.sessionInfo.appInfo=b;b.ver&&b.ver!=svGlobal.version&&svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+b.ver);r=!0;if(d.onready)d.onready();if(d.onsessionstart)d.onsessionstart(d.sessionInfo);if(d.onloggedin)d.onloggedin();x(k);b=document.getElementById("filecontainer");b.style.display="block";b.style.margin="2em";k.refreshFiles(!0);window.$file=d;break;case 58:c=b;if(h)if(b=parseInt(c.charAt(0),10),c=c.substring(1),5==b)h.notifyFiles(JSON.parse(c));
else switch(c=c.split("\t"),b){case 1:h.confirmId(c[0],c[1],c[2]);break;case 2:h.read(c[0],parseInt(c[1],10),parseInt(c[2],10));break;case 4:h.close(c[0]);break;case 9:b='<a href="'+c[0]+'" download="'+c[1]+'" target="_blank">'+__svi18n.info.fileReady+"</a>",surfaces.getFocused().showMessage({msg:b,title:__svi18n.info.download})}break;case 62:a:switch(c=parseInt(b.substring(0,1),16),b=b.substring(1),c){case 0:c=JSON.parse(b);restoreVar();m=!0;b=c.width;c=c.height;if(b==widthRdp&&c==heightRdp)break;
setResolution(b,c,!1,!1);break;case 7:c=JSON.parse(b);c.width&&c.height&&setResolution(c.width,c.height,!0,rdpArgs.monitorDef&&0<=rdpArgs.monitor?!0:!1);c.color&&(setBpp(c.color,!0),svGlobal.logger.warn("Color depth changed to:"+c.color));c.version&&(d.sessionInfo.protocolVersion=c.version);break;case 8:c=JSON.parse(b);reqCredential=!0;if(d.onrequestcredential&&d.onrequestcredential(c,n.reconnect))break a;if(d.onautherror&&d.onautherror(c,n.reconnect))break a;surfaces.getFocused().requestCredential(c,
n.reconnect);break;case 12:v=!0}}}};this.showMessage=function(a){d.displayMsg&&a&&hi5.notifications.notify({msg:a})};this.writeRawInput=function(a){if(r){u(a);if(d.onactivity)d.onactivity(a);return!0}return!1};this.getFileUrl=function(a){var e=t(),f=w,b=f.indexOf("://");e=(0<b&&11>b?f:e+f)+"s="+sessionId+"&f="+a;return d.modifyURL(e)};this.listFiles=function(a,e){h&&r&&h.list(a,e)};var n=new function(a){this.localLockFlags=0;this.checkLockFlags=!0;this.send=a.writeRawInput;this.sendInput=function(e){a.writeRawInput(e)};
this.getAppInfo=function(){return a.sessionInfo.appInfo};this.onresize=function(e){};this.onorientationchange=function(e){};this.onfocus=function(e){};this.getShareFiles=a.listFiles;this.getFile=function(e){var f=a.getFileUrl(e);a.ondownload&&a.ondownload({fileName:e,url:f})||window.open(f)};this.getFileLink=a.getFileUrl;this.getGateway=function(){return l};this.reconnect=function(e,f,b){}}(this);this.addSurface=function(a){k=a;a.setClipboard(!1);a.setReadOnly(!0);a.setController(n);a.setFeature(65552);
a.run(1033)};this.hide=function(){k||k.hide()};this.close=function(){if(g&&m)try{g.send("85"),g.close()}catch(a){}else q()};hi5.browser.isChromeApp?chrome.runtime.onSuspend.addListener(q):window.addEventListener("unload",q,!1)};
