var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,d,c){if(b){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var f=a[c];f in d||(d[f]={});d=d[f]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,d,c){var f=this.length||0;0>d&&(d=Math.max(0,f+d));if(null==c||c>f)c=f;c=Number(c);0>c&&(c=Math.max(0,f+c));for(d=Number(d||0);d<c;d++)this[d]=a;return this}},"es6-impl","es3");
$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var d=0,c={next:function(){if(d<a.length){var f=d++;return{value:b(f,a[f]),done:!1}}c.next=function(){return{done:!0,value:void 0}};return c.next()}};c[Symbol.iterator]=function(){return c};return c};
$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,d){return[a,d]})}},"es6-impl","es3");var hi5=hi5||{};
hi5.init={inited:!1,funcs:[],push:function(a){hi5.init.funcs.push(a)},start:function(a){if(!hi5.init.inited){hi5.browser.innerHeight=window.innerHeight;hi5.init.inited=!0;a=hi5.init.funcs;for(var b=0,d=a.length;b<d;b++)a[b]();hi5.init.release()}},release:function(){document.removeEventListener("DOMContentLoaded",hi5.init.start,!1)}};
window.requestAnimationFrame||(window.requestAnimationFrame=window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,30,Date.now())});window.URL=window.URL||window.webkitURL;window.WebSocket=window.WebSocket||window.MozWebSocket;hi5.WebSocket=window.WebSocket;hi5.$=function(a){return document.getElementById(a)};
hi5.html={hasClass:function(a,b){return a.classList.contains(b)},addClass:function(a,b){a.classList.add(b)},removeClass:function(a,b){a.classList.remove(b)}};
hi5.browser=new function(){var a=navigator.userAgent;this.innerHeight=0;this.isEdge=-1!=a.indexOf("Edge");var b=(this.isIE=-1!=a.indexOf("MSIE")||-1!=a.indexOf("Trident"))||this.isEdge;this.isTouch="maxTouchPoints"in navigator||"msMaxTouchPoints"in navigator?1<=(navigator.msMaxTouchPoints||navigator.maxTouchPoints):"ontouchstart"in window||"createTouch"in document||"DocumentTouch"in window&&window.document instanceof window.DocumentTouch||-1!=a.indexOf("Mobile");this.isFirefox=-1!=a.indexOf("Firefox")&&
!b;this.isOpera=-1!=a.indexOf("Opera");this.isRIM=-1!=a.indexOf(" RIM ");this.isChrome=-1!=a.indexOf("Chrome")&&!b;this.isMacOS=-1!=a.indexOf("Mac OS");this.isWindows=-1!=a.indexOf("Windows ");this.isiOS=navigator.userAgent.match(/(iPad|iPhone|iPod)/i)?!0:!1;this.isSafari=-1==a.indexOf("Chrome")&&-1!=a.indexOf("Safari")&&!b;this.isWebKit=-1!=a.indexOf("WebKit");this.isCrOS=-1!=a.indexOf("CrOS");this.isOperaNext=-1!=a.indexOf("Edition Next");this.isAndroid=-1!=a.indexOf("Android");this.isChromeApp=
"chrome"in window&&"app"in chrome&&"window"in chrome.app;this.isDesktop=!a.match(/(iPhone|iPod|iPad|Android|BlackBerry|Mobile)/);this.isLinux=-1!=a.indexOf("Linux");this.isElectron=!!(window.process&&process.versions&&process.versions.electron);b=window.outerHeight-window.innerHeight;this.isMetro=0==window.screenY&&(0==window.screenX||window.screenX+window.outerWidth==screen.width)&&3<b&&31>b;this.isMultitask=!(this.isiOS&&this.isSafari&&0<a.indexOf("Version/5"));this.binaryWS=function(){return hi5.browser.isChrome?
!0:hi5.tool.hasProperty(WebSocket,"binaryType")};this.cookie2Obj=function(){var a=document.cookie,f={};if(""==a)return f;for(var e=a.split(";"),b=0,d=e.length;b<d;b++){for(var l=e[b];" "==l.charAt(0);)l=l.substring(1,l.length);a=l.indexOf("=");if(0<a){var g=decodeURIComponent(l.substring(a+1).replace(/\+/g," "));hi5.tool.isNumber(g)&&"0"!=g[0]&&parseFloat(g)==g&&(g=parseFloat(g));if("true"==g||"on"==g)g=!0;else if("false"==g||"off"==g)g=!1;f[l.substring(0,a)]=g}}return f};this.obj2url=function(a){var c=
"",e;for(e in a)c+="&"+e+"=",c="boolean"==typeof a[e]?c+(a[e]?"on":"off"):c+encodeURIComponent(a[e]);c&&(c=c.substring(1));return c};this.getLibPath=function(a){for(var c=document.getElementsByTagName("script"),e,b,d="",l=c.length,g=0;g<l;g++)if(b=c[g].src,e=b.indexOf(a),-1<e){d=b.substring(0,e);break}0==d.indexOf(location.origin)&&(d=d.substring(location.origin.length));return d};this.loadJS=function(a,b){0>a.indexOf("/")&&(a=hi5.libPath+a);if(!hi5.browser.getLibPath(a)){var e=document.createElement("script");
e.type="text/javascript";e.src=a;b&&(e.onload=b,e.onreadystatechange=function(){"complete"==this.readyState&&b()});(document.body||document.getElementsByTagName("script")[0].parentNode).appendChild(e)}};this.formToObj=function(a,b){var e=a.elements,c,f=e.length;b||(b={});for(var d=0;d<f;d++){var g=e[d];if(c=g.name){var m=g.type;switch(m){case "submit":case "button":case "reset":continue;case "checkbox":g=g.checked;break;case "radio":if(!g.checked)continue;g=g.value;break;case "number":parseFloat(g.value);
default:g=g.value}""!=g&&(b[c]=g)}}return b};this.objToForm=function(a,b){var e,c=b.elements,f;for(f in a)if(e=c[f]){var d=a[f];"boolean"==typeof d?e.checked=d:e.value=d}};this.objToCookie=function(a){for(var c in a)""!=a[c]&&(document.cookie=c+"="+a[c])};this.getScale=function(){return document.documentElement.clientWidth/window.innerWidth};this.httpGet=function(a,b){var e=new XMLHttpRequest;e.open("GET",a,b);e.withCredentials=!0;e.setRequestHeader("Content-Type","text/plain;charset=UTF-8");e.send(null);
return e.responseText};this.selectEditable=function(a){try{var c=document.createRange();c.selectNodeContents(a);var e=window.getSelection();e.removeAllRanges();e.addRange(c)}catch(h){console.log(h)}};this.setOrientaionHandler=function(a){"onorientationchange"in screen?screen.onorientationchange=a:"onmozorientationchange"in screen?screen.onmozorientationchange=a:"onmsorientationchange"in screen?screen.onmsorientationchange=a:window.addEventListener("orientationchange",a,!1)};var d={x:0,y:0};this.getMousePos=
function(a,b){var e=(b||a.target).getBoundingClientRect();d.x=a.clientX-e.left;d.y=a.clientY-e.top;return d};this.calMousePos=function(a,b,e){e=e.getBoundingClientRect();d.x=a-e.left;d.y=b-e.top;return d};this.getHost=function(){var a=hi5.tool.queryToObj().gateway;if(!a&&!hi5.browser.isChromeApp)if(a=location.host){var b=location.pathname,e=b.indexOf("://");0<e&&(a+=b.substring(0,b.indexOf("/",e+3)))}else a="localhost";return a};this.html2text=function(a){var b=document.createElement("div");b.innerHTML=
a.replace(/<style([\s\S]*?)<\/style>/g,"");return b.textContent.replace(/\r?\n/g,"\r\n").replace(RegExp("\u00a0","g")," ")};this.dataURLtoBlob=function(a){var b=a.indexOf(","),e=a.substring(0,b++),c=e.indexOf(":"),d=e.indexOf(";",c),d=d>c?e.substring(c+1,d):"text/plain";a=0<e.indexOf("base64",c)?hi5.Base64.dec(a,b,!0):a.substring(b);return new Blob([a],{type:d})};this.blobToArray=function(a,b){var e=new FileReader;e.onloadend=function(a){a.target.readyState==FileReader.DONE&&b(new Uint8Array(a.target.result))};
e.readAsArrayBuffer(a)};this.blobToText=function(a,b){var e=new FileReader;e.onloadend=function(a){a.target.readyState==FileReader.DONE&&b(a.target.result)};e.readAsText(a)};this.loadFlash=function(a,b,e,d,k){d=d||8;k=k||8;e=e||"__sv_flash_plugin";b=b||document.body;var c=document.getElementById(e);if(c)return c;var c=document.createElement("div"),f=c.style;f.position="fixed";f.width=f.height=d+"px";f.bottom=f.left=k+"px";f.overflow="hidden";f.opacity=0;c.innerHTML='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" type="application/x-shockwave-flash" data="'+
a+'" width="'+d+'" height="'+k+'" id="'+e+'"><param name="allowScriptAccess" value="always" /></object>';b.appendChild(c);return c.childNodes[0]};this.getScreenWidth=function(){if(-1==navigator.userAgent.indexOf("MSIE")&&-1==navigator.userAgent.indexOf("Trident")||0<=window.screenX&&window.screenX<screen.width&&0<=window.screenY&&window.screenY<screen.height)return screen.width;for(var a=window.outerWidth,b=[1920,2560,3840,4E3,7680],e=0;5>e;e++)if(a<=b[e])return b[e];return a};this.getScreenHeight=
function(){if(-1==navigator.userAgent.indexOf("MSIE")&&-1==navigator.userAgent.indexOf("Trident")||0<=window.screenX&&window.screenX<screen.width&&0<=window.screenY&&window.screenY<screen.height)return screen.height;for(var a=window.outerHeight,b=[1080,1200,1600,2E3,2160,4320],e=0;5>e;e++)if(a<=b[e])return b[e];return a};this.cookie={set:function(a,b,e){var c=new Date;c.setTime(c.getTime()+864E5*e);e="expires="+c.toUTCString();document.cookie=a+"="+b+";"+e+";path=/"},get:function(a){a+="=";for(var b=
decodeURIComponent(document.cookie).split(";"),e=0;e<b.length;e++){for(var c=b[e];" "==c.charAt(0);)c=c.substring(1);if(0==c.indexOf(a))return c.substring(a.length,c.length)}return""},"delete":function(a){document.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;"}};this.getChildByNameOrId=function(a,b){if(a)for(var e=a.childNodes,c=e.length,d=0;d<c;d++)if(e[d].name==b||e[d].id==b)return e[d];return null}};
hi5.libPath||(hi5.libPath=hi5.browser.getLibPath("hi5core.js")||hi5.browser.getLibPath("hi5.js"),hi5.libPath?hi5.libMin=!1:(hi5.libPath=hi5.browser.getLibPath("hi5core_min.js")||hi5.browser.getLibPath("hi5_min.js"),hi5.libPath&&(hi5.libMin=!0)));
hi5.storage=new function(){function a(a,b){this._state=b||0;this._value=a}function b(a){return a&&0==a.indexOf("{")&&(a=JSON.parse(a))&&"_state"in a&&"_value"in a?a:null}var d="chrome"in window&&!!chrome.storage,c="localStorage"in window;if(c)try{localStorage.setItem("_t_s_t","1"),localStorage.removeItem("_t_s_t")}catch(e){c=this.isAvailable=!1}this.isAvailable=!!d||c;var f=d||!this.isAvailable?{}:localStorage;d&&chrome.storage.local.get(null,function(a){for(var b in a)f[b]=a[b]});this.set=function(b,
c){f[b]=JSON.stringify(new a(c,1))};this.get=function(a){a=f[a];var e=b(a);return e?e._value:a};this.clear=function(a){f={};d?chrome.storage.local.clear(a||function(){}):c&&localStorage.clear()};this.remove=function(a){if(f.removeItem)f.removeItem(a);else{var e=b(f[a]);e&&(e._state=2,f[a]=JSON.stringify(e))}};this.commit=function(a){a=a||function(){};if(d){var e={},c=[],l=!1,g;for(g in f){var m=b(f[g]);m&&(1==m._state?(e[g]=m._value,l=!0):2==m._state&&c.push(g))}0<c.length&&chrome.storage.local.remove(c,
function(){for(var b=0,e=c.length;b<e;b++)delete f[c[b]];a&&a()});l&&chrome.storage.local.set(e,a)}else a()}};
hi5.tool={isNumber:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},cumulativePos:function(a){var b=0,d=0;do if(b+=a.offsetTop||0,d+=a.offsetLeft||0,b+=parseInt(a.style.borderLeftWidth)||0,d+=parseInt(a.style.borderTopWidth)||0,b-=a.scrollTop,d-=a.scrollLeft,a=a.offsetParent,a==document.body)break;while(a);return{x:d,y:b}},getPos:function(a,b){var d=0,c=0;do{if(b&&"static"!=getComputedStyle(a).getPropertyValue("position"))break;d+=a.offsetLeft;c+=a.offsetTop}while(a=a.offsetParent);return{x:d,
y:c}},bytesToSize:function(a){if(isNaN(a))return"";var b=Math.floor(Math.log(+a)/Math.log(2));1>b&&(b=0);b=Math.floor(b/10);a=+a/Math.pow(2,10*b);a.toString().length>a.toFixed(3).toString().length&&(a=a.toFixed(2));return a+" bytes; KB; MB; GB; TB; PB; EB; ZB; YB".split(";")[b]},queryToObj:hi5.string.queryToObj,replaceQuery:function(a,b,d){var c=a.indexOf(b+"="),f=!1;0<c&&(c=a.charAt(c-1),"&"==c||"?"==c)&&(f=!0);return f?a.replace(new RegExp("[\\?&]"+b+"=([^&#]*)"),function(a){return a.charAt(0)+
b+"="+encodeURIComponent(d)}):a+="&"+b+"="+encodeURIComponent(d)},disableInput:function(a){window.__hi5_bk&&hi5.tool.enableInput();var b=document.createElement("div");if(a){var d=window.getComputedStyle(a);b.style.position=d.getPropertyValue("position");b.style.left=d.getPropertyValue("left");b.style.top=d.getPropertyValue("top");b.style.width=d.getPropertyValue("width");b.style.height=d.getPropertyValue("height");b.style.zIndex=d.getPropertyValue("zIndex");b.style.right=d.getPropertyValue("right");
b.style.bottom=d.getPropertyValue("bottom")}else b.style.position="fixed",b.style.left=0,b.style.top=0,b.style.width="100%",b.style.height="100%",b.style.zIndex=99999;b.style.background="url("+hi5.libPath+"spinner.gif) no-repeat center center";a?a.parentNode.appendChild(b):document.body.appendChild(b);window.__hi5_bk=b},enableInput:function(){window.__hi5_bk&&(window.__hi5_bk.parentNode.removeChild(window.__hi5_bk),window.__hi5_bk=null)},scale:function(a,b,d,c,f){c=void 0===c?"left top":c+" "+f;d||
(d=b);a.style.transformOrigin=c;a.style.MozTransformOrigin=c;a.style.webkitTransformOrigin=c;a.style.msTransformOrigin=c;a.style.OTransformOrigin=c;b="scale("+b+","+d+")";a.style.transform=b;a.style.MozTransform=b;a.style.webkitTransform=b;a.style.msTransform=b;a.style.OTransform=b},openWebSocket:function(a,b,d){var c=!1;d&&(d=hi5.callback.put(d),a+="&callback="+d);var f=new WebSocket(a,"ctrl");f.onopen=function(a){c=!0;b&&f.send(b)};f.onclose=function(a){c||alert("Failed to connect")};f.onmessage=
function(a){a=JSON.parse(a.data);f.close();a.callback?hi5.callback.get(a.callback)(a):console.log(a)};return f},getChildNodesByTag:function(a,b){for(var d=a.childNodes,c=[],f=0,e=d.length;f<e;f++)d[f].nodeName.toLowerCase()==b&&c.push(d[f]);return c},hasProperty:function(a,b){return b in a||b in a.prototype?!0:b in(a.__proto__||a.constructor.prototype)},isCapslock:function(a){var b=String.fromCharCode(a.keyCode||a.which);return b.toUpperCase()!=b||b.toLowerCase()==b||a.shiftKey?!1:!0},getImage:function(a,
b){b&&0!=b.indexOf("/")&&(b=hi5.libPath+b);return hi5&&hi5.appcfg&&hi5.appcfg.img?hi5.appcfg.img[a]||b:b},uuid:function(){for(var a="",b=Array(16),d,c=0;16>c;c++)switch(b[c]=255*Math.random()|0,d=b[c].toString(16),1==d.length&&(d="0"+d),c){case 3:case 5:case 7:case 9:a+=d;a+="-";break;case 6:a+="4"+d[1];break;case 8:a+=(parseInt(d[0],16)&3|8).toString(16)+d[1];break;default:a+=d}return a},text2html:function(a){return a.replace(/\n/g,"<br>")},Profiler:function(){function a(){this.totalTime=this.count=
0}var b={},d=0,c=null,f=!1;this.begin=function(e){if(f){c=e;var h=b[e];void 0===h&&(h=new a,b[e]=h);d=(new Date).getTime();return h}};this.end=function(a){if(f){a=b[a||c];var e=(new Date).getTime()-d;a.totalTime+=e;a.count++;return a}};this.start=function(){f||(f=!0,b={},d=0,c=null)};this.stop=function(){f&&(f=!1)};this.isStarted=function(){return f};this.print=function(){console.log(this.getResult())};this.getResult=function(a){var c={},e="undefined"===typeof a?0:a.length,d;for(d in b)0<e&&d.substring(0,
e)!==a||(c[d]=b[d]);return c}},ResponseMonitor:function(a,b){function d(){f&&(a(),e&&(c=setTimeout(b,e)))}var c=0,f=0,e;this.tag=0;this.check=function(a){f&&(clearTimeout(c),c=setTimeout(d,a||f))};this.setInterval=function(a,b){f=1E3*a|0;e=1E3*b|0};this.stop=function(){clearTimeout(c);f=0}}};navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;
hi5.audio={recordable:!!navigator.getUserMedia||!!navigator.mediaDevices,getAudioContext:function(){var a=window.top;if(!a.AudioContext&&!a.webkitAudioContext)return null;a.__audioCtx&&a.__audioCtx.state&&"running"!=a.__audioCtx.state&&(a.__audioCtx.close&&a.__audioCtx.close(),a.__audioCtx=null);a.__audioCtx||(a.__audioCtx=new (a.AudioContext||a.webkitAudioContext));a.__audioCtx.__refCount=a.__audioCtx.__refCount?a.__audioCtx.__refCount+1:1;return a.__audioCtx},downsample:function(a,b){if(1==b)return a;
if(1>b)console.error("rate must be smaller than the original rate");else{for(var d=new Float32Array(Math.round(a.length/b)),c=0,f=0;c<d.length;){for(var e=Math.round((c+1)*b),h=0,k=0;f<e&&f<a.length;f++)h+=a[f],k++;d[c]=h/k;c++;f=e}return d}},releaseAudioContext:function(){var a=window;try{window.parent!=window&&(a=window.parent)}catch(b){}a.__audioCtx&&(a.__audioCtx.__refCount&&a.__audioCtx.__refCount--,!a.__audioCtx.__refCount||1>a.__audioCtx.__refCount)&&(a.__audioCtx.close&&a.__audioCtx.close(),
a.__audioCtx=null)}};hi5.audio.recordable&&(hi5.browser.isChrome||hi5.browser.isSafari)&&"https:"!=document.location.protocol&&"localhost"!=location.hostname&&"127.0.0.1"!=location.hostname&&(hi5.audio.recordable=!1);
hi5.video={webcam:function(){navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices&&navigator.mediaDevices.enumerateDevices().then(function(a){a.forEach(function(a){"videoinput"==a.kind&&(hi5.video.webcam=a)})});return null}(),resolutions:function(a){function b(b){f.video.width.exact=b.width;f.video.height.exact=b.height;navigator.mediaDevices.getUserMedia(f).then(function(d){d=d.getVideoTracks()[0].getSettings().frameRate;c.push({width:b.width,height:b.height,frameRate:d});e--;0==e&&a(c)})["catch"](function(b){e--;
0==e&&a(c)})}for(var d=[{width:1920,height:1080},{width:1280,height:720},{width:1024,height:768},{width:960,height:540},{width:848,height:480},{width:800,height:600},{width:640,height:480},{width:640,height:360},{width:424,height:240},{width:352,height:288},{width:352,height:240},{width:320,height:240},{width:320,height:180}],c=[],f={video:{width:{exact:0},height:{exact:0}}},e=d.length,h=0,k=d.length;h<k;h++)b(d[h])}};
hi5.EventControl=function(a){a.addEvent=function(b,d){a[b]&&a[b]._evt_listeners||(a[b]=function(){a.fireEvent(b,arguments)},a[b]._evt_listeners=[]);a[b]._evt_listeners.push(d)};a.removeEvent=function(b,d){if(!a[b]&&!a[b]._evt_listeners)return!1;var c=a[b]._evt_listeners,f=c.indexOf(d);return-1<f?(c.removeElm(f),!0):!1};a.fireEvent=function(b,d){if(a[b]&&a[b]._evt_listeners){var c=a[b]._evt_listeners;d||(d=[]);for(var f=[],e=0,h=c.length;e<h;e++)f.push(c[e].apply(a,d));return f}};return a};
hi5.ui=hi5.ui||{};hi5.ui.initAs=function(a,b){var d=a["data-h5-ui"];if(!d)return a["data-h5-ui"]=b,!0;if(-1!=hi5.string.seperatedStr.indexOf(d,b))return!1;a["data-h5-ui"]=d+","+b;return!0};hi5.ui.clean=function(a){a["data-h5-ui"]&&(a["data-h5-ui"]="")};hi5.ui.confirm=function(a){return hi5.browser.isChromeApp?!0:confirm(a)};
hi5.ui.addInputListener=function(a,b){var d=!1,c=!1;a.addEventListener("keydown",function(a){console.log("--",a);c&&(c=!1);"Process"==a.key||229==a.keyCode||d||b(a)});a.addEventListener("keyup",function(a){console.log("--",a);"Process"==a.key||229==a.keyCode||d||c||b(a)});a.addEventListener("input",function(a){console.log("--",a);d||c||b(a)});a.addEventListener("compositionstart",function(a){console.log("--start:");d=!0});a.addEventListener("compositionend",function(a){console.log("--end:"+a.data);
d=!1;b(a);c=!0})};hi5.chromeapp={convertLink:function(a){for(var b=0,d=a.length;b<d;b++)a[b].onclick=function(a){a=a.target.href;var b=a.lastIndexOf("/");-1!=b&&(a=a.substring(b+1));chrome.app.window.create(a,{left:window.screenLeft+20,top:window.screenTop+20,width:window.innerWidth,height:window.innerHeight});return!1}}};
hi5.Draggable=function(a,b,d,c,f,e){var h,k;function l(b){p=h=!1;b.stopPropagation();b.preventDefault();var e=b.touchs||b.changedTouches;if(e){if(1!=e.length)return;b=e[0]}else if(0!=b.button)return;n=hi5.tool.getPos(a);k=b.pageX;q=b.pageY;h=!0}function g(b){if(h){var e=b.touchs&&b.touchs[0]||b.changedTouches&&b.changedTouches[0]||b;if(!(3>Math.abs(k-e.pageX)&&3>Math.abs(q-e.pageY))){p||(p=!0,d&&d(e));if(c){var g=c(e);g&&(e=g)}g=n.x+e.pageX-k;e=n.y+e.pageY-q;0>g&&(g=0);g>window.innerWidth-a.offsetWidth&&
(g=window.innerWidth-a.offsetWidth);0>e&&(e=0);e>window.innerHeight-a.offsetHeight&&(e=window.innerHeight-a.offsetHeight);a.style.left=g+"px";a.style.top=e+"px";b.stopPropagation();b.preventDefault()}}}function m(a){h&&(a.preventDefault(),a.stopPropagation(),h=!1,a=a.touchs&&a.touchs[0]||a.changedTouches&&a.changedTouches[0]||a,p?f&&f(a):e&&e(a),p=!1)}b=b||a;b.draggable=!1;if(!hi5.ui.initAs(b,"Draggable"))return b;var n=null;var q=k=0;var p=h=!1;var t=hi5.browser.isTouch;b.addEventListener("touchstart",
l,!1);b.addEventListener("mousedown",l,!1);document.addEventListener("touchmove",g,!1);document.addEventListener("mousemove",g,!1);b.addEventListener("touchmove",g,!1);b.addEventListener("mousemove",g,!1);document.addEventListener("touchend",m,!1);document.addEventListener("mouseup",m,!1);b.addEventListener("touchend",m,!1);b.addEventListener("mouseup",m,!1);t&&(document.addEventListener("touchcancel",m,!1),b.addEventListener("touchcancel",m,!1));return a};
hi5.Fadable=function(a,b,d,c){function f(){document.activeElement==a||document.activeElement==a.activeObj?setTimeout(f,g):a.style.display="none"}function e(){m&&clearTimeout(m);m=setTimeout(function(){a.beforeDisplay&&a.beforeDisplay();a.style.display=c;n&&(m&&clearTimeout(m),m=setTimeout(f,g))},88);return!1}function h(a){m&&clearTimeout(m)}function k(a){e()}if(!hi5.ui.initAs(a,"Fadable"))return a;0>a.tabIndex&&(a.tabIndex=999);var l=d||document;c=c||"block";var g=b||3E3,m=0,n=!0;a.setFadable=function(b){(n=
b)?(b="mouseup",navigator.pointerEnabled?b="pointerup":navigator.msPointerEnabled?b="MSPointerUp":hi5.browser.isTouch&&(b="touchend"),l.addEventListener(b,e,!1),l.addEventListener("mouseup",e,!1),a.addEventListener("mouseenter",h,!1),a.addEventListener("mouseleave",k,!1)):(a.style.display=c,a.removeEventListener("mouseenter",h,!1),a.removeEventListener("mouseleave",k,!1))};a.startFade=e;return a};
hi5.cancelDefault=function(a){a.preventDefault&&a.preventDefault();a.stopPropagation&&a.stopPropagation();return!1};
hi5.Toolbar=function(a,b,d){if(b){var c=(b=a.querySelector("#svImgHandle"))||document.createElement("img");b||(c.style.cursor="move",c.style.width="11px",c.src=d,c.id="svImgHandle",a.appendChild(c));hi5.Draggable(a,c)}a.addButton=function(b,e,c){var d=document.createElement("img");d.src=b;hi5.browser.isTouch?navigator.msMaxTouchPoints||d.addEventListener("touchend",e,!1):d.addEventListener("click",e,!1);d.className="h5-img-btn";a.appendChild(d);c&&(d.id=c,d.name=c);return d};a.getButton=function(b){for(var e=
a.getElementsByTagName("img"),c=e.length,d=0;d<c;d++)if(e[d].id==b||e[d].name==b)return e[d];return null};a.removeButton=function(b){for(var e=a.getElementsByTagName("img"),c=e.length,d=0;d<c;d++)if(e[d].id==b||e[d].name==b){a.removeChild(e[d]);break}};d=a.getElementsByTagName("img");b=d.length;for(c=0;c<b;c++)d[c].className="h5-img-btn";return a};
hi5.ProgressBar=function(a){a.progress=0;a.maxValue=0;var b=a.getElementsByTagName("div")[0];a.setProgress=function(d){d=Math.floor(d/a.maxValue*100);d!=a.progress&&(a.progress=d,b.style.width=d/100*a.offsetWidth+"px")};return a};
hi5.Lightbox=function(a,b,d,c){function f(){var b=(e.clientWidth-a.offsetWidth)/2,c=(e.clientHeight-a.offsetHeight)/3;0>b&&(b=0);0>c&&(c=0);a.style.left=b+"px";a.style.top=c+"px"}var e=document.createElement("div");e.id="divBackground";e.style.position="fixed";e.style.left=0;e.style.top=0;e.style.width="100%";e.style.height="100%";e.style.zIndex=999;e.style.backgroundColor=d?d:"#222";b||(b=.4);1>b&&(e.style.opacity=b);a.style.position="absolute";a.style.zIndex=1E3;a.style.visibility="hidden";var h=
document.createElement("img");h.width=25;h.height=25;h.src=hi5.tool.getImage("del","del.png");h.className="h5-img-btn";h.style.cursor="pointer";h.align="top";h.style.position="absolute";c?(h.style.top="-20px",h.style.right="-15px"):(h.style.top="0px",h.style.right="0px");a.resize=f;a.show=function(){document.body.appendChild(e);a.appendChild(h);a.style.display="block";a.style.visibility="visible";f();if(a.onopen)a.onopen(a)};a.visible=function(){return a&&"visible"==a.style.visibility};a.dismiss=
function(b){function c(){document.body.removeChild(e);a.removeChild(h);a.style.display="none";a.style.visibility="hidden";if(a.onclose)a.onclose()}"number"==typeof b?setTimeout(c,b):c()};a.background=e;h.addEventListener("click",a.dismiss,!1);return a};
hi5.ui.Lightbox=function(a,b){function d(){var b=(window.innerWidth-a.clientWidth)/2|0,e=(window.innerHeight-a.clientHeight)/3|0;a.style.borderWidth=e+"px "+b+"px "+2*e+"px "+b+"px"}function c(a){27==a.keyCode&&f()}function f(){var b=a.style;b.boxSizing=e.boxSizing;b.top=e.top;b.left=e.left;b.borderWidth=e.borderWidth;b.borderColor=e.borderColor;b.borderStyle=e.borderStyle;b.zIndex=e.zIndex;b.position=e.position;b.display=e.display;b.opacity=e.opacity;h=!1;k&&a.removeChild(k);document.removeEventListener("keydown",
c,!1);l&&l.onclose&&(l.onclose(),l=null)}var e=null,h=!1;b=b||{};void 0==b.backgroundColor&&(b.backgroundColor="#333");void 0==b.zIndex&&(b.zIndex=999);void 0==b.opacity&&(b.opacity=.9);var k=null;!0!==b.noClose&&(k=document.createElement("img"),k.width=25,k.height=25,k.src=hi5.tool.getImage("del","del.png"),k.className="h5-img-btn",k.style.cursor="pointer",k.align="top",k.style.position="absolute",b.close?(k.style.top=b.close.top,k.style.right=b.close.right):(k.style.top=0,k.style.right=0));this.resize=
d;var l=null;this.show=function(){var g=a.style;l=this;e={boxSizing:g.boxSizing,position:g.position,top:g.top,left:g.left,borderWidth:g.borderWidth,borderColor:g.borderColor,display:g.display,zIndex:g.zIndex,borderStyle:g.borderStyle,opacity:g.opacity};g.boxSizing="content-box";g.position="absolute";g.display="block";g.borderStyle="solid";g.borderColor=b.backgroundColor;g.top=0;g.left=0;g.zIndex=b.zIndex;g.opacity=b.opacity;d();window.addEventListener("resize",d,!1);h=!0;k&&a.appendChild(k);document.addEventListener("keydown",
c,!1);if(this.onopen)this.onopen()};this.visible=function(){return h};this.dismiss=f;k&&k.addEventListener("click",f,!1)};
hi5.ui.LightboxWithBtn=function(a,b){function d(){var b=(window.innerWidth-a.clientWidth)/2|0,e=(window.innerHeight-a.clientHeight)/3|0;a.style.borderWidth=e+"px "+b+"px "+2*e+"px "+b+"px"}function c(a){27==a.keyCode&&f()}function f(){var b=a.style;b.boxSizing=e.boxSizing;b.top=e.top;b.left=e.left;b.borderWidth=e.borderWidth;b.borderColor=e.borderColor;b.borderStyle=e.borderStyle;b.zIndex=e.zIndex;b.position=e.position;b.display=e.display;b.opacity=e.opacity;h=!1;a.removeChild(k);document.removeEventListener("keydown",
c,!1);l&&l.onclose&&(l.onclose(),l=null)}var e=null,h=!1;b=b||{};void 0==b.backgroundColor&&(b.backgroundColor="#333");void 0==b.zIndex&&(b.zIndex=999);void 0==b.opacity&&(b.opacity=.9);var k=document.createElement("button");k.innerHTML="Continue";k.style="float: right";this.resize=d;var l=null;this.show=function(){var f=a.style;l=this;e={boxSizing:f.boxSizing,position:f.position,top:f.top,left:f.left,borderWidth:f.borderWidth,borderColor:f.borderColor,display:f.display,zIndex:f.zIndex,borderStyle:f.borderStyle,
opacity:f.opacity};f.boxSizing="content-box";f.position="absolute";f.display="block";f.borderStyle="solid";f.borderColor=b.backgroundColor;f.top=0;f.left=0;f.zIndex=b.zIndex;f.opacity=b.opacity;d();window.addEventListener("resize",d,!1);h=!0;a.appendChild(k);document.addEventListener("keydown",c,!1);if(this.onopen)this.onopen()};this.visible=function(){return h};this.dismiss=f;k.addEventListener("click",f)};
hi5.canvas={TextSelect:function(a,b,d,c,f){f||(f=a.canvas.width-1);b--;this.clear=function(){a.clearRect(0,0,a.canvas.width,a.canvas.height)};this.draw=function(e,c,k,l){l>c?l-c<b&&(l=c+b):c-l<b&&(l=c-b);a.fillStyle=d||"#61D2D6";a.beginPath();a.moveTo(e,c);a.lineTo(f,c);a.lineTo(f,l-b);a.lineTo(k,l-b);a.lineTo(k,l);a.lineTo(0,l);a.lineTo(0,c+b);a.lineTo(e,c+b);a.lineTo(e,c);a.fill()}}};
hi5.DataTable=function(a){if(hi5.ui.initAs(a,"DataTable")){hi5.EventControl(a);"string"==typeof a&&(a=JSON.parse(a));var b=a.rows,d=a.cols;a.rowNo=-1;a.beforeGetValue=null;a.moveTo=function(b){a.rowNo=b};a.getColNo=function(a){for(var b=0,e=d.length;b<e;b++)if(d[b].name==a)return b;return-1};a.getValue=function(c){var d=b[a.rowNo][c];return a.beforeGetValue?a.beforeGetValue(c,d):d};a.setValue=function(c,d){a.beforeSetValue&&(d=a.beforeSetValue(c,d));b[a.rowNo][c]=d;a.fireEvent("onchange",[c,a.rowNo,
d])};a.first=function(){a.moveTo(0)};a.next=function(){a.moveTo(a.rowNo+1)};a.last=function(){a.moveTo(b.length-1)};a.hasNext=function(){return a.rowNo<b.length-1};a.remove=function(c){c||(c=a.rowNo);var d=[c];a.fireEvent("beforeremove",d);b.splice(c,1);a.fireEvent("onremove",d)};a.perform=function(b){"function"==typeof a[b]?a[b].apply(a):a.fireEvent("onaction",[b])};a.getObject=function(){for(var b={},f=0,e=d.length;f<e;f++)b[d[f].name]=a.getValue(f);return b};a.find=function(a,d){for(var e=0,c=
b.length;e<c;e++)if(b[e][a]==d)return b[e];return null};a.sort=function(b){a.cols[b].sortDir=void 0==a.cols[b].sortDir?-1:-a.cols[b].sortDir;var c=a.cols[b].sortDir;a.rows.length&&(a.rows.sort(function(a,d){return a[b]>d[b]?c:a[b]<d[b]?-c:0}),a.fireEvent("reload"))}}a.fireEvent("onopen");return a};
hi5.DataGrid=function(a,b){function d(b){var e=this.rowIndex;"number"==typeof e&&(f=e-=a.tHead.rows.length,c.moveTo(e));if(a.onrowclick)a.onrowclick(b)}if(!hi5.ui.initAs(a,"DataGrid"))return a;if("TABLE"!=a.nodeName)throw"Not HTML Table";var c=null;a.onrowclick=null;Object.defineProperty(a,"dataTable",{get:function(){return c},set:function(b){c=b;c.addEvent("reload",function(){a.fillData(c)})},enumerable:!0,configurable:!0});var f=-1;a.getValue=function(a){var b=c;b.moveTo(f);return b.getValue(b.getColNo(a))};
a.fillData=function(e){var c=e.rows,h=a.tBodies[0],k;a._rowTemp||(a._rowTemp=a.tBodies[0].rows[0].cloneNode(!0));var l=a._rowTemp;var p=l.cells.length,t=h.cloneNode(!1);var w=c.length;for(k=0;k<w;k++){var r=l.cloneNode(!0);var v=r.cells;e.moveTo(k);for(c=0;c<p;c++)if(!v[c].innerHTML){var u=e.getValue(c);a.beforeDisplayValue&&(u=a.beforeDisplayValue(c,u));b?v[c].innerText=u:v[c].innerHTML=u}f=k;r.addEventListener("click",d,!1);a.beforeAppendRow&&a.beforeAppendRow(r);t.appendChild(r)}a.removeChild(h);
a.appendChild(t)};a.open=function(){c&&(a.fillData(c),c.addEvent("onremove",function(b){var e=a.tBodies[0];(b=e.rows[b])&&e.removeChild(b)}))};a.clear=function(){if(a._rowTemp){a.removeChild(a.tBodies[0]);var b=document.createElement("tbody");b.appendChild(a._rowTemp);a.appendChild(b)}};for(var e=a.tHead.rows[0].cells,h=e.length,k=0;k<h;k++)e[k].addEventListener("click",function(a){c&&c.sort(a.target.cellIndex)},!1);return a};
hi5.Select=function(a,b,d){if(!hi5.ui.initAs(a,"Select"))return a;var c=a.parentNode,f=document.createElement("div");f.style.padding="0";f.style.display="inline";c.insertBefore(f,a);var e=document.createElement("img");e.src=hi5.tool.getImage("select","select.png");e.height=a.offsetHeight;e.style.verticalAlign="-6px";f.appendChild(a);f.appendChild(e);var h=document.createElement("select");b&&(h.multiple=!0,d||(d=","));c=a.getAttribute("hi5_size");h.size=c?c:10;if(c=a.getAttribute("hi5_list"))if(c=
c.split(";"),f=c.length,0<f)for(var k=h.options,l=0;l<f;l++)k[l]=new Option(c[l]);h.style.position="absolute";h.style.zIndex=99999;h.style.display="none";document.body.appendChild(h);a.show=function(){a.beforedropdown&&a.beforedropdown(a);h.style.display="";h.focus()};a.hide=function(){h.style.display="none";a.focus()};e.onclick=function(){if("none"==h.style.display){if(0==h.options.length){var b=a.getAttribute("onfetchlist");b&&eval(b)}b=hi5.tool.getPos(a,!1);h.style.left=b.x+"px";h.style.top=b.y+
a.offsetHeight+"px";h.style.width=a.offsetWidth+e.width+3+"px";a.show()}else a.hide()};h.onchange=function(){if(b){for(var e=[],c,f=h.options,k=0,l=f.length;k<l;k++)c=f[k],c.selected&&e.push(c.value);a.value=e.join(d)}else a.value=h.value,h.style.display="none";if(a.onchange)a.onchange()};a.options=h.options;return a};hi5.init.push(function(){for(var a=document.getElementsByClassName("Hi5Select"),b=a.length,d=0;d<b;d++)new hi5.Select(a[d])});
hi5.Tab=function(a){function b(b){var c=e;e!=b&&(h[e].className="tab_back",k[e].className="tab_hide",e=b);h[b].className="tab_front";k[b].className="tab_show";h[b].focus();c!=b&&a.fireEvent("ontabchange",[b,c])}function d(a){a=h.indexOf(a.target);-1!=a&&b(a)}if(!hi5.ui.initAs(a,"Tab"))return a;hi5.EventControl(a);for(var c=a.getElementsByClassName("tab")[0].getElementsByClassName("tab_title")[0].childNodes,f=c.length,e=0,h=[],k=[],l=0;l<f;l++){var g=c[l];"SPAN"==g.nodeName.toUpperCase()&&(g.className=
"tab_back",g.onclick=d,g.onfocus=d,h[h.length]=g)}c=a.getElementsByClassName("tab_body")[0].childNodes;f=c.length;for(l=0;l<f;l++)g=c[l],"DIV"==g.nodeName.toUpperCase()&&(k[k.length]=g,g.className="tab_hide");b(e);a.setSelected=b;a.getSelected=function(){return e};return a};hi5.init.push(function(){for(var a=document.getElementsByClassName("tab_all"),b=a.length,d=0;d<b;d++)new hi5.Tab(a[d])});
hi5.Notification=function(a){function b(){a||(a=hi5.$("hi5_notifer_all"),a||(a=document.createElement("div"),a.name=a.id="hi5_notifer_all",document.body.appendChild(a)));return a}function d(a){var e=new c(a);b().appendChild(e);a.select&&(a=e.getElementsByClassName("hi5_notifer_msg")[0],"TEXTAREA"==a.nodeName?a.select():hi5.browser.selectEditable(a))}function c(a){function b(a,b){var e=document.createElement("span");e.className=b;e.onclick=function(b){a.apply(c,[b])};return e}var c=document.createElement("div");
c.className="hi5_notifer slideUp";c.title=a.title;c.message=a.msg;c.msgCount=1;a.name&&(c.msgName=a.name);var e=document.createElement("div");e.className="hi5_notifer_title";var g=document.createElement("span");g.className="hi5_notifer_icon";e.appendChild(g);e.appendChild(document.createTextNode(c.title));c.appendChild(e);var e=document.createElement("div"),m="text/plain"==a.format?document.createElement("textarea"):document.createElement("div");m.className="hi5_notifer_msg";m.style.width="100%";
m.innerHTML=a.msg;e.appendChild(m);var n=document.createElement("span");n.className="hi5_notifer_count";c.setCount=function(a){c.msgCount=a;n.innerHTML=1<a?"("+c.msgCount+")":""};a.count&&c.setCount(a.count);e.appendChild(n);c.setMessage=function(a){c.message=a;m.innerHTML=a};c.appendChild(e);a.cbNo&&c.appendChild(b(a.cbNo,"hi5_notifer_button_no"));a.cbYes&&c.appendChild(b(a.cbYes,"hi5_notifer_button_yes"));c.destroy=function(){if(c.parentNode){c.parentNode.removeChild(c);var b=f.notifyPool.shift();
if(b)d(b);else if(f.onempty&&0==f.notifySize())f.onempty();a.cbClose&&a.cbClose()}};if(a.timeout){var q=setTimeout(function(){c.destroy()},a.timeout);c.addEventListener("mouseover",function(){clearTimeout(q)},!1)}a.onclick?c.onclick=a.onclick:a.cbYes||a.cbNo||(c.onclick=c.destroy);return c}this.notifyPool=[];var f=this;this.notify=function(a){var c;a="string"==typeof a?{msg:a,title:"",count:1,type:0}:a;a.title||(a.title="");a.count||(a.count=1);if(!f.onnotify||!f.onnotify(a)){var e=hi5.tool.getChildNodesByTag(b(),
"div"),l=e.length;if(0<l)if(3==a.type)for(c=l;0<c;){c--;var g=e[c];if(g.msgName==a.name){g.message!=a.msg?(g.setMessage(a.msg),g.setCount(1)):g.setCount(g.msgCount+1);return}}else if(g=e[l-1],!g.msgName&&g.title==a.title&&g.message==a.msg){g.setCount(g.msgCount+1);return}if(3>l)d(a);else{c=f.notifyPool;g=c.length;if(0<g)if(3==a.type)for(;0<g;)g--,c[g].name==a.name&&(c[g].msg!=a.msg?(c[g].msg=a.msg,c[g].count=0):c[g].count++);else if(g=c[g-1],!g.name&&g.title==a.title&&g.msg==a.msg){g.count++;return}c.push(a)}}};
this.notifySize=function(){return hi5.tool.getChildNodesByTag(b(),"div").length};this.clearAll=function(){f.notifyPool.length=0;for(var a=b();a.hasChildNodes();)a.removeChild(a.firstChild)}};hi5.notifications=new hi5.Notification;
hi5.file={readAsArrayBuffer:function(a,b){var d=new FileReader;d.onloadend=function(a){b(new Uint8Array(a.target.result))};d.readAsArrayBuffer(a)},getEntries:function(a){var b=a.target&&(a.target.webkitEntries||a.target.entries||[]);if(!b.length&&(a=a.dataTransfer&&a.dataTransfer.items))for(var d=0,c;c=a[d];++d)if("file"==c.kind){if(!c.webkitGetAsEntry&&!c.getAsEntry)break;c=c.getAsEntry?c.getAsEntry():c.webkitGetAsEntry();if(!c)break;b.push(c)}return b},getFilesFromEntries:function(a,b){function d(){e--;
e||b(h)}function c(a){return function(b){b.fullPath=a;h.push(b);d()}}function f(a){var b=a.length;e+=b;for(var g=0;g<b;g++){var h=a[g];h.isFile?h.file(c(h.fullPath),function(a){console.log(a);d()}):h.isDirectory&&h.createReader().readEntries(function(a){a.length&&f(a);d()},function(){d()})}}var e=0,h=[];f(a)},DirectoryReader:function(a){function b(a,b){var c=a.createReader(),d=[],e=function(){c.readEntries(function(a){a.length?(d=d.concat(Array.prototype.slice.call(a||[],0)),e()):b(d)})};e()}function d(a){for(var e=
0,f=a.length;e<f;e++){var k=a[e];k.isFile?k.file(function(a){return function(b){c.onfile(b,a)}}(k.fullPath)):k.isDirectory&&b(k,function(a){d(a)})}}var c=this;this.start=function(){d(a)}},UploadManager:function(a){var b={},d=0,c=a;this.canCopyFile=!1;this.enabled=!0;hi5.EventControl(this);var f=this,e=null,h=0,k=!0,l=!0,g=!1;this.setDownload=function(a){k=a};this.setUpload=function(a){l=a};this.release=function(){b=c=a=f=null};this.read=function(c,e,h){var g=b[b[c]];if("undefined"!=typeof g&&!(1>
g.size&&__svi18n.file.zero)){var k=g.slice(e,e+h),l=new FileReader;l.onloadend=function(b){b.target.readyState==FileReader.DONE&&(b=new Uint8Array(b.target.result),a.send(c,e,h,b,g.preferPaste),d+=h,f.fireEvent("progress",[d]))};l.readAsArrayBuffer(k)}};this.mkdirs=function(b){f.enabled&&("/"!=b.charAt(b.length-1)&&(b+="/"),a.start([b],0,!0))};this.addFiles=function(c,e){var d=c.length;if(d&&f.enabled&&l){g=e&&f.canCopyFile;var k=[];h=Date.now();for(var m=0;m<d;m++){var n=c[m];g&&(n.preferPaste=!0);
var r=n.fullPath||n.name;-1==f.fireEvent("beforeupload",[n,r,g]).indexOf(!0)&&(k.push(c[m]),r=encodeURIComponent(r),b[r]=n)}0<k.length?(a.start(k,g),f.fireEvent("uploadstarted",[g])):f.fireEvent("uploaded",[g,{size:0,duration:0}])}};this.removeFile=function(a,b){c.remove(a,b)};this.confirmId=function(a,c,e){b[a]=c;e&&(d+=parseInt(e))};this.close=function(a,c){var e=g,k={size:d,duration:Date.now()-h,cancelled:c};if(a){var l=b[a];l&&(e=b[l].preferPaste||!1,delete b[a],delete b[l],l=decodeURIComponent(l),
f.fireEvent("fileuploaded",[l,e&&f.canCopyFile,k]));for(var m in b)return}else b={};h=d=0;f.fireEvent("uploaded",[e&&f.canCopyFile,k])};this.cancelAll=function(){c.cancelAll();f.fireEvent("uploadingCancelled");f.close(null,!0)};this.list=function(a,b){e=b;c.list(a)};this.notifyFiles=function(a){e&&e(a);f.fireEvent("files")};this.download=function(){k&&c.download()}},WsFileService:function(a){function b(b,c,f){var e=c.length,d=new Uint8Array(2+2*e);d[0]=58;d[1]=f?b|128:b;f=2;for(var k=0;k<e;k++)b=
c.charCodeAt(k),d[f++]=b&255,d[f++]=b>>8&255;a(d.buffer)}this.start=function(b,c,f){for(var e=b.length,d=20*e+2,k=0,l=new Uint8Array(8),g=2,m,n,q,p;k<e;k++)d=f?d+2*(encodeURIComponent(b[k]).length+1):d+2*(encodeURIComponent(b[k].fullPath||b[k].name).length+1);d=new Uint8Array(d);d[0]=58;d[1]=0;c&&(d[1]|=128);for(k=0;k<e;k++){c=f?0:b[k].size;d[g++]=c&255;d[g++]=c>>8&255;d[g++]=c>>16&255;d[g++]=c>>24&255;4294967296>c?g+=4:(m=hi5.NumUtils.splitInt64(c).high,d[g++]=m&255,d[g++]=m>>8&255,d[g++]=m>>16&
255,d[g++]=m>>24&255);f||hi5.NumUtils.toBytes(b[k].lastModified||b[k].lastModifiedDate.getTime(),l);d.set(l,g);g+=12;m=encodeURIComponent(f?b[k]:b[k].fullPath||b[k].name);n=m.length;for(q=0;q<n;q++)p=m.charCodeAt(q),d[g++]=p&255,d[g++]=p>>8&255;g+=2;svGlobal.logger.info("upload file: "+m+" size:"+c)}a(d.buffer)};this.send=function(b,c,f,e,h){svGlobal.logger.debug("send file, id:"+b+" offset:"+c+" len:"+f);var d=new Uint8Array(22+f);d[0]=58;d[1]=3;h&&(d[1]|=128);h=2;d[h++]=b&255;d[h++]=b>>8&255;d[h++]=
b>>16&255;d[h++]=b>>24&255;d[h++]=c&255;d[h++]=c>>8&255;d[h++]=c>>16&255;d[h++]=c>>24&255;4294967296>c?h+=4:(c=hi5.NumUtils.splitInt64(c).high,d[h++]=c&255,d[h++]=c>>8&255,d[h++]=c>>16&255,d[h++]=c>>24&255);d[h++]=f&255;d[h++]=f>>8&255;d[h++]=f>>16&255;d[h++]=f>>24&255;d.set(e,h+4);a(d.buffer)};this.remove=function(a,c){b(6,a,c)};this.list=function(a){b(5,a)};this.cancelAll=function(){b(7,"")};this.download=function(){b(136,"")}}};
hi5.Chat=function(a,b){function d(a,b,c){var d=document.createElement("span");d.className=b;d.innerHTML=a;c.appendChild(d);return d}function c(){var a=e.value;k.add(a,b);e.value="";if(k.onchat)k.onchat(a,b)}var f=hi5.$("chatHistory"),e=hi5.$("chatText"),h=hi5.$("chatSend"),k=this;this.add=function(c,e){var g=document.createElement("div");d((e||b)+":","chatFrom",g);d(c,"chatMsg",g);var h=new Date;d(h.getHours()+":"+h.getMinutes()+":"+h.getSeconds(),"chatTime",g);"block"!=a.style.display&&(a.style.display=
"block");f.appendChild(g);f.scrollTop=f.scrollHeight};e.addEventListener("keydown",function(a){13==a.keyCode&&c()},!1);h.addEventListener("click",c,!1)};document.addEventListener("DOMContentLoaded",hi5.init.start,!1);
