var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,h){if(a==Array.prototype||a==Object.prototype)return a;a[e]=h.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var e=0;e<a.length;++e){var h=a[e];if(h&&h.Math==Math)return h}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,e){var h=$jscomp.propertyToPolyfillSymbol[e];if(null==h)return a[e];h=a[h];return void 0!==h?h:a[e]};$jscomp.polyfill=function(a,e,h,b){e&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,e,h,b):$jscomp.polyfillUnisolated(a,e,h,b))};
$jscomp.polyfillUnisolated=function(a,e,h,b){h=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var d=a[b];if(!(d in h))return;h=h[d]}a=a[a.length-1];b=h[a];e=e(b);e!=b&&null!=e&&$jscomp.defineProperty(h,a,{configurable:!0,writable:!0,value:e})};
$jscomp.polyfillIsolated=function(a,e,h,b){var d=a.split(".");a=1===d.length;b=d[0];b=!a&&b in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var c=0;c<d.length-1;c++){var f=d[c];if(!(f in b))return;b=b[f]}d=d[d.length-1];h=$jscomp.IS_SYMBOL_NATIVE&&"es6"===h?b[d]:null;e=e(h);null!=e&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:e}):e!==h&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(b,d,{configurable:!0,writable:!0,value:e})))};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(e,h,b){var d=this.length||0;0>h&&(h=Math.max(0,d+h));if(null==b||b>d)b=d;b=Number(b);0>b&&(b=Math.max(0,d+b));for(h=Number(h||0);h<b;h++)this[h]=e;return this}},"es6","es3");$jscomp.typedArrayFill=function(a){return a?a:Array.prototype.fill};$jscomp.polyfill("Int8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Uint8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint8ClampedArray.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Float32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Float64Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.arrayIteratorImpl=function(a){var e=0;return function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var e=function(d,c){this.$jscomp$symbol$id_=d;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};e.prototype.toString=function(){return this.$jscomp$symbol$id_};var h=0,b=function(d){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new e("jscomp_symbol_"+(d||"")+"_"+h++,d)};return b},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var e="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),h=0;h<e.length;h++){var b=$jscomp.global[e[h]];"function"===typeof b&&"function"!=typeof b.prototype[a]&&$jscomp.defineProperty(b.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,e){a instanceof String&&(a+="");var h=0,b=!1,d={next:function(){if(!b&&h<a.length){var c=h++;return{value:e(c,a[c]),done:!1}}b=!0;return{done:!0,value:void 0}}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(e,h){return[e,h]})}},"es6","es3");var hi5=hi5||{};
hi5.init={inited:!1,funcs:[],push:function(a){hi5.init.funcs.push(a)},start:function(a){if(!hi5.init.inited){hi5.browser.innerHeight=window.innerHeight;hi5.init.inited=!0;a=hi5.init.funcs;for(var e=0,h=a.length;e<h;e++)a[e]();hi5.init.release()}},release:function(){document.removeEventListener("DOMContentLoaded",hi5.init.start,!1)}};
window.requestAnimationFrame||(window.requestAnimationFrame=window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,30,Date.now())});window.URL=window.URL||window.webkitURL;window.WebSocket=window.WebSocket||window.MozWebSocket;hi5.WebSocket=window.WebSocket;hi5.$=function(a){return document.getElementById(a)};
hi5.html={hasClass:function(a,e){return a.classList.contains(e)},addClass:function(a,e){a.classList.add(e)},removeClass:function(a,e){a.classList.remove(e)}};
hi5.browser=new function(){var a=navigator.userAgent;this.innerHeight=0;this.isEdge=-1!=a.indexOf("Edge");var e=(this.isIE=-1!=a.indexOf("MSIE")||-1!=a.indexOf("Trident"))||this.isEdge;this.isTouch="maxTouchPoints"in navigator||"msMaxTouchPoints"in navigator?1<=(navigator.msMaxTouchPoints||navigator.maxTouchPoints):"ontouchstart"in window||"createTouch"in document||"DocumentTouch"in window&&window.document instanceof window.DocumentTouch||-1!=a.indexOf("Mobile");this.isFirefox=-1!=a.indexOf("Firefox")&&
!e;this.isOpera=-1!=a.indexOf("Opera");this.isRIM=-1!=a.indexOf(" RIM ");this.isChrome=-1!=a.indexOf("Chrome")&&!e;this.isMacOS=-1!=a.indexOf("Mac OS");this.isWindows=-1!=a.indexOf("Windows ");this.isiOS=navigator.userAgent.match(/(iPad|iPhone|iPod)/i)?!0:!1;this.isSafari=-1==a.indexOf("Chrome")&&-1!=a.indexOf("Safari")&&!e;this.isWebKit=-1!=a.indexOf("WebKit");this.isCrOS=-1!=a.indexOf("CrOS");this.isOperaNext=-1!=a.indexOf("Edition Next");this.isAndroid=-1!=a.indexOf("Android");this.isChromeApp=
"chrome"in window&&"app"in chrome&&"window"in chrome.app;this.isDesktop=!a.match(/(iPhone|iPod|iPad|Android|BlackBerry|Mobile)/);this.isLinux=-1!=a.indexOf("Linux");this.isElectron=!!(window.process&&process.versions&&process.versions.electron);e=window.outerHeight-window.innerHeight;this.isMetro=0==window.screenY&&(0==window.screenX||window.screenX+window.outerWidth==screen.width)&&3<e&&31>e;this.isMultitask=!(this.isiOS&&this.isSafari&&0<a.indexOf("Version/5"));this.binaryWS=function(){return hi5.browser.isChrome?
!0:hi5.tool.hasProperty(WebSocket,"binaryType")};this.cookie2Obj=function(){var b=document.cookie,d={};if(""==b)return d;for(var c=b.split(";"),f=0,g=c.length;f<g;f++){for(var l=c[f];" "==l.charAt(0);)l=l.substring(1,l.length);b=l.indexOf("=");if(0<b){var k=decodeURIComponent(l.substring(b+1).replace(/\+/g," "));hi5.tool.isNumber(k)&&"0"!=k[0]&&parseFloat(k)==k&&(k=parseFloat(k));if("true"==k||"on"==k)k=!0;else if("false"==k||"off"==k)k=!1;d[l.substring(0,b)]=k}}return d};this.obj2url=function(b){var d=
"",c;for(c in b)d+="&"+c+"=",d="boolean"==typeof b[c]?d+(b[c]?"on":"off"):d+encodeURIComponent(b[c]);d&&(d=d.substring(1));return d};this.getLibPath=function(b){for(var d=document.getElementsByTagName("script"),c,f,g="",l=d.length,k=0;k<l;k++)if(f=d[k].src,c=f.indexOf(b),-1<c){g=f.substring(0,c);break}0==g.indexOf(location.origin)&&(g=g.substring(location.origin.length));return g};this.getJS=function(b){for(var d=document.getElementsByTagName("script"),c,f,g=d.length,l="/"==b[0],k=0;k<g;k++)if(f=
d[k].src,c=f.indexOf(b),-1!=c&&(l||"/"==f[c-1]))return d[k];return null};this.loadJS=function(b,d,c){0>b.indexOf("/")&&(b=hi5.libPath+b);var f=hi5.browser.getJS(b);if(f)return f;f=document.createElement("script");f.type="text/javascript";d&&(f.onload=d,f.onreadystatechange=function(){"complete"==this.readyState&&d()});c&&(f.onerror=c);(document.currentScript?document.currentScript.parentNode:document.head||document.body).appendChild(f);f.src=b;return f};this.formToObj=function(b,d){b=b.elements;var c,
f=b.length;d||(d={});for(var g=0;g<f;g++){var l=b[g];if(c=l.name){var k=l.type;switch(k){case "submit":case "button":case "reset":continue;case "checkbox":l=l.checked;break;case "radio":if(!l.checked)continue;l=l.value;break;case "number":parseFloat(l.value);default:l=l.value}""!==l&&(d[c]=l)}}return d};this.objToForm=function(b,d){var c=d.elements,f;for(f in b)if(d=c[f]){var g=b[f];"boolean"==typeof g?d.checked=g:d.value=g}};this.objToCookie=function(b){for(var d in b)""!=b[d]&&(document.cookie=
d+"="+b[d])};this.getScale=function(){return document.documentElement.clientWidth/window.innerWidth};this.httpGet=function(b,d){var c=new XMLHttpRequest;c.open("GET",b,d);c.withCredentials=!0;c.setRequestHeader("Content-Type","text/plain;charset=UTF-8");c.send(null);return c.responseText};this.selectEditable=function(b){try{var d=document.createRange();d.selectNodeContents(b);var c=window.getSelection();c.removeAllRanges();c.addRange(d)}catch(f){console.log(f)}};this.setOrientaionHandler=function(b){"onorientationchange"in
screen?screen.onorientationchange=b:"onmozorientationchange"in screen?screen.onmozorientationchange=b:"onmsorientationchange"in screen?screen.onmsorientationchange=b:window.addEventListener("orientationchange",b,!1)};var h={x:0,y:0};this.getMousePos=function(b,d){d=(d||b.target).getBoundingClientRect();h.x=b.clientX-d.left;h.y=b.clientY-d.top;return h};this.calMousePos=function(b,d,c){c=c.getBoundingClientRect();h.x=b-c.left;h.y=d-c.top;return h};this.getHost=function(){var b=hi5.tool.queryToObj().gateway;
if(!b&&!hi5.browser.isChromeApp)if(b=location.host){var d=location.pathname,c=d.indexOf("://");0<c&&(b+=d.substring(0,d.indexOf("/",c+3)))}else b="localhost";return b};this.html2text=function(b){var d=document.createElement("div");b=b.replace(/<style([\s\S]*?)<\/style>/g,"");b=b.replace(/<\/p>/g,"</p>\r\n");b=b.replace(/<br\s?\/?>/,"\r\n");d.innerHTML=b;return d.textContent.replace(/\u00a0/g," ")};this.dataURLtoBlob=function(b){var d=b.indexOf(","),c=b.substring(0,d++),f=c.indexOf(":"),g=c.indexOf(";",
f);g=g>f?c.substring(f+1,g):"text/plain";b=0<c.indexOf("base64",f)?hi5.Base64.dec(b,d,!0):b.substring(d);return new Blob([b],{type:g})};this.blobToArray=function(b,d){var c=new FileReader;c.onloadend=function(f){f.target.readyState==FileReader.DONE&&d(new Uint8Array(f.target.result))};c.readAsArrayBuffer(b)};this.blobToText=function(b,d){var c=new FileReader;c.onloadend=function(f){f.target.readyState==FileReader.DONE&&d(f.target.result)};c.readAsText(b)};this.loadFlash=function(b,d,c,f,g){f=f||8;
g=g||8;c=c||"__sv_flash_plugin";d=d||document.body;var l=document.getElementById(c);if(l)return l;l=document.createElement("div");var k=l.style;k.position="fixed";k.width=k.height=f+"px";k.bottom=k.left=g+"px";k.overflow="hidden";k.opacity=0;l.innerHTML='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" type="application/x-shockwave-flash" data="'+b+'" width="'+f+'" height="'+g+'" id="'+c+'"><param name="allowScriptAccess" value="always" /></object>';d.appendChild(l);return l.childNodes[0]};
this.getScreenWidth=function(){if(-1==navigator.userAgent.indexOf("MSIE")&&-1==navigator.userAgent.indexOf("Trident")||0<=window.screenX&&window.screenX<screen.width&&0<=window.screenY&&window.screenY<screen.height)return screen.width;for(var b=window.outerWidth,d=[1920,2560,3840,4E3,7680],c=0;5>c;c++)if(b<=d[c])return d[c];return b};this.getScreenHeight=function(){if(-1==navigator.userAgent.indexOf("MSIE")&&-1==navigator.userAgent.indexOf("Trident")||0<=window.screenX&&window.screenX<screen.width&&
0<=window.screenY&&window.screenY<screen.height)return screen.height;for(var b=window.outerHeight,d=[1080,1200,1600,2E3,2160,4320],c=0;5>c;c++)if(b<=d[c])return d[c];return b};this.cookie={set:function(b,d,c){var f=new Date;f.setTime(f.getTime()+864E5*c);c="expires="+f.toUTCString();document.cookie=b+"="+d+";"+c+";path=/"},get:function(b){b+="=";for(var d=decodeURIComponent(document.cookie).split(";"),c=0;c<d.length;c++){for(var f=d[c];" "==f.charAt(0);)f=f.substring(1);if(0==f.indexOf(b))return f.substring(b.length,
f.length)}return""},delete:function(b){document.cookie=b+"=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;"}};this.getChildByNameOrId=function(b,d){if(b){b=b.childNodes;for(var c=b.length,f=0;f<c;f++)if(b[f].name==d||b[f].id==d)return b[f]}return null};this.launchApp=function(b,d,c){function f(r){r=Date.now()-n;m?k&&clearTimeout(k):777>r&&(clearTimeout(q),m=!0)}function g(r){m&&(k=setTimeout(function(){l();d()},300))}function l(){window.removeEventListener("blur",f);window.removeEventListener("focus",
g)}var k,m=!1;window.focus();window.addEventListener("blur",f);window.addEventListener("focus",g);var n=Date.now();location.href=b;var q=setTimeout(function(){l();c&&c()},777)};this.initDialog=function(b,d){b.addEventListener("cancel",function(){b.returnValue=""});var c=b.querySelector("form");if(c){var f=c.querySelector('button[name="cancel"]');f&&(f.onclick=function(){b.close("")});c.onsubmit=function(g){g.preventDefault();g=c.elements;for(var l="",k=0,m=g.length;k<m;k++){var n=g[k];n.value&&(l+=
n.name+"="+encodeURIComponent(n.value))}b.close(l)};b.addEventListener("close",function(){d&&d(b.returnValue)})}}};hi5.libPath||(hi5.libPath=hi5.browser.getLibPath("hi5core.js")||hi5.browser.getLibPath("hi5.js"),hi5.libPath?hi5.libMin=!1:(hi5.libPath=hi5.browser.getLibPath("hi5core_min.js")||hi5.browser.getLibPath("hi5_min.js"),hi5.libPath&&(hi5.libMin=!0)));
hi5.storage=new function(){function a(c,f){this._state=f||0;this._value=c}function e(c){return c&&0==c.indexOf("{")&&(c=JSON.parse(c))&&"_state"in c&&"_value"in c?c:null}var h="chrome"in window&&!!chrome.storage,b="localStorage"in window;if(b)try{localStorage.setItem("_t_s_t","1"),localStorage.removeItem("_t_s_t")}catch(c){b=this.isAvailable=!1}this.isAvailable=!!h||b;var d=h||!this.isAvailable?{}:localStorage;h&&chrome.storage.local.get(null,function(c){for(var f in c)d[f]=c[f]});this.set=function(c,
f){d[c]=JSON.stringify(new a(f,1))};this.get=function(c){c=d[c];var f=e(c);return f?f._value:c};this.clear=function(c){d={};h?chrome.storage.local.clear(c||function(){}):b&&localStorage.clear()};this.remove=function(c){if(d.removeItem)d.removeItem(c);else{var f=e(d[c]);f&&(f._state=2,d[c]=JSON.stringify(f))}};this.commit=function(c){c=c||function(){};if(h){var f={},g=[],l=!1,k;for(k in d){var m=e(d[k]);m&&(1==m._state?(f[k]=m._value,l=!0):2==m._state&&g.push(k))}0<g.length&&chrome.storage.local.remove(g,
function(){for(var n=0,q=g.length;n<q;n++)delete d[g[n]];c&&c()});l&&chrome.storage.local.set(f,c)}else c()}};
hi5.tool={isNumber:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},cumulativePos:function(a){var e=0,h=0;do if(e+=a.offsetTop||0,h+=a.offsetLeft||0,e+=parseInt(a.style.borderLeftWidth)||0,h+=parseInt(a.style.borderTopWidth)||0,e-=a.scrollTop,h-=a.scrollLeft,a=a.offsetParent,a==document.body)break;while(a);return{x:h,y:e}},getPos:function(a,e){return a.getBoundingClientRect()},bytesToSize:function(a){if(isNaN(a))return"";var e=Math.floor(Math.log(+a)/Math.log(2));1>e&&(e=0);e=Math.floor(e/10);
a=+a/Math.pow(2,10*e);a.toString().length>a.toFixed(3).toString().length&&(a=a.toFixed(2));return a+" bytes; KB; MB; GB; TB; PB; EB; ZB; YB".split(";")[e]},queryToObj:hi5.string.queryToObj,replaceQuery:function(a,e,h){var b=a.indexOf(e+"="),d=!1;0<b&&(b=a.charAt(b-1),"&"==b||"?"==b)&&(d=!0);return d?a.replace(new RegExp("[\\?&]"+e+"=([^&#]*)"),function(c){return c.charAt(0)+e+"="+encodeURIComponent(h)}):a+="&"+e+"="+encodeURIComponent(h)},disableInput:function(a){window.__hi5_bk&&hi5.tool.enableInput();
var e=document.createElement("div");if(a){var h=window.getComputedStyle(a);e.style.position=h.getPropertyValue("position");e.style.left=h.getPropertyValue("left");e.style.top=h.getPropertyValue("top");e.style.width=h.getPropertyValue("width");e.style.height=h.getPropertyValue("height");e.style.zIndex=h.getPropertyValue("zIndex");e.style.right=h.getPropertyValue("right");e.style.bottom=h.getPropertyValue("bottom")}else e.style.position="fixed",e.style.left=0,e.style.top=0,e.style.width="100%",e.style.height=
"100%",e.style.zIndex=99999;e.style.background="url("+hi5.libPath+"spinner.gif) no-repeat center center";a?a.parentNode.appendChild(e):document.body.appendChild(e);window.__hi5_bk=e},enableInput:function(){window.__hi5_bk&&(window.__hi5_bk.parentNode.removeChild(window.__hi5_bk),window.__hi5_bk=null)},scale:function(a,e,h,b,d){b=void 0===b?"left top":b+" "+d;h||(h=e);a.style.transformOrigin=b;a.style.MozTransformOrigin=b;a.style.webkitTransformOrigin=b;a.style.msTransformOrigin=b;a.style.OTransformOrigin=
b;e="scale("+e+","+h+")";a.style.transform=e;a.style.MozTransform=e;a.style.webkitTransform=e;a.style.msTransform=e;a.style.OTransform=e},openWebSocket:function(a,e,h){var b=!1;if(h){var d=hi5.callback.put(h);a+="&callback="+d}var c=new WebSocket(a,"ctrl");c.onopen=function(f){b=!0;e&&c.send(e)};c.onclose=function(f){b||alert("Failed to connect")};c.onmessage=function(f){f=JSON.parse(f.data);c.close();f.callback?hi5.callback.get(f.callback)(f):h(f)};return c},scanAnyGood:function(a,e,h){for(var b=
!1,d=a.length,c=0,f=a.length;c<f;c++){var g=new WebSocket(a[c]);g.onopen=function(){b||(b=!0,e(this.url));this.close()};g.onerror=function(){d--;b||0!=d||h()}}},getChildNodesByTag:function(a,e){a=a.childNodes;for(var h=[],b=0,d=a.length;b<d;b++)a[b].nodeName.toLowerCase()==e&&h.push(a[b]);return h},hasProperty:function(a,e){return e in a||e in a.prototype?!0:e in(a.__proto__||a.constructor.prototype)},isCapslock:function(a){var e=String.fromCharCode(a.keyCode||a.which);return e.toUpperCase()!=e||
e.toLowerCase()==e||a.shiftKey?!1:!0},getImage:function(a,e){e&&0!=e.indexOf("/")&&(e=hi5.libPath+e);return hi5&&hi5.appcfg&&hi5.appcfg.img?hi5.appcfg.img[a]||e:e},uuid:function(){for(var a="",e=Array(16),h,b=0;16>b;b++)switch(e[b]=255*Math.random()|0,h=e[b].toString(16),1==h.length&&(h="0"+h),b){case 3:case 5:case 7:case 9:a+=h;a+="-";break;case 6:a+="4"+h[1];break;case 8:a+=(parseInt(h[0],16)&3|8).toString(16)+h[1];break;default:a+=h}return a},text2html:function(a){return a.replace(/\n/g,"<br>")},
Profiler:function(){function a(){this.totalTime=this.count=0}var e={},h=0,b=null,d=!1;this.begin=function(c){if(d){b=c;var f=e[c];void 0===f&&(f=new a,e[c]=f);h=(new Date).getTime();return f}};this.end=function(c){if(d){c=e[c||b];var f=(new Date).getTime()-h;c.totalTime+=f;c.count++;return c}};this.start=function(){d||(d=!0,e={},h=0,b=null)};this.stop=function(){d&&(d=!1)};this.isStarted=function(){return d};this.print=function(){console.log(this.getResult())};this.getResult=function(c){var f={},
g="undefined"===typeof c?0:c.length,l;for(l in e)0<g&&l.substring(0,g)!==c||(f[l]=e[l]);return f}},ResponseMonitor:function(a,e){function h(){d&&(a(),c&&(b=setTimeout(e,c)))}var b=0,d=0,c;this.tag=0;this.check=function(f){d&&(clearTimeout(b),b=setTimeout(h,f||d))};this.setInterval=function(f,g){d=1E3*f|0;c=1E3*g|0};this.stop=function(){clearTimeout(b);d=0}}};navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;
hi5.audio={recordable:!!navigator.getUserMedia||!!navigator.mediaDevices,playable:!(!window.AudioContext&&!window.webkitAudioContext),_resumeListener:function(a){hi5.audio.__audioCtx&&"suspended"===hi5.audio.__audioCtx.state&&hi5.audio.__audioCtx.resume();document.removeEventListener("click",hi5.audio._resumeListener,!1)},__audioCtx:null,getAudioContext:function(){return window.AudioContext?new AudioContext:window.webkitAudioContext?new webkitAudioContext:null},downsample:function(a,e){if(1==e)return a;
for(var h=Math.round(a.length/e),b=new Float32Array(h),d=0;d<h;d++)b[d]=a[d*e|0];return b},releaseAudioContext:function(){hi5.audio.__audioCtx&&(hi5.audio.__audioCtx.__refCount&&hi5.audio.__audioCtx.__refCount--,!hi5.audio.__audioCtx.__refCount||1>hi5.audio.__audioCtx.__refCount)&&(hi5.audio.__audioCtx.close&&hi5.audio.__audioCtx.close(),hi5.audio.__audioCtx=null)},Recorder:function(a){function e(v){n=!0;v.getAudioTracks()[0].getSettings().sampleRate&&(k=v.getAudioTracks()[0].getSettings().sampleRate,
console.log("ctx sampleRate:"+a.sampleRate+" settings:"+v.getAudioTracks()[0].getSettings().sampleRate));m=k/r.nSamplesPerSec;if(l.onopen)l.onopen(!0);w=new MSGSMEncoder;c=v;f=a.createMediaStreamSource(v);var x=1==r.formatTag;g=a.createScriptProcessor?a.createScriptProcessor(1024,1,1):a.createJavaScriptNode(1024,1,1);var y=null,z=null;x&&!y&&(y=new Int16Array(2*Math.round(1024/m)),z=new Uint8Array(y.buffer));g.onaudioprocess=function(A){if(d){A=A.inputBuffer.getChannelData(0);var C=A.length;if(x){var E=
0;if(1==m)for(var u=0;u<C;u++){var B=32767*A[u];y[E++]=B;y[E++]=B}else{var D=p(A,m);C=D.length;4*C!=z.length&&console.log("errr len");for(u=0;u<C;u++)B=32767*D[u],y[E++]=B,y[E++]=B}_recorder.ondata(z,z.length)}else t.addData(A,m);A.fill(0)}};f.connect(g);g.connect(a.destination)}function h(v){d=n=!1;if(l.onopen)l.onopen(!1);svGlobal.logger.warn("Error on getUserMedia: "+v)}function b(){d||(c&&c.getTracks&&c.getTracks()[0].stop(),g&&g.disconnect(),f&&f.disconnect(),n=!1)}var d=!1,c=null,f=null,g=null,
l=this,k=a.sampleRate,m=k/22050,n=!1,q=0;l=this;var r=null,w=null,p=hi5.audio.downsample;this.start=function(v,x){r=v;t.init(65*Math.round(x/2/160));q&&clearTimeout(q);if(!n)navigator.mediaDevices?navigator.mediaDevices.getUserMedia({audio:!0}).then(e).catch(h):navigator.getUserMedia({audio:!0},e,h);else if(l.onopen)l.onopen(!0);d=!0};this.stop=function(){d=!1};this.close=function(){d=!1;t&&t.reset();w=new MSGSMEncoder;q=setTimeout(b,3E5)};var t=new function(){function v(u){for(var B=z/160|0,D=0;D<
B;D++){var F=w.encode(u,y,E,A);A+=F;A==C&&(A=0,l.ondata(E,C));y+=160;z-=160}x=0<z?u:null}var x=null,y=0,z=0,A=0,C=65*Math.floor(Math.floor(Math.floor(4096/m)/160)/2),E=new Uint8Array(C);this.init=function(u){C=Math.max(u,65);console.log("nSingle:"+C);E=new Uint8Array(C);svGlobal.logger.info("rec buffer size: "+u)};this.reset=function(){z=y=A=0;x=null};this.addData=function(u,B){u=p(u,B);if(0==z)z=u.length,y=0,v(u);else{B=z+u.length;var D=new Float32Array(B);D.set(x.subarray(y));D.set(u,z);y=0;z=B;
v(D)}}}},WorkletRecorder:function(a,e){function h(k){var m=a.sampleRate;k.getAudioTracks()[0].getSettings().sampleRate&&(m=k.getAudioTracks()[0].getSettings().sampleRate,console.log("ctx sampleRate:"+a.sampleRate+" settings:"+k.getAudioTracks()[0].getSettings().sampleRate));m/=f.nSamplesPerSec;if(this.onopen)this.onopen(!0);c=k;d=a.createMediaStreamSource(k);var n=1==f.formatTag;k=0;g&&(n?k=g*f.nChannels:(k=65*Math.round(g/2/160),65>k&&(k=65)));n=new window.AudioWorkletNode(a,"sv_record_worklet");
n.port.onmessage=function(q){this.ondata(q.data,q.data.length)}.bind(this);console.log("set node parameter");d.connect(n);n.connect(a.destination);n.port.postMessage({type:"start",rate:m,formatTag:f.formatTag,length:k})}function b(k){c=null;if(this.onopen)this.onopen(!1);svGlobal.logger.warn("Error on getUserMedia: "+k)}var d=null,c=null,f=null,g=0,l=null;a.audioWorklet.addModule(e).then(function(){console.log("loading complete: "+e)});this.start=function(k,m){console.log("xxx start");f=k;g=m;navigator.mediaDevices?
navigator.mediaDevices.getUserMedia({audio:!0}).then(h.bind(this)).catch(b.bind(this)):navigator.getUserMedia({audio:!0},h,b)};this.stop=function(){console.log("xxx stop");l&&(l.port.postMessage({type:"stop"}),l.disconnect());c&&c.getTracks&&c.getTracks()[0].stop();d&&d.disconnect();d=c=l=null};this.close=function(){console.log("xxx close");this.stop()}}};
hi5.audio.recordable&&(hi5.browser.isChrome||hi5.browser.isSafari)&&"https:"!=document.location.protocol&&"localhost"!=location.hostname&&"127.0.0.1"!=location.hostname&&(hi5.audio.recordable=!1);navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices().then(function(a){hi5.audio.recordable&&(hi5.audio.recordable=a.some(function(e){return"audioinput"==e.kind}))}).catch(function(a){});
hi5.video={webcam:function(){navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices&&navigator.mediaDevices.enumerateDevices().then(function(a){a.forEach(function(e){"videoinput"==e.kind&&(hi5.video.webcam=e)})});return null}(),resolutions:function(a){function e(l){d.video.width.exact=l.width;d.video.height.exact=l.height;navigator.mediaDevices.getUserMedia(d).then(function(k){k=k.getVideoTracks()[0].getSettings().frameRate;b.push({width:l.width,height:l.height,frameRate:k});c--;0==c&&a(b)}).catch(function(k){c--;
0==c&&a(b)})}for(var h=[{width:1920,height:1080},{width:1280,height:720},{width:1024,height:768},{width:960,height:540},{width:848,height:480},{width:800,height:600},{width:640,height:480},{width:640,height:360},{width:424,height:240},{width:352,height:288},{width:352,height:240},{width:320,height:240},{width:320,height:180}],b=[],d={video:{width:{exact:0},height:{exact:0}}},c=h.length,f=0,g=h.length;f<g;f++)e(h[f])}};
hi5.EventControl=function(a){a.addEvent=function(e,h){a[e]&&a[e]._evt_listeners||(a[e]=function(){a.fireEvent(e,arguments)},a[e]._evt_listeners=[]);a[e]._evt_listeners.push(h)};a.removeEvent=function(e,h){if(!a[e]&&!a[e]._evt_listeners)return!1;e=a[e]._evt_listeners;h=e.indexOf(h);return-1<h?(e.removeElm(h),!0):!1};a.fireEvent=function(e,h){if(a[e]&&a[e]._evt_listeners){e=a[e]._evt_listeners;h||(h=[]);for(var b=[],d=0,c=e.length;d<c;d++)b.push(e[d].apply(a,h));return b}};return a};
hi5.ui=hi5.ui||{};hi5.ui.initAs=function(a,e){var h=a["data-h5-ui"];if(!h)return a["data-h5-ui"]=e,!0;if(-1!=hi5.string.seperatedStr.indexOf(h,e))return!1;a["data-h5-ui"]=h+","+e;return!0};hi5.ui.clean=function(a){a["data-h5-ui"]&&(a["data-h5-ui"]="")};hi5.ui.confirm=function(a){return hi5.browser.isChromeApp?!0:confirm(a)};
hi5.ui.addInputListener=function(a,e){var h=!1,b=!1;a.addEventListener("keydown",function(d){console.log("--",d);b&&(b=!1);"Process"==d.key||229==d.keyCode||h||e(d)});a.addEventListener("keyup",function(d){console.log("--",d);"Process"==d.key||229==d.keyCode||h||b||e(d)});a.addEventListener("input",function(d){console.log("--",d);h||b||e(d)});a.addEventListener("compositionstart",function(d){console.log("--start:");h=!0});a.addEventListener("compositionend",function(d){console.log("--end:"+d.data);
h=!1;e(d);b=!0})};hi5.chromeapp={convertLink:function(a){for(var e=0,h=a.length;e<h;e++)a[e].onclick=function(b){b=b.target.href;var d=b.lastIndexOf("/");-1!=d&&(b=b.substring(d+1));chrome.app.window.create(b,{left:window.screenLeft+20,top:window.screenTop+20,width:window.innerWidth,height:window.innerHeight});return!1}}};
hi5.Draggable=function(a,e,h,b,d,c){var f,g;function l(p){r=f=!1;var t=p.touchs||p.changedTouches;if(t){if(1!=t.length)return;p=t[0]}else if(0!=p.button)return;n=hi5.tool.getPos(a);g=p.pageX;q=p.pageY;f=!0}function k(p){if(f&&(p=p.touchs&&p.touchs[0]||p.changedTouches&&p.changedTouches[0]||p,!(3>Math.abs(g-p.pageX)&&3>Math.abs(q-p.pageY)))){r||(r=!0,h&&h(p));if(b){var t=b(p);t&&(p=t)}t=n.x+p.pageX-g;p=n.y+p.pageY-q;0>t&&(t=0);t>window.innerWidth-a.offsetWidth&&(t=window.innerWidth-a.offsetWidth);
0>p&&(p=0);p>window.innerHeight-a.offsetHeight&&(p=window.innerHeight-a.offsetHeight);a.style.left=t+"px";a.style.top=p+"px"}}function m(p){f&&(f=!1,p=p.touchs&&p.touchs[0]||p.changedTouches&&p.changedTouches[0]||p,r?d&&d(p):c&&c(p),r=!1)}e=e||a;e.draggable=!1;if(!hi5.ui.initAs(e,"Draggable"))return e;var n=null;var q=g=0;var r=f=!1;var w=hi5.browser.isTouch;e.addEventListener("touchstart",l,!1);e.addEventListener("mousedown",l,!1);document.addEventListener("touchmove",k,!1);document.addEventListener("mousemove",
k,!1);e.addEventListener("touchmove",k,!1);e.addEventListener("mousemove",k,!1);document.addEventListener("touchend",m,!1);document.addEventListener("mouseup",m,!1);e.addEventListener("touchend",m,!1);e.addEventListener("mouseup",m,!1);w&&(document.addEventListener("touchcancel",m,!1),e.addEventListener("touchcancel",m,!1));return a};
hi5.Fadable=function(a,e,h,b){function d(){document.activeElement==a||document.activeElement==a.activeObj?setTimeout(d,k):a.style.display="none"}function c(){m&&clearTimeout(m);m=setTimeout(function(){a.beforeDisplay&&a.beforeDisplay();a.style.display=b;n&&(m&&clearTimeout(m),m=setTimeout(d,k))},88);return!1}function f(q){m&&clearTimeout(m)}function g(q){c()}if(!hi5.ui.initAs(a,"Fadable"))return a;0>a.tabIndex&&(a.tabIndex=999);var l=h||document;b=b||"block";var k=e||3E3,m=0,n=!0;a.setFadable=function(q){(n=
q)?(q="mouseup",navigator.pointerEnabled?q="pointerup":navigator.msPointerEnabled?q="MSPointerUp":hi5.browser.isTouch&&(q="touchend"),l.addEventListener(q,c,!1),l.addEventListener("mouseup",c,!1),a.addEventListener("mouseenter",f,!1),a.addEventListener("mouseleave",g,!1)):(a.style.display=b,a.removeEventListener("mouseenter",f,!1),a.removeEventListener("mouseleave",g,!1))};a.startFade=c;return a};
hi5.cancelDefault=function(a){a.preventDefault&&a.preventDefault();a.stopPropagation&&a.stopPropagation();return!1};
hi5.Toolbar=function(a,e,h){if(e){var b=(e=a.querySelector("#svImgHandle"))||document.createElement("img");e||(b.style.cursor="move",b.style.width="11px",b.src=h,b.id="svImgHandle",a.appendChild(b));hi5.Draggable(a,b)}a.addButton=function(d,c,f){var g=document.createElement("img");g.src=d;hi5.browser.isTouch?navigator.msMaxTouchPoints||g.addEventListener("touchend",c,!1):g.addEventListener("click",c,!1);g.className="h5-img-btn";a.appendChild(g);f&&(g.id=f,g.name=f);return g};a.getButton=function(d){for(var c=
a.getElementsByTagName("img"),f=c.length,g=0;g<f;g++)if(c[g].id==d||c[g].name==d)return c[g];return null};a.removeButton=function(d){for(var c=a.getElementsByTagName("img"),f=c.length,g=0;g<f;g++)if(c[g].id==d||c[g].name==d){a.removeChild(c[g]);break}};h=a.getElementsByTagName("img");e=h.length;for(b=0;b<e;b++)h[b].className="h5-img-btn";return a};
hi5.ProgressBar=function(a){a.progress=0;a.maxValue=0;var e=a.getElementsByTagName("div")[0];a.setProgress=function(h){h=Math.floor(h/a.maxValue*100);h!=a.progress&&(a.progress=h,e.style.width=h/100*a.offsetWidth+"px")};return a};
hi5.Lightbox=function(a,e,h,b){function d(){var g=(c.clientWidth-a.offsetWidth)/2,l=(c.clientHeight-a.offsetHeight)/3;0>g&&(g=0);0>l&&(l=0);a.style.left=g+"px";a.style.top=l+"px"}var c=document.createElement("div");c.id="divBackground";c.style.position="fixed";c.style.left=0;c.style.top=0;c.style.width="100%";c.style.height="100%";c.style.zIndex=999;c.style.backgroundColor=h?h:"#222";e||(e=.4);1>e&&(c.style.opacity=e);a.style.position="absolute";a.style.zIndex=1E3;a.style.visibility="hidden";var f=
document.createElement("img");f.width=25;f.height=25;f.src=hi5.tool.getImage("del","del.png");f.className="h5-img-btn";f.style.cursor="pointer";f.align="top";f.style.position="absolute";b?(f.style.top="-20px",f.style.right="-15px"):(f.style.top="0px",f.style.right="0px");a.resize=d;a.show=function(){document.body.appendChild(c);a.appendChild(f);a.style.display="block";a.style.visibility="visible";d();if(a.onopen)a.onopen(a)};a.visible=function(){return a&&"visible"==a.style.visibility};a.dismiss=
function(g){function l(){document.body.removeChild(c);a.removeChild(f);a.style.display="none";a.style.visibility="hidden";if(a.onclose)a.onclose()}"number"==typeof g?setTimeout(l,g):l()};a.background=c;f.addEventListener("click",a.dismiss,!1);return a};
hi5.ui.Lightbox=function(a,e){function h(){var k=(window.innerWidth-a.clientWidth)/2|0,m=(window.innerHeight-a.clientHeight)/3|0;a.style.borderWidth=m+"px "+k+"px "+2*m+"px "+k+"px"}function b(k){27==k.keyCode&&d()}function d(){var k=a.style;k.boxSizing=c.boxSizing;k.top=c.top;k.left=c.left;k.borderWidth=c.borderWidth;k.borderColor=c.borderColor;k.borderStyle=c.borderStyle;k.zIndex=c.zIndex;k.position=c.position;k.display="none";f=!1;g&&g.parentNode&&g.parentNode.removeChild(g);document.removeEventListener("keydown",
b,!1);l&&l.onclose&&(l.onclose(),l=null)}var c=null,f=!1;e=e||{};void 0==e.backgroundColor&&(e.backgroundColor="#333");void 0==e.zIndex&&(e.zIndex=999);var g=null;!0!==e.noClose&&(g=document.createElement("img"),g.width=25,g.height=25,g.src=hi5.tool.getImage("del","del.png"),g.className="h5-img-btn",g.style.cursor="pointer",g.align="top",g.style.position="absolute",e.close?(g.style.top=e.close.top,g.style.right=e.close.right):(g.style.top=0,g.style.right=0));this.resize=h;var l=null;this.show=function(){var k=
a.style;l=this;c={boxSizing:k.boxSizing,position:k.position,top:k.top,left:k.left,borderWidth:k.borderWidth,borderColor:k.borderColor,display:k.display,zIndex:k.zIndex,borderStyle:k.borderStyle,opacity:k.opacity};k.boxSizing="content-box";k.position="absolute";k.display="block";k.borderStyle="solid";k.borderColor=e.backgroundColor;k.top=0;k.left=0;k.zIndex=e.zIndex;h();window.addEventListener("resize",h,!1);f=!0;g&&a.appendChild(g);document.addEventListener("keydown",b,!1);if(this.onopen)this.onopen()};
this.visible=function(){return f};this.dismiss=d;g&&g.addEventListener("click",d,!1)};
hi5.ui.LightboxWithBtn=function(a,e){function h(){var k=(window.innerWidth-a.clientWidth)/2|0,m=(window.innerHeight-a.clientHeight)/3|0;a.style.borderWidth=m+"px "+k+"px "+2*m+"px "+k+"px"}function b(k){27==k.keyCode&&d()}function d(){var k=a.style;k.boxSizing=c.boxSizing;k.top=c.top;k.left=c.left;k.borderWidth=c.borderWidth;k.borderColor=c.borderColor;k.borderStyle=c.borderStyle;k.zIndex=c.zIndex;k.position=c.position;k.display=c.display;k.opacity=c.opacity;f=!1;a.removeChild(g);document.removeEventListener("keydown",
b,!1);l&&l.onclose&&(l.onclose(),l=null)}var c=null,f=!1;e=e||{};void 0==e.backgroundColor&&(e.backgroundColor="#333");void 0==e.zIndex&&(e.zIndex=999);void 0==e.opacity&&(e.opacity=.9);var g=document.createElement("button");g.id="continue_button";g.innerHTML="Continue";g.style="float: right";this.resize=h;var l=null;this.show=function(){var k=a.style;l=this;c={boxSizing:k.boxSizing,position:k.position,top:k.top,left:k.left,borderWidth:k.borderWidth,borderColor:k.borderColor,display:k.display,zIndex:k.zIndex,
borderStyle:k.borderStyle,opacity:k.opacity};k.boxSizing="content-box";k.position="absolute";k.display="block";k.borderStyle="solid";k.borderColor=e.backgroundColor;k.top=0;k.left=0;k.zIndex=e.zIndex;k.opacity=e.opacity;h();window.addEventListener("resize",h,!1);f=!0;a.appendChild(g);document.addEventListener("keydown",b,!1);if(this.onopen)this.onopen()};this.visible=function(){return f};this.dismiss=d;g.addEventListener("click",d)};
hi5.canvas={TextSelect:function(a,e,h,b,d){d||(d=a.canvas.width-1);e--;this.clear=function(){a.clearRect(0,0,a.canvas.width,a.canvas.height)};this.draw=function(c,f,g,l){l>f?l-f<e&&(l=f+e):f-l<e&&(l=f-e);a.fillStyle=h||"#61D2D6";a.beginPath();a.moveTo(c,f);a.lineTo(d,f);a.lineTo(d,l-e);a.lineTo(g,l-e);a.lineTo(g,l);a.lineTo(0,l);a.lineTo(0,f+e);a.lineTo(c,f+e);a.lineTo(c,f);a.fill()}}};
hi5.DataTable=function(a){if(hi5.ui.initAs(a,"DataTable")){hi5.EventControl(a);"string"==typeof a&&(a=JSON.parse(a));var e=a.rows,h=a.cols;a.rowNo=-1;a.beforeGetValue=null;a.moveTo=function(b){a.rowNo=b};a.getColNo=function(b){for(var d=0,c=h.length;d<c;d++)if(h[d].name==b)return d;return-1};a.getValue=function(b){var d=e[a.rowNo][b];return a.beforeGetValue?a.beforeGetValue(b,d):d};a.setValue=function(b,d){a.beforeSetValue&&(d=a.beforeSetValue(b,d));e[a.rowNo][b]=d;a.fireEvent("onchange",[b,a.rowNo,
d])};a.first=function(){a.moveTo(0)};a.next=function(){a.moveTo(a.rowNo+1)};a.last=function(){a.moveTo(e.length-1)};a.hasNext=function(){return a.rowNo<e.length-1};a.remove=function(b){b||(b=a.rowNo);var d=[b];a.fireEvent("beforeremove",d);e.splice(b,1);a.fireEvent("onremove",d)};a.perform=function(b){"function"==typeof a[b]?a[b].apply(a):a.fireEvent("onaction",[b])};a.getObject=function(){for(var b={},d=0,c=h.length;d<c;d++)b[h[d].name]=a.getValue(d);return b};a.find=function(b,d){for(var c=0,f=
e.length;c<f;c++)if(e[c][b]==d)return e[c];return null};a.sort=function(b){a.cols[b].sortDir=void 0==a.cols[b].sortDir?-1:-a.cols[b].sortDir;var d=a.cols[b].sortDir;a.rows.length&&(a.rows.sort(function(c,f){return c[b]>f[b]?d:c[b]<f[b]?-d:0}),a.fireEvent("reload"))}}a.fireEvent("onopen");return a};
hi5.DataGrid=function(a,e){function h(l){var k=this.rowIndex;"number"==typeof k&&(d=k-=a.tHead.rows.length,b.moveTo(k));if(a.onrowclick)a.onrowclick(l)}if(!hi5.ui.initAs(a,"DataGrid"))return a;if("TABLE"!=a.nodeName)throw"Not HTML Table";var b=null;a.onrowclick=null;Object.defineProperty(a,"dataTable",{get:function(){return b},set:function(l){b=l;b.addEvent("reload",function(){a.fillData(b)})},enumerable:!0,configurable:!0});var d=-1;a.getValue=function(l){var k=b;k.moveTo(d);return k.getValue(k.getColNo(l))};
a.fillData=function(l){var k=l.rows,m=l.cols;if(k&&m){m=a.tBodies[0];var n;a._rowTemp||(a._rowTemp=a.tBodies[0].rows[0].cloneNode(!0));var q=a._rowTemp;var r=q.cells.length,w=m.cloneNode(!1);var p=k.length;for(n=0;n<p;n++){var t=q.cloneNode(!0);var v=t.cells;l.moveTo(n);for(k=0;k<r;k++)if(!v[k].innerHTML){var x=l.getValue(k);a.beforeDisplayValue&&(x=a.beforeDisplayValue(k,x));e?v[k].innerText=x:v[k].innerHTML=x}d=n;t.addEventListener("click",h,!1);a.beforeAppendRow&&a.beforeAppendRow(t);w.appendChild(t)}a.removeChild(m);
a.appendChild(w)}};a.open=function(){b&&(a.fillData(b),b.addEvent("onremove",function(l){var k=a.tBodies[0];(l=k.rows[l])&&k.removeChild(l)}))};a.clear=function(){if(a._rowTemp){a.removeChild(a.tBodies[0]);var l=document.createElement("tbody");l.appendChild(a._rowTemp);a.appendChild(l)}};for(var c=a.tHead.rows[0].cells,f=c.length,g=0;g<f;g++)c[g].addEventListener("click",function(l){b&&b.sort(l.target.cellIndex)},!1);return a};
hi5.Select=function(a,e,h){if(!hi5.ui.initAs(a,"Select"))return a;var b=a.parentNode,d=document.createElement("div");d.style.padding="0";d.style.display="inline";b.insertBefore(d,a);var c=document.createElement("img");c.src=hi5.tool.getImage("select","select.png");c.height=a.offsetHeight;c.style.verticalAlign="-6px";d.appendChild(a);d.appendChild(c);var f=document.createElement("select");e&&(f.multiple=!0,h||(h=","));b=a.getAttribute("hi5_size");f.size=b?b:10;if(b=a.getAttribute("hi5_list"))if(b=
b.split(";"),d=b.length,0<d)for(var g=f.options,l=0;l<d;l++)g[l]=new Option(b[l]);f.style.position="absolute";f.style.zIndex=99999;f.style.display="none";document.body.appendChild(f);a.show=function(){a.beforedropdown&&a.beforedropdown(a);f.style.display="";f.focus()};a.hide=function(){f.style.display="none";a.focus()};c.onclick=function(){if("none"==f.style.display){if(0==f.options.length){var k=a.getAttribute("onfetchlist");k&&eval(k)}k=hi5.tool.getPos(a,!1);f.style.left=k.x+"px";f.style.top=k.y+
a.offsetHeight+"px";f.style.width=a.offsetWidth+c.width+3+"px";a.show()}else a.hide()};f.onchange=function(){if(e){for(var k=[],m,n=f.options,q=0,r=n.length;q<r;q++)m=n[q],m.selected&&k.push(m.value);a.value=k.join(h)}else a.value=f.value,f.style.display="none";if(a.onchange)a.onchange()};a.options=f.options;return a};hi5.init.push(function(){for(var a=document.getElementsByClassName("Hi5Select"),e=a.length,h=0;h<e;h++)new hi5.Select(a[h])});
hi5.Tab=function(a){function e(m){var n=c;c!=m&&(f[c].className="tab_back",g[c].className="tab_hide",c=m);f[m].className="tab_front";g[m].className="tab_show";f[m].focus();n!=m&&a.fireEvent("ontabchange",[m,n])}function h(m){m=f.indexOf(m.target);-1!=m&&e(m)}if(!hi5.ui.initAs(a,"Tab"))return a;hi5.EventControl(a);for(var b=a.getElementsByClassName("tab")[0].getElementsByClassName("tab_title")[0].childNodes,d=b.length,c=0,f=[],g=[],l=0;l<d;l++){var k=b[l];"SPAN"==k.nodeName.toUpperCase()&&(k.className=
"tab_back",k.onclick=h,k.onfocus=h,f[f.length]=k)}b=a.getElementsByClassName("tab_body")[0].childNodes;d=b.length;for(l=0;l<d;l++)k=b[l],"DIV"==k.nodeName.toUpperCase()&&(g[g.length]=k,k.className="tab_hide");e(c);a.setSelected=e;a.getSelected=function(){return c};return a};hi5.init.push(function(){for(var a=document.getElementsByClassName("tab_all"),e=a.length,h=0;h<e;h++)new hi5.Tab(a[h])});
hi5.Notification=function(a){function e(){a||(a=hi5.$("hi5_notifer_all"),a||(a=document.createElement("div"),a.name=a.id="hi5_notifer_all",a.style.display="none",document.body.appendChild(a)));return a}function h(c){var f=new b(c);e().appendChild(f);a.style.display="block";c.select&&(c=f.getElementsByClassName("hi5_notifer_msg")[0],"TEXTAREA"==c.nodeName?c.select():hi5.browser.selectEditable(c))}function b(c){function f(p,t,v){var x=document.createElement("button");t&&(x.className=t);v&&(x.innerHTML=
v);x.onclick=function(y){p.apply(g,[y])};return x}var g=document.createElement("div");g.className="hi5_notifer slideUp";g.title=c.title;g.message=c.msg;g.msgCount=1;c.name&&(g.msgName=c.name);var l=document.createElement("div");l.className="hi5_notifer_title";var k=document.createElement("span");k.className="hi5_notifer_icon";l.appendChild(k);l.appendChild(document.createTextNode(g.title));g.appendChild(l);l=document.createElement("div");var m="text/plain"==c.format?document.createElement("textarea"):
document.createElement("div");m.className="hi5_notifer_msg";m.style.width="100%";m.innerHTML=c.msg;l.appendChild(m);var n=document.createElement("span");n.className="hi5_notifer_count";g.setCount=function(p){g.msgCount=p;n.innerHTML=1<p?"("+g.msgCount+")":""};c.count&&g.setCount(c.count);l.appendChild(n);g.setMessage=function(p){g.message=p;m.innerHTML=p};g.appendChild(l);c.cbNo&&g.appendChild(f(c.cbNo,"hi5_notifer_button_no"));c.cbYes&&g.appendChild(f(c.cbYes,"hi5_notifer_button_yes"));if(c.buttons){l=
document.createElement("div");l.className="hi5_float";k=0;for(var q=c.buttons.length;k<q;k++){var r=c.buttons[k];l.appendChild(f(r.onclick,r.className,r.label))}g.appendChild(l)}g.destroy=function(){if(g.parentNode){g.parentNode.removeChild(g);var p=d.notifyPool.shift();if(p)h(p);else if(0==d.notifySize()&&(a.style.display="none",d.onempty))d.onempty();c.cbClose&&c.cbClose()}};if(c.timeout){var w=setTimeout(function(){g.destroy()},c.timeout);g.addEventListener("mouseover",function(){clearTimeout(w)},
!1)}c.onclick?g.onclick=c.onclick:c.cbYes||c.cbNo||(g.onclick=g.destroy);return g}this.notifyPool=[];var d=this;this.notify=function(c){c="string"==typeof c?{msg:c,title:"",count:1,type:0}:c;c.title||(c.title="");c.count||(c.count=1);if(!d.onnotify||!d.onnotify(c)){var f=hi5.tool.getChildNodesByTag(e(),"div"),g=f.length;if(0<g)if(3==c.type)for(var l=g;0<l;){l--;var k=f[l];if(k.msgName==c.name){k.message!=c.msg?(k.setMessage(c.msg),k.setCount(1)):k.setCount(k.msgCount+1);return}}else if(k=f[g-1],!k.msgName&&
k.title==c.title&&k.message==c.msg){k.setCount(k.msgCount+1);return}if(3>g)h(c);else{f=d.notifyPool;g=f.length;if(0<g)if(3==c.type)for(;0<g;)g--,f[g].name==c.name&&(f[g].msg!=c.msg?(f[g].msg=c.msg,f[g].count=0):f[g].count++);else if(g=f[g-1],!g.name&&g.title==c.title&&g.msg==c.msg){g.count++;return}f.push(c)}}};this.notifySize=function(){return hi5.tool.getChildNodesByTag(e(),"div").length};this.clearAll=function(){d.notifyPool.length=0;for(var c=e();c.hasChildNodes();)c.removeChild(c.firstChild)}};
hi5.notifications=new hi5.Notification;
hi5.file={readAsArrayBuffer:function(a,e){var h=new FileReader;h.onloadend=function(b){e(new Uint8Array(b.target.result))};h.readAsArrayBuffer(a)},getEntries:function(a){var e=a.target&&(a.target.webkitEntries||a.target.entries||[]);if(!e.length&&(a=a.dataTransfer&&a.dataTransfer.items))for(var h=0,b;b=a[h];++h)if("file"==b.kind){if(!b.webkitGetAsEntry&&!b.getAsEntry)break;b=b.getAsEntry?b.getAsEntry():b.webkitGetAsEntry();if(!b)break;e.push(b)}return e},getFilesFromEntries:function(a,e){function h(){c--;
c||e(f)}function b(g){return function(l){l.fullPath=g;f.push(l);h()}}function d(g){var l=g.length;c+=l;for(var k=0;k<l;k++){var m=g[k];m.isFile?m.file(b(m.fullPath),function(n){console.log(n);h()}):m.isDirectory&&m.createReader().readEntries(function(n){n.length&&d(n);h()},function(){h()})}}var c=0,f=[];d(a)},DirectoryReader:function(a){function e(d,c){var f=d.createReader(),g=[],l=function(){f.readEntries(function(k){k.length?(g=g.concat(Array.prototype.slice.call(k||[],0)),l()):c(g)})};l()}function h(d){for(var c=
0,f=d.length;c<f;c++){var g=d[c];g.isFile?g.file(function(l){return function(k){b.onfile(k,l)}}(g.fullPath)):g.isDirectory&&e(g,function(l){h(l)})}}var b=this;this.start=function(){h(a)}},UploadManager:function(a){var e={},h=0,b=a;this.canCopyFile=!1;this.enabled=!0;hi5.EventControl(this);var d=this,c=null,f=0,g=!0,l=!0,k=!1;this.setDownload=function(m){g=m};this.setUpload=function(m){l=m};this.release=function(){e=b=a=d=null};this.read=function(m,n,q){var r=e[e[m]];if("undefined"!=typeof r&&!(1>
r.size&&__svi18n.file.zero)){var w=r.slice(n,n+q),p=new FileReader;p.onloadend=function(t){t.target.readyState==FileReader.DONE&&(t=new Uint8Array(t.target.result),a.send(m,n,q,t,r.preferPaste),h+=q,d.fireEvent("progress",[h]))};p.readAsArrayBuffer(w)}};this.mkdirs=function(m){d.enabled&&("/"!=m.charAt(m.length-1)&&(m+="/"),a.start([m],0,!0))};this.addFiles=function(m,n){var q=m.length;if(q&&d.enabled&&l){k=n&&d.canCopyFile;n=[];f=Date.now();for(var r=0;r<q;r++){var w=m[r];k&&(w.preferPaste=!0);var p=
w.fullPath||w.name;-1==d.fireEvent("beforeupload",[w,p,k]).indexOf(!0)&&(n.push(m[r]),p=encodeURIComponent(p),e[p]=w)}0<n.length?(a.start(n,k),d.fireEvent("uploadstarted",[k])):d.fireEvent("uploaded",[k,{size:0,duration:0}])}};this.removeFile=function(m,n){b.remove(m,n)};this.confirmId=function(m,n,q){e[m]=n;q&&(h+=parseInt(q))};this.close=function(m,n){var q=k;n={size:h,duration:Date.now()-f,cancelled:n};if(m){var r=e[m];r&&(q=e[r].preferPaste||!1,delete e[m],delete e[r],m=decodeURIComponent(r),
d.fireEvent("fileuploaded",[m,q&&d.canCopyFile,n]));for(var w in e)return}else e={};f=h=0;d.fireEvent("uploaded",[q&&d.canCopyFile,n])};this.cancelAll=function(){b.cancelAll();d.fireEvent("uploadingCancelled");d.close(null,!0)};this.list=function(m,n){c=n;b.list(m)};this.notifyFiles=function(m){c&&c(m);d.fireEvent("files")};this.download=function(){g&&b.download()}},WsFileService:function(a){function e(h,b,d){var c=b.length,f=new Uint8Array(2+2*c);f[0]=58;f[1]=d?h|128:h;d=2;for(var g=0;g<c;g++)h=
b.charCodeAt(g),f[d++]=h&255,f[d++]=h>>8&255;a(f.buffer)}this.start=function(h,b,d){for(var c=h.length,f=20*c+2,g=0,l=new Uint8Array(8),k=2,m,n,q,r;g<c;g++)f=d?f+2*(encodeURIComponent(h[g]).length+1):f+2*(encodeURIComponent(h[g].fullPath||h[g].name).length+1);f=new Uint8Array(f);f[0]=58;f[1]=0;b&&(f[1]|=128);for(g=0;g<c;g++){b=d?0:h[g].size;f[k++]=b&255;f[k++]=b>>8&255;f[k++]=b>>16&255;f[k++]=b>>24&255;4294967296>b?k+=4:(m=hi5.NumUtils.splitInt64(b).high,f[k++]=m&255,f[k++]=m>>8&255,f[k++]=m>>16&
255,f[k++]=m>>24&255);d||hi5.NumUtils.toBytes(h[g].lastModified||h[g].lastModifiedDate.getTime(),l);f.set(l,k);k+=12;m=encodeURIComponent(d?h[g]:h[g].fullPath||h[g].name);n=m.length;for(q=0;q<n;q++)r=m.charCodeAt(q),f[k++]=r&255,f[k++]=r>>8&255;k+=2;svGlobal.logger.info("upload file: "+m+" size:"+b)}a(f.buffer)};this.send=function(h,b,d,c,f){svGlobal.logger.debug("send file, id:"+h+" offset:"+b+" len:"+d);var g=new Uint8Array(22+d);g[0]=58;g[1]=3;f&&(g[1]|=128);f=2;g[f++]=h&255;g[f++]=h>>8&255;g[f++]=
h>>16&255;g[f++]=h>>24&255;g[f++]=b&255;g[f++]=b>>8&255;g[f++]=b>>16&255;g[f++]=b>>24&255;4294967296>b?f+=4:(b=hi5.NumUtils.splitInt64(b).high,g[f++]=b&255,g[f++]=b>>8&255,g[f++]=b>>16&255,g[f++]=b>>24&255);g[f++]=d&255;g[f++]=d>>8&255;g[f++]=d>>16&255;g[f++]=d>>24&255;g.set(c,f+4);a(g.buffer)};this.remove=function(h,b){e(6,h,b)};this.list=function(h){e(5,h)};this.cancelAll=function(){e(7,"")};this.download=function(){e(136,"")}}};
hi5.Chat=function(a,e){function h(l,k,m){var n=document.createElement("span");n.className=k;n.innerHTML=l;m.appendChild(n);return n}function b(){var l=c.value;g.add(l,e);c.value="";if(g.onchat)g.onchat(l,e)}var d=hi5.$("chatHistory"),c=hi5.$("chatText"),f=hi5.$("chatSend"),g=this;this.add=function(l,k){var m=document.createElement("div");h((k||e)+":","chatFrom",m);h(l,"chatMsg",m);l=new Date;h(l.getHours()+":"+l.getMinutes()+":"+l.getSeconds(),"chatTime",m);"block"!=a.style.display&&(a.style.display=
"block");d.appendChild(m);d.scrollTop=d.scrollHeight};c.addEventListener("keydown",function(l){13==l.keyCode&&b()},!1);f.addEventListener("click",b,!1)};document.addEventListener("DOMContentLoaded",hi5.init.start,!1);
