var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,g){if(a==Array.prototype||a==Object.prototype)return a;a[e]=g.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var e=0;e<a.length;++e){var g=a[e];if(g&&g.Math==Math)return g}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,e){var g=$jscomp.propertyToPolyfillSymbol[e];if(null==g)return a[e];g=a[g];return void 0!==g?g:a[e]};$jscomp.polyfill=function(a,e,g,b){e&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,e,g,b):$jscomp.polyfillUnisolated(a,e,g,b))};
$jscomp.polyfillUnisolated=function(a,e,g,b){g=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var d=a[b];if(!(d in g))return;g=g[d]}a=a[a.length-1];b=g[a];e=e(b);e!=b&&null!=e&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:e})};
$jscomp.polyfillIsolated=function(a,e,g,b){var d=a.split(".");a=1===d.length;b=d[0];b=!a&&b in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var c=0;c<d.length-1;c++){var f=d[c];if(!(f in b))return;b=b[f]}d=d[d.length-1];g=$jscomp.IS_SYMBOL_NATIVE&&"es6"===g?b[d]:null;e=e(g);null!=e&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:e}):e!==g&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(b,d,{configurable:!0,writable:!0,value:e})))};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(e,g,b){var d=this.length||0;0>g&&(g=Math.max(0,d+g));if(null==b||b>d)b=d;b=Number(b);0>b&&(b=Math.max(0,d+b));for(g=Number(g||0);g<b;g++)this[g]=e;return this}},"es6","es3");$jscomp.typedArrayFill=function(a){return a?a:Array.prototype.fill};$jscomp.polyfill("Int8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Uint8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint8ClampedArray.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Float32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Float64Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.arrayIteratorImpl=function(a){var e=0;return function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var e=function(d,c){this.$jscomp$symbol$id_=d;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};e.prototype.toString=function(){return this.$jscomp$symbol$id_};var g=0,b=function(d){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new e("jscomp_symbol_"+(d||"")+"_"+g++,d)};return b},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var e="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),g=0;g<e.length;g++){var b=$jscomp.global[e[g]];"function"===typeof b&&"function"!=typeof b.prototype[a]&&$jscomp.defineProperty(b.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,e){a instanceof String&&(a+="");var g=0,b=!1,d={next:function(){if(!b&&g<a.length){var c=g++;return{value:e(c,a[c]),done:!1}}b=!0;return{done:!0,value:void 0}}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(e,g){return[e,g]})}},"es6","es3");var hi5=hi5||{};
hi5.init={inited:!1,funcs:[],push:function(a){hi5.init.funcs.push(a)},start:function(a){if(!hi5.init.inited){hi5.browser.innerHeight=window.innerHeight;hi5.init.inited=!0;a=hi5.init.funcs;for(var e=0,g=a.length;e<g;e++)a[e]();hi5.init.release()}},release:function(){document.removeEventListener("DOMContentLoaded",hi5.init.start,!1)}};
window.requestAnimationFrame||(window.requestAnimationFrame=window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,30,Date.now())});window.URL=window.URL||window.webkitURL;window.WebSocket=window.WebSocket||window.MozWebSocket;hi5.WebSocket=window.WebSocket;hi5.$=function(a){return document.getElementById(a)};
hi5.html={hasClass:function(a,e){return a.classList.contains(e)},addClass:function(a,e){a.classList.add(e)},removeClass:function(a,e){a.classList.remove(e)}};
hi5.browser=new function(){var a=navigator.userAgent;this.innerHeight=0;this.isEdge=-1!=a.indexOf("Edge");var e=(this.isIE=-1!=a.indexOf("MSIE")||-1!=a.indexOf("Trident"))||this.isEdge;this.isTouch="maxTouchPoints"in navigator||"msMaxTouchPoints"in navigator?1<=(navigator.msMaxTouchPoints||navigator.maxTouchPoints):"ontouchstart"in window||"createTouch"in document||"DocumentTouch"in window&&window.document instanceof window.DocumentTouch||-1!=a.indexOf("Mobile");this.isFirefox=-1!=a.indexOf("Firefox")&&
!e;this.isOpera=-1!=a.indexOf("Opera");this.isRIM=-1!=a.indexOf(" RIM ");this.isChrome=-1!=a.indexOf("Chrome")&&!e;this.isMacOS=-1!=a.indexOf("Mac OS");this.isWindows=-1!=a.indexOf("Windows ");this.isiOS=navigator.userAgent.match(/(iPad|iPhone|iPod)/i)?!0:!1;this.isSafari=-1==a.indexOf("Chrome")&&-1!=a.indexOf("Safari")&&!e;this.isWebKit=-1!=a.indexOf("WebKit");this.isCrOS=-1!=a.indexOf("CrOS");this.isOperaNext=-1!=a.indexOf("Edition Next");this.isAndroid=-1!=a.indexOf("Android");this.isChromeApp=
"chrome"in window&&"app"in chrome&&"window"in chrome.app;this.isDesktop=!a.match(/(iPhone|iPod|iPad|Android|BlackBerry|Mobile)/);this.isLinux=-1!=a.indexOf("Linux");this.isElectron=!!(window.process&&process.versions&&process.versions.electron);e=window.outerHeight-window.innerHeight;this.isMetro=0==window.screenY&&(0==window.screenX||window.screenX+window.outerWidth==screen.width)&&3<e&&31>e;this.isMultitask=!(this.isiOS&&this.isSafari&&0<a.indexOf("Version/5"));this.binaryWS=function(){return hi5.browser.isChrome?
!0:hi5.tool.hasProperty(WebSocket,"binaryType")};this.cookie2Obj=function(){var b=document.cookie,d={};if(""==b)return d;for(var c=b.split(";"),f=0,h=c.length;f<h;f++){for(var k=c[f];" "==k.charAt(0);)k=k.substring(1,k.length);b=k.indexOf("=");if(0<b){var l=decodeURIComponent(k.substring(b+1).replace(/\+/g," "));hi5.tool.isNumber(l)&&"0"!=l[0]&&parseFloat(l)==l&&(l=parseFloat(l));if("true"==l||"on"==l)l=!0;else if("false"==l||"off"==l)l=!1;d[k.substring(0,b)]=l}}return d};this.obj2url=function(b){var d=
"",c;for(c in b)d+="&"+c+"=",d="boolean"==typeof b[c]?d+(b[c]?"on":"off"):d+encodeURIComponent(b[c]);d&&(d=d.substring(1));return d};this.getLibPath=function(b){for(var d=document.getElementsByTagName("script"),c,f,h="",k=d.length,l=0;l<k;l++)if(f=d[l].src,c=f.indexOf(b),-1<c){h=f.substring(0,c);break}0==h.indexOf(location.origin)&&(h=h.substring(location.origin.length));return h};this.getJS=function(b){for(var d=document.getElementsByTagName("script"),c,f,h=d.length,k="/"==b[0],l=0;l<h;l++)if(f=
d[l].src,c=f.indexOf(b),-1!=c&&(k||"/"==f[c-1]))return d[l];return null};this.loadJS=function(b,d,c){0>b.indexOf("/")&&(b=hi5.libPath+b);var f=hi5.browser.getJS(b);if(f)return f;f=document.createElement("script");f.type="text/javascript";d&&(f.onload=d,f.onreadystatechange=function(){"complete"==this.readyState&&d()});c&&(f.onerror=c);(document.currentScript?document.currentScript.parentNode:document.head||document.body).appendChild(f);f.src=b;return f};this.formToObj=function(b,d){b=b.elements;var c,
f=b.length;d||(d={});for(var h=0;h<f;h++){var k=b[h];if(c=k.name){var l=k.type;switch(l){case "submit":case "button":case "reset":continue;case "checkbox":k=k.checked;break;case "radio":if(!k.checked)continue;k=k.value;break;case "number":parseFloat(k.value);default:k=k.value}""!==k&&(d[c]=k)}}return d};this.objToForm=function(b,d){var c=d.elements,f;for(f in b)if(d=c[f]){var h=b[f];"boolean"==typeof h?d.checked=h:d.value=h}};this.objToCookie=function(b){for(var d in b)""!=b[d]&&(document.cookie=
d+"="+b[d])};this.getScale=function(){return document.documentElement.clientWidth/window.innerWidth};this.httpGet=function(b,d){var c=new XMLHttpRequest;c.open("GET",b,d);c.withCredentials=!0;c.setRequestHeader("Content-Type","text/plain;charset=UTF-8");c.send(null);return c.responseText};this.selectEditable=function(b){try{var d=document.createRange();d.selectNodeContents(b);var c=window.getSelection();c.removeAllRanges();c.addRange(d)}catch(f){console.log(f)}};this.setOrientaionHandler=function(b){"onorientationchange"in
screen?screen.onorientationchange=b:"onmozorientationchange"in screen?screen.onmozorientationchange=b:"onmsorientationchange"in screen?screen.onmsorientationchange=b:window.addEventListener("orientationchange",b,!1)};var g={x:0,y:0};this.getMousePos=function(b,d){d=(d||b.target).getBoundingClientRect();g.x=b.clientX-d.left;g.y=b.clientY-d.top;return g};this.calMousePos=function(b,d,c){c=c.getBoundingClientRect();g.x=b-c.left;g.y=d-c.top;return g};this.getHost=function(){var b=hi5.tool.queryToObj().gateway;
if(!b&&!hi5.browser.isChromeApp)if(b=location.host){var d=location.pathname,c=d.indexOf("://");0<c&&(b+=d.substring(0,d.indexOf("/",c+3)))}else b="localhost";return b};this.html2text=function(b){var d=document.createElement("div");b=b.replace(/<style([\s\S]*?)<\/style>/g,"");b=b.replace(/<\/p>/g,"</p>\r\n");b=b.replace(/<br\s?\/?>/,"\r\n");d.innerHTML=b;return d.textContent.replace(/\u00a0/g," ")};this.dataURLtoBlob=function(b){var d=b.indexOf(","),c=b.substring(0,d++),f=c.indexOf(":"),h=c.indexOf(";",
f);h=h>f?c.substring(f+1,h):"text/plain";b=0<c.indexOf("base64",f)?hi5.Base64.dec(b,d,!0):b.substring(d);return new Blob([b],{type:h})};this.downloadData=function(b,d,c){b=new Blob(b,{type:c||"application/octet-binary"});var f=URL.createObjectURL(b);d=d||"file.bin";hi5.notifications.notify({msg:'<a href="'+f+'" target="_blank" download="'+d+'">Download '+d+"</a>",html:!0,cbClose:function(){setTimeout(function(){URL.revokeObjectURL(f)},999)}})};this.blobToArray=function(b,d){var c=new FileReader;c.onloadend=
function(f){f.target.readyState==FileReader.DONE&&d(new Uint8Array(f.target.result))};c.readAsArrayBuffer(b)};this.blobToText=function(b,d){var c=new FileReader;c.onloadend=function(f){f.target.readyState==FileReader.DONE&&d(f.target.result)};c.readAsText(b)};this.getScreenWidth=function(){if(-1==navigator.userAgent.indexOf("MSIE")&&-1==navigator.userAgent.indexOf("Trident")||0<=window.screenX&&window.screenX<screen.width&&0<=window.screenY&&window.screenY<screen.height)return screen.width;for(var b=
window.outerWidth,d=[1920,2560,3840,4E3,7680],c=0;5>c;c++)if(b<=d[c])return d[c];return b};this.getScreenHeight=function(){if(-1==navigator.userAgent.indexOf("MSIE")&&-1==navigator.userAgent.indexOf("Trident")||0<=window.screenX&&window.screenX<screen.width&&0<=window.screenY&&window.screenY<screen.height)return screen.height;for(var b=window.outerHeight,d=[1080,1200,1600,2E3,2160,4320],c=0;5>c;c++)if(b<=d[c])return d[c];return b};this.cookie={set:function(b,d,c){var f=new Date;f.setTime(f.getTime()+
864E5*c);c="expires="+f.toUTCString();document.cookie=b+"="+d+";"+c+";path=/"},get:function(b){b+="=";for(var d=document.cookie.split(";"),c=0;c<d.length;c++){for(var f=d[c];" "==f.charAt(0);)f=f.substring(1);if(0==f.indexOf(b))return f.substring(b.length,f.length)}return""},delete:function(b){document.cookie=b+"=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;"}};this.getChildByNameOrId=function(b,d){if(b){b=b.childNodes;for(var c=b.length,f=0;f<c;f++)if(b[f].name==d||b[f].id==d)return b[f]}return null};
this.launchApp=function(b,d,c){function f(r){r=Date.now()-n;m?l&&clearTimeout(l):777>r&&(clearTimeout(q),m=!0)}function h(r){m&&(l=setTimeout(function(){k();d()},300))}function k(){window.removeEventListener("blur",f);window.removeEventListener("focus",h)}var l,m=!1;window.focus();window.addEventListener("blur",f);window.addEventListener("focus",h);var n=Date.now();location.href=b;var q=setTimeout(function(){k();c&&c()},777)};this.initDialog=function(b,d){b.addEventListener("cancel",function(){b.returnValue=
""});var c=b.querySelector("form");if(c){var f=c.querySelector('button[name="cancel"]');f&&(f.onclick=function(){b.close("")});c.onsubmit=function(h){h.preventDefault();h=c.elements;for(var k="",l=0,m=h.length;l<m;l++){var n=h[l];n.value&&(k+=n.name+"="+encodeURIComponent(n.value))}b.close(k)};b.addEventListener("close",function(){d&&d(b.returnValue)})}}};
hi5.libPath||(hi5.libPath=hi5.browser.getLibPath("hi5core.js")||hi5.browser.getLibPath("hi5.js"),hi5.libPath?hi5.libMin=!1:(hi5.libPath=hi5.browser.getLibPath("hi5core_min.js")||hi5.browser.getLibPath("hi5_min.js"),hi5.libPath&&(hi5.libMin=!0)));
hi5.storage=new function(){function a(c,f){this._state=f||0;this._value=c}function e(c){return c&&0==c.indexOf("{")&&(c=JSON.parse(c))&&"_state"in c&&"_value"in c?c:null}var g="chrome"in window&&!!chrome.storage,b="localStorage"in window;if(b)try{localStorage.setItem("_t_s_t","1"),localStorage.removeItem("_t_s_t")}catch(c){b=this.isAvailable=!1}this.isAvailable=!!g||b;var d=g||!this.isAvailable?{}:localStorage;g&&chrome.storage.local.get(null,function(c){for(var f in c)d[f]=c[f]});this.set=function(c,
f){d[c]=JSON.stringify(new a(f,1))};this.get=function(c){c=d[c];var f=e(c);return f?f._value:c};this.clear=function(c){d={};g?chrome.storage.local.clear(c||function(){}):b&&localStorage.clear()};this.remove=function(c){if(d.removeItem)d.removeItem(c);else{var f=e(d[c]);f&&(f._state=2,d[c]=JSON.stringify(f))}};this.commit=function(c){c=c||function(){};if(g){var f={},h=[],k=!1,l;for(l in d){var m=e(d[l]);m&&(1==m._state?(f[l]=m._value,k=!0):2==m._state&&h.push(l))}0<h.length&&chrome.storage.local.remove(h,
function(){for(var n=0,q=h.length;n<q;n++)delete d[h[n]];c&&c()});k&&chrome.storage.local.set(f,c)}else c()}};
hi5.tool={isNumber:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},cumulativePos:function(a){var e=0,g=0;do if(e+=a.offsetTop||0,g+=a.offsetLeft||0,e+=parseInt(a.style.borderLeftWidth)||0,g+=parseInt(a.style.borderTopWidth)||0,e-=a.scrollTop,g-=a.scrollLeft,a=a.offsetParent,a==document.body)break;while(a);return{x:g,y:e}},getPos:function(a,e){return a.getBoundingClientRect()},bytesToSize:function(a){if(isNaN(a))return"";var e=Math.floor(Math.log(+a)/Math.log(2));1>e&&(e=0);e=Math.floor(e/10);
a=+a/Math.pow(2,10*e);a.toString().length>a.toFixed(3).toString().length&&(a=a.toFixed(2));return a+" bytes; KB; MB; GB; TB; PB; EB; ZB; YB".split(";")[e]},queryToObj:hi5.string.queryToObj,replaceQuery:function(a,e,g){var b=a.indexOf(e+"="),d=!1;0<b&&(b=a.charAt(b-1),"&"==b||"?"==b)&&(d=!0);return d?a.replace(new RegExp("[\\?&]"+e+"=([^&#]*)"),function(c){return c.charAt(0)+e+"="+encodeURIComponent(g)}):a+="&"+e+"="+encodeURIComponent(g)},disableInput:function(a){window.__hi5_bk&&hi5.tool.enableInput();
var e=document.createElement("div");if(a){var g=window.getComputedStyle(a);e.style.position=g.getPropertyValue("position");e.style.left=g.getPropertyValue("left");e.style.top=g.getPropertyValue("top");e.style.width=g.getPropertyValue("width");e.style.height=g.getPropertyValue("height");e.style.zIndex=g.getPropertyValue("zIndex");e.style.right=g.getPropertyValue("right");e.style.bottom=g.getPropertyValue("bottom")}else e.style.position="fixed",e.style.left=0,e.style.top=0,e.style.width="100%",e.style.height=
"100%",e.style.zIndex=99999;e.style.background="url("+hi5.libPath+"spinner.gif) no-repeat center center";a?a.parentNode.appendChild(e):document.body.appendChild(e);window.__hi5_bk=e},enableInput:function(){window.__hi5_bk&&(window.__hi5_bk.parentNode.removeChild(window.__hi5_bk),window.__hi5_bk=null)},scale:function(a,e,g,b,d){b=void 0===b?"left top":b+" "+d;g||(g=e);a.style.transformOrigin=b;a.style.MozTransformOrigin=b;a.style.webkitTransformOrigin=b;a.style.msTransformOrigin=b;a.style.OTransformOrigin=
b;e="scale("+e+","+g+")";a.style.transform=e;a.style.MozTransform=e;a.style.webkitTransform=e;a.style.msTransform=e;a.style.OTransform=e},openWebSocket:function(a,e,g){var b=!1;if(g){var d=hi5.callback.put(g);a+="&callback="+d}var c=new WebSocket(a,"ctrl");c.onopen=function(f){b=!0;e&&c.send(e)};c.onclose=function(f){b||alert("Failed to connect")};c.onmessage=function(f){f=JSON.parse(f.data);c.close();f.callback?hi5.callback.get(f.callback)(f):g(f)};return c},scanAnyGood:function(a,e,g){for(var b=
!1,d=a.length,c=0,f=a.length;c<f;c++){var h=new WebSocket(a[c]);h.onopen=function(){b||(b=!0,e(this.url));this.close()};h.onerror=function(){d--;b||0!=d||g()}}},getChildNodesByTag:function(a,e){a=a.childNodes;for(var g=[],b=0,d=a.length;b<d;b++)a[b].nodeName.toLowerCase()==e&&g.push(a[b]);return g},hasProperty:function(a,e){return e in a||e in a.prototype?!0:e in(a.__proto__||a.constructor.prototype)},isCapslock:function(a){var e=String.fromCharCode(a.keyCode||a.which);return e.toUpperCase()!=e||
e.toLowerCase()==e||a.shiftKey?!1:!0},getImage:function(a,e){e&&0!=e.indexOf("/")&&(e=hi5.libPath+e);return hi5&&hi5.appcfg&&hi5.appcfg.img?hi5.appcfg.img[a]||e:e},uuid:function(){for(var a="",e=Array(16),g,b=0;16>b;b++)switch(e[b]=255*Math.random()|0,g=e[b].toString(16),1==g.length&&(g="0"+g),b){case 3:case 5:case 7:case 9:a+=g;a+="-";break;case 6:a+="4"+g[1];break;case 8:a+=(parseInt(g[0],16)&3|8).toString(16)+g[1];break;default:a+=g}return a},text2html:function(a){return a.replace(/\n/g,"<br>")},
Profiler:function(){function a(){this.totalTime=this.count=0}var e={},g=0,b=null,d=!1;this.begin=function(c){if(d){b=c;var f=e[c];void 0===f&&(f=new a,e[c]=f);g=(new Date).getTime();return f}};this.end=function(c){if(d){c=e[c||b];var f=(new Date).getTime()-g;c.totalTime+=f;c.count++;return c}};this.start=function(){d||(d=!0,e={},g=0,b=null)};this.stop=function(){d&&(d=!1)};this.isStarted=function(){return d};this.print=function(){console.log(this.getResult())};this.getResult=function(c){var f={},
h="undefined"===typeof c?0:c.length,k;for(k in e)0<h&&k.substring(0,h)!==c||(f[k]=e[k]);return f}},ResponseMonitor:function(a,e){function g(){d&&(a(),c&&(b=setTimeout(e,c)))}var b=0,d=0,c;this.tag=0;this.check=function(f){d&&(clearTimeout(b),b=setTimeout(g,f||d))};this.setInterval=function(f,h){d=1E3*f|0;c=1E3*h|0};this.stop=function(){clearTimeout(b);d=0}}};navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;
hi5.audio={recordable:!!navigator.getUserMedia||!!navigator.mediaDevices,playable:!(!window.AudioContext&&!window.webkitAudioContext),_resumeListener:function(a){hi5.audio.__audioCtx&&"suspended"===hi5.audio.__audioCtx.state&&hi5.audio.__audioCtx.resume();document.removeEventListener("click",hi5.audio._resumeListener,!1)},__audioCtx:null,getAudioContext:function(){return window.AudioContext?new AudioContext:window.webkitAudioContext?new webkitAudioContext:null},downsample:function(a,e){if(1==e)return a;
for(var g=Math.round(a.length/e),b=new Float32Array(g),d=0;d<g;d++)b[d]=a[d*e|0];return b},releaseAudioContext:function(){hi5.audio.__audioCtx&&(hi5.audio.__audioCtx.__refCount&&hi5.audio.__audioCtx.__refCount--,!hi5.audio.__audioCtx.__refCount||1>hi5.audio.__audioCtx.__refCount)&&(hi5.audio.__audioCtx.close&&hi5.audio.__audioCtx.close(),hi5.audio.__audioCtx=null)},Recorder:function(a){function e(v){n=!0;v.getAudioTracks()[0].getSettings().sampleRate&&(l=v.getAudioTracks()[0].getSettings().sampleRate,
console.log("ctx sampleRate:"+a.sampleRate+" settings:"+v.getAudioTracks()[0].getSettings().sampleRate));m=l/r.nSamplesPerSec;if(k.onopen)k.onopen(!0);w=new MSGSMEncoder;c=v;f=a.createMediaStreamSource(v);var x=1==r.formatTag;h=a.createScriptProcessor?a.createScriptProcessor(1024,1,1):a.createJavaScriptNode(1024,1,1);var y=null,z=null;x&&!y&&(y=new Int16Array(2*Math.round(1024/m)),z=new Uint8Array(y.buffer));h.onaudioprocess=function(A){if(d){A=A.inputBuffer.getChannelData(0);var C=A.length;if(x){var E=
0;if(1==m)for(var u=0;u<C;u++){var B=32767*A[u];y[E++]=B;y[E++]=B}else{var D=p(A,m);C=D.length;4*C!=z.length&&console.log("errr len");for(u=0;u<C;u++)B=32767*D[u],y[E++]=B,y[E++]=B}_recorder.ondata(z,z.length)}else t.addData(A,m);A.fill(0)}};f.connect(h);h.connect(a.destination)}function g(v){d=n=!1;if(k.onopen)k.onopen(!1);svGlobal.logger.warn("Error on getUserMedia: "+v)}function b(){d||(c&&c.getTracks&&c.getTracks()[0].stop(),h&&h.disconnect(),f&&f.disconnect(),n=!1)}var d=!1,c=null,f=null,h=null,
k=this,l=a.sampleRate,m=l/22050,n=!1,q=0;k=this;var r=null,w=null,p=hi5.audio.downsample;this.start=function(v,x){r=v;t.init(65*Math.round(x/2/160));q&&clearTimeout(q);if(!n)navigator.mediaDevices?navigator.mediaDevices.getUserMedia({audio:!0}).then(e).catch(g):navigator.getUserMedia({audio:!0},e,g);else if(k.onopen)k.onopen(!0);d=!0};this.stop=function(){d=!1};this.close=function(){d=!1;t&&t.reset();w=new MSGSMEncoder;q=setTimeout(b,3E5)};var t=new function(){function v(u){for(var B=z/160|0,D=0;D<
B;D++){var F=w.encode(u,y,E,A);A+=F;A==C&&(A=0,k.ondata(E,C));y+=160;z-=160}x=0<z?u:null}var x=null,y=0,z=0,A=0,C=65*Math.floor(Math.floor(Math.floor(4096/m)/160)/2),E=new Uint8Array(C);this.init=function(u){C=Math.max(u,65);console.log("nSingle:"+C);E=new Uint8Array(C);svGlobal.logger.info("rec buffer size: "+u)};this.reset=function(){z=y=A=0;x=null};this.addData=function(u,B){u=p(u,B);if(0==z)z=u.length,y=0,v(u);else{B=z+u.length;var D=new Float32Array(B);D.set(x.subarray(y));D.set(u,z);y=0;z=B;
v(D)}}}},WorkletRecorder:function(a,e){function g(l){var m=a.sampleRate;l.getAudioTracks()[0].getSettings().sampleRate&&(m=l.getAudioTracks()[0].getSettings().sampleRate,console.log("ctx sampleRate:"+a.sampleRate+" settings:"+l.getAudioTracks()[0].getSettings().sampleRate));m/=f.nSamplesPerSec;if(this.onopen)this.onopen(!0);c=l;d=a.createMediaStreamSource(l);var n=1==f.formatTag;l=0;h&&(n?l=h*f.nChannels:(l=65*Math.round(h/2/160),65>l&&(l=65)));n=new window.AudioWorkletNode(a,"sv_record_worklet");
n.port.onmessage=function(q){this.ondata(q.data,q.data.length)}.bind(this);console.log("set node parameter");d.connect(n);n.connect(a.destination);n.port.postMessage({type:"start",rate:m,formatTag:f.formatTag,length:l})}function b(l){c=null;if(this.onopen)this.onopen(!1);svGlobal.logger.warn("Error on getUserMedia: "+l)}var d=null,c=null,f=null,h=0,k=null;a.audioWorklet.addModule(e).then(function(){console.log("loading complete: "+e)});this.start=function(l,m){console.log("xxx start");f=l;h=m;navigator.mediaDevices?
navigator.mediaDevices.getUserMedia({audio:!0}).then(g.bind(this)).catch(b.bind(this)):navigator.getUserMedia({audio:!0},g,b)};this.stop=function(){console.log("xxx stop");k&&(k.port.postMessage({type:"stop"}),k.disconnect());c&&c.getTracks&&c.getTracks()[0].stop();d&&d.disconnect();d=c=k=null};this.close=function(){console.log("xxx close");this.stop()}}};
hi5.audio.recordable&&(hi5.browser.isChrome||hi5.browser.isSafari)&&"https:"!=document.location.protocol&&"localhost"!=location.hostname&&"127.0.0.1"!=location.hostname&&(hi5.audio.recordable=!1);navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices().then(function(a){hi5.audio.recordable&&(hi5.audio.recordable=a.some(function(e){return"audioinput"==e.kind}))}).catch(function(a){});
hi5.video={webcam:function(){navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices&&navigator.mediaDevices.enumerateDevices().then(function(a){a.forEach(function(e){"videoinput"==e.kind&&(hi5.video.webcam=e)})});return null}(),resolutions:function(a){function e(k){d.video.width.exact=k.width;d.video.height.exact=k.height;navigator.mediaDevices.getUserMedia(d).then(function(l){l=l.getVideoTracks()[0].getSettings().frameRate;b.push({width:k.width,height:k.height,frameRate:l});c--;0==c&&a(b)}).catch(function(l){c--;
0==c&&a(b)})}for(var g=[{width:1920,height:1080},{width:1280,height:720},{width:1024,height:768},{width:960,height:540},{width:848,height:480},{width:800,height:600},{width:640,height:480},{width:640,height:360},{width:424,height:240},{width:352,height:288},{width:352,height:240},{width:320,height:240},{width:320,height:180}],b=[],d={video:{width:{exact:0},height:{exact:0}}},c=g.length,f=0,h=g.length;f<h;f++)e(g[f])}};
hi5.EventControl=function(a){a.addEvent=function(e,g){a[e]&&a[e]._evt_listeners||(a[e]=function(){a.fireEvent(e,arguments)},a[e]._evt_listeners=[]);a[e]._evt_listeners.push(g)};a.removeEvent=function(e,g){if(!a[e]&&!a[e]._evt_listeners)return!1;e=a[e]._evt_listeners;g=e.indexOf(g);return-1<g?(e.removeElm(g),!0):!1};a.fireEvent=function(e,g){if(a[e]&&a[e]._evt_listeners){e=a[e]._evt_listeners;g||(g=[]);for(var b=[],d=0,c=e.length;d<c;d++)b.push(e[d].apply(a,g));return b}};return a};
hi5.ui=hi5.ui||{};hi5.ui.initAs=function(a,e){var g=a["data-h5-ui"];if(!g)return a["data-h5-ui"]=e,!0;if(-1!=hi5.string.seperatedStr.indexOf(g,e))return!1;a["data-h5-ui"]=g+","+e;return!0};hi5.ui.clean=function(a){a["data-h5-ui"]&&(a["data-h5-ui"]="")};hi5.ui.confirm=function(a){return hi5.browser.isChromeApp?!0:confirm(a)};
hi5.ui.addInputListener=function(a,e){var g=!1,b=!1;a.addEventListener("keydown",function(d){console.log("--",d);b&&(b=!1);"Process"==d.key||229==d.keyCode||g||e(d)});a.addEventListener("keyup",function(d){console.log("--",d);"Process"==d.key||229==d.keyCode||g||b||e(d)});a.addEventListener("input",function(d){console.log("--",d);g||b||e(d)});a.addEventListener("compositionstart",function(d){console.log("--start:");g=!0});a.addEventListener("compositionend",function(d){console.log("--end:"+d.data);
g=!1;e(d);b=!0})};hi5.chromeapp={convertLink:function(a){for(var e=0,g=a.length;e<g;e++)a[e].onclick=function(b){b=b.target.href;var d=b.lastIndexOf("/");-1!=d&&(b=b.substring(d+1));chrome.app.window.create(b,{left:window.screenLeft+20,top:window.screenTop+20,width:window.innerWidth,height:window.innerHeight});return!1}}};
hi5.Draggable=function(a,e,g,b,d,c){var f,h;function k(p){r=f=!1;var t=p.touchs||p.changedTouches;if(t){if(1!=t.length)return;p=t[0]}else if(0!=p.button)return;n=hi5.tool.getPos(a);h=p.pageX;q=p.pageY;f=!0}function l(p){if(f&&(p=p.touchs&&p.touchs[0]||p.changedTouches&&p.changedTouches[0]||p,!(3>Math.abs(h-p.pageX)&&3>Math.abs(q-p.pageY)))){r||(r=!0,g&&g(p));if(b){var t=b(p);t&&(p=t)}t=n.x+p.pageX-h;p=n.y+p.pageY-q;0>t&&(t=0);t>window.innerWidth-a.offsetWidth&&(t=window.innerWidth-a.offsetWidth);
0>p&&(p=0);p>window.innerHeight-a.offsetHeight&&(p=window.innerHeight-a.offsetHeight);a.style.left=t+"px";a.style.top=p+"px"}}function m(p){f&&(f=!1,p=p.touchs&&p.touchs[0]||p.changedTouches&&p.changedTouches[0]||p,r?d&&d(p):c&&c(p),r=!1)}e=e||a;e.draggable=!1;if(!hi5.ui.initAs(e,"Draggable"))return e;var n=null;var q=h=0;var r=f=!1;var w=hi5.browser.isTouch;e.addEventListener("touchstart",k,!1);e.addEventListener("mousedown",k,!1);document.addEventListener("touchmove",l,!1);document.addEventListener("mousemove",
l,!1);e.addEventListener("touchmove",l,!1);e.addEventListener("mousemove",l,!1);document.addEventListener("touchend",m,!1);document.addEventListener("mouseup",m,!1);e.addEventListener("touchend",m,!1);e.addEventListener("mouseup",m,!1);w&&(document.addEventListener("touchcancel",m,!1),e.addEventListener("touchcancel",m,!1));return a};
hi5.Fadable=function(a,e,g,b){function d(){document.activeElement==a||document.activeElement==a.activeObj?setTimeout(d,l):a.style.display="none"}function c(){m&&clearTimeout(m);m=setTimeout(function(){a.beforeDisplay&&a.beforeDisplay();a.style.display=b;n&&(m&&clearTimeout(m),m=setTimeout(d,l))},88);return!1}function f(q){m&&clearTimeout(m)}function h(q){c()}if(!hi5.ui.initAs(a,"Fadable"))return a;0>a.tabIndex&&(a.tabIndex=999);var k=g||document;b=b||"block";var l=e||3E3,m=0,n=!0;a.setFadable=function(q){(n=
q)?(q="mouseup",navigator.pointerEnabled?q="pointerup":navigator.msPointerEnabled?q="MSPointerUp":hi5.browser.isTouch&&(q="touchend"),k.addEventListener(q,c,!1),k.addEventListener("mouseup",c,!1),a.addEventListener("mouseenter",f,!1),a.addEventListener("mouseleave",h,!1)):(a.style.display=b,a.removeEventListener("mouseenter",f,!1),a.removeEventListener("mouseleave",h,!1))};a.startFade=c;return a};
hi5.cancelDefault=function(a){a.preventDefault&&a.preventDefault();a.stopPropagation&&a.stopPropagation();return!1};
hi5.Toolbar=function(a,e,g){if(e){var b=(e=a.querySelector("#svImgHandle"))||document.createElement("img");e||(b.style.cursor="move",b.style.width="11px",b.src=g,b.id="svImgHandle",a.appendChild(b));hi5.Draggable(a,b)}a.addButton=function(d,c,f){var h=document.createElement("img");h.src=d;hi5.browser.isTouch?navigator.msMaxTouchPoints||h.addEventListener("touchend",c,!1):h.addEventListener("click",c,!1);h.className="h5-img-btn";a.appendChild(h);f&&(h.id=f,h.name=f);return h};a.getButton=function(d){for(var c=
a.getElementsByTagName("img"),f=c.length,h=0;h<f;h++)if(c[h].id==d||c[h].name==d)return c[h];return null};a.removeButton=function(d){for(var c=a.getElementsByTagName("img"),f=c.length,h=0;h<f;h++)if(c[h].id==d||c[h].name==d){a.removeChild(c[h]);break}};g=a.getElementsByTagName("img");e=g.length;for(b=0;b<e;b++)g[b].className="h5-img-btn";return a};
hi5.ProgressBar=function(a){a.progress=0;a.maxValue=0;var e=a.getElementsByTagName("div")[0];a.setProgress=function(g){g=Math.floor(g/a.maxValue*100);g!=a.progress&&(a.progress=g,e.style.width=g/100*a.offsetWidth+"px")};return a};
hi5.Lightbox=function(a,e,g,b){function d(){var h=(c.clientWidth-a.offsetWidth)/2,k=(c.clientHeight-a.offsetHeight)/3;0>h&&(h=0);0>k&&(k=0);a.style.left=h+"px";a.style.top=k+"px"}var c=document.createElement("div");c.id="divBackground";c.style.position="fixed";c.style.left=0;c.style.top=0;c.style.width="100%";c.style.height="100%";c.style.zIndex=999;c.style.backgroundColor=g?g:"#222";e||(e=.4);1>e&&(c.style.opacity=e);a.style.position="absolute";a.style.zIndex=1E3;a.style.visibility="hidden";var f=
document.createElement("img");f.width=25;f.height=25;f.src=hi5.tool.getImage("del","del.png");f.className="h5-img-btn";f.style.cursor="pointer";f.align="top";f.style.position="absolute";b?(f.style.top="-20px",f.style.right="-15px"):(f.style.top="0px",f.style.right="0px");a.resize=d;a.show=function(){document.body.appendChild(c);a.appendChild(f);a.style.display="block";a.style.visibility="visible";d();if(a.onopen)a.onopen(a)};a.visible=function(){return a&&"visible"==a.style.visibility};a.dismiss=
function(h){function k(){document.body.removeChild(c);a.removeChild(f);a.style.display="none";a.style.visibility="hidden";if(a.onclose)a.onclose()}"number"==typeof h?setTimeout(k,h):k()};a.background=c;f.addEventListener("click",a.dismiss,!1);return a};
hi5.ui.Lightbox=function(a,e){function g(){var m=(window.innerWidth-a.clientWidth)/2|0,n=(window.innerHeight-a.clientHeight)/3|0;a.style.borderWidth=n+"px "+m+"px "+2*n+"px "+m+"px"}function b(m){27==m.keyCode&&d()}function d(){var m=a.style;m.boxSizing=c.boxSizing;m.top=c.top;m.left=c.left;m.borderWidth=c.borderWidth;m.borderColor=c.borderColor;m.borderStyle=c.borderStyle;m.zIndex=c.zIndex;m.position=c.position;m.display="none";f=!1;h&&h.parentNode&&h.parentNode.removeChild(h);k&&k.parentNode&&k.parentNode.removeChild(k);
document.removeEventListener("keydown",b,!1);l&&l.onclose&&(l.onclose(),l=null)}var c=null,f=!1;e=e||{};void 0==e.backgroundColor&&(e.backgroundColor="#333");void 0==e.zIndex&&(e.zIndex=999);var h=null;!0!==e.noClose&&(h=document.createElement("img"),h.width=25,h.height=25,h.src=hi5.tool.getImage("del","del.png"),h.className="h5-img-btn",h.style.cursor="pointer",h.align="top",h.style.position="absolute",e.close?(h.style.top=e.close.top,h.style.right=e.close.right):(h.style.top=0,h.style.right=0));
var k=null;e.btnYes&&(k=document.createElement("button"),e.btnYes.id&&(k.id=k.id),k.innerHTML=e.btnYes.label||"Ok",k.style="float: right");this.resize=g;var l=null;this.show=function(){var m=a.style;l=this;c={boxSizing:m.boxSizing,position:m.position,top:m.top,left:m.left,borderWidth:m.borderWidth,borderColor:m.borderColor,display:m.display,zIndex:m.zIndex,borderStyle:m.borderStyle,opacity:m.opacity};m.boxSizing="content-box";m.position="absolute";m.display="block";m.borderStyle="solid";m.borderColor=
e.backgroundColor;m.top=0;m.left=0;m.zIndex=e.zIndex;g();window.addEventListener("resize",g,!1);f=!0;h&&a.appendChild(h);k&&(a.appendChild(k),k.onclick=e.btnYes.onclick||d);document.addEventListener("keydown",b,!1);if(this.onopen)this.onopen()};this.visible=function(){return f};this.dismiss=d;h&&h.addEventListener("click",d,!1)};
hi5.canvas={TextSelect:function(a,e,g,b,d){d||(d=a.canvas.width-1);e--;this.clear=function(){a.clearRect(0,0,a.canvas.width,a.canvas.height)};this.draw=function(c,f,h,k){k>f?k-f<e&&(k=f+e):f-k<e&&(k=f-e);a.fillStyle=g||"#61D2D6";a.beginPath();a.moveTo(c,f);a.lineTo(d,f);a.lineTo(d,k-e);a.lineTo(h,k-e);a.lineTo(h,k);a.lineTo(0,k);a.lineTo(0,f+e);a.lineTo(c,f+e);a.lineTo(c,f);a.fill()}}};
hi5.DataTable=function(a){if(hi5.ui.initAs(a,"DataTable")){hi5.EventControl(a);"string"==typeof a&&(a=JSON.parse(a));var e=a.rows,g=a.cols;a.rowNo=-1;a.beforeGetValue=null;a.moveTo=function(b){a.rowNo=b};a.getColNo=function(b){for(var d=0,c=g.length;d<c;d++)if(g[d].name==b)return d;return-1};a.getValue=function(b){var d=e[a.rowNo][b];return a.beforeGetValue?a.beforeGetValue(b,d):d};a.setValue=function(b,d){a.beforeSetValue&&(d=a.beforeSetValue(b,d));e[a.rowNo][b]=d;a.fireEvent("onchange",[b,a.rowNo,
d])};a.first=function(){a.moveTo(0)};a.next=function(){a.moveTo(a.rowNo+1)};a.last=function(){a.moveTo(e.length-1)};a.hasNext=function(){return a.rowNo<e.length-1};a.remove=function(b){b||(b=a.rowNo);var d=[b];a.fireEvent("beforeremove",d);e.splice(b,1);a.fireEvent("onremove",d)};a.perform=function(b){"function"==typeof a[b]?a[b].apply(a):a.fireEvent("onaction",[b])};a.getObject=function(){for(var b={},d=0,c=g.length;d<c;d++)b[g[d].name]=a.getValue(d);return b};a.find=function(b,d){for(var c=0,f=
e.length;c<f;c++)if(e[c][b]==d)return e[c];return null};a.sort=function(b){a.cols[b].sortDir=void 0==a.cols[b].sortDir?-1:-a.cols[b].sortDir;var d=a.cols[b].sortDir;a.rows.length&&(a.rows.sort(function(c,f){return c[b]>f[b]?d:c[b]<f[b]?-d:0}),a.fireEvent("reload"))}}a.fireEvent("onopen");return a};
hi5.DataGrid=function(a,e){function g(k){var l=this.rowIndex;"number"==typeof l&&(d=l-=a.tHead.rows.length,b.moveTo(l));if(a.onrowclick)a.onrowclick(k)}if(!hi5.ui.initAs(a,"DataGrid"))return a;if("TABLE"!=a.nodeName)throw"Not HTML Table";var b=null;a.onrowclick=null;Object.defineProperty(a,"dataTable",{get:function(){return b},set:function(k){b=k;b.addEvent("reload",function(){a.fillData(b)})},enumerable:!0,configurable:!0});var d=-1;a.getValue=function(k){var l=b;l.moveTo(d);return l.getValue(l.getColNo(k))};
a.fillData=function(k){var l=k.rows,m=k.cols;if(l&&m){m=a.tBodies[0];var n;a._rowTemp||(a._rowTemp=a.tBodies[0].rows[0].cloneNode(!0));var q=a._rowTemp;var r=q.cells.length,w=m.cloneNode(!1);var p=l.length;for(n=0;n<p;n++){var t=q.cloneNode(!0);var v=t.cells;k.moveTo(n);for(l=0;l<r;l++)if(!v[l].innerHTML){var x=k.getValue(l);a.beforeDisplayValue&&(x=a.beforeDisplayValue(l,x));e?v[l].innerText=x:v[l].innerHTML=x}d=n;t.addEventListener("click",g,!1);a.beforeAppendRow&&a.beforeAppendRow(t);w.appendChild(t)}a.removeChild(m);
a.appendChild(w)}};a.open=function(){b&&(a.fillData(b),b.addEvent("onremove",function(k){var l=a.tBodies[0];(k=l.rows[k])&&l.removeChild(k)}))};a.clear=function(){if(a._rowTemp){a.removeChild(a.tBodies[0]);var k=document.createElement("tbody");k.appendChild(a._rowTemp);a.appendChild(k)}};for(var c=a.tHead.rows[0].cells,f=c.length,h=0;h<f;h++)c[h].addEventListener("click",function(k){b&&b.sort(k.target.cellIndex)},!1);return a};
hi5.Select=function(a,e,g){if(!hi5.ui.initAs(a,"Select"))return a;var b=a.parentNode,d=document.createElement("div");d.style.padding="0";d.style.display="inline";b.insertBefore(d,a);var c=document.createElement("img");c.src=hi5.tool.getImage("select","select.png");c.height=a.offsetHeight;c.style.verticalAlign="-6px";d.appendChild(a);d.appendChild(c);var f=document.createElement("select");e&&(f.multiple=!0,g||(g=","));b=a.getAttribute("hi5_size");f.size=b?b:10;if(b=a.getAttribute("hi5_list"))if(b=
b.split(";"),d=b.length,0<d)for(var h=f.options,k=0;k<d;k++)h[k]=new Option(b[k]);f.style.position="absolute";f.style.zIndex=99999;f.style.display="none";document.body.appendChild(f);a.show=function(){a.beforedropdown&&a.beforedropdown(a);f.style.display="";f.focus()};a.hide=function(){f.style.display="none";a.focus()};c.onclick=function(){if("none"==f.style.display){if(0==f.options.length){var l=a.getAttribute("onfetchlist");l&&eval(l)}l=hi5.tool.getPos(a,!1);f.style.left=l.x+"px";f.style.top=l.y+
a.offsetHeight+"px";f.style.width=a.offsetWidth+c.width+3+"px";a.show()}else a.hide()};f.onchange=function(){if(e){for(var l=[],m,n=f.options,q=0,r=n.length;q<r;q++)m=n[q],m.selected&&l.push(m.value);a.value=l.join(g)}else a.value=f.value,f.style.display="none";if(a.onchange)a.onchange()};a.options=f.options;return a};hi5.init.push(function(){for(var a=document.getElementsByClassName("Hi5Select"),e=a.length,g=0;g<e;g++)new hi5.Select(a[g])});
hi5.Tab=function(a){function e(m){var n=c;c!=m&&(f[c].className="tab_back",h[c].className="tab_hide",c=m);f[m].className="tab_front";h[m].className="tab_show";f[m].focus();n!=m&&a.fireEvent("ontabchange",[m,n])}function g(m){m=f.indexOf(m.target);-1!=m&&e(m)}if(!hi5.ui.initAs(a,"Tab"))return a;hi5.EventControl(a);for(var b=a.getElementsByClassName("tab")[0].getElementsByClassName("tab_title")[0].childNodes,d=b.length,c=0,f=[],h=[],k=0;k<d;k++){var l=b[k];"SPAN"==l.nodeName.toUpperCase()&&(l.className=
"tab_back",l.onclick=g,l.onfocus=g,f[f.length]=l)}b=a.getElementsByClassName("tab_body")[0].childNodes;d=b.length;for(k=0;k<d;k++)l=b[k],"DIV"==l.nodeName.toUpperCase()&&(h[h.length]=l,l.className="tab_hide");e(c);a.setSelected=e;a.getSelected=function(){return c};return a};hi5.init.push(function(){for(var a=document.getElementsByClassName("tab_all"),e=a.length,g=0;g<e;g++)new hi5.Tab(a[g])});
hi5.Notification=function(a){function e(){a||(a=hi5.$("hi5_notifer_all"),a||(a=document.createElement("div"),a.name=a.id="hi5_notifer_all",a.style.display="none",document.body.appendChild(a)));return a}function g(c){var f=new b(c);e().appendChild(f);a.style.display="block";c.select&&(c=f.getElementsByClassName("hi5_notifer_msg")[0],"TEXTAREA"==c.nodeName?c.select():hi5.browser.selectEditable(c))}function b(c){function f(p,t,v){var x=document.createElement("button");t&&(x.className=t);v&&(x.innerHTML=
v);x.onclick=function(y){p.apply(h,[y])};return x}var h=document.createElement("div");h.className="hi5_notifer slideUp";h.title=c.title;h.msgCount=1;c.name&&(h.msgName=c.name);var k=document.createElement("div");k.className="hi5_notifer_title";var l=document.createElement("span");l.className="hi5_notifer_icon";k.appendChild(l);k.appendChild(document.createTextNode(h.title));h.appendChild(k);k=document.createElement("div");var m=document.createElement("div");m.className="hi5_notifer_msg";m.style.width=
"100%";h.setMessage=function(p){h.message=p.msg;!0===p.html?m.innerHTML=p.msg:m.innerText=p.msg};h.setMessage(c);k.appendChild(m);var n=document.createElement("span");n.className="hi5_notifer_count";h.setCount=function(p){h.msgCount=p;n.innerHTML=1<p?"("+h.msgCount+")":""};c.count&&h.setCount(c.count);k.appendChild(n);h.appendChild(k);c.cbNo&&h.appendChild(f(c.cbNo,"hi5_notifer_button_no"));c.cbYes&&h.appendChild(f(c.cbYes,"hi5_notifer_button_yes"));if(c.buttons){k=document.createElement("div");k.className=
"hi5_float";l=0;for(var q=c.buttons.length;l<q;l++){var r=c.buttons[l];k.appendChild(f(r.onclick,r.className,r.label))}h.appendChild(k)}h.destroy=function(){if(h.parentNode){h.parentNode.removeChild(h);var p=d.notifyPool.shift();if(p)g(p);else if(0==d.notifySize()&&(a.style.display="none",d.onempty))d.onempty();c.cbClose&&c.cbClose()}};if(c.timeout){var w=setTimeout(function(){h.destroy()},c.timeout);h.addEventListener("mouseover",function(){clearTimeout(w)},!1)}c.onclick?h.onclick=c.onclick:c.cbYes||
c.cbNo||(h.onclick=h.destroy);return h}this.notifyPool=[];var d=this;this.notify=function(c){c="string"==typeof c?{msg:c,title:"",count:1,type:0}:c;c.title||(c.title="");c.count||(c.count=1);if(!d.onnotify||!d.onnotify(c)){var f=hi5.tool.getChildNodesByTag(e(),"div"),h=f.length;if(0<h)if(3==c.type)for(var k=h;0<k;){k--;var l=f[k];if(l.msgName==c.name){l.message!=c.msg?(l.setMessage(c),l.setCount(1)):l.setCount(l.msgCount+1);return}}else if(l=f[h-1],!l.msgName&&l.title==c.title&&l.message==c.msg){l.setCount(l.msgCount+
1);return}if(3>h)g(c);else{f=d.notifyPool;h=f.length;if(0<h)if(3==c.type)for(;0<h;)h--,f[h].name==c.name&&(f[h].msg!=c.msg?(f[h].msg=c.msg,f[h].count=0):f[h].count++);else if(h=f[h-1],!h.name&&h.title==c.title&&h.msg==c.msg){h.count++;return}f.push(c)}}};this.notifySize=function(){return hi5.tool.getChildNodesByTag(e(),"div").length};this.clearAll=function(){d.notifyPool.length=0;for(var c=e();c.hasChildNodes();)c.removeChild(c.firstChild)}};hi5.notifications=new hi5.Notification;
hi5.file={readAsArrayBuffer:function(a,e){var g=new FileReader;g.onloadend=function(b){e(new Uint8Array(b.target.result))};g.readAsArrayBuffer(a)},getEntries:function(a){var e=a.target&&(a.target.webkitEntries||a.target.entries||[]);if(!e.length&&(a=a.dataTransfer&&a.dataTransfer.items))for(var g=0,b;b=a[g];++g)if("file"==b.kind){if(!b.webkitGetAsEntry&&!b.getAsEntry)break;b=b.getAsEntry?b.getAsEntry():b.webkitGetAsEntry();if(!b)break;e.push(b)}return e},getFilesFromEntries:function(a,e){function g(){c--;
c||e(f)}function b(h){return function(k){k.fullPath=h;f.push(k);g()}}function d(h){var k=h.length;c+=k;for(var l=0;l<k;l++){var m=h[l];m.isFile?m.file(b(m.fullPath),function(n){console.log(n);g()}):m.isDirectory&&m.createReader().readEntries(function(n){n.length&&d(n);g()},function(){g()})}}var c=0,f=[];d(a)},DirectoryReader:function(a){function e(d,c){var f=d.createReader(),h=[],k=function(){f.readEntries(function(l){l.length?(h=h.concat(Array.prototype.slice.call(l||[],0)),k()):c(h)})};k()}function g(d){for(var c=
0,f=d.length;c<f;c++){var h=d[c];h.isFile?h.file(function(k){return function(l){b.onfile(l,k)}}(h.fullPath)):h.isDirectory&&e(h,function(k){g(k)})}}var b=this;this.start=function(){g(a)}},UploadManager:function(a){var e={},g=0,b=a;this.canCopyFile=!1;this.enabled=!0;hi5.EventControl(this);var d=this,c=null,f=0,h=!0,k=!0,l=!1;this.setDownload=function(m){h=m};this.setUpload=function(m){k=m};this.release=function(){e=b=a=d=null};this.read=function(m,n,q){var r=e[e[m]];if("undefined"!=typeof r&&!(1>
r.size&&__svi18n.file.zero)){var w=r.slice(n,n+q),p=new FileReader;p.onloadend=function(t){t.target.readyState==FileReader.DONE&&(t=new Uint8Array(t.target.result),a.send(m,n,q,t,r.preferPaste),g+=q,d.fireEvent("progress",[g]))};p.readAsArrayBuffer(w)}};this.mkdirs=function(m){d.enabled&&("/"!=m.charAt(m.length-1)&&(m+="/"),a.start([m],0,!0))};this.addFiles=function(m,n){var q=m.length;if(q&&d.enabled&&k){l=n&&d.canCopyFile;n=[];f=Date.now();for(var r=0;r<q;r++){var w=m[r];l&&(w.preferPaste=!0);var p=
w.fullPath||w.name;-1==d.fireEvent("beforeupload",[w,p,l]).indexOf(!0)&&(n.push(m[r]),p=encodeURIComponent(p),e[p]=w)}0<n.length?(a.start(n,l),d.fireEvent("uploadstarted",[l])):d.fireEvent("uploaded",[l,{size:0,duration:0}])}};this.removeFile=function(m,n){b.remove(m,n)};this.confirmId=function(m,n,q){e[m]=n;q&&(g+=parseInt(q))};this.close=function(m,n){var q=l;n={size:g,duration:Date.now()-f,cancelled:n};if(m){var r=e[m];r&&(q=e[r].preferPaste||!1,delete e[m],delete e[r],m=decodeURIComponent(r),
d.fireEvent("fileuploaded",[m,q&&d.canCopyFile,n]));for(var w in e)return}else e={};f=g=0;d.fireEvent("uploaded",[q&&d.canCopyFile,n])};this.cancelAll=function(){b.cancelAll();d.fireEvent("uploadingCancelled");d.close(null,!0)};this.list=function(m,n){c=n;b.list(m)};this.notifyFiles=function(m){c&&c(m);d.fireEvent("files")};this.download=function(){h&&b.download()}},WsFileService:function(a){function e(g,b,d){var c=b.length,f=new Uint8Array(2+2*c);f[0]=58;f[1]=d?g|128:g;d=2;for(var h=0;h<c;h++)g=
b.charCodeAt(h),f[d++]=g&255,f[d++]=g>>8&255;a(f.buffer)}this.start=function(g,b,d){for(var c=g.length,f=20*c+2,h=0,k=new Uint8Array(8),l=2,m,n,q,r;h<c;h++)f=d?f+2*(encodeURIComponent(g[h]).length+1):f+2*(encodeURIComponent(g[h].fullPath||g[h].name).length+1);f=new Uint8Array(f);f[0]=58;f[1]=0;b&&(f[1]|=128);for(h=0;h<c;h++){b=d?0:g[h].size;f[l++]=b&255;f[l++]=b>>8&255;f[l++]=b>>16&255;f[l++]=b>>24&255;4294967296>b?l+=4:(m=hi5.NumUtils.splitInt64(b).high,f[l++]=m&255,f[l++]=m>>8&255,f[l++]=m>>16&
255,f[l++]=m>>24&255);d||hi5.NumUtils.toBytes(g[h].lastModified||g[h].lastModifiedDate.getTime(),k);f.set(k,l);l+=12;m=encodeURIComponent(d?g[h]:g[h].fullPath||g[h].name);n=m.length;for(q=0;q<n;q++)r=m.charCodeAt(q),f[l++]=r&255,f[l++]=r>>8&255;l+=2;svGlobal.logger.info("upload file: "+m+" size:"+b)}a(f.buffer)};this.send=function(g,b,d,c,f){svGlobal.logger.debug("send file, id:"+g+" offset:"+b+" len:"+d);var h=new Uint8Array(22+d);h[0]=58;h[1]=3;f&&(h[1]|=128);f=2;h[f++]=g&255;h[f++]=g>>8&255;h[f++]=
g>>16&255;h[f++]=g>>24&255;h[f++]=b&255;h[f++]=b>>8&255;h[f++]=b>>16&255;h[f++]=b>>24&255;4294967296>b?f+=4:(b=hi5.NumUtils.splitInt64(b).high,h[f++]=b&255,h[f++]=b>>8&255,h[f++]=b>>16&255,h[f++]=b>>24&255);h[f++]=d&255;h[f++]=d>>8&255;h[f++]=d>>16&255;h[f++]=d>>24&255;h.set(c,f+4);a(h.buffer)};this.remove=function(g,b){e(6,g,b)};this.list=function(g){e(5,g)};this.cancelAll=function(){e(7,"")};this.download=function(){e(136,"")}}};
hi5.Chat=function(a,e){function g(k,l,m){var n=document.createElement("span");n.className=l;n.innerHTML=k;m.appendChild(n);return n}function b(){var k=c.value;h.add(k,e);c.value="";if(h.onchat)h.onchat(k,e)}var d=hi5.$("chatHistory"),c=hi5.$("chatText"),f=hi5.$("chatSend"),h=this;this.add=function(k,l){var m=document.createElement("div");g((l||e)+":","chatFrom",m);g(k,"chatMsg",m);k=new Date;g(k.getHours()+":"+k.getMinutes()+":"+k.getSeconds(),"chatTime",m);"block"!=a.style.display&&(a.style.display=
"block");d.appendChild(m);d.scrollTop=d.scrollHeight};c.addEventListener("keydown",function(k){13==k.keyCode&&b()},!1);f.addEventListener("click",b,!1)};document.addEventListener("DOMContentLoaded",hi5.init.start,!1);
