var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(f,k,g){if(null==f)throw new TypeError("The 'this' value for String.prototype."+g+" must not be null or undefined");if(k instanceof RegExp)throw new TypeError("First argument to String.prototype."+g+" must not be a regular expression");return f+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,k,g){if(f==Array.prototype||f==Object.prototype)return f;f[k]=g.value;return f};
$jscomp.getGlobal=function(f){f=["object"==typeof globalThis&&globalThis,f,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var k=0;k<f.length;++k){var g=f[k];if(g&&g.Math==Math)return g}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(f,k){var g=$jscomp.propertyToPolyfillSymbol[k];if(null==g)return f[k];g=f[g];return void 0!==g?g:f[k]};$jscomp.polyfill=function(f,k,g,e){k&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(f,k,g,e):$jscomp.polyfillUnisolated(f,k,g,e))};
$jscomp.polyfillUnisolated=function(f,k,g,e){g=$jscomp.global;f=f.split(".");for(e=0;e<f.length-1;e++){var c=f[e];if(!(c in g))return;g=g[c]}f=f[f.length-1];e=g[f];k=k(e);k!=e&&null!=k&&$jscomp.defineProperty(g,f,{configurable:!0,writable:!0,value:k})};
$jscomp.polyfillIsolated=function(f,k,g,e){var c=f.split(".");f=1===c.length;e=c[0];e=!f&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var a=0;a<c.length-1;a++){var d=c[a];if(!(d in e))return;e=e[d]}c=c[c.length-1];g=$jscomp.IS_SYMBOL_NATIVE&&"es6"===g?e[c]:null;k=k(g);null!=k&&(f?$jscomp.defineProperty($jscomp.polyfills,c,{configurable:!0,writable:!0,value:k}):k!==g&&($jscomp.propertyToPolyfillSymbol[c]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(c):$jscomp.POLYFILL_PREFIX+c,c=
$jscomp.propertyToPolyfillSymbol[c],$jscomp.defineProperty(e,c,{configurable:!0,writable:!0,value:k})))};$jscomp.polyfill("String.prototype.startsWith",function(f){return f?f:function(k,g){var e=$jscomp.checkStringArgs(this,k,"startsWith");k+="";var c=e.length,a=k.length;g=Math.max(0,Math.min(g|0,e.length));for(var d=0;d<a&&g<c;)if(e[g++]!=k[d++])return!1;return d>=a}},"es6","es3");
function showTwoFAQR(f,k){var g=hi5.$("twofainfo");if(g){var e=hi5.$("barcodeDiv"),c=hi5.$("enableTwoFA"),a=hi5.$("disableTwoFA");k?(hi5.$("imgBarcode").src="data:image/png;base64,"+k,e.style.display="block",a.style.display="none",c.style.display="block"):(e.style.display="none",a.style.display="block",c.style.display="none");var d=new hi5.ui.Lightbox(g);d.show();hi5.$("faCode").focus();hi5.$("faCode").value="";c.onclick=a.onclick=function(m){var b=hi5.$("faCode").value;m=m.target==c?1:0;if(6!=b.length)hi5.notifications.notify(__svi18n.info.digit6||
"It must be a 6 digit number");else{var l=g.querySelector('input[name="pwd"]');f(b,m,l?l.value:"");d.dismiss()}}}}
svGlobal.auth=new function(){function f(a){hi5.tool.enableInput();if(a.error)svGlobal.gatewayError(a.name,a.message||a.msg);else{hi5.$("frmLogin").style.display="none";hi5.$("frmConn").style.display="block";var d=document.getElementById("pwdZone");d&&(d.style.display=a.isDomainUser?"none":"table-row-group");a.isDomainUser&&!a.twoFAEnabled&&(d=document.getElementById("settings"))&&(d.style.display="none");for(d=hi5.$("programs");d.hasChildNodes();)d.removeChild(d.firstChild);var m=a.servers;if(!a.accessNotInList){var b=
hi5.$("anyconn");b&&(b.style.display="none")}if(a.hash){b=hi5.$("gateway").value;var l=b.indexOf(":");-1!=l&&(b=b.substring(0,l));b.toLowerCase().startsWith("www.")&&(b=b.substring(4));document.cookie="__SV_TOKEN_S="+a.hash+"-"+encodeURIComponent(a.name)+";domain=."+b}b=svGlobal.auth.getUserName(hi5.$("user").value);window.__sparkUser={session:a.session,account:b,gateway:hi5.$("gateway").value,servers:m,twoFA:a.twoFA,twoFAEnabled:a.twoFAEnabled,twoFAQR:a.twoFAQR};a=m.length;if(!(1>a)){b="";for(l=
0;l<a;l++){var q=m[l].server,n=m[l].id;q=m[l].displayName||n||q;var h=m[l].icon;h||(h="rdp32.png");var p=document.createElement("div");p.className="icon";var t=document.createElement("img");t.src=h;t.id=n;t.alt=n;t.title=q;t.style.cursor="pointer";t.onclick=k;p.appendChild(t);p.appendChild(document.createElement("br"));p.appendChild(document.createTextNode(q));d.appendChild(p);hi5.appcfg.startup&&n===hi5.appcfg.startup.server&&(b=n)}!b&&hi5.appcfg.startup&&(console.log("start up:"+hi5.appcfg.startup.server+
" not found, use the first instead"),b=m[0].id);b&&g(b,!hi5.appcfg.startup.newWindow,!0)}}}function k(a){var d=a.target;d.onclick=null;setTimeout(function(){d.onclick=k},300);g(d.id)}function g(a,d,m){var b=window.__sparkUser,l=b.servers,q=l.length;b.server=null;window.sparkGateway=b.gateway;for(var n=0;n<q;n++){var h=l[n];if(a==h.id){h.gateway=b.gateway;h.session=b.session;h.account=b.account;b.server=h;break}}if(b.server){console.log("connecting to:"+b.server.id);(a=hi5.$("touchpad"))&&a.checked&&
(b.server.touchpad=!0);if(a=hi5.$("keyboard"))a=parseInt(a.options[a.selectedIndex].value),0<a&&(b.server.keyboard=a);if(svGlobal.auth.onconnect)svGlobal.auth.onconnect(b.server);b.server.rdp&&b.server.rdp.remoteProgram&&(b.server.startProgram="app");a="default"==hi5.appcfg.newWindow?void 0:"width="+window.outerWidth+",height="+window.outerHeight;if(b.server.http)d=location.protocol+"//"+b.server.id+"."+b.gateway,b.server.http.path&&(d+=b.server.http.path),window.open(d,"_blank",a);else if(l="app"==
b.server.startProgram,void 0==d&&(d=l),d){var p=svManager.getInstance();if(l&&p&&p.running())p.startApp(b.server.exe||b.server.rdp.remoteProgram,b.server.args||b.server.rdp.remoteArgs,""),c&&c.visible()&&c.dismiss();else{var t=function(r){function w(){null==c&&(c=new hi5.ui.Lightbox(hi5.$("login")));c.visible()?c.dismiss():c.show()}var v=r.toolbar.querySelector("#__sv_btn_home");v||(v=r.toolbar.addButton(hi5.appcfg.img.home||"home.png",w),v.id="__sv_btn_home")};p=new Rdp2(b.server);hi5.$("login").style.display=
"none";var u=new svGlobal.LocalInterface;u.onremoteappicon=function(r,w){if(u.toolbar&&r.isMainWin()&&32==w.getWidth()){var v="win"+r.id;if(!u.toolbar.querySelector("#"+v)){t(u);var x=u.toolbar.addButton(w.getDataURL(),function(){r.activate(1)});x.id=v;x.title=r.titleInfo;x.style.width="32px";x.style.height="32px";x.addEventListener("mouseover",function(){x.title=r.titleInfo},!1);setTimeout(function(){r.activate(1)},333)}}};u.onremoteappclose=function(r){u.toolbar&&(r=u.toolbar.querySelector("#win"+
r.id))&&u.toolbar.removeChild(r)};p.addSurface(u);p.run();p.onclose=function(){m?showLogDlg():(p.hide(),hi5.$("login").style.display="block")}}}else d=document.getElementById("multiMon"),b.server.rdp?(b.server.rdp.multiMon=d&&d.checked?"on":"off",window.open("rdpdirect.html","_blank",a)):b.server.vnc?window.open("vnc.html","_blank",a):b.server.ssh?window.open("sshdirect.html","_blank",a):b.server.telnet&&window.open("telnet.html","_blank",a)}else hi5.notifications.notify("Not a valid server")}var e=
this,c=null;this.getLoginURL=function(){return("https:"==location.protocol?"wss://":"ws://")+hi5.$("gateway").value+"/LOGIN?"};this.closeSession=function(a,d){console.log("close session "+d+" on user "+a);window.__sparkUser&&(a||(a=window.__sparkUser.account),d||(d=window.__sparkUser.session));a&&d&&(a=svGlobal.auth.getLoginURL()+"action=close&user="+encodeURIComponent(a)+"&svSession="+d,(new WebSocket(a,"login")).onopen=function(m){console.log("Sign out");window.__sparkUser=null})};this.showLogDlg=
function(){if(hi5.appcfg&&hi5.appcfg.returnUrl)window.location.href=hi5.appcfg.returnUrl;else{var a=window.__sparkUser.account,d=window.__sparkUser.session;window.__sparkUser=null;var m=hi5.$("frmLogin");m.elements.pwd.value="";m.style.display="block";hi5.$("frmConn").style.display="none";(m=svManager.getInstance())&&m.running()&&m.close();svGlobal.auth.closeSession(a,d)}};this.getUserName=function(a){hi5.appcfg&&hi5.appcfg.domain&&(a.toLowerCase().startsWith(hi5.appcfg.domain.toLowerCase()+"\\")||
(a=hi5.appcfg.domain+"\\"+a));return a};this.login=function(a){function d(l,q){window.__sparkUser=null;if(!e.beforelogin||!e.beforelogin(l)){hi5.tool.disableInput();var n=new WebSocket(l.substring(0,l.indexOf("?"))+"?_METHOD=post","login");n.onclose=function(h){m||(hi5.notifications.notify(__svi18n.errorCode.connection),e.showLogDlg());hi5.tool.enableInput();e.afterlogin&&e.afterlogin(m);m=!1};n.onopen=function(h){m=!0};n.onmessage=function(h){var p=h.data,t=p.substring(0,2);if("00"==t)n.send("00"+
l.substring(l.indexOf("?")+1));else if("01"==t)switch(hi5.tool.enableInput(),p.substring(2,3)){case "0":if(h=hi5.$("twofacode")){var u=new hi5.ui.Lightbox(h);u.show();var r=hi5.$("btnTwoFACode"),w=hi5.$("faAuthCode");w.focus();w.value="";r.onclick=function(){n.send("code:"+w.value);u.dismiss()};w.addEventListener("keyup",function(v){if(13==v.keyCode||"Enter"==v.code)v.preventDefault(),r.click()})}break;case "1":h=p.substring(4),showTwoFAQR(function(v,x){n.send("code:"+v)},h)}else h=JSON.parse(h.data),
0===h.type&&(h.message||h.name)?svGlobal.gatewayError(h.name,h.message||h.msg):(h.error||n.send("A1"+navigator.userAgent),q(h))}}}var m=!1,b=hi5.browser.cookie2Obj();b.svSession&&b.svEmail&&(a+="&svSession="+b.svSession+"&svEmail="+encodeURIComponent(b.svEmail));setTimeout(function(){d(a,f)},5);return!1}};
window.addEventListener("load",function(f){function k(){f.preventDefault();svGlobal.auth.beforesubmit&&svGlobal.auth.beforesubmit();var e=hi5.$("frmLogin").elements,c=svGlobal.auth.getUserName(e.user.value),a=e.pwd.value;c=svGlobal.auth.getLoginURL()+"user="+encodeURIComponent(c)+"&pwd="+encodeURIComponent(a);(a=e.sharedSecret)&&a.value&&(c+="&sharedSecret="+encodeURIComponent(a.value));e.pwd.value="";return svGlobal.auth.login(c)}function g(e,c,a){var d=svGlobal.auth.getLoginURL()+"action=code",
m=new WebSocket(d,"login");m.onmessage=function(b){b=JSON.parse(b.data);b.error?svGlobal.gatewayError(b.name,b.message||b.msg):hi5.notifications.notify(__svi18n.info.succeeded);m.close()};m.onopen=function(b){m.send("twof:"+e+"\t"+__sparkUser.account+"\t"+c+"\t"+__sparkUser.session+"\t"+a+"\t")}}(function(){hi5.$("user").focus();hi5.$("frmLogin").onsubmit=k;var e=hi5.$("anyconn");e&&(e.onclick=function(){var l="default"==hi5.appcfg.newWindow?void 0:"width="+window.outerWidth+",height="+window.outerHeight;
window.open("rdp.html?gateway="+hi5.$("gateway").value,"_blank",l)});if(e=document.querySelector('input[name="showlogin"]'))e.onclick=svGlobal.auth.showLogDlg;var c=hi5.browser.cookie2Obj(),a=-1!=document.cookie.indexOf("__SV_TOKEN_A"),d=hi5.tool.queryToObj();if(c.svEmail||c.user||a||d.autoLogin||d.user&&d.pwd){var m=hi5.$("frmLogin").elements;m.user.value=c.svEmail||c.user||d.user||"";m.pwd.value=(c.svSession?"fake":c.pwd)||d.pwd||"_";c.gateway&&(m.gateway.value=c.gateway);(m.user.value&&m.pwd.value||
c.autoLogin||a||d.autoLogin)&&setTimeout(k,30)}e=hi5.$("settings");var b=hi5.$("settingsDiv");e&&(e.onclick=function(){if(b){var l=document.getElementById("2fa_code_pwd");l&&(l.style.display=__sparkUser.twoFAEnabled?"table-row":"none");(new hi5.ui.Lightbox(b)).show();hi5.$("currPwd").focus();if(l=hi5.$("btnTwoFA"))l.onclick=function(){showTwoFAQR(g,window.__sparkUser.twoFAQR)},0==__sparkUser.twoFA&&l.parentNode.removeChild(l)}});if(e=hi5.$("frmSettings"))e.onsubmit=function(l){l.preventDefault();
var q=l.target.elements;if(q.newPwd1.value!=q.newPwd2.value)hi5.notifications.notify(__svi18n.errorCode.pwdmatch);else{l=svGlobal.auth.getLoginURL()+"_METHOD=post&action=put";var n=new WebSocket(l,"login");n.onmessage=function(h){if(0==h.data.indexOf("00")){h="00currPwd="+encodeURIComponent(q.currPwd.value)+"&newPwd="+encodeURIComponent(q.newPwd1.value);h+="&user="+encodeURIComponent(svGlobal.auth.getUserName(hi5.$("user").value));var p=e.elements.faCode;p&&(h+="&code="+p.value);n.send(h);hi5.$("frmSettings").reset()}else h=
JSON.parse(h.data),h.error&&svGlobal.gatewayError(h.name,h.message||h.msg)};b.dismiss&&b.dismiss();return!1}};c=hi5.$("gateway");(a=c.value)||(a=hi5.appcfg.defaultPort?window.location.hostname+":"+hi5.appcfg.defaultPort:window.location.host);0==a.length&&(a="localhost");c.value=a;c=hi5.$("touchpadmode");hi5.browser.isTouch&&(c.style.display="");(c=hi5.$("user"))&&!c.value&&hi5.appcfg&&hi5.appcfg.domain&&!hi5.appcfg.hiddenDomain&&(c.value=hi5.appcfg.domain+"\\");(function(){var l=!1,q="";try{document.createElement("canvas").getContext("2d"),
l=!0}catch(t){q="This browser does not support Canvas.\n\n"}var n=!("WebSocket"in window)&&!("MozWebSocket"in window),h=navigator.userAgent,p=-1!=h.indexOf("Firefox");n&&(q+="This browser doesn't support WebSocket.\n\n",p?q+="Please update to Firefox 6 or later.\n\n":-1!=h.indexOf("Opera")?q+="Please open 'opera:config#Enable WebSockets' (type it in the link field) make 'Enable WebSockets' selected and restart Opera.\n\n":-1!=h.indexOf("MSIE")&&(q+="Please install Google Chrome Frame.\n\n"));0<q.length&&
hi5.notifications.notify(q);return!n&&l})();(c=hi5.$("defPort"))&&hi5.appcfg.defaultPort&&(c.innerHTML=hi5.appcfg.defaultPort);(c=document.getElementById("frmConn"))&&(c=c.querySelector('select[name="keyboard"]'));c&&(a=svGlobal.Rdp.languageToKeyboard.detect())&&(c.value=a)})()},!1);window.addEventListener("beforeunload",function(){svGlobal.auth.closeSession()},!1);
