var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(b,f,g){if(null==b)throw new TypeError("The 'this' value for String.prototype."+g+" must not be null or undefined");if(f instanceof RegExp)throw new TypeError("First argument to String.prototype."+g+" must not be a regular expression");return b+""};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,f,g){b!=Array.prototype&&b!=Object.prototype&&(b[f]=g.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,f,g,a){if(f){g=$jscomp.global;b=b.split(".");for(a=0;a<b.length-1;a++){var d=b[a];d in g||(g[d]={});g=g[d]}b=b[b.length-1];a=g[b];f=f(a);f!=a&&null!=f&&$jscomp.defineProperty(g,b,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("String.prototype.startsWith",function(b){return b?b:function(b,g){var a=$jscomp.checkStringArgs(this,b,"startsWith");b+="";for(var d=a.length,e=b.length,h=Math.max(0,Math.min(g|0,a.length)),l=0;l<e&&h<d;)if(a[h++]!=b[l++])return!1;return l>=e}},"es6-impl","es3");
function showTwoFAQR(b,f){var g=hi5.$("twofainfo");if(g){var a=hi5.$("barcodeDiv"),d=hi5.$("enableTwoFA"),e=hi5.$("disableTwoFA");f?(hi5.$("imgBarcode").src="data:image/png;base64,"+f,a.style.display="block",e.style.display="none",d.style.display="block"):(a.style.display="none",e.style.display="block",d.style.display="none");var h=new hi5.ui.Lightbox(g);h.show();hi5.$("faCode").focus();hi5.$("faCode").value="";d.onclick=e.onclick=function(a){var e=hi5.$("faCode").value;a=a.target==d?1:0;6!=e.length?
hi5.notifications.notify(__svi18n.info.digit6||"It must be a 6 digit number"):(b(e,a),h.dismiss())}}}
svGlobal.auth=new function(){function b(a){hi5.tool.enableInput();if(a.error)svGlobal.gatewayError(a.name,a.message);else{hi5.$("frmLogin").style.display="none";hi5.$("frmConn").style.display="block";for(var e=hi5.$("programs");e.hasChildNodes();)e.removeChild(e.firstChild);var d=a.servers;if(!a.accessNotInList){var c=hi5.$("anyconn");c&&(c.style.display="none")}c=svGlobal.auth.getUserName(hi5.$("user").value);window.__sparkUser={session:a.session,account:c,gateway:hi5.$("gateway").value,servers:d,
twoFA:a.twoFA,twoFAEnabled:a.twoFAEnabled,twoFAQR:a.twoFAQR};a=d.length;if(!(1>a)){for(var c="",b=0;b<a;b++){var r=d[b].server,k=d[b].id,r=d[b].displayName||k||r,n=d[b].icon;n||(n="rdp32.png");var q=document.createElement("div");q.className="icon";var p=document.createElement("img");p.src=n;p.id=k;p.alt=k;p.title=r;p.style.cursor="pointer";p.onclick=f;q.appendChild(p);q.appendChild(document.createElement("br"));q.appendChild(document.createTextNode(r));e.appendChild(q);hi5.appcfg.startup&&k===hi5.appcfg.startup.server&&
(c=k)}!c&&hi5.appcfg.startup&&(console.log("start up:"+hi5.appcfg.startup.server+" not found, use the first instead"),c=d[0].id);c&&g(c,!hi5.appcfg.startup.newWindow,!0)}}}function f(a){var e=a.target;e.onclick=null;setTimeout(function(){e.onclick=f},300);g(e.id)}function g(a,b,g){var c=window.__sparkUser,e=c.servers,l=e.length;c.server=null;window.sparkGateway=c.gateway;for(var k=0;k<l;k++){var n=e[k];if(a==n.id){n.gateway=c.gateway;n.session=c.session;n.account=c.account;c.server=n;break}}if(c.server){console.log("connecting to:"+
c.server.id);(a=hi5.$("touchpad"))&&a.checked&&(c.server.touchpad=!0);if(a=hi5.$("keyboard"))a=parseInt(a.options[a.selectedIndex].value),0<a&&(c.server.keyboard=a);if(svGlobal.auth.onconnect)svGlobal.auth.onconnect(c.server);a=c.server.rdp&&("app"==c.server.startProgram||c.server.rdp.remoteProgram);void 0==b&&(b=a);if(b){var f=svManager.getInstance();if(a&&f&&f.running())f.startApp(c.server.exe||c.server.rdp.remoteProgram,c.server.args||c.server.rdp.remoteArgs,""),d&&d.visible()&&d.dismiss();else{var h=
function(a){function c(){null==d&&(d=new hi5.ui.Lightbox(hi5.$("login")));d.visible()?d.dismiss():d.show()}var b=a.toolbar.querySelector("#__sv_btn_home");b||(b=a.toolbar.addButton(hi5.appcfg.img.home||"home.png",c),b.id="__sv_btn_home")},f=new Rdp2(c.server);hi5.$("login").style.display="none";var m=new svGlobal.LocalInterface;m.onremoteappicon=function(a,c){if(m.toolbar&&a.isMainWin()&&32==c.getWidth()){var b="win"+a.id;if(!m.toolbar.querySelector("#"+b)){h(m);var e=m.toolbar.addButton(c.getDataURL(),
function(){a.activate(1)});e.id=b;e.title=a.titleInfo;e.style.width="32px";e.style.height="32px";e.addEventListener("mouseover",function(){e.title=a.titleInfo},!1);setTimeout(function(){a.activate(1)},333)}}};m.onremoteappclose=function(a){m.toolbar&&(a=m.toolbar.querySelector("#win"+a.id))&&m.toolbar.removeChild(a)};f.addSurface(m);f.run();f.onclose=function(){if(g){window.__sparkUser=null;var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none"}else f.hide(),
hi5.$("login").style.display="block"}}}else b=document.getElementById("multiMon"),c.server.rdp?(b&&b.checked&&(c.server.rdp.multiMon="on"),window.open("rdpdirect.html")):c.server.vnc?window.open("vnc.html"):c.server.ssh?window.open("sshdirect.html"):c.server.telnet&&window.open("telnet.html")}else hi5.notifications.notify("Not a valid server")}var a=this,d=null;this.getLoginURL=function(){return("https:"==location.protocol?"wss://":"ws://")+hi5.$("gateway").value+"/LOGIN?"};this.showLogDlg=function(){window.__sparkUser=
null;var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none";(a=svManager.getInstance())&&a.running()&&a.close()};this.getUserName=function(a){hi5.appcfg&&hi5.appcfg.domain&&(a.toLowerCase().startsWith(hi5.appcfg.domain.toLowerCase()+"\\")||(a=hi5.appcfg.domain+"\\"+a));return a};this.login=function(d){function e(c,b){window.__sparkUser=null;if(!a.beforelogin||!a.beforelogin(c)){hi5.tool.disableInput();var d=new WebSocket(c.substring(0,c.indexOf("?"))+
"?_METHOD=post","login");d.onclose=function(c){f||(hi5.notifications.notify(__svi18n.errorCode.connection),a.showLogDlg());hi5.tool.enableInput();a.afterlogin&&a.afterlogin(f);f=!1};d.onopen=function(a){f=!0};d.onmessage=function(a){var e=a.data,f=e.substring(0,2);if("00"==f)d.send("00"+c.substring(c.indexOf("?")+1));else if("01"==f)switch(hi5.tool.enableInput(),e.substring(2,3)){case "0":if(a=hi5.$("twofacode")){var g=new hi5.ui.Lightbox(a);g.show();a=hi5.$("btnTwoFACode");var k=hi5.$("faAuthCode");
k.focus();k.value="";a.onclick=function(){d.send("code:"+k.value);g.dismiss()}}break;case "1":a=e.substring(4),showTwoFAQR(function(a,c){d.send("code:"+a)},a)}else a=JSON.parse(a.data),0===a.type&&(a.message||a.name)?svGlobal.gatewayError(a.name,a.message):(a.error||d.send("A1"+navigator.userAgent),b(a))}}}var f=!1,c=hi5.browser.cookie2Obj();c.svSession&&c.svEmail&&(d+="&svSession="+c.svSession+"&svEmail="+encodeURIComponent(c.svEmail));setTimeout(function(){e(d,b)},5);return!1}};
window.addEventListener("load",function(b){function f(){b.preventDefault();svGlobal.auth.beforesubmit&&svGlobal.auth.beforesubmit();var a=hi5.$("frmLogin").elements,d=svGlobal.auth.getUserName(a.user.value),e=a.pwd.value,d=svGlobal.auth.getLoginURL()+"user="+encodeURIComponent(d)+"&pwd="+encodeURIComponent(e);(a=a.sharedSecret)&&a.value&&(d+="&sharedSecret="+encodeURIComponent(a.value));return svGlobal.auth.login(d)}function g(a,b){var d=svGlobal.auth.getLoginURL()+"action=code",f=new WebSocket(d,
"login");f.onmessage=function(a){a=JSON.parse(a.data);a.error?svGlobal.gatewayError(a.name,a.message):hi5.notifications.notify(__svi18n.info.succeeded);f.close()};f.onopen=function(d){f.send("twof:"+a+"\t"+__sparkUser.account+"\t"+b+"\t"+__sparkUser.session)}}(function(){hi5.$("user").focus();hi5.$("frmLogin").onsubmit=f;var a=hi5.$("anyconn");a&&(a.onclick=function(){window.open("rdp.html?gateway="+hi5.$("gateway").value)});if(a=document.querySelector('input[name="showlogin"]'))a.onclick=svGlobal.auth.showLogDlg;
var a=hi5.browser.cookie2Obj(),b=-1!=document.cookie.indexOf("__SV_TOKEN_A"),e=hi5.tool.queryToObj();if(a.svEmail||a.user||b||e.autoLogin||e.user&&e.pwd){var h=hi5.$("frmLogin").elements;h.user.value=a.svEmail||a.user||e.user||"";h.pwd.value=(a.svSession?"fake":a.pwd)||e.pwd||"_";a.gateway&&(h.gateway.value=a.gateway);(h.user.value&&h.pwd.value||a.autoLogin||b||e.autoLogin)&&setTimeout(f,30)}var a=hi5.$("settings"),l=hi5.$("settingsDiv");a&&(a.onclick=function(){if(l){(new hi5.ui.Lightbox(l)).show();
hi5.$("currPwd").focus();var a=hi5.$("btnTwoFA");a&&(a.onclick=function(){showTwoFAQR(g,window.__sparkUser.twoFAQR)},0==__sparkUser.twoFA&&a.parentNode.removeChild(a))}});if(a=hi5.$("frmSettings"))a.onsubmit=function(a){a.preventDefault();var b=a.target.elements;if(b.newPwd1.value!=b.newPwd2.value)hi5.notifications.notify(__svi18n.errorCode.pwdmatch);else{a=svGlobal.auth.getLoginURL()+"_METHOD=post&action=put";var c=new WebSocket(a,"login");c.onmessage=function(a){0==a.data.indexOf("00")?(c.send("00currPwd="+
encodeURIComponent(b.currPwd.value)+"&newPwd="+encodeURIComponent(b.newPwd1.value)+"&user="+encodeURIComponent(svGlobal.auth.getUserName(hi5.$("user").value))),hi5.$("frmSettings").reset()):(a=JSON.parse(a.data),a.error&&svGlobal.gatewayError(a.name,a.message))};l.dismiss&&l.dismiss();return!1}};a=hi5.$("gateway");(b=a.value)||(b=hi5.appcfg.defaultPort?window.location.hostname+":"+hi5.appcfg.defaultPort:window.location.host);0==b.length&&(b="localhost");a.value=b;a=hi5.$("touchpadmode");hi5.browser.isTouch&&
(a.style.display="");(a=hi5.$("user"))&&!a.value&&hi5.appcfg&&hi5.appcfg.domain&&!hi5.appcfg.hiddenDomain&&(a.value=hi5.appcfg.domain+"\\");(function(){var a=!1,b="";try{document.createElement("canvas").getContext("2d"),a=!0}catch(q){b="This browser does not support Canvas.\n\n"}var d=!("WebSocket"in window)&&!("MozWebSocket"in window),e=navigator.userAgent,f=-1!=e.indexOf("Firefox");d&&(b+="This browser doesn't support WebSocket.\n\n",f?b+="Please update to Firefox 6 or later.\n\n":-1!=e.indexOf("Opera")?
b+="Please open 'opera:config#Enable WebSockets' (type it in the link field) make 'Enable WebSockets' selected and restart Opera.\n\n":-1!=e.indexOf("MSIE")&&(b+="Please install Google Chrome Frame.\n\n"));0<b.length&&hi5.notifications.notify(b);return!d&&a})();(a=hi5.$("defPort"))&&hi5.appcfg.defaultPort&&(a.innerHTML=hi5.appcfg.defaultPort);(a=document.getElementById("frmConn"))&&(a=a.querySelector('select[name="keyboard"]'));a&&(b=svGlobal.Rdp.languageToKeyboard.detect())&&(a.value=b)})()},!1);
