var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(g,e,f){if(null==g)throw new TypeError("The 'this' value for String.prototype."+f+" must not be null or undefined");if(e instanceof RegExp)throw new TypeError("First argument to String.prototype."+f+" must not be a regular expression");return g+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(g,e,f){if(g==Array.prototype||g==Object.prototype)return g;g[e]=f.value;return g};
$jscomp.getGlobal=function(g){g=["object"==typeof globalThis&&globalThis,g,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var e=0;e<g.length;++e){var f=g[e];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(g,e){var f=$jscomp.propertyToPolyfillSymbol[e];if(null==f)return g[e];f=g[f];return void 0!==f?f:g[e]};$jscomp.polyfill=function(g,e,f,k){e&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(g,e,f,k):$jscomp.polyfillUnisolated(g,e,f,k))};
$jscomp.polyfillUnisolated=function(g,e,f,k){f=$jscomp.global;g=g.split(".");for(k=0;k<g.length-1;k++){var l=g[k];if(!(l in f))return;f=f[l]}g=g[g.length-1];k=f[g];e=e(k);e!=k&&null!=e&&$jscomp.defineProperty(f,g,{configurable:!0,writable:!0,value:e})};
$jscomp.polyfillIsolated=function(g,e,f,k){var l=g.split(".");g=1===l.length;k=l[0];k=!g&&k in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var q=0;q<l.length-1;q++){var b=l[q];if(!(b in k))return;k=k[b]}l=l[l.length-1];f=$jscomp.IS_SYMBOL_NATIVE&&"es6"===f?k[l]:null;e=e(f);null!=e&&(g?$jscomp.defineProperty($jscomp.polyfills,l,{configurable:!0,writable:!0,value:e}):e!==f&&($jscomp.propertyToPolyfillSymbol[l]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(l):$jscomp.POLYFILL_PREFIX+l,l=
$jscomp.propertyToPolyfillSymbol[l],$jscomp.defineProperty(k,l,{configurable:!0,writable:!0,value:e})))};$jscomp.polyfill("String.prototype.startsWith",function(g){return g?g:function(e,f){var k=$jscomp.checkStringArgs(this,e,"startsWith");e+="";var l=k.length,q=e.length;f=Math.max(0,Math.min(f|0,k.length));for(var b=0;b<q&&f<l;)if(k[f++]!=e[b++])return!1;return b>=q}},"es6","es3");
function showTwoFAQR(g,e){var f=hi5.$("twofainfo");if(f){var k=hi5.$("barcodeDiv"),l=hi5.$("enableTwoFA"),q=hi5.$("disableTwoFA");e?(hi5.$("imgBarcode").src="data:image/png;base64,"+e,k.style.display="block",q.style.display="none",l.style.display="block"):(k.style.display="none",q.style.display="block",l.style.display="none");var b=new hi5.ui.Lightbox(f);b.show();hi5.$("faCode").focus();hi5.$("faCode").value="";l.onclick=q.onclick=function(a){var d=hi5.$("faCode").value;a=a.target==l?1:0;if(6!=d.length)hi5.notifications.notify(__svi18n.info.digit6||
"It must be a 6 digit number");else{var c=f.querySelector('input[name="pwd"]');g(d,a,c?c.value:"");b.dismiss()}}}}
svGlobal.auth=new function(){var g=this;this.getLoginURL=function(){return("https:"==location.protocol?"wss://":"ws://")+hi5.$("gateway").value+"/LOGIN?"};this.closeSession=function(e,f){console.log("close session "+f+" on user "+e);window.__sparkUser&&(e||(e=window.__sparkUser.account),f||(f=window.__sparkUser.session));e&&f&&(e=svGlobal.auth.getLoginURL()+"action=close&user="+encodeURIComponent(e)+"&svSession="+f,(new WebSocket(e,"login")).onopen=function(k){console.log("Sign out");window.__sparkUser=
null})};this.showLogDlg=function(){if(hi5.appcfg&&hi5.appcfg.returnUrl)window.location.href=hi5.appcfg.returnUrl;else{var e=window.__sparkUser.account,f=window.__sparkUser.session;window.__sparkUser=null;var k=hi5.$("frmLogin");k.elements.pwd.value="";k.style.display="block";hi5.$("frmConn").style.display="none";(k=svManager.getInstance())&&k.running()&&k.close();svGlobal.auth.closeSession(e,f)}};this.getUserName=function(e){hi5.appcfg&&hi5.appcfg.domain&&(e.toLowerCase().startsWith(hi5.appcfg.domain.toLowerCase()+
"\\")||(e=hi5.appcfg.domain+"\\"+e));return e};this.login=function(e){function f(q,b){window.__sparkUser=null;if(!g.beforelogin||!g.beforelogin(q)){var a=new WebSocket(q.substring(0,q.indexOf("?"))+"?_METHOD=post","login");a.onclose=function(d){g.afterlogin&&g.afterlogin(k);k=!1};a.onopen=function(d){k=!0};a.onmessage=function(d){var c=d.data,n=c.substring(0,2);if("00"==n)a.send("00"+q.substring(q.indexOf("?")+1));else if("01"==n)switch(hi5.tool.enableInput(),c.substring(2,3)){case "0":if(d=hi5.$("twofacode")){var p=
new hi5.ui.Lightbox(d);p.show();var t=hi5.$("btnTwoFACode"),h=hi5.$("faAuthCode");h.focus();h.value="";t.onclick=function(){a.send("code:"+h.value);p.dismiss()};h.addEventListener("keyup",function(m){if(13==m.keyCode||"Enter"==m.code)m.preventDefault(),t.click()})}break;case "1":d=c.substring(4),showTwoFAQR(function(m,r){a.send("code:"+m)},d)}else d=JSON.parse(d.data),0===d.type&&(d.message||d.name)?svGlobal.gatewayError(d.name,d.message||d.msg):(d.error||a.send("A1"+navigator.userAgent),b(d))}}}
var k=!1,l=hi5.browser.cookie2Obj();l.svSession&&l.svEmail&&(e+="&svSession="+l.svSession+"&svEmail="+encodeURIComponent(l.svEmail));setTimeout(function(){f(e,svGlobal.onloggedin)},5);return!1}};
function startExitingApp(g){function e(q){f.addSurface(q);f.startExitingApp(g)}var f=svManager.getInstance();window.svOnSurfaceReady=e;window.open("rail.html").svOnSurfaceReady=e;var k=hi5.$(g),l=k.parentNode;l.removeChild(k);l=l.parentNode;0==l.getElementsByTagName("input").length&&(l.dismiss(),f.checkRemaining(2E3))}function getLoginURL(){return("https:"==location.protocol?"wss://":"ws://")+hi5.$("gateway").value+"/LOGIN?"}
window.addEventListener("load",function(g){function e(){g.preventDefault();svGlobal.auth.beforesubmit&&svGlobal.auth.beforesubmit();var b=hi5.$("frmLogin").elements,a=svGlobal.auth.getUserName(b.user.value),d=b.pwd.value;a=getLoginURL()+"user="+encodeURIComponent(a)+"&pwd="+encodeURIComponent(d);(d=b.sharedSecret)&&d.value&&(a+="&sharedSecret="+encodeURIComponent(d.value));b.pwd.value="";return svGlobal.auth.login(a)}function f(b,a,d){var c=svGlobal.auth.getLoginURL()+"action=code",n=new WebSocket(c,
"login");n.onmessage=function(p){p=JSON.parse(p.data);p.error?svGlobal.gatewayError(p.name,p.message||p.msg):hi5.notifications.notify(__svi18n.info.succeeded);n.close()};n.onopen=function(p){n.send("twof:"+b+"\t"+__sparkUser.account+"\t"+a+"\t"+__sparkUser.session+"\t"+d+"\t")}}function k(b){var a=b.target;a.onclick=null;setTimeout(function(){a.onclick=k},300);q(a.id)}function l(){function b(c){d.addSurface(c);c=a.exe||a.rdp.remoteProgram;var n=a.args||a.rdp.remoteArgs||"";console.log("remoteApp: "+
c+" arg="+n+" running="+d.running());d.running()?d.startApp(c,n,""):d.run()}var a=window.__sparkUser.server,d=svManager.getInstance();null==d&&(d=new svGlobal.Rdp2(a),d.sessionTimeout=9E5);window.svOnSurfaceReady=b;window.open("rail.html").svOnSurfaceReady=b}function q(b,a,d){var c=window.__sparkUser,n=c.servers,p=n.length;c.server=null;window.sparkGateway=c.gateway;for(var t=0;t<p;t++){var h=n[t];if(b==h.id){h.gateway=c.gateway;h.session=c.session;h.account=c.account;c.server=h;break}}if(c.server){console.log("connecting to:"+
c.server.id);(b=hi5.$("touchpad"))&&b.checked&&(c.server.touchpad=!0);if(b=hi5.$("keyboard"))b=parseInt(b.options[b.selectedIndex].value),0<b&&(c.server.keyboard=b);"undefined"==typeof a&&(a=(b=hi5.$("sameWindow"))&&b.checked);a&&!c.server.rdp&&(a=!1);c.server.rdp&&c.server.rdp.remoteProgram&&(c.server.startProgram="app");b="default"==hi5.appcfg.newWindow?void 0:"width="+window.outerWidth+",height="+window.outerHeight;if(c.server.http)a=location.protocol+"//"+c.server.id+"."+c.gateway,c.server.http.path&&
(a+=c.server.http.path),window.open(a,"_blank",b);else if("app"==c.server.startProgram&&hi5.browser.isMultitask&&!a)l();else if(a){var m=new Rdp2(c.server);hi5.$("login").style.display="none";m.addSurface(new svGlobal.LocalInterface);m.run();m.onclose=function(){d?showLogDlg():(m.hide(),hi5.$("login").style.display="block")}}else a=document.getElementById("multiMon"),c.server.rdp?(c.server.rdp.multiMon=a&&a.checked?"on":"off",window.open("rdpdirect.html","_blank",b)):c.server.vnc?window.open("vnc.html",
"_blank",b):c.server.ssh?window.open("sshdirect.html","_blank",b):c.server.telnet&&window.open("telnet.html","_blank",b)}else hi5.notifications.notify("Not a valid server")}svGlobal.auth.beforelogin=function(){hi5.tool.disableInput()};svGlobal.auth.afterlogin=function(b){b||(hi5.notifications.notify(__svi18n.errorCode.connection),svGlobal.auth.showLogDlg());hi5.tool.enableInput()};svGlobal.onloggedin=function(b){hi5.tool.enableInput();if(b.error)svGlobal.gatewayError(b.name,b.message||b.msg);else{hi5.$("frmLogin").style.display=
"none";hi5.$("frmConn").style.display="block";var a=document.getElementById("pwdZone");a&&(a.style.display=b.isDomainUser?"none":"table-row-group");b.isDomainUser&&!b.twoFAEnabled&&(a=document.getElementById("settings"))&&(a.style.display="none");a=!0===b.passkey?"inline":"none";var d=document.getElementById("passkeySignIn");d&&(d.style.display=a);if(d=document.getElementById("addPasskeyBtn"))d.style.display=a;if(d=document.getElementById("deletePasskeyBtn"))d.style.display=a;for(a=hi5.$("programs");a.hasChildNodes();)a.removeChild(a.firstChild);
d=b.servers;if(!b.accessNotInList){var c=hi5.$("anyconn");c&&(c.style.display="none")}if(b.hash){c=hi5.$("gateway").value;var n=c.indexOf(":");-1!=n&&(c=c.substring(0,n));c.toLowerCase().startsWith("www.")&&(c=c.substring(4));document.cookie="__SV_TOKEN_S="+b.hash+"-"+encodeURIComponent(b.name)+";domain=."+c}c=svGlobal.auth.getUserName(hi5.$("user").value);hi5.appcfg&&hi5.appcfg.domain&&hi5.appcfg.hiddenDomain&&(c=hi5.appcfg.domain+"\\"+c);window.__sparkUser={session:b.session,account:c,gateway:hi5.$("gateway").value,
servers:d,twoFA:b.twoFA,twoFAEnabled:b.twoFAEnabled,twoFAQR:b.twoFAQR};b=d.length;if(!(1>b)){c="";for(n=0;n<b;n++){var p=d[n].server,t=d[n].id;p=d[n].displayName||t||p;var h=d[n].icon;h||(h="rdp32.png");var m=document.createElement("div");m.className="icon";var r=document.createElement("img");r.src=h;r.id=t;r.alt=t;r.title=p;r.style.cursor="pointer";r.onclick=k;m.appendChild(r);m.appendChild(document.createElement("br"));m.appendChild(document.createTextNode(p));a.appendChild(m);hi5.appcfg.startup&&
t===hi5.appcfg.startup.server&&(c=t)}!c&&hi5.appcfg.startup&&(console.log("start up:"+hi5.appcfg.startup.server+" not found, use the first instead"),c=d[0].id);c&&q(c,!hi5.appcfg.startup.newWindow,!0)}}};(function(){hi5.PasskeyClient&&hi5.PasskeyClient.supportsPasskey(function(h){if(h){if(h=document.getElementById("passkeySignIn")){var m=new hi5.PasskeyClient;h.addEventListener("click",function(r){r.preventDefault();m.passkeySignIn()});(h=document.getElementById("addPasskeyBtn"))&&h.addEventListener("click",
function(r){m.passkeyAdd()});(h=document.getElementById("deletePasskeyBtn"))&&h.addEventListener("click",function(r){m.passkeyDel()})}}else(h=hi5.$("passkeySignIn"))&&h.parentNode.removeChild(h),(h=hi5.$("addPasskeyBtn"))&&h.parentNode.removeChild(h),(h=hi5.$("deletePasskeyBtn"))&&h.parentNode.removeChild(h)});hi5.$("user").focus();hi5.$("frmLogin").onsubmit=e;var b=hi5.$("anyconn");b&&(b.onclick=function(){var h="default"==hi5.appcfg.newWindow?void 0:"width="+window.outerWidth+",height="+window.outerHeight;
window.open("rdp.html?gateway="+hi5.$("gateway").value,"_blank",h)});if(b=document.querySelector('input[name="showlogin"]'))b.onclick=svGlobal.auth.showLogDlg;var a=hi5.browser.cookie2Obj(),d=-1!=document.cookie.indexOf("__SV_TOKEN_A"),c=hi5.tool.queryToObj();if(a.svEmail||a.user||d||c.autoLogin||c.user&&c.pwd){var n=hi5.$("frmLogin").elements;n.user.value=a.svEmail||a.user||c.user||"";n.pwd.value=(a.svSession?"fake":a.pwd)||c.pwd||"_";a.gateway&&(n.gateway.value=a.gateway);(n.user.value&&n.pwd.value||
a.autoLogin||d||c.autoLogin)&&setTimeout(e,30)}b=hi5.$("settings");var p=hi5.$("settingsDiv");b&&(b.onclick=function(){if(p){var h=document.getElementById("2fa_code_pwd");h&&(h.style.display=__sparkUser.twoFAEnabled?"table-row":"none");(new hi5.ui.Lightbox(p)).show();hi5.$("currPwd").focus();if(h=hi5.$("btnTwoFA"))h.onclick=function(){showTwoFAQR(f,window.__sparkUser.twoFAQR)},0==__sparkUser.twoFA&&h.parentNode.removeChild(h)}});if(b=hi5.$("frmSettings"))b.onsubmit=function(h){h.preventDefault();
var m=h.target.elements;if(m.newPwd1.value!=m.newPwd2.value)hi5.notifications.notify(__svi18n.errorCode.pwdmatch);else{h=getLoginURL()+"_METHOD=post&action=put";var r=new WebSocket(h,"login");r.onmessage=function(u){if(0==u.data.indexOf("00")){u="00currPwd="+encodeURIComponent(m.currPwd.value)+"&newPwd="+encodeURIComponent(m.newPwd1.value);u+="&user="+encodeURIComponent(svGlobal.auth.getUserName(hi5.$("user").value));var v=b.elements.faCode;v&&(u+="&code="+v.value);r.send(u);hi5.$("frmSettings").reset()}else u=
JSON.parse(u.data),u.error&&svGlobal.gatewayError(u.name,u.message||u.msg)};p.dismiss&&p.dismiss();return!1}};var t=hi5.$("sameWindow");t&&(hi5.browser.isiOS||hi5.browser.isIE||hi5.browser.isChromeApp)&&(t.checked=!0);(a=hi5.$("multiMon"))&&t&&(a.onchange=function(h){h.target.checked&&(t.checked=!1)});a=hi5.$("gateway");(d=a.value)||(d=hi5.appcfg.defaultPort?window.location.hostname+":"+hi5.appcfg.defaultPort:window.location.host);0==d.length&&(d="localhost");a.value=d;a=hi5.$("touchpadmode");hi5.browser.isTouch&&
(a.style.display="");(a=hi5.$("user"))&&!a.value&&hi5.appcfg&&hi5.appcfg.domain&&(a.value=hi5.appcfg.domain+"\\");(function(){var h=!1,m="";try{document.createElement("canvas").getContext("2d"),h=!0}catch(w){m="This browser does not support Canvas.\n\n"}var r=!("WebSocket"in window)&&!("MozWebSocket"in window),u=navigator.userAgent,v=-1!=u.indexOf("Firefox");r&&(m+="This browser doesn't support WebSocket.\n\n",v?m+="Please update to Firefox 6 or later.\n\n":-1!=u.indexOf("Opera")?m+="Please open 'opera:config#Enable WebSockets' (type it in the link field) make 'Enable WebSockets' selected and restart Opera.\n\n":
-1!=u.indexOf("MSIE")&&(m+="Please install Google Chrome Frame.\n\n"));0<m.length&&hi5.notifications.notify(m);return!r&&h})();(a=hi5.$("defPort"))&&hi5.appcfg.defaultPort&&(a.innerHTML=hi5.appcfg.defaultPort);(a=document.getElementById("frmConn"))&&(a=a.querySelector('select[name="keyboard"]'));a&&(d=svGlobal.Rdp.languageToKeyboard.detect())&&(a.value=d)})()},!1);window.addEventListener("beforeunload",function(){svGlobal.auth.closeSession()},!1);
