var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(b,c,a){if(null==b)throw new TypeError("The 'this' value for String.prototype."+a+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+a+" must not be a regular expression");return b+""};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,a){b!=Array.prototype&&b!=Object.prototype&&(b[c]=a.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,c,a,d){if(c){a=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var e=b[d];e in a||(a[e]={});a=a[e]}b=b[b.length-1];d=a[b];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(a,b,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("String.prototype.startsWith",function(b){return b?b:function(b,a){var d=$jscomp.checkStringArgs(this,b,"startsWith");b+="";for(var e=d.length,c=b.length,g=Math.max(0,Math.min(a|0,d.length)),f=0;f<c&&g<e;)if(d[g++]!=b[f++])return!1;return f>=c}},"es6-impl","es3");
svGlobal.auth=new function(){function b(){var a="https:"==location.protocol?"wss://":"ws://",b=hi5.$("gateway");return a=b?a+b.value:a+hi5.browser.getHost()}function c(a){hi5.tool.enableInput();if(a.error||!a.token)a.name?hi5.notifications.notify(__svi18n.errorCode["S"+a.name]):(console.log("Invalid result:",a),hi5.notifications.notify("Failed to login"));else{hi5.$("frmLogin").style.display="none";var d=hi5.$("frmLogin").elements,d=svGlobal.auth.getUserName(d.user.value),c=hi5.appcfg.color||16,g=
b()+"/RDP?__SV_TOKEN_T="+a.token+"&user="+encodeURIComponent(d)+"&server_bpp="+c+"&keyboard=",f=hi5.$("keyboard"),k=1033;f&&(f=parseInt(f.options[f.selectedIndex].value),0<f&&(k=f));document.cookie="user="+d;document.cookie="keyboard="+k;document.cookie="__SV_TOKEN_T="+a.token;a=new svGlobal.Rdp(g+k,window.innerWidth,window.innerHeight,c);d=new svGlobal.LocalInterface;a.addSurface(d);a.run()}}var a=this;this.getLoginURL=function(){return b()+"/AUTH?"};this.showLogDlg=function(){window.__sparkUser=
null;var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";(a=svManager.getInstance())&&a.running()&&a.close()};this.getUserName=function(a){hi5.appcfg&&hi5.appcfg.domain&&(a.toLowerCase().startsWith(hi5.appcfg.domain.toLowerCase()+"\\")||(a=hi5.appcfg.domain+"\\"+a));return a};this.login=function(d){function b(b,d){window.__sparkUser=null;if(!a.beforelogin||!a.beforelogin(b)){hi5.tool.disableInput();var c=new WebSocket(b.substring(0,b.indexOf("?"))+"?_METHOD=post","login");c.onclose=
function(b){h||(hi5.notifications.notify(__svi18n.errorCode.connection),a.showLogDlg());hi5.tool.enableInput();a.afterlogin&&a.afterlogin(h);h=!1};c.onopen=function(a){h=!0};c.onmessage=function(a){0==a.data.indexOf("00")?c.send("00"+b.substring(b.indexOf("?")+1)):(a=JSON.parse(a.data),0===a.type&&a.message?hi5.notifications.notify(a.message):(a.error||c.send("A1"+navigator.userAgent),d(a),c.close()))}}}var h=!1,g=hi5.browser.cookie2Obj();g.svSession&&g.svEmail&&(d+="&svSession="+g.svSession+"&svEmail="+
encodeURIComponent(g.svEmail));setTimeout(function(){b(d,c)},5);return!1};this.loggedin=c};
window.addEventListener("load",function(b){function c(a){a&&a.preventDefault();svGlobal.auth.beforesubmit&&svGlobal.auth.beforesubmit();a=hi5.browser.cookie2Obj();if(a.__SV_TOKEN_T)svGlobal.auth.loggedin({token:a.__SV_TOKEN_T});else{var b=hi5.$("frmLogin").elements;a=svGlobal.auth.getUserName(b.user.value);b=b.pwd.value;a=svGlobal.auth.getLoginURL()+"user="+encodeURIComponent(a)+"&pwd="+encodeURIComponent(b)+"&authType=okta_trusted";svGlobal.auth.login(a)}return!1}(function(){hi5.$("user").focus();
hi5.$("frmLogin").onsubmit=c;var a=hi5.$("anyconn");a&&(a.onclick=function(){window.open("rdp.html?gateway="+hi5.$("gateway").value)});if(a=document.querySelector('input[name="showlogin"]'))a.onclick=svGlobal.auth.showLogDlg;var a=hi5.$("gateway"),b=a.value;b||(b=hi5.appcfg.defaultPort?window.location.hostname+":"+hi5.appcfg.defaultPort:window.location.host);0==b.length&&(b="localhost");a.value=b;a=hi5.$("touchpadmode");hi5.browser.isTouch&&(a.style.display="");(a=hi5.$("user"))&&!a.value&&hi5.appcfg&&
hi5.appcfg.domain&&!hi5.appcfg.hiddenDomain&&(a.value=hi5.appcfg.domain+"\\");(a=hi5.$("defPort"))&&hi5.appcfg.defaultPort&&(a.innerHTML=hi5.appcfg.defaultPort);(a=document.getElementById("frmLogin"))&&(a=a.querySelector('select[name="keyboard"]'));a&&(b=svGlobal.Rdp.languageToKeyboard.detect())&&(a.value=b);var a=hi5.browser.cookie2Obj(),b=hi5.tool.queryToObj(),e=hi5.$("frmLogin").elements;a.keyboard&&(e.keyboard.value=a.keyboard);a.__SV_TOKEN_T&&(e.user.value=a.user||b.user||"",e.pwd.value="",a.gateway&&
(e.gateway.value=a.gateway),setTimeout(c,30))})()},!1);
