var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(c,d,a){if(null==c)throw new TypeError("The 'this' value for String.prototype."+a+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+a+" must not be a regular expression");return c+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,d,a){if(c==Array.prototype||c==Object.prototype)return c;c[d]=a.value;return c};
$jscomp.getGlobal=function(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<c.length;++d){var a=c[d];if(a&&a.Math==Math)return a}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(c,d){var a=$jscomp.propertyToPolyfillSymbol[d];if(null==a)return c[d];a=c[a];return void 0!==a?a:c[d]};$jscomp.polyfill=function(c,d,a,b){d&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(c,d,a,b):$jscomp.polyfillUnisolated(c,d,a,b))};
$jscomp.polyfillUnisolated=function(c,d,a,b){a=$jscomp.global;c=c.split(".");for(b=0;b<c.length-1;b++){var e=c[b];if(!(e in a))return;a=a[e]}c=c[c.length-1];b=a[c];d=d(b);d!=b&&null!=d&&$jscomp.defineProperty(a,c,{configurable:!0,writable:!0,value:d})};
$jscomp.polyfillIsolated=function(c,d,a,b){var e=c.split(".");c=1===e.length;b=e[0];b=!c&&b in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in b))return;b=b[g]}e=e[e.length-1];a=$jscomp.IS_SYMBOL_NATIVE&&"es6"===a?b[e]:null;d=d(a);null!=d&&(c?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:d}):d!==a&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(b,e,{configurable:!0,writable:!0,value:d})))};$jscomp.polyfill("String.prototype.startsWith",function(c){return c?c:function(d,a){var b=$jscomp.checkStringArgs(this,d,"startsWith");d+="";var e=b.length,f=d.length;a=Math.max(0,Math.min(a|0,b.length));for(var g=0;g<f&&a<e;)if(b[a++]!=d[g++])return!1;return g>=f}},"es6","es3");
svGlobal.auth=new function(){function c(){var b="https:"==location.protocol?"wss://":"ws://",e=hi5.$("gateway");return b=e?b+e.value:b+hi5.browser.getHost()}function d(b){hi5.tool.enableInput();if(b.error||!b.token)b.name?hi5.notifications.notify(__svi18n.errorCode["S"+b.name]):(console.log("Invalid result:",b),hi5.notifications.notify("Failed to login"));else{hi5.$("frmLogin").style.display="none";var e=hi5.$("frmLogin").elements;e=svGlobal.auth.getUserName(e.user.value);var f=hi5.appcfg.color||
16,g=c()+"/RDP?__SV_TOKEN_T="+b.token+"&user="+encodeURIComponent(e)+"&server_bpp="+f+"&keyboard=",h=hi5.$("keyboard"),m=1033;h&&(h=parseInt(h.options[h.selectedIndex].value),0<h&&(m=h));document.cookie="user="+e;document.cookie="keyboard="+m;document.cookie="__SV_TOKEN_T="+b.token;b=new svGlobal.Rdp(g+m,window.innerWidth,window.innerHeight,f);e=new svGlobal.LocalInterface;b.addSurface(e);b.run()}}var a=this;this.getLoginURL=function(){return c()+"/AUTH?"};this.showLogDlg=function(){window.__sparkUser=
null;var b=hi5.$("frmLogin");b.elements.pwd.value="";b.style.display="block";(b=svManager.getInstance())&&b.running()&&b.close()};this.getUserName=function(b){hi5.appcfg&&hi5.appcfg.domain&&(b.toLowerCase().startsWith(hi5.appcfg.domain.toLowerCase()+"\\")||(b=hi5.appcfg.domain+"\\"+b));return b};this.login=function(b){function e(h,m){window.__sparkUser=null;if(!a.beforelogin||!a.beforelogin(h)){hi5.tool.disableInput();var l=new WebSocket(h.substring(0,h.indexOf("?"))+"?_METHOD=post","login");l.onclose=
function(k){f||(hi5.notifications.notify(__svi18n.errorCode.connection),a.showLogDlg());hi5.tool.enableInput();a.afterlogin&&a.afterlogin(f);f=!1};l.onopen=function(k){f=!0};l.onmessage=function(k){0==k.data.indexOf("00")?l.send("00"+h.substring(h.indexOf("?")+1)):(k=JSON.parse(k.data),0===k.type&&k.message?hi5.notifications.notify(k.message):(k.error||l.send("A1"+navigator.userAgent),m(k),l.close()))}}}var f=!1,g=hi5.browser.cookie2Obj();g.svSession&&g.svEmail&&(b+="&svSession="+g.svSession+"&svEmail="+
encodeURIComponent(g.svEmail));setTimeout(function(){e(b,d)},5);return!1};this.loggedin=d};
window.addEventListener("load",function(c){function d(a){a&&a.preventDefault();svGlobal.auth.beforesubmit&&svGlobal.auth.beforesubmit();a=hi5.browser.cookie2Obj();if(a.__SV_TOKEN_T)svGlobal.auth.loggedin({token:a.__SV_TOKEN_T});else{var b=hi5.$("frmLogin").elements;a=svGlobal.auth.getUserName(b.user.value);b=b.pwd.value;a=svGlobal.auth.getLoginURL()+"user="+encodeURIComponent(a)+"&pwd="+encodeURIComponent(b)+"&authType=okta_trusted";svGlobal.auth.login(a)}return!1}(function(){hi5.$("user").focus();
hi5.$("frmLogin").onsubmit=d;var a=hi5.$("anyconn");a&&(a.onclick=function(){window.open("rdp.html?gateway="+hi5.$("gateway").value)});if(a=document.querySelector('input[name="showlogin"]'))a.onclick=svGlobal.auth.showLogDlg;a=hi5.$("gateway");var b=a.value;b||(b=hi5.appcfg.defaultPort?window.location.hostname+":"+hi5.appcfg.defaultPort:window.location.host);0==b.length&&(b="localhost");a.value=b;a=hi5.$("touchpadmode");hi5.browser.isTouch&&(a.style.display="");(a=hi5.$("user"))&&!a.value&&hi5.appcfg&&
hi5.appcfg.domain&&!hi5.appcfg.hiddenDomain&&(a.value=hi5.appcfg.domain+"\\");(a=hi5.$("defPort"))&&hi5.appcfg.defaultPort&&(a.innerHTML=hi5.appcfg.defaultPort);(a=document.getElementById("frmLogin"))&&(a=a.querySelector('select[name="keyboard"]'));a&&(b=svGlobal.Rdp.languageToKeyboard.detect())&&(a.value=b);a=hi5.browser.cookie2Obj();b=hi5.tool.queryToObj();var e=hi5.$("frmLogin").elements;a.keyboard&&(e.keyboard.value=a.keyboard);a.__SV_TOKEN_T&&(e.user.value=a.user||b.user||"",e.pwd.value="",a.gateway&&
(e.gateway.value=a.gateway),setTimeout(d,30))})()},!1);
