function showTwoFAQR(k,f){var l=hi5.$("twofainfo");if(l){var h=hi5.$("barcodeDiv"),d=hi5.$("enableTwoFA"),r=hi5.$("disableTwoFA");f?(hi5.$("imgBarcode").src="data:image/png;base64,"+f,h.style.display="block",r.style.display="none",d.style.display="block"):(h.style.display="none",r.style.display="block",d.style.display="none");var t=new hi5.ui.Lightbox(l);t.show();hi5.$("faCode").focus();hi5.$("faCode").value="";d.onclick=r.onclick=function(a){var b=hi5.$("faCode").value;a=a.target==d?1:0;6!=b.length?
hi5.notifications.notify(__svi18n.info.digit6||"It must be a 6 digit number"):(k(b,a),t.dismiss())}}}
svGlobal.auth=new function(){var k=this;this.getLoginURL=function(){return("https:"==location.protocol?"wss://":"ws://")+hi5.$("gateway").value+"/LOGIN?"};this.login=function(f){function l(d,f){window.__sparkUser=null;if(!k.beforelogin||!k.beforelogin(d)){var a=new WebSocket(d.substring(0,d.indexOf("?"))+"?_METHOD=post","login");a.onclose=function(a){k.afterlogin&&k.afterlogin(h);h=!1};a.onopen=function(a){h=!0};a.onmessage=function(b){var e=b.data,c=e.substring(0,2);if("00"==c)a.send("00"+d.substring(d.indexOf("?")+
1));else if("01"==c)switch(hi5.tool.enableInput(),e.substring(2,3)){case "0":if(b=hi5.$("twofacode")){var g=new hi5.ui.Lightbox(b);g.show();b=hi5.$("btnTwoFACode");var m=hi5.$("faAuthCode");m.focus();m.value="";b.onclick=function(){a.send("code:"+m.value);g.dismiss()}}break;case "1":b=e.substring(4),showTwoFAQR(function(b,c){a.send("code:"+b)},b)}else b=JSON.parse(b.data),0===b.type&&(b.message||b.name)?svGlobal.gatewayError(b.name,b.message):(b.error||a.send("A1"+navigator.userAgent),f(b))}}}var h=
!1,d=hi5.browser.cookie2Obj();d.svSession&&d.svEmail&&(f+="&svSession="+d.svSession+"&svEmail="+encodeURIComponent(d.svEmail));setTimeout(function(){l(f,svGlobal.onloggedin)},5);return!1}};
function startExitingApp(k){function f(d){l.addSurface(d);l.startExitingApp(k)}var l=svManager.getInstance();window.svOnSurfaceReady=f;window.open("rail.html").svOnSurfaceReady=f;var h=hi5.$(k),d=h.parentNode;d.removeChild(h);d=d.parentNode;0==d.getElementsByTagName("input").length&&(d.dismiss(),l.checkRemaining(2E3))}function getLoginURL(){return("https:"==location.protocol?"wss://":"ws://")+hi5.$("gateway").value+"/LOGIN?"}
window.addEventListener("load",function(k){function f(){k.preventDefault();svGlobal.auth.beforesubmit&&svGlobal.auth.beforesubmit();var a=hi5.$("frmLogin").elements,b=a.user.value,e=a.pwd.value,b=getLoginURL()+"user="+encodeURIComponent(b)+"&pwd="+encodeURIComponent(e);(a=a.sharedSecret)&&a.value&&(b+="&sharedSecret="+encodeURIComponent(a.value));return svGlobal.auth.login(b)}function l(a,b){var e=svGlobal.auth.getLoginURL()+"action=code",c=new WebSocket(e,"login");c.onmessage=function(a){a=JSON.parse(a.data);
a.error?svGlobal.gatewayError(a.name,a.message):hi5.notifications.notify(__svi18n.info.succeeded);c.close()};c.onopen=function(e){c.send("twof:"+a+"\t"+__sparkUser.account+"\t"+b+"\t"+__sparkUser.session)}}function h(){window.__sparkUser=null;var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none";(a=svManager.getInstance())&&a.running()&&a.close()}function d(a){var b=a.target;b.onclick=null;setTimeout(function(){b.onclick=d},300);t(b.id)}function r(){function a(a){e.addSurface(a);
e.running()?e.startApp(b.exe,b.args,""):e.run()}var b=window.__sparkUser.server,e=svManager.getInstance();null==e&&(e=new svGlobal.Rdp2(b),e.sessionTimeout=9E5);window.svOnSurfaceReady=a;window.open("rail.html").svOnSurfaceReady=a}function t(a,b,e){var c=window.__sparkUser,d=c.servers,m=d.length;c.server=null;window.sparkGateway=c.gateway;for(var p=0;p<m;p++){var q=d[p];if(a==q.id){q.gateway=c.gateway;q.session=c.session;q.account=c.account;c.server=q;break}}if(c.server){console.log("connecting to:"+
c.server.id);(a=hi5.$("touchpad"))&&a.checked&&(c.server.touchpad=!0);if(a=hi5.$("keyboard"))a=parseInt(a.options[a.selectedIndex].value),0<a&&(c.server.keyboard=a);"undefined"==typeof b&&(b=(a=hi5.$("sameWindow"))&&a.checked);b&&!c.server.rdp&&(b=!1);if(c.server.rdp&&"app"==c.server.startProgram&&hi5.browser.isMultitask&&!b)r();else if(b){var n=new Rdp2(c.server);hi5.$("login").style.display="none";n.addSurface(new svGlobal.LocalInterface);n.run();n.onclose=function(){if(e){window.__sparkUser=null;
var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none"}else n.hide(),hi5.$("login").style.display="block"}}else b=document.getElementById("multiMon"),c.server.rdp?(b&&b.checked&&(c.server.rdp.multiMon="on"),window.open("rdpdirect.html")):c.server.vnc?window.open("vnc.html"):c.server.ssh?window.open("sshdirect.html"):c.server.telnet&&window.open("telnet.html")}else hi5.notifications.notify("Not a valid server")}svGlobal.auth.beforelogin=function(){hi5.tool.disableInput()};
svGlobal.auth.afterlogin=function(a){a||(hi5.notifications.notify(__svi18n.errorCode.connection),h());hi5.tool.enableInput()};svGlobal.onloggedin=function(a){hi5.tool.enableInput();if(a.error)svGlobal.gatewayError(a.name,a.message);else{hi5.$("frmLogin").style.display="none";hi5.$("frmConn").style.display="block";for(var b=hi5.$("programs");b.hasChildNodes();)b.removeChild(b.firstChild);var e=a.servers;if(!a.accessNotInList){var c=hi5.$("anyconn");c&&(c.style.display="none")}c=hi5.$("user").value;
hi5.appcfg&&hi5.appcfg.domain&&hi5.appcfg.hiddenDomain&&(c=hi5.appcfg.domain+"\\"+c);window.__sparkUser={session:a.session,account:c,gateway:hi5.$("gateway").value,servers:e,twoFA:a.twoFA,twoFAEnabled:a.twoFAEnabled,twoFAQR:a.twoFAQR};a=e.length;if(!(1>a)){for(var c="",g=0;g<a;g++){var m=e[g].server,p=e[g].id,m=e[g].displayName||p||m,q=e[g].icon;q||(q="rdp32.png");var n=document.createElement("div");n.className="icon";var f=document.createElement("img");f.src=q;f.id=p;f.alt=p;f.title=m;f.style.cursor=
"pointer";f.onclick=d;n.appendChild(f);n.appendChild(document.createElement("br"));n.appendChild(document.createTextNode(m));b.appendChild(n);hi5.appcfg.startup&&p===hi5.appcfg.startup.server&&(c=p)}!c&&hi5.appcfg.startup&&(console.log("start up:"+hi5.appcfg.startup.server+" not found, use the first instead"),c=e[0].id);c&&t(c,!hi5.appcfg.startup.newWindow,!0)}}};(function(){hi5.$("user").focus();hi5.$("frmLogin").onsubmit=f;var a=hi5.$("anyconn");a&&(a.onclick=function(){window.open("rdp.html?gateway="+
hi5.$("gateway").value)});if(a=document.querySelector('input[name="showlogin"]'))a.onclick=h;var a=hi5.browser.cookie2Obj(),b=-1!=document.cookie.indexOf("__SV_TOKEN_A"),d=hi5.tool.queryToObj();if(a.svEmail||a.user||b||d.autoLogin){var c=hi5.$("frmLogin").elements;c.user.value=a.svEmail||a.user||"";c.pwd.value=(a.svSession?"fake":a.pwd)||"_";a.gateway&&(c.gateway.value=a.gateway);(c.user.value&&c.pwd.value||a.autoLogin||b||d.autoLogin)&&setTimeout(f,30)}var a=hi5.$("settings"),g=hi5.$("settingsDiv");
a&&(a.onclick=function(){if(g){(new hi5.ui.Lightbox(g)).show();hi5.$("currPwd").focus();var a=hi5.$("btnTwoFA");a&&(a.onclick=function(){showTwoFAQR(l,window.__sparkUser.twoFAQR)},0==__sparkUser.twoFA&&a.parentNode.removeChild(a))}});if(a=hi5.$("frmSettings"))a.onsubmit=function(a){a.preventDefault();var b=a.target.elements;if(b.newPwd1.value!=b.newPwd2.value)hi5.notifications.notify(__svi18n.errorCode.pwdmatch);else{a=getLoginURL()+"_METHOD=post&action=put";var c=new WebSocket(a,"login");c.onmessage=
function(a){0==a.data.indexOf("00")?(c.send("00currPwd="+encodeURIComponent(b.currPwd.value)+"&newPwd="+encodeURIComponent(b.newPwd1.value)+"&user="+encodeURIComponent(hi5.$("user").value)),hi5.$("frmSettings").reset()):(a=JSON.parse(a.data),a.error&&svGlobal.gatewayError(a.name,a.message))};g.dismiss&&g.dismiss();return!1}};(a=hi5.$("sameWindow"))&&(hi5.browser.isiOS||hi5.browser.isIE||hi5.browser.isChromeApp)&&(a.checked=!0);a=hi5.$("gateway");(b=a.value)||(b=hi5.appcfg.defaultPort?window.location.hostname+
":"+hi5.appcfg.defaultPort:window.location.host);0==b.length&&(b="localhost");a.value=b;a=hi5.$("touchpadmode");hi5.browser.isTouch&&(a.style.display="");(a=hi5.$("user"))&&!a.value&&hi5.appcfg&&hi5.appcfg.domain&&(a.value=hi5.appcfg.domain+"\\");(function(){var a=!1,b="";try{document.createElement("canvas").getContext("2d"),a=!0}catch(u){b="This browser does not support Canvas.\n\n"}var c=!("WebSocket"in window)&&!("MozWebSocket"in window),d=navigator.userAgent,e=-1!=d.indexOf("Firefox");c&&(b+=
"This browser doesn't support WebSocket.\n\n",e?b+="Please update to Firefox 6 or later.\n\n":-1!=d.indexOf("Opera")?b+="Please open 'opera:config#Enable WebSockets' (type it in the link field) make 'Enable WebSockets' selected and restart Opera.\n\n":-1!=d.indexOf("MSIE")&&(b+="Please install Google Chrome Frame.\n\n"));0<b.length&&hi5.notifications.notify(b);return!c&&a})();(a=hi5.$("defPort"))&&hi5.appcfg.defaultPort&&(a.innerHTML=hi5.appcfg.defaultPort);(a=document.getElementById("frmConn"))&&
(a=a.querySelector('select[name="keyboard"]'));a&&(b=svGlobal.Rdp.languageToKeyboard.detect())&&(a.value=b)})()},!1);
