var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,h,a){if(b==Array.prototype||b==Object.prototype)return b;b[h]=a.value;return b};
$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var h=0;h<b.length;++h){var a=b[h];if(a&&a.Math==Math)return a}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,h){var a=$jscomp.propertyToPolyfillSymbol[h];if(null==a)return b[h];a=b[a];return void 0!==a?a:b[h]};$jscomp.polyfill=function(b,h,a,c){h&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,h,a,c):$jscomp.polyfillUnisolated(b,h,a,c))};
$jscomp.polyfillUnisolated=function(b,h,a,c){a=$jscomp.global;b=b.split(".");for(c=0;c<b.length-1;c++){var f=b[c];if(!(f in a))return;a=a[f]}b=b[b.length-1];c=a[b];h=h(c);h!=c&&null!=h&&$jscomp.defineProperty(a,b,{configurable:!0,writable:!0,value:h})};
$jscomp.polyfillIsolated=function(b,h,a,c){var f=b.split(".");b=1===f.length;c=f[0];c=!b&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var d=0;d<f.length-1;d++){var l=f[d];if(!(l in c))return;c=c[l]}f=f[f.length-1];a=$jscomp.IS_SYMBOL_NATIVE&&"es6"===a?c[f]:null;h=h(a);null!=h&&(b?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:h}):h!==a&&($jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+f,f=
$jscomp.propertyToPolyfillSymbol[f],$jscomp.defineProperty(c,f,{configurable:!0,writable:!0,value:h})))};$jscomp.polyfill("Array.from",function(b){return b?b:function(h,a,c){a=null!=a?a:function(e){return e};var f=[],d="undefined"!=typeof Symbol&&Symbol.iterator&&h[Symbol.iterator];if("function"==typeof d){h=d.call(h);for(var l=0;!(d=h.next()).done;)f.push(a.call(c,d.value,l++))}else for(d=h.length,l=0;l<d;l++)f.push(a.call(c,h[l],l));return f}},"es6","es3");
var QUERY_FILE_TYPE_RECORDING_FILE=1,QUERY_FILE_TYPE_INDEX_FILE=2,QUERY_EVNET_TYPE_USER_EVENT=4,QUERY_EVNET_TYPE_ATTACK_EVENT=6,QUERY_EVNET_TYPE_LICENSE_EVENT=8,QUERY_FILE_TYPE_INDEX_APP=9,QUERY_FILE_TYPE_KEYBOARD_INPUT=10,QUERY_FILE_TYPE_APP_USAGE=11,QUERY_FILE_TYPE_FILE_OPT=12,QUERY_FILE_TYPE_PRINT_OPT=13,RESPONSE_TYPE_RECORDING_FILE=1,RESPONSE_TYPE_INDEX_FILE=2,RESPONSE_TYPE_USER_EVENTS=4,RESPONSE_TYPE_ATTACK_EVENTS=6,RESPONSE_TYPE_LICENSE_EVENTS=8,RESPONSE_TYPE_INDEX_APP=9,RESPONSE_TYPE_KEYBOARD_INPUT=
10,RESPONSE_TYPE_APP_USAGE=11,RESPONSE_TYPE_FILE_OPT=12,RESPONSE_TYPE_PRINT_OPT=13,USER_EVENT_TYPE_CONNECT=0,USER_EVENT_TYPE_DISCONNECT=1,USER_EVENT_TYPE_CLOSE=2,queryType=0,wsObj;
function init(){console.log("init() host: "+window.location.host);document.getElementById("searchApp").style.display="none";document.getElementById("searchAppFormat").style.display="none";document.getElementById("searchKeyboard").style.display="none";var b=document.getElementById("playbacknote");b.style.fontWeight="bold";b.style.color="white";b.style.backgroundColor="grey";document.getElementById("keyboardnote").style.fontWeight="lighter";document.getElementById("applicationnote").style.fontWeight=
"lighter";document.getElementById("filenote").style.fontWeight="lighter";document.getElementById("printnote").style.fontWeight="lighter";document.getElementById("usereventnote").style.fontWeight="lighter";document.getElementById("attacknote").style.fontWeight="lighter";document.getElementById("licensenote").style.fontWeight="lighter";resetResult();wsObj||(wsObj=new WebSocketObj,wsObj.initialized=function(){console.log("WebSocket Object get initialized successfully.")});wsObj.initialize()}
function WebSocketObj(){var b=this,h;this.isConnected=!1;this.initialize=function(){h=new WebSocket(("https:"==location.protocol?"wss://":"ws://")+window.location.host+"/QUERY");h.binaryType="arraybuffer";h.onopen=function(){b.isConnected=!0;b.initialized&&b.initialized()};h.onmessage=function(a){try{b.processMsgFromMonitor(a.data)}catch(c){console.log(c)}};h.onclose=function(){console.log("SparkGatewayMonitor closed the connection.");h&&(h=null,b.isConnected?console.log("Lost connection to SparkGatewayMonitor."):
console.log("SparkGatewayMonitor is disconencted."));b.isConnected=!1};h.onerror=function(a){console.log("Websocket error observed: "+a);h&&h.close()}};this.retrieveFileContent=function(a,c,f,d,l,e){var g=new Uint8Array(9+c.length+1+f.length+1+1),k=0;g[k++]=a;g[k++]=d&255;g[k++]=d>>8&255;g[k++]=d>>16&255;g[k++]=d>>24&255;g[k++]=l&255;g[k++]=l>>8&255;g[k++]=l>>16&255;g[k++]=l>>24&255;for(a=0;a<c.length;a++)g[k++]=c.charCodeAt(a);for(a=g[k++]=0;a<f.length;a++)g[k++]=f.charCodeAt(a);g[k++]=0;g[k++]=
e?1:0;b.sendMsgToMonitor(g)};this.searchKeyboardInput=function(a,c,f,d,l,e){var g=new Uint8Array(9+c.length+1+f.length+1+d.length+1),k=0;g[k++]=a;g[k++]=l&255;g[k++]=l>>8&255;g[k++]=l>>16&255;g[k++]=l>>24&255;g[k++]=e&255;g[k++]=e>>8&255;g[k++]=e>>16&255;g[k++]=e>>24&255;for(a=0;a<c.length;a++)g[k++]=c.charCodeAt(a);for(a=g[k++]=0;a<f.length;a++)g[k++]=f.charCodeAt(a);for(a=g[k++]=0;a<d.length;a++)g[k++]=d.charCodeAt(a);g[k++]=0;b.sendMsgToMonitor(g)};this.searchAppUsage=function(a,c,f,d,l,e){var g=
new Uint8Array(9+c.length+1+f.length+1+d.length+1),k=0;g[k++]=a;g[k++]=l&255;g[k++]=l>>8&255;g[k++]=l>>16&255;g[k++]=l>>24&255;g[k++]=e&255;g[k++]=e>>8&255;g[k++]=e>>16&255;g[k++]=e>>24&255;for(a=0;a<c.length;a++)g[k++]=c.charCodeAt(a);for(a=g[k++]=0;a<f.length;a++)g[k++]=f.charCodeAt(a);for(a=g[k++]=0;a<d.length;a++)g[k++]=d.charCodeAt(a);g[k++]=0;b.sendMsgToMonitor(g)};this.retrieveUserEvents=function(a,c,f,d,l){var e=new Uint8Array(9+c.length+1+f.length+1),g=0;e[g++]=a;e[g++]=d&255;e[g++]=d>>8&
255;e[g++]=d>>16&255;e[g++]=d>>24&255;e[g++]=l&255;e[g++]=l>>8&255;e[g++]=l>>16&255;e[g++]=l>>24&255;for(a=0;a<c.length;a++)e[g++]=c.charCodeAt(a);for(a=e[g++]=0;a<f.length;a++)e[g++]=f.charCodeAt(a);e[g++]=0;b.sendMsgToMonitor(e)};this.retrieveAttackEvents=function(a,c,f){var d=new Uint8Array(9),l=0;d[l++]=a;d[l++]=c&255;d[l++]=c>>8&255;d[l++]=c>>16&255;d[l++]=c>>24&255;d[l++]=f&255;d[l++]=f>>8&255;d[l++]=f>>16&255;d[l++]=f>>24&255;b.sendMsgToMonitor(d)};this.retrieveLicenseEvents=function(a,c,f){var d=
new Uint8Array(9),l=0;d[l++]=a;d[l++]=c&255;d[l++]=c>>8&255;d[l++]=c>>16&255;d[l++]=c>>24&255;d[l++]=f&255;d[l++]=f>>8&255;d[l++]=f>>16&255;d[l++]=f>>24&255;b.sendMsgToMonitor(d)};this.sendMsgToMonitor=function(a){h&&h.readyState==h.OPEN?h.send(a):console.log("Error: failed to send data through websocket with state: "+h.readyState)};this.processMsgFromMonitor=function(a){a.byteLength&&(a=new Uint8Array(a));var c=a[0];switch(c){case RESPONSE_TYPE_RECORDING_FILE:console.log("Received content of recording files");
a=a.slice?new hi5.DataBuffer(a.slice(1,a.length)):new hi5.DataBuffer(a.subarray(1,a.length));var f=a.getLittleEndian16();setResultLabel(f);if(0<f){var d=document.getElementById("resultTable");c=document.createElement("table");c.setAttribute("class","resulttable");d.appendChild(c);d=window.location.host;1>d.length&&(d="localhost");var l=location.protocol+"//"+d+"/playeremote.html?file=";for(d=0;d<f;d++){var e=a.getBytes(16);e=arrayToUuidString(e);var g=a.getByte();g=getProtocolType(g);var k=document.createElement("a");
k.href=l+e+"&type="+g;e=document.createTextNode("recording_file_"+(d+1)+".rdpv");k.appendChild(e);k.target="_blank";e=c.insertRow(d);g=e.insertCell(0);g.appendChild(k);g=e.insertCell(1);g.innerHTML=""}}break;case RESPONSE_TYPE_INDEX_FILE:console.log("Received content of index files");a=a.slice?new hi5.DataBuffer(a.slice(1,a.length)):new hi5.DataBuffer(a.subarray(1,a.length));f=a.getLittleEndian16();setResultLabel(f);if(0<f)for(d=document.getElementById("resultTable"),c=document.createElement("table"),
c.setAttribute("class","resulttable"),d.appendChild(c),d=0;d<f;d++)e=a.getLittleEndian32(),e=a.getBytes(e),e=new Blob([e],{type:"text/plain"}),k=document.createElement("a"),k.href=window.URL.createObjectURL(e),e=document.createTextNode("index_file_"+(d+1)+".srt"),k.appendChild(e),k.download="index_file_"+(d+1)+".srt",e=c.insertRow(d),e=e.insertCell(0),e.appendChild(k);break;case RESPONSE_TYPE_INDEX_APP:console.log("Received content of application usage files");a=a.slice?new hi5.DataBuffer(a.slice(1,
a.length)):new hi5.DataBuffer(a.subarray(1,a.length));f=a.getLittleEndian16();setResultLabel(f);if(0<f)for(l=1==a.getByte()?".srt":".txt",d=document.getElementById("resultTable"),c=document.createElement("table"),c.setAttribute("class","resulttable"),d.appendChild(c),d=0;d<f;d++)e=a.getLittleEndian32(),e=a.getBytes(e),e=new Blob([e],{type:"text/plain"}),k=document.createElement("a"),k.href=window.URL.createObjectURL(e),e=document.createTextNode("app_usage_file_"+(d+1)+l),k.appendChild(e),k.download=
"app_usage_file_"+(d+1)+l,e=c.insertRow(d),e=e.insertCell(0),e.appendChild(k);break;case RESPONSE_TYPE_USER_EVENTS:console.log("Received user events");a=a.slice?new hi5.DataBuffer(a.slice(1,a.length)):new hi5.DataBuffer(a.subarray(1,a.length));f=a.getLittleEndian32();setResultLabel(f);if(0<f)for(d=document.getElementById("resultTable"),c=document.createElement("table"),c.setAttribute("class","resulttable"),d.appendChild(c),d=0;d<f;d++){e=a.getLittleEndian16();k=a.getAscllString(e,!1);e=a.getLittleEndian16();
var n=a.getAscllString(e,!1);l=a.getLittleEndian32();var m=a.getByte();e=c.insertRow(d);g=e.insertCell(0);g.innerHTML=k;g=e.insertCell(1);g.innerHTML=n;g=e.insertCell(2);g.innerHTML=parseEventType(m);e=e.insertCell(3);e.innerHTML=parseEventTime(l)}break;case RESPONSE_TYPE_ATTACK_EVENTS:console.log("Received attack events");a=a.slice?new hi5.DataBuffer(a.slice(1,a.length)):new hi5.DataBuffer(a.subarray(1,a.length));f=a.getLittleEndian32();setResultLabel(f);if(0<f)for(d=document.getElementById("resultTable"),
c=document.createElement("table"),c.setAttribute("class","resulttable"),d.appendChild(c),d=0;d<f;d++)e=a.getLittleEndian16(),m=a.getAscllString(e,!1),e=a.getLittleEndian16(),l=a.getAscllString(e,!1),e=a.getLittleEndian16(),k=a.getAscllString(e,!1),n=a.getLittleEndian32(),e=c.insertRow(d),g=e.insertCell(0),g.innerHTML=parseEventTime(n),g=e.insertCell(1),g.innerHTML=m,g=e.insertCell(2),g.innerHTML=l,e=e.insertCell(3),e.innerHTML=k;break;case RESPONSE_TYPE_LICENSE_EVENTS:console.log("Received license events");
a=a.slice?new hi5.DataBuffer(a.slice(1,a.length)):new hi5.DataBuffer(a.subarray(1,a.length));f=a.getLittleEndian32();setResultLabel(f);if(0<f)for(d=document.getElementById("resultTable"),c=document.createElement("table"),c.setAttribute("class","resulttable"),d.appendChild(c),d=0;d<f;d++)e=a.getLittleEndian16(),m=a.getAscllString(e,!1),l=a.getLittleEndian32(),a.getByte(),e=c.insertRow(d),g=e.insertCell(0),g.innerHTML=parseEventTime(l),g=e.insertCell(1),g.innerHTML=m;break;case RESPONSE_TYPE_KEYBOARD_INPUT:console.log("Received result of searching keyboard input");
a=a.slice?new hi5.DataBuffer(a.slice(1,a.length)):new hi5.DataBuffer(a.subarray(1,a.length));f=a.getLittleEndian16();setResultLabel(f);if(0<f)for(d=document.getElementById("resultTable"),c=document.createElement("table"),c.setAttribute("class","resulttable"),d.appendChild(c),d=window.location.host,1>d.length&&(d="localhost"),l=location.protocol+"//"+d+"/playeremote.html?file=",d=0;d<f;d++){e=a.getBytes(16);e=arrayToUuidString(e);g=a.getByte();g=getProtocolType(g);m="";k=a.getLittleEndian16();for(n=
0;n<k;n++){var p=a.getLittleEndian16();p=a.getAscllString(p,!1);m=m?m+"<br/>"+p:p}k=document.createElement("a");k.href=l+e+"&type="+g;e=document.createTextNode("recording_file_"+(d+1)+".rdpv");k.appendChild(e);k.target="_blank";e=c.insertRow(d);g=e.insertCell(0);g.appendChild(k);m&&(g=e.insertCell(1),g.innerHTML=m)}break;case RESPONSE_TYPE_APP_USAGE:console.log("Received result of searching application usage");a=a.slice?new hi5.DataBuffer(a.slice(1,a.length)):new hi5.DataBuffer(a.subarray(1,a.length));
f=a.getLittleEndian16();setResultLabel(f);if(0<f)for(d=document.getElementById("resultTable"),c=document.createElement("table"),c.setAttribute("class","resulttable"),d.appendChild(c),d=window.location.host,1>d.length&&(d="localhost"),l=location.protocol+"//"+d+"/playeremote.html?file=",d=0;d<f;d++){e=a.getBytes(16);e=arrayToUuidString(e);g=a.getByte();g=getProtocolType(g);m="";k=a.getLittleEndian16();for(n=0;n<k;n++)p=a.getLittleEndian16(),p=a.getAscllString(p,!1),m=m?m+"<br/>"+p:p;k=document.createElement("a");
k.href=l+e+"&type="+g;e=document.createTextNode("recording_file_"+(d+1)+".rdpv");k.appendChild(e);k.target="_blank";e=c.insertRow(d);g=e.insertCell(0);g.appendChild(k);m&&(g=e.insertCell(1),g.innerHTML=m)}break;case RESPONSE_TYPE_FILE_OPT:console.log("Received content of file operation files");a=a.slice?new hi5.DataBuffer(a.slice(1,a.length)):new hi5.DataBuffer(a.subarray(1,a.length));f=a.getLittleEndian16();setResultLabel(f);if(0<f)for(d=document.getElementById("resultTable"),c=document.createElement("table"),
c.setAttribute("class","resulttable"),d.appendChild(c),d=0;d<f;d++)e=a.getLittleEndian32(),e=a.getBytes(e),e=new Blob([e],{type:"text/plain"}),k=document.createElement("a"),k.href=window.URL.createObjectURL(e),e=document.createTextNode("file_transfer_"+(d+1)+".txt"),k.appendChild(e),k.download="file_transfer_"+(d+1)+".txt",e=c.insertRow(d),e=e.insertCell(0),e.appendChild(k);break;case RESPONSE_TYPE_PRINT_OPT:console.log("Received content of print operation files");a=a.slice?new hi5.DataBuffer(a.slice(1,
a.length)):new hi5.DataBuffer(a.subarray(1,a.length));f=a.getLittleEndian16();setResultLabel(f);if(0<f)for(d=document.getElementById("resultTable"),c=document.createElement("table"),c.setAttribute("class","resulttable"),d.appendChild(c),d=0;d<f;d++)e=a.getLittleEndian32(),e=a.getBytes(e),e=new Blob([e],{type:"text/plain"}),k=document.createElement("a"),k.href=window.URL.createObjectURL(e),e=document.createTextNode("print_history_"+(d+1)+".txt"),k.appendChild(e),k.download="print_history_"+(d+1)+".txt",
e=c.insertRow(d),e=e.insertCell(0),e.appendChild(k);break;default:throw"Invalid channel data received: unknown type ["+c+"], ignored.";}}}function parseEventType(b){switch(b){case USER_EVENT_TYPE_CONNECT:return"Connect";case USER_EVENT_TYPE_DISCONNECT:return"Disconnect";case USER_EVENT_TYPE_CLOSE:return"Close";default:return"Unknown"}}function getProtocolType(b){return 0==b?"RDP":1==b?"VNC":2==b?"SSH":3==b?"TEL":"RDP"}
function arrayToUuidString(b){return Array.from(b,function(h){return("0"+(h&255).toString(16)).slice(-2)}).join("").replace(/(.{8})(.{4})(.{4})(.{4})(.{12})/,"$1-$2-$3-$4-$5")}function parseEventTime(b){var h=new Date(1970,0,1);h.setSeconds(b);return h.getUTCFullYear()+"-"+(h.getUTCMonth()+1)+"-"+h.getUTCDate()+" "+h.getUTCHours()+":"+h.getUTCMinutes()+":"+h.getUTCSeconds()+"(UTC)"}
function getRecordingFile(){if(wsObj&&wsObj.isConnected){var b=document.getElementById("userName").value,h=document.getElementById("hostName").value,a=new Date(document.getElementById("startTime").value),c=new Date(document.getElementById("endTime").value);isNaN(a)?(document.getElementById("errorMsg").innerHTML="Please provide the StartTime",document.getElementById("errorDiv").style.display="block"):(a=a.getTime()/1E3,c=isNaN(c)?Date.now()/1E3:c.getTime()/1E3,wsObj.retrieveFileContent(QUERY_FILE_TYPE_RECORDING_FILE,
b,h,a,c,!1))}}
function getIndexFile(){if(wsObj&&wsObj.isConnected){var b=document.getElementById("userName").value,h=document.getElementById("hostName").value,a=new Date(document.getElementById("startTime").value),c=new Date(document.getElementById("endTime").value);isNaN(a)?(document.getElementById("errorMsg").innerHTML="Please provide the StartTime",document.getElementById("errorDiv").style.display="block"):(a=a.getTime()/1E3,c=isNaN(c)?Math.round(Date.now()/1E3):c.getTime()/1E3,wsObj.retrieveFileContent(QUERY_FILE_TYPE_INDEX_FILE,b,
h,a,c,!0))}}
function getFileOptFile(){if(wsObj&&wsObj.isConnected){var b=document.getElementById("userName").value,h=document.getElementById("hostName").value,a=new Date(document.getElementById("startTime").value),c=new Date(document.getElementById("endTime").value);isNaN(a)?(document.getElementById("errorMsg").innerHTML="Please provide the StartTime",document.getElementById("errorDiv").style.display="block"):(a=a.getTime()/1E3,c=isNaN(c)?Math.round(Date.now()/1E3):c.getTime()/1E3,wsObj.retrieveFileContent(QUERY_FILE_TYPE_FILE_OPT,b,
h,a,c,!1))}}
function getPrintOptFile(){if(wsObj&&wsObj.isConnected){var b=document.getElementById("userName").value,h=document.getElementById("hostName").value,a=new Date(document.getElementById("startTime").value),c=new Date(document.getElementById("endTime").value);isNaN(a)?(document.getElementById("errorMsg").innerHTML="Please provide the StartTime",document.getElementById("errorDiv").style.display="block"):(a=a.getTime()/1E3,c=isNaN(c)?Math.round(Date.now()/1E3):c.getTime()/1E3,wsObj.retrieveFileContent(QUERY_FILE_TYPE_PRINT_OPT,b,
h,a,c,!1))}}function getIndexApp(){getIndexAppUsage(!1)}function getIndexAppSrt(){getIndexAppUsage(!0)}
function getIndexAppUsage(b){if(wsObj&&wsObj.isConnected){var h=document.getElementById("userName").value,a=document.getElementById("hostName").value,c=new Date(document.getElementById("startTime").value),f=new Date(document.getElementById("endTime").value);isNaN(c)?(document.getElementById("errorMsg").innerHTML="Please provide the StartTime",document.getElementById("errorDiv").style.display="block"):(c=c.getTime()/1E3,f=isNaN(f)?Math.round(Date.now()/1E3):f.getTime()/1E3,wsObj.retrieveFileContent(QUERY_FILE_TYPE_INDEX_APP,
h,a,c,f,b))}}
function searchKeyboardInput(){resetResult();if(wsObj&&wsObj.isConnected){var b=document.getElementById("userName").value,h=document.getElementById("hostName").value,a=document.getElementById("searchKey").value,c=new Date(document.getElementById("startTime").value),f=new Date(document.getElementById("endTime").value);isNaN(c)?(document.getElementById("errorMsg").innerHTML="Please provide the StartTime",document.getElementById("errorDiv").style.display="block"):(c=c.getTime()/1E3,f=isNaN(f)?Math.round(Date.now()/
1E3):f.getTime()/1E3,wsObj.searchKeyboardInput(QUERY_FILE_TYPE_KEYBOARD_INPUT,b,h,a,c,f))}}
function searchAppUsage(){resetResult();if(wsObj&&wsObj.isConnected){var b=document.getElementById("userName").value,h=document.getElementById("hostName").value,a=document.getElementById("searchAppName").value,c=new Date(document.getElementById("startTime").value),f=new Date(document.getElementById("endTime").value);isNaN(c)?(document.getElementById("errorMsg").innerHTML="Please provide the StartTime",document.getElementById("errorDiv").style.display="block"):(c=c.getTime()/1E3,f=isNaN(f)?Math.round(Date.now()/
1E3):f.getTime()/1E3,wsObj.searchAppUsage(QUERY_FILE_TYPE_APP_USAGE,b,h,a,c,f))}}
function getUserEvents(){if(wsObj&&wsObj.isConnected){var b=document.getElementById("userName").value,h=document.getElementById("hostName").value,a=new Date(document.getElementById("startTime").value),c=new Date(document.getElementById("endTime").value);isNaN(a)?(document.getElementById("errorMsg").innerHTML="Please provide the StartTime",document.getElementById("errorDiv").style.display="block"):(a=a.getTime()/1E3,c=isNaN(c)?Math.round(Date.now()/1E3):c.getTime()/1E3,wsObj.retrieveUserEvents(QUERY_EVNET_TYPE_USER_EVENT,
b,h,a,c))}}function getAttackEvents(){if(wsObj&&wsObj.isConnected){var b=new Date(document.getElementById("startTime").value),h=new Date(document.getElementById("endTime").value);isNaN(b)?(document.getElementById("errorMsg").innerHTML="Please provide the StartTime",document.getElementById("errorDiv").style.display="block"):(b=b.getTime()/1E3,h=isNaN(h)?Math.round(Date.now()/1E3):h.getTime()/1E3,wsObj.retrieveAttackEvents(QUERY_EVNET_TYPE_ATTACK_EVENT,b,h))}}
function getLicenseEvents(){if(wsObj&&wsObj.isConnected){var b=new Date(document.getElementById("startTime").value),h=new Date(document.getElementById("endTime").value);isNaN(b)?(document.getElementById("errorMsg").innerHTML="Please provide the StartTime",document.getElementById("errorDiv").style.display="block"):(b=b.getTime()/1E3,h=isNaN(h)?Math.round(Date.now()/1E3):h.getTime()/1E3,wsObj.retrieveLicenseEvents(QUERY_EVNET_TYPE_LICENSE_EVENT,b,h))}}
function resetResult(){document.getElementById("errorMsg").innerHTML="";document.getElementById("errorDiv").style.display="none";document.getElementById("result").style.display="none";for(var b=document.getElementById("resultTable");b.firstChild;)b.firstChild.remove()}window.addEventListener("load",init,!1);
function loadRecordingQuery(){resetItemStyle();var b=document.getElementById("playbacknote");b.style.fontWeight="bold";b.style.color="white";b.style.backgroundColor="grey";document.getElementById("searchApp").style.display="none";document.getElementById("searchAppFormat").style.display="none";document.getElementById("searchKeyboard").style.display="none";queryType=0;resetResult()}
function loadKeyboardInputQuery(){resetItemStyle();var b=document.getElementById("keyboardnote");b.style.fontWeight="bold";b.style.color="white";b.style.backgroundColor="grey";document.getElementById("searchApp").style.display="none";document.getElementById("searchAppFormat").style.display="none";document.getElementById("searchKeyboard").style.display="block";queryType=1;resetResult()}
function loadApplicationQuery(){resetItemStyle();var b=document.getElementById("applicationnote");b.style.fontWeight="bold";b.style.color="white";b.style.backgroundColor="grey";document.getElementById("searchApp").style.display="block";document.getElementById("searchAppFormat").style.display="block";document.getElementById("searchKeyboard").style.display="none";queryType=2;resetResult()}
function loadFileTransferQuery(){resetItemStyle();var b=document.getElementById("filenote");b.style.fontWeight="bold";b.style.color="white";b.style.backgroundColor="grey";document.getElementById("searchApp").style.display="none";document.getElementById("searchAppFormat").style.display="none";document.getElementById("searchKeyboard").style.display="none";queryType=3;resetResult()}
function loadUserEventQuery(){resetItemStyle();var b=document.getElementById("usereventnote");b.style.fontWeight="bold";b.style.color="white";b.style.backgroundColor="grey";document.getElementById("searchApp").style.display="none";document.getElementById("searchAppFormat").style.display="none";document.getElementById("searchKeyboard").style.display="none";queryType=4;resetResult()}
function loadAttackQuery(){resetItemStyle();var b=document.getElementById("attacknote");b.style.fontWeight="bold";b.style.color="white";b.style.backgroundColor="grey";document.getElementById("searchApp").style.display="none";document.getElementById("searchAppFormat").style.display="none";document.getElementById("searchKeyboard").style.display="none";queryType=5;resetResult()}
function loadLicenseQuery(){resetItemStyle();var b=document.getElementById("licensenote");b.style.fontWeight="bold";b.style.color="white";b.style.backgroundColor="grey";document.getElementById("searchApp").style.display="none";document.getElementById("searchAppFormat").style.display="none";document.getElementById("searchKeyboard").style.display="none";queryType=6;resetResult()}
function loadPrintQuery(){resetItemStyle();var b=document.getElementById("printnote");b.style.fontWeight="bold";b.style.color="white";b.style.backgroundColor="grey";document.getElementById("searchApp").style.display="none";document.getElementById("searchAppFormat").style.display="none";document.getElementById("searchKeyboard").style.display="none";queryType=7;resetResult()}
function search(){resetResult();switch(queryType){case 0:getRecordingFile();break;case 1:document.getElementById("searchKey").value?searchKeyboardInput():getIndexFile();break;case 2:document.getElementById("searchAppName").value?searchAppUsage():document.getElementById("searchAppSrt").checked?getIndexAppSrt():getIndexApp();break;case 3:getFileOptFile();break;case 4:getUserEvents();break;case 5:getAttackEvents();break;case 6:getLicenseEvents();break;case 7:getPrintOptFile();break;default:getRecordingFile()}}
function setResultLabel(b){document.getElementById("result").style.display="block";var h=document.getElementById("resultLabel");switch(queryType){case 0:h.innerHTML="Recordings files: <b>"+b+"</b>";break;case 1:h.innerHTML="Keyboard inputs files: <b>"+b+"</b>";break;case 2:h.innerHTML="Application Usage files: <b>"+b+"</b>";break;case 3:h.innerHTML="File transfer files: <b>"+b+"</b>";break;case 4:h.innerHTML="User events: <b>"+b+"</b>";break;case 5:h.innerHTML="Attack events: <b>"+b+"</b>";break;
case 6:h.innerHTML="License events: <b>"+b+"</b>";break;case 7:h.innerHTML="Print files: <b>"+b+"</b>";break;default:h.innerHTML="Found files: <b>"+b+"</b>"}}function clearErrorMsg(){document.getElementById("errorMsg").innerHTML="";document.getElementById("errorDiv").style.display="none"}
function resetItemStyle(){document.getElementById("playbacknote").style.color="grey";document.getElementById("playbacknote").style.backgroundColor="#fafafa";document.getElementById("playbacknote").style.fontWeight="lighter";document.getElementById("keyboardnote").style.color="grey";document.getElementById("keyboardnote").style.backgroundColor="#fafafa";document.getElementById("keyboardnote").style.fontWeight="lighter";document.getElementById("applicationnote").style.color="grey";document.getElementById("applicationnote").style.backgroundColor=
"#fafafa";document.getElementById("applicationnote").style.fontWeight="lighter";document.getElementById("filenote").style.color="grey";document.getElementById("filenote").style.backgroundColor="#fafafa";document.getElementById("filenote").style.fontWeight="lighter";document.getElementById("printnote").style.color="grey";document.getElementById("printnote").style.backgroundColor="#fafafa";document.getElementById("printnote").style.fontWeight="lighter";document.getElementById("usereventnote").style.color=
"grey";document.getElementById("usereventnote").style.backgroundColor="#fafafa";document.getElementById("usereventnote").style.fontWeight="lighter";document.getElementById("attacknote").style.color="grey";document.getElementById("attacknote").style.backgroundColor="#fafafa";document.getElementById("attacknote").style.fontWeight="lighter";document.getElementById("licensenote").style.color="grey";document.getElementById("licensenote").style.backgroundColor="#fafafa";document.getElementById("licensenote").style.fontWeight=
"lighter"};
