var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var g=0;return function(){return g<a.length?{done:!1,value:a[g++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var g="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return g?g.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var g=0;g<a.length;++g){var k=a[g];if(k&&k.Math==Math)return k}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},g=Object.create(new $jscomp.global.Proxy(a,{get:function(k,h,p){return k==a&&"q"==h&&p==g}}));return!0===g.q}catch(k){return!1}};
$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,k){if(a==Array.prototype||a==Object.prototype)return a;a[g]=k.value;return a};$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";
var $jscomp$lookupPolyfilledValue=function(a,g){var k=$jscomp.propertyToPolyfillSymbol[g];if(null==k)return a[g];k=a[k];return void 0!==k?k:a[g]};$jscomp.polyfill=function(a,g,k,h){g&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,g,k,h):$jscomp.polyfillUnisolated(a,g,k,h))};
$jscomp.polyfillUnisolated=function(a,g,k,h){k=$jscomp.global;a=a.split(".");for(h=0;h<a.length-1;h++){var p=a[h];if(!(p in k))return;k=k[p]}a=a[a.length-1];h=k[a];g=g(h);g!=h&&null!=g&&$jscomp.defineProperty(k,a,{configurable:!0,writable:!0,value:g})};
$jscomp.polyfillIsolated=function(a,g,k,h){var p=a.split(".");a=1===p.length;h=p[0];h=!a&&h in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var t=0;t<p.length-1;t++){var r=p[t];if(!(r in h))return;h=h[r]}p=p[p.length-1];k=$jscomp.IS_SYMBOL_NATIVE&&"es6"===k?h[p]:null;g=g(k);null!=g&&(a?$jscomp.defineProperty($jscomp.polyfills,p,{configurable:!0,writable:!0,value:g}):g!==k&&($jscomp.propertyToPolyfillSymbol[p]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(p):$jscomp.POLYFILL_PREFIX+p,p=
$jscomp.propertyToPolyfillSymbol[p],$jscomp.defineProperty(h,p,{configurable:!0,writable:!0,value:g})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var g=function(p,t){this.$jscomp$symbol$id_=p;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:t})};g.prototype.toString=function(){return this.$jscomp$symbol$id_};var k=0,h=function(p){if(this instanceof h)throw new TypeError("Symbol is not a constructor");return new g("jscomp_symbol_"+(p||"")+"_"+k++,p)};return h},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var g="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),k=0;k<g.length;k++){var h=$jscomp.global[g[k]];"function"===typeof h&&"function"!=typeof h.prototype[a]&&$jscomp.defineProperty(h.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.owns=function(a,g){return Object.prototype.hasOwnProperty.call(a,g)};
$jscomp.polyfill("WeakMap",function(a){function g(){if(!a||!Object.seal)return!1;try{var d=Object.seal({}),b=Object.seal({}),n=new a([[d,2],[b,3]]);if(2!=n.get(d)||3!=n.get(b))return!1;n.delete(d);n.set(b,4);return!n.has(d)&&4==n.get(b)}catch(v){return!1}}function k(){}function h(d){var b=typeof d;return"object"===b&&null!==d||"function"===b}function p(d){if(!$jscomp.owns(d,r)){var b=new k;$jscomp.defineProperty(d,r,{value:b})}}function t(d){if(!$jscomp.ISOLATE_POLYFILLS){var b=Object[d];b&&(Object[d]=
function(n){if(n instanceof k)return n;Object.isExtensible(n)&&p(n);return b(n)})}}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(g())return a;var r="$jscomp_hidden_"+Math.random();t("freeze");t("preventExtensions");t("seal");var x=0,e=function(d){this.id_=(x+=Math.random()+1).toString();if(d){d=$jscomp.makeIterator(d);for(var b;!(b=d.next()).done;)b=b.value,this.set(b[0],b[1])}};e.prototype.set=function(d,b){if(!h(d))throw Error("Invalid WeakMap key");
p(d);if(!$jscomp.owns(d,r))throw Error("WeakMap key fail: "+d);d[r][this.id_]=b;return this};e.prototype.get=function(d){return h(d)&&$jscomp.owns(d,r)?d[r][this.id_]:void 0};e.prototype.has=function(d){return h(d)&&$jscomp.owns(d,r)&&$jscomp.owns(d[r],this.id_)};e.prototype.delete=function(d){return h(d)&&$jscomp.owns(d,r)&&$jscomp.owns(d[r],this.id_)?delete d[r][this.id_]:!1};return e},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function g(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var e=Object.seal({x:4}),d=new a($jscomp.makeIterator([[e,"s"]]));if("s"!=d.get(e)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var b=d.entries(),n=b.next();if(n.done||n.value[0]!=e||"s"!=n.value[1])return!1;n=b.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!b.next().done?!1:!0}catch(v){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(g())return a;var k=new WeakMap,h=function(e){this.data_={};this.head_=r();this.size=0;if(e){e=$jscomp.makeIterator(e);for(var d;!(d=e.next()).done;)d=d.value,this.set(d[0],d[1])}};h.prototype.set=function(e,d){e=0===e?0:e;var b=p(this,e);b.list||(b.list=this.data_[b.id]=[]);b.entry?b.entry.value=d:(b.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:e,value:d},b.list.push(b.entry),
this.head_.previous.next=b.entry,this.head_.previous=b.entry,this.size++);return this};h.prototype.delete=function(e){e=p(this,e);return e.entry&&e.list?(e.list.splice(e.index,1),e.list.length||delete this.data_[e.id],e.entry.previous.next=e.entry.next,e.entry.next.previous=e.entry.previous,e.entry.head=null,this.size--,!0):!1};h.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=r();this.size=0};h.prototype.has=function(e){return!!p(this,e).entry};h.prototype.get=function(e){return(e=
p(this,e).entry)&&e.value};h.prototype.entries=function(){return t(this,function(e){return[e.key,e.value]})};h.prototype.keys=function(){return t(this,function(e){return e.key})};h.prototype.values=function(){return t(this,function(e){return e.value})};h.prototype.forEach=function(e,d){for(var b=this.entries(),n;!(n=b.next()).done;)n=n.value,e.call(d,n[1],n[0],this)};h.prototype[Symbol.iterator]=h.prototype.entries;var p=function(e,d){var b=d&&typeof d;"object"==b||"function"==b?k.has(d)?b=k.get(d):
(b=""+ ++x,k.set(d,b)):b="p_"+d;var n=e.data_[b];if(n&&$jscomp.owns(e.data_,b))for(e=0;e<n.length;e++){var v=n[e];if(d!==d&&v.key!==v.key||d===v.key)return{id:b,list:n,index:e,entry:v}}return{id:b,list:n,index:-1,entry:void 0}},t=function(e,d){var b=e.head_;return $jscomp.iteratorPrototype(function(){if(b){for(;b.head!=e.head_;)b=b.previous;for(;b.next!=b.head;)return b=b.next,{done:!1,value:d(b)};b=null}return{done:!0,value:void 0}})},r=function(){var e={};return e.previous=e.next=e.head=e},x=0;
return h},"es6","es3");
hi5.PasskeyClient=function(){function a(c,l){var f="action=registerstart&user="+encodeURIComponent(c),m=new XMLHttpRequest;m.open("POST","/PASSKEY",!0);m.setRequestHeader("Content-Type","application/x-www-form-urlencoded");m.onreadystatechange=function(){this.readyState===XMLHttpRequest.DONE&&(200===this.status?l(this.responseText,c):500==this.status&&this.responseText?b(this.responseText):b("Connection failed. Passkey may be disabled."))};m.send(f)}function g(c,l){var f=JSON.parse(c),m=f.requestId;
c={};c.publicKey=f.publicKeyCredentialCreationOptions;c.publicKey.user&&c.publicKey.user.id&&(c.publicKey.user.id=n(c.publicKey.user.id));c.publicKey.challenge&&(c.publicKey.challenge=n(c.publicKey.challenge));if(c.publicKey.excludeCredentials){f=$jscomp.makeIterator(c.publicKey.excludeCredentials);for(var q=f.next();!q.done;q=f.next())excludeCred=q.value,excludeCred.id&&(excludeCred.id=n(excludeCred.id))}navigator.credentials.create(c).then(function(u){u=JSON.stringify(u);k(l,m,u)}).catch(function(u){b("Authenticator could not generate a passkey, see console log for details")})}
function k(c,l,f){c=encodeURIComponent(c);l=encodeURIComponent(l);f=encodeURIComponent(f);f="action=registercomplete&user="+c+"&requestid="+l+"&registerresponse="+f;c=new XMLHttpRequest;c.open("POST","/PASSKEY",!0);c.setRequestHeader("Content-Type","application/x-www-form-urlencoded");c.onreadystatechange=function(){this.readyState===XMLHttpRequest.DONE&&(200===this.status?hi5.notifications.notify("New Passkey has been created successfully"):500==this.status&&this.responseText?b(this.responseText):
b("Connection failed"))};c.send(f)}function h(c,l){var f=JSON.parse(c),m=f.requestId;c={};f=f.publicKeyCredentialRequestOptions;if(f.allowCredentials)for(var q=$jscomp.makeIterator(f.allowCredentials),u=q.next();!u.done;u=q.next())allowCred=u.value,allowCred.id&&(allowCred.id=n(allowCred.id));f.challenge&&(f.challenge=n(f.challenge));c.publicKey=f;navigator.credentials.get(c).then(function(w){var y={};y.credential=w;y.requestId=m;w=JSON.stringify(y);p(l,m,w)}).catch(function(w){b(w.message+", code: "+
w.code)})}function p(c,l,f){var m="action=logincomplete";c&&(c=encodeURIComponent(c),m+="&user="+c);l=encodeURIComponent(l);m+="&requestid="+l;f=encodeURIComponent(f);m+="&loginresponse="+f;f=new XMLHttpRequest;f.open("POST","/PASSKEY",!0);f.setRequestHeader("Content-Type","application/x-www-form-urlencoded");f.onreadystatechange=function(){if(this.readyState===XMLHttpRequest.DONE)if(200===this.status){var q=hi5.browser.cookie2Obj();q.svSession&&q.svEmail&&encodeURIComponent(q.svEmail);q=svGlobal.auth.getLoginURL();
svGlobal.auth.login(q)}else 500==this.status&&this.responseText?b(this.responseText):b("Connection failed")};f.send(m)}function t(c,l){var f="action=requestregistrations&user="+encodeURIComponent(c),m=new XMLHttpRequest;m.open("POST","/PASSKEY",!0);m.setRequestHeader("Content-Type","application/x-www-form-urlencoded");m.onreadystatechange=function(){this.readyState===XMLHttpRequest.DONE&&(200===this.status?l(this.responseText,c):500==this.status&&this.responseText?b(this.responseText):b("Connection failed, Passkey may be disabled."))};
m.send(f)}function r(c,l){c=JSON.parse(c);var f=c.registrations.length,m=e();if(0==f){if(m){m.innerHTML="<p>Could not find any passkey</p>";var q=new hi5.ui.Lightbox(m.parentNode);q.show()}}else{m.innerHTML="";for(f=0;f<c.registrations.length;f++){var u=c.registrations[f];u=x(f,l,u.timestamp,u.credentialId);m.appendChild(u)}q=new hi5.ui.Lightbox(m.parentNode,{btnYes:{onclick:function(){q.dismiss();d(l)}}});q.show()}}function x(c,l,f,m){v.set(c,m);l="<b>User:&nbsp;</b>"+l+"&nbsp;&nbsp;&nbsp;<b>created at:</b> "+
f;f=document.createElement("div");f.style.width="440px";f.style.paddingBottom="5px";m=document.createElement("input");m.type="checkbox";m.name="passkeyRegistration";m.value=c;f.appendChild(m);f.innerHTML+=l;f.innerHTML+="</br>";return f}function e(){var c=document.getElementById("passkeySelection");return c?c.querySelector("div[name=passkeys]"):null}function d(c){var l="",f=e().querySelectorAll("input[type=checkbox][name=passkeyRegistration]:checked");if(0<f.length){for(var m=0;m<f.length;m++){var q=
parseInt(f[m].value);q=v.get(q);l+=q;l+=","}f="action=deleteregistrations&user=";c&&(c=encodeURIComponent(c),f+="&user="+c);0<l.length&&(l=encodeURIComponent(l),f+="&selectedcredentialids="+l);l=new XMLHttpRequest;l.open("POST","/PASSKEY",!0);l.setRequestHeader("Content-Type","application/x-www-form-urlencoded");l.onreadystatechange=function(){this.readyState===XMLHttpRequest.DONE&&(200===this.status?hi5.notifications.notify("Passkey has been removed successfully"):500==this.status&&this.responseText?
b(this.responseText):b("Connection failed"))};l.send(f)}}function b(c){hi5.notifications.notify("Failed to handle passkey: "+c)}function n(c){var l="==".slice(0,(4-c.length%4)%4);c=c.replace(/-/g,"+").replace(/_/g,"/")+l;c=atob(c);l=new ArrayBuffer(c.length);for(var f=new Uint8Array(l),m=0;m<c.length;m++)f[m]=c.charCodeAt(m);return l}this.passkeyAdd=function(){var c=hi5.$("user");hi5.notifications.clearAll();c.value?a(c.value,g):b("Please login first")};this.passkeySignIn=function(){var c="action=loginstart",
l=hi5.$("user").value;l&&(c+="&user="+encodeURIComponent(l));var f=new XMLHttpRequest;f.open("POST","/PASSKEY",!0);f.setRequestHeader("Content-Type","application/x-www-form-urlencoded");f.onreadystatechange=function(){this.readyState===XMLHttpRequest.DONE&&(200===this.status?h(this.responseText,l):500==this.status&&this.responseText?b(this.responseText):b("Connection failed. Passkey may be disabled."))};f.send(c)};var v=new Map;this.passkeyDel=function(){v.clear();var c=hi5.$("user");hi5.notifications.clearAll();
c.value?t(c.value,r):b("Please login first")}};hi5.PasskeyClient.supportsPasskey=function(a){window.PublicKeyCredential&&"https:"==location.protocol?PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable().then(function(g){return a(g)}).catch(function(g){console.error(g);a(!1)}):a(!1)};
