var wsRdp=null;
function websocketData(a){a=a.data;switch(a.type){case 0:switch(a.cmd){case 0:initialize(a.data);break;case 1:setBpp(a.data);break;case 2:setResolution(a.data);break;case 3:restoreVar();break;case 4:wsRdp&&wsRdp.close();setTimeout(function(){close()},50);break;case 5:wsRdp.setAudioFormat(a.data);break;case 6:wsRdp.onSlowPath=a.start?wsRdp.onFastPath=function(){_dataReceived.id=1;self.postMessage(_dataReceived)}:wsRdp.onFastPath=null;break;case 7:historyCallback();break;default:console.log("invalid cmd:"+a.cmd),
console.log(a)}break;case 5:wsRdp.writeRawInput(a.data);break;case 6:localFilePlayer.onmessage(a);break;default:console.log("Invalid msg type: "+a.type),console.log(a)}}function FilePlayerProxy(){this.onmessage=function(){};this.onclose=function(){};this.onopen=function(){};this.close=function(){}}var localFilePlayer=new FilePlayerProxy,historyCallback=null;self.addEventListener("message",websocketData,!1);
var _cursorMov={type:1,event:6,x:0,y:0},_cursor={type:9,cache_idx:0,rawData:null,none:!1,hotX:0,hotY:0,width:0,height:0,xorSize:0,andSize:0,result:"",distance:0,bpp:0,system:""},_msgData={type:10,data:null},_altSecData={type:11,data:null,size:0},_dataReceived={type:1,event:8,id:0};
function initialize(a){var e=a.libPath,f=!1!==a.libMin?"_min.js":".js";importScripts(e+"hi5core"+f);importScripts(e+"rdpcore"+f);wsRdp=a.addr?new RdpGeneral(a.addr,a.width,a.height,a.server_bpp,new DisplayBufferWrapper,!0,a.wsPost):new RdpGeneral(localFilePlayer,a.width,a.height,a.server_bpp,new DisplayBufferWrapper,!0,!1);wsRdp.onopen=function(){self.postMessage({type:1,event:0})};wsRdp.onclose=function(a){self.postMessage({type:1,event:1,expected:a})};wsRdp.onerror=function(a){self.postMessage({type:1,
event:2,code:a})};wsRdp.oninfo=function(a){self.postMessage({type:1,event:3,code:a})};wsRdp.onloggedin=function(a){self.postMessage({type:1,event:4})};wsRdp.onHistoryReceived=function(){_dataReceived.id=0;self.postMessage(_dataReceived)};wsRdp.onReqHistory=function(){_dataReceived.id=3;self.postMessage(_dataReceived)};wsRdp.onresolutionchange=function(a,c){self.postMessage({type:1,event:5,w:a,h:c})};wsRdp.onLockKeyState=function(a){self.postMessage({type:1,event:10,state:a})};wsRdp.onMoveCursor=function(a,
c){_cursorMov.x=a;_cursorMov.y=c;self.postMessage(_cursorMov)};wsRdp.onCloseSurface=function(a,c){self.postMessage({type:1,event:6})};wsRdp.onColorChange=function(a){self.postMessage({type:1,event:9,color:a})};wsRdp.onAltSecWindows=function(a,c){_altSecData.data=a.getBytes(c);_altSecData.size=c;self.postMessage(_altSecData,[_altSecData.data.buffer])};wsRdp.onmessage=function(a){_msgData.data=a.data;"string"!=typeof _msgData.data?self.postMessage(_msgData,[_msgData.data]):self.postMessage(_msgData)};
wsRdp.run()}function setResolution(a){wsRdp&&wsRdp.setResolution(a.w,a.h)}function setBpp(a){wsRdp&&wsRdp.setColor(a)}function restoreVar(){wsRdp&&wsRdp.resetStatus()}
function DisplayBufferWrapper(){var a={type:2,x:0,y:0,w:0,h:0,pixel:null,offset:0,scansize:0},e={type:3,srcx:0,srcy:0,cx:0,cy:0,dx:0,dy:0},f={type:5,l:0,t:0,w:0,h:0,color:0},k={type:6,x1:0,y1:0,x2:0,y2:0,color:0},c={type:7,opcode:0,dstwidth:0,x:0,y:0,cx:0,cy:0,src:0,srcwidth:0,srcx:0,srcy:0},b={type:12,font:0,flags:0,mixmode:0,foregroundColor:0,backgroundColor:0,clipLeft:0,clipTop:0,clipcx:0,clipcy:0,boxLeft:0,boxTop:0,boxcx:0,boxcy:0,x:0,y:0,length:0,text:null,_left:0,_top:0,_right:0,_bottom:0},
g={type:13,cacheID:0,cacheIDX:0,x:0,y:0,cx:0,cy:0,srcx:0,srcy:0,opcode:0},d={type:14,x:0,y:0,cx:0,cy:0,offset:0},p={type:16,font:0,character:0,glyph:null},h={type:17,idx:0,cursor:null},l={type:20,order:0,data:null,off:0},n={type:21,id:0,idx:0,bitmap:null};this.setRGBs=function(r,m,q,b,c,d,e){a.x=r;a.y=m;a.w=q;a.h=b;a.pixel=c;a.offset=d;a.scansize=e;self.postMessage(a,[c.buffer])};this.moveArea=function(a,m,q,b,c,d){e.srcx=a;e.srcy=m;e.cx=q;e.cy=b;e.dx=c;e.dy=d;self.postMessage(e)};this.fillRect=function(a,
m,q,b,c){f.l=a;f.t=m;f.w=q;f.h=b;f.color=c;self.postMessage(f)};this.drawLine=function(a,m,b,c,d){k.x1=a;k.y1=m;k.x2=b;k.y2=c;k.color=d;self.postMessage(k)};this.bitBlt=function(a,m,b,d,e,g,f,h,k,l){c.opcode=a;c.dstwidth=m;c.x=b;c.y=d;c.cx=e;c.cy=g;c.src=f;c.srcwidth=h;c.srcx=k;c.srcy=l;self.postMessage(c)};this.drawLineExt=function(a,b,c,d,e,g){};this.drawText=function(a,m,c,d,e,g,f,h,k,l,n,p,t,u,v,w,x,y,z,A,B){b.font=a;b.flags=m;b.mixmode=c;b.foregroundColor=d;b.backgroundColor=e;b.clipLeft=g;b.clipTop=
f;b.clipcx=h;b.clipcy=k;b.boxLeft=l;b.boxTop=n;b.boxcx=p;b.boxcy=t;b.x=u;b.y=v;b.length=w;b.text=x;b._left=y;b._top=z;b._right=A;b._bottom=B;self.postMessage(b)};this.drawBitmap=function(a,b,c,d,e,f,h,k,l){g.cacheID=a;g.cacheIDX=b;g.x=c;g.y=d;g.cx=e;g.cy=f;g.srcx=h;g.srcy=k;g.opcode=l;self.postMessage(g)};this.saveDesktop=function(a,b,c,e,f){d.type=14;d.x=a;d.y=b;d.cx=c;d.cy=e;d.offset=f;self.postMessage(d)};this.restoreDesktop=function(a,b,c,e,f){d.type=15;d.x=a;d.y=b;d.cx=c;d.cy=e;d.offset=f;self.postMessage(d)};
this.putFont=function(a,b,c){p.font=a;p.character=b;p.glyph=c;self.postMessage(p,[c.fontData.buffer])};this.putCursor=function(a,b){h.type=17;h.idx=a;h.cursor=b;b.rawData?self.postMessage(h,[b.rawData.buffer]):self.postMessage(h)};this.setCursor=function(a){h.type=18;h.idx=a;h.cursor=null;self.postMessage(h)};this.getHistory=function(a,b){historyCallback=b;self.postMessage({type:19})};this.setHistory=function(a,b){l.order=a;l.data=b.getData();l.off=b.getPosition();self.postMessage(l,[l.data.buffer])};
this.putBitmap=function(a,b,c){n.id=a;n.idx=b;n.bitmap=c;c.raw?self.postMessage(n,[c.data.buffer,c.raw.buffer]):self.postMessage(n,[c.data.buffer])}};
