var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(k,t,p){if(null==k)throw new TypeError("The 'this' value for String.prototype."+p+" must not be null or undefined");if(t instanceof RegExp)throw new TypeError("First argument to String.prototype."+p+" must not be a regular expression");return k+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(k,t,p){if(k==Array.prototype||k==Object.prototype)return k;k[t]=p.value;return k};
$jscomp.getGlobal=function(k){k=["object"==typeof globalThis&&globalThis,k,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var t=0;t<k.length;++t){var p=k[t];if(p&&p.Math==Math)return p}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(k,t){var p=$jscomp.propertyToPolyfillSymbol[t];if(null==p)return k[t];p=k[p];return void 0!==p?p:k[t]};$jscomp.polyfill=function(k,t,p,x){t&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(k,t,p,x):$jscomp.polyfillUnisolated(k,t,p,x))};
$jscomp.polyfillUnisolated=function(k,t,p,x){p=$jscomp.global;k=k.split(".");for(x=0;x<k.length-1;x++){var y=k[x];if(!(y in p))return;p=p[y]}k=k[k.length-1];x=p[k];t=t(x);t!=x&&null!=t&&$jscomp.defineProperty(p,k,{configurable:!0,writable:!0,value:t})};
$jscomp.polyfillIsolated=function(k,t,p,x){var y=k.split(".");k=1===y.length;x=y[0];x=!k&&x in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var ca=0;ca<y.length-1;ca++){var X=y[ca];if(!(X in x))return;x=x[X]}y=y[y.length-1];p=$jscomp.IS_SYMBOL_NATIVE&&"es6"===p?x[y]:null;t=t(p);null!=t&&(k?$jscomp.defineProperty($jscomp.polyfills,y,{configurable:!0,writable:!0,value:t}):t!==p&&($jscomp.propertyToPolyfillSymbol[y]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(y):$jscomp.POLYFILL_PREFIX+
y,y=$jscomp.propertyToPolyfillSymbol[y],$jscomp.defineProperty(x,y,{configurable:!0,writable:!0,value:t})))};$jscomp.polyfill("String.prototype.startsWith",function(k){return k?k:function(t,p){var x=$jscomp.checkStringArgs(this,t,"startsWith");t+="";var y=x.length,ca=t.length;p=Math.max(0,Math.min(p|0,x.length));for(var X=0;X<ca&&p<y;)if(x[p++]!=t[X++])return!1;return X>=ca}},"es6","es3");
$jscomp.polyfill("String.fromCodePoint",function(k){return k?k:function(t){for(var p="",x=0;x<arguments.length;x++){var y=Number(arguments[x]);if(0>y||1114111<y||y!==Math.floor(y))throw new RangeError("invalid_code_point "+y);65535>=y?p+=String.fromCharCode(y):(y-=65536,p+=String.fromCharCode(y>>>10&1023|55296),p+=String.fromCharCode(y&1023|56320))}return p}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(k){return k?k:function(t,p,x){var y=this.length||0;0>p&&(p=Math.max(0,y+p));if(null==x||x>y)x=y;x=Number(x);0>x&&(x=Math.max(0,y+x));for(p=Number(p||0);p<x;p++)this[p]=t;return this}},"es6","es3");$jscomp.typedArrayFill=function(k){return k?k:Array.prototype.fill};$jscomp.polyfill("Int8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Uint8ClampedArray.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Float32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Float64Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("String.prototype.trimRight",function(k){function t(){return this.replace(/[\s\xa0]+$/,"")}return k||t},"es_2019","es3");$jscomp.polyfill("String.prototype.trimEnd",function(k){return k||String.prototype.trimRight},"es_2019","es3");var svManager={getInstance:function(){var k=window.$ssh;return k&&k.running&&k.running()?k:null}};
function connvertServer(k){var t={};t.id=k.id;t.server=k.id;t.displayName=k.displayName||k.id;if(k=k.ssh){for(var p in k)t[p]=k[p];t.user=k.username||"";t.pwd=k.password||""}return t}
svGlobal.SSH=function(k,t,p,x){function y(a){return"on"==a||"true"==a||1==a}function ca(a){h.loadbalanceToken||(B.randomAppId&&(a=hi5.tool.uuid()),h.loadbalanceToken=B.loadbalanceTokenName?B.loadbalanceTokenName+"="+a:"")}function X(){var a=k.indexOf("://"),b=k.substring(a+3);a=b.indexOf("/");0<a&&(b=b.substring(0,a));return location.protocol+"//"+b}function zb(a){if(!Da)return"";var b=X(),d=Ea.clipboard,c=d.indexOf("://");b=(0<c&&11>c?d:b+d)+"s="+Da+"&t="+Date.now()+"&type="+a;return hi5.browser.httpGet(h.modifyURL(b),
!1)}function Pa(a,b){b&&(Y=b);a&&(a>K&&(a=K),S=a,ua=(S-1)*q);Za=1==Y&&S==K}function va(a,b,d,c){var e=b;c=c||Math.floor(e/q);b=d||Math.floor(a/w);var m=null;d&&(a=M*w,e=K*q);F&&(m=r.getImageData(0,0,Math.min(b*w,N),Math.min(c*q,K*q)));t=a;p=e;d=t;a=p;C.setSize(d,a);Z.width=d;Z.height=a;r.textBaseline="top";r.font=n.fontSize+"px "+(n.fontFamily||n.fontName);Fa();m&&r.putImageData(m,0,0);K=c;M=b;N=M*w;Pa(Math.floor(p/q));E?E.resize(M,K):E=new $a(M,K);if(h.onresolutionchange)h.onresolutionchange(t,p)}
function Qa(a){A.send(a)}function Ga(){return n.displayName||n.server||n.symlink||n.id||"undefined"}function ab(a){h.setTitle&&(document.title=a)}function bb(a,b,d){this.need=a;this.handler=b;this.repeat=d||1}function Ab(a){aa=new RecordingManager;aa.setHeader({name:"rec",width:a.width,height:a.height,color:a.fontSize,namesuffix:".sshv",filetag:"SSHV",duration:0})}function Bb(a,b){var d=0,c=!1;this.width=a;this.interval=b;var e=0;this.start=function(){c||(c=!0,d=setInterval(function(){if(C&&F){var m=
C.getThumbnail(a);m&&m.length!=e&&(A.send("8E7"+m),e=m.length)}},b))};this.stop=function(){clearInterval(d)}}function Cb(a,b){!V||V.width==a&&V.interval==b||(V.stop(),V=null);V||(V=new Bb(a,b));V.start()}function Db(a){F&&A.send("5D"+a.join("\t"));G=null}function cb(){if(G){var a=G.answer.length;a<G.prompt.length?(da(G.prompt[a]),pa()):(A.send("5D"+G.answer.join("\t")),G=null)}}function Eb(a){F&&A.send("5B"+a)}function Fb(a){var b=parseInt(a.substring(0,1),16),d=a.substring(1);a=!1;var c=h.sessionInfo.appInfo;
switch(b){case 1:var e=JSON.parse(d);h.onsessionjoin&&(a=h.onsessionjoin(e));if(a)break;h.showMessage(__svi18n.info.joinsession.applyArgs([e.numericId,e.__ip,e.name]));break;case 2:e=JSON.parse(d);h.onsessionexit&&(a=h.onsessionexit(e));if(a)break;h.showMessage(__svi18n.info.exitsession.applyArgs([e.numericId,e.__ip,e.name]));break;case 3:e=JSON.parse(d);c.joinMode!=e.mode&&(c.joinMode=e.mode,b=hi5.$("joinSelect"))&&(b.value=e.mode);if(c.hasControl)break;C.setReadOnly(!1);if(b=hi5.$("requestControl"))b.disabled=
!0;h.ongivecontrol&&(a=h.ongivecontrol());if(a)break;h.showMessage(__svi18n.info.givecontrol);break;case 4:C.setReadOnly(!0);c.hasControl=!1;if(b=hi5.$("requestControl"))b.disabled=!1;h.ontakebackcontrol&&(a=h.ontakebackcontrol());if(a)break;h.showMessage(__svi18n.info.nocontrol);break;case 5:e=JSON.parse(d);h.onrequirecontrol&&(a=h.onrequirecontrol(e));if(a)break;a=__svi18n.info.title.applyArgs([e.name,e.numericId,e.__ip]);h.showMessage({title:a,msg:__svi18n.info.recontrol,cbYes:function(){h.giveControl(e.numericId);
this.destroy()},cbNo:function(){h.refuseControl(e.numericId);this.destroy()}});break;case 6:C.setTouchRemoting(!0);break;case 7:e=JSON.parse(d);e.width&&e.height&&va(0,0,e.cols,e.rows);break;case 8:e=JSON.parse(d);if(h.onrequestcredential&&h.onrequestcredential(e))break;C.requestCredential(e);break;case 9:e=JSON.parse(d);0<e.interval&&0<e.width?Cb(e.width,e.interval):V&&(V.stop(),V=null);break;case 11:e=JSON.parse(d);h.onrequirejoin&&(a=h.onrequirejoin(e));if(a)break;a=__svi18n.info.title.applyArgs([e.name,
e.numericId,e.__ip]);h.showMessage({title:a,msg:__svi18n.info.reqjoin,cbYes:function(){h.allowJoin(e.numericId,!0);this.destroy()},cbNo:function(){h.allowJoin(e.numericId,!1);this.destroy()}});break;case 12:db=!0}}function Gb(a){var b=B.page&&B.page.join||"";if(b.startsWith("http://")||b.startsWith("https://"))return b;if(b.startsWith("/"))return location.origin+b;var d=location.href,c=d.lastIndexOf("/");if(b)return d.substring(0,c+1)+b;b=X();d.toLowerCase().startsWith(b.toLowerCase())&&(b=d.substring(0,
c));return b+"/"+a}function qa(a){ja.style.display=a?"none":"block"}function Hb(a){svGlobal.logger.info("opened...");F=!0;A.send("87"+navigator.userAgent);if(h.onopen)h.onopen()}function Ib(a){svGlobal.logger.warn(a)}function Ha(a){svGlobal.logger.warn("closed ...");qa(!0);if(!F&&((a=__svi18n.errorCode.connection)||(a="error connection"),h)){if(h.onerror)h.onerror({name:"connection",message:a});h.showMessage(a);0<svGlobal.log&&console.error(a)}wa=F=!1;if(h)if(h.onclose)h.onclose(db);else if(hi5.appcfg&&
hi5.appcfg.returnUrl){window.location.href=hi5.appcfg.returnUrl;return}try{null!=aa&&(aa.exit(),aa=null),C&&C.close()}catch(b){}na&&(na.release(),na=null);Z=r=null;A&&(A.onopen=null,A.onmessage=null,A.onclose=null,A=A.onerror=null);C=Q=null;h&&(h=null);window&&window.$ssh&&(window.$ssh=null);null!=aa&&(aa.exit(),aa=null)}function eb(){10>n.fontSize&&(n.fontSize=10);13>n.fontSize?q=n.fontSize+6:12<n.fontSize&&19>n.fontSize?q=n.fontSize+8:18<n.fontSize&&25>n.fontSize?q=n.fontSize+12:24<n.fontSize&&
(q=n.fontSize+16);n.lineHeight&&(q=parseInt(n.lineHeight));fb=(q-n.fontSize)/2|0;r.textBaseline="top";r.font=n.fontSize+"px "+n.fontFamily;w=r.measureText("X").width;K=parseInt(p/q);M=parseInt(t/w);N=M*w;Pa(parseInt(p/q));E?E.resize(M,K):E=new $a(M,K)}function Ra(){Fa();z=v=0;eb();ja.style.width=w+"px";ja.style.height=q+"px";wa=!0}function gb(){xa=!1;H=n.fgColor||ba[7];L=n.bgColor||ba[0];Sa=0;ra=!0}function hb(a){switch(a){case 0:svGlobal.logger.info("C0 0");break;case 5:svGlobal.logger.info("C0 END enquiry");
break;case 7:svGlobal.logger.info("C0 bell");break;case 8:Ta();break;case 9:v=8*((v/w/8|0)+1)*w;ya();break;case 10:Ua(!0);break;case 11:Ua();break;case 12:svGlobal.logger.info("C0 form feed");break;case 13:ib();break;case 14:svGlobal.logger.info("C0 Shift out");break;case 15:svGlobal.logger.info("C0 exit_alt_charset_mode");break;default:svGlobal.logger.warn("Unknown C0 control:"+a)}}function Jb(a){var b=a.getPosition();if(!O.parse(a))return a.setPosition(b-2),!1;a=O.count;b=O.parameters;switch(O.command){case 64:0==
a&&(b[0]=1);a=b[0];b="";for(var d=a*w,c=r.getImageData(v,z,N-v-d,q),e=0;e<a;e++)b+=" ";da(b);v-=d;r.putImageData(c,v+d,z);E.insertSpace(a,R(),P());break;case 65:0==a&&(b[0]=1);z-=(b[0]||1)*q;break;case 66:0==a&&(b[0]=1);z+=(b[0]||1)*q;ya(!0);break;case 67:0==a&&(b[0]=1);a=b[0]||1;a>M&&(a=M);v+=a*w;break;case 68:0==a&&(b[0]=1);v-=(b[0]||1)*w;0>v&&(v=0);break;case 69:0==a&&(b[0]=1);z+=b[0]*q;v=0;break;case 70:0==a&&(b[0]=1);z-=b[0]*q;v=0;break;case 71:0==a&&(b[0]=1);Ia(0,b[0]);break;case 72:case 102:0==
a&&(b[0]=b[1]=1);Ia(b[0]||1,b[1]||1);break;case 74:a||(b[0]=0);switch(b[0]){case 0:r.fillStyle=L;r.fillRect(v,z,N-v,K*q-z);r.fillStyle=H;E.clearEOS(R(),P());break;case 1:r.fillStyle=L;r.fillRect(0,0,v,z);r.fillStyle=H;E.clearBOS(R(),P());break;case 2:Fa();z=v=0;E.cleanScreen();break;case 3:Fa();z=v=0;E.cleanScreen();break;default:svGlobal.logger.warn("invalid CSI J:"+b[0])}break;case 75:a||(b[0]=0);switch(b[0]){case 0:jb();break;case 1:r.fillStyle=L;r.fillRect(0,z,v,q);r.fillStyle=H;E.clearBOL(R(),
P());break;case 2:r.fillStyle=L;r.fillRect(0,z,N,q);r.fillStyle=H;E.clearLine(P());break;default:svGlobal.logger.warn("invalid CSI K:"+b[0])}break;case 76:case 84:a||(b[0]=1);kb(b[0],76==O.command);break;case 77:case 83:a||(b[0]=1);lb(b[0],77==O.command);break;case 80:a||(b[0]=1);a=b[0];b=v+a*w;b=r.getImageData(b,z,N-b,q);jb();r.putImageData(b,v,z);E.deleteChars(R(),P(),a);break;case 88:a||(b[0]=1);a=b[0];r.fillStyle=L;r.fillRect(v,z,a*w,q);r.fillStyle=H;E.eraseChars(R(),P(),a);break;case 90:a||(b[0]=
1);v=8*((v/w/8|0)-b[0]+1)*w;ya();break;case 99:I("x1B[?6c");break;case 100:a||(b[0]=1);Ia(b[0]);break;case 101:a||(b[0]=1);Ia(P()+b[0]);break;case 104:if(63==O.mode)switch(b[0]){case 1:oa.setCursorKeyMode(1);break;case 5:svGlobal.logger.info("Reversal screen mode");break;case 6:svGlobal.logger.info("Relative origion mode");break;case 7:svGlobal.logger.info("wraparound mode on");ra=!0;break;case 12:break;case 25:qa(!1);break;case 45:svGlobal.logger.info("reverse-wraparound mode on");break;case 1E3:case 1001:case 1002:case 1003:case 1005:case 1006:U=
b[0];svGlobal.logger.warn("mouse tracking on:"+U);break;case 1034:svGlobal.logger.warn("TD:Interpret meta key, xterm.");break;case 1048:case 1049:svGlobal.logger.warn("TD: Save cursor");break;default:svGlobal.logger.warn("TD: CSI ? Pm h, Ps:"+b[0])}break;case 108:if(63==O.mode)switch(b[0]){case 1:oa.setCursorKeyMode(0);break;case 2:za.setKeyboard("vt52");break;case 3:svGlobal.logger.info("80 Column Mode (DECCOLM), VT100");break;case 5:svGlobal.logger.info("screen mode: "+O.toString());break;case 6:svGlobal.logger.info("Absolute origion mode: "+
O.toString());break;case 7:ra=!1;break;case 12:break;case 25:qa(!0);break;case 45:svGlobal.logger.info("reverse-wraparound mode off");break;case 47:svGlobal.logger.info("TODO: use Normal Screen Buffer, xterm.");break;case 1E3:case 1001:case 1002:case 1003:case 1005:case 1006:U=0;break;case 1048:case 1049:svGlobal.logger.warn("TD: Restore cursor");break;default:svGlobal.logger.warn("TD: CSI ? Pm l, Ps:"+b[0])}break;case 109:0==a&&(a=1,b[0]=0);for(d=0;d<a;d++)switch(b[d]){case 0:Aa(7);Ba(0);Va(!1);
break;case 1:Va(!0);break;case 2:break;case 4:break;case 5:case 8:break;case 7:Aa(0);Ba(7);break;case 27:Aa(7);Ba(0);break;case 30:case 31:case 32:case 33:case 34:case 35:case 36:case 37:Aa(b[d]-30);break;case 38:return 2==b[d+1]&&(H="rgb("+b[d+2]+","+b[d+3]+","+b[d+4]+")",r.fillStyle=H),!0;case 39:Aa(7);break;case 40:case 41:case 42:case 43:case 44:case 45:case 46:case 47:Ba(b[d]-40);break;case 48:return 2==b[d+1]&&(L="rgb("+b[d+2]+","+b[d+3]+","+b[d+4]+")"),!0;case 49:Ba(0);1==d&&39==b[0]&&Va(!1);
break;default:return svGlobal.logger.warn("TD: SGR="+O.toString()),!0}break;case 110:6==b[0]?63==O.mode?I("\u001b[?"+P()+";"+R()+"R"):I("\u001b["+P()+";"+R()+"R"):5==b[0]&&I("\u001b[0n");break;case 112:"!"==O.trailing&&gb();break;case 114:O.mode||Pa(b[1],b[0]);break;case 124:break;default:svGlobal.logger.warn("TD: CSI="+O.toString())}return!0}function kb(a,b){a||(a=1);b=b?z/q+1|0:Y;var d=(b-1)*q;if(S!=b){var c=r.getImageData(0,d,N,(S-b-a+1)*q);r.fillStyle=L;r.fillRect(0,d,N,q*a);r.putImageData(c,
0,(b+a-1)*q);r.fillStyle=H;E.scrollUp(a,b,S)}}function lb(a,b){a||(a=1);b=b?z/q+1|0:Y;var d=(b-1)*q,c=S*q,e=a*q,m=d+e;c!=m&&(m=r.getImageData(0,m,N,c-m),r.fillStyle=L,r.fillRect(0,c-e,N,e),r.fillStyle=H,r.putImageData(m,0,d),E.scrollDown(a,b,S))}function Ua(a){a&&E.cariageReturn(R(),P());z+=q;ya(a)}function ya(a){ra&&v>=N&&(v=0,z+=q);(ra||a)&&z>ua&&(z>ua&&(z=ua),Za?(r.drawImage(Z,0,-q),r.fillStyle=L,r.fillRect(0,ua,t,q),E.appendLines(1)):(a=r.getImageData(0,(Y-0)*q,N,(S-Y)*q),r.fillStyle=L,r.fillRect(0,
(Y-1)*q,N,(S-Y+1)*q),r.putImageData(a,0,(Y-1)*q),E.scrollDown(1,Y,S)),r.fillStyle=H)}function Ta(){v-=w;0>v&&(v=0)}function P(){return(z/q|0)+1}function R(){return(v/w|0)+1}function Ia(a,b){b&&(v=(b-1)*w,0>v&&(v=0));a&&(a>K&&(a=K),z=(a-1)*q)}function Ba(a){L=Ja[a];L||(L=n.bgColor||"black",svGlobal.logger.info("xx colorIndex:"+a))}function Aa(a){Sa=a;H=ba[a];H||(H=n.fgColor||"white",svGlobal.logger.info("xx colorIndex:"+a));r.fillStyle=H}function Va(a){ba=a?mb:Ja;H=ba[Sa]}function jb(){r.fillStyle=
L;r.fillRect(v,z,N-v,q);r.fillStyle=H;E.clearEOL(R(),P())}function Fa(){r.fillStyle=L;r.fillRect(0,0,Z.width,Z.height);r.fillStyle=H}function pa(){ja.style.top=z+"px";ja.style.left=v+"px";var a=E.getChar((v/w|0)+1,(z/q|0)+1);a&&r.measureText(a).width>w?ja.style.width=2*w+"px":ja.style.width=w+"px"}function da(a){if(a){T.on&&(a.startsWith(T.prompt)?(T.on=!1,setTimeout(T.process,30)):T.text+=a);var b=M-(v/w|0);for(var d=a.length,c=0;c<d;){var e=a.charAt(c++);r.measureText(e).width>w?b-=2:b--;if(0==
b)break;else if(0>b){c--;break}}b=c+1>d?-1:c;0<=b?(nb(a.substring(0,b),b),ya(),da(a.substring(b))):nb(a,a.length)}}function nb(a,b){if(a){E.writeText(R(),P(),a);for(var d=0,c=[],e=0;e<b;e++){var m=a.charAt(e),f=r.measureText(m).width;c.push(f);d+=f<=w?w:2*w}r.fillStyle=L;r.fillRect(v,z,Math.ceil(d),q);r.fillStyle=H;d=z+fb;for(e=0;e<b;e++)m=a.charAt(e),f=c[e],f==w?(r.fillText(m,v,d),v+=w):f>w?(f=(2*w-f)/2|0,r.fillText(m,v+f,d),v+=2*w):(f=(w-f)/2|0,r.fillText(m,v+f,d),v+=w)}}function ob(a){ea+=a;ka?
(da(a),pa()):G&&G.echo[G.answer.length]&&(da(a),pa())}function ib(){v=0;z>(S-1)*q&&(z=(S-1)*q)}function pb(a){if(F&&Ca)return(a=a.getData("text/plain"))?(a=a.replace(/\r\n/g,"\n"),ka||G?ob(a):I(a),!0):!1}function Wa(){if(W){var a=!!W.value;W.value=E.toString();a||(a=new hi5.ui.Lightbox(W.parentNode),a.show(),C&&C.setIgnorePaste(!1),a.onclose=function(){W.value="";C&&C.focus()});setTimeout(function(){W.scrollTop=W.scrollHeight},10)}}function qb(a){y(n.mapDisk)&&(J||(J=new hi5.file.UploadManager(new hi5.file.WsFileService(Qa),
!1),J.enabled=!0,J.canCopyFile=!1,J.addEvent("beforeupload",function(b,d,c){h.beforeupload&&h.beforeupload(b,d,c)}),J.addEvent("fileuploaded",function(b,d,c){if(h.onfileuploaded)h.onfileuploaded(b,d,c)}),J.addEvent("uploaded",function(b,d){if(h.onuploaded)h.onuploaded(b,d)}),J.addEvent("uploadingCancelled",function(){if(h.onuploadingCancelled)h.onuploadingCancelled()})),a.setFileHandler(J))}function rb(a,b,d){return a.querySelector(b+'[name="'+d+'"]')||document.getElementById(d)}function I(a){if(a){a=
Ka.encode(a);var b=a.length+1,d=new Uint8Array(b);d[0]=147;for(var c=1;c<b;c++)d[c]=a[c-1];A.send(d.buffer)}}function Kb(a,b){a&&"text/plain"==b?pb(a):h.showMessage("Please use Ctrl+V or browser's Edit menu")}function $a(a,b){function d(f,g){if(g)for(var l=r.measureText("W").width,u=0;u<f;u++){var D=g[u];D&&7923<D.charCodeAt(0)&&r.measureText(D).width>l&&f--}return f}var c=0,e=[],m=10*b;this.resize=function(f,g,l){l=0;for(var u=e.length;l<u;l++)if(e[l]&&(e[l].length=f,f>a))for(var D=a;D<f;D++)e[l][D]=
" ";a=f;b=g;m=10*b};this.writeText=function(f,g,l){g--;f--;var u=e[c+g];u||(u=[],e[c+g]=u);g=0;for(var D=l.length;g<D;g++)u[g+f]=l[g]};this.cariageReturn=function(f,g){g--;if(g=e[c+g])f=g.length,g[f]="\r",g[f+1]="\n"};this.appendLines=function(f){c+=f};this.scrollDown=function(f,g,l){l=c+l-1-f;for(g=c+g-1;g<=l;g++)e[g]=e[g+f];l++;for(g=0;g<f;g++)e[l+g]=[]};this.scrollUp=function(f,g,l){g=c+g-1+f;for(l=c+l-1;l>=g;l--)e[l]=e[l-f];g--;for(l=0;l<f;l++)e[g-l]=[]};this.cleanScreen=function(){c=e.length;
if(c>=m){var f=2*b;e.splice(0,f);c-=f}};this.clearEOS=function(f,g){g--;f--;for(var l=c+g,u,D=0,fa=b-g;D<fa;D++)if(u=e[l+D])for(g=f;g<a;g++)u[g]=" "};this.clearBOS=function(f,g){g--;f--;for(var l=c,u,D,fa=0;fa<g;fa++)if(D=e[l+fa])for(f=d(f,dataRow),u=0;u<f;u++)D[u]=" "};this.clearLine=function(f){f--;(f=e[c+f])&&hi5.Arrays.fill(f,0,a," ")};this.clearBOL=function(f,g){g--;f--;if(g=e[c+g]){f=d(f,g);for(var l=0;l<f;l++)g[l]=" "}};this.clearEOL=function(f,g){g--;f--;if(g=e[c+g])for(f=d(f,g);f<a;f++)g[f]=
" "};this.eraseChars=function(f,g,l){g--;f--;if(g=e[c+g]){var u=f=d(f,g);for(f+=l;u<f;u++)g[u]=" "}};this.deleteChars=function(f,g,l){g--;f--;if(g=e[c+g])f=d(f,g),g.splice(f,l)};this.getChar=function(f,g){g--;f--;return(g=e[c+g])?g[d(f,g)]:null};this.insertSpace=function(f,g,l){l--;g--;if(l=e[c+l]){g=d(g,l);for(var u=l.length-1;u>=g;u--)l[u+f]=l[u];for(u=0;u<f;u++)l[g+u]=" "}};this.getSingleLine=function(f,g,l){f--;g--;var u="";if(f=e[c+f])for(g=d(g,f),l=null==l||l>=f.length?f.length:d(l-1,f);g<l;g++)u+=
f[g];return u};this.getMultiLines=function(f,g,l,u){if(u<g)return this.getMultiLines(l,u,f,g);var D=u-g+1;if(1>D)return null;if(1==D)return this.getSingleLine(g,f,l);f=this.getSingleLine(g,f,null);l=this.getSingleLine(u,1,l);D-=2;g+=c;for(var fa=0;fa<D;fa++)f=(u=e[fa+g])?f+u.join(""):f+"\r\n";return f+l};this.toString=function(){for(var f="",g=0,l=e.length;g<l;g++)e[g]&&(f+=e[g].join("").trimEnd()),f+="\r\n";return f}}var ha=0,ia=null,db=!1,xa=!1;this.displayMsg=!0;this.reconnectTimes=0;this.setTitle=
this.openLink=!0;this.mode=0;this.reconnectOnResize=!0;var h=this,sb=new hi5.codec["utf-8"].Decoder,Ka=new hi5.codec["utf-8"].Encoder,Lb={stream:!0};this.setCodec=function(a,b){sb="string"==typeof a?"utf-8"==a?new hi5.codec["utf-8"].Decoder:new TextDecoder(a):a;if(b)if("string"==typeof b)if(a=hi5.codec[b])Ka=new a.Encoder;else return Ka=new hi5.codec["utf-8"].Encoder,svGlobal.logger.warn("Unsupported encode: "+b),!1;else Ka=b;return!0};this.getHistory=function(){return E.toString()};hi5.appcfg||(hi5.appcfg=
{img:{},toolbar:{fadable:!0},displayMsg:!0});var B=hi5.appcfg,T={on:!1,text:"",prompt:"",cmd:"",process:function(){var a=T.cmd.indexOf(" "),b=T.cmd.substring(a+1);a=b.lastIndexOf(".");var d="";if(-1!=a)switch(b.substring(a+1).toLowerCase()){case "jpe":case "jpg":case "jpeg":d="image/jpeg";break;case "gif":d="image/gif";break;case "bmp":d="image/bmp";break;case "svg":d="image/svg+xml";break;case "png":d="image/png";break;case "webp":d="image/webp";break;case "ico":d="image/x-icon"}a="data:"+(d||"application/octet-stream")+
";base64,"+T.text;T.text="";h.showMessage(d?{msg:'<img src="'+a+'" style="max-width:100%"/>',html:!0}:{msg:'<a download="'+b+'" href="'+a+'" target="_blank">'+b+"</a>",html:!0})}};void 0!=B.reconnectOnResize&&(this.reconnectOnResize=B.reconnectOnResize);var Xa="object"==typeof k?k:null,tb="object"==typeof k||0<k.indexOf("/PLAY?");tb?(this.mode=1,Xa&&(k=""),k+="&touchpad=on"):0<k.indexOf("/JOIN?")&&(this.mode=2,this.reconnectOnResize=!1);var n=hi5.tool.queryToObj(k.substring(k.indexOf("?")+1));void 0==
n.mapClipboard&&B.clipboard&&void 0!=B.clipboard.enabled&&(n.mapClipboard=B.clipboard.enabled);n.keyfile&&n.keyfile.startsWith("-----BEGIN")&&(B.wsPost=!0);n.color||(n.color=32);n.fontFamily||(n.fontFamily='"Courier New"');var Mb=n.terminalType||"default",Ca=y(n.mapClipboard),W=null,E=null,Ea={download:"/DOWNLOAD?",clipboard:"/CLIP?"};this.setLinks=function(a){a.download&&(Ea.download=a.download);a.clipboard&&(Ea.clipboard=a.clipboard)};this.server=n.server;this.port=parseInt(n.port,10);this.sessionInfo=
{major:0,minor:0,width:0,height:0,bpp:0,bigEndian:!0,trueColor:!0};var C=null,F=!1,wa=!1,Ya=0,Da="",U=0,J=null;B.copyDialog=!0;var v=0,z=0,ub=0,vb=0,w=0,q=18,fb=0,Ja="#000 #cd0000 #00cd00 #cdcd00 #0000ee #cd00cd #00cdcd #e5e5e5".split(" "),mb="#7f7f7f #ff0000 #00ff00 #ffff00 #5c5cff #ff00ff #00ffff #ffffff".split(" "),Nb="#073642 #dc322f #859900 #b58900 #268bd2 #d33682 #2aa198 #eee8d5".split(" "),Ob="#002b36 #cb4b16 #586e75 #657b83 #839496 #6c71c4 #93a1a1 #fdf6e3".split(" "),Pb="#000 #cd0000 #00cd00 #cdcd00 #0000ee #cd00cd #00cdcd #e5e5e5".split(" "),
Qb="#7f7f7f #ff0000 #00ff00 #ffff00 #5c5cff #ff00ff #00ffff #ffffff".split(" "),ba=Ja,H=n.fgColor||ba[7],L=n.bgColor||ba[0],Sa=0,ra=!0;n.wraparoundMode&&(ra=y(n.wraparoundMode));var Y=1,S=24,ua=0,Za=!0,ja=null,K=0,M=0,N=0,aa=null;window.$ssh=this;var na=new function(a){var b=0,d=0,c=new Uint8Array(a),e=this,m=new bb(0,null,0);this.needMore=!1;this.release=function(){e=c=m=null};this.getHandler=function(){return m};this.getData=function(){return c};this.getPosition=function(){return b};this.setPosition=
function(f){b=f};this.getEnd=function(){return d};this.has=function(f){return d-b>=f};this.set=function(f){var g=f.length,l=d-b;if(1>l)d=g,c=f;else{var u=c.subarray(b,d);d=l+g;g=new Uint8Array(d);g.set(u);g.set(f,l);c=g}b=0};this.handle=function(){m.handler(e,m)};this.setHandler=function(f){f&&1>f.need&&svGlobal.logger.warn("need < 1");(m=f)&&d-b>=f.need&&f.handler(e,f)};this.getByte=function(){return c[b++]};this.peekByte=function(){return c[b]};this.getBE32=function(){return c[b++]<<24|c[b++]<<
16|c[b++]<<8|c[b++]};this.getBE16=function(){return c[b++]<<8|c[b++]};this.skip=function(f){b+=f};this.skipBack=function(f){b-=f};this.getBytes=function(f,g){if(g)for(var l=0;l<f;l++)g[l]=c[b++];else return g=b,b+=f,c.subarray(g,b)};this.copyToByteArray=function(f,g,l,u){hi5.Arrays.arraycopy(c,l,f,g,u)}}(4194304),Rb={l:"\u250c",k:"\u2510",m:"\u2514",j:"\u2518",q:"\u2500",x:"\u2502",n:"\u253c","~":"\u2022",u:"\u2524",t:"\u251c",v:"\u2534",w:"\u252c"};this.__que=na;this.running=function(){return F};
this.setTheme=function(a){"light"==a?(this.setColorTable(Nb),this.setColorTableBright(Ob)):"classic"==a?(this.setColorTable(Pb),this.setColorTableBright(Qb)):svGlobal.logger.warn("Invalid theme: "+a)};this.setColorTable=function(a){ba=Ja=a;H=n.fgColor||ba[7];L=n.bgColor||ba[0]};this.setColorTableBright=function(a){mb=a};this.loadbalanceToken="";if(B.ssh){var La=B.ssh;La.theme&&!n.theme&&(n.theme=La.theme);La.charset&&!n.charset&&(n.charset=La.charset)}n.theme&&this.setTheme(n.theme);n.charset&&this.setCodec(n.charset);
B.loadbalanceTokenName&&n[B.loadbalanceTokenName]&&ca(n[B.loadbalanceTokenName]);this.mapCmdToCtrl=!0;var A=null;t||(t=window.innerWidth);n.width=t;k+="&width="+t;p||(p=window.innerHeight);n.height=p;k+="&height="+p;x=(x=x||n.fontSize)?parseInt(x):13;n.fontSize?(x=parseInt(n.fontSize,10),n.fontSize=x):(n.fontSize=x,k+="&fontSize="+x);var Z=window.OffscreenCanvas?new OffscreenCanvas(t,p):document.createElement("canvas"),r;this.modifyURL=function(a){h.loadbalanceToken&&(a+="&"+h.loadbalanceToken);return a};
this.__write=Qa;this.getFileUrl=function(a){var b=X(),d=Ea.download,c=d.indexOf("://");b=(0<c&&11>c?d:b+d)+"s="+Da+"&f="+a;return h.modifyURL(b)};this.listFiles=function(a,b){J&&J.list(a,b)};this.reconnect=function(a,b){va(a,b);A.send("ED"+M+"\t"+K+"\t"+t+"\t"+p)};var Q=new function(a,b){this.setJoinMode=a.setJoinMode;this.requestControl=a.requestControl;this.writeKeyComb=a.writeKeyComb;this.localLockFlags=0;this.checkLockFlags=!0;var d=!1,c={drawable:b};this.pauseUpdate=function(m){d=m};this.draw=
function(m,f,g,l,u){return d?null:c};this.getAppMode=function(){return a.mode};this.send=function(m){"891"!=m&&F&&a.__write(m)};this.sendInput=function(m){a.writeRawInput(m);if(a.onactivity)a.onactivity(m)};var e=null;this.getAppInfo=function(){return a.sessionInfo.appInfo};this.onresize=function(m){if(m=m.target.svSurface){m=m.getFreeSpace();var f=m.width,g=m.height;hi5.browser.isTouch||Math.abs(t-f)<w&&Math.abs(p-g)<q||!a.reconnectOnResize||!F||(e&&(clearTimeout(e),e=null),e=setTimeout(function(){va(f,
g);A.send("ED"+M+"\t"+K+"\t"+t+"\t"+p)},333))}};this.onorientationchange=function(m){};this.getClipData=zb;this.getShareFiles=a.listFiles;this.getFile=function(m){var f=a.getFileUrl(m);a.ondownload&&a.ondownload({fileName:m,url:f})||window.open(f)};this.getFileLink=a.getFileUrl;this.getGateway=function(){return k};this.reconnect=function(m,f,g){};this.sendKeyboardSyncFlags=function(m){return F?(this.remoteLockFlags=this.localLockFlags=m,!0):!1};this.setWorkDir=function(m,f){f&&a.writeText("cd "+f+
"\n")}}(this,Z);void 0!=B.displayMsg?this.displayMsg=B.displayMsg:B.displayMsg=this.displayMsg;void 0!=B.reconnectTimes&&(this.reconnectTimes=B.reconnectTimes);void 0!=B.openLink&&(this.openLink=B.openLink);void 0!=B.setTitle&&(this.setTitle=B.setTitle);"boolean"==typeof B.useWSS&&(k=(B.useWSS?"wss":"ws")+k.substring(k.indexOf("://")));this.getURL=function(){return k};this.getRuntimeURL=function(a){eb();var b=k+"&cols="+M+"&rows="+K;b+="&binary=on";var d=window.opener;if(d){var c=null;try{c=d.__sparkUser}catch(e){}c&&
(d=c.account,c=c.session,d&&(b+="&account="+d),c&&(b+="&session="+c))}b+="&pasteCap="+(hi5.browser.isChrome&&hi5.browser.isDesktop?3:0);a&&0==h.mode&&B.wsPost&&(b=k.substring(0,k.indexOf("?"))+"?_METHOD=post");b=h.modifyURL(b);(a=hi5.browser.cookie.get("__SV_TOKEN_A"))&&(b+="&__SV_TOKEN_A="+encodeURIComponent(a));return b};var Sb=parseInt(n.server_bpp||n.color||24);this.getColor=function(){return Sb};this.getDisplayName=Ga;this.run=function(){if(!F){if(Xa)A=Xa,Ra();else{var a=h.getRuntimeURL(!0);
A=h.oncreatewebsocket?h.oncreatewebsocket(a):new WebSocket(a,"ssh");A.binaryType="arraybuffer"}A.onopen=Hb;void 0!=n.recording&&"on"==n.recording&&Ab(n);A.onmessage=function(b){b=b.data;if("string"!=typeof b){var d=new Uint8Array(b);null!=aa&&aa.add(new RecordingObj(d,0,b.byteLength));na.set(d);na.handle()}else{var c=parseInt(b.substring(0,2),16);d=b.substring(2);switch(c){case 0:b=h.getRuntimeURL(!1);b=b.substring(b.indexOf("?")+1);A.send("00"+b);break;case 15:b=JSON.parse(d);A.send("8D");if(h){h.sessionInfo.protocolVersion=
b.protocolVersion;if(h.onready)h.onready();if(h.onloggedin)h.onloggedin();B.pingInterval&&h.startPing(B.pingInterval);J&&(J.enabled=!0)}qa(!1);break;case 26:b=JSON.parse(d);if(b.name){svGlobal.logger.info("msg="+d);if(h.onerror)h.onerror(b);d=__svi18n.errorCode["S"+b.name]||"";d+=b.message||b.msg;h.showMessage(d)}else 0<svGlobal.log&&console.erro("No error code for message:"+d);break;case 27:0!=B.drawLicense&&C.drawLicense(d);break;case 56:b=JSON.parse(d);Da=b.session;ca(b.appId);b.server||(b.server=
Ga());if(d=hi5.$("joinSelect"))d.value=b.joinMode;if(d=hi5.$("requestControl"))d.disabled=b.hasControl;d=Gb("joinssh.html")+"?id="+b.numericId;d=h.modifyURL(d);var e=b.webAddress;e&&0<e.length&&(c=e.indexOf("://"),e=e.substring(c+3),c=e.indexOf("/"),0<c&&(e=e.substring(0,c)),e.toLowerCase()!=location.host.toLowerCase()&&(d+="&gateway="+e));b.joinLink=d;h.sessionInfo.appInfo=b;b.ver&&b.ver!=svGlobal.version&&svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+b.ver);Ra();if(h&&h.onsessionstart)h.onsessionstart(h.sessionInfo);
break;case 58:if(J)if(b=parseInt(d.charAt(0),10),d=d.substring(1),5==b)J.notifyFiles(JSON.parse(d));else switch(d=d.split("\t"),b){case 1:J.confirmId(d[0],d[1],d[2]);break;case 2:J.read(d[0],parseInt(d[1],10),parseInt(d[2],10));break;case 4:J.close(d[0]);break;case 9:b='<a href="'+d[0]+'" download="'+d[1]+'" target="_blank">'+__svi18n.info.fileReady+"</a>",surfaces.getFocused().showMessage({msg:b,title:__svi18n.info.download})}break;case 59:b=hi5.Base64.dec(d,0);Ya=b[3]<<24|b[2]<<16|b[1]<<8|b[0];
Ya&64&&h.showMessage(__svi18n.info.recording);C.setFeature(Ya);break;case 61:b=JSON.parse(d);switch(b.type){case 0:n.fontSize=parseInt(b.fontSize);t=b.width;p=b.height;Ra();C.setAutoScale(!0);va(0,0,M,K);if(d=b.server)h.server=b.server,ab(Ga());(d=b.mapDisk)&&qb(C);qa(!1);wb=b.length;if(h.onopened)h.onopened(b);break;case 1:b=b.duration;if(h.onprogress)h.onprogress(b,wb);break;case 2:2==b.status?F=!0:(d=0==b.status,Q.pauseUpdate(d),b.warn&&h.showMessage(d?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed))}break;
case 62:Fb(d);break;case 91:wa=!0;if(h.onusername)h.onusername(Eb);else da(__svi18n.info.user||d),ka=!0,pa();break;case 93:G=JSON.parse(d);if(h.onauthprompt)h.onauthprompt(G,Db);else b=G.name||"",G.instruction&&(b+=G.instruction),b&&(z+=q,v=0,da(b),pa()),G.answer=[],cb();break;default:svGlobal.logger.warn("@TODO:"+b+"\n")}}};A.onclose=Ha;A.onerror=Ib;ab(Ga())}};this.setJoinMode=function(a){F&&A.send("8E1"+a)};this.refuseControl=function(a){F&&A.send("8E3"+a)};this.giveControl=function(a){F&&A.send("8E4"+
a)};this.requestControl=function(){F&&A.send("8E2")};this.play=function(){A.send("F3")};this.pause=function(){A.send("F2")};this.scan=function(a){A.send("F4"+(a?"1":"0"))};this.seek=function(a){C&&F&&A.send("F4"+(a?"1":"0")+"\t"+(a/C.getScale().x|0))};this.allowJoin=function(a,b){A.send("8EA"+a+"\t"+(b?1:0))};var V=null,ka=!1,G=null,ea="",wb=0;this.hide=function(){C&&(qa(!0),C.hide())};this.showMessage=function(a,b){h.displayMsg&&a&&(C?C.showMessage(a,b):("string"==typeof a&&(a={msg:a,timeout:b||
0}),hi5.notifications.notify(a)))};this.close=function(){if(A&&F)try{A.send("85"),A.close()}catch(a){}else Ha()};hi5.browser.isChromeApp?chrome.runtime.onSuspend.addListener(Ha):window.addEventListener("unload",Ha,!1);var Tb=new bb(1024,function(a){var b=v,d=z;for(a.needMore=!1;a.has(1);){var c=a.getByte();if(31>=c)if(27==c){a:{var e=a;if(e.has(1)){c=e.getByte();switch(c){case 40:c=e.getByte();svGlobal.logger.info("G0 Character Set start:"+String.fromCharCode(c));48==c?(xa=!0,svGlobal.logger.info("Line drawing mode on")):
(svGlobal.logger.info("Line drawing mode off"),xa=!1);break;case 41:c=e.getByte();xa=!1;svGlobal.logger.info("G0 Character Set canel: "+String.fromCharCode(c));break;case 60:za.exitVT52();break;case 55:ub=v;vb=z;break;case 56:v=ub;z=vb;break;case 61:svGlobal.logger.info("TODO: Enter alt keypad mode");break;case 62:svGlobal.logger.info("TODO: Enter keypad mode");break;case 66:break;case 68:lb();break;case 69:ib();Ua(!0);break;case 77:kb();break;case 83:break;case 90:I("x1B[?6c");break;case 92:svGlobal.logger.info("ST");
break;case 93:c=svGlobal.logger;for(var m=c.info,f=e,g=f.getPosition(),l="",u=f.getEnd(),D=f.getData();g<u;)if(e=D[g++],7!=e)switch(e>>4){case 0:case 1:case 2:case 3:case 4:case 5:case 6:case 7:l+=String.fromCodePoint(e);break;case 12:case 13:l+=String.fromCodePoint((e&31)<<6|D[g++]&63);break;case 14:l+=String.fromCodePoint((e&15)<<12|(D[g++]&63)<<6|(D[g++]&63)<<0)}else break;f.setPosition(g);m.call(c,"OSC:"+l);break;case 91:c=Jb(e);break a;case 99:svGlobal.logger.info("full reset");gb();break;default:svGlobal.logger.warn("unkown cmd for ESC:"+
c)}c=!0}else e.skipBack(1),c=!1}if(!c)return}else hb(c);else if(128<=c&&159>=c)switch(c){case 146:a.skip(2);break;default:svGlobal.logger.warn("C1:"+c)}else{a.skipBack(1);c=a;m=c.getPosition();f=c.getEnd();g=c.getData();for(l=m;m<f;)if(e=g[m++],31>=e){m--;break}c.setPosition(m);if(m>l){if(c=g.subarray(l,m),c=sb.decode(c,Lb),xa)for(m=c.split(""),c="",e=0,f=m.length;e<f;e++)g=m[e],c+=Rb[g]||g}else c="";da(c);if(a.needMore)return}}b==v&&d==z||pa();ia&&ia.check()});na.setHandler(Tb);this.refreshOutput=
function(){};var O={mode:0,parameters:[0],count:0,trailing:"",command:0,toString:function(){var a="CSI, ";this.mode&&(a+="mode:"+String.fromCharCode(this.mode));0<this.count&&(a+=" parameters:"+this.parameters.slice(0,this.count).join(";"));this.trailing&&(a+=" trailing:"+this.trailing);return a+=" cmd:"+String.fromCharCode(this.command)},parse:function(a){var b=0,d=!1,c=a.getByte();if(!c)return!1;if(60<=c&&63>=c)this.mode=c,c=a.getByte();else if(this.mode=0,31>=c||128<=c&&159>=c)hb(c),c=a.getByte();
if(!c)return!1;for(this.count=0;48<=c&&63>=c;)if(59==c?(this.parameters[this.count]=d?b:null,this.count++,b=0,d=!1):48<=c&&57>=c?(b=10*b+(c-48),d=!0):svGlobal.logger.warn("CSI Parameter: "+String.fromCharCode(c)),c=a.getByte(),!c)return!1;d?(this.parameters[this.count]=b,this.count++):0<this.count&&(this.parameters[this.count]=1,this.count++);for(;32<=c&&47>=c;)if(this.trailing+=String.fromCharCode(c),c=a.getByte(),!c)return!1;64<=c&&127>=c?this.command=c:(this.command="",svGlobal.logger.warn("Invalid CSI final char:"+
String.fromCharCode(c)));return!0}},Ma=document.getElementById("svHistory");Ma&&(Ca?Ma.onclick=Wa:Ma.parentNode.removeChild(Ma));this.showHistory=Wa;this.getUploadManager=function(){return J};this.addSurface=function(a){C=a;tb&&a.setPlayerMode();var b=a.canvas.parentNode;Ca&&(W=rb(b,"textarea","copytextarea"))&&(W.value="");ja=rb(b,"div","cursorID");Z.width=t;Z.height=p;r=Z.getContext("2d",{alpha:!1});r.fontKerning="none";a.alwaysPaste=!0;a.setAutoScale(0<h.mode);va(t,p);a.setController(Q);a.setTouchpad(y(n.touchpad));
a.setClipboard(y(n.mapClipboard));qb(C);b=void 0!=n.cmdToCtrl?y(n.cmdToCtrl):void 0!=B.cmdToCtrl?B.cmdToCtrl:h.mapCmdToCtrl;a.run(99997,!1,!1,b);Ca&&(a.onclipdata=pb)};this.sendPing=function(a){a=new Uint8Array(2);a[0]=146;Qa(a.buffer)};this.startPing=function(a){ia||(ia=new hi5.tool.ResponseMonitor(function(){wa&&h.sendPing()},function(){wa&&ia.check(1)}));ia.setInterval(a,a);setTimeout(function(){ia.check()},1E3*a)};this.stopPing=function(){ia&&ia.stop()};this.writeText=I;this.writeScancode=function(a,
b){I(oa.process(a,b,0))};var Ub={" ":57,space:57,pageup:201,pagedown:209,end:207,home:199,left:203,up:200,right:205,down:208,printscreen:183,insert:210,del:211,"delete":211,altgr:184,windows:219,windowsright:220,context:221,esc:1,backspace:14,tab:15,enter:28,meta:29,command:29,ctrl:29,shift:42,alt:56,capslock:58,f1:59,f2:60,f3:61,f4:62,f5:63,f6:64,f7:65,f8:66,f9:67,f10:68,f11:87,f12:88,numlock:69,scrolllock:70,add:78};this.writeKeyComb=function(a){a=a.split("+");var b=a.length;if(0!=b)for(var d=null,
c=0;c<b;c++){var e=a[c];""==e&&""==d&&(e="Add");if(""!=e){d=e;var m=Ub[d.toLowerCase()];m?h.writeScancode(!0,m):svGlobal.logger.warn("Invalid key:"+d)}d=e}};var Na=!1,la=0,ma=0,Oa=0,sa=!1,xb=0,yb=0,ta=null;this.writeRawInput=function(a){if(F){var b=parseInt(a.substring(0,2),16);a=a.substring(2).split("\t");switch(b){case 128:la=parseInt(a[0]);ma=parseInt(a[1]);Oa=parseInt(a[2]);sa=!1;Na=!0;xb=Math.floor(la/w)*w;yb=Math.floor(ma/q)*q;1015==U?I("\u001b["+(parseInt(a[2])+32)+";"+(Math.floor(la/w)+1)+
";"+(Math.floor(ma/q)+1)+"M"):1006==U?I("\u001b[<"+a[2]+";"+(Math.floor(la/w)+1)+";"+(Math.floor(ma/q)+1)+"M"):U&&I("\u001b[M"+a[2]+String.fromCharCode(Math.floor(la/w)+33)+String.fromCharCode(Math.floor(ma/q)+33));return;case 129:U&&(1015==U?I("\u001b["+(parseInt(a[2])+32)+";"+(Math.floor(la/w)+1)+";"+(Math.floor(ma/q)+1)+"M"):1006==U?I("\u001b[<"+a[2]+";"+(Math.floor(parseInt(a[0])/w)+1)+";"+(Math.floor(parseInt(a[1])/q)+1)+"m"):U&&I("\u001b[M3"+String.fromCharCode(Math.floor(parseInt(a[0])/w)+
33)+String.fromCharCode(Math.floor(parseInt(a[1])/q)+33)));Oa=parseInt(a[2]);2==Oa&&Na&&!sa?(W&&(W.value=""),Ca&&C.processClipReq("text/plain",Kb)):sa&&(a=E.getMultiLines(Math.floor(la/w)+1,Math.floor(ma/q+.1)+1,Math.floor(parseInt(a[0])/w+.4)+1,Math.floor(parseInt(a[1])/q-.4)+1))&&C&&C.copyToClip("text/plain;"+a);ta&&(setTimeout(C.removeWhiteboard,333),ta=null);sa=Na=!1;return;case 130:if(Na){b=parseInt(a[0]);a=parseInt(a[1]);if(!sa){if(3>Math.abs(b-la)&&3>Math.abs(a-ma))return;sa=!0}if(0==Oa){if(!ta){var d=
C.initWhiteboard();d.style.opacity=.6;d=d.getContext("2d");ta=new hi5.canvas.TextSelect(d,q,B.selectionColor,"1px",t)}ta.clear();ta.draw(xb,yb,b,a)}}return;case 131:1006==U?I("\u001b[<"+("1"==a[2]?65:64)+";"+(Math.floor(parseInt(a[0])/w)+1)+";"+(Math.floor(parseInt(a[1])/q)+1)+"M"):U?I("\u001b[M"+("1"==a[2]?5:4)+String.fromCharCode(Math.floor(parseInt(a[0])/w)+64)+String.fromCharCode(Math.floor(parseInt(a[1])/q)+64)):"0"==a[2]&&Wa();return;case 132:d=0==a[0];b=parseInt(a[1]);if(ka||G)d&&(a=b,28==
a||156==a?(z+=q,v=0,ka?(ka=!1,A.send("5B"+ea),ea=""):G&&(G.answer.push(ea),ea="",cb())):14==a&&0<ea.length&&(ea=ea.substring(0,ea.length-1),ka&&(Ta(),da(" "),Ta())));else if(I(oa.process(d,b,0)),28!=b)ha||(ha=R());else if(ha){if(ha&&(a=E.getSingleLine(P(),ha,R()))){b=E.getSingleLine(P(),1,ha);if(h.oncommand)h.oncommand(a,b);a.startsWith("cd /")?C.setDirectory(a.substring(3)):a.startsWith("base64 ")&&(T.on=!0,T.cmd=a,T.prompt=b)}ha=0}return;case 139:b=parseInt(a[1]);d=0==a[0];I(oa.process(d,b,1));
return;case 134:ka||G?ob(a[0]):(ha||(ha=R()),I(oa.process(!0,a[0],3)));return}svGlobal.logger.warn("Unknowncode: "+a[1]+" type:"+b)}};var za=new function(){function a(u){switch(u){case e:return"vt100";case m:return"vt52";case f:return"att513";case c:return"linux";case d:return"xterm";case b:return"default";default:return"unknown"}}var b="\u001b[11~ \u001b[12~ \u001b[13~ \u001b[14~ \u001b[15~ \u001b[17~ \u001b[18~ \u001b[19~ \u001b[20~ \u001b[21~ \u001b[23~ \u001b[24~".split(" "),d="\u001bOP \u001bOQ \u001bOR \u001bOS \u001b[15~ \u001b[17~ \u001b[18~ \u001b[19~ \u001b[20~ \u001b[21~ \u001b[23~ \u001b[24~".split(" "),
c="\u001b[[A \u001b[[B \u001b[[C \u001b[[D \u001b[[E \u001b[17~ \u001b[18~ \u001b[19~ \u001b[20~ \u001b[21~ \u001b[23~ \u001b[24~".split(" "),e="\u001bOP \u001bOQ \u001bOR \u001bOS \u001bOT \u001bOU \u001bOV \u001bOW \u001bOX \u001bOY \u001bOZ \u001bO[".split(" "),m=["\u001bP","\u001bQ","\u001bR","\u001bS"],f="\u001bOw \u001bNa \u001bSB \u001b[J \u001bOm \u001bf6 \u001b[U \u001b[V \u001bOk \u001bOl".split(" "),g=b,l=b;this.setKeyboard=function(u){u=u.toLowerCase();svGlobal.logger.info("set keyboard: "+
u);g!=m&&(l=g);switch(u){case "vt52":g=m;break;case "att513":g=f;break;case "vt100":g=e;break;case "linux":g=c;break;case "xterm":g=d;break;case "default":g=b;break;default:g=b}};this.exitVT52=function(){svGlobal.logger.info("exit vt52, switch to: "+a(l));g=l};this.fromScancode=function(u){var D;59<=u&&68>=u?D=g[u-59]:87==u?D=g[10]:88==u&&(D=g[11]);return D||""}};za.setKeyboard(Mb);this.setKeyboard=function(a){za.setKeyboard(a)};var oa=new function(){var a=!1,b=!1,d=!1,c=0;this.setAltDown=function(e){b=
e};this.setCtrlDown=function(e){a=e};this.setCursorKeyMode=function(e){svGlobal.logger.info("Esc mode:"+e+" was: "+c);c=e};this.process=function(e,m,f){if(3==f)return m;if(0==f){switch(m){case 29:case 157:return a=e,"";case 56:case 184:return b=e,"";case 42:case 54:return d=e,""}if(e){switch(m){case 28:e="\r";break;case 200:e=0==c?"\u001b[A":1==c?"\u001bOA":"\u001bA";break;case 208:e=0==c?"\u001b[B":1==c?"\u001bOB":"\u001bB";break;case 205:e=0==c?"\u001b[C":1==c?"\u001bOC":"\u001bC";break;case 203:e=
0==c?"\u001b[D":1==c?"\u001bOD":"\u001bD";break;case 59:case 60:case 61:case 62:case 63:case 64:case 65:case 66:case 67:case 68:case 87:case 88:e=za.fromScancode(m);break;case 15:e="\t";break;case 209:e="\u001b[6~";break;case 201:e="\u001b[5~";break;case 199:e=0==c?"\u001b[H":"\u001bOH";break;case 207:e=0==c?"\u001b[F":"\u001bOF";break;case 14:e=d?"\b":"\u007f";break;case 211:e="\u001b[3~";break;case 197:e="\u00ff\u00f3";break;case 210:e="\u001b[2~";break;case 1:e="\u001b";break;case 55:e="*";break;
case 71:e=Q.localLockFlags&2?"7":0==c?"\u001b[H":"\u001bOH";break;case 72:e=Q.localLockFlags&2?"8":0==c?"\u001b[A":"\u001bOA";break;case 73:e=Q.localLockFlags&2?"9":"\u001b[5~";break;case 74:e="-";break;case 75:e=Q.localLockFlags&2?"4":0==c?"\u001b[D":"\u001bOD";break;case 76:e=Q.localLockFlags&2?"5":"\u001bOu";break;case 77:e=Q.localLockFlags&2?"6":0==c?"\u001b[C":"\u001bOC";break;case 78:e="+";break;case 79:e=Q.localLockFlags&2?"1":0==c?"\u001b[F":"\u001bOF";break;case 80:e=Q.localLockFlags&2?"2":
0==c?"\u001b[B":"\u001bOB";break;case 81:e=Q.localLockFlags&2?"3":"\u001b[6~";break;case 82:e=Q.localLockFlags&2?"0":"\u001b[2~";break;case 83:e=Q.localLockFlags&2?".":"\u001b[3~";break;case 156:e="\r";break;case 181:e="/";break;default:return svGlobal.logger.warn("Invalid code:"+m),""}b&&(e="\u001b"+e);return e}return""}if(1==f&&e)if(a){if(64<m&&91>m)return String.fromCharCode(m-64);switch(m){case 54:return"\u001e";case 219:return"\u001b";case 220:return"\u001c";case 221:return"\u001d";case 32:return"\x00";
case 192:return"\u001e";case 191:return"\u001f";default:return svGlobal.logger.warn("Invalid key code:"+m),""}}else if(b)return"\u001b"+String.fromCharCode(m).toLowerCase()}};this.getKeyHandler=function(){return oa}};
