var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(h,r,m){if(null==h)throw new TypeError("The 'this' value for String.prototype."+m+" must not be null or undefined");if(r instanceof RegExp)throw new TypeError("First argument to String.prototype."+m+" must not be a regular expression");return h+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(h,r,m){if(h==Array.prototype||h==Object.prototype)return h;h[r]=m.value;return h};
$jscomp.getGlobal=function(h){h=["object"==typeof globalThis&&globalThis,h,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var r=0;r<h.length;++r){var m=h[r];if(m&&m.Math==Math)return m}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(h,r){var m=$jscomp.propertyToPolyfillSymbol[r];if(null==m)return h[r];m=h[m];return void 0!==m?m:h[r]};$jscomp.polyfill=function(h,r,m,x){r&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(h,r,m,x):$jscomp.polyfillUnisolated(h,r,m,x))};
$jscomp.polyfillUnisolated=function(h,r,m,x){m=$jscomp.global;h=h.split(".");for(x=0;x<h.length-1;x++){var z=h[x];if(!(z in m))return;m=m[z]}h=h[h.length-1];x=m[h];r=r(x);r!=x&&null!=r&&$jscomp.defineProperty(m,h,{configurable:!0,writable:!0,value:r})};
$jscomp.polyfillIsolated=function(h,r,m,x){var z=h.split(".");h=1===z.length;x=z[0];x=!h&&x in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var ca=0;ca<z.length-1;ca++){var Y=z[ca];if(!(Y in x))return;x=x[Y]}z=z[z.length-1];m=$jscomp.IS_SYMBOL_NATIVE&&"es6"===m?x[z]:null;r=r(m);null!=r&&(h?$jscomp.defineProperty($jscomp.polyfills,z,{configurable:!0,writable:!0,value:r}):r!==m&&($jscomp.propertyToPolyfillSymbol[z]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(z):$jscomp.POLYFILL_PREFIX+
z,z=$jscomp.propertyToPolyfillSymbol[z],$jscomp.defineProperty(x,z,{configurable:!0,writable:!0,value:r})))};$jscomp.polyfill("String.prototype.startsWith",function(h){return h?h:function(r,m){var x=$jscomp.checkStringArgs(this,r,"startsWith");r+="";var z=x.length,ca=r.length;m=Math.max(0,Math.min(m|0,x.length));for(var Y=0;Y<ca&&m<z;)if(x[m++]!=r[Y++])return!1;return Y>=ca}},"es6","es3");
$jscomp.polyfill("String.fromCodePoint",function(h){return h?h:function(r){for(var m="",x=0;x<arguments.length;x++){var z=Number(arguments[x]);if(0>z||1114111<z||z!==Math.floor(z))throw new RangeError("invalid_code_point "+z);65535>=z?m+=String.fromCharCode(z):(z-=65536,m+=String.fromCharCode(z>>>10&1023|55296),m+=String.fromCharCode(z&1023|56320))}return m}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(h){return h?h:function(r,m,x){var z=this.length||0;0>m&&(m=Math.max(0,z+m));if(null==x||x>z)x=z;x=Number(x);0>x&&(x=Math.max(0,z+x));for(m=Number(m||0);m<x;m++)this[m]=r;return this}},"es6","es3");$jscomp.typedArrayFill=function(h){return h?h:Array.prototype.fill};$jscomp.polyfill("Int8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Uint8ClampedArray.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Float32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Float64Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("String.prototype.trimRight",function(h){function r(){return this.replace(/[\s\xa0]+$/,"")}return h||r},"es_2019","es3");$jscomp.polyfill("String.prototype.trimEnd",function(h){return h||String.prototype.trimRight},"es_2019","es3");var svManager={getInstance:function(){var h=window.$ssh;return h&&h.running&&h.running()?h:null}};
function connvertServer(h){var r={};r.id=h.id;r.server=h.id;r.displayName=h.displayName||h.id;if(h=h.ssh){for(var m in h)r[m]=h[m];r.user=h.username||"";r.pwd=h.password||""}return r}
svGlobal.SSH=function(h,r,m,x){function z(a){return"on"==a||"true"==a||1==a}function ca(a){k.loadbalanceToken||(D.randomAppId&&(a=hi5.tool.uuid()),k.loadbalanceToken=D.loadbalanceTokenName?D.loadbalanceTokenName+"="+a:"")}function Y(){var a=h.indexOf("://"),b=h.substring(a+3);a=b.indexOf("/");0<a&&(b=b.substring(0,a));return location.protocol+"//"+b}function wb(a){if(!Ba)return"";var b=Y(),e=Ca.clipboard,c=e.indexOf("://");b=(0<c&&11>c?e:b+e)+"s="+Ba+"&t="+Date.now()+"&type="+a;return hi5.browser.httpGet(k.modifyURL(b),
!1)}function Oa(a,b){b&&(Z=b);a&&(Q=a,Da=(Q-1)*n);Xa=1==Z&&Q==Math.floor(m/n)}function Ea(a,b,e,c){var d=b;c=c||Math.floor(d/n);b=e||Math.floor(a/v);var l=null;e&&(a=O*v,d=R*n);F&&(l=q.getImageData(0,0,Math.min(b*v,M),Math.min(c*n,R*n)));r=a;m=d;e=r;a=m;C.setSize(e,a);aa.width=e;aa.height=a;q.textBaseline="top";q.font=u.fontSize+"px "+(u.fontFamily||u.fontName);Fa();l&&(q.putImageData(l,0,0),da());R=c;O=b;M=O*v;Oa(Math.floor(m/n));E?E.resize(O,R):E=new Ya(O,R);if(k.onresolutionchange)k.onresolutionchange(r,
m)}function Pa(a){B.send(a)}function Ga(){return u.displayName||u.server||u.symlink||u.id||"undefined"}function Za(a){k.setTitle&&(document.title=a)}function $a(a,b,e){this.need=a;this.handler=b;this.repeat=e||1}function xb(a){ba=new RecordingManager;ba.setHeader({name:"rec",width:a.width,height:a.height,color:a.fontSize,namesuffix:".sshv",filetag:"SSHV",duration:0})}function yb(a,b){var e=0,c=!1;this.width=a;this.interval=b;var d=0;this.start=function(){c||(c=!0,e=setInterval(function(){if(C&&F){var l=
C.getThumbnail(a);l&&l.length!=d&&(B.send("8E7"+l),d=l.length)}},b))};this.stop=function(){clearInterval(e)}}function zb(a,b){!W||W.width==a&&W.interval==b||(W.stop(),W=null);W||(W=new yb(a,b));W.start()}function Ab(a){F&&B.send("5D"+a.join("\t"));G=null}function ab(){if(G){var a=G.answer.length;a<G.prompt.length?(ea(G.prompt[a]),da(),ra()):(B.send("5D"+G.answer.join("\t")),G=null)}}function Bb(a){F&&B.send("5B"+a)}function Cb(a){var b=parseInt(a.substring(0,1),16),e=a.substring(1);a=!1;var c=k.sessionInfo.appInfo;
switch(b){case 1:var d=JSON.parse(e);k.onsessionjoin&&(a=k.onsessionjoin(d));if(a)break;k.showMessage(__svi18n.info.joinsession.applyArgs([d.numericId,d.__ip,d.name]));break;case 2:d=JSON.parse(e);k.onsessionexit&&(a=k.onsessionexit(d));if(a)break;k.showMessage(__svi18n.info.exitsession.applyArgs([d.numericId,d.__ip,d.name]));break;case 3:d=JSON.parse(e);c.joinMode!=d.mode&&(c.joinMode=d.mode,b=hi5.$("joinSelect"))&&(b.value=d.mode);if(c.hasControl)break;C.setReadOnly(!1);if(b=hi5.$("requestControl"))b.disabled=
!0;k.ongivecontrol&&(a=k.ongivecontrol());if(a)break;k.showMessage(__svi18n.info.givecontrol);break;case 4:C.setReadOnly(!0);c.hasControl=!1;if(b=hi5.$("requestControl"))b.disabled=!1;k.ontakebackcontrol&&(a=k.ontakebackcontrol());if(a)break;k.showMessage(__svi18n.info.nocontrol);break;case 5:d=JSON.parse(e);k.onrequirecontrol&&(a=k.onrequirecontrol(d));if(a)break;a=__svi18n.info.title.applyArgs([d.name,d.numericId,d.__ip]);k.showMessage({title:a,msg:__svi18n.info.recontrol,cbYes:function(){k.giveControl(d.numericId);
this.destroy()},cbNo:function(){k.refuseControl(d.numericId);this.destroy()}});break;case 6:C.setTouchRemoting(!0);break;case 7:d=JSON.parse(e);d.width&&d.height&&Ea(0,0,d.cols,d.rows);break;case 8:d=JSON.parse(e);if(k.onrequestcredential&&k.onrequestcredential(d))break;C.requestCredential(d);break;case 9:d=JSON.parse(e);0<d.interval&&0<d.width?zb(d.width,d.interval):W&&(W.stop(),W=null);break;case 11:d=JSON.parse(e);k.onrequirejoin&&(a=k.onrequirejoin(d));if(a)break;a=__svi18n.info.title.applyArgs([d.name,
d.numericId,d.__ip]);k.showMessage({title:a,msg:__svi18n.info.reqjoin,cbYes:function(){k.allowJoin(d.numericId,!0);this.destroy()},cbNo:function(){k.allowJoin(d.numericId,!1);this.destroy()}});break;case 12:bb=!0}}function Db(a){var b=D.page&&D.page.join||"";if(b.startsWith("http://")||b.startsWith("https://"))return b;if(b.startsWith("/"))return location.origin+b;var e=location.href,c=e.lastIndexOf("/");if(b)return e.substring(0,c+1)+b;b=Y();e.toLowerCase().startsWith(b.toLowerCase())&&(b=e.substring(0,
c));return b+"/"+a}function sa(a){na.style.display=a?"none":"block"}function Eb(a){svGlobal.logger.info("opened...");F=!0;B.send("87"+navigator.userAgent);if(k.onopen)k.onopen()}function Fb(a){svGlobal.logger.warn(a)}function Ha(a){svGlobal.logger.warn("closed ...");sa(!0);if(!F&&((a=__svi18n.errorCode.connection)||(a="error connection"),k)){if(k.onerror)k.onerror({name:"connection",message:a});k.showMessage(a);0<svGlobal.log&&console.error(a)}xa=F=!1;if(k&&k.onclose)k.onclose(bb);try{null!=ba&&(ba.exit(),
ba=null),C&&C.close()}catch(b){}oa&&(oa.release(),oa=null);aa=q=null;B&&(B.onopen=null,B.onmessage=null,B.onclose=null,B=B.onerror=null);C=S=null;k&&(k=null);window&&window.$ssh&&(window.$ssh=null);null!=ba&&(ba.exit(),ba=null)}function cb(){10>u.fontSize&&(u.fontSize=10);13>u.fontSize?n=u.fontSize+6:12<u.fontSize&&19>u.fontSize?n=u.fontSize+8:18<u.fontSize&&25>u.fontSize?n=u.fontSize+12:24<u.fontSize&&(n=u.fontSize+16);u.lineHeight&&(n=parseInt(u.lineHeight));db=(n-u.fontSize)/2|0;q.textBaseline=
"top";q.font=u.fontSize+"px "+u.fontFamily;v=q.measureText("X").width;R=parseInt(m/n);O=parseInt(r/v);M=O*v;Oa(parseInt(m/n));E?E.resize(O,R):E=new Ya(O,R)}function Qa(){Fa();A=w=0;cb();na.style.width=v+"px";na.style.height=n+"px";xa=!0}function da(){eb||Ra.drawImage(aa,0,0)}function fb(){ya=!1;I=u.fgColor||pa[7];K=u.bgColor||pa[0];Sa=0;ta=!0}function gb(a){switch(a){case 0:svGlobal.logger.info("C0 0");break;case 5:svGlobal.logger.info("C0 END enquiry");break;case 7:svGlobal.logger.info("C0 bell");
break;case 8:Ta();break;case 9:a=w/v/8;a=parseInt(a)+1;w=8*a*v;ua();break;case 10:A+=n;ua(!0);break;case 11:A+=n;ua(void 0);break;case 12:svGlobal.logger.info("C0 form feed");break;case 13:hb();break;case 14:svGlobal.logger.info("C0 Shift out");break;case 15:svGlobal.logger.info("C0 exit_alt_charset_mode");break;default:svGlobal.logger.warn("Unknown C0 control:"+a)}}function Gb(a){var b=a.getPosition();if(!N.parse(a))return a.setPosition(b-2),!1;a=N.count;b=N.parameters;switch(N.command){case 64:0==
a&&(b[0]=1);a=b[0];b="";for(var e=a*v,c=q.getImageData(w,A,M-w-e,n),d=0;d<a;d++)b+=" ";ea(b);w-=e;q.putImageData(c,w+e,A);E.insertSpace(a,T(),P());break;case 65:0==a&&(b[0]=1);A-=(b[0]||1)*n;break;case 66:0==a&&(b[0]=1);A+=(b[0]||1)*n;break;case 67:0==a&&(b[0]=1);w+=(b[0]||1)*v;break;case 68:0==a&&(b[0]=1);w-=(b[0]||1)*v;break;case 69:0==a&&(b[0]=1);A+=b[0]*n;w=0;break;case 70:0==a&&(b[0]=1);A-=b[0]*n;w=0;break;case 71:0==a&&(b[0]=1);Ia(0,b[0]);break;case 72:case 102:0==a&&(b[0]=b[1]=1);Ia(b[0]||
1,b[1]||1);break;case 74:a||(b[0]=0);switch(b[0]){case 0:q.fillStyle=K;q.fillRect(w,A,M-w,R*n-A);q.fillStyle=I;E.clearEOS(T(),P());break;case 1:q.fillStyle=K;q.fillRect(0,0,w,A);q.fillStyle=I;E.clearBOS(T(),P());break;case 2:Fa();A=w=0;E.cleanScreen();break;case 3:Fa();A=w=0;E.cleanScreen();break;default:svGlobal.logger.warn("invalid CSI J:"+b[0])}break;case 75:a||(b[0]=0);switch(b[0]){case 0:ib();break;case 1:q.fillStyle=K;q.fillRect(0,A,w,n);q.fillStyle=I;E.clearBOL(T(),P());break;case 2:q.fillStyle=
K;q.fillRect(0,A,M,n);q.fillStyle=I;E.clearLine(P());break;default:svGlobal.logger.warn("invalid CSI K:"+b[0])}break;case 76:case 84:a||(b[0]=1);jb(b[0],76==N.command);break;case 77:case 83:a||(b[0]=1);kb(b[0],77==N.command);break;case 80:a||(b[0]=1);a=b[0];b=w+a*v;b=q.getImageData(b,A,M-b,n);ib();q.putImageData(b,w,A);E.deleteChars(T(),P(),a);break;case 88:a||(b[0]=1);a=b[0];q.fillStyle=K;q.fillRect(w,A,a*v,n);q.fillStyle=I;E.eraseChars(T(),P(),a);break;case 90:a||(b[0]=1);w=8*((w/v/8|0)-b[0]+1)*
v;ua();break;case 100:a||(b[0]=1);Ia(b[0]);break;case 101:a||(b[0]=1);Ia(P()+b[0]);break;case 104:if(63==N.mode)switch(b[0]){case 1:qa.setEscMode(1);break;case 5:svGlobal.logger.info("Reversal screen mode");break;case 6:svGlobal.logger.info("Relative origion mode");break;case 7:svGlobal.logger.info("wraparound mode on");ta=!0;break;case 25:sa(!1);break;case 45:svGlobal.logger.info("reverse-wraparound mode on");break;case 1E3:case 1001:case 1002:case 1003:case 1005:case 1006:V=b[0];svGlobal.logger.warn("mouse tracking on:"+
V);break;case 1034:svGlobal.logger.warn("TD:Interpret meta key, xterm.");break;default:svGlobal.logger.warn("TD: CSI ? Pm h, Ps:"+b[0])}break;case 108:if(63==N.mode)switch(b[0]){case 1:qa.setEscMode(0);break;case 2:qa.setEscMode(2);break;case 3:svGlobal.logger.info("80 Column Mode (DECCOLM), VT100");break;case 5:svGlobal.logger.info("screen mode: "+N.toString());break;case 6:svGlobal.logger.info("Absolute origion mode: "+N.toString());break;case 7:ta=!1;break;case 12:break;case 25:sa(!0);break;case 45:svGlobal.logger.info("reverse-wraparound mode off");
break;case 1E3:case 1001:case 1002:case 1003:case 1005:case 1006:V=0;break;default:svGlobal.logger.warn("TD: CSI ? Pm l, Ps:"+b[0])}break;case 109:0==a&&(a=1,b[0]=0);for(e=0;e<a;e++)switch(b[e]){case 0:za(7);Aa(0);Ua(!1);break;case 1:Ua(!0);break;case 2:break;case 4:break;case 5:case 8:break;case 7:za(0);Aa(7);break;case 27:za(7);Aa(0);break;case 30:case 31:case 32:case 33:case 34:case 35:case 36:case 37:za(b[e]-30);break;case 38:return 2==b[e+1]&&(I="rgb("+b[e+2]+","+b[e+3]+","+b[e+4]+")",q.fillStyle=
I),!0;case 39:za(7);break;case 40:case 41:case 42:case 43:case 44:case 45:case 46:case 47:Aa(b[e]-40);break;case 48:return 2==b[e+1]&&(K="rgb("+b[e+2]+","+b[e+3]+","+b[e+4]+")"),!0;case 49:Aa(0);1==e&&39==b[0]&&Ua(!1);break;default:return svGlobal.logger.warn("TD: SGR="+N.toString()),!0}break;case 110:6==b[0]?63==N.mode?L("\u001b[?"+P()+";"+T()+"R"):L("\u001b["+P()+";"+T()+"R"):5==b[0]&&L("\u001b[0n");break;case 112:"!"==N.trailing&&fb();break;case 114:N.mode||Oa(b[1],b[0]);break;default:svGlobal.logger.warn("TD: CSI="+
N.toString())}return!0}function jb(a,b){a||(a=1);b=b?A/n+1:Z;var e=(b-1)*n;if(Q!=b){var c=q.getImageData(0,e,M,(Q-b-a+1)*n);q.fillStyle=K;q.fillRect(0,e,M,n*a);q.putImageData(c,0,(b+a-1)*n);q.fillStyle=I;E.scrollUp(a,b,Q)}}function kb(a,b){a||(a=1);b=b?A/n+1:Z;var e=(b-1)*n,c=Q*n,d=a*n,l=e+d;c!=l&&(l=q.getImageData(0,l,M,c-l),q.fillStyle=K,q.fillRect(0,c-d,M,d),q.fillStyle=I,q.putImageData(l,0,e),E.scrollDown(a,b,Q))}function ua(a){ta&&w>=M&&(w=0,A+=n);if((ta||a)&&A>Da){for(;A>Da;)A-=n;Xa?(q.drawImage(aa,
0,-n),q.fillStyle=K,q.fillRect(0,Da,r,n),E.appendLines(1)):(a=q.getImageData(0,(Z-0)*n,M,(Q-Z)*n),q.fillStyle=K,q.fillRect(0,(Z-1)*n,M,(Q-Z+1)*n),q.putImageData(a,0,(Z-1)*n),E.scrollDown(1,Z,Q));q.fillStyle=I}}function Ta(){w-=v;0>w&&(w=0)}function P(){return(A/n|0)+1}function T(){return(w/v|0)+1}function Ia(a,b){b&&(w=(b-1)*v,0>w&&(w=0));a&&(A=(a-1)*n)}function Aa(a){K=Ja[a];K||(K=u.bgColor||"black",svGlobal.logger.info("xx colorIndex:"+a))}function za(a){Sa=a;I=pa[a];I||(I=u.fgColor||"white",svGlobal.logger.info("xx colorIndex:"+
a));q.fillStyle=I}function Ua(a){pa=a?lb:Ja;I=pa[Sa]}function ib(){q.fillStyle=K;q.fillRect(w,A,M-w,n);q.fillStyle=I;E.clearEOL(T(),P())}function Fa(){q.fillStyle=K;q.fillRect(0,0,aa.width,aa.height);q.fillStyle=I}function ra(){na.style.top=A+"px";na.style.left=w+"px";var a=E.getChar((w/v|0)+1,(A/n|0)+1);a&&q.measureText(a).width>v?na.style.width=2*v+"px":na.style.width=v+"px"}function ea(a){U.on&&(a.startsWith(U.prompt)?(U.on=!1,setTimeout(U.process,30)):U.text+=a);var b=O-(w/v|0);for(var e=a.length,
c=0;c<e;){var d=a.charAt(c++);q.measureText(d).width>v?b-=2:b--;if(0==b)break;else if(0>b){c--;break}}b=c+1>=e?-1:c;0<=b?(mb(a.substring(0,b),b),ua(),ea(a.substring(b))):mb(a,a.length)}function mb(a,b){if(a){E.writeText(T(),P(),a);for(var e=0,c=[],d=0;d<b;d++){var l=a.charAt(d),t=q.measureText(l).width;c.push(t);e+=t<=v?v:2*v}q.fillStyle=K;q.fillRect(w|0,A,Math.ceil(e),n);q.fillStyle=I;e=A+db;for(d=0;d<b;d++)l=a.charAt(d),t=c[d],t==v?(q.fillText(l,w,e),w+=v):t>v?(t=(2*v-t)/2,q.fillText(l,w+t,e),w+=
2*v):(t=(v-t)/2,q.fillText(l,w+t,e),w+=v)}}function nb(a){fa+=a;ka?(ea(a),da(),ra()):G&&G.echo[G.answer.length]&&(ea(a),da(),ra())}function hb(){w=0;A>(Q-1)*n&&(A=(Q-1)*n)}function ob(a){if(F)return(a=a.getData("text/plain"))?(a=a.replace(/\r\n/g,"\n"),ka||G?nb(a):L(a),!0):!1}function pb(){if(X){var a=!!X.value;X.value=E.toString();a||(a=new hi5.ui.Lightbox(document.getElementById("copydialog")),a.show(),C&&C.setIgnorePaste(!1),a.onclose=function(){X.value="";C&&C.focus()});setTimeout(function(){X.scrollTop=
X.scrollHeight},10)}}function qb(a){z(u.mapDisk)&&(J||(J=new hi5.file.UploadManager(new hi5.file.WsFileService(Pa),!1),J.enabled=!0,J.canCopyFile=!1,J.addEvent("beforeupload",function(b,e,c){k.beforeupload&&k.beforeupload(b,e,c)}),J.addEvent("fileuploaded",function(b,e,c){if(k.onfileuploaded)k.onfileuploaded(b,e,c)}),J.addEvent("uploaded",function(b,e){if(k.onuploaded)k.onuploaded(b,e)}),J.addEvent("uploadingCancelled",function(){if(k.onuploadingCancelled)k.onuploadingCancelled()})),a.setFileHandler(J))}
function L(a){if(a){a=Ka.encode(a);var b=a.length+1,e=new Uint8Array(b);e[0]=147;for(var c=1;c<b;c++)e[c]=a[c-1];B.send(e.buffer)}}function Hb(a,b){a&&"text/plain"==b?ob(a):k.showMessage("Please use Ctrl+V or browser's Edit menu")}function Ya(a,b){function e(){var f=Array(a);hi5.Arrays.fill(f,0,a," ");return f}function c(f,g){if(g)for(var p=q.measureText("W").width,y=0;y<f;y++){var H=g[y];H&&7923<H.charCodeAt(0)&&q.measureText(H).width>p&&f--}return f}var d=0,l=[],t=10*b;this.resize=function(f,g,
p){p=0;for(var y=l.length;p<y;p++)if(l[p]&&(l[p].length=f,f>a))for(var H=a;H<f;H++)l[p][H]=" ";a=f;b=g;t=10*b};this.writeText=function(f,g,p){g--;f--;var y=l[d+g];y||(y=e(),l[d+g]=y);g=0;for(var H=p.length;g<H;g++)y[g+f]=p[g]};this.appendLines=function(f){d+=f};this.scrollDown=function(f,g,p){p=d+p-1-f;for(g=d+g-1;g<=p;g++)l[g]=l[g+f];p++;for(g=0;g<f;g++)l[p+g]=e()};this.scrollUp=function(f,g,p){g=d+g-1+f;for(p=d+p-1;p>=g;p--)l[p]=l[p-f];g--;for(p=0;p<f;p++)l[g-p]=e()};this.cleanScreen=function(){d=
l.length;if(d>=t){var f=2*b;l.splice(0,f);d-=f}};this.clearEOS=function(f,g){g--;f--;for(var p=d+g,y,H=0,ha=b-g;H<ha;H++)if(y=l[p+H])for(g=f;g<a;g++)y[g]=" "};this.clearBOS=function(f,g){g--;f--;for(var p=d,y,H,ha=0;ha<g;ha++)if(H=l[p+ha])for(f=c(f,dataRow),y=0;y<f;y++)H[y]=" "};this.clearLine=function(f){f--;(f=l[d+f])&&hi5.Arrays.fill(f,0,a," ")};this.clearBOL=function(f,g){g--;f--;if(g=l[d+g]){f=c(f,g);for(var p=0;p<f;p++)g[p]=" "}};this.clearEOL=function(f,g){g--;f--;if(g=l[d+g])for(f=c(f,g);f<
a;f++)g[f]=" "};this.eraseChars=function(f,g,p){g--;f--;if(g=l[d+g]){var y=f=c(f,g);for(f+=p;y<f;y++)g[y]=" "}};this.deleteChars=function(f,g,p){g--;f--;if(g=l[d+g])f=c(f,g),g.splice(f,p)};this.getChar=function(f,g){g--;f--;return(g=l[d+g])?g[c(f,g)]:null};this.insertSpace=function(f,g,p){p--;g--;if(p=l[d+p]){g=c(g,p);for(var y=p.length-1;y>=g;y--)p[y+f]=p[y];for(y=0;y<f;y++)p[g+y]=" "}};this.getSingleLine=function(f,g,p){f--;g--;p--;var y="";if(f=l[d+f])for(g=c(g,f),p=c(p,f);g<p;g++)y+=f[g];return y.trimEnd()};
this.getMultiLines=function(f,g,p,y){if(y<g)return this.getMultiLines(p,y,f,g);var H=y-g+1;if(1>H)return null;if(1==H)return this.getSingleLine(g,f,p);f=this.getSingleLine(g,f,a);p=this.getSingleLine(y,1,p);H-=2;g+=d;for(var ha=0;ha<H;ha++)f=(y=l[ha+g])?f+("\r\n"+y.join("").trimEnd()):f+"\r\n\r\n";return f+"\r\n"+p};this.toString=function(){for(var f="",g=0,p=l.length;g<p;g++)l[g]&&(f+=l[g].join("").trimEnd()),f+="\r\n";return f}}var ia=0,ja=null,bb=!1,ya=!1;this.displayMsg=!0;this.reconnectTimes=
0;this.setTitle=this.openLink=!0;this.mode=0;this.reconnectOnResize=!0;var k=this,La=new hi5.codec["utf-8"].Decoder,Ka=new hi5.codec["utf-8"].Encoder,Ib={stream:!0};this.setCodec=function(a,b){if("string"==typeof a){if(b=hi5.codec[a])return La=new b.Decoder,Ka=new b.Encoder,!0;La=new TextDecoder(a);Ka=new hi5.codec["utf-8"].Encoder;return!1}La=a;Ka=b;return!0};this.getHistory=function(){return E.toString()};hi5.appcfg||(hi5.appcfg={img:{},toolbar:{fadable:!0},displayMsg:!0});var D=hi5.appcfg,U={on:!1,
text:"",prompt:"",cmd:"",process:function(){var a=U.cmd.indexOf(" "),b=U.cmd.substring(a+1);a=b.lastIndexOf(".");var e="";if(-1!=a)switch(b.substring(a+1).toLowerCase()){case "jpe":case "jpg":case "jpeg":e="image/jpeg";break;case "gif":e="image/gif";break;case "bmp":e="image/bmp";break;case "svg":e="image/svg+xml";break;case "png":e="image/png";break;case "webp":e="image/webp";break;case "ico":e="image/x-icon"}a="data:"+(e||"application/octet-stream")+";base64,"+U.text;U.text="";k.showMessage(e?{msg:'<img src="'+
a+'" style="max-width:100%"/>'}:{msg:'<a download="'+b+'" href="'+a+'" target="_blank">'+b+"</a>"})}};void 0!=D.reconnectOnResize&&(this.reconnectOnResize=D.reconnectOnResize);var Va="object"==typeof h?h:null,rb="object"==typeof h||0<h.indexOf("/PLAY?");rb?(this.mode=1,Va&&(h=""),h+="&touchpad=on"):0<h.indexOf("/JOIN?")&&(this.mode=2,this.reconnectOnResize=!1);var u=hi5.tool.queryToObj(h.substring(h.indexOf("?")+1));u.keyfile&&u.keyfile.startsWith("-----BEGIN")&&(D.wsPost=!0);u.color||(u.color=32);
u.fontFamily||(u.fontFamily='"Courier New"');var X=z(u.mapClipboard)?document.getElementById("copytextarea"):null,E=null;X&&(X.value="");var Ca={download:"/DOWNLOAD?",clipboard:"/CLIP?"};this.setLinks=function(a){a.download&&(Ca.download=a.download);a.clipboard&&(Ca.clipboard=a.clipboard)};this.server=u.server;this.port=parseInt(u.port,10);this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:!0,trueColor:!0};var C=null,F=!1,xa=!1,Wa=0,Ba="",V=0,J=null;D.copyDialog=!0;var w=0,A=0,v=0,
n=18,db=0,Ja="#000 #cd0000 #00cd00 #cdcd00 #0000ee #cd00cd #00cdcd #e5e5e5".split(" "),lb="#7f7f7f #ff0000 #00ff00 #ffff00 #5c5cff #ff00ff #00ffff #ffffff".split(" "),pa=Ja,I=u.fgColor||pa[7],K=u.bgColor||pa[0],Sa=0,ta=!0;u.wraparoundMode&&(ta=z(u.wraparoundMode));var Z=1,Q=24,Da=0,Xa=!0,na=document.getElementById("cursorID"),R=0,O=0,M=0,ba=null;window.$ssh=this;var oa=new function(a){var b=0,e=0,c=new Uint8Array(a),d=this,l=new $a(0,null,0);this.needMore=!1;this.release=function(){d=c=l=null};this.getHandler=
function(){return l};this.getData=function(){return c};this.getPosition=function(){return b};this.setPosition=function(t){b=t};this.getEnd=function(){return e};this.has=function(t){return e-b>=t};this.set=function(t){var f=t.length,g=e-b;if(1>g)e=f,c=t;else{var p=c.subarray(b,e);e=g+f;f=new Uint8Array(e);f.set(p);f.set(t,g);c=f}b=0};this.handle=function(){l.handler(d,l)};this.setHandler=function(t){t&&1>t.need&&svGlobal.logger.warn("need < 1");(l=t)&&e-b>=t.need&&t.handler(d,t)};this.getByte=function(){return c[b++]};
this.peekByte=function(){return c[b]};this.getBE32=function(){return c[b++]<<24|c[b++]<<16|c[b++]<<8|c[b++]};this.getBE16=function(){return c[b++]<<8|c[b++]};this.skip=function(t){b+=t};this.skipBack=function(t){b-=t};this.getBytes=function(t,f){if(f)for(var g=0;g<t;g++)f[g]=c[b++];else return f=b,b+=t,c.subarray(f,b)};this.copyToByteArray=function(t,f,g,p){hi5.Arrays.arraycopy(c,g,t,f,p)}}(4194304),Jb={l:"\u250c",k:"\u2510",m:"\u2514",j:"\u2518",q:"\u2500",x:"\u2502",n:"\u253c","~":"\u2022",u:"\u2524",
t:"\u251c",v:"\u2534",w:"\u252c"};this.__que=oa;this.running=function(){return F};this.setColorTable=function(a){Ja=a};this.setColorTableBright=function(a){lb=a};this.loadbalanceToken="";D.loadbalanceTokenName&&u[D.loadbalanceTokenName]&&ca(u[D.loadbalanceTokenName]);this.mapCmdToCtrl=!0;var B=null;r||(r=window.innerWidth);u.width=r;h+="&width="+r;m||(m=window.innerHeight);u.height=m;h+="&height="+m;x=(x=x||u.fontSize)?parseInt(x):13;u.fontSize?(x=parseInt(u.fontSize,10),u.fontSize=x):(u.fontSize=
x,h+="&fontSize="+x);var Ra,aa=window.OffscreenCanvas?new OffscreenCanvas(r,m):document.createElement("canvas"),q;this.modifyURL=function(a){k.loadbalanceToken&&(a+="&"+k.loadbalanceToken);return a};this.__write=Pa;this.getFileUrl=function(a){var b=Y(),e=Ca.download,c=e.indexOf("://");b=(0<c&&11>c?e:b+e)+"s="+Ba+"&f="+a;return k.modifyURL(b)};this.listFiles=function(a,b){J&&J.list(a,b)};this.reconnect=function(a,b){Ea(a,b);B.send("ED"+O+"\t"+R+"\t"+r+"\t"+m)};var S=new function(a){this.setJoinMode=
a.setJoinMode;this.requestControl=a.requestControl;this.writeKeyComb=a.writeKeyComb;this.localLockFlags=0;this.checkLockFlags=!0;this.getAppMode=function(){return a.mode};this.send=function(e){"891"!=e&&F&&a.__write(e)};this.sendInput=function(e){a.writeRawInput(e);if(a.onactivity)a.onactivity(e)};var b=null;this.getAppInfo=function(){return a.sessionInfo.appInfo};this.onresize=function(e){if(e=e.target.svSurface){e=e.getFreeSpace();var c=e.width,d=e.height;hi5.browser.isTouch||Math.abs(r-c)<v&&Math.abs(m-
d)<n||!a.reconnectOnResize||!F||(b&&(clearTimeout(b),b=null),b=setTimeout(function(){Ea(c,d);B.send("ED"+O+"\t"+R+"\t"+r+"\t"+m)},333))}};this.onorientationchange=function(e){};this.getClipData=wb;this.getShareFiles=a.listFiles;this.getFile=function(e){var c=a.getFileUrl(e);a.ondownload&&a.ondownload({fileName:e,url:c})||window.open(c)};this.getFileLink=a.getFileUrl;this.getGateway=function(){return h};this.reconnect=function(e,c,d){};this.sendKeyboardSyncFlags=function(e){return F?(this.remoteLockFlags=
this.localLockFlags=e,!0):!1};this.setWorkDir=function(e,c){c&&a.writeText("cd "+c+"\n")}}(this);void 0!=D.displayMsg?this.displayMsg=D.displayMsg:D.displayMsg=this.displayMsg;void 0!=D.reconnectTimes&&(this.reconnectTimes=D.reconnectTimes);void 0!=D.openLink&&(this.openLink=D.openLink);void 0!=D.setTitle&&(this.setTitle=D.setTitle);"boolean"==typeof D.useWSS&&(h=(D.useWSS?"wss":"ws")+h.substring(h.indexOf("://")));this.getURL=function(){return h};var Kb=parseInt(u.server_bpp||u.color||24);this.getColor=
function(){return Kb};this.getDisplayName=Ga;this.run=function(){if(!F){if(Va)B=Va,Qa();else{cb();var a=h+="&cols="+O+"&rows="+R;hi5.browser.binaryWS()&&(a+="&binary=on");var b=window.opener;if(b){var e=null;try{e=b.__sparkUser}catch(c){}e&&(b=e.account,e=e.session,b&&(a+="&account="+b),e&&(a+="&session="+e))}h=a+("&pasteCap="+(hi5.browser.isChrome&&hi5.browser.isDesktop?3:0));a=0==k.mode&&D.wsPost?h.substring(0,h.indexOf("?"))+"?_METHOD=post":h;a=k.modifyURL(a);(e=hi5.browser.cookie.get("__SV_TOKEN_A"))&&
(a+="&__SV_TOKEN_A="+encodeURIComponent(e));B=new WebSocket(a,"ssh");B.binaryType="arraybuffer"}B.onopen=Eb;void 0!=u.recording&&"on"==u.recording&&xb(u);B.onmessage=function(c){c=c.data;if("string"!=typeof c){var d=new Uint8Array(c);null!=ba&&ba.add(new RecordingObj(d,0,c.byteLength));oa.set(d);oa.handle()}else{var l=parseInt(c.substring(0,2),16);d=c.substring(2);switch(l){case 0:c=h.substring(h.indexOf("?")+1);B.send("00"+c);B.send("87"+navigator.userAgent);break;case 15:c=JSON.parse(d);B.send("8D");
if(k){k.sessionInfo.protocolVersion=c.protocolVersion;if(k.onready)k.onready();if(k.onloggedin)k.onloggedin();D.pingInterval&&k.startPing(D.pingInterval);J&&(J.enabled=!0)}sa(!1);break;case 26:c=JSON.parse(d);if(c.name){svGlobal.logger.info("msg="+d);if(k.onerror)k.onerror(c);d=__svi18n.errorCode["S"+c.name]||"";d+=c.message||c.msg;k.showMessage(d)}else 0<svGlobal.log&&console.erro("No error code for message:"+d);break;case 27:0!=D.drawLicense&&C.drawLicense(d);break;case 56:c=JSON.parse(d);Ba=c.session;
ca(c.appId);c.server||(c.server=Ga());if(d=hi5.$("joinSelect"))d.value=c.joinMode;if(d=hi5.$("requestControl"))d.disabled=c.hasControl;d=Db("joinssh.html")+"?id="+c.numericId;d=k.modifyURL(d);var t=c.webAddress;t&&0<t.length&&(l=t.indexOf("://"),t=t.substring(l+3),l=t.indexOf("/"),0<l&&(t=t.substring(0,l)),t.toLowerCase()!=location.host.toLowerCase()&&(d+="&gateway="+t));c.joinLink=d;k.sessionInfo.appInfo=c;c.ver&&c.ver!=svGlobal.version&&svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+
c.ver);Qa();if(k&&k.onsessionstart)k.onsessionstart(k.sessionInfo);break;case 58:if(J)if(c=parseInt(d.charAt(0),10),d=d.substring(1),5==c)J.notifyFiles(JSON.parse(d));else switch(d=d.split("\t"),c){case 1:J.confirmId(d[0],d[1],d[2]);break;case 2:J.read(d[0],parseInt(d[1],10),parseInt(d[2],10));break;case 4:J.close(d[0]);break;case 9:c='<a href="'+d[0]+'" download="'+d[1]+'" target="_blank">'+__svi18n.info.fileReady+"</a>",surfaces.getFocused().showMessage({msg:c,title:__svi18n.info.download})}break;
case 59:c=hi5.Base64.dec(d,0);Wa=c[3]<<24|c[2]<<16|c[1]<<8|c[0];Wa&64&&k.showMessage(__svi18n.info.recording);C.setFeature(Wa);break;case 61:c=JSON.parse(d);switch(c.type){case 0:u.fontSize=parseInt(c.fontSize);r=c.width;m=c.height;Qa();C.setAutoScale(!0);Ea(0,0,O,R);if(d=c.server)k.server=c.server,Za(Ga());(d=c.mapDisk)&&qb(C);sa(!1);sb=c.length;if(k.onopened)k.onopened(c);break;case 1:c=c.duration;if(k.onprogress)k.onprogress(c,sb);break;case 2:2==c.status?F=!0:((eb=d=0==c.status)||da(),c.warn&&
k.showMessage(d?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed))}break;case 62:Cb(d);break;case 91:xa=!0;if(k.onusername)k.onusername(Bb);else ea(__svi18n.info.user||d),ka=!0,da(),ra();break;case 93:G=JSON.parse(d);if(k.onauthprompt)k.onauthprompt(G,Ab);else c=G.name||"",G.instruction&&(c+=G.instruction),c&&(A+=n,w=0,ea(c),ra()),G.answer=[],ab();break;default:svGlobal.logger.warn("@TODO:"+c+"\n")}}};B.onclose=Ha;B.onerror=Fb;Za(Ga())}};this.setJoinMode=function(a){F&&B.send("8E1"+a)};this.refuseControl=
function(a){F&&B.send("8E3"+a)};this.giveControl=function(a){F&&B.send("8E4"+a)};this.requestControl=function(){F&&B.send("8E2")};this.play=function(){B.send("F3")};this.pause=function(){B.send("F2")};this.scan=function(a){B.send("F4"+(a?"1":"0"))};this.seek=function(a){C&&F&&B.send("F4"+(a?"1":"0")+"\t"+(a/C.getScale().x|0))};this.allowJoin=function(a,b){B.send("8EA"+a+"\t"+(b?1:0))};var W=null,ka=!1,G=null,fa="",sb=0;this.hide=function(){C&&(sa(!0),C.hide())};this.showMessage=function(a,b){k.displayMsg&&
a&&(C?C.showMessage(a,b):("string"==typeof a&&(a={msg:a,timeout:b||0}),hi5.notifications.notify(a)))};this.close=function(){if(B&&F)try{B.send("85"),B.close()}catch(a){}else Ha()};hi5.browser.isChromeApp?chrome.runtime.onSuspend.addListener(Ha):window.addEventListener("unload",Ha,!1);var Lb=new $a(1024,function(a){var b=w,e=A;for(a.needMore=!1;a.has(1);){var c=a.getByte();if(31>=c)if(27==c){a:{var d=a;if(d.has(1)){c=d.getByte();switch(c){case 40:c=d.getByte();svGlobal.logger.info("G0 Character Set start:"+
String.fromCharCode(c));48==c?(ya=!0,svGlobal.logger.info("Line drawing mode on")):(svGlobal.logger.info("Line drawing mode off"),ya=!1);break;case 41:c=d.getByte();ya=!1;svGlobal.logger.info("G0 Character Set canel: "+String.fromCharCode(c));break;case 55:svGlobal.logger.info("save_cursor");break;case 61:svGlobal.logger.info("TODO: Enter alt keypad mode");break;case 62:svGlobal.logger.info("TODO: Enter keypad mode");break;case 68:kb();break;case 69:hb();A+=n;ua(!0);break;case 77:jb();break;case 92:svGlobal.logger.info("ST");
break;case 93:c=svGlobal.logger;for(var l=c.info,t=d,f=t.getPosition(),g="",p=t.getEnd(),y=t.getData();f<p;)if(d=y[f++],7!=d)switch(d>>4){case 0:case 1:case 2:case 3:case 4:case 5:case 6:case 7:g+=String.fromCodePoint(d);break;case 12:case 13:g+=String.fromCodePoint((d&31)<<6|y[f++]&63);break;case 14:g+=String.fromCodePoint((d&15)<<12|(y[f++]&63)<<6|(y[f++]&63)<<0)}else break;t.setPosition(f);l.call(c,"OSC:"+g);break;case 91:c=Gb(d);break a;case 99:svGlobal.logger.info("full reset");fb();break;default:svGlobal.logger.warn("unkown cmd for ESC:"+
c)}c=!0}else d.skipBack(1),c=!1}if(!c)return}else gb(c);else if(128<=c&&159>=c)switch(c){case 146:a.skip(2);break;default:svGlobal.logger.warn("C1:"+c)}else{a.skipBack(1);c=a;l=c.getPosition();t=c.getEnd();f=c.getData();for(g=l;l<t;)if(d=f[l++],31>=d){l--;break}c.setPosition(l);if(l>g){if(c=f.subarray(g,l),c=La.decode(c,Ib),ya)for(l=c.split(""),c="",d=0,t=l.length;d<t;d++)f=l[d],c+=Jb[f]||f}else c="";ea(c);if(a.needMore)return}}b==w&&e==A||ra();da();ja&&ja.check()});oa.setHandler(Lb);var eb=!1;this.refreshOutput=
da;var N={mode:0,parameters:[0],count:0,trailing:0,command:0,toString:function(){var a="CSI, ";this.mode&&(a+="mode:"+String.fromCharCode(this.mode));0<this.count&&(a+=" parameters:"+this.parameters.slice(0,this.count).join(";"));this.trailing&&(a+=" trailing:"+String.fromCharCode(this.trailing));return a+=" cmd:"+String.fromCharCode(this.command)},parse:function(a){var b=0,e=!1,c=a.getByte();if(!c)return!1;if(60<=c&&63>=c)this.mode=c,c=a.getByte();else if(this.mode=0,31>=c||128<=c&&159>=c)gb(c),
c=a.getByte();if(!c)return!1;for(this.count=0;48<=c&&57>=c||59==c;)if(59==c?(this.parameters[this.count]=e?b:null,this.count++,b=0,e=!1):(b=10*b+(c-48),e=!0),c=a.getByte(),!c)return!1;e?(this.parameters[this.count]=b,this.count++):0<this.count&&(this.parameters[this.count]=1,this.count++);if(32<=c&&47>=c){if(this.trailing=c,c=a.getByte(),!c)return!1}else this.trailing=0;64<=c&&127>=c?this.command=c:(this.command="",svGlobal.logger.warn("Invalid CSI final char:"+String.fromCharCode(c)));return!0}};
if(X){var tb=document.getElementById("svHistory");tb&&(tb.onclick=pb)}this.showHistory=pb;this.getUploadManager=function(){return J};this.addSurface=function(a){C=a;rb&&a.setPlayerMode();Ra=C.context;Ra.fontKerning="none";aa.width=r;aa.height=m;q=aa.getContext("2d",{alpha:!1});q.fontKerning="none";a.alwaysPaste=!0;a.setAutoScale(0<k.mode);a.setSize(r,m);a.setController(S);a.setTouchpad(z(u.touchpad));a.setClipboard(z(u.mapClipboard));qb(C);var b=void 0!=u.cmdToCtrl?z(u.cmdToCtrl):void 0!=D.cmdToCtrl?
D.cmdToCtrl:k.mapCmdToCtrl;a.run(99997,!1,!0,b);a.onclipdata=ob};this.sendPing=function(a){a=new Uint8Array(2);a[0]=146;Pa(a.buffer)};this.startPing=function(a){ja||(ja=new hi5.tool.ResponseMonitor(function(){xa&&k.sendPing()},function(){xa&&ja.check(1)}));ja.setInterval(a,a);setTimeout(function(){ja.check()},1E3*a)};this.stopPing=function(){ja&&ja.stop()};this.writeText=L;this.writeScancode=function(a,b){L(qa.process(a,b,0))};var Mb={" ":57,space:57,pageup:201,pagedown:209,end:207,home:199,left:203,
up:200,right:205,down:208,printscreen:183,insert:210,del:211,"delete":211,altgr:184,windows:219,windowsright:220,context:221,esc:1,backspace:14,tab:15,enter:28,meta:29,command:29,ctrl:29,shift:42,alt:56,capslock:58,f1:59,f2:60,f3:61,f4:62,f5:63,f6:64,f7:65,f8:66,f9:67,f10:68,f11:87,f12:88,numlock:69,scrolllock:70,add:78};this.writeKeyComb=function(a){a=a.split("+");var b=a.length;if(0!=b)for(var e=null,c=0;c<b;c++){var d=a[c];""==d&&""==e&&(d="Add");if(""!=d){e=d;var l=Mb[e.toLowerCase()];l?k.writeScancode(!0,
l):svGlobal.logger.warn("Invalid key:"+e)}e=d}};var Ma=!1,la=0,ma=0,Na=0,va=!1,ub=0,vb=0,wa=null;this.writeRawInput=function(a){if(F){var b=parseInt(a.substring(0,2),16);a=a.substring(2).split("\t");switch(b){case 128:la=parseInt(a[0]);ma=parseInt(a[1]);Na=parseInt(a[2]);va=!1;Ma=!0;ub=Math.floor(la/v)*v;vb=Math.floor(ma/n)*n;1015==V?L("\u001b["+(parseInt(a[2])+32)+";"+(Math.floor(la/v)+1)+";"+(Math.floor(ma/n)+1)+"M"):1006==V?L("\u001b[<"+a[2]+";"+(Math.floor(la/v)+1)+";"+(Math.floor(ma/n)+1)+"M"):
V&&L("\u001b[M"+a[2]+String.fromCharCode(Math.floor(la/v)+33)+String.fromCharCode(Math.floor(ma/n)+33));return;case 129:V&&(1015==V?L("\u001b["+(parseInt(a[2])+32)+";"+(Math.floor(la/v)+1)+";"+(Math.floor(ma/n)+1)+"M"):1006==V?L("\u001b[<"+a[2]+";"+(Math.floor(parseInt(a[0])/v)+1)+";"+(Math.floor(parseInt(a[1])/n)+1)+"m"):V&&L("\u001b[M3"+String.fromCharCode(Math.floor(parseInt(a[0])/v)+33)+String.fromCharCode(Math.floor(parseInt(a[1])/n)+33)));Na=parseInt(a[2]);2==Na&&Ma&&!va?(X&&(X.value=""),C.processClipReq("text/plain",
Hb)):va&&(a=E.getMultiLines(Math.floor(la/v)+1,Math.floor(ma/n+.1)+1,Math.floor(parseInt(a[0])/v+.4)+1,Math.floor(parseInt(a[1])/n-.4)+1))&&C&&C.copyToClip("text/plain;"+a);wa&&(setTimeout(C.removeWhiteboard,333),wa=null);va=Ma=!1;return;case 130:if(Ma){b=parseInt(a[0]);a=parseInt(a[1]);if(!va){if(3>Math.abs(b-la)&&3>Math.abs(a-ma))return;va=!0}if(0==Na){if(!wa){var e=C.initWhiteboard();e.style.opacity=.6;e=e.getContext("2d");wa=new hi5.canvas.TextSelect(e,n,D.selectionColor,"1px",r)}wa.clear();wa.draw(ub,
vb,b,a)}}return;case 131:1006==V?L("\u001b[<"+("1"==a[2]?65:64)+";"+(Math.floor(parseInt(a[0])/v)+1)+";"+(Math.floor(parseInt(a[1])/n)+1)+"M"):V&&L("\u001b[M"+("1"==a[2]?5:4)+String.fromCharCode(Math.floor(parseInt(a[0])/v)+64)+String.fromCharCode(Math.floor(parseInt(a[1])/n)+64));return;case 132:e=0==a[0];b=parseInt(a[1]);if(ka||G)e&&(a=b,28==a||156==a?(A+=n,w=0,ka?(ka=!1,B.send("5B"+fa),fa=""):G&&(G.answer.push(fa),fa="",ab())):14==a&&0<fa.length&&(fa=fa.substring(0,fa.length-1),ka&&(Ta(),ea(" "),
da(),Ta())));else if(L(qa.process(e,b,0)),28!=b)ia||(ia=T());else if(ia){if(ia&&(a=E.getSingleLine(P(),ia,T()))){b=E.getSingleLine(P(),1,ia);if(k.oncommand)k.oncommand(a,b);a.startsWith("cd /")?C.setDirectory(a.substring(3)):a.startsWith("base64 ")&&(U.on=!0,U.cmd=a,U.prompt=b)}ia=0}return;case 139:b=parseInt(a[1]);e=0==a[0];L(qa.process(e,b,1));return;case 134:ka||G?nb(a[0]):(ia||(ia=T()),L(qa.process(!0,a[0],3)));return}svGlobal.logger.warn("Unknowncode: "+a[1]+" type:"+b)}};var qa=new function(){var a=
!1,b=!1,e=!1,c=0;this.setAltDown=function(d){b=d};this.setCtrlDown=function(d){a=d};this.setEscMode=function(d){c=d;svGlobal.logger.info("Esc mode:"+d)};this.process=function(d,l,t){if(3==t)return l;if(0==t){switch(l){case 29:case 157:return a=d,"";case 56:case 184:return b=d,"";case 42:case 54:return e=d,""}if(d){switch(l){case 28:d="\r";break;case 200:d=0==c?"\u001b[A":1==c?"\u001bOA":"\u001bA";break;case 208:d=0==c?"\u001b[B":1==c?"\u001bOB":"\u001bB";break;case 205:d=0==c?"\u001b[C":1==c?"\u001bOC":
"\u001bC";break;case 203:d=0==c?"\u001b[D":1==c?"\u001bOD":"\u001bD";break;case 59:d="\u001bOP";break;case 60:d="\u001bOQ";break;case 61:d="\u001bOR";break;case 62:d="\u001bOS";break;case 63:d="\u001b[15~";break;case 64:d="\u001b[17~";break;case 65:d="\u001b[18~";break;case 66:d="\u001b[19~";break;case 67:d="\u001b[20~";break;case 68:d="\u001b[21~";break;case 87:d="\u001b[23~";break;case 88:d="\u001b[24~";break;case 15:d="\t";break;case 209:d="\u001b[6~";break;case 201:d="\u001b[5~";break;case 199:d=
0==c?"\u001b[H":"\u001bOH";break;case 207:d=0==c?"\u001b[F":"\u001bOF";break;case 14:d=e?"\b":"\u007f";break;case 211:d="\u001b[3~";break;case 197:d="\u00ff\u00f3";break;case 210:d="\u001b[2~";break;case 1:d="\u001b";break;case 55:d="*";break;case 71:d=S.localLockFlags&2?"7":0==c?"\u001b[H":"\u001bOH";break;case 72:d=S.localLockFlags&2?"8":0==c?"\u001b[A":"\u001bOA";break;case 73:d=S.localLockFlags&2?"9":"\u001b[5~";break;case 74:d="-";break;case 75:d=S.localLockFlags&2?"4":0==c?"\u001b[D":"\u001bOD";
break;case 76:d=S.localLockFlags&2?"5":"\u001bOu";break;case 77:d=S.localLockFlags&2?"6":0==c?"\u001b[C":"\u001bOC";break;case 78:d="+";break;case 79:d=S.localLockFlags&2?"1":0==c?"\u001b[F":"\u001bOF";break;case 80:d=S.localLockFlags&2?"2":0==c?"\u001b[B":"\u001bOB";break;case 81:d=S.localLockFlags&2?"3":"\u001b[6~";break;case 82:d=S.localLockFlags&2?"0":"\u001b[2~";break;case 83:d=S.localLockFlags&2?".":"\u001b[3~";break;case 156:d="\r";break;case 181:d="/";break;default:return svGlobal.logger.warn("Invalid code:"+
l),""}b&&(d="\u001b"+d);return d}return""}if(1==t&&d)if(a){if(64<l&&91>l)return String.fromCharCode(l-64);switch(l){case 54:return"\u001e";case 219:return"\u001b";case 220:return"\u001c";case 221:return"\u001d";case 32:return"\x00";case 192:return"\u001e";case 191:return"\u001f";default:return svGlobal.logger.warn("Invalid key code:"+l),""}}else if(b)return"\u001b"+String.fromCharCode(l).toLowerCase()}}};
