var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(l,q,v){if(null==l)throw new TypeError("The 'this' value for String.prototype."+v+" must not be null or undefined");if(q instanceof RegExp)throw new TypeError("First argument to String.prototype."+v+" must not be a regular expression");return l+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(l,q,v){if(l==Array.prototype||l==Object.prototype)return l;l[q]=v.value;return l};
$jscomp.getGlobal=function(l){l=["object"==typeof globalThis&&globalThis,l,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var q=0;q<l.length;++q){var v=l[q];if(v&&v.Math==Math)return v}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(l,q){var v=$jscomp.propertyToPolyfillSymbol[q];if(null==v)return l[q];v=l[v];return void 0!==v?v:l[q]};$jscomp.polyfill=function(l,q,v,F){q&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(l,q,v,F):$jscomp.polyfillUnisolated(l,q,v,F))};
$jscomp.polyfillUnisolated=function(l,q,v,F){v=$jscomp.global;l=l.split(".");for(F=0;F<l.length-1;F++){var E=l[F];if(!(E in v))return;v=v[E]}l=l[l.length-1];F=v[l];q=q(F);q!=F&&null!=q&&$jscomp.defineProperty(v,l,{configurable:!0,writable:!0,value:q})};
$jscomp.polyfillIsolated=function(l,q,v,F){var E=l.split(".");l=1===E.length;F=E[0];F=!l&&F in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var B=0;B<E.length-1;B++){var N=E[B];if(!(N in F))return;F=F[N]}E=E[E.length-1];v=$jscomp.IS_SYMBOL_NATIVE&&"es6"===v?F[E]:null;q=q(v);null!=q&&(l?$jscomp.defineProperty($jscomp.polyfills,E,{configurable:!0,writable:!0,value:q}):q!==v&&($jscomp.propertyToPolyfillSymbol[E]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(E):$jscomp.POLYFILL_PREFIX+E,E=
$jscomp.propertyToPolyfillSymbol[E],$jscomp.defineProperty(F,E,{configurable:!0,writable:!0,value:q})))};$jscomp.polyfill("String.prototype.startsWith",function(l){return l?l:function(q,v){var F=$jscomp.checkStringArgs(this,q,"startsWith");q+="";var E=F.length,B=q.length;v=Math.max(0,Math.min(v|0,F.length));for(var N=0;N<B&&v<E;)if(F[v++]!=q[N++])return!1;return N>=B}},"es6","es3");
$jscomp.polyfill("String.prototype.endsWith",function(l){return l?l:function(q,v){var F=$jscomp.checkStringArgs(this,q,"endsWith");q+="";void 0===v&&(v=F.length);v=Math.max(0,Math.min(v|0,F.length));for(var E=q.length;0<E&&0<v;)if(F[--v]!=q[--E])return!1;return 0>=E}},"es6","es3");$jscomp.findInternal=function(l,q,v){l instanceof String&&(l=String(l));for(var F=l.length,E=0;E<F;E++){var B=l[E];if(q.call(v,B,E,l))return{i:E,v:B}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(l){return l?l:function(q,v){return $jscomp.findInternal(this,q,v).v}},"es6","es3");var svGlobal=svGlobal||{logger:new hi5.Logger,util:{}};svGlobal.version="6.4.0";svGlobal.build="1076";function cancelDefault(l){l.preventDefault&&l.preventDefault();l.stopPropagation&&l.stopPropagation();return!1}
function LocalInterface(l,q){function v(a){var c=a-hi5.browser.innerHeight;10<c&&22>c&&(a=hi5.browser.innerHeight);return a}function F(a){x.detectInput&&Z&&ka&&(Ja||"text"==ka.system||"none"==ka.system?setTimeout(function(){hb(!0)},5):setTimeout(function(){hb(!1)},5));if(document.activeElement!=a||!p.focused){for(var c=a,d,b=[];c.parentElement;)if(c=c.parentElement,d=getComputedStyle(c))d.getPropertyValue("overflow"),"block"==d.getPropertyValue("display")&&b.push([c,c.scrollTop,c.scrollLeft]);a.focus();
if(b.length){a=0;for(d=b.length;a<d;a++){c=b[a];if(c[0].scrollTop!=c[1]||c[0].scrollLeft!=c[2])c[0].scrollTop=c[1],c[0].scrollLeft=c[2];b[a]=null}b=null}}}function E(){var a=[];this.sent=0;this.types=[];var c=this;this.datas=a;this.setData=function(d,b){if("text/plain"==d||"text/html"==d)2<b.length&&"`\t`"==b.substring(0,3)&&(b=b.substring(3)),b=b.replace(/\r?\n/g,"\r\n");c.types.push(d);a.push(b)};this.getData=function(d){var b=a[c.types.indexOf(d)];b||"text/richtext"!=d||(b=a[c.types.indexOf("text/rtf")]);
return b};this.removeData=function(d){d=c.types.indexOf(d);-1!=d&&(c.types.splice(d,1),a.splice(d,1))};this.equals=function(d){if(!d||!hi5.Arrays.equals(c.types,d.types))return!1;for(var b,h,f=c.types,k=0,m=f.length;k<m;k++)if(b=f[k],h=c.getData(b),b=d.getData(b),h!=b)return!1;return!0}}function B(){ib=!0;Ka=!1;if(z){var a=z.element;a.removeEventListener("copy",y.onCopy,!1);a.removeEventListener("cut",y.onCopy,!1)}svGlobal.logger.info("Async clipboard enabled.")}function N(a){function c(){return n?
a.value:C.isFirefox?a.textContent:a.innerText}function d(){e&&(g="",e.setValue(""))}function b(G){u=G.keyCode;if(e.onkeydown)e.onkeydown(G)}function h(G){if(e.onkeyup)e.onkeyup(G);G=G.keyCode;(13==G||32==G&&32==u)&&setTimeout(d,100)}function f(G){if(e.onbackspace)for(var Q=0;Q<G;Q++)e.onbackspace()}function k(G){if(!e.disableTextInput){G.stopPropagation();G=c();var Q=G.length;if(G!=g){var aa=g.length,S=G.indexOf(g);if(G&&0===S){if(G=G.substring(aa),0<G.length&&e.ontextinput&&(e.ontextinput({data:G,
target:a}),"."==G)){d();return}}else if(S=g.indexOf(G),0===S)8!=u&&f(aa-Q);else if(C.isAndroid&&f(aa),0<G.length&&e.ontextinput)e.ontextinput({data:G,target:a});""===c()&&setTimeout(d,100);g=c()}}}function m(G){if(!e.disableTextInput&&G.data&&(G.stopPropagation(),C.isIE&&G.preventDefault(),e.ontextinput))e.ontextinput(G)}function t(G){if(e.oncomposition)e.oncomposition(G)}this.unicode=!1;var e=this,g="",u=0,n="INPUT"==a.nodeName||"TEXTAREA"==a.nodeName,J="DIV"==a.nodeName;this.setValue=function(G){var Q=
e.disableTextInput;e.disableTextInput=!0;n?a.value=G:J&&(a.innerHTML=G);e.disableTextInput=Q};this.init=d;this.disableTextInput=!1;d();a.addEventListener("keydown",b,!1);a.addEventListener("keyup",h,!1);a.addEventListener("keypress",function(G){if(e.onkeypress)e.onkeypress(G)},!1);C.isAndroid&&C.isChrome?(a.addEventListener("input",k,!1),a.addEventListener("mouseup",d,!1)):window.TextEvent?(a.addEventListener("textInput",m,!1),a.addEventListener("textinput",m,!1)):hi5.tool.hasProperty(InputEvent,
"data")?a.addEventListener("input",m,!1):(a.addEventListener("input",k,!1),a.addEventListener("mouseup",d,!1));a.addEventListener("compositionstart",t,!1);a.addEventListener("compositionend",t,!1);a.addEventListener("compositionupdate",t,!1);this.release=function(){e=null;a.removeEventListener("keydown",b,!1);a.removeEventListener("keyup",h,!1);a.removeEventListener("input",k,!1);a.removeEventListener("focus",d,!1);a.removeEventListener("textInput",m,!1);a.removeEventListener("textinput",m,!1);a=
null};this.select=function(){zb(a)}}function ba(a,c,d){var b=0,h=0;a.addEventListener("wheel",function(f){var k=Va(f);var m=f.deltaMode||0;var t=!!f.deltaX||!!f.wheelDeltaX;f.preventDefault();f.stopPropagation();var e=1==m?1:"deltaY"in f?40:"wheelDelta"in f?120:0;if(e){var g=Date.now();100<g-h&&(b=0);f=-f.deltaY||-f.deltaX||f.wheelDelta;3==m&&(f*=24*e);0!=f&&(b+=f,m=b/e|0,b%=e,0!==m&&c(m,k,t));h=g}else m=-f.detail,32768==Math.abs(m)&&(f=window.innerHeight/40|0,m=0>m?-f:f),c(m,k,!1)},!0)}function pa(a){function c(e){if(!k&&
m.onmousedown)m.onmousedown(e)}function d(e){if(!k&&m.onmousemove)m.onmousemove(e)}function b(e){if(p&&p.focused)if(k)k=!1;else if(m.onmouseup)m.onmouseup(e)}function h(e){if(x.releaseOnMouseOut)for(e=0;5>e;e++)A.mouseDown[e]&&(La("81",A.x+"\t"+A.y+"\t"+e),A.mouseDown[e]=!1)}function f(e){"touchstart"==e.type&&(k=!0);if(m.ontouch)m.ontouch(e)}var k=!1,m=this,t=navigator.pointerEnabled||navigator.msPointerEnabled||!1;"ontouchstart"in window||!t?(a.addEventListener("touchstart",f,!1),a.addEventListener("touchend",
f,!1),a.addEventListener("touchmove",f,!1),a.addEventListener("touchcancel",f,!1),document.addEventListener("mousemove",d,!1),a.addEventListener("mousedown",c,!1),a.addEventListener("mouseout",h,!1),document.addEventListener("mouseup",b,!1)):navigator.pointerEnabled?(a.addEventListener("pointerdown",f,!1),a.addEventListener("pointerup",f,!1),a.addEventListener("pointermove",f,!1),a.addEventListener("pointerout",h,!1),a.addEventListener("pointercancel",f,!1)):navigator.msPointerEnabled&&(a.addEventListener("MSPointerDown",
f,!1),a.addEventListener("MSPointerUp",f,!1),a.addEventListener("MSPointerMove",f,!1),a.addEventListener("MSPointerCancel",f,!1));this.release=function(){"ontouchstart"in window||!t?(a.removeEventListener("touchstart",f,!1),a.removeEventListener("touchend",f,!1),a.removeEventListener("touchmove",f,!1),a.removeEventListener("touchcancel",f,!1),document.removeEventListener("mousemove",d,!1),a.removeEventListener("mousedown",c,!1),document.removeEventListener("mouseup",b,!1)):navigator.pointerEnabled?
(a.removeEventListener("pointerdown",f,!1),a.removeEventListener("pointerup",f,!1),a.removeEventListener("pointermove",f,!1),a.removeEventListener("pointercancel",f,!1)):navigator.msPointerEnabled&&(a.removeEventListener("MSPointerDown",f,!1),a.removeEventListener("MSPointerUp",f,!1),a.removeEventListener("MSPointerMove",f,!1),a.removeEventListener("MSPointerCancel",f,!1));this.onmouseup=this.onmousemove=this.ontouch=this.onmousedown=null}}function Ea(){return qa?!0:!ua&&W<=window.innerWidth&&X<=
window.innerHeight}function hc(a){function c(f,k){for(var m,t=f.length,e=Array(t),g=0;g<t;g++){m=f[g];var u=Wa(m.clientX,m.clientY,l),n=g;m=m.identifier;if(!(256>m)){var J=b.indexOf(m);-1!=J?m=J:(b.push(m),m=b.length-1)}e[n]={contactId:m,contactFlags:k,x:u.x,y:u.y}}return e}var d,b=[],h=!1;this.handle=function(f){var k=f.type,m=f.touches,t=f.changedTouches;cancelDefault(f);switch(k){case "touchstart":h=!1;d=f=c(m,25);break;case "touchmove":f=c(t,26);d||(d=c(m||t,25));m=!1;if(0<d.length&&1==f.length){a:{t=
d.length;for(k=0;k<t;k++)if(d[k].contactId==f[0].contactId){t=k;break a}t=-1}-1!=t&&d[t].x==f[0].x&&d[t].y==f[0].y&&(m=!0)}if(m)break;else 0<d.length&&(a.redirectTouches(d),d.length=0);a.redirectTouches(f);h=!0;break;case "touchend":if(h)f=c(t,4);else{a.redirectTouches(d);f=d.length;for(m=0;m<f;m++)d[m].contactFlags=4;f=d}a.redirectTouches(f);b.length=d.length=0;break;case "touchcancel":a.redirectTouches(c(t,34)),b.length=d.length=0}}}function Ab(a){function c(H){var K=H[1].screenX-H[0].screenX;H=
H[1].screenY-H[0].screenY;return Math.sqrt(K*K+H*H)}function d(H,K){for(var L=0,M=H.length;L<M;L++)if(H[L].identifier==K)return H[L];return null}function b(H){this.identifier=H.pointerId;this.clientX=H.clientX;this.clientY=H.clientY;this.pageX=H.pageX;this.pageY=H.pageY;this.screenX=H.screenX;this.screenY=H.screenY}var h=0,f=0,k=0,m=0,t=!1,e=0,g=0,u=0,n=0,J=!1,G=!1,Q=3,aa=!1;C.isIE&&(Q*=3);this.delay=!1;var S=[],Xa=this;this.handlePointer=function(H){if(H.pointerType==H.MSPOINTER_TYPE_MOUSE||"mouse"==
H.pointerType)switch(H.type){case "MSPointerDown":case "pointerdown":jb(H);break;case "pointermove":case "MSPointerMove":kb(H);break;case "pointerup":case "MSPointerUp":lb(H)}else H.touches=H.changedTouches=[new b(H)],Xa.handle(H)};this.handle=function(H){var K=H.type,L=H.touches;var M=H.changedTouches;var ca=0,da=0;switch(K){case "touchstart":case "MSPointerDown":case "pointerdown":aa=!1;f="touchstart"==K?L.length:f+1;G=!1;m=Date.now();t=1==f&&200>m-k;K=L[0];h=K.identifier;M=Wa(K.clientX,K.clientY,
l);e=M.x|0;g=M.y|0;J=!0;2!=L.length?aa=!1:(M=L[1].screenX-L[0].screenX,aa=100<Math.abs(L[1].screenY-L[0].screenY)||350<Math.abs(M));(t||1<f&&!aa)&&cancelDefault(H);if(3==f){ca=K=M=0;da=9999;for(var ma=0,mb=L.length;ma<mb;ma++)L[ma].screenY>ca&&(ca=L[ma].screenY,M=ma),L[ma].screenY<da&&(da=L[ma].screenY,K=ma);S=[{screenX:L[K].screenX,screenY:L[K].screenY,identifier:L[K].identifier},{screenX:L[M].screenX,screenY:L[M].screenY,identifier:L[M].identifier}]}break;case "pointermove":case "MSPointerMove":if(1<
f)break;case "touchmove":if(aa)return;K=M[L.length-1];if(!K)break;if(K.identifier!=h&&(K=d(M,h),!K)){cancelDefault(H);return}M=Wa(K.clientX,K.clientY,l);ca=M.x|0;da=M.y|0;if(J){if(0===ca-e&&0===da-g)return;if(Math.abs(ca-e)<Q&&Math.abs(da-g)<Q){cancelDefault(H);return}J=!1;M=Date.now()-m;if((G=88>M)&&!Ea()&&1==f){aa=!0;return}a.touchstart({x:e,y:g,flick:G,pointes:f,screenX:K.screenX,screenY:K.screenY,moved:!0,target:H.target})}cancelDefault(H);a.touchmove({x:ca,y:da,flick:G,pointes:f,moved:!0,screenX:K.screenX,
screenY:K.screenY,target:H.target});break;case "MSPointerUp":case "touchend":case "pointerup":if(aa)return;if(3==M.length+L.length){K=a.touchend;ma=G;mb=f;var ic=!J,jc=H.target;var va=[],Ya=d(L,S[0].identifier)||d(M,S[0].identifier);Ya&&va.push(Ya);(Ya=d(L,S[1].identifier)||d(M,S[1].identifier))&&va.push(Ya);L="";2==va.length&&(M=c(va)-c(S),60>Math.abs(M)?80<va[0].screenX-S[0].screenX?L="RIGHT":80<S[0].screenX-va[0].screenX?L="LEFT":80<va[0].screenY-S[0].screenY?L="DOWN":80<S[0].screenY-va[0].screenY&&
(L="UP"):L=0>M?"CLOSE":"OPEN");K.call(a,{x:ca,y:da,flick:ma,pointes:mb,moved:ic,target:jc,gesture:L});f=0;break}else{if(2<f){f=0;break}if(K=d(M,h))L=Date.now(),M=Wa(K.clientX,K.clientY,l),ca=M.x|0,da=M.y|0,G?a.touchend({x:ca,y:da,flick:!0,pointes:f,moved:!J,screenX:K.screenX,screenY:K.screenY,target:H.target}):(M=L-m,J?(k=L,t?cancelDefault(H):(u=ca,n=da),500>M?(k=L,a.touchstart({x:u,y:n,flick:!1,pointes:f,screenX:K.screenX,screenY:K.screenY,moved:!1,target:H.target}),a.touchend({x:u,y:n,flick:!1,
pointes:f,moved:!1,screenX:K.screenX,screenY:K.screenY,target:H.target})):a.longpress({x:ca,y:da,flick:!1,pointes:f,moved:!1,screenX:K.screenX,screenY:K.screenY,target:H.target})):a.touchend({x:ca,y:da,flick:!1,pointes:f,moved:!0,screenX:K.screenX,screenY:K.screenY,target:H.target}))}f=0;break;case "MSPointerCancel":case "touchcancel":f=0}t&&cancelDefault(H)}}function kc(){D(!0,14,"Backspace");D(!1,14,"Backspace")}function zb(a){try{a.select?a.select():C.selectEditable(a)}catch(c){svGlobal.logger.info(c)}}
function Bb(){function a(){h.focus()}function c(t,e){var g=document.createElement("a");g.href="#";g.accessKey=t;g.onfocus=a;g.style.position="absolute";g.style.width=1;g.style.height=1;g.style.left=0;g.style.top=e+"px";g.style.pointerEvents="none";return g}var d=p.forceTextArea||C.isIE,b=document.createElement(d?"textarea":"div"),h=this;this.element=b;this.setFontSize=function(t){b.style.fontSize=x.inputFontSize||t};d?(b.style.opacity=0,b.readOnly=Z&&C.isMetro?!0:!1):b.contentEditable=!Z||(C.isChrome||
C.isFirefox)&&(C.isWindows||C.isCrOS)?!0:!1;b.setAttribute("autocomplete",C.isChrome?"new-password":"off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.accessKey="f";b.id="wsinput";b.tabIndex=1;b.style.opacity=.01;b.style.resize="none";b.style.position="absolute";b.style.margin="0";b.style.border="none";b.style.outline="none";var f=hi5.tool.getPos(l,!0);b.style.left=f.x+"px";b.style.top=f.y+"px";b.style.paddingRight=0;b.style.paddingBottom=
0;b.style.width="10px";b.style.height="10px";b.style.zIndex=88;b.style.cursor="default";b.style.fontWeight="normal";b.style.fonStyle="normal";b.style.overflow="hidden";Z&&(b.style.fontSize="2em");C.isiOS?(b.addEventListener("focus",function(t){setTimeout(function(){t.target.style.fontSize="0px"},333)},!1),b.addEventListener("blur",function(t){t.target.style.fontSize="1em"},!1)):C.isFirefox?b.style.fontSize=0:d?b.style.fontSize="1px":C.isChrome||(b.style.textIndent="-999em");R=new N(b);R.onbackspace=
kc;f=l.parentNode;f.appendChild(b);C.isIE&&(f.appendChild(c("E"),60),f.appendChild(c("V"),61),f.appendChild(c("A"),62),f.appendChild(c("T"),63),f.appendChild(c("H"),64));var k=b.style.opacity,m=b.style.textIndent||0;this.resetCSS=function(){_fontSize=b.style.fontSize;k=b.style.opacity;b.style.opacity=.01;b.style.textIndent=0};this.restoreCSS=function(){b.style.opacity=k;b.style.textIndent=m};this.getValue=function(){return d?b.value:b.innerHTML};this.setValue=function(t){R&&(R.disableTextInput=!0);
d?b.value=t:b.innerHTML=t;R&&(R.disableTextInput=!1)};this.focus=function(){h.setValue(" ");F(b)};this.setContentEditable=function(t){d?(t="true"==t,b.readOnly==t&&(b.readOnly=!t)):b.setAttribute("contenteditable",t)};this.isIMEMode=!1;this.adjust=function(t){var e=hi5.tool.getPos(l,!0);A.offX=e.x;A.offY=e.y;var g=p.railWin?Math.min(window.innerWidth-e.x,W):W,u=p.railWin?Math.min(window.innerHeight-e.y,X):X;if(Z){var n=Math.max(window.pageXOffset+100,e.x);t=Math.max(window.pageYOffset+100,e.y)}else{var J=
Math.min(window.innerHeight-e.y,X);n=Math.round(.7*Math.min(window.innerWidth-e.x,W));t=Math.round(J*(t?.99:.7))}g-=n;u-=t;x.disableAdjust&&(t=n=0,g=l.offsetWidth,u=l.offsetHeight);b.style.width=g+"px";b.style.height=u+"px";b.style.paddingLeft=n+"px";b.style.paddingTop=t+"px";b.style.left=e.x+"px";b.style.top=e.y+"px"};this.remove=function(){R&&(R.release(),R=null);b.parentNode&&b.parentNode.removeChild(b);b=null};this.hide=function(){b.style.visibility="hidden"};this.getElement=function(){return b};
this.select=function(){zb(b)}}function Ma(a){function c(){x.text||(x.text={});return x.text}function d(e,g,u,n,J){if(f){var G=c();e.fillStyle=G.backgroundFillStyle||"white";e.fillRect(g,u-J+2,n,J);e.fillStyle=G.fillStyle||"#337788";e.textBaseline="bottom";e.fillText(f,g+3,u-2);e.strokeStyle=t.getColor(f);e.lineWidth=2;e.beginPath();e.moveTo(g,u);e.lineTo(g+n,u);e.stroke()}}function b(){var e=r.getContext("2d"),g=e.getImageData(0,0,r.cursorWidth,r.cursorHeight);if(f){e.font=c().font||"11px Arial";
var u=1.2*(e.measureText("W").width+1)+4;r.width=Math.max(r.cursorWidth,e.measureText(f).width+4);r.height=r.cursorHeight+u;d(e,0,r.height-1,r.width,u)}else r.width=r.cursorWidth,r.height=r.cursorHeight;e.putImageData(g,0,0)}if(!r){var h=l.parentNode,f="",k=0;r=h.querySelector('canvas[name="svImgCursor"]');if(!r){r=document.createElement("canvas");r.setAttribute("name","svImgCursor");r.style.position="absolute";r.style.left=90;r.style.top=90;r.scrX=0;r.scrY=0;r.hotX=0;r.hotY=0;r.width=r.height=32;
r.__left=0;r.__top=0;r.__visible=!1;r.style.visibility="hidden";r.style.zIndex=87;var m=null;x.disableClickEffect||(m=document.createElement("div"),m.className="mouse-click-off",m.style.zIndex=89);var t={getColor:function(e){if(t[e])return t[e];var g=hi5.graphic.colorTable.getNext();return t[e]=g}};r.setCursor=function(e){var g=e.width,u=e.height,n=e.rawData,J=0,G=0,Q=r.getContext("2d");f&&(Q.font=c().font||"11px Arial",J=Q.measureText(f).width,G=1.2*(Q.measureText("W").width+1)+4);if(a)if(f){if(a){r.cursorWidth=
J;r.cursorHeight=G;r.hotX=e.hotX;r.hotY=-u;r.width=J;r.height=G+4;d(Q,0,r.height-1,r.width,G);return}}else r.__setVisible(!1);if(n&&g&&u){var aa=g*u,S=0,Xa=Q.createImageData(g,u),H=Xa.data,K=e.hotX-r.hotX,L=e.hotY-r.hotY;r.cursorWidth=g;r.cursorHeight=u;r.hotX=e.hotX;r.hotY=e.hotY;r.width=Math.max(g,J+4);r.height=u+G+4;f&&d(Q,0,r.height-1,r.width,G);for(J=0;J<aa;J++)e=n[J],H[S++]=e&255,H[S++]=e>>8&255,H[S++]=e>>16&255,H[S++]=e>>24&255;Q.putImageData(Xa,0,0,0,0,g,u);r.__left-=K;r.__top-=L;r.style.left=
r.__left+"px";r.style.top=r.__top+"px"}};r.__setVisible=function(e){r.__visible=e;r.style.visibility=e?"visible":"hidden"};ka&&ka.rawData?r.setCursor(ka):r.setCursor({rawData:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,
-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,-16777216,-16777216,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,-16777216,-1,-1,-16777216,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],width:32,height:32,hotX:10,hotY:10});r.moveCursor=function(e,g,u,n,J){var G=e-r.hotX,Q=g-r.hotY;r.__left=G;r.__top=Q;r.style.left=G+"px";r.style.top=Q+"px";if(f!=u||k!=n)f=u,k=n,b();m&&J&32768&&(m.style.left=e-30+"px",m.style.top=g-30+"px",m.className="mouse-click-on",setTimeout(function(){m.className=
"mouse-click-off"},500))};h.appendChild(r);m&&h.appendChild(m)}}}function nb(a){if(!1!==x.disableScrollbars){var c=document.body;a?(ob=a,c.style.overflow=a):(ob=W<=window.innerWidth&&X<=window.innerHeight?"hidden":"visible",c.style.overflow=ob)}}function Na(a){var c=l.parentNode;document.body.style.overflow="hidden";ea=la=a?Math.min(window.innerWidth/W,window.innerHeight/X):1;hi5.tool.scale(c,ea,ea)}function pb(){if(p.toolbar)p.toolbar.removeButton("svCloud");else{var a=hi5.$("svCloud");a&&a.parentNode.removeChild(a)}}
function Cb(){var a=chrome.app.window.current();a&&a.fullscreen()}function qb(a,c){var d=document.getElementById("_tmpEditable");a||(a="div");var b=document.body;d&&d.nodeName!=a.toUpperCase()&&(b.removeChild(d),d=null);d||(d=document.createElement(a),d.id="_tmpEditable","div"==a&&!1!==c&&(d.contentEditable=!0,C.isIE&&(d.style.textIndent="-999px")),d.style.position="absolute",d.style.zIndex=9999,d.style.left=b.scrollLeft+50+"px",d.style.top=b.scrollTop+50+"px",d.style.width="4px",d.style.height="4px",
d.tabIndex=2,d.style.outline="none",d.style.opacity=.01,d.style.overflow="hidden",b.appendChild(d));return d}function Db(a){if(!p.focused){Oa.clearPDF();p.focused=!0;if(w&&w.onfocus)w.onfocus(a);p.focusTime=Date.now();na&&(fa=w.fromSyncedSurface?w.fromSyncedSurface(200):!1,fa||(y&&(y.clipData=null),p.onreqpaste||ib?w.send("8911"):y.read(function(c){c&&!c.equals(y.clipData)?(w.send("8911"),y.clipData=c):w.send("8910")})));I.setNeedSyncKey(!0);I.sendMissKey();I.ctrlDelayed&&(I.ctrlDelayed=!1)}}function Eb(a){var c=
__svi18n.remoteApp.close;if(!Fb&&p.railWin&&p.railWin.isRunning()&&c&&(a||(a=window.event),2!=w.getAppMode()))return p.showMessage(c),a&&(a.returnValue=c),c}function Za(a){if(p&&(p.focused=!1,p.onunload))p.onunload()}function Gb(){z&&(z.element.oncontextmenu=function(){return!1},C.isIE||(z.element.onselectstart=function(){return!1}))}function Hb(a){z&&z.adjust();if(Aa)Na(!0);else if(!(ua&&2500>Date.now()-ua)){var c=C.isWindows&&!C.isMetro;if(!Z||c&&!ua||C.isCrOS||C.isChromeApp)w.onresize(a)}}function Ib(a){I.setNeedSyncKey(!0);
p&&(p.focused=!1,p.blurTime=Date.now())}function lc(){window.svSurface||(window.svSurface=p);window.addEventListener("resize",Hb,!1);if(!wa){var a=!C.isChromeApp;a&&window.addEventListener("beforeunload",Eb,!1);a?window.addEventListener("unload",Za,!1):chrome.runtime.onSuspend.addListener(Za);Gb();z.element.addEventListener("focus",Db,!1);z.element.addEventListener("blur",Ib,!1);C.isChromeApp&&!x.disableMaxFullScn&&chrome.app.window.current().onMaximized.addListener(Cb);(a=hi5.$("saveSession"))&&
a.addEventListener("change",function(d){w.saveSession({save:d.target.checked})});if(a=hi5.$("reqFullscr"))a.onclick=function(d){p&&p.requestFullscreen(!0)};a=hi5.$("attachPrinter");var c=hi5.$("localPrinter");a&&c&&(a.onclick=function(d){p.showPrinters(function(b){b&&w.attachPrinter(b)})})}}function Jb(){if(!ra){var a=hi5.$("touchGesture");a&&(a.style.display="block");if(a=hi5.$("extKBD"))a.onchange=function(c){p.setExtKeyboard(c.target.checked)};ra=hi5.$("svTouchInput");try{window.parent==window||
ra||(ra=window.parent.document.getElementById("svTouchInput"))}catch(c){}ra&&"IMG"!=ra.nodeName&&(a=document.createElement("img"),a.id="svTouchInput",a.src=x.img&&x.img.kbd||"kbd.png",ra.parentNode.replaceChild(a,ra),ra=a)}}function xa(a,c){function d(k,m){var t=document.createElement("span");t.data_path=k;t.className="path";t.innerHTML=m;t.onclick=function(){xa(this.data_path,c)};return t}function b(k){for(var m=h;m.hasChildNodes();)m.removeChild(m.firstChild);var t=d("/","&nbsp&nbsp&nbsp/");m.appendChild(t);
if("/"!=k&&""!==k){k=k.split("/");for(var e="/",g=0,u=k.length;g<u;g++)t=k[g],""!==t&&(e=e+k[g]+"/",t=d(e,t+"/"),m.appendChild(t))}}var h=hi5.$("parentPath");h.currentDir||(h.currentDir="/");"."==a?a=h.currentDir:h.currentDir=a;h.currentDir=a;c?c.visible()?hi5.tool.disableInput(hi5.$("filecontainer")):c.onopen=function(){hi5.tool.disableInput(hi5.$("filecontainer"))}:hi5.tool.disableInput();var f=new hi5.DataGrid(hi5.$("filelist"));f.clear();w.getShareFiles(a,function(k){function m(u){u||(u=f.getValue("Name"));
var n=k.parent;if(""===n||"/"!=n.charAt(n.length-1))n+="/";if("."==u)return n;if(".."==u){if(1==n.length)return n;var J=n.lastIndexOf("/",n.length-2);if(-1!=J)return n.substring(0,J+1)}return n+u}k.error&&__svi18n.file[k.error]&&p.showMessage(__svi18n.file[k.error]);var t=new hi5.DataTable(k);f.dataTable=t;var e=hi5.tool.bytesToSize;f.beforeDisplayValue=function(u,n){u=t.cols[u].name;return"Date Modified"==u?(new Date(n)).toLocaleString():"Size"==u?e(n):"Type"==u&&"folder"==n?__svi18n.file.folder:
"Name"==u?decodeURIComponent(n):n};f.onrowclick=function(u){var n=f.getValue("Name"),J=f.getValue("Type");n=m(n);u=u.target.name;"delete"==u?(O.removeFile(n),xa(k.parent,c)):"folder"==J?xa(n,c):u&&w.getFile(decodeURIComponent(n),null,u)};f.beforeAppendRow=function(u){var n;if("folder"==t.getValue(t.getColNo("Type"))){if(n=u.querySelector('img[name="download"]'))n.style.visibility="hidden"}else{n=f.getValue("Name");var J=m(n);w.getFileLink(decodeURIComponent(J));if(10<n.length&&".uploading"==n.substring(n.length-
10)){if(n=u.querySelector('img[name="download"]'))n.style.visibility="hidden";if(n=u.querySelector('img[name="view"]'))n.style.visibility="hidden"}}};f.open();b(k.parent);var g=document.getElementById("__diskSpace");g&&(g.innerHTML=hi5.tool.bytesToSize(k.freeSpace)+"/"+hi5.tool.bytesToSize(k.totalSpace));c&&(c.__position="\\\\tsclient\\"+k.name+k.parent.replace(/\//g,"\\"),c.__workdir=k.parent);hi5.tool.enableInput()})}function Kb(a){O&&(a&&cancelDefault(a),a=hi5.$("filecontainer"),ha=new hi5.ui.Lightbox(a),
xa(".",ha),ha.show(),ha.onclose=function(){hi5.tool.enableInput();p.focus()},(a=document.getElementById("__sv_folder__"))&&O.mkdirs&&(a.onclick=function(){var c=document.getElementById("__sv_folder_name_");c&&c.value&&(O.mkdirs(c.value),xa(".",ha),c.value="")}),a=document.getElementById("__sv_position__"))&&(a.onclick=function(){w.setWorkDir&&w.setWorkDir(ha.__position,ha.__workdir);ha.dismiss()})}function Lb(){var a=q.toolbar;if(a){for(var c=a.childNodes,d=!1,b=0,h=c.length;b<h;b++)if(1==c[b].nodeType&&
-1==["svTouchInput","svCloud","svInfo"].indexOf(c[b].id)){d=!0;break}if(c=hi5.$("appinfo"))c.className="h5-form";if(p.showToolbar||Z||O||c||d){a.style.left=.45*window.innerWidth+"px";if(d=null===p.toolbar)p.toolbar=new hi5.Toolbar(a,x.toolbar.draggable,x.img.handle||"handle.png");Z||(a=hi5.$("svTouchInput"))&&a.parentNode.removeChild(a);if(a=p.toolbar.getButton("svCloud"))O?(a.style.display="",a.onclick=Kb):a.style.display="none";new hi5.Fadable(p.toolbar,x.toolbar.fadeDelay||5E3,z.element,"inline-block");
a=x.toolbar.fadable;p.toolbar.setFadable(a);a&&(p.toolbar.style.display="none");if(a=p.toolbar.getButton("svInfo"))c?(a.style.display="",d&&(a.onclick=function(f){cancelDefault(f);p.showConnectonInfo()})):a.style.display="none";if(p.onloadtoolbar)p.onloadtoolbar(p.toolbar)}}}function mc(a){O.addFiles(a.target.files,!1);a.target.value=null}function nc(){var a=z.element;sa&&sa.release();sa=new svGlobal.util.MapDisk(a,O,!0);hi5.$("filecontainer")&&($a=new svGlobal.util.MapDisk(hi5.$("filecontainer"),
O,!1),hi5.$("uploadfile").addEventListener("change",mc,!1))}function ab(a){r&&r.__setVisible(!1)}function Mb(a){if(P){if(a-rb>Nb)if(A.isMultiMon){var c=Pa(A.left,A.top,A.right,A.bottom);c&&(P.putImageData(c.imgData,c.left-A.left,c.top-A.top,0,0,c.width,c.height),rb=a)}else if(c=Pa(0,0,A.right,A.bottom))P.putImageData(c.imgData,c.left,c.top,0,0,c.width,c.height),rb=a;bb=requestAnimationFrame(Mb)}}function Ob(a,c,d,b){r||Ma(x.cursorNameOnly);r.__visible||r.__setVisible(!0);a=r.scrX+a;c=r.scrY+c;0>a?
a=0:a>W&&(a=W-1);0>c?c=0:c>X&&(c=X-1);r.scrX=a;r.scrY=c;var h=a-r.hotX,f=c-r.hotY;C.isIE&&(h=h/ea|0,f=f/la|0);r.style.left=h+A.offX+"px";r.style.top=f+A.offY+"px";V&&!d&&w.sendInput("82"+a+"\t"+c);A.x=a;A.y=c;b&&(d=r.getBoundingClientRect(),3>d.top?window.scrollBy(0,-20):3>d.left?window.scrollBy(-20,0):d.bottom>window.innerHeight?window.scrollBy(0,20):d.right>window.innerWidth&&window.scrollBy(20,0))}function Fa(a,c,d){a=a/ea|0;c=c/la|0;p.moveCursor(a,c,d)}function hb(a){z?z.setContentEditable(a?
"true":"false"):document.getElementById("wsinput")&&input.setAttribute("contenteditable",a?"true":"false");ua=a?1:0;Y&&Y.setVisibility(a);if(p.toolbar){var c=p.toolbar.getButton("svTouchInput");c&&(c.className=a?"h5-img-btn-on":"h5-img-btn")}}function sb(){(Ja=!Ja)&&z&&z.adjust();hb(Ja);z&&(z.element.blur(),z.element.focus())}function tb(a,c,d,b){switch(a){case "touchstart":ub=!1;0===r.scrX&&0===r.scrY&&Fa(c-50,d-50);b&&(p.beforemousedown&&p.beforemousedown(r.scrX,r.scrY,0),w.sendInput("80"+r.scrX+
"\t"+r.scrY+"\t0"));break;case "touchmove":b=c-cb;a=d-Ga;if(0===b&&0===a)return;var h=5>Math.abs(Pb)&&5>Math.abs(Qb)&&(7<Math.abs(b)||7<Math.abs(a));h||(Ob(b,a,!1,!0),ub=!0);Pb=b;Qb=a;break;case "touchend":if(a=!ub&&!b)p.beforemousedown&&p.beforemousedown(r.scrX,r.scrY,0),w.sendInput("80"+r.scrX+"\t"+r.scrY+"\t0");if(a||b)w.sendInput("81"+r.scrX+"\t"+r.scrY+"\t0"),p.aftermouseup&&p.aftermouseup(r.scrX,r.scrY,0)}cb=c;Ga=d}function oc(a){V&&Ba&&(a.touches||a.changedTouches?Ba.handle(a):Ba.handlePointer(a))}
function pc(a){if(!V)return!1;if("false"==z.element.contentEditable&&(C.isiOS||C.isAndroid))return Rb(a);a.stopPropagation();I.check(a);var c=T.getKeyCode(a),d="keydown"==a.type;if(Sb(a,c,d))return cancelDefault(a);17!=c||d||(Ca=!1,Ha&&I.preKey.down&&oa(!1,I.preKey.code,T.getScancodeByKeyCode(I.preKey.code)));var b=T.getScancode(a),h=T.isPrintableScancode(b,a);3==a.location&&(h=89==b?!0:!1);if(!h){I.afterComposition&&d&&(I.afterComposition=!1);if(I.onComposition||I.afterComposition&&!d)return!0;I.continue(d,
b,!0)&&D(d,b,a.key);if(17==c||(ia||a.metaKey)&&(86==c||67==c||88==c))return d&&(17==c&&Ka&&z&&Da&&(a.target==z.element?(z.setValue("Copying... Please try again"),z.select()):(ja.setValue("Copying... Please try again"),ja.select())),67==c||88==c)&&(Ca=!0),17!=c||d||(Ca=!1),!0;3==a.location?I.noUnicode=!0:d&&(I.noUnicode=!1);return 9==c&&!1===x.tabCapture?!0:cancelDefault(a)}(h=I.isAltGr(d))?ya=ia=!1:I.noUnicode&&(I.noUnicode=!1);h=!h&&(a.ctrlKey||a.altKey||a.metaKey);if(a.altKey&&h&&70<b&&83>b&&74!=
b&&78!=b){if(56==I.preScancode.code||184==I.preScancode.code)D(!0,1,"Escape"),D(!1,1,"Escape");h=!1}if(h)return(86!=c||!a.ctrlKey&&!a.metaKey||a.ctrlKey&&a.altKey||!na)&&oa(d,c,T.getScancode(a)),d&&(db=c),17==c||(a.ctrlKey||a.metaKey)&&(86==c||67==c||88==c)?(!d||67!=c&&88!=c||(Ca=!0),!0):a.altKey&&!a.ctrlKey||a.ctrlKey&&!a.altKey||a.metaKey?cancelDefault(a):!0;if(!(c!=db||d||a.ctrlKey&&a.altKey))return oa(!1,c,T.getScancode(a)),db=0,cancelDefault(a);db=0;return!0}function qc(a){I.onComposition="compositionend"!=
a.type;I.afterComposition=!I.onComposition}function Sb(a,c,d){switch(c){case 8:case 35:if(!ia&&!a.metaKey||!a.altKey||x.disableShortcuts||3==a.location)return!1;D(d,211,"Delete");break;case 33:if(!a.altKey||x.disableShortcuts||3==a.location)return!1;D(d,15,"Tab");break;case 34:if(!a.altKey||x.disableShortcuts||3==a.location)return!1;d?(D(!0,42,"Shift"),D(!0,15,"Tab")):(D(!1,15,"Tab"),D(!1,42,"Shift"));break;case 45:if(!a.altKey||x.disableShortcuts)return!1;D(d,1,"Escape");break;case 36:if(!a.altKey||
x.disableShortcuts||3==a.location)return!1;d?(D(!1,56,"Alt"),D(!0,29,"Control"),D(!0,1,"Escape")):(D(!1,1,"Escape"),D(!1,29,"Control"));break;default:return!1}return!0}function Rb(a){if(!V)return!1;x.logKey&&svGlobal.logger.info(a);if(a.isComposing&&"Process"!==a.key)return svGlobal.logger.warn("kkk Extra IME key ignored"),!1;I.check(a);var c=T.getKeyCode(a),d="keydown"==a.type,b=T.getScancode(a);if(Sb(a,c,d))return cancelDefault(a);var h=86==c&&(Tb&&!d||(a.ctrlKey||a.metaKey)&&!(a.ctrlKey&&a.altKey))&&
na;if(0<b)if(h)eb&&d&&eb.sendCtrlVLater();else if(I.continue(d,b,!1)){if(44==c){d||(ia||a.shiftKey?(D(!0,183),D(!1,183)):(D(!0,170),D(!0,183),D(!1,183),D(!1,170)));var f=!0}else f=!1;if(f)return cancelDefault(a);D(d,b,a.key)}17!=c&&(Tb=h);return 17==c||(ia||a.metaKey)&&(86==c||67==c||88==c)?(d&&(17==c&&Ka&&z&&Da&&(z.setValue("Copying... Please try again"),z.select()),67==c||88==c)&&(Ca=!0),17!=c||d||(Ca=!1),!0):144==c||16==c||9==c&&!1===x.tabCapture?!1:cancelDefault(a)}function rc(a){if(V)if(I.noUnicode)I.noUnicode=
!1;else if(a=a.data,"`\t`"!=a){var c=ia||ya;c&&(a=a.toLowerCase());a=a.replace(/\u00a0/g," ");if(p.onunicode){var d=p.onunicode(a);d&&(c=d.ctrl||d.alt)}if(x.scancode&&x.scancode[a])if(a=x.scancode[a],"number"==typeof a)ta(!0,a),ta(!1,a);else for(c=0,d=a.length;c<d;c++)ta(a[c].down,a[c].key);else w.sendInput("86"+a+"\t"+(c||Ub?1:0));Y&&Y.resetModifier()}}function sc(a,c){var d=a?a.getData(c):null;!d&&a&&(d=a.getData(a.types[0]));if(d&&"text/plain"==c){for(var b=0,h="",f=d.length;b<f&&(h=d.charAt(b),
"\r"==h||"\n"==h);b++);b&&(d=d.substring(b))}if(d)return w.send("881"+c+"\t"+d),a.sent=Date.now(),!0;if(p.onreqpaste)return p.onreqpaste(c,function(k){w.send("881"+c+"\t"+k)},function(){w.send("881ERROR\t")}),!0;w.send("881"+c+"\t");return!1}function fb(){w.writeKeyComb("ctrl+v",20)}function tc(a){var c=0===a.types.length||a.equals(y.clipData),d=c?"":a.types.join(","),b=!0;if(!c){-1!=d.indexOf("text/html")&&-1==d.indexOf("text/richtext")&&(d+=",text/richtext");var h=a.getData("text/plain");h=h?h.hashCode():
0;w.send("880"+d+"\t"+h);y.clipData=a}p.onclipdata&&(b=!p.onclipdata(a,c));b&&setTimeout(fb,500)}function ta(a,c,d){if(p.onscancode){var b=p.onscancode(a,c);if(b){a=0;for(c=b.length;a<c;a++)w.sendInput("84"+(b[a].down?0:49152)+"\t"+b[a].key);return}}b="84"+(a?0:49152)+"\t"+c;d&&(b+="\t"+d);w.sendInput(b);I.preScancode.code=c;I.preScancode.down=a}function D(a,c,d){if(V){switch(c){case 221:if(a&&!x.disableKbdSync){ta(!0,221,d);ta(!1,221,d);return}break;case 58:if(a){if(Ha&&!x.disableKbdSync){ta(!0,
58,d);ta(!1,58,d);return}w.localLockFlags^=4}break;case 69:a&&(w.localLockFlags^=2);break;case 70:a&&(w.localLockFlags^=1)}!I.isKeyDownSent(a,c)&&999<Date.now()-p.focusTime&&ta(!0,c,d);ta(a,c,d)}}function oa(a,c,d){if(V){var b="8B"+(a?0:49152)+"\t"+c;d&&(b+="\t"+d);I.ctrlDelayed&&(I.ctrlDelayed=!1,D(!0,29,"Control"));w.sendInput(b);I.preKey.code=c;I.preKey.down=a}}function La(a,c){I.ctrlDelayed&&(I.ctrlDelayed=!1,D(!0,29,"Control"));w.sendInput(a+c)}function Qa(a,c,d,b,h){if(!V)return!1;F(z.element);
b||(b=ea);h||(h=la);A.mouseDown[d]=!0;a=(a/b|0)+A.left;c=(c/h|0)+A.top;p.beforemousedown&&p.beforemousedown(a,c,d);A.x=a;A.y=c;La("80",a+"\t"+c+"\t"+d)}function jb(a){I.sendMissKey(a);var c=Va(a);Qa(c.x,c.y,a.button);return Vb?!0:cancelDefault(a)}function Wb(a,c,d,b){d||(d=ea);b||(b=la);a=(a/d|0)+A.left;c=(c/b|0)+A.top;0>a&&(a=0);0>c&&(c=0);if(p.onmousemove)p.onmousemove(a,c);A.x=a;A.y=c;La("82",a+"\t"+c)}function kb(a){I.isNeedSyncKey()&&I.syncLockKeyStatus(a);if(!Xb||!z||a.target!=z.element&&!A.mouseDown[0])return!1;
var c=Va(a,z.element);!Ra||!C.isAndroid&&!C.isiOS&&ka&&ka.system?r&&r.__visible&&r.__setVisible(!1):Fa(c.x,c.y,!0);Wb(c.x,c.y);return cancelDefault(a)}function Sa(a,c,d,b,h){b||(b=ea);h||(h=la);A.mouseDown[d]&&(A.mouseDown[d]=!1,a=(a/b|0)+A.left,c=(c/h|0)+A.top,0>a&&(a=0),0>c&&(c=0),La("81",a+"\t"+c+"\t"+d),p.aftermouseup&&p.aftermouseup(a,c,d),y&&"denied"==y.clipboardWrite&&y.waitForCopyContent(),w.resumeAudio&&(w.resumeAudio(),w.resumeAudio=null))}function lb(a){if(!V)return!1;var c=Va(a,z.element);
Sa(c.x,c.y,a.button);return Vb?!0:cancelDefault(a)}function Yb(a,c,d,b,h){b||(b=ea);h||(h=la);a=(a/b|0)+A.left;c=(c/h|0)+A.top;p.onmousewheel&&p.onmousewheel(a,c,d)||La("83",a+"\t"+c+"\t"+d)}function uc(a,c){if(!V)return!1;var d=Math.abs(a);a=0>a?1:0;for(var b=0;b<d;b++)Yb(c.x,c.y,a);return!1}function vc(a){if(a.none)return"none";if(a.system)return a.system;if(Ra)return"none";var c;if(!(c=a.url)){var d=a.rawData;c=a.width;var b=a.height,h=document.createElement("canvas"),f=h.getContext("2d"),k=f.createImageData(c,
b),m=k.data,t=c*b,e=window.devicePixelRatio||1,g=0,u=0;h.width=c;for(h.height=b;g<t;g++){var n=d[g];m[u++]=n&255;m[u++]=n>>8&255;m[u++]=n>>16&255;m[u++]=n>>24&255}f.putImageData(k,0,0,0,0,c,b);1==e?c=h.toDataURL():h.toDataURLHD?c=h.toDataURLHD():(d=document.createElement("canvas"),f=d.getContext("2d"),d.width=c*e|0,d.height=b*e|0,f.scale(e,e),f.drawImage(h,0,0),c=d.toDataURL())}return"url("+c+") "+a.hotX+" "+a.hotY+", default"}function Zb(){document.fullscreenElement?navigator.keyboard&&navigator.keyboard.lock():
navigator.keyboard&&navigator.keyboard.unlock()}l||(l=hi5.$("remotectrl"));q||(q={});q.pcKey||(q.pcKey=hi5.$("pc_key"));q.toolbar||(q.toolbar=hi5.$("svToolbar"));q.frmLogin||(q.frmLogin=hi5.$("frmLogin"));var $b=q.notifications||hi5.notifications;if(window.svSurface&&svSurface.canvas==l&&svSurface.railWin)return svSurface.railWin.mainWin=null,window.svSurface;var C=hi5.browser,Z=C.isTouch,Ta=C.getChildByNameOrId,w=null,Aa=!1,ea=1,la=1,gb=0,ac=0,vb=!1;l.style.outline="none";var W=0,X=0,P=l.getContext("2d",
{alpha:!0}),R=null,ja=null,ia=!1,ya=!1,Ia=!1,Fb=!1,fa=!1,O=null,na=!0,Da=!1,wb=!1,Ca=!1,Tb=!1,bc=0;this.context=P;this.fileProgress=null;this.focusTime=this.blurTime=0;var p=this,V=!0,qa=!1,wa=!1,Xb=!0,Ua=null,cc=null,ha=null,r=null,ka=null,Ba=null,ra=null,ua=0,cb=-1,Ga=-1,Pb=0,Qb=0,ub=!1,ob=null,A={x:0,y:0,offX:0,offY:0,left:0,top:0,right:0,bottom:0,primary:!1,isMultiMon:!1,btnDown:-1,mouseDown:[]},sa=null,$a=null,rb=0,Pa,xb=!1,dc=0,bb=0,Ja=!1,za=null;this._cr=[82,69,77,79,84,69,83,80,65,82,75];
window.svSurface=this;hi5.appcfg||(hi5.appcfg={img:{},toolbar:{fadable:!0},displayMsg:!0});var x=hi5.appcfg;void 0==x.toolbar.draggable&&(x.toolbar.draggable=!0);var Vb=window.clipboardData?!0:!!x.defaultEvent,Ra=C.isIE&&!x.disableCursor,ib=C.isChromeApp||C.isIE||1==x.directClipAccess,Ub=!!x.forceScancode;this.setConfig=function(a){x=a};this.railWin=this.toolbar=null;this.showToolbar=this.focused=!1;this.canvas=l;this.forceTextArea=this.alwaysPaste=!1;"visible"in x.toolbar&&(this.showToolbar=x.toolbar.visible);
var Va=C.getMousePos,Wa=C.calMousePos;this.getWindow=function(){return window};this.setImageCursor=function(a){Ra=a};this.setMonitor=function(a,c,d,b){A.left=a;A.top=c;A.right=d;A.bottom=b;A.primary=0==a&&0==c;0!=d&&0!=b&&(A.isMultiMon=!1,p.setSize(d-a+1,b-c+1),A.isMultiMon=!0,nb("hidden"),x.disableScrollbars=!0)};this.configMonitor=function(){var a=window.screenX,c=window.screenY;if(window.outerWidth<window.innerWidth){var d=(window.innerWidth-window.outerWidth)/2;svGlobal.logger.warn("* screenX:"+
window.screenX+" screenY:"+window.screenY+" outerWidth:"+window.outerWidth+" innerWidth:"+window.innerWidth+" off:"+d);a-=d;c-=d}0<=a&&100>a&&0<=c&&100>c&&(0<a&&(svGlobal.logger.warn("* invalid left:"+a),a=0),0<c&&(svGlobal.logger.warn("* invalid top: "+c),c=0));d=(window.innerWidth&-4)+a-1;var b=(window.innerHeight&-4)+c-1;p.setMonitor(a,c,d,b);svGlobal.logger.info("monitor, l:"+a+" t:"+c+" r:"+d+" b:"+b)};this.isClipSynced=function(a){if(!fa)return!1;var c=Date.now()-p.blurTime;if(a&&c>a)return!1;
svGlobal.logger.info("clip synced in "+c);return!0};this.getScale=function(){return{x:ea,y:la}};var U=null,Y=null,Ka=!C.isChromeApp&&!x.copyDialog&&!x.directClipAccess&&!C.isIE;this.getThumbnail=function(a){a=a||64;U||(U=document.createElement("canvas"));var c=Math.floor(l.height/l.width*a);U.width!=a&&(U.width=a);U.height!=c&&(U.height=c);U.getContext("2d").drawImage(l,0,0,l.width,l.height,0,0,a,c);return U.toDataURL()};this.getThumbnailBlob=function(a,c){a=a||64;var d=Math.floor(l.height/l.width*
a);U||(U=window.OffscreenCanvas?new OffscreenCanvas(a,d):document.createElement("canvas"));U.width!=a&&(U.width=a);U.height!=d&&(U.height=d);U.getContext("2d").drawImage(l,0,0,l.width,l.height,0,0,a,d);return U.toBlob(c)};this.initChat=function(a){var c=document.getElementById("chatWindow");hi5.Draggable(c);return new hi5.Chat(c,a)};this.equals=function(a){return l==a.canvas};this.getFreeSpace=function(){var a=hi5.tool.getPos(l),c=window.innerWidth-a.x;a=v(window.innerHeight)-a.y;return{width:c,height:a}};
var T=new function(){var a=1033,c=C.isFirefox,d=C.isMacOS||C.isiOS,b=[0],h=null;b[3]=197;b[8]=14;b[9]=15;b[12]=76;b[13]=28;b[16]=42;b[17]=29;b[18]=56;b[19]=197;b[20]=58;b[27]=1;b[32]=57;b[33]=201;b[34]=209;b[35]=207;b[36]=199;b[37]=203;b[38]=200;b[39]=205;b[40]=208;b[44]=55;b[45]=210;b[46]=211;b[48]=11;b[49]=2;b[50]=3;b[51]=4;b[52]=5;b[53]=6;b[54]=7;b[55]=8;b[56]=9;b[57]=10;b[65]=30;b[66]=48;b[67]=46;b[68]=32;b[69]=18;b[70]=33;b[71]=34;b[72]=35;b[73]=23;b[74]=36;b[75]=37;b[76]=38;b[77]=50;b[78]=49;
b[79]=24;b[80]=25;b[81]=16;b[82]=19;b[83]=31;b[84]=20;b[85]=22;b[86]=47;b[87]=17;b[88]=45;b[89]=21;b[90]=44;b[91]=219;b[92]=220;b[93]=221;b[96]=82;b[97]=79;b[98]=80;b[99]=81;b[100]=75;b[101]=76;b[102]=77;b[103]=71;b[104]=72;b[105]=73;b[106]=55;b[107]=78;b[109]=74;b[110]=83;b[111]=181;b[112]=59;b[113]=60;b[114]=61;b[115]=62;b[116]=63;b[117]=64;b[118]=65;b[119]=66;b[120]=67;b[121]=68;b[122]=87;b[123]=88;b[144]=69;b[145]=70;b[154]=183;b[166]=59;b[167]=60;b[168]=61;b[173]=66;b[174]=67;b[175]=68;b[182]=
63;b[183]=62;b[216]=64;b[217]=65;b[186]=39;b[187]=13;b[188]=51;b[189]=12;b[190]=52;b[191]=53;b[192]=41;b[219]=26;b[220]=43;b[221]=27;b[222]=40;b[224]=29;b[225]=184;b[226]=86;b[235]=123;b[255]=121;var f={Escape:1,Digit1:2,Digit2:3,Digit3:4,Digit4:5,Digit5:6,Digit6:7,Digit7:8,Digit8:9,Digit9:10,Digit0:11,Minus:12,Equal:13,Backspace:14,Tab:15,KeyQ:16,KeyW:17,KeyE:18,KeyR:19,KeyT:20,KeyY:21,KeyU:22,KeyI:23,KeyO:24,KeyP:25,BracketLeft:26,BracketRight:27,Enter:28,ControlLeft:29,KeyA:30,KeyS:31,KeyD:32,
KeyF:33,KeyG:34,KeyH:35,KeyJ:36,KeyK:37,KeyL:38,Semicolon:39,Quote:40,Backquote:41,ShiftLeft:42,Backslash:43,KeyZ:44,KeyX:45,KeyC:46,KeyV:47,KeyB:48,KeyN:49,KeyM:50,Comma:51,Period:52,Slash:53,ShiftRight:54,NumpadMultiply:55,AltLeft:56,Space:57,CapsLock:58,F1:59,F2:60,F3:61,F4:62,F5:63,F6:64,F7:65,F8:66,F9:67,F10:68,NumLock:69,ScrollLock:70,Numpad7:71,Numpad8:72,Numpad9:73,NumpadSubtract:74,Numpad4:75,Numpad5:76,Numpad6:77,NumpadAdd:78,Numpad1:79,Numpad2:80,Numpad3:81,Numpad0:82,NumpadDecimal:83,
IntlBackslash:86,F11:87,F12:88,NumpadEqual:89,F13:91,F14:92,F15:93,F16:99,F17:100,F18:101,F19:102,F20:103,F21:104,F22:105,F23:106,F24:107,KanaMode:112,Lang2:113,Lang1:114,IntlRo:115,Convert:121,NonConvert:123,IntlYen:125,NumpadComma:126,Paste:138,MediaTrackPrevious:144,Cut:151,Copy:152,MediaTrackNext:153,NumpadEnter:156,ControlRight:157,VolumeMute:160,AudioVolumeMute:160,LaunchApp2:161,MediaPlayPause:162,MediaStop:164,Eject:172,VolumeDown:174,AudioVolumeDown:174,VolumeUp:176,AudioVolumeUp:176,BrowserHome:178,
NumpadDivide:181,PrintScreen:183,AltRight:184,Help:187,Pause:197,Home:199,ArrowUp:200,PageUp:201,ArrowLeft:203,ArrowRight:205,End:207,ArrowDown:208,PageDown:209,Insert:210,Delete:211,OSLeft:219,MetaLeft:219,OSRight:220,MetaRight:220,ContextMenu:221,Power:222,BrowserSearch:229,BrowserFavorites:230,BrowserRefresh:231,BrowserStop:232,BrowserForward:233,BrowserBack:234,LaunchApp1:235,LaunchMail:236,LaunchMediaPlayer:237};this.isPrintableScancode=function(e,g){if(95<g.keyCode&&112>g.keyCode)return!0;if(0==
e&&g){var u=g.char||g.key;if(u&&1==u.length)return e=u.charCodeAt(0),!(31>=e||127==e||128<=e&&159>=e)}return g.altKey&&70<e&&83>e&&74!=e&&78!=e?!0:1<e&&14>e||15<e&&28>e||29<e&&42>e||42<e&&54>e||57==e||86==e||115==e||125==e};var k=function(e){e=e.keyCode;if(c)switch(e){case 173:return 189;case 61:return 187;case 59:return 186;case 224:return 17}return e};this.mapCmdToCtrl=this.converMacCtrl=!0;var m=d?function(e){switch(e){case 91:return T.mapCmdToCtrl?17:91;case 93:return T.mapCmdToCtrl?17:93;case 17:return T.converMacCtrl?
91:17;case 229:return 69}return 0}:null;this.setLayout=function(e){a=e;var g=null;e="K"+e;e in t&&(g=t[e]());null===g&&(g=b);h=g;null!==h&&svGlobal.logger.info("Keyboard layout: "+a)};this.getKeyCode=function(e){var g=0;m&&(g=m(e.keyCode));g||(g=k?k(e):e.keyCode);return g};this.getScancode=function(e){var g=0;if(e.code)g=f[e.code]||0;else{var u=T.getKeyCode(e);switch(u){case 16:g=2==e.location?54:42;break;case 17:g=2==e.location?157:29;break;case 18:g=2==e.location?184:56;break;case 33:g=3==e.location?
73:201;break;case 34:g=3==e.location?81:209;break;case 35:g=3==e.location?79:207;break;case 36:g=3==e.location?71:199;break;case 37:g=3==e.location?75:203;break;case 38:g=3==e.location?72:200;break;case 39:g=3==e.location?77:205;break;case 40:g=3==e.location?80:208;break;case 45:g=3==e.location?82:210;break;case 46:g=3==e.location?83:211;break;default:h&&(g=h[u]||0)}}if(d)switch(g){case 29:this.converMacCtrl&&(g=219);break;case 157:this.converMacCtrl&&(g=220);break;case 219:this.mapCmdToCtrl&&(g=
29);break;case 220:this.mapCmdToCtrl&&(g=157)}return g};this.getScancodeByKeyCode=function(e){return h?h[e]||0:0};this.getCodeTable=function(){return h};this.getLayoutCreator=function(){return t};var t=new function(){this.K3758162961=function(){var e=b.slice(0);e[244]=41;e[243]=41;e[189]=12;e[222]=13;e[220]=125;e[192]=26;e[219]=27;e[187]=39;e[186]=40;e[221]=43;e[188]=51;e[190]=52;e[191]=53;e[226]=115;e[29]=123;e[28]=121;e[240]=112;e[242]=112;c&&(e[173]=12,e[160]=13,e[64]=26,e[59]=39,e[58]=40,k=function(g){return 220==
g.keyCode&&"_"==g.key?226:g.keyCode});return e};this.K1034=this.K66570=this.K2058=this.K1040=this.K66576=function(){var e=b.slice(0);e[220]=41;e[219]=12;e[221]=13;e[186]=26;e[187]=27;e[191]=43;e[192]=39;e[189]=53;e[226]=86;c&&(k=function(g){var u=g.keyCode;g=g.key;switch(u){case 0:if("\u00e8"==g||"\u00e9"==g||"["==g)return 186;if("\u00f2"==g||"\u00e7"==g||"@"==g)return 192;if("\u00e0"==g||"\u00b0"==g||"#"==g||"\u00f9"==g||"\u00a7"==g)return 222;break;case 60:return 226;case 160:return 221;case 171:return 187;
case 173:return 189;case 222:return 219}return u});return e};this.K2057=function(){var e=b.slice(0);e[223]=41;e[222]=43;e[192]=40;e[220]=86;c&&(e[192]=41,e[173]=12,e[61]=13,e[59]=39,e[222]=40,e[163]=43);return e};this.K1031=this.K4106=this.K5130=this.K6154=this.K7178=this.K8202=this.K9226=this.K10250=this.K11274=this.K12298=this.K13322=this.K14346=this.K15370=this.K16395=this.K17418=this.K18442=this.K19466=this.K20490=this.K99997=this.K66567=this.K2952791047=function(){var e=b.slice(0);e[220]=41;
e[219]=12;e[221]=13;e[186]=26;e[187]=27;e[191]=43;e[192]=39;e[189]=53;e[226]=86;e[90]=21;e[89]=44;c?k=function(g){var u=g.keyCode,n=g.key;switch(u){case 60:return 226;case 160:return 220;case 63:return 219;case 192:return 221;case 171:return 187;case 163:return 191;case 173:return 189;case 0:if("\u00f6"==n||"\u00d6"==n&&g.shiftKey)return 192;if("\u00e4"==n||"\u00c4"==n&&g.shiftKey)return 222;if("\u00fc"==n||"\u00dc"==n&&g.shiftKey)return 186}return u}:hi5.browser.isLinux&&(k=function(g){var u=g.keyCode;
g=g.key;switch(u){case 187:if("Dead"==g)return 221;break;case 192:if("Dead"==g||"\u00b0"==g)return 220;break;case 220:return 226}return u});return e};this.K2070=function(){var e=b.slice(0);e[220]=41;e[219]=12;e[221]=13;e[186]=27;e[187]=26;e[191]=43;e[192]=39;e[189]=53;e[226]=86;return e};this.K2060=this.K99998=this.K2067=function(){var e=b.slice(0);e[222]=41;e[219]=12;e[189]=13;e[221]=26;e[186]=27;e[77]=39;e[192]=40;e[188]=50;e[190]=51;e[191]=52;e[187]=53;e[226]=86;e[65]=16;e[90]=17;e[81]=30;e[87]=
44;c&&(k=function(g){var u=g.keyCode,n=g.key;switch(u){case 60:return 226;case 169:return 219;case 173:return 189;case 160:return 221;case 164:return 186;case 165:return 192;case 59:return 190;case 58:return 191;case 61:return 187;case 0:if("\u00b2"==n||"\u00b3"==n&&g.shiftKey)return 222;if("\u00b5"==n||"`\u00b5"==n||"DeadGrave"==n||"\u00a3"==n&&g.shiftKey||("`"==n||"``"==n)&&g.ctrlKey&&g.altKey)return 220}return u});return e};this.K3084=this.K4105=function(){var e=b.slice(0);e[222]=41;e[192]=40;
e[226]=86;c&&(k=function(g){var u=g.keyCode,n=g.key;switch(u){case 0:if("\u00b0"==n||"\u00ac"==n&&g.ctrlKey&&g.altKey)return 222;if("\u00e7"==n||"\u00c7"==n&&g.shiftKey)return 221;if("\u00e0"==n||"DeadGrave"==n||"\u00c0"==n&&g.shiftKey)return 220;if("\u00e8"==n||"\u00c8"==n&&g.shiftKey)return 192;if("\u00e9"==n||"\u00c9"==n&&g.shiftKey)return 191;if("\u00f9"==n||"\u00d9"==n&&g.shiftKey)return 226;if("DeadTilde"==n)return 221;break;case 173:return 189;case 61:return 187;case 160:return 219;case 59:return 186}return u});
return e};this.K1036=function(){var e=b.slice(0);e[222]=41;e[219]=12;e[187]=13;e[221]=26;e[186]=27;e[220]=43;e[77]=39;e[192]=40;e[190]=51;e[191]=52;e[223]=53;e[226]=86;e[65]=16;e[90]=17;e[81]=30;e[87]=44;e[188]=50;c&&(k=function(g){var u=g.keyCode,n=g.key;switch(u){case 0:if("\u00b2"==n)return 222;if("\u00e7"==n||"\u00c7"==n&&g.shiftKey)return 221;if("\u00e0"==n||"\u00c0"==n&&g.shiftKey)return 220;if("\u00e8"==n||"\u00c8"==n&&g.shiftKey)return 192;if("\u00e9"==n||"\u00c9"==n&&g.shiftKey)return 189;
if("\u00f9"==n||"\u00d9"==n&&g.shiftKey)return 226;if("DeadTilde"==n)return 221;break;case 60:return 226;case 169:return 219;case 61:return 187;case 160:return 221;case 164:return 186;case 170:return 220;case 165:return 192;case 59:return 190;case 58:return 191;case 161:return 223}return u});return e};this.K4108=this.K2055=function(){var e=b.slice(0);e[191]=41;e[219]=12;e[221]=13;e[186]=26;e[192]=27;e[223]=43;e[222]=39;e[220]=40;e[188]=51;e[190]=52;e[189]=53;e[226]=86;e[90]=21;e[89]=44;c&&(k=function(g){var u=
g.keyCode,n=g.key;switch(u){case 0:if("\u00a7"==n||"\u00b0"==n&&g.shiftKey)return 191;if("\u00e0"==n||"\u00e4"==n&&g.shiftKey||"{"==n&&g.ctrlKey&&g.altKey)return 220;if("\u00e8"==n||"\u00fc"==n&&g.shiftKey||"["==n&&g.ctrlKey&&g.altKey)return 186;if("\u00e9"==n||"\u00f6"==n&&g.shiftKey)return 222;break;case 222:return 219;case 160:return 221;case 161:return 192;case 164:return 223;case 173:return 189;case 60:return 226}return u});return e};this.K1044=this.K1083=this.K1030=function(){var e=b.slice(0);
e[220]=41;e[187]=12;e[219]=13;e[221]=26;e[186]=27;e[191]=43;e[192]=39;e[222]=40;e[189]=53;e[226]=86;c&&(k=function(g){var u=g.keyCode,n=g.key;switch(u){case 0:if("\u00e5"==n||"\u00c5"==n&&g.shiftKey)return 221;if("\u00f8"==n||"\u00d8"==n&&g.shiftKey||"\u00f6"==n&&g.ctrlKey&&g.altKey)return 192;if("\u00e6"==n||"\u00c6"==n&&g.shiftKey||"\u00e4"==n&&g.ctrlKey&&g.altKey)return 222;break;case 172:return 220;case 171:return 187;case 220:return 219;case 160:return 186;case 222:return 191;case 173:return 189;
case 60:return 226}return u});return e};this.K1039=function(){var e=b.slice(0);e[220]=41;e[187]=12;e[219]=13;e[221]=26;e[186]=27;e[191]=43;e[192]=39;e[222]=40;e[189]=53;e[226]=86;c&&(k=function(g){var u=g.keyCode;g=g.key;switch(u){case 0:if("Dead"==g)return 220;if("\u00f6"==g||"\u00d6"==g||"\\"==g)return 187;if("\u00f0"==g||"\u00d0"==g)return 221;if("\u00e6"==g||"\u00c6"==g)return 192;if("\u00fe"==g||"\u00de"==g)return 189;break;case 173:return 219;case 222:return"Dead"==g||"'"==g?222:186;case 171:return 191;
case 60:return 226}return u});return e};this.K1053=function(){var e=b.slice(0);e[220]=41;e[187]=12;e[219]=13;e[221]=26;e[186]=27;e[191]=43;e[192]=39;e[222]=40;e[189]=53;e[226]=86;c&&(k=function(g){var u=g.keyCode,n=g.key;switch(u){case 0:if("\u00a7"==n||"\u00bd"==n&&g.shiftKey)return 220;if("\u00e5"==n||"\u00c5"==n&&g.shiftKey)return 221;if("\u00f8"==n||"\u00d8"==n&&g.shiftKey||"\u00f6"==n&&g.ctrlKey&&g.altKey)return 192;if("\u00e4"==n||"\u00c4"==n&&g.shiftKey)return 222;break;case 171:return 187;
case 192:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return u});return e};this.K1055=function(){var e=b.slice(0);e[220]=52;e[223]=12;e[189]=13;e[191]=51;e[188]=43;e[190]=53;e[226]=86;c&&(k=function(g){var u=g.keyCode,n=g.key;switch(u){case 0:if("\u011f"==n||"\u011e"==n&&g.shiftKey||g.ctrlKey&&g.altKey&&"BracketLeft"==g.code)return 219;if("\u00fc"==n||"\u00dc"==n&&g.shiftKey||g.ctrlKey&&g.altKey&&"BracketRight"==g.code)return 221;if("\u015f"==n||"\u015e"==
n&&g.shiftKey||g.ctrlKey&&g.altKey&&"Semicolon"==g.code)return 186;if("\u00f6"==n||"\u00d6"==n&&g.shiftKey)return 191;if("\u00e7"==n||"\u00c7"==n&&g.shiftKey)return 220;break;case 73:return 222;case 60:return 226;case 173:return 189;case 170:return 223;case 162:return 192}return u});return e};this.K6153=function(){var e=b.slice(0);e[223]=41;e[189]=12;e[187]=13;e[219]=26;e[221]=27;e[186]=39;e[192]=40;e[222]=43;e[220]=86;e[188]=51;e[190]=52;e[191]=53;return e}}};this.getKeyboardMgr=function(){return T};
var y=new function(){function a(d,b){var h=y.parseClipData(b);if(!(x.copyTextOnly&&"text/plain"!=h.type||y.processFileGroup(h)))if((b=h.value.startsWith("<img data-sv-img"))&&"denied"!=y.clipboardWrite&&navigator.clipboard.write)d.preventDefault(),setTimeout(function(){y.copyImageToClipboard(h.value)},20);else{if("text/plain"!=h.type&&!b){var f=hi5.browser.html2text(h.value);f&&d.clipboardData.setData("text/plain",f)}b&&y.processImgCopy(h.value);d.clipboardData.setData(h.type,h.value);d.preventDefault()}}
function c(){y&&(y.copyContent&&(y.copyToClipboard(y.copyContent.type,y.copyContent.value),y.copyContent=null),y.waitingCopyContent=!1)}this.hasCopyCmd=document.queryCommandSupported("copy");this.hasPasteCmd=document.queryCommandSupported("paste");this.pasteEventFired=!1;this.clipboardWrite=this.clipboardRead="denied";this.init=function(){navigator.permissions&&(navigator.permissions.query({name:"clipboard-read"}).then(function(d){y&&(y.clipboardRead=d.state,d.onchange=function(){y&&(y.clipboardRead=
d.state,"granted"==y.clipboardRead&&B(),svGlobal.logger.info("clipboard-read change: "+y.clipboardRead))},"granted"==y.clipboardRead&&B(),svGlobal.logger.info("clipboard-read: "+y.clipboardRead))}).catch(function(d){svGlobal.logger.info(d)}),navigator.permissions.query({name:"clipboard-write"}).then(function(d){y&&(y.clipboardWrite=d.state,d.onchange=function(){y&&(y.clipboardWrite=d.state,svGlobal.logger.info("clipboard-write change: "+y.clipboardWrite))},svGlobal.logger.info("clipboard-write: "+
y.clipboardWrite))}).catch(function(d){svGlobal.logger.info(d)}))};this.release=function(){y.clipData=null};this.clipData=null;this.read=function(d){var b=new E;if("denied"!=y.clipboardRead)navigator.clipboard.read?navigator.clipboard.read().then(function(h){for(var f=h.length,k=0,m=0;m<f;m++){var t=h[m].types[0];h[m].getType(t).then(function(e){"text/plain"==t||"text/html"==t||"text/rtf"==t?hi5.browser.blobToText(e,function(g){b.setData(t,g);k++;k==f&&d(b)}):"image/png"==t&&hi5.browser.blobToArray(e,
function(g){g=hi5.Base64.enc(g);b.setData("image/png",g);k++;k==f&&d(b)})}).catch(function(e){d(b);svGlobal.logger.warn(e.message)})}}).catch(function(h){svGlobal.logger.warn(h.message)}):navigator.clipboard.readText&&navigator.clipboard.readText().then(function(h){b.setData("text/plain",h);d(b)}).catch(function(h){d(null)});else if(window.clipboardData)b.setData("text/plain",window.clipboardData.getData("Text")),d(b);else return d(null),!1;return!0};this.paste=function(d,b){var h=window.clipboardData||
b.clipboardData;if(h.files&&0<h.files.length&&O)O.addFiles(h.files,!0);else{var f=new E,k=0,m=null,t=window.clipboardData?h.getData("Text"):h.getData("text/plain"),e="",g="";e=0;h.types&&(g=h.getData("text/html"));g&&!t&&(t=hi5.browser.html2text(g));t&&f.setData("text/plain",t);if(x.pasteTextOnly)b.preventDefault(),d(f);else{var u=h.items;if(u)for(k=0,e=u.length;k<e;k++){if("image/png"==u[k].type){m=u[k].getAsFile();break}}else if(h.files)for(u=h.files,k=0,e=u.length;k<e;k++)if(-1!=u[k].type.indexOf("image/png")){m=
u[k];break}if(m)b.preventDefault(),hi5.browser.blobToArray(m,function(J){J=hi5.Base64.enc(J);f.setData("image/png",J);d(f)});else if(t){if(h.types){m=h.types.indexOf?-1!=h.types.indexOf("text/rtf"):h.types.contains("text/rtf");if(e=h.getData("text/rtf"))0==e.charCodeAt(e.length-1)&&(e=e.substring(0,e.length-1)),f.setData("text/rtf",e);g&&(k=g.lastIndexOf("</html>"),k+7<g.length&&(g=g.substring(0,k+7)),f.setData("text/html",g));if(!m||e||g){b.preventDefault();d(f);return}}if("TEXTAREA"==b.target.nodeName)b.preventDefault(),
document.queryCommandSupported("paste")&&(f=y.getClipContent(f)),d(f);else{R&&(R.disableTextInput=!0);ja&&(ja.disableTextInput=!0);b.target.innerHTML="";var n=b.target.style.opacity;b.target.style.opacity=.01;setTimeout(function(){var J=b.target.innerHTML;J&&J!=t&&(f.setData("text/html","<body>"+J+"</body>"),R?R.init():b.target.innerHTML="");d(f);b.target.style.opacity=n;R&&(R.disableTextInput=!1);ja&&(ja.disableTextInput=!1)},300)}}else b.preventDefault(),d(f)}}};this.onCopy=function(d){if(d.target==
z.element){V&&na||cancelDefault(d);var b="copy"==d.type,h=b?46:45;b=b?67:88;Ca||(D(!0,29,"Control"),oa(!0,b,h),oa(!1,b,h),D(!1,29,"Control"));C.isMacOS&&oa(!1,b,h);na&&!ib&&Da&&(999<Date.now()-bc&&(h=w.getClipData(d.type),a(d,h),y.clipData=null,fa=!0),bc=Date.now(),svGlobal.logger.info("clip synced: true"))}};this.onPaste=function(d){if(d.target==z.element){eb&&eb.cancelCtrlV();if(!V||!na)return cancelDefault(d);wb||(fa=!0);if(!p.alwaysPaste&&fa){var b=!0;p.onclipdata&&(b=!p.onclipdata(y.clipData,
!0));b&&setTimeout(fb,300);svGlobal.logger.info("Ctrl+V only");return cancelDefault(d)}fa=!0;y.paste(tc,d);return!0}};this.parseClipData=function(d){var b=d.indexOf(";"),h=d.substring(0,b);d=d.substring(b+1);return{type:h,value:d}};this.getClipContent=function(d){if(!document.queryCommandSupported("paste"))return d;var b=qb(x.pasteTextOnly?"textarea":"div");b.focus();try{if(document.queryCommandEnabled("paste")&&document.execCommand("paste"))return d||(d=new E),x.pasteTextOnly||d.setData("text/html",
"<body>"+b.innerHTML+"</body>"),-1==d.types.indexOf("text/plain")&&d.setData("text/plain",x.pasteTextOnly?b.value:b.innerText||hi5.browser.html2text(b.innerHTML)),d}finally{p.focused=!0,b.parentNode.removeChild(b),z&&z.focus()}return d};this.accessClip=function(d,b){function h(k){d(null)}if("denied"!=y.clipboardRead&&navigator.clipboard.readText){if("text/plain"==b)return navigator.clipboard.readText().then(function(k){var m=new E;m.setData("text/plain",k);d(m)}).catch(h),!0;if(navigator.clipboard.read)return navigator.clipboard.read().then(function(k){k.length?
k[0].getType(b).then(function(m){"image/png"==b?hi5.browser.blobToArray(m,function(t){t=hi5.Base64.enc(t);var e=new E;e.setData("image/png",t);d(e)}):"text/html"==b&&m.text().then(function(t){var e=new E;e.setData("txt/html",t);d(e)}).catch(h)}).catch(h):d(null)}).catch(h),!0}document.queryCommandSupported("paste")||d(null);var f=qb(x.pasteTextOnly?"textarea":"div");f.focus();f.addEventListener("paste",function(k){k.stopPropagation();y.pasteEventFired=!0;y.paste(function(m){p.focused=!0;f.parentNode&&
f.parentNode.removeChild(f);z&&z.focus();d(m)},k)},!1);y.pasteEventFired=!1;if(document.queryCommandEnabled("paste")&&document.execCommand("paste")&&y.pasteEventFired)return!0;setTimeout(function(){fa=!0;y.pasteEventFired||d(null);p.focused=!0;f.parentNode&&f.parentNode.removeChild(f);z&&z.focus()},55);return!1};this.waitingCopyContent=!1;this.copyContent=null;this.waitForCopyContent=function(){y.waitingCopyContent=!0;setTimeout(c,700)};this.prePaste=function(){fa||!document.queryCommandEnabled("paste")&&
!window.clipboardData||y.accessClip(function(d){if(d){var b=0===d.types.length||d.equals(y.clipData),h=b?"":d.types.join(",");b||(b=(b=d.getData("text/plain"))?b.hashCode():0,w.send("880"+h+"\t"+b),y.clipData=d,fa=!0)}})};this.copyImageToClipboard=function(d){var b=d.indexOf('src="')+5,h=d.indexOf('"',b);d=d.substring(b,h);fetch(d).then(function(f){if(f.ok)return f.blob();throw Error("Nework error, access "+stc);}).then(function(f){f=new ClipboardItem({"image/png":f});navigator.clipboard.write([f])}).catch(function(f){svGlobal.logger.warn(f)})};
this.copyToClipboard=function(d,b){var h="text/plain"==d?"textarea":"div",f=!1,k=b.startsWith("<img data-sv-img"),m="text/plain"==d;"text/html"!=d||-1<b.search(/<.*(font|color|img|table|style|class).*>/gmi)||(d="text/plain",m=!0);m&&(window.clipboardData?(window.clipboardData.setData("Text",b),f=!0):"denied"!=y.clipboardWrite&&(navigator.clipboard.writeText(b).catch(function(e){svGlobal.logger.warn(e)}),f=!0));if(!m||!f)if((k||"text/html"==d||"text/rtf"==d)&&"denied"!=y.clipboardWrite&&navigator.clipboard.write)k?
y.copyImageToClipboard(b):(f=null,"text/html"==d?(f=new Blob([b],{type:"text/html"}),h=new Blob([hi5.browser.html2text(b)],{type:"text/plain"}),f=new ClipboardItem({"text/html":f,"text/plain":h})):p.showMessage("Type text/rtf not supported on write"),navigator.clipboard.write([f])),f=!0;else{m=qb(h,!1);if("div"==h)if(m.innerHTML=b,m.focus(),k&&document.body.createControlRange){var t=document.body.createControlRange();t.add(m.childNodes[0]);k=!1}else C.selectEditable(m);else m.value=b,m.focus(),m.select();
try{f=t?t.execCommand("Copy"):document.execCommand("copy",!1,null)}catch(e){}finally{p.focused=!0,m.parentNode.removeChild(m),z&&z.focus()}}fa=!0;if(!f&&p.beforeCopyDialog&&p.beforeCopyDialog(b,__svi18n.info.imgCopyDownload,d))return!0;k=k&&!f&&y.processImgCopy(b);f||!k&&__svi18n.info.userCopy&&p.showMessage({title:__svi18n.info.userCopy,msg:b,timeout:9999,select:!0,format:d,cbYes:function(){navigator.clipboard.writeText(b)}});return f};this.processFileGroup=function(d){if("application/x-filegroup"==
d.type){d=d.value.split("\r\n");var b="",h=0,f=null;d.forEach(function(k){k=k.split("\t");1<k.length&&(b&&(b+=","),b+=k[0],f||(f=k[0]),h+=parseInt(k[1],10))});28<b.length&&(b=b.substring(0,28)+"...");b=b+"<br>Total: "+hi5.tool.bytesToSize(h)+" Qty:"+d.length;__svi18n.info.download&&p.showMessage({title:__svi18n.info.download,msg:b,timeout:9E3,cbYes:function(){this.destroy();w.getFile(f,"clip")},cbNo:function(){this.destroy()}});return!0}return!1};this.processImgCopy=function(d){return 0<d.indexOf("data-sv-img")&&
__svi18n.info.imgCopyDownload?(p.showMessage({title:__svi18n.info.imgCopyDownload,msg:d,timeout:9999}),!0):!1}},Ha=C.isMacOS||C.isiOS,I=new function(){this.afterComposition=this.onComposition=this.ctrlDelayed=this.noKeyStuck=!1;this.preKey={code:0,down:!1};this.preScancode={code:0,down:!1};var a=this.noUnicode=!1,c=!1,d=!1,b={},h=0;this.sendMissKey=function(f){if(!I.noKeyStuck)for(var k in b)if(b[k]){var m=parseInt(k,10);if(f)switch(m){case 42:case 59:if(f.shiftKey)return;break;case 29:case 157:if(Ha){if(f.metaKey)return}else if(f.ctrlKey)return;
break;case 56:case 184:if(f.altKey)return;break;case 219:case 220:if(Ha){if(f.ctrlKey)return}else if(f.metaKey)return}svGlobal.logger.warn("kkk send missing key up: "+m);D(!1,m)}};this.isKeyDown=function(f){return b[f]};this.isKeyDownSent=function(f,k){var m=!0;f||(m=b[k]);f?b[k]=f:delete b[k];return m};this.syncLockKeyStatus=function(f){if(f.getModifierState&&w.sendKeyboardSyncFlags){var k=0;f.getModifierState("CapsLock")&&(k|=4);Ha||C.isCrOS?k|=w.localLockFlags&2:f.getModifierState("NumLock")&&
(k|=2);f.getModifierState("ScrollLock")&&(k|=1);w.sendKeyboardSyncFlags(k)?w.checkLockFlags=!1:w.checkLockFlags=!0}};this.check=function(f){var k=T.getKeyCode(f),m="keydown"==f.type;w.checkLockFlags&&m&&144!=k&20!=k&&145!=k&&I.syncLockKeyStatus(f);17==k&&(ia=m)};this.continue=function(f,k,m){if(29==k&&f)return I.ctrlDelayed=!0,!1;if(I.ctrlDelayed||Ha&&f)if(184==k)I.ctrlDelayed=!1,d=c=!0;else if(I.ctrlDelayed)return I.ctrlDelayed=!1,c||D(!0,29,"Control"),!0;if(29==k){if(c&&!f)return!1}else if(184==
k&&c)return f||(c=!1,a=!0,d&&m&&(D(!0,184,"AltGraph"),D(!1,184,"AltGraph"),d=!1)),m?!1:!0;return!0};this.isAltGr=function(f){return c?(d=!1,!0):a?(a=!1,f?!1:!0):!1};this.isNeedSyncKey=function(){if(w){if(w.checkLockFlags)return h=1,!0;if(5>h)return h++,!0}return!1};this.setNeedSyncKey=function(f){w&&(w.checkLockFlags=f,h=0)}};this.requestCredential=function(a,c){x.closeOnDisconn=!1;var d=null,b=q.frmLogin;if(b)d=q.frmLogin;else{var h=__svi18n.template.login;if(!h){p.showMessage("No value for login template");
return}d=document.createElement("div");d.className="appdlg";d.innerHTML=h;document.body.appendChild(d);b=hi5.$("frmLogin")}var f=Ta(b,"loginDomain"),k="INPUT"==f.tagName.toUpperCase();f&&a.nbDomain&&(k?f.value=a.nbDomain:f.innerHTML=a.nbDomain);var m=new hi5.ui.Lightbox(d);m.onclose=function(){document.body.removeChild(d)};m.show();(a=Ta(b,"loginUser"))&&a.focus();b&&(b.onsubmit=function(){var t=Ta(b,"loginUser").value,e=Ta(b,"loginPassword").value,g=k?f.value:f.innerHTML;m.dismiss();setTimeout(function(){c(t,
e,g)},5);return!1})};var z=null;if(Z)Jb();else{var yb=hi5.$("tmContainer");yb&&yb.parentNode.removeChild(yb)}Z&&!x.toolbar.draggable&&window.addEventListener("scroll",function(){setTimeout(function(){if(Y){var a=q.pcKey;a&&(a.style.top=window.pageYOffset+"px",a.style.left=window.pageXOffset+"px")}p.toolbar&&(p.toolbar.style.top=window.pageYOffset+"px",p.toolbar.style.left=window.pageXOffset+.45*window.innerWidth+"px")},200)},!1);this.setCaretPos=function(a,c){};this.showMessage=function(a,c){a&&x.displayMsg&&
$b.notify("string"==typeof a?{msg:a,timeout:c||0}:a)};this.hideWhenClose="hideWhenClose"in x?x.hideWhenClose:!0;this.setReadOnly=function(a,c){Xb=(V=!a)||!0===c};this.setPlayerMode=function(){wa=!0;p.showToolbar=!1;p.setReadOnly(!0);p.hideWhenClose=!1};this.showTwoFAQR=function(){var a=w.getAppInfo(),c=hi5.$("twofainfo"),d=hi5.$("barcodeDiv"),b=hi5.$("enableTwoFA"),h=hi5.$("disableTwoFA");a.twoFAEnabled?(d.style.display="none",h.style.display="block",b.style.display="none"):(hi5.$("imgBarcode").src=
"data:image/png;base64,"+hi5.Base64.enc(a.twoFAQR),d.style.display="block",h.style.display="none",b.style.display="block");var f=hi5.$("faCode");f.value="";var k=new hi5.ui.Lightbox(c);k.show();b.onclick=h.onclick=function(m){var t=f.value;m=m.target==b?1:0;w.onauthcoderesult=function(e,g){g?k.dismiss():(f.value="",p.showMessage(__svi18n.errorCode.S3021||"Wrong authentication code",5E3))};6!=t.length?hi5.notifications.notify(__svi18n.info.digit6||"It must be a 6 digit number"):w.authWithCode(t,m)}};
this.showTwoFACode=function(){var a=hi5.$("twofacode");if(a){var c=new hi5.ui.Lightbox(a,{noClose:!0});c.show();var d=hi5.$("btnTwoFACode"),b=hi5.$("faAuthCode");b.value="";d.onclick=function(){var h=b.value;6!=h.length?hi5.notifications.notify(__svi18n.info.digit6||"It must be a 6 digit number"):(w.onauthcoderesult=function(f,k){k?c.dismiss():(b.value="",p.showMessage(__svi18n.errorCode.S3021||"Wrong authentication code",5E3));w.onauthcoderesult=null},w.authWithCode(h,2))};b.addEventListener("keyup",
function(h){if(13==h.keyCode||"Enter"==h.code)h.preventDefault(),d.click()})}};this.setAutoScale=function(a){var c="autoScale"in x;c&&(a=x.autoScale);a?(Na(!0),nb("hidden")):c||Na(!1);Aa=a};this.getAutoScale=function(){return Aa};Ra&&Ma(x.cursorNameOnly);this.setTouchpad=function(a){qa=a;var c=hi5.$("touchpadMode");c&&(c.checked=a,c.onchange=function(d){qa=d.target.checked});a&&(r||Ma(x.cursorNameOnly))};this.setExtKeyboard=function(a){if(Z){z.adjust(!0);z.setContentEditable(a?"true":"false");ua=
a?1:0;C.isChrome&&z.setFontSize("2em");a&&z.focus();var c=hi5.$("extKBD");c&&c.checked!=a&&(c.checked=a)}};this.focus=function(){z&&F(z.element)};this.getInputElement=function(){return z};this.scaleTo=function(a,c,d){gb=a;ac=c;vb=d;l&&50<W&&(a/=W,c/=X,vb?(ea=a,la=c):la=ea=c=a=Math.min(a,c),hi5.tool.scale(l.parentNode,a,c))};this.setSize=function(a,c,d){A.isMultiMon||(A.right!=A.left+a-1&&(A.right=A.left+a-1,A.bottom=A.top+c-1),W=a,X=c,Aa||nb(d),l.width=W,l.height=X,Aa?Na(!0):gb&&gb!=a&&p.scaleTo(gb,
ac,vb),Z&&Jb(),z||(z=new Bb),z.adjust())};this.reposition=function(){z.adjust()};this.setController=function(a){w=a;Pa=a.draw;w.sendInput||(w.sendInput=w.send);Z&&C.setOrientaionHandler(function(){Aa?Na(!0):(clearTimeout(cc),cc=setTimeout(function(){window.innerWidth>window.innerHeight!=W>X&&(w.onorientationchange({svSurface:p,innerWidth:window.innerWidth,innerHeight:v(window.innerHeight)}),x.disableScoll||window.scrollTo(0,0))},555))})};this.setFileHandler=function(a){"FileReader"in window||(a=null);
if(a){if(!O&&!wa)if(O=a,O.addEvent("uploaded",function(d,b){!d&&hi5.$("filecontainer")&&dc&16&&(hi5.$("__cancelUpload")&&(hi5.$("__cancelUpload").style.visibility="hidden"),p.fileProgress&&(p.fileProgress.maxValue=0,p.fileProgress.style.display="none"),p.refreshFiles(!ha),!b.cancelled&&__svi18n.file.uploadDone&&b.size&&b.duration&&p.showMessage(__svi18n.file.uploadDone+" "+hi5.tool.bytesToSize(b.size/(b.duration/1E3))+"/s",5E3))}),O.addEvent("uploadstarted",function(d){d&&setTimeout(fb,999)}),hi5.$("filecontainer")){hi5.$("filecontainer").className=
"h5-form";hi5.$("total")&&(p.fileProgress=new hi5.ProgressBar(hi5.$("total")));var c=hi5.$("__cancelUpload");c&&c.addEventListener("click",function(){O.cancelAll()},!1);O.addEvent("beforeupload",function(d,b,h){h||(c&&(c.style.visibility="visible"),p.fileProgress&&(p.fileProgress.style.display="block",p.fileProgress.maxValue+=d.size))});O.addEvent("progress",function(d){p.fileProgress&&p.fileProgress.setProgress(d)})}else pb()}else O=null,p.fileProgress=null,pb(),sa&&(sa.release(),sa=null);Lb();nc()};
this.setFeature=function(a){dc=a;var c,d=!(a&16),b=!(a&65536);(d||wa)&&pb();a&128&&(c=hi5.$("uploadfile"))&&(c.style.visibility="hidden");a&131072&&((c=hi5.$("__sv_download__"))&&c.parentNode.removeChild(c),(c=hi5.$("__sv_view__"))&&c.parentNode.removeChild(c));a&1048576&&(c=hi5.$("__sv_view__"))&&c.parentNode.removeChild(c);a&256||(c=hi5.$("shadowing"))&&c.parentNode.removeChild(c);a&1024||(c=hi5.$("ssParent"))&&c.parentNode.removeChild(c);(b&&d||wa)&&p.setFileHandler(null)};var Oa=new function(){function a(){if(0===
d.length){if(b=!1,!h){var k=hi5.$("_sv_pdf_parent");k&&f&&f.visible()&&f.dismiss();k&&k.parentNode&&setTimeout(function(){k&&k.parentNode&&k.parentNode.removeChild(k)},9999);C.isFirefox&&w&&w.restoreResize&&w.restoreResize()}}else c()}function c(){var k=d.shift();if(k){var m=hi5.$("_sv_pdf_parent"),t=__svi18n.info.printready||"Your document is ready.",e=k.endsWith(".txt");k=(h=!e&&(C.isAndroid||C.isiOS||!!x.showPDFLink))?'<p style="text-align:center;line-height:4em"><a href="'+k+'" target="_blank">'+
t+"</a></p>":(C.isChromeApp?"<webview":"<iframe")+' src="'+k+'" width="100%" height="100%" id="_iFramePDF">'+(C.isChromeApp?"</webview>":"</iframe>");m&&m.visible&&m.visible()&&m.dismiss&&m.dismiss();m&&m.parentNode&&m.parentNode.removeChild(m);m=document.createElement("div");m.style.backgroundColor="white";m.style.width=h?"30%":"70%";m.style.height=h?"4elm":"70%";m.id="_sv_pdf_parent";h?m.style.overflow="scroll":!e&&C.isFirefox&&w.saveResize&&w.saveResize(!1);m.innerHTML=k;document.body.appendChild(m);
f=new hi5.ui.Lightbox(m,{close:{top:"-20px",right:"-15px"}});f.onclose=a;f.show();e&&(m=document.getElementById("_iFramePDF").contentWindow,m.focus(),m.print())}b=!0}var d=[],b=!1,h=!1,f=null;this.clearPDF=function(){a()};this.showPDF=function(k){d.push(k);b||c()}};this.close=function(){xb=!1;svGlobal.logger.info("close ui...");V=!1;bb&&cancelAnimationFrame(bb);Za();za&&(za.release(),za=null);if(document){if(z){var a=z.element;document.removeEventListener("mousemove",kb,!1);a.removeEventListener("mousedown",
jb,!1);document.removeEventListener("mouseup",lb,!1);a.removeEventListener("mouseleave",ab,!1);a.removeEventListener("mouseenter",ab,!1);a.removeEventListener("paste",y.onPaste,!1);a.removeEventListener("copy",y.onCopy,!1);a.removeEventListener("cut",y.onCopy,!1);a.removeEventListener("focus",Db,!1);a.removeEventListener("blur",Ib,!1)}y&&(document.removeEventListener("paste",y.onPaste,!1),document.removeEventListener("copy",y.onCopy,!1),document.removeEventListener("cut",y.onCopy,!1))}if(window){window.removeEventListener("resize",
Hb,!1);window.removeEventListener("beforeunload",Eb,!1);window.removeEventListener("unload",Za,!1);ka=null;r&&(r.parentNode&&r.parentNode.removeChild(r),r=null);p&&p.toolbar&&(p.toolbar.setFadable=null,p.toolbar.startFade=null,p.toolbar.style.display="none",hi5.ui.clean(p.toolbar),p.toolbar=null);try{Ua&&Ua.parentNode&&(Ua.parentNode.removeChild(Ua),Ua=null),z&&(z.remove(),z=null)}catch(d){}}y&&(y.release(),y=null);$a&&($a.release(),$a=null);sa&&(sa.release(),sa=null);ja&&(ja.release(),ja=null);w=
Pa=Ba=ka=r=ha=O=ja=U=I=T=null;p.fileProgress=null;Oa&&Oa.clearPDF();Oa=null;Aa&&p.setAutoScale(!1);Y&&(Y.setVisibility(!1),Y.release(),Y=null);"clearScreen"in x&&!x.clearScreen||P.fillRect(0,0,l.width,l.height);window.svSurface&&window.svSurface==p&&(window.svSurface=null);Fb=!0;if(window&&!wa){try{if(x.closeOnDisconn)window.close();else if(this.hide(),C.isChromeApp){var c=chrome.app.window.current();c&&!x.disableMaxFullScn&&(c.onMaximized.removeListener(Cb),c.isFullscreen()&&(c.restore(),c.restore()))}}catch(d){}p=
l=P=p.context=null;svGlobal.logger.info("closed ui")}};this.setFastCopy=function(a){};this.drawLicense=function(a){if(0!=x.drawLicense){var c=a.charAt(0);P.save();P.font="12pt Arial";P.fillStyle="W"==c?"red":"black";a=a.substring(1);P.fillText(a,10,X-24);P.restore()}};this.drawText=function(a){var c=x.text||{};P.save();var d=l.width,b=l.height;P.fillStyle=c.backgroundFillStyle||"white";P.fillRect(0,0,d,b);var h=20,f=50;"center"==c.textAlign&&(h=d/2,f=b/2);P.font=c.font||"18pt Arial";P.fillStyle=c.fillStyle||
"black";c.textAlign&&(P.textAlign=c.textAlign);c.textBaseline&&(P.textBaseline=c.textBaseline);P.fillText(a,h,f);P.restore()};this.showPDF=function(a){Oa.showPDF(a)};this.showPrinters=function(a){var c=hi5.$("localPrinter");if(c){var d=hi5.$("selectPrinter");w.getPrinters(function(h){var f=d.options;f.length=0;f[0]=new Option(".........");for(var k=0,m=h.length;k<m;k++)f[k+1]=new Option(h[k].name,h[k].driver)});var b=new hi5.ui.Lightbox(c);b.show();b.onclose=function(){if(0<d.selectedIndex){var h=
d.options[d.selectedIndex],f=h.label,k=c.querySelector('[name="driverName"]:checked');h=h.value;k&&(k=k.value,"remote"==k?h="":"local"!=k&&(h=k));k=c.querySelector('[name="isDefault"]').checked;a({name:f,driver:h,isDefault:k})}else a(null)}}};this.hide=function(){p.hideWhenClose&&(l.height=1,l.width=1);z&&z.hide()};var ec=0;this.copyToClip=function(a,c){na&&Da&&(a=y.parseClipData(a),x.copyTextOnly&&"text/plain"!=a.type||y.processFileGroup(a)||(y.waitingCopyContent?y.copyContent=a:(c=a.value,(!x.copyDialog&&
(!c.startsWith("<img data-sv-img")||navigator.clipboard&&navigator.clipboard.write)||y.hasCopyCmd||navigator.clipboard)&&y.copyToClipboard(a.type,c))))};Y=new function(){function a(){d&&(ia?hi5.html.addClass(d,"button_selected"):hi5.html.removeClass(d,"button_selected"));b&&(ya?hi5.html.addClass(b,"button_selected"):hi5.html.removeClass(b,"button_selected"));h&&(Ia?hi5.html.addClass(h,"button_selected"):hi5.html.removeClass(h,"button_selected"))}function c(n){n=n.target;var J=n.innerHTML;J=J.replace(/\u2190/g,
"left").replace(/\u2191/g,"up").replace(/\u2192/g,"right").replace(/\u2193/g,"down");switch(J){case "Ctrl":d||(d=n);ia?D(!1,29,"Control"):D(!0,29,"Control");ia=!ia;a();break;case "Alt":b||(b=n);ya?D(!1,56,"Alt"):D(!0,56,"Alt");ya=!ya;a();break;case "Shift":h||(h=n);Ia?D(!1,42,"Shift"):D(!0,42,"Shift");Ia=!Ia;a();break;case "...":if(n=Ta(q.pcKey,"pc_key_more"))n.style.display="block"==n.style.display?"none":"block";break;case "Start":J="Ctrl+Esc";default:p.writeKeyComb(J),Y.resetModifier()}}var d=
null,b=null,h=null,f={ctrl:!1,alt:!1,shift:!1};this.release=function(){f=null};this.setStickyKey=function(n){f=n};this.setVisibility=function(n){if(n){if(ua=Date.now(),n=q.pcKey)n.style.display="block",n.style.top=window.pageYOffset+"px",ja&&(ja.setValue("`\t`"),ja.select())}else if(ua=0,n=q.pcKey)n=hi5.$("shortcuts"),n&&n.checked||(k.style.display="none")};this.resetModifier=function(){ya&&!f.alt&&(ya=!1,D(!1,56,"Alt"));ia&&!f.ctrl&&(ia=!1,D(!1,29,"Control"));Ia&&!f.shift&&(Ia=!1,D(!1,42,"Shift"));
a()};var k=q.pcKey;if(k){var m=k.getElementsByTagName("span"),t=m.length,e=C.isFirefox?"mousedown":"touchstart";"ontouchstart"in window||(navigator.pointerEnabled?e="pointerdown":navigator.msPointerEnabled&&(e="MSPointerDown"));for(var g=0;g<t;g++){var u=m[g];u.className="button";u.addEventListener(e,c,!1);"mousedown"!=e&&u.addEventListener("mousedown",c,!1)}k.style.position="absolute"}};this.setStickyKey=function(a){Y.setStickyKey(a)};var fc=hi5.$("shortcuts");fc&&fc.addEventListener("change",function(a){Y.setVisibility(a.target.checked)});
this.setKeysVisibility=function(a){Y&&Y.setVisibility(a)};this.setDirectory=function(a){var c=hi5.$("parentPath");c&&"."!=a&&(c.currentDir=a)};this.refreshFiles=function(a){a?(xa(".",null),(a=document.getElementById("__sv_folder__"))&&!a.onclick&&O.mkdirs&&(a.onclick=function(){var c=document.getElementById("__sv_folder_name_");c&&c.value&&(O.mkdirs(c.value),xa(".",null),c.value="")})):ha&&ha.visible()?xa(".",ha):Kb(null)};this.showConnectonInfo=function(){var a=w.getAppInfo(),c=hi5.$("numericId");
c&&(c.innerHTML=a.numericId);if(c=hi5.$("connectingTo"))c.innerHTML=a.server;if(c=hi5.$("joinLink"))if(c.href=c.innerHTML=a.joinLink,c=document.getElementById("shareSession"))navigator.share?c.onclick=function(d){navigator.share({url:a.joinLink})}:c.style.display="none";c=new hi5.ui.Lightbox(hi5.$("appinfo"));c.show();z&&(z.element.oncontextmenu=null,z.element.onselectstart=null);c.onclose=Gb;c=hi5.$("btnTwoFA");hi5.$("twofainfo")&&c&&(a.twoFAEnabled||a.twoFAQR?c.onclick=function(){p.showTwoFAQR()}:
c.disabled=!0);if(c=hi5.$("attachPrinter"))c.disabled=!w.getAgentStatus||1!=w.getAgentStatus()};this.setupTwoFA=function(a){};this.processLink=function(a){function c(h){window.open(a);h.target.parentNode.removeChild(h.target)}if(p.beforeOpenLink)return p.beforeOpenLink(a);if(!p.toolbar)return!1;clearTimeout(ec);var d=p.toolbar,b=d.getButton("_svLinkInfo");b?b.onclick=c:(b=d.addButton(x.img.link?x.img.link:"link.png",c),b.id="_svLinkInfo");b.title=a;d.startFade();ec=setTimeout(function(){p.toolbar&&
p.toolbar.removeButton("_svLinkInfo")},1E4);return!0};this.setUnicode=function(a){z&&(!a&&Z&&(C.isiOS||C.isAndroid)&&(a=!0),svGlobal.logger.info("Unicode:"+a),R.onkeydown=R.onkeyup=a?pc:Rb,R.ontextinput=a?rc:null,R.unicode=a)&&(R.oncomposition=qc)};this.forceScancode=function(a){Ub=a};this.setTouchRemoting=function(a){!0===a?(Ba=new hc(p,l),svGlobal.logger.info("touch remoting"),__svi18n.info.touchremoting&&p.showMessage(__svi18n.info.touchremoting)):Ba=new Ab(p)};this.setClipboard=function(a,c,d){(na=
a)?(Da=void 0==c?!0:c,wb=void 0==d?!0:d,y.init()):wb=Da=!1;Ka=a?!C.isChromeApp&&!x.copyDialog&&!x.directClipAccess&&!C.isIE:!1};this.setJoinMode=function(a){w.setJoinMode(a)};this.requestControl=function(){w.requestControl()};this.repaint=function(a,c,d,b){A.isMultiMon?(a<A.left&&(a=A.left),c<A.top&&(c=A.top),d>A.right&&(d=A.right),b>A.bottom&&(b=A.bottom),a<=A.right&&c<=A.bottom&&(a=w.refresh(a,c,d,b))&&P.putImageData(a.imgData,a.left-A.left,a.top-A.top,0,0,a.width,a.height)):(a=w.refresh(a,c,d,
b))&&P.putImageData(a.imgData,a.left,a.top,0,0,a.width,a.height)};this.running=function(){return xb};this.run=function(a,c,d,b){function h(f){f.target.removeEventListener("click",h,!1);w.send("884")}xb=!0;T.converMacCtrl=!1!==c;T.mapCmdToCtrl=!1!==b;I.noKeyStuck=!!d;!T.mapCmdToCtrl&&C.isMacOS&&B();z||(z=new Bb);z.adjust();$b.clearAll();3758162961!=a&&3758162962!=a||!z||z.setContentEditable("false");T.setLayout(a);a=-1!=[99997,99998,99999].indexOf(a);void 0==x.closeOnDisconn&&(x.closeOnDisconn=!!window.opener&&
!C.isChromeApp);x.disableScoll||window.scrollTo(0,0);Lb();lc();c=z.element;wa||(Ba=new Ab(p),za=new pa(c),za.ontouch=oc,za.onmousedown=jb,za.onmousemove=kb,za.onmouseup=lb,c.addEventListener("mouseleave",ab,!1),c.addEventListener("mouseenter",ab,!1),ba(c,uc,!1),c.addEventListener("paste",y.onPaste,!1),na&&Ka&&Da&&(c.addEventListener("copy",y.onCopy,!1),c.addEventListener("cut",y.onCopy,!1)));!1!==x.autoFocus&&F(c);p.setUnicode(a);this.drawText(__svi18n.wait);if(p.onstart)p.onstart(l);c.addEventListener("click",
h,!1);Pa&&(bb=requestAnimationFrame(Mb));z.adjust();x.disableScoll||window.scrollTo(0,0)};var Nb=x.animation||42;C.isIE&&(Nb*=2);this.moveCursorBy=this.movCursorBy=Ob;this.moveCursor=function(a,c,d,b,h,f){a-=A.left;c-=A.top;0>a||0>c||a>=W||c>=X||(r||Ma(x.cursorNameOnly),r.__visible||r.__setVisible(!0),r.scrX=a,r.scrY=c,r.moveCursor(a+A.offX,c+A.offY,b,h,f),V&&!d&&w.sendInput("82"+a+"\t"+c),A.x=a,A.y=c)};this.switchSoftKeyboard=sb;this.isSoftKeyboardOn=function(){return Ja};var gc=hi5.$("svTouchInput");
gc&&gc.addEventListener("click",function(){sb()},!1);this.touchstart=function(a){switch(a.pointes){case 1:qa?(r||Ma(x.cursorNameOnly),tb("touchstart",a.screenX,a.screenY,!a.flick)):a.flick&&!Ea()||Qa(a.x,a.y,0);break;case 2:cb=a.screenX,Ga=a.screenY}};this.touchmove=function(a){switch(a.pointes){case 1:qa?tb("touchmove",a.screenX,a.screenY,!a.flick):(!a.flick||Ea())&&Wb(a.x,a.y);break;case 2:19<Math.abs(a.screenY-Ga)&&(Yb(a.x,a.y,0<a.screenY-Ga?0:1),cb=a.screenX,Ga=a.screenY)}};this.touchend=function(a){switch(a.pointes){case 1:qa?
tb("touchend",a.screenX,a.screenY,!a.flick):(Fa(a.x,a.y,!0),a.flick&&!Ea()||Sa(a.x,a.y,0));break;case 2:if(!a.moved){var c=qa?r.scrX:a.x;a=qa?r.scrY:a.y;Fa(c,a);Qa(c,a,2);Sa(c,a,2)}break;case 3:if(a.gesture)switch(a.gesture){case "OPEN":D(!0,219);D(!0,200);D(!1,200);D(!1,219);break;case "CLOSE":D(!0,219);D(!0,208);D(!1,208);D(!1,219);break;case "LEFT":D(!0,56);D(!0,1);D(!1,1);D(!1,56);break;case "RIGHT":D(!0,42);D(!0,56);D(!0,1);D(!1,1);D(!1,56);D(!1,42);break;case "UP":D(!0,42);D(!0,219);oa(!0,77,
50);oa(!1,77,50);D(!1,219);D(!1,42);break;case "DOWN":D(!0,219),oa(!0,77,50),oa(!1,77,50),D(!1,219)}else sb()}};this.flick=function(a){switch(a.from){case 4:w.sendInput("840\t209");w.sendInput("8449152\t209");break;case 2:w.sendInput("840\t201"),w.sendInput("8449152\t201")}};this.longpress=function(a){qa&&(a.pointes=2);switch(a.pointes){case 1:var c=a.x;a=a.y;Fa(c,a);Qa(c,a,2);Sa(c,a,2);break;case 2:r&&(Qa(r.scrX,r.scrY,2,1),Sa(r.scrX,r.scrY,2,1))}};this.redirectTouches=function(a){if(V){for(var c=
a.length,d,b="90"+c,h=0;h<c;h++)d=a[h],b=b+"\t"+d.contactId+";"+d.contactFlags+";"+Math.floor(d.x/ea)+";"+Math.floor(d.y/la);w.send(b)}};var db=0;this.setIgnorePaste=function(a){fa=a};this.processClipReq=function(a,c){if(!na)return w.send("881ERROR\t"),!0;var d=y.clipData;c||(c=sc);return d||fa?(c(d,a),!0):y.accessClip(function(b){c(b,a)},a)};var eb=C.isIE?new function(){var a;this.sendCtrlVLater=function(){a=setTimeout(fb,333)};this.cancelCtrlV=function(){clearTimeout(a)};return this}:null;this.getMousePosition=
function(){return A};this.writeKeyComb=function(a){w.writeKeyComb(a)};this.setCursor=function(a){a&&!x.disableCursor&&(ka=a,r&&r.setCursor(a),r&&Ra&&!a.system&&(r.__setVisible(!0),Fa(A.x,A.y,!0)),wa||(a.result||(a.result=x.cursorNameOnly?"none":vc(a)),z?z.element.style.cursor=a.result:l.style.cursor=a.result))};this.setVisible=function(a,c){var d=a?"visible":"hidden";"number"==typeof c?setTimeout(function(){l.style.visibility=d},c):l.style.visibility=d};this.initWhiteboard=function(a,c){var d=l.parentNode,
b=d.querySelector('canvas[name="svWhiteboard"]');b||(b=document.createElement("canvas"),b.setAttribute("name","svWhiteboard"),b.width=a||W,b.height=c||X,b.style.zIndex=80,a=z.element,b.style.position=a.style.position,b.style.left=a.style.left,b.style.top=a.style.top,d.appendChild(b));return b};this.removeWhiteboard=function(){var a=l.parentNode,c=a.querySelector('canvas[name="svWhiteboard"]');c&&a.removeChild(c)};this.requestFullscreen=function(a){document.fullscreenElement?(document.exitFullscreen(),
document.removeEventListener("fullscreenchange",Zb,!1)):(!1!==a&&document.addEventListener("fullscreenchange",Zb,!1),document.body.requestFullscreen())};this.requestUsbDevices=function(a,c){var d=[],b=document.getElementById("usbPicker"),h=document.getElementById("addUSB"),f=document.getElementById("selectedUSB");h.onclick=function(){navigator.usb.requestDevice(a).then(function(m){d.find(function(t){return t.serialNumber==m.serialNumber&&t.vendorId==m.vendorId&&t.productId==m.productId})||m.open().then(function(){d.push(m);
var t=document.createElement("option");t.innerHTML=m.productName||"Unknown USB device";f.appendChild(t);m.close()}).catch(function(t){hi5.notifications.notify("Failed to open "+m.productName+" Error:"+t)})})};var k=new hi5.ui.Lightbox(b);k.onclose=function(){h.onclick=null;f.length=0;c(d)};document.getElementById("frmUsbPicker").onsubmit=function(m){m.preventDefault();k.dismiss();return!1};k.show()}}svGlobal.LocalInterface||(svGlobal.LocalInterface=LocalInterface);
svGlobal.rdpFile={loadRdpFile:function(l,q){var v=q.elements,F=l.split("\r\n");2>F.length&&(F=l.split("\n"));if(2>F.length)return!1;l=hi5.$("gateway");var E=l.value;q.reset();l.value=E;q=0;for(l=F.length;q<l;q++){var B=F[q];E=B.indexOf(":");var N=B.substring(0,E);B=B.substring(E+3);N=N.toLowerCase();switch(N){case "full address":E=B.indexOf(":");0<E?(v.server.value=B.substring(0,E),v.port.value=B.substring(E+1)):v.server.value=B;break;case "username":v.user.value=B;break;case "domain":v.domain.value=
B;break;case "connect to console":v.useConsole.checked="0"!=B;break;case "desktopwidth":v.width.value=B;break;case "desktopheight":v.height.value=B;break;case "session bpp":v.server_bpp.value=B;break;case "audiomode":v.playSound.value=B;break;case "alternate shell":0<B.length&&(v.command.value=B,hi5.$("app").checked||(hi5.$("shell").checked=!0));break;case "shell working directory":v.directory=B;break;case "redirectclipboard":v.mapClipboard.checked="0"!=B;break;case "redirectprinters":v.mapPrinter.checked=
"0"!=B;break;case "server port":0<B.length&&(v.port.value=B);break;case "disable wallpaper":v.background.checked="0"==B;break;case "disable themes":v.styles.checked="0"==B;break;case "disable menu anims":v.animation.checked="0"==B;break;case "disable full window drag":v.contents.checked="0"==B;break;case "allow font smoothing":v.smoothfont.checked="0"!=B;break;case "allow desktop composition":v.composition.checked="0"!=B;break;case "bitmapcachepersistenable":v.bitmap.checked="0"!=B;break;case "remoteapplicationprogram":v.exe.value=
B;break;case "remoteapplicationcmdline":v.args.value=B;break;case "remoteapplicationmode":hi5.$("app").checked="1"==B;break;case "loadbalanceinfo":v.loadBalanceInfo.value=B}}return!0},handleFiles:function(l,q){if(1!=l.length)hi5.notifications.notify({msg:"Please one file only"});else{var v=l[0];l=v.name;var F=l.length;if(4<F&&".rdp"==l.substring(F-4).toLowerCase()){var E=new FileReader,B=!1;E.onload=function(N){!(N=N.target.result)||svGlobal.rdpFile.loadRdpFile(N,q)||B||(B=!0,E.readAsText(v))};E.readAsText(v,
"UTF-16LE")}else hi5.notifications.notify({msg:"Sorry, Please .rdp file only"})}}};
function initDragDrop(l,q){function v(B){svGlobal.rdpFile.handleFiles(B.target.files,q)}if("FileReader"in window){var F=l.style.backgroundColor,E=hi5.$("rdpfile");E&&E.addEventListener("change",v,!1);l.addEventListener("dragover",function(B){cancelDefault(B);l.style.backgroundColor="yellow"},!1);l.addEventListener("dragleave",function(B){cancelDefault(B);l.style.backgroundColor=F},!1);l.addEventListener("drop",function(B){cancelDefault(B);l.style.backgroundColor=F;svGlobal.rdpFile.handleFiles(B.dataTransfer.files,
q)},!1)}}svGlobal.util.initDragDrop=initDragDrop;
svGlobal.util.initMapDisk=svGlobal.util.MapDisk=function(l,q,v){function F(N){cancelDefault(N);q&&("0.6"!=l.style.opacity&&(l.style.opacity="0.6"),l.style.backgroundColor="yellow")}function E(N){cancelDefault(N);q&&(l.style.opacity=l.__oldOpacity,l.style.backgroundColor=l.__oldColor)}function B(N){cancelDefault(N);if(q){l.style.opacity=l.__oldOpacity;l.style.backgroundColor=l.__oldColor;var ba=hi5.file.getEntries(N);!ba.length||"file:"==location.protocol&&!hi5.browser.isElectron&&hi5.browser.isChrome?
q.addFiles?q.addFiles(N.dataTransfer.files,v):q.addFile(N.dataTransfer.files[0]):hi5.file.getFilesFromEntries(ba,function(pa){q.addFiles?q.addFiles(pa,v):q.addFile(pa[0])})}}"FileReader"in window&&(l.__oldColor=l.style.backgroundColor,l.__oldOpacity=l.style.opacity,l.addEventListener("dragover",F,!1),l.addEventListener("dragleave",E,!1),l.addEventListener("drop",B,!1),this.release=function(){l.removeEventListener("dragover",F,!1);l.removeEventListener("dragleave",E,!1);l.removeEventListener("drop",
B,!1);l=q=null})};
svGlobal.util.getServerArgs=function(l){var q=window.opener;if(!l)try{q&&q.__sparkUser&&q.__sparkUser.server&&(l=q.__sparkUser.server),!l&&q.sparkServer&&(l=q.sparkServer)}catch(v){}l?(q=l.rdp||l.vnc||l.ssh||l.telnet||null)&&!l.server&&(q.gateway=l.gateway,q.session=l.session,q.account=l.account,q.server=l.id,q.displayName=l.displayName,q.shadowing=l.shadowing,q.user=q.username||"",q.pwd=q.password||"",q.useConsole=q.console||!1,q.server_bpp=q.color,q.legacyMode=q.leagacyMode||q.legacyMode||!1,q.exe=
q.remoteProgram||"",q.args=q.remoteArgs||"",q.startProgram=0<q.exe.length?"app":q.command&&0<q.command.length?"shell":"noapp",l.keyboard&&(q.keyboard=l.keyboard),l=q):l=hi5.browser.cookie2Obj();return l};(function(){function l(q){q=document.getElementsByClassName("ver");for(var v=q.length,F=0;F<v;F++)q[F].innerHTML=svGlobal.version;window.removeEventListener("load",l,!1)}window.addEventListener("load",l,!1)})();svGlobal.gatewayError=function(l,q){(l=__svi18n.errorCode["S"+l])?q&&(l+="; "+q):l=q;hi5.notifications.notify(l)};
svGlobal.ui={initMonitors:function(l){if(!("getScreenDetails"in window&&screen.isExtended))return!1;window.getScreenDetails().then(function(q){q.screens.forEach(function(v,F){var E=document.createElement("div"),B=document.createElement("input");B.type="checkbox";B.value=F;var N=document.createElement("label");F=F+": "+v.width+" x "+v.height+"; ("+v.left+","+v.top+")";v==q.currentScreen&&(F+=" *");N.innerHTML=F;B.onclick=function(){if(B.checked){svGlobal.monitors=svGlobal.monitors||[];var ba=q.screens[parseInt(B.value)],
pa=window.open("monitor.html","","left="+ba.left+",top="+ba.top+",width="+ba.width+",height="+ba.height+",fullscreen=yes,directories=no,location=no,menubar=no,resizable=no,scroolbars=no,status=no,toolbar=no");pa.moveTo(ba.left,ba.top);pa.resizeTo(ba.width,ba.height);pa.document.body.requestFullscreen().catch(function(Ea){svGlobal.logger.info(Ea)});svGlobal.monitors.push(pa)}};E.appendChild(B);E.appendChild(N);l.appendChild(E)})}).catch(function(q){hi5.notifications.notify("Failed to get screen details."+
q)});return!0}};svGlobal.logger.info("ver:"+svGlobal.version);(1>window.devicePixelRatio||1<window.devicePixelRatio&&2>window.devicePixelRatio)&&svGlobal.logger.info("Please make sure the zoom level of your browser is 100%");
