var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(l,q,v){if(null==l)throw new TypeError("The 'this' value for String.prototype."+v+" must not be null or undefined");if(q instanceof RegExp)throw new TypeError("First argument to String.prototype."+v+" must not be a regular expression");return l+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(l,q,v){if(l==Array.prototype||l==Object.prototype)return l;l[q]=v.value;return l};
$jscomp.getGlobal=function(l){l=["object"==typeof globalThis&&globalThis,l,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var q=0;q<l.length;++q){var v=l[q];if(v&&v.Math==Math)return v}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(l,q){var v=$jscomp.propertyToPolyfillSymbol[q];if(null==v)return l[q];v=l[v];return void 0!==v?v:l[q]};$jscomp.polyfill=function(l,q,v,B){q&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(l,q,v,B):$jscomp.polyfillUnisolated(l,q,v,B))};
$jscomp.polyfillUnisolated=function(l,q,v,B){v=$jscomp.global;l=l.split(".");for(B=0;B<l.length-1;B++){var E=l[B];if(!(E in v))return;v=v[E]}l=l[l.length-1];B=v[l];q=q(B);q!=B&&null!=q&&$jscomp.defineProperty(v,l,{configurable:!0,writable:!0,value:q})};
$jscomp.polyfillIsolated=function(l,q,v,B){var E=l.split(".");l=1===E.length;B=E[0];B=!l&&B in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var C=0;C<E.length-1;C++){var O=E[C];if(!(O in B))return;B=B[O]}E=E[E.length-1];v=$jscomp.IS_SYMBOL_NATIVE&&"es6"===v?B[E]:null;q=q(v);null!=q&&(l?$jscomp.defineProperty($jscomp.polyfills,E,{configurable:!0,writable:!0,value:q}):q!==v&&($jscomp.propertyToPolyfillSymbol[E]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(E):$jscomp.POLYFILL_PREFIX+E,E=
$jscomp.propertyToPolyfillSymbol[E],$jscomp.defineProperty(B,E,{configurable:!0,writable:!0,value:q})))};$jscomp.polyfill("String.prototype.startsWith",function(l){return l?l:function(q,v){var B=$jscomp.checkStringArgs(this,q,"startsWith");q+="";var E=B.length,C=q.length;v=Math.max(0,Math.min(v|0,B.length));for(var O=0;O<C&&v<E;)if(B[v++]!=q[O++])return!1;return O>=C}},"es6","es3");
$jscomp.polyfill("String.prototype.endsWith",function(l){return l?l:function(q,v){var B=$jscomp.checkStringArgs(this,q,"endsWith");q+="";void 0===v&&(v=B.length);v=Math.max(0,Math.min(v|0,B.length));for(var E=q.length;0<E&&0<v;)if(B[--v]!=q[--E])return!1;return 0>=E}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(l){return l?l:function(q,v,B){var E=this.length||0;0>v&&(v=Math.max(0,E+v));if(null==B||B>E)B=E;B=Number(B);0>B&&(B=Math.max(0,E+B));for(v=Number(v||0);v<B;v++)this[v]=q;return this}},"es6","es3");$jscomp.typedArrayFill=function(l){return l?l:Array.prototype.fill};$jscomp.polyfill("Int8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Uint8ClampedArray.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Float32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Float64Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.findInternal=function(l,q,v){l instanceof String&&(l=String(l));for(var B=l.length,E=0;E<B;E++){var C=l[E];if(q.call(v,C,E,l))return{i:E,v:C}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(l){return l?l:function(q,v){return $jscomp.findInternal(this,q,v).v}},"es6","es3");var svGlobal=svGlobal||{logger:new hi5.Logger,util:{}};svGlobal.version="7.0.0";svGlobal.build="1093";
function cancelDefault(l){l.preventDefault&&l.preventDefault();l.stopPropagation&&l.stopPropagation();return!1}
function LocalInterface(l,q){function v(a){var b=a-hi5.browser.innerHeight;10<b&&22>b&&(a=hi5.browser.innerHeight);return a}function B(a){w.detectInput&&Z&&ka&&(La||"text"==ka.system||"none"==ka.system?setTimeout(function(){jb(!0)},5):setTimeout(function(){jb(!1)},5));if(document.activeElement!=a||!p.focused){for(var b=a,d,c=[];b.parentElement;)if(b=b.parentElement,d=getComputedStyle(b))d.getPropertyValue("overflow"),"block"==d.getPropertyValue("display")&&c.push([b,b.scrollTop,b.scrollLeft]);a.focus();
if(c.length){a=0;for(d=c.length;a<d;a++){b=c[a];if(b[0].scrollTop!=b[1]||b[0].scrollLeft!=b[2])b[0].scrollTop=b[1],b[0].scrollLeft=b[2];c[a]=null}c=null}}}function E(){var a=[];this.sent=0;this.types=[];var b=this;this.datas=a;this.setData=function(d,c){if("text/plain"==d||"text/html"==d)2<c.length&&"`\t`"==c.substring(0,3)&&(c=c.substring(3)),c=c.replace(/\r?\n/g,"\r\n");b.types.push(d);a.push(c)};this.getData=function(d){var c=a[b.types.indexOf(d)];c||"text/richtext"!=d||(c=a[b.types.indexOf("text/rtf")]);
return c};this.removeData=function(d){d=b.types.indexOf(d);-1!=d&&(b.types.splice(d,1),a.splice(d,1))};this.equals=function(d){if(!d||!hi5.Arrays.equals(b.types,d.types))return!1;for(var c,f,g=b.types,m=0,k=g.length;m<k;m++)if(c=g[m],f=b.getData(c),c=d.getData(c),f!=c)return!1;return!0}}function C(){kb=!0;Ma=!1;if(A){var a=A.element;a.removeEventListener("copy",y.onCopy,!1);a.removeEventListener("cut",y.onCopy,!1)}svGlobal.logger.info("Async clipboard enabled.")}function O(a){function b(){return n?
a.value:D.isFirefox?a.textContent:a.innerText}function d(){e&&(h="",e.setValue(""))}function c(G){t=G.keyCode;if(e.onkeydown)e.onkeydown(G)}function f(G){if(e.onkeyup)e.onkeyup(G);G=G.keyCode;(13==G||32==G&&32==t)&&setTimeout(d,100)}function g(G){if(e.onbackspace)for(var Q=0;Q<G;Q++)e.onbackspace()}function m(G){if(!e.disableTextInput){G.stopPropagation();G=b();var Q=G.length;if(G!=h){var aa=h.length,S=G.indexOf(h);if(G&&0===S){if(G=G.substring(aa),0<G.length&&e.ontextinput&&(e.ontextinput({data:G,
target:a}),"."==G)){d();return}}else if(S=h.indexOf(G),0===S)8!=t&&g(aa-Q);else if(D.isAndroid&&g(aa),0<G.length&&e.ontextinput)e.ontextinput({data:G,target:a});""===b()&&setTimeout(d,100);h=b()}}}function k(G){if(!e.disableTextInput&&G.data&&(G.stopPropagation(),D.isIE&&G.preventDefault(),e.ontextinput))e.ontextinput(G)}function u(G){if(e.oncomposition)e.oncomposition(G)}this.unicode=!1;var e=this,h="",t=0,n="INPUT"==a.nodeName||"TEXTAREA"==a.nodeName,J="DIV"==a.nodeName;this.setValue=function(G){var Q=
e.disableTextInput;e.disableTextInput=!0;n?a.value=G:J&&(a.innerHTML=G);e.disableTextInput=Q};this.init=d;this.disableTextInput=!1;d();a.addEventListener("keydown",c,!1);a.addEventListener("keyup",f,!1);a.addEventListener("keypress",function(G){if(e.onkeypress)e.onkeypress(G)},!1);D.isAndroid&&D.isChrome?(a.addEventListener("input",m,!1),a.addEventListener("mouseup",d,!1)):window.TextEvent?(a.addEventListener("textInput",k,!1),a.addEventListener("textinput",k,!1)):hi5.tool.hasProperty(InputEvent,
"data")?a.addEventListener("input",k,!1):(a.addEventListener("input",m,!1),a.addEventListener("mouseup",d,!1));a.addEventListener("compositionstart",u,!1);a.addEventListener("compositionend",u,!1);a.addEventListener("compositionupdate",u,!1);this.release=function(){e=null;a.removeEventListener("keydown",c,!1);a.removeEventListener("keyup",f,!1);a.removeEventListener("input",m,!1);a.removeEventListener("focus",d,!1);a.removeEventListener("textInput",k,!1);a.removeEventListener("textinput",k,!1);a=
null};this.select=function(){Db(a)}}function ba(a,b,d){var c=0,f=0;a.addEventListener("wheel",function(g){var m=Xa(g);var k=g.deltaMode||0;var u=!!g.deltaX||!!g.wheelDeltaX;g.preventDefault();g.stopPropagation();var e=1==k?1:"deltaY"in g?40:"wheelDelta"in g?120:0;if(e){var h=Date.now();100<h-f&&(c=0);g=-g.deltaY||-g.deltaX||g.wheelDelta;3==k&&(g*=24*e);0!=g&&(c+=g,k=c/e|0,c%=e,0!==k&&b(k,m,u));f=h}else k=-g.detail,32768==Math.abs(k)&&(g=window.innerHeight/40|0,k=0>k?-g:g),b(k,m,!1)},!0)}function qa(a){function b(e){if(!m&&
k.onmousedown)k.onmousedown(e)}function d(e){if(!m&&k.onmousemove)k.onmousemove(e)}function c(e){if(p&&p.focused)if(m)m=!1;else if(k.onmouseup)k.onmouseup(e)}function f(e){if(w.releaseOnMouseOut)for(e=0;5>e;e++)z.mouseDown[e]&&(Na("81",z.x+"\t"+z.y+"\t"+e),z.mouseDown[e]=!1)}function g(e){"touchstart"==e.type&&(m=!0);if(k.ontouch)k.ontouch(e)}var m=!1,k=this,u=navigator.pointerEnabled||navigator.msPointerEnabled||!1;"ontouchstart"in window||!u?(a.addEventListener("touchstart",g,!1),a.addEventListener("touchend",
g,!1),a.addEventListener("touchmove",g,!1),a.addEventListener("touchcancel",g,!1),document.addEventListener("mousemove",d,!1),a.addEventListener("mousedown",b,!1),a.addEventListener("mouseout",f,!1),document.addEventListener("mouseup",c,!1)):navigator.pointerEnabled?(a.addEventListener("pointerdown",g,!1),a.addEventListener("pointerup",g,!1),a.addEventListener("pointermove",g,!1),a.addEventListener("pointerout",f,!1),a.addEventListener("pointercancel",g,!1)):navigator.msPointerEnabled&&(a.addEventListener("MSPointerDown",
g,!1),a.addEventListener("MSPointerUp",g,!1),a.addEventListener("MSPointerMove",g,!1),a.addEventListener("MSPointerCancel",g,!1));this.release=function(){"ontouchstart"in window||!u?(a.removeEventListener("touchstart",g,!1),a.removeEventListener("touchend",g,!1),a.removeEventListener("touchmove",g,!1),a.removeEventListener("touchcancel",g,!1),document.removeEventListener("mousemove",d,!1),a.removeEventListener("mousedown",b,!1),document.removeEventListener("mouseup",c,!1)):navigator.pointerEnabled?
(a.removeEventListener("pointerdown",g,!1),a.removeEventListener("pointerup",g,!1),a.removeEventListener("pointermove",g,!1),a.removeEventListener("pointercancel",g,!1)):navigator.msPointerEnabled&&(a.removeEventListener("MSPointerDown",g,!1),a.removeEventListener("MSPointerUp",g,!1),a.removeEventListener("MSPointerMove",g,!1),a.removeEventListener("MSPointerCancel",g,!1));this.onmouseup=this.onmousemove=this.ontouch=this.onmousedown=null}}function Ga(){return ra?!0:!va&&W<=window.innerWidth&&X<=
window.innerHeight}function kc(a){function b(g,m){for(var k,u=g.length,e=Array(u),h=0;h<u;h++){k=g[h];var t=Ya(k.clientX,k.clientY,l),n=h;k=k.identifier;if(!(256>k)){var J=c.indexOf(k);-1!=J?k=J:(c.push(k),k=c.length-1)}e[n]={contactId:k,contactFlags:m,x:t.x,y:t.y}}return e}var d,c=[],f=!1;this.handle=function(g){var m=g.type,k=g.touches,u=g.changedTouches;cancelDefault(g);switch(m){case "touchstart":f=!1;d=g=b(k,25);break;case "touchmove":g=b(u,26);d||(d=b(k||u,25));k=!1;if(0<d.length&&1==g.length){a:{u=
d.length;for(m=0;m<u;m++)if(d[m].contactId==g[0].contactId){u=m;break a}u=-1}-1!=u&&d[u].x==g[0].x&&d[u].y==g[0].y&&(k=!0)}if(k)break;else 0<d.length&&(a.redirectTouches(d),d.length=0);a.redirectTouches(g);f=!0;break;case "touchend":if(f)g=b(u,4);else{a.redirectTouches(d);g=d.length;for(k=0;k<g;k++)d[k].contactFlags=4;g=d}a.redirectTouches(g);c.length=d.length=0;break;case "touchcancel":a.redirectTouches(b(u,34)),c.length=d.length=0}}}function Eb(a){function b(H){var K=H[1].screenX-H[0].screenX;H=
H[1].screenY-H[0].screenY;return Math.sqrt(K*K+H*H)}function d(H,K){for(var L=0,N=H.length;L<N;L++)if(H[L].identifier==K)return H[L];return null}function c(H){this.identifier=H.pointerId;this.clientX=H.clientX;this.clientY=H.clientY;this.pageX=H.pageX;this.pageY=H.pageY;this.screenX=H.screenX;this.screenY=H.screenY}var f=0,g=0,m=0,k=0,u=!1,e=0,h=0,t=0,n=0,J=!1,G=!1,Q=3,aa=!1;D.isIE&&(Q*=3);this.delay=!1;var S=[],Za=this;this.handlePointer=function(H){if(H.pointerType==H.MSPOINTER_TYPE_MOUSE||"mouse"==
H.pointerType)switch(H.type){case "MSPointerDown":case "pointerdown":lb(H);break;case "pointermove":case "MSPointerMove":mb(H);break;case "pointerup":case "MSPointerUp":nb(H)}else H.touches=H.changedTouches=[new c(H)],Za.handle(H)};this.handle=function(H){var K=H.type,L=H.touches;var N=H.changedTouches;var ca=0,da=0;switch(K){case "touchstart":case "MSPointerDown":case "pointerdown":aa=!1;g="touchstart"==K?L.length:g+1;G=!1;k=Date.now();u=1==g&&200>k-m;K=L[0];f=K.identifier;N=Ya(K.clientX,K.clientY,
l);e=N.x|0;h=N.y|0;J=!0;2!=L.length?aa=!1:(N=L[1].screenX-L[0].screenX,aa=100<Math.abs(L[1].screenY-L[0].screenY)||350<Math.abs(N));(u||1<g&&!aa)&&cancelDefault(H);if(3==g){ca=K=N=0;da=9999;for(var na=0,ob=L.length;na<ob;na++)L[na].screenY>ca&&(ca=L[na].screenY,N=na),L[na].screenY<da&&(da=L[na].screenY,K=na);S=[{screenX:L[K].screenX,screenY:L[K].screenY,identifier:L[K].identifier},{screenX:L[N].screenX,screenY:L[N].screenY,identifier:L[N].identifier}]}break;case "pointermove":case "MSPointerMove":if(1<
g)break;case "touchmove":if(aa)return;K=N[L.length-1];if(!K)break;if(K.identifier!=f&&(K=d(N,f),!K)){cancelDefault(H);return}N=Ya(K.clientX,K.clientY,l);ca=N.x|0;da=N.y|0;if(J){if(0===ca-e&&0===da-h)return;if(Math.abs(ca-e)<Q&&Math.abs(da-h)<Q){cancelDefault(H);return}J=!1;N=Date.now()-k;if((G=88>N)&&!Ga()&&1==g){aa=!0;return}a.touchstart({x:e,y:h,flick:G,pointes:g,screenX:K.screenX,screenY:K.screenY,moved:!0,target:H.target})}cancelDefault(H);a.touchmove({x:ca,y:da,flick:G,pointes:g,moved:!0,screenX:K.screenX,
screenY:K.screenY,target:H.target});break;case "MSPointerUp":case "touchend":case "pointerup":if(aa)return;if(3==N.length+L.length){K=a.touchend;na=G;ob=g;var lc=!J,mc=H.target;var wa=[],$a=d(L,S[0].identifier)||d(N,S[0].identifier);$a&&wa.push($a);($a=d(L,S[1].identifier)||d(N,S[1].identifier))&&wa.push($a);L="";2==wa.length&&(N=b(wa)-b(S),60>Math.abs(N)?80<wa[0].screenX-S[0].screenX?L="RIGHT":80<S[0].screenX-wa[0].screenX?L="LEFT":80<wa[0].screenY-S[0].screenY?L="DOWN":80<S[0].screenY-wa[0].screenY&&
(L="UP"):L=0>N?"CLOSE":"OPEN");K.call(a,{x:ca,y:da,flick:na,pointes:ob,moved:lc,target:mc,gesture:L});g=0;break}else{if(2<g){g=0;break}if(K=d(N,f))L=Date.now(),N=Ya(K.clientX,K.clientY,l),ca=N.x|0,da=N.y|0,G?a.touchend({x:ca,y:da,flick:!0,pointes:g,moved:!J,screenX:K.screenX,screenY:K.screenY,target:H.target}):(N=L-k,J?(m=L,u?cancelDefault(H):(t=ca,n=da),500>N?(m=L,a.touchstart({x:t,y:n,flick:!1,pointes:g,screenX:K.screenX,screenY:K.screenY,moved:!1,target:H.target}),a.touchend({x:t,y:n,flick:!1,
pointes:g,moved:!1,screenX:K.screenX,screenY:K.screenY,target:H.target})):a.longpress({x:ca,y:da,flick:!1,pointes:g,moved:!1,screenX:K.screenX,screenY:K.screenY,target:H.target})):a.touchend({x:ca,y:da,flick:!1,pointes:g,moved:!0,screenX:K.screenX,screenY:K.screenY,target:H.target}))}g=0;break;case "MSPointerCancel":case "touchcancel":g=0}u&&cancelDefault(H)}}function nc(){F(!0,14,"Backspace");F(!1,14,"Backspace")}function Db(a){try{a.select?a.select():D.selectEditable(a)}catch(b){svGlobal.logger.info(b)}}
function oc(a){function b(){g.focus()}function d(u,e){var h=document.createElement("a");h.href="#";h.accessKey=u;h.onfocus=b;h.style.position="absolute";h.style.width=1;h.style.height=1;h.style.left=0;h.style.top=e+"px";h.style.pointerEvents="none";return h}var c=a||p.forceTextArea||D.isIE,f=document.createElement(c?"input":"div"),g=this;this.element=f;this.setFontSize=function(u){f.style.fontSize=w.inputFontSize||u};c?(f.style.opacity=0,f.readOnly=Z&&D.isMetro?!0:!1):f.contentEditable=!Z||(D.isChrome||
D.isFirefox)&&(D.isWindows||D.isCrOS)?!0:!1;f.setAttribute("autocomplete",D.isChrome?"new-password":"off");f.setAttribute("autocorrect","off");f.setAttribute("autocapitalize","off");f.setAttribute("spellcheck","false");f.setAttribute("inputmode","password");a&&f.setAttribute("type","password");f.accessKey="f";f.id="wsinput";f.tabIndex=1;f.style.opacity=.01;f.style.resize="none";f.style.position="absolute";f.style.margin="0";f.style.border="none";f.style.outline="none";a=hi5.tool.getPos(l,!0);f.style.left=
a.x+"px";f.style.top=a.y+"px";f.style.paddingRight=0;f.style.paddingBottom=0;f.style.width="10px";f.style.height="10px";f.style.zIndex=88;f.style.cursor="default";f.style.fontWeight="normal";f.style.fonStyle="normal";f.style.overflow="hidden";Z&&(f.style.fontSize="2em");D.isiOS?(f.addEventListener("focus",function(u){setTimeout(function(){u.target.style.fontSize="0px"},333)},!1),f.addEventListener("blur",function(u){u.target.style.fontSize="1em"},!1)):D.isFirefox?f.style.fontSize=0:c?f.style.fontSize=
"1px":D.isChrome||(f.style.textIndent="-999em");R=new O(f);R.onbackspace=nc;a=l.parentNode;a.appendChild(f);D.isIE&&(a.appendChild(d("E"),60),a.appendChild(d("V"),61),a.appendChild(d("A"),62),a.appendChild(d("T"),63),a.appendChild(d("H"),64));var m=f.style.opacity,k=f.style.textIndent||0;this.resetCSS=function(){_fontSize=f.style.fontSize;m=f.style.opacity;f.style.opacity=.01;f.style.textIndent=0};this.restoreCSS=function(){f.style.opacity=m;f.style.textIndent=k};this.getValue=function(){return c?
f.value:f.innerHTML};this.setValue=function(u){R&&(R.disableTextInput=!0);c?f.value=u:f.innerHTML=u;R&&(R.disableTextInput=!1)};this.focus=function(){g.setValue(" ");B(f)};this.setContentEditable=function(u){c?(u="true"==u,f.readOnly==u&&(f.readOnly=!u)):f.setAttribute("contenteditable",u)};this.isIMEMode=!1;this.adjust=function(u){var e=hi5.tool.getPos(l,!0);z.offX=e.x;z.offY=e.y;var h=p.railWin?Math.min(window.innerWidth-e.x,W):W,t=p.railWin?Math.min(window.innerHeight-e.y,X):X;if(Z){var n=Math.max(window.pageXOffset+
100,e.x);u=Math.max(window.pageYOffset+100,e.y)}else{var J=Math.min(window.innerHeight-e.y,X);n=Math.round(.7*Math.min(window.innerWidth-e.x,W));u=Math.round(J*(u?.99:.7))}h-=n;t-=u;w.disableAdjust&&(u=n=0,h=l.offsetWidth,t=l.offsetHeight);f.style.width=h+"px";f.style.height=t+"px";f.style.paddingLeft=n+"px";f.style.paddingTop=u+"px";f.style.left=e.x+"px";f.style.top=e.y+"px"};this.remove=function(){R&&(R.release(),R=null);f.parentNode&&f.parentNode.removeChild(f);f=null};this.hide=function(){f.style.visibility=
"hidden"};this.getElement=function(){return f};this.select=function(){Db(f)}}function Oa(a){function b(){w.text||(w.text={});return w.text}function d(e,h,t,n,J){if(g){var G=b();e.fillStyle=G.backgroundFillStyle||"white";e.fillRect(h,t-J+2,n,J);e.fillStyle=G.fillStyle||"#337788";e.textBaseline="bottom";e.fillText(g,h+3,t-2);e.strokeStyle=u.getColor(g);e.lineWidth=2;e.beginPath();e.moveTo(h,t);e.lineTo(h+n,t);e.stroke()}}function c(){var e=r.getContext("2d"),h=e.getImageData(0,0,r.cursorWidth,r.cursorHeight);
if(g){e.font=b().font||"11px Arial";var t=1.2*(e.measureText("W").width+1)+4;r.width=Math.max(r.cursorWidth,e.measureText(g).width+4);r.height=r.cursorHeight+t;d(e,0,r.height-1,r.width,t)}else r.width=r.cursorWidth,r.height=r.cursorHeight;e.putImageData(h,0,0)}if(!r){var f=l.parentNode,g="",m=0;r=f.querySelector('canvas[name="svImgCursor"]');if(!r){r=document.createElement("canvas");r.setAttribute("name","svImgCursor");r.style.position="absolute";r.style.left=90;r.style.top=90;r.scrX=0;r.scrY=0;r.hotX=
0;r.hotY=0;r.width=r.height=32;r.__left=0;r.__top=0;r.__visible=!1;r.style.visibility="hidden";r.style.zIndex=87;var k=null;w.disableClickEffect||(k=document.createElement("div"),k.className="mouse-click-off",k.style.zIndex=89);var u={getColor:function(e){if(u[e])return u[e];var h=hi5.graphic.colorTable.getNext();return u[e]=h}};r.setCursor=function(e){var h=e.width,t=e.height,n=e.rawData,J=0,G=0,Q=r.getContext("2d");g&&(Q.font=b().font||"11px Arial",J=Q.measureText(g).width,G=1.2*(Q.measureText("W").width+
1)+4);if(a)if(g){if(a){r.cursorWidth=J;r.cursorHeight=G;r.hotX=e.hotX;r.hotY=-t;r.width=J;r.height=G+4;d(Q,0,r.height-1,r.width,G);return}}else r.__setVisible(!1);if(n&&h&&t){var aa=h*t,S=0,Za=Q.createImageData(h,t),H=Za.data,K=e.hotX-r.hotX,L=e.hotY-r.hotY;r.cursorWidth=h;r.cursorHeight=t;r.hotX=e.hotX;r.hotY=e.hotY;r.width=Math.max(h,J+4);r.height=t+G+4;g&&d(Q,0,r.height-1,r.width,G);for(J=0;J<aa;J++)e=n[J],H[S++]=e&255,H[S++]=e>>8&255,H[S++]=e>>16&255,H[S++]=e>>24&255;Q.putImageData(Za,0,0,0,0,
h,t);r.__left-=K;r.__top-=L;r.style.left=r.__left+"px";r.style.top=r.__top+"px"}};r.__setVisible=function(e){r.__visible=e;r.style.visibility=e?"visible":"hidden"};ka&&ka.rawData?r.setCursor(ka):r.setCursor({rawData:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,-16777216,-16777216,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
-16777216,-1,-1,-16777216,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],width:32,height:32,hotX:10,hotY:10});r.moveCursor=function(e,h,t,n,J){var G=e-r.hotX,Q=h-r.hotY;r.__left=G;r.__top=Q;r.style.left=G+"px";r.style.top=Q+"px";if(g!=t||m!=n)g=t,m=n,c();k&&J&32768&&(k.style.left=e-30+"px",k.style.top=h-30+"px",k.className=
"mouse-click-on",setTimeout(function(){k.className="mouse-click-off"},500))};f.appendChild(r);k&&f.appendChild(k)}}}function pb(a){if(!1!==w.disableScrollbars){var b=document.body;a?(qb=a,b.style.overflow=a):(qb=W<=window.innerWidth&&X<=window.innerHeight?"hidden":"visible",b.style.overflow=qb)}}function Pa(a){var b=l.parentNode;document.body.style.overflow="hidden";ea=la=a?Math.min(window.innerWidth/W,window.innerHeight/X):1;hi5.tool.scale(b,ea,ea)}function Fb(a){if(!A||a)A=new oc(a);A.adjust()}
function rb(){if(p.toolbar)p.toolbar.removeButton("svCloud");else{var a=hi5.$("svCloud");a&&a.parentNode.removeChild(a)}}function Gb(){var a=chrome.app.window.current();a&&a.fullscreen()}function sb(a,b){var d=document.getElementById("_tmpEditable");a||(a="div");var c=document.body;d&&d.nodeName!=a.toUpperCase()&&(c.removeChild(d),d=null);d||(d=document.createElement(a),d.id="_tmpEditable","div"==a&&!1!==b&&(d.contentEditable=!0,D.isIE&&(d.style.textIndent="-999px")),d.style.position="absolute",d.style.zIndex=
9999,d.style.left=c.scrollLeft+50+"px",d.style.top=c.scrollTop+50+"px",d.style.width="4px",d.style.height="4px",d.tabIndex=2,d.style.outline="none",d.style.opacity=.01,d.style.overflow="hidden",c.appendChild(d));return d}function Hb(a){if(!p.focused){Qa.clearPDF();p.focused=!0;if(ma&&ma.onfocus)ma.onfocus(a,Ba);p.focusTime=Date.now();oa&&(fa=x.fromSyncedSurface?x.fromSyncedSurface(200):!1,fa||(y&&(y.clipData=null),p.onreqpaste||kb?x.send("8911"):y.read(function(b){b&&!b.equals(y.clipData)?(x.send("8911"),
y.clipData=b):x.send("8910")})));I.setNeedSyncKey(!0);I.sendMissKey();I.ctrlDelayed&&(I.ctrlDelayed=!1)}}function Ib(a){var b=__svi18n.remoteApp.close;if(!Jb&&p.railWin&&p.railWin.isRunning()&&b&&(a||(a=window.event),2!=x.getAppMode()))return p.showMessage(b),a&&(a.returnValue=b),b}function ab(a){if(p&&(p.focused=!1,p.onunload))p.onunload()}function Kb(){A&&(A.element.oncontextmenu=function(){return!1},D.isIE||(A.element.onselectstart=function(){return!1}))}function Lb(a){if(!document.hidden)if(A&&
A.adjust(),Ca)Pa(!0);else if(!(va&&2500>Date.now()-va)){var b=D.isWindows&&!D.isMetro;if(!Z||b&&!va||D.isCrOS||D.isChromeApp)x.onresize(a)}}function Mb(a){I.setNeedSyncKey(!0);p&&(p.focused=!1,p.blurTime=Date.now())}function pc(){window.svSurface||(window.svSurface=p);window.addEventListener("resize",Lb,!1);if(!xa){var a=!D.isChromeApp;a&&window.addEventListener("beforeunload",Ib,!1);a?window.addEventListener("unload",ab,!1):chrome.runtime.onSuspend.addListener(ab);Kb();A.element.addEventListener("focus",
Hb,!1);A.element.addEventListener("blur",Mb,!1);D.isChromeApp&&!w.disableMaxFullScn&&chrome.app.window.current().onMaximized.addListener(Gb);(a=hi5.$("saveSession"))&&a.addEventListener("change",function(d){x.saveSession({save:d.target.checked})});if(a=hi5.$("reqFullscr"))a.onclick=function(d){p&&p.requestFullscreen(!0)};a=hi5.$("attachPrinter");var b=hi5.$("localPrinter");a&&b&&(a.onclick=function(d){p.showPrinters(function(c){c&&x.attachPrinter(c)})})}}function Nb(){if(!sa){var a=hi5.$("touchGesture");
a&&(a.style.display="block");if(a=hi5.$("extKBD"))a.onchange=function(b){p.setExtKeyboard(b.target.checked)};sa=hi5.$("svTouchInput");try{window.parent==window||sa||(sa=window.parent.document.getElementById("svTouchInput"))}catch(b){}sa&&"IMG"!=sa.nodeName&&(a=document.createElement("img"),a.id="svTouchInput",a.src=w.img&&w.img.kbd||"kbd.png",sa.parentNode.replaceChild(a,sa),sa=a)}}function ya(a,b){function d(g,m){var k=document.createElement("span");k.data_path=g;k.className="path";k.innerHTML=m;
k.onclick=function(){ya(this.data_path,b)};return k}function c(g){for(var m=f;m.hasChildNodes();)m.removeChild(m.firstChild);var k=d("/","&nbsp&nbsp&nbsp/");m.appendChild(k);if("/"!=g&&""!==g){g=g.split("/");for(var u="/",e=0,h=g.length;e<h;e++)k=g[e],""!==k&&(u=u+g[e]+"/",k=d(u,k+"/"),m.appendChild(k))}}var f=hi5.$("parentPath");f.currentDir||(f.currentDir="/");"."==a&&(a=f.currentDir);b?b.visible()?hi5.tool.disableInput(hi5.$("filecontainer")):b.onopen=function(){hi5.tool.disableInput(hi5.$("filecontainer"))}:
hi5.tool.disableInput();x.getShareFiles(a,function(g){function m(t){t||(t=k.getValue("Name"));var n=g.parent;if(""===n||"/"!=n.charAt(n.length-1))n+="/";if("."==t)return n;if(".."==t){if(1==n.length)return n;var J=n.lastIndexOf("/",n.length-2);if(-1!=J)return n.substring(0,J+1)}return n+t}if(g.error&&__svi18n.file[g.error])p.showMessage(__svi18n.file[g.error]||"Access Denied");else{f.currentDir=g.parent||a;var k=new hi5.DataGrid(hi5.$("filelist"));k.clear();var u=new hi5.DataTable(g);k.dataTable=
u;var e=hi5.tool.bytesToSize;k.beforeDisplayValue=function(t,n){t=u.cols[t].name;return"Date Modified"==t?(new Date(n)).toLocaleString():"Size"==t?e(n):"Type"==t&&"folder"==n?__svi18n.file.folder:"Name"==t?decodeURIComponent(n):n};k.onrowclick=function(t){var n=k.getValue("Name"),J=k.getValue("Type");n=m(n);t=t.target.name;"delete"==t?(P.removeFile(n),ya(g.parent,b)):"folder"==J?ya(n,b):t&&x.getFile(decodeURIComponent(n),null,t)};k.beforeAppendRow=function(t){var n;if("folder"==u.getValue(u.getColNo("Type"))){if(n=
t.querySelector('img[name="download"]'))n.style.visibility="hidden"}else{n=k.getValue("Name");var J=m(n);x.getFileLink(decodeURIComponent(J));if(10<n.length&&".uploading"==n.substring(n.length-10)){if(n=t.querySelector('img[name="download"]'))n.style.visibility="hidden";if(n=t.querySelector('img[name="view"]'))n.style.visibility="hidden"}}};k.open();c(g.parent);var h=document.getElementById("__diskSpace");h&&(h.innerHTML=hi5.tool.bytesToSize(g.freeSpace)+"/"+hi5.tool.bytesToSize(g.totalSpace));b&&
(b.__position="\\\\tsclient\\"+g.name+g.parent.replace(/\//g,"\\"),b.__workdir=g.parent);hi5.tool.enableInput()}})}function Ob(a){P&&(a&&cancelDefault(a),a=hi5.$("filecontainer"),ha=new hi5.ui.Lightbox(a),ya(".",ha),ha.show(),ha.onclose=function(){hi5.tool.enableInput();p.focus()},(a=document.getElementById("__sv_folder__"))&&P.mkdirs&&(a.onclick=function(){var b=document.getElementById("__sv_folder_name_");b&&b.value&&(P.mkdirs(b.value),ya(".",ha),b.value="")}),a=document.getElementById("__sv_position__"))&&
(a.onclick=function(){x.setWorkDir&&x.setWorkDir(ha.__position,ha.__workdir);ha.dismiss()})}function Pb(){var a=q.toolbar;if(a){for(var b=a.childNodes,d=!1,c=0,f=b.length;c<f;c++)if(1==b[c].nodeType&&-1==["svTouchInput","svCloud","svInfo"].indexOf(b[c].id)){d=!0;break}if(b=hi5.$("appinfo"))b.className="h5-form";if(p.showToolbar||Z||P||b||d){a.style.left=.45*window.innerWidth+"px";if(d=null===p.toolbar)p.toolbar=new hi5.Toolbar(a,w.toolbar.draggable,w.img.handle||"handle.png");Z||(a=hi5.$("svTouchInput"))&&
a.parentNode.removeChild(a);if(a=p.toolbar.getButton("svCloud"))P?(a.style.display="",a.onclick=Ob):a.style.display="none";new hi5.Fadable(p.toolbar,w.toolbar.fadeDelay||5E3,A.element,"inline-block");a=w.toolbar.fadable;p.toolbar.setFadable(a);a&&(p.toolbar.style.display="none");if(a=p.toolbar.getButton("svInfo"))b?(a.style.display="",d&&(a.onclick=function(g){cancelDefault(g);p.showConnectonInfo()})):a.style.display="none";if(p.onloadtoolbar)p.onloadtoolbar(p.toolbar)}}}function qc(a){P.addFiles(a.target.files,
!1);a.target.value=null}function rc(){var a=A.element;ta&&ta.release();ta=new svGlobal.util.MapDisk(a,P,!0);hi5.$("filecontainer")&&(bb=new svGlobal.util.MapDisk(hi5.$("filecontainer"),P,!1),hi5.$("uploadfile").addEventListener("change",qc,!1))}function cb(a){r&&r.__setVisible(!1)}function Qb(a){if(a-tb>=ub)if(z.isMultiMon){var b=Ra(z.left,z.top,z.right,z.bottom,Ba);b&&(b.imgData?M.putImageData(b.imgData,b.left-z.left,b.top-z.top,0,0,b.width,b.height):M.drawImage(b.drawable,0,0),tb=a)}else if(b=Ra(0,
0,z.right,z.bottom,Ba))b.imgData?M.putImageData(b.imgData,b.left,b.top,0,0,b.width,b.height):M.drawImage(b.drawable,0,0),tb=a;db=requestAnimationFrame(Qb)}function Rb(a,b,d,c){r||Oa(w.cursorNameOnly);r.__visible||r.__setVisible(!0);a=r.scrX+a;b=r.scrY+b;0>a?a=0:a>W&&(a=W-1);0>b?b=0:b>X&&(b=X-1);r.scrX=a;r.scrY=b;var f=a-r.hotX,g=b-r.hotY;D.isIE&&(f=f/ea|0,g=g/la|0);r.style.left=f+z.offX+"px";r.style.top=g+z.offY+"px";V&&!d&&x.sendInput("82"+a+"\t"+b);z.x=a;z.y=b;c&&(d=r.getBoundingClientRect(),3>
d.top?window.scrollBy(0,-20):3>d.left?window.scrollBy(-20,0):d.bottom>window.innerHeight?window.scrollBy(0,20):d.right>window.innerWidth&&window.scrollBy(20,0))}function Ha(a,b,d){a=a/ea|0;b=b/la|0;p.moveCursor(a,b,d)}function jb(a){A?A.setContentEditable(a?"true":"false"):document.getElementById("wsinput")&&input.setAttribute("contenteditable",a?"true":"false");va=a?1:0;Y&&Y.setVisibility(a);if(p.toolbar){var b=p.toolbar.getButton("svTouchInput");b&&(b.className=a?"h5-img-btn-on":"h5-img-btn")}}
function vb(){(La=!La)&&A&&A.adjust();jb(La);A&&(A.element.blur(),A.element.focus())}function wb(a,b,d,c){switch(a){case "touchstart":xb=!1;0===r.scrX&&0===r.scrY&&Ha(b-50,d-50);c&&(p.beforemousedown&&p.beforemousedown(r.scrX,r.scrY,0),x.sendInput("80"+r.scrX+"\t"+r.scrY+"\t0"));break;case "touchmove":c=b-eb;a=d-Ia;if(0===c&&0===a)return;var f=5>Math.abs(Sb)&&5>Math.abs(Tb)&&(7<Math.abs(c)||7<Math.abs(a));f||(Rb(c,a,!1,!0),xb=!0);Sb=c;Tb=a;break;case "touchend":if(a=!xb&&!c)p.beforemousedown&&p.beforemousedown(r.scrX,
r.scrY,0),x.sendInput("80"+r.scrX+"\t"+r.scrY+"\t0");if(a||c)x.sendInput("81"+r.scrX+"\t"+r.scrY+"\t0"),p.aftermouseup&&p.aftermouseup(r.scrX,r.scrY,0)}eb=b;Ia=d}function sc(a){V&&Da&&(a.touches||a.changedTouches?Da.handle(a):Da.handlePointer(a))}function tc(a){if(!V)return!1;if("false"==A.element.contentEditable&&(D.isiOS||D.isAndroid))return Ub(a);a.stopPropagation();I.check(a);var b=T.getKeyCode(a),d="keydown"==a.type;if(Vb(a,b,d))return cancelDefault(a);17!=b||d||(Ea=!1,Ja&&I.preKey.down&&pa(!1,
I.preKey.code,T.getScancodeByKeyCode(I.preKey.code)));var c=T.getScancode(a),f=T.isPrintableScancode(c,a);3==a.location&&(f=89==c?!0:!1);if(!f){I.afterComposition&&d&&(I.afterComposition=!1);if(I.onComposition||I.afterComposition&&!d)return!0;I.continue(d,c,!0)&&F(d,c,a.key);if(17==b||(ia||a.metaKey)&&(86==b||67==b||88==b))return d&&(17==b&&Ma&&A&&Fa&&(a.target==A.element?(A.setValue("Copying... Please try again"),A.select()):(ja.setValue("Copying... Please try again"),ja.select())),67==b||88==b)&&
(Ea=!0),17!=b||d||(Ea=!1),!0;3==a.location?I.noUnicode=!0:d&&(I.noUnicode=!1);return 9==b&&!1===w.tabCapture?!0:cancelDefault(a)}(f=I.isAltGr(d))?za=ia=!1:I.noUnicode&&(I.noUnicode=!1);f=!f&&(a.ctrlKey||a.altKey||a.metaKey);if(a.altKey&&f&&70<c&&83>c&&74!=c&&78!=c){if(56==I.preScancode.code||184==I.preScancode.code)F(!0,1,"Escape"),F(!1,1,"Escape");f=!1}if(f)return(86!=b||!a.ctrlKey&&!a.metaKey||a.ctrlKey&&a.altKey||!oa)&&pa(d,b,T.getScancode(a)),d&&(fb=b),17==b||(a.ctrlKey||a.metaKey)&&(86==b||67==
b||88==b)?(!d||67!=b&&88!=b||(Ea=!0),!0):a.altKey&&!a.ctrlKey||a.ctrlKey&&!a.altKey||a.metaKey?cancelDefault(a):!0;if(!(b!=fb||d||a.ctrlKey&&a.altKey))return pa(!1,b,T.getScancode(a)),fb=0,cancelDefault(a);fb=0;return!0}function uc(a){I.onComposition="compositionend"!=a.type;I.afterComposition=!I.onComposition}function Vb(a,b,d){switch(b){case 8:case 35:if(!ia&&!a.metaKey||!a.altKey||w.disableShortcuts||3==a.location)return!1;F(d,211,"Delete");break;case 33:if(!a.altKey||w.disableShortcuts||3==a.location)return!1;
F(d,15,"Tab");break;case 34:if(!a.altKey||w.disableShortcuts||3==a.location)return!1;d?(F(!0,42,"Shift"),F(!0,15,"Tab")):(F(!1,15,"Tab"),F(!1,42,"Shift"));break;case 45:if(!a.altKey||w.disableShortcuts)return!1;F(d,1,"Escape");break;case 36:if(!a.altKey||w.disableShortcuts||3==a.location)return!1;d?(F(!1,56,"Alt"),F(!0,29,"Control"),F(!0,1,"Escape")):(F(!1,1,"Escape"),F(!1,29,"Control"));break;default:return!1}return!0}function Ub(a){if(!V)return!1;w.logKey&&svGlobal.logger.info(a);if(a.isComposing&&
"Process"!==a.key)return svGlobal.logger.warn("kkk Extra IME key ignored"),!1;I.check(a);var b=T.getKeyCode(a),d="keydown"==a.type,c=T.getScancode(a);if(Vb(a,b,d))return cancelDefault(a);var f=86==b&&(Wb&&!d||(a.ctrlKey||a.metaKey)&&!(a.ctrlKey&&a.altKey))&&oa;if(0<c)if(f)gb&&d&&gb.sendCtrlVLater();else if(I.continue(d,c,!1)){if(44==b){d||(ia||a.shiftKey?(F(!0,183),F(!1,183)):(F(!0,170),F(!0,183),F(!1,183),F(!1,170)));var g=!0}else g=!1;if(g)return cancelDefault(a);F(d,c,a.key)}17!=b&&(Wb=f);return 17==
b||(ia||a.metaKey)&&(86==b||67==b||88==b)?(d&&(17==b&&Ma&&A&&Fa&&(A.setValue("Copying... Please try again"),A.select()),67==b||88==b)&&(Ea=!0),17!=b||d||(Ea=!1),!0):144==b||16==b||9==b&&!1===w.tabCapture?!1:cancelDefault(a)}function vc(a){if(V)if(I.noUnicode)I.noUnicode=!1;else if(a=a.data,"`\t`"!=a){var b=ia||za;b&&(a=a.toLowerCase());a=a.replace(/\u00a0/g," ");if(p.onunicode){var d=p.onunicode(a);d&&(b=d.ctrl||d.alt)}if(w.scancode&&w.scancode[a])if(a=w.scancode[a],"number"==typeof a)ua(!0,a),ua(!1,
a);else for(b=0,d=a.length;b<d;b++)ua(a[b].down,a[b].key);else x.sendInput("86"+a+"\t"+(b||Xb?1:0));Y&&Y.resetModifier()}}function wc(a,b){var d=a?a.getData(b):null;!d&&a&&(d=a.getData(a.types[0]));if(d&&"text/plain"==b){for(var c=0,f="",g=d.length;c<g&&(f=d.charAt(c),"\r"==f||"\n"==f);c++);c&&(d=d.substring(c))}if(d)return x.send("881"+b+"\t"+d),a.sent=Date.now(),!0;if(p.onreqpaste)return p.onreqpaste(b,function(m){x.send("881"+b+"\t"+m)},function(){x.send("881ERROR\t")}),!0;x.send("881"+b+"\t");
return!1}function hb(){x.writeKeyComb("ctrl+v",20)}function xc(a){var b=0===a.types.length||a.equals(y.clipData),d=b?"":a.types.join(","),c=!0;if(!b){-1!=d.indexOf("text/html")&&-1==d.indexOf("text/richtext")&&(d+=",text/richtext");var f=a.getData("text/plain");f=f?f.hashCode():0;x.send("880"+d+"\t"+f);y.clipData=a}p.onclipdata&&(c=!p.onclipdata(a,b));c&&setTimeout(hb,500)}function ua(a,b,d){if(p.onscancode){var c=p.onscancode(a,b);if(c){a=0;for(b=c.length;a<b;a++)x.sendInput("84"+(c[a].down?0:49152)+
"\t"+c[a].key);return}}c="84"+(a?0:49152)+"\t"+b;d&&(c+="\t"+d);x.sendInput(c);I.preScancode.code=b;I.preScancode.down=a}function F(a,b,d){if(V){switch(b){case 221:if(a&&!w.disableKbdSync){ua(!0,221,d);ua(!1,221,d);return}break;case 58:if(a){if(Ja&&!w.disableKbdSync){ua(!0,58,d);ua(!1,58,d);return}x.localLockFlags^=4}break;case 69:a&&(x.localLockFlags^=2);break;case 70:a&&(x.localLockFlags^=1)}!I.isKeyDownSent(a,b)&&999<Date.now()-p.focusTime&&ua(!0,b,d);ua(a,b,d)}}function pa(a,b,d){if(V){var c=
"8B"+(a?0:49152)+"\t"+b;d&&(c+="\t"+d);I.ctrlDelayed&&(I.ctrlDelayed=!1,F(!0,29,"Control"));x.sendInput(c);I.preKey.code=b;I.preKey.down=a}}function Na(a,b){I.ctrlDelayed&&(I.ctrlDelayed=!1,F(!0,29,"Control"));x.sendInput(a+b)}function Sa(a,b,d,c,f){if(!V)return!1;B(A.element);c||(c=ea);f||(f=la);z.mouseDown[d]=!0;a=(a/c|0)+z.left;b=(b/f|0)+z.top;p.beforemousedown&&p.beforemousedown(a,b,d);z.x=a;z.y=b;Na("80",a+"\t"+b+"\t"+d)}function lb(a){I.sendMissKey(a);var b=Xa(a);Sa(b.x,b.y,a.button);return Yb?
!0:cancelDefault(a)}function Zb(a,b,d,c){d||(d=ea);c||(c=la);a=(a/d|0)+z.left;b=(b/c|0)+z.top;0>a&&(a=0);0>b&&(b=0);if(p.onmousemove)p.onmousemove(a,b);z.x=a;z.y=b;Na("82",a+"\t"+b)}function mb(a){I.isNeedSyncKey()&&I.syncLockKeyStatus(a);if(!$b||!A||a.target!=A.element&&!z.mouseDown[0])return!1;var b=Xa(a,A.element);!Ta||!D.isAndroid&&!D.isiOS&&ka&&ka.system?r&&r.__visible&&r.__setVisible(!1):Ha(b.x,b.y,!0);Zb(b.x,b.y);return cancelDefault(a)}function Ua(a,b,d,c,f){c||(c=ea);f||(f=la);z.mouseDown[d]&&
(z.mouseDown[d]=!1,a=(a/c|0)+z.left,b=(b/f|0)+z.top,0>a&&(a=0),0>b&&(b=0),Na("81",a+"\t"+b+"\t"+d),p.aftermouseup&&p.aftermouseup(a,b,d),y&&"denied"==y.clipboardWrite&&y.waitForCopyContent(),ma.resumePlay&&(ma.resumePlay(),ma.resumePlay=null))}function nb(a){if(!V)return!1;var b=Xa(a,A.element);Ua(b.x,b.y,a.button);return Yb?!0:cancelDefault(a)}function ac(a,b,d,c,f){c||(c=ea);f||(f=la);a=(a/c|0)+z.left;b=(b/f|0)+z.top;p.onmousewheel&&p.onmousewheel(a,b,d)||Na("83",a+"\t"+b+"\t"+d)}function yc(a,
b){if(!V)return!1;var d=Math.abs(a);a=0>a?1:0;for(var c=0;c<d;c++)ac(b.x,b.y,a);return!1}function zc(a){if(a.none)return"none";if(a.system)return a.system;if(Ta)return"none";var b;if(!(b=a.url)){var d=a.rawData;b=a.width;var c=a.height,f=document.createElement("canvas"),g=f.getContext("2d"),m=g.createImageData(b,c),k=m.data,u=b*c,e=window.devicePixelRatio||1,h=0,t=0;f.width=b;for(f.height=c;h<u;h++){var n=d[h];k[t++]=n&255;k[t++]=n>>8&255;k[t++]=n>>16&255;k[t++]=n>>24&255}g.putImageData(m,0,0,0,0,
b,c);1==e?b=f.toDataURL():f.toDataURLHD?b=f.toDataURLHD():(d=document.createElement("canvas"),g=d.getContext("2d"),d.width=b*e|0,d.height=c*e|0,g.scale(e,e),g.drawImage(f,0,0),b=d.toDataURL())}return"url("+b+") "+a.hotX+" "+a.hotY+", default"}function bc(){document.fullscreenElement?navigator.keyboard&&navigator.keyboard.lock():navigator.keyboard&&navigator.keyboard.unlock()}l||(l=hi5.$("remotectrl"));q||(q={});q.pcKey||(q.pcKey=hi5.$("pc_key"));q.toolbar||(q.toolbar=hi5.$("svToolbar"));q.frmLogin||
(q.frmLogin=hi5.$("frmLogin"));var cc=q.notifications||hi5.notifications;if(window.svSurface&&svSurface.canvas==l&&svSurface.railWin)return svSurface.railWin.mainWin=null,window.svSurface;var D=hi5.browser,Z=D.isTouch,Va=D.getChildByNameOrId,x=null,ma=null,Ca=!1,ea=1,la=1,ib=0,dc=0,yb=!1;l.style.outline="none";var W=0,X=0;hi5.appcfg||(hi5.appcfg={img:{},toolbar:{fadable:!0},displayMsg:!0});var w=hi5.appcfg,zb={alpha:!1,desynchronized:!0,antialias:!1,powerPreference:"high-performance"};1==w.alpha&&
(zb.alpha=!0);0==w.desynchronized&&(zb.desynchronized=!1);var M=l.getContext("2d",zb),R=null,ja=null,ia=M.imageSmoothingEnabled=!1,za=!1,Ka=!1,Jb=!1,fa=!1,P=null,oa=!0,Fa=!1,Ab=!1,Ea=!1,Wb=!1,ec=0;this.context=M;this.fileProgress=null;this.focusTime=this.blurTime=0;var p=this,V=!0,ra=!1,xa=!1,$b=!0,Wa=null,fc=null,ha=null,r=null,ka=null,Da=null,sa=null,va=0,eb=-1,Ia=-1,Sb=0,Tb=0,xb=!1,qb=null,z={x:0,y:0,offX:0,offY:0,left:0,top:0,right:0,bottom:0,primary:!1,isMultiMon:!1,btnDown:-1,mouseDown:[]},
ta=null,bb=null,tb=0,Ra,Bb=!1,gc=0,db=0,La=!1,Aa=null,Ba=65535;this._cr=[82,69,77,79,84,69,83,80,65,82,75];window.svSurface=this;void 0==w.toolbar.draggable&&(w.toolbar.draggable=!0);var Yb=window.clipboardData?!0:!!w.defaultEvent,Ta=D.isIE&&!w.disableCursor,kb=D.isChromeApp||D.isIE||1==w.directClipAccess,Xb=!!w.forceScancode;this.setConfig=function(a){w=a};this.setId=function(a){Ba=a};this.railWin=this.toolbar=null;this.showToolbar=this.focused=!1;this.canvas=l;this.forceTextArea=this.alwaysPaste=
!1;"visible"in w.toolbar&&(this.showToolbar=w.toolbar.visible);var Xa=D.getMousePos,Ya=D.calMousePos;this.getWindow=function(){return window};this.setImageCursor=function(a){Ta=a};this.setMonitor=function(a,b,d,c){z.left=a;z.top=b;z.right=d;z.bottom=c;z.primary=0==a&&0==b;0!=d&&0!=c&&(z.isMultiMon=!1,p.setSize(d-a+1,c-b+1),z.isMultiMon=!0,pb("hidden"),w.disableScrollbars=!0)};this.isMonitor=function(a,b,d,c,f){return f==Ba||z.left==a&&z.top==b};this.configMonitor=function(){var a=window.screenX,b=
window.screenY;if(window.outerWidth<window.innerWidth){var d=(window.innerWidth-window.outerWidth)/2;svGlobal.logger.warn("* screenX:"+window.screenX+" screenY:"+window.screenY+" outerWidth:"+window.outerWidth+" innerWidth:"+window.innerWidth+" off:"+d);a-=d;b-=d}0<=a&&100>a&&0<=b&&100>b&&(0<a&&(svGlobal.logger.warn("* invalid left:"+a),a=0),0<b&&(svGlobal.logger.warn("* invalid top: "+b),b=0));d=(window.innerWidth&-4)+a-1;var c=(window.innerHeight&-4)+b-1;p.setMonitor(a,b,d,c);svGlobal.logger.info("monitor, l:"+
a+" t:"+b+" r:"+d+" b:"+c)};this.isClipSynced=function(a){if(!fa)return!1;var b=Date.now()-p.blurTime;if(a&&b>a)return!1;svGlobal.logger.info("clip synced in "+b);return!0};this.getScale=function(){return{x:ea,y:la}};var U=null,Y=null,Ma=!D.isChromeApp&&!w.copyDialog&&!w.directClipAccess&&!D.isIE;this.getThumbnail=function(a){a=a||64;U||(U=document.createElement("canvas"));var b=Math.floor(l.height/l.width*a);U.width!=a&&(U.width=a);U.height!=b&&(U.height=b);U.getContext("2d").drawImage(l,0,0,l.width,
l.height,0,0,a,b);return U.toDataURL()};this.getThumbnailBlob=function(a,b){a=a||64;var d=Math.floor(l.height/l.width*a);U||(U=window.OffscreenCanvas?new OffscreenCanvas(a,d):document.createElement("canvas"));U.width!=a&&(U.width=a);U.height!=d&&(U.height=d);U.getContext("2d").drawImage(l,0,0,l.width,l.height,0,0,a,d);return U.toBlob(b)};this.getSnapshot=function(a,b){l.toBlob(a,b)};this.initChat=function(a){var b=document.getElementById("chatWindow");hi5.Draggable(b);return new hi5.Chat(b,a)};this.equals=
function(a){return l==a.canvas};this.getFreeSpace=function(){var a=hi5.tool.getPos(l),b=window.innerWidth-a.x;a=v(window.innerHeight)-a.y;return{width:b,height:a}};var T=new function(){var a=1033,b=D.isFirefox,d=D.isMacOS||D.isiOS,c=[0],f=null;c[3]=197;c[8]=14;c[9]=15;c[12]=76;c[13]=28;c[16]=42;c[17]=29;c[18]=56;c[19]=197;c[20]=58;c[27]=1;c[32]=57;c[33]=201;c[34]=209;c[35]=207;c[36]=199;c[37]=203;c[38]=200;c[39]=205;c[40]=208;c[44]=55;c[45]=210;c[46]=211;c[48]=11;c[49]=2;c[50]=3;c[51]=4;c[52]=5;c[53]=
6;c[54]=7;c[55]=8;c[56]=9;c[57]=10;c[65]=30;c[66]=48;c[67]=46;c[68]=32;c[69]=18;c[70]=33;c[71]=34;c[72]=35;c[73]=23;c[74]=36;c[75]=37;c[76]=38;c[77]=50;c[78]=49;c[79]=24;c[80]=25;c[81]=16;c[82]=19;c[83]=31;c[84]=20;c[85]=22;c[86]=47;c[87]=17;c[88]=45;c[89]=21;c[90]=44;c[91]=219;c[92]=220;c[93]=221;c[96]=82;c[97]=79;c[98]=80;c[99]=81;c[100]=75;c[101]=76;c[102]=77;c[103]=71;c[104]=72;c[105]=73;c[106]=55;c[107]=78;c[109]=74;c[110]=83;c[111]=181;c[112]=59;c[113]=60;c[114]=61;c[115]=62;c[116]=63;c[117]=
64;c[118]=65;c[119]=66;c[120]=67;c[121]=68;c[122]=87;c[123]=88;c[144]=69;c[145]=70;c[154]=183;c[166]=59;c[167]=60;c[168]=61;c[173]=66;c[174]=67;c[175]=68;c[182]=63;c[183]=62;c[216]=64;c[217]=65;c[186]=39;c[187]=13;c[188]=51;c[189]=12;c[190]=52;c[191]=53;c[192]=41;c[219]=26;c[220]=43;c[221]=27;c[222]=40;c[224]=29;c[225]=184;c[226]=86;c[235]=123;c[255]=121;var g={Escape:1,Digit1:2,Digit2:3,Digit3:4,Digit4:5,Digit5:6,Digit6:7,Digit7:8,Digit8:9,Digit9:10,Digit0:11,Minus:12,Equal:13,Backspace:14,Tab:15,
KeyQ:16,KeyW:17,KeyE:18,KeyR:19,KeyT:20,KeyY:21,KeyU:22,KeyI:23,KeyO:24,KeyP:25,BracketLeft:26,BracketRight:27,Enter:28,ControlLeft:29,KeyA:30,KeyS:31,KeyD:32,KeyF:33,KeyG:34,KeyH:35,KeyJ:36,KeyK:37,KeyL:38,Semicolon:39,Quote:40,Backquote:41,ShiftLeft:42,Backslash:43,KeyZ:44,KeyX:45,KeyC:46,KeyV:47,KeyB:48,KeyN:49,KeyM:50,Comma:51,Period:52,Slash:53,ShiftRight:54,NumpadMultiply:55,AltLeft:56,Space:57,CapsLock:58,F1:59,F2:60,F3:61,F4:62,F5:63,F6:64,F7:65,F8:66,F9:67,F10:68,NumLock:69,ScrollLock:70,
Numpad7:71,Numpad8:72,Numpad9:73,NumpadSubtract:74,Numpad4:75,Numpad5:76,Numpad6:77,NumpadAdd:78,Numpad1:79,Numpad2:80,Numpad3:81,Numpad0:82,NumpadDecimal:83,IntlBackslash:86,F11:87,F12:88,NumpadEqual:89,F13:91,F14:92,F15:93,F16:99,F17:100,F18:101,F19:102,F20:103,F21:104,F22:105,F23:106,F24:107,KanaMode:112,Lang2:113,Lang1:114,IntlRo:115,Convert:121,NonConvert:123,IntlYen:125,NumpadComma:126,Paste:138,MediaTrackPrevious:144,Cut:151,Copy:152,MediaTrackNext:153,NumpadEnter:156,ControlRight:157,VolumeMute:160,
AudioVolumeMute:160,LaunchApp2:161,MediaPlayPause:162,MediaStop:164,Eject:172,VolumeDown:174,AudioVolumeDown:174,VolumeUp:176,AudioVolumeUp:176,BrowserHome:178,NumpadDivide:181,PrintScreen:183,AltRight:184,Help:187,Pause:197,Home:199,ArrowUp:200,PageUp:201,ArrowLeft:203,ArrowRight:205,End:207,ArrowDown:208,PageDown:209,Insert:210,Delete:211,OSLeft:219,MetaLeft:219,OSRight:220,MetaRight:220,ContextMenu:221,Power:222,BrowserSearch:229,BrowserFavorites:230,BrowserRefresh:231,BrowserStop:232,BrowserForward:233,
BrowserBack:234,LaunchApp1:235,LaunchMail:236,LaunchMediaPlayer:237};this.isPrintableScancode=function(e,h){if(95<h.keyCode&&112>h.keyCode)return!0;if(0==e&&h){var t=h.char||h.key;if(t&&1==t.length)return e=t.charCodeAt(0),!(31>=e||127==e||128<=e&&159>=e)}return h.altKey&&70<e&&83>e&&74!=e&&78!=e?!0:1<e&&14>e||15<e&&28>e||29<e&&42>e||42<e&&54>e||57==e||86==e||115==e||125==e};var m=function(e){e=e.keyCode;if(b)switch(e){case 173:return 189;case 61:return 187;case 59:return 186;case 224:return 17}return e};
this.mapCmdToCtrl=this.converMacCtrl=!0;var k=d?function(e){switch(e){case 91:return T.mapCmdToCtrl?17:91;case 93:return T.mapCmdToCtrl?17:93;case 17:return T.converMacCtrl?91:17;case 229:return 69}return 0}:null;this.setLayout=function(e){a=e;var h=null;e="K"+e;e in u&&(h=u[e]());null===h&&(h=c);f=h;null!==f&&svGlobal.logger.info("Keyboard layout: "+a)};this.getKeyCode=function(e){var h=0;k&&(h=k(e.keyCode));h||(h=m?m(e):e.keyCode);return h};this.getScancode=function(e){var h=0;if(e.code)h=g[e.code]||
0;else{var t=T.getKeyCode(e);switch(t){case 16:h=2==e.location?54:42;break;case 17:h=2==e.location?157:29;break;case 18:h=2==e.location?184:56;break;case 33:h=3==e.location?73:201;break;case 34:h=3==e.location?81:209;break;case 35:h=3==e.location?79:207;break;case 36:h=3==e.location?71:199;break;case 37:h=3==e.location?75:203;break;case 38:h=3==e.location?72:200;break;case 39:h=3==e.location?77:205;break;case 40:h=3==e.location?80:208;break;case 45:h=3==e.location?82:210;break;case 46:h=3==e.location?
83:211;break;default:f&&(h=f[t]||0)}}if(d)switch(h){case 29:this.converMacCtrl&&(h=219);break;case 157:this.converMacCtrl&&(h=220);break;case 219:this.mapCmdToCtrl&&(h=29);break;case 220:this.mapCmdToCtrl&&(h=157)}return h};this.getScancodeByKeyCode=function(e){return f?f[e]||0:0};this.getCodeTable=function(){return f};this.getLayoutCreator=function(){return u};var u=new function(){this.K3758162961=function(){var e=c.slice(0);e[244]=41;e[243]=41;e[189]=12;e[222]=13;e[220]=125;e[192]=26;e[219]=27;
e[187]=39;e[186]=40;e[221]=43;e[188]=51;e[190]=52;e[191]=53;e[226]=115;e[29]=123;e[28]=121;e[240]=112;e[242]=112;b&&(e[173]=12,e[160]=13,e[64]=26,e[59]=39,e[58]=40,m=function(h){return 220==h.keyCode&&"_"==h.key?226:h.keyCode});return e};this.K1034=this.K66570=this.K2058=this.K1040=this.K66576=function(){var e=c.slice(0);e[220]=41;e[219]=12;e[221]=13;e[186]=26;e[187]=27;e[191]=43;e[192]=39;e[189]=53;e[226]=86;b&&(m=function(h){var t=h.keyCode;h=h.key;switch(t){case 0:if("\u00e8"==h||"\u00e9"==h||
"["==h)return 186;if("\u00f2"==h||"\u00e7"==h||"@"==h)return 192;if("\u00e0"==h||"\u00b0"==h||"#"==h||"\u00f9"==h||"\u00a7"==h)return 222;break;case 60:return 226;case 160:return 221;case 171:return 187;case 173:return 189;case 222:return 219}return t});return e};this.K2057=function(){var e=c.slice(0);e[223]=41;e[222]=43;e[192]=40;e[220]=86;b&&(e[192]=41,e[173]=12,e[61]=13,e[59]=39,e[222]=40,e[163]=43);return e};this.K1031=this.K4106=this.K5130=this.K6154=this.K7178=this.K8202=this.K9226=this.K10250=
this.K11274=this.K12298=this.K13322=this.K14346=this.K15370=this.K16395=this.K17418=this.K18442=this.K19466=this.K20490=this.K99997=this.K66567=this.K2952791047=function(){var e=c.slice(0);e[220]=41;e[219]=12;e[221]=13;e[186]=26;e[187]=27;e[191]=43;e[192]=39;e[189]=53;e[226]=86;e[90]=21;e[89]=44;b?m=function(h){var t=h.keyCode,n=h.key;switch(t){case 60:return 226;case 160:return 220;case 63:return 219;case 192:return 221;case 171:return 187;case 163:return 191;case 173:return 189;case 0:if("\u00f6"==
n||"\u00d6"==n&&h.shiftKey)return 192;if("\u00e4"==n||"\u00c4"==n&&h.shiftKey)return 222;if("\u00fc"==n||"\u00dc"==n&&h.shiftKey)return 186}return t}:hi5.browser.isLinux&&(m=function(h){var t=h.keyCode;h=h.key;switch(t){case 187:if("Dead"==h)return 221;break;case 192:if("Dead"==h||"\u00b0"==h)return 220;break;case 220:return 226}return t});return e};this.K2070=function(){var e=c.slice(0);e[220]=41;e[219]=12;e[221]=13;e[186]=27;e[187]=26;e[191]=43;e[192]=39;e[189]=53;e[226]=86;return e};this.K2060=
this.K99998=this.K2067=function(){var e=c.slice(0);e[222]=41;e[219]=12;e[189]=13;e[221]=26;e[186]=27;e[77]=39;e[192]=40;e[188]=50;e[190]=51;e[191]=52;e[187]=53;e[226]=86;e[65]=16;e[90]=17;e[81]=30;e[87]=44;b&&(m=function(h){var t=h.keyCode,n=h.key;switch(t){case 60:return 226;case 169:return 219;case 173:return 189;case 160:return 221;case 164:return 186;case 165:return 192;case 59:return 190;case 58:return 191;case 61:return 187;case 0:if("\u00b2"==n||"\u00b3"==n&&h.shiftKey)return 222;if("\u00b5"==
n||"`\u00b5"==n||"DeadGrave"==n||"\u00a3"==n&&h.shiftKey||("`"==n||"``"==n)&&h.ctrlKey&&h.altKey)return 220}return t});return e};this.K3084=this.K4105=function(){var e=c.slice(0);e[222]=41;e[192]=40;e[226]=86;b&&(m=function(h){var t=h.keyCode,n=h.key;switch(t){case 0:if("\u00b0"==n||"\u00ac"==n&&h.ctrlKey&&h.altKey)return 222;if("\u00e7"==n||"\u00c7"==n&&h.shiftKey)return 221;if("\u00e0"==n||"DeadGrave"==n||"\u00c0"==n&&h.shiftKey)return 220;if("\u00e8"==n||"\u00c8"==n&&h.shiftKey)return 192;if("\u00e9"==
n||"\u00c9"==n&&h.shiftKey)return 191;if("\u00f9"==n||"\u00d9"==n&&h.shiftKey)return 226;if("DeadTilde"==n)return 221;break;case 173:return 189;case 61:return 187;case 160:return 219;case 59:return 186}return t});return e};this.K1036=function(){var e=c.slice(0);e[222]=41;e[219]=12;e[187]=13;e[221]=26;e[186]=27;e[220]=43;e[77]=39;e[192]=40;e[190]=51;e[191]=52;e[223]=53;e[226]=86;e[65]=16;e[90]=17;e[81]=30;e[87]=44;e[188]=50;b&&(m=function(h){var t=h.keyCode,n=h.key;switch(t){case 0:if("\u00b2"==n)return 222;
if("\u00e7"==n||"\u00c7"==n&&h.shiftKey)return 221;if("\u00e0"==n||"\u00c0"==n&&h.shiftKey)return 220;if("\u00e8"==n||"\u00c8"==n&&h.shiftKey)return 192;if("\u00e9"==n||"\u00c9"==n&&h.shiftKey)return 189;if("\u00f9"==n||"\u00d9"==n&&h.shiftKey)return 226;if("DeadTilde"==n)return 221;break;case 60:return 226;case 169:return 219;case 61:return 187;case 160:return 221;case 164:return 186;case 170:return 220;case 165:return 192;case 59:return 190;case 58:return 191;case 161:return 223}return t});return e};
this.K4108=this.K2055=function(){var e=c.slice(0);e[191]=41;e[219]=12;e[221]=13;e[186]=26;e[192]=27;e[223]=43;e[222]=39;e[220]=40;e[188]=51;e[190]=52;e[189]=53;e[226]=86;e[90]=21;e[89]=44;b&&(m=function(h){var t=h.keyCode,n=h.key;switch(t){case 0:if("\u00a7"==n||"\u00b0"==n&&h.shiftKey)return 191;if("\u00e0"==n||"\u00e4"==n&&h.shiftKey||"{"==n&&h.ctrlKey&&h.altKey)return 220;if("\u00e8"==n||"\u00fc"==n&&h.shiftKey||"["==n&&h.ctrlKey&&h.altKey)return 186;if("\u00e9"==n||"\u00f6"==n&&h.shiftKey)return 222;
break;case 222:return 219;case 160:return 221;case 161:return 192;case 164:return 223;case 173:return 189;case 60:return 226}return t});return e};this.K1044=this.K1083=this.K1030=function(){var e=c.slice(0);e[220]=41;e[187]=12;e[219]=13;e[221]=26;e[186]=27;e[191]=43;e[192]=39;e[222]=40;e[189]=53;e[226]=86;b&&(m=function(h){var t=h.keyCode,n=h.key;switch(t){case 0:if("\u00e5"==n||"\u00c5"==n&&h.shiftKey)return 221;if("\u00f8"==n||"\u00d8"==n&&h.shiftKey||"\u00f6"==n&&h.ctrlKey&&h.altKey)return 192;
if("\u00e6"==n||"\u00c6"==n&&h.shiftKey||"\u00e4"==n&&h.ctrlKey&&h.altKey)return 222;break;case 172:return 220;case 171:return 187;case 220:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return t});return e};this.K1039=function(){var e=c.slice(0);e[220]=41;e[187]=12;e[219]=13;e[221]=26;e[186]=27;e[191]=43;e[192]=39;e[222]=40;e[189]=53;e[226]=86;b&&(m=function(h){var t=h.keyCode;h=h.key;switch(t){case 0:if("Dead"==h)return 220;if("\u00f6"==h||"\u00d6"==h||
"\\"==h)return 187;if("\u00f0"==h||"\u00d0"==h)return 221;if("\u00e6"==h||"\u00c6"==h)return 192;if("\u00fe"==h||"\u00de"==h)return 189;break;case 173:return 219;case 222:return"Dead"==h||"'"==h?222:186;case 171:return 191;case 60:return 226}return t});return e};this.K1053=function(){var e=c.slice(0);e[220]=41;e[187]=12;e[219]=13;e[221]=26;e[186]=27;e[191]=43;e[192]=39;e[222]=40;e[189]=53;e[226]=86;b&&(m=function(h){var t=h.keyCode,n=h.key;switch(t){case 0:if("\u00a7"==n||"\u00bd"==n&&h.shiftKey)return 220;
if("\u00e5"==n||"\u00c5"==n&&h.shiftKey)return 221;if("\u00f8"==n||"\u00d8"==n&&h.shiftKey||"\u00f6"==n&&h.ctrlKey&&h.altKey)return 192;if("\u00e4"==n||"\u00c4"==n&&h.shiftKey)return 222;break;case 171:return 187;case 192:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return t});return e};this.K1055=function(){var e=c.slice(0);e[220]=52;e[223]=12;e[189]=13;e[191]=51;e[188]=43;e[190]=53;e[226]=86;b&&(m=function(h){var t=h.keyCode,n=h.key;switch(t){case 0:if("\u011f"==
n||"\u011e"==n&&h.shiftKey||h.ctrlKey&&h.altKey&&"BracketLeft"==h.code)return 219;if("\u00fc"==n||"\u00dc"==n&&h.shiftKey||h.ctrlKey&&h.altKey&&"BracketRight"==h.code)return 221;if("\u015f"==n||"\u015e"==n&&h.shiftKey||h.ctrlKey&&h.altKey&&"Semicolon"==h.code)return 186;if("\u00f6"==n||"\u00d6"==n&&h.shiftKey)return 191;if("\u00e7"==n||"\u00c7"==n&&h.shiftKey)return 220;break;case 73:return 222;case 60:return 226;case 173:return 189;case 170:return 223;case 162:return 192}return t});return e};this.K6153=
function(){var e=c.slice(0);e[223]=41;e[189]=12;e[187]=13;e[219]=26;e[221]=27;e[186]=39;e[192]=40;e[222]=43;e[220]=86;e[188]=51;e[190]=52;e[191]=53;return e}}};this.getKeyboardMgr=function(){return T};var y=new function(){function a(d,c){var f=y.parseClipData(c);if(!(w.copyTextOnly&&"text/plain"!=f.type||y.processFileGroup(f)))if((c=f.value.startsWith("<img data-sv-img"))&&"denied"!=y.clipboardWrite&&navigator.clipboard.write)d.preventDefault(),setTimeout(function(){y.copyImageToClipboard(f.value)},
20);else{if("text/plain"!=f.type&&!c){var g=hi5.browser.html2text(f.value);g&&d.clipboardData.setData("text/plain",g)}c&&y.processImgCopy(f.value);d.clipboardData.setData(f.type,f.value);d.preventDefault()}}function b(){y&&(y.copyContent&&(y.copyToClipboard(y.copyContent.type,y.copyContent.value),y.copyContent=null),y.waitingCopyContent=!1)}this.hasCopyCmd=document.queryCommandSupported("copy");this.hasPasteCmd=document.queryCommandSupported("paste");this.pasteEventFired=!1;this.clipboardWrite=this.clipboardRead=
"denied";this.init=function(){navigator.permissions&&(navigator.permissions.query({name:"clipboard-read"}).then(function(d){y&&(y.clipboardRead=d.state,d.onchange=function(){y&&(y.clipboardRead=d.state,"granted"==y.clipboardRead&&C(),svGlobal.logger.info("clipboard-read change: "+y.clipboardRead))},"granted"==y.clipboardRead&&C(),svGlobal.logger.info("clipboard-read: "+y.clipboardRead))}).catch(function(d){svGlobal.logger.info(d)}),navigator.permissions.query({name:"clipboard-write"}).then(function(d){y&&
(y.clipboardWrite=d.state,d.onchange=function(){y&&(y.clipboardWrite=d.state,svGlobal.logger.info("clipboard-write change: "+y.clipboardWrite))},svGlobal.logger.info("clipboard-write: "+y.clipboardWrite))}).catch(function(d){svGlobal.logger.info(d)}))};this.release=function(){y.clipData=null};this.clipData=null;this.read=function(d){var c=new E;if("denied"!=y.clipboardRead)navigator.clipboard.read?navigator.clipboard.read().then(function(f){for(var g=f.length,m=0,k=0;k<g;k++){var u=f[k].types[0];
f[k].getType(u).then(function(e){"text/plain"==u||"text/html"==u||"text/rtf"==u?hi5.browser.blobToText(e,function(h){c.setData(u,h);m++;m==g&&d(c)}):"image/png"==u&&hi5.browser.blobToArray(e,function(h){h=hi5.Base64.enc(h);c.setData("image/png",h);m++;m==g&&d(c)})}).catch(function(e){d(c);svGlobal.logger.warn(e.message)})}}).catch(function(f){svGlobal.logger.warn(f.message)}):navigator.clipboard.readText&&navigator.clipboard.readText().then(function(f){c.setData("text/plain",f);d(c)}).catch(function(f){d(null)});
else if(window.clipboardData)c.setData("text/plain",window.clipboardData.getData("Text")),d(c);else return d(null),!1;return!0};this.paste=function(d,c){var f=window.clipboardData||c.clipboardData;if(f.files&&0<f.files.length&&P)P.addFiles(f.files,!0);else{var g=new E,m=0,k=null,u=window.clipboardData?f.getData("Text"):f.getData("text/plain"),e="",h="";e=0;f.types&&(h=f.getData("text/html"));h&&!u&&(u=hi5.browser.html2text(h));u&&g.setData("text/plain",u);if(w.pasteTextOnly)c.preventDefault(),d(g);
else{var t=f.items;if(t)for(m=0,e=t.length;m<e;m++){if("image/png"==t[m].type){k=t[m].getAsFile();break}}else if(f.files)for(t=f.files,m=0,e=t.length;m<e;m++)if(-1!=t[m].type.indexOf("image/png")){k=t[m];break}if(k)c.preventDefault(),hi5.browser.blobToArray(k,function(J){J=hi5.Base64.enc(J);g.setData("image/png",J);d(g)});else if(u){if(f.types){k=f.types.indexOf?-1!=f.types.indexOf("text/rtf"):f.types.contains("text/rtf");if(e=f.getData("text/rtf"))0==e.charCodeAt(e.length-1)&&(e=e.substring(0,e.length-
1)),g.setData("text/rtf",e);h&&(m=h.lastIndexOf("</html>"),m+7<h.length&&(h=h.substring(0,m+7)),g.setData("text/html",h));if(!k||e||h){c.preventDefault();d(g);return}}if("TEXTAREA"==c.target.nodeName)c.preventDefault(),document.queryCommandSupported("paste")&&(g=y.getClipContent(g)),d(g);else{R&&(R.disableTextInput=!0);ja&&(ja.disableTextInput=!0);c.target.innerHTML="";var n=c.target.style.opacity;c.target.style.opacity=.01;setTimeout(function(){var J=c.target.innerHTML;J&&J!=u&&(g.setData("text/html",
"<body>"+J+"</body>"),R?R.init():c.target.innerHTML="");d(g);c.target.style.opacity=n;R&&(R.disableTextInput=!1);ja&&(ja.disableTextInput=!1)},300)}}else c.preventDefault(),d(g)}}};this.onCopy=function(d){if(d.target==A.element){V&&oa||cancelDefault(d);var c="copy"==d.type,f=c?46:45;c=c?67:88;Ea||(F(!0,29,"Control"),pa(!0,c,f),pa(!1,c,f),F(!1,29,"Control"));D.isMacOS&&pa(!1,c,f);oa&&!kb&&Fa&&(999<Date.now()-ec&&(f=x.getClipData(d.type),a(d,f),y.clipData=null,fa=!0),ec=Date.now(),svGlobal.logger.info("clip synced: true"))}};
this.onPaste=function(d){if(d.target==A.element){gb&&gb.cancelCtrlV();if(!V||!oa)return cancelDefault(d);Ab||(fa=!0);if(!p.alwaysPaste&&fa){var c=!0;p.onclipdata&&(c=!p.onclipdata(y.clipData,!0));c&&setTimeout(hb,300);svGlobal.logger.info("Ctrl+V only");return cancelDefault(d)}fa=!0;y.paste(xc,d);return!0}};this.parseClipData=function(d){var c=d.indexOf(";"),f=d.substring(0,c);d=d.substring(c+1);return{type:f,value:d}};this.getClipContent=function(d){if(!document.queryCommandSupported("paste"))return d;
var c=sb(w.pasteTextOnly?"textarea":"div");c.focus();try{if(document.queryCommandEnabled("paste")&&document.execCommand("paste"))return d||(d=new E),w.pasteTextOnly||d.setData("text/html","<body>"+c.innerHTML+"</body>"),-1==d.types.indexOf("text/plain")&&d.setData("text/plain",w.pasteTextOnly?c.value:c.innerText||hi5.browser.html2text(c.innerHTML)),d}finally{p.focused=!0,c.parentNode.removeChild(c),A&&A.focus()}return d};this.accessClip=function(d,c){function f(m){d(null)}if("denied"!=y.clipboardRead&&
navigator.clipboard.readText){if("text/plain"==c)return navigator.clipboard.readText().then(function(m){var k=new E;k.setData("text/plain",m);d(k)}).catch(f),!0;if(navigator.clipboard.read)return navigator.clipboard.read().then(function(m){m.length?m[0].getType(c).then(function(k){"image/png"==c?hi5.browser.blobToArray(k,function(u){u=hi5.Base64.enc(u);var e=new E;e.setData("image/png",u);d(e)}):"text/html"==c&&k.text().then(function(u){var e=new E;e.setData("txt/html",u);d(e)}).catch(f)}).catch(f):
d(null)}).catch(f),!0}document.queryCommandSupported("paste")||d(null);var g=sb(w.pasteTextOnly?"textarea":"div");g.focus();g.addEventListener("paste",function(m){m.stopPropagation();y.pasteEventFired=!0;y.paste(function(k){p.focused=!0;g.parentNode&&g.parentNode.removeChild(g);A&&A.focus();d(k)},m)},!1);y.pasteEventFired=!1;if(document.queryCommandEnabled("paste")&&document.execCommand("paste")&&y.pasteEventFired)return!0;setTimeout(function(){fa=!0;y.pasteEventFired||d(null);p.focused=!0;g.parentNode&&
g.parentNode.removeChild(g);A&&A.focus()},55);return!1};this.waitingCopyContent=!1;this.copyContent=null;this.waitForCopyContent=function(){y.waitingCopyContent=!0;setTimeout(b,700)};this.prePaste=function(){fa||!document.queryCommandEnabled("paste")&&!window.clipboardData||y.accessClip(function(d){if(d){var c=0===d.types.length||d.equals(y.clipData),f=c?"":d.types.join(",");c||(c=(c=d.getData("text/plain"))?c.hashCode():0,x.send("880"+f+"\t"+c),y.clipData=d,fa=!0)}})};this.copyImageToClipboard=function(d){var c=
d.indexOf('src="')+5,f=d.indexOf('"',c);d=d.substring(c,f);fetch(d).then(function(g){if(g.ok)return g.blob();throw Error("Nework error, access "+stc);}).then(function(g){g=new ClipboardItem({"image/png":g});navigator.clipboard.write([g])}).catch(function(g){svGlobal.logger.warn(g)})};this.copyToClipboard=function(d,c){var f="text/plain"==d?"textarea":"div",g=!1,m=c.startsWith("<img data-sv-img"),k="text/plain"==d;"text/html"!=d||-1<c.search(/<.*(font|color|img|table|style|class).*>/gmi)||(d="text/plain",
k=!0);k&&(window.clipboardData?(window.clipboardData.setData("Text",c),g=!0):"denied"!=y.clipboardWrite&&(navigator.clipboard.writeText(c).catch(function(e){svGlobal.logger.warn(e)}),g=!0));if(!k||!g)if((m||"text/html"==d||"text/rtf"==d)&&"denied"!=y.clipboardWrite&&navigator.clipboard.write)m?y.copyImageToClipboard(c):(g=null,"text/html"==d?(g=new Blob([c],{type:"text/html"}),f=new Blob([hi5.browser.html2text(c)],{type:"text/plain"}),g=new ClipboardItem({"text/html":g,"text/plain":f})):p.showMessage("Type text/rtf not supported on write"),
navigator.clipboard.write([g])),g=!0;else{k=sb(f,!1);if("div"==f)if(k.innerHTML=c,k.focus(),m&&document.body.createControlRange){var u=document.body.createControlRange();u.add(k.childNodes[0]);m=!1}else D.selectEditable(k);else k.value=c,k.focus(),k.select();try{g=u?u.execCommand("Copy"):document.execCommand("copy",!1,null)}catch(e){}finally{p.focused=!0,k.parentNode.removeChild(k),A&&A.focus()}}fa=!0;if(!g&&p.beforeCopyDialog&&p.beforeCopyDialog(c,__svi18n.info.imgCopyDownload,d))return!0;m=m&&!g&&
y.processImgCopy(c);g||!m&&__svi18n.info.userCopy&&p.showMessage({title:__svi18n.info.userCopy,msg:c,timeout:9999,select:!0,format:d,cbYes:function(){navigator.clipboard.writeText(c)}});return g};this.processFileGroup=function(d){if("application/x-filegroup"==d.type){d=d.value.split("\r\n");var c="",f=0,g=null;d.forEach(function(m){m=m.split("\t");1<m.length&&(c&&(c+=","),c+=m[0],g||(g=m[0]),f+=parseInt(m[1],10))});28<c.length&&(c=c.substring(0,28)+"...");c=c+"<br>Total: "+hi5.tool.bytesToSize(f)+
" Qty:"+d.length;__svi18n.info.download&&p.showMessage({title:__svi18n.info.download,msg:c,timeout:9E3,html:!0,cbYes:function(){this.destroy();x.getFile(g,"clip")},cbNo:function(){this.destroy()}});return!0}return!1};this.processImgCopy=function(d){return 0<d.indexOf("data-sv-img")&&__svi18n.info.imgCopyDownload?(p.showMessage({title:__svi18n.info.imgCopyDownload,msg:d,timeout:9999,html:!0}),!0):!1}},Ja=D.isMacOS||D.isiOS,I=new function(){this.afterComposition=this.onComposition=this.ctrlDelayed=
this.noKeyStuck=!1;this.preKey={code:0,down:!1};this.preScancode={code:0,down:!1};var a=this.noUnicode=!1,b=!1,d=!1,c={},f=0;this.sendMissKey=function(g){if(!I.noKeyStuck)for(var m in c)if(c[m]){var k=parseInt(m,10);if(g)switch(k){case 42:case 59:if(g.shiftKey)return;break;case 29:case 157:if(Ja){if(g.metaKey)return}else if(g.ctrlKey)return;break;case 56:case 184:if(g.altKey)return;break;case 219:case 220:if(Ja){if(g.ctrlKey)return}else if(g.metaKey)return}svGlobal.logger.warn("kkk send missing key up: "+
k);F(!1,k)}};this.isKeyDown=function(g){return c[g]};this.isKeyDownSent=function(g,m){var k=!0;g||(k=c[m]);g?c[m]=g:delete c[m];return k};this.syncLockKeyStatus=function(g){if(g.getModifierState&&x.sendKeyboardSyncFlags){var m=0;g.getModifierState("CapsLock")&&(m|=4);Ja||D.isCrOS?m|=x.localLockFlags&2:g.getModifierState("NumLock")&&(m|=2);g.getModifierState("ScrollLock")&&(m|=1);x.sendKeyboardSyncFlags(m)?x.checkLockFlags=!1:x.checkLockFlags=!0}};this.check=function(g){var m=T.getKeyCode(g),k="keydown"==
g.type;x.checkLockFlags&&k&&144!=m&20!=m&&145!=m&&I.syncLockKeyStatus(g);17==m&&(ia=k)};this.continue=function(g,m,k){if(29==m&&g)return I.ctrlDelayed=!0,!1;if(I.ctrlDelayed||Ja&&g)if(184==m)I.ctrlDelayed=!1,d=b=!0;else if(I.ctrlDelayed)return I.ctrlDelayed=!1,b||F(!0,29,"Control"),!0;if(29==m){if(b&&!g)return!1}else if(184==m&&b)return g||(b=!1,a=!0,d&&k&&(F(!0,184,"AltGraph"),F(!1,184,"AltGraph"),d=!1)),k?!1:!0;return!0};this.isAltGr=function(g){return b?(d=!1,!0):a?(a=!1,g?!1:!0):!1};this.isNeedSyncKey=
function(){if(x){if(x.checkLockFlags)return f=1,!0;if(5>f)return f++,!0}return!1};this.setNeedSyncKey=function(g){x&&(x.checkLockFlags=g,f=0)}};this.requestCredential=function(a,b){w.closeOnDisconn=!1;var d=null,c=q.frmLogin;if(c)d=q.frmLogin;else{var f=__svi18n.template.login;if(!f){p.showMessage("No value for login template");return}d=document.createElement("div");d.className="appdlg";d.innerHTML=f;document.body.appendChild(d);c=hi5.$("frmLogin")}var g=Va(c,"loginDomain"),m="INPUT"==g.tagName.toUpperCase();
g&&a.nbDomain&&(m?g.value=a.nbDomain:g.innerHTML=a.nbDomain);var k=new hi5.ui.Lightbox(d);k.onclose=function(){document.body.removeChild(d)};k.show();(a=Va(c,"loginUser"))&&a.focus();c&&(c.onsubmit=function(){var u=Va(c,"loginUser").value,e=Va(c,"loginPassword").value,h=m?g.value:g.innerHTML;k.dismiss();setTimeout(function(){b(u,e,h)},5);return!1})};var A=null;if(Z)Nb();else{var Cb=hi5.$("tmContainer");Cb&&Cb.parentNode.removeChild(Cb)}Z&&!w.toolbar.draggable&&window.addEventListener("scroll",function(){setTimeout(function(){if(Y){var a=
q.pcKey;a&&(a.style.top=window.pageYOffset+"px",a.style.left=window.pageXOffset+"px")}p.toolbar&&(p.toolbar.style.top=window.pageYOffset+"px",p.toolbar.style.left=window.pageXOffset+.45*window.innerWidth+"px")},200)},!1);this.setCaretPos=function(a,b){};this.showMessage=function(a,b){a&&w.displayMsg&&cc.notify("string"==typeof a?{msg:a,timeout:b||0}:a)};this.hideWhenClose="hideWhenClose"in w?w.hideWhenClose:!0;this.setReadOnly=function(a,b){$b=(V=!a)||!0===b};this.setPlayerMode=function(){xa=!0;p.showToolbar=
!1;p.setReadOnly(!0);p.hideWhenClose=!1};this.showTwoFAQR=function(){var a=x.getAppInfo(),b=hi5.$("twofainfo"),d=hi5.$("barcodeDiv"),c=hi5.$("enableTwoFA"),f=hi5.$("disableTwoFA");a.twoFAEnabled?(d.style.display="none",f.style.display="block",c.style.display="none"):(hi5.$("imgBarcode").src="data:image/png;base64,"+hi5.Base64.enc(a.twoFAQR),d.style.display="block",f.style.display="none",c.style.display="block");var g=hi5.$("faCode");g.value="";var m=new hi5.ui.Lightbox(b);m.show();c.onclick=f.onclick=
function(k){var u=g.value;k=k.target==c?1:0;x.onauthcoderesult=function(e,h){h?m.dismiss():(g.value="",p.showMessage(__svi18n.errorCode.S3021||"Wrong authentication code",5E3))};6!=u.length?hi5.notifications.notify(__svi18n.info.digit6||"It must be a 6 digit number"):x.authWithCode(u,k)}};this.showTwoFACode=function(){var a=hi5.$("twofacode");if(a){var b=new hi5.ui.Lightbox(a,{noClose:!0});b.show();var d=hi5.$("btnTwoFACode"),c=hi5.$("faAuthCode");c.value="";d.onclick=function(){var f=c.value;6!=
f.length?hi5.notifications.notify(__svi18n.info.digit6||"It must be a 6 digit number"):(x.onauthcoderesult=function(g,m){m?b.dismiss():(c.value="",p.showMessage(__svi18n.errorCode.S3021||"Wrong authentication code",5E3));x.onauthcoderesult=null},x.authWithCode(f,2))};c.addEventListener("keyup",function(f){if(13==f.keyCode||"Enter"==f.code)f.preventDefault(),d.click()})}};this.setAutoScale=function(a){var b="autoScale"in w;b&&(a=w.autoScale);a?(Pa(!0),pb("hidden")):b||Pa(!1);Ca=a};this.getAutoScale=
function(){return Ca};Ta&&Oa(w.cursorNameOnly);this.setTouchpad=function(a){ra=a;var b=hi5.$("touchpadMode");b&&(b.checked=a,b.onchange=function(d){ra=d.target.checked});a&&(r||Oa(w.cursorNameOnly))};this.setExtKeyboard=function(a){if(Z){A.adjust(!0);A.setContentEditable(a?"true":"false");va=a?1:0;D.isChrome&&A.setFontSize("2em");a&&A.focus();var b=hi5.$("extKBD");b&&b.checked!=a&&(b.checked=a)}};this.focus=function(){A&&B(A.element)};this.getInputElement=function(){return A};this.scaleTo=function(a,
b,d){ib=a;dc=b;yb=d;l&&50<W&&(a/=W,b/=X,yb?(ea=a,la=b):la=ea=b=a=Math.min(a,b),hi5.tool.scale(l.parentNode,a,b))};this.setSize=function(a,b,d){z.isMultiMon||(z.right!=z.left+a-1&&(z.right=z.left+a-1,z.bottom=z.top+b-1),W=a,X=b,Ca||pb(d),l.width=W,l.height=X,Ca?Pa(!0):ib&&ib!=a&&p.scaleTo(ib,dc,yb),Z&&Nb(),Fb())};this.reposition=function(){A.adjust()};this.setDrawable=function(a){ma!=a&&(ma=a,Ra=a.draw)};this.getDrawable=function(){return ma};this.getController=function(){return x};this.setController=
function(a){x!=a&&(x=a,a.draw&&this.setDrawable(a),x.sendInput||(x.sendInput=x.send),Z&&D.setOrientaionHandler(function(){Ca?Pa(!0):(clearTimeout(fc),fc=setTimeout(function(){window.innerWidth>window.innerHeight!=W>X&&(x.onorientationchange({svSurface:p,innerWidth:window.innerWidth,innerHeight:v(window.innerHeight)}),w.disableScoll||window.scrollTo(0,0))},555))}))};this.setFileHandler=function(a){"FileReader"in window||(a=null);if(a){if(!P&&!xa)if(P=a,P.addEvent("uploaded",function(d,c){!d&&hi5.$("filecontainer")&&
gc&16&&(hi5.$("__cancelUpload")&&(hi5.$("__cancelUpload").style.visibility="hidden"),p.fileProgress&&(p.fileProgress.maxValue=0,p.fileProgress.style.display="none"),p.refreshFiles(!ha),!c.cancelled&&__svi18n.file.uploadDone&&c.size&&c.duration&&p.showMessage(__svi18n.file.uploadDone+" "+hi5.tool.bytesToSize(c.size/(c.duration/1E3))+"/s",5E3))}),P.addEvent("uploadstarted",function(d){d&&setTimeout(hb,999)}),hi5.$("filecontainer")){hi5.$("filecontainer").className="h5-form";hi5.$("total")&&(p.fileProgress=
new hi5.ProgressBar(hi5.$("total")));var b=hi5.$("__cancelUpload");b&&b.addEventListener("click",function(){P.cancelAll()},!1);P.addEvent("beforeupload",function(d,c,f){f||(b&&(b.style.visibility="visible"),p.fileProgress&&(p.fileProgress.style.display="block",p.fileProgress.maxValue+=d.size))});P.addEvent("progress",function(d){p.fileProgress&&p.fileProgress.setProgress(d)})}else rb()}else P=null,p.fileProgress=null,rb(),ta&&(ta.release(),ta=null);Pb();rc()};this.setFeature=function(a){gc=a;var b,
d=!(a&16),c=!(a&65536);(d||xa)&&rb();a&128&&(b=hi5.$("uploadfile"))&&(b.style.visibility="hidden");a&131072&&((b=hi5.$("__sv_download__"))&&b.parentNode.removeChild(b),(b=hi5.$("__sv_view__"))&&b.parentNode.removeChild(b));a&1048576&&(b=hi5.$("__sv_view__"))&&b.parentNode.removeChild(b);a&256||(b=hi5.$("shadowing"))&&b.parentNode.removeChild(b);a&1024||(b=hi5.$("ssParent"))&&b.parentNode.removeChild(b);(c&&d||xa)&&p.setFileHandler(null)};var Qa=new function(){function a(){if(0===d.length){if(c=!1,
!f){var m=hi5.$("_sv_pdf_parent");m&&g&&g.visible()&&g.dismiss();m&&m.parentNode&&setTimeout(function(){m&&m.parentNode&&m.parentNode.removeChild(m)},9999);D.isFirefox&&x&&x.restoreResize&&x.restoreResize()}}else b()}function b(){var m=d.shift();if(m){var k=hi5.$("_sv_pdf_parent"),u=__svi18n.info.printready||"Your document is ready.",e=m.endsWith(".txt");m=(f=!e&&(D.isAndroid||D.isiOS||!!w.showPDFLink))?'<p style="text-align:center;line-height:4em"><a href="'+m+'" target="_blank">'+u+"</a></p>":(D.isChromeApp?
"<webview":"<iframe")+' src="'+m+'" width="100%" height="100%" id="_iFramePDF">'+(D.isChromeApp?"</webview>":"</iframe>");k&&k.visible&&k.visible()&&k.dismiss&&k.dismiss();k&&k.parentNode&&k.parentNode.removeChild(k);k=document.createElement("div");k.style.backgroundColor="white";k.style.width=f?"30%":"70%";k.style.height=f?"4elm":"70%";k.id="_sv_pdf_parent";f?k.style.overflow="scroll":!e&&D.isFirefox&&x.saveResize&&x.saveResize(!1);k.innerHTML=m;document.body.appendChild(k);g=new hi5.ui.Lightbox(k,
{close:{top:"-20px",right:"-15px"}});g.onclose=a;g.show();e&&(k=document.getElementById("_iFramePDF").contentWindow,k.focus(),k.print())}c=!0}var d=[],c=!1,f=!1,g=null;this.clearPDF=function(){a()};this.showPDF=function(m){d.push(m);c||b()}};this.close=function(){Bb=!1;svGlobal.logger.info("close ui...");V=!1;db&&cancelAnimationFrame(db);ab();Aa&&(Aa.release(),Aa=null);if(document){if(A){var a=A.element;document.removeEventListener("mousemove",mb,!1);a.removeEventListener("mousedown",lb,!1);document.removeEventListener("mouseup",
nb,!1);a.removeEventListener("mouseleave",cb,!1);a.removeEventListener("mouseenter",cb,!1);a.removeEventListener("paste",y.onPaste,!1);a.removeEventListener("copy",y.onCopy,!1);a.removeEventListener("cut",y.onCopy,!1);a.removeEventListener("focus",Hb,!1);a.removeEventListener("blur",Mb,!1)}y&&(document.removeEventListener("paste",y.onPaste,!1),document.removeEventListener("copy",y.onCopy,!1),document.removeEventListener("cut",y.onCopy,!1))}if(window){window.removeEventListener("resize",Lb,!1);window.removeEventListener("beforeunload",
Ib,!1);window.removeEventListener("unload",ab,!1);ka=null;r&&(r.parentNode&&r.parentNode.removeChild(r),r=null);p&&p.toolbar&&(p.toolbar.setFadable=null,p.toolbar.startFade=null,p.toolbar.style.display="none",hi5.ui.clean(p.toolbar),p.toolbar=null);try{Wa&&Wa.parentNode&&(Wa.parentNode.removeChild(Wa),Wa=null),A&&(A.remove(),A=null)}catch(d){}}y&&(y.release(),y=null);bb&&(bb.release(),bb=null);ta&&(ta.release(),ta=null);ja&&(ja.release(),ja=null);x=Ra=Da=ka=r=ha=P=ja=U=I=T=null;p.fileProgress=null;
Qa&&Qa.clearPDF();Qa=null;Ca&&p.setAutoScale(!1);Y&&(Y.setVisibility(!1),Y.release(),Y=null);"clearScreen"in w&&!w.clearScreen||M.fillRect(0,0,l.width,l.height);window.svSurface&&window.svSurface==p&&(window.svSurface=null);Jb=!0;if(window&&!xa){try{if(w.closeOnDisconn)window.close();else if(this.hide(),D.isChromeApp){var b=chrome.app.window.current();b&&!w.disableMaxFullScn&&(b.onMaximized.removeListener(Gb),b.isFullscreen()&&(b.restore(),b.restore()))}}catch(d){}p=l=M=p.context=null;svGlobal.logger.info("closed ui")}};
this.setFastCopy=function(a){};this.drawLicense=function(a){if(0!=w.drawLicense){var b=a.charAt(0);M.save();M.font="12pt Arial";M.fillStyle="W"==b?"red":"black";a=a.substring(1);M.fillText(a,10,X-24);M.restore()}};this.drawText=function(a){var b=w.text||{};M.save();var d=l.width,c=l.height;M.fillStyle=b.backgroundFillStyle||"white";M.fillRect(0,0,d,c);var f=20,g=50;"center"==b.textAlign&&(f=d/2,g=c/2);M.font=b.font||"18pt Arial";M.fillStyle=b.fillStyle||"black";b.textAlign&&(M.textAlign=b.textAlign);
b.textBaseline&&(M.textBaseline=b.textBaseline);M.fillText(a,f,g);M.restore()};this.showPlay=function(){M.save();var a=l.width,b=l.height;M.fillStyle="grey";M.fillRect(0,0,a,b);a=a/2|0;var d=b/2|0;b=b/20|0;M.fillStyle="white";M.beginPath();var c=a-b,f=d-b;M.moveTo(c,f);M.lineTo(c,d+b);M.lineTo(a+b,d);M.lineTo(c,f);M.fill();M.restore()};this.showPDF=function(a){Qa.showPDF(a)};this.showPrinters=function(a){var b=hi5.$("localPrinter");if(b){var d=hi5.$("selectPrinter");x.getPrinters(function(f){var g=
d.options;g.length=0;g[0]=new Option(".........");for(var m=0,k=f.length;m<k;m++)g[m+1]=new Option(f[m].name,f[m].driver)});var c=new hi5.ui.Lightbox(b);c.show();c.onclose=function(){if(0<d.selectedIndex){var f=d.options[d.selectedIndex],g=f.label,m=b.querySelector('[name="driverName"]:checked');f=f.value;m&&(m=m.value,"remote"==m?f="":"local"!=m&&(f=m));m=b.querySelector('[name="isDefault"]').checked;a({name:g,driver:f,isDefault:m})}else a(null)}}};this.hide=function(){p.hideWhenClose&&(l.height=
1,l.width=1);A&&A.hide()};var hc=0;this.copyToClip=function(a,b){oa&&Fa&&(a=y.parseClipData(a),w.copyTextOnly&&"text/plain"!=a.type||y.processFileGroup(a)||(y.waitingCopyContent?y.copyContent=a:(b=a.value,(!w.copyDialog&&(!b.startsWith("<img data-sv-img")||navigator.clipboard&&navigator.clipboard.write)||y.hasCopyCmd||navigator.clipboard)&&y.copyToClipboard(a.type,b))))};Y=new function(){function a(){d&&(ia?hi5.html.addClass(d,"button_selected"):hi5.html.removeClass(d,"button_selected"));c&&(za?hi5.html.addClass(c,
"button_selected"):hi5.html.removeClass(c,"button_selected"));f&&(Ka?hi5.html.addClass(f,"button_selected"):hi5.html.removeClass(f,"button_selected"))}function b(n){n=n.target;var J=n.innerHTML;J=J.replace(/\u2190/g,"left").replace(/\u2191/g,"up").replace(/\u2192/g,"right").replace(/\u2193/g,"down");switch(J){case "Ctrl":d||(d=n);ia?F(!1,29,"Control"):F(!0,29,"Control");ia=!ia;a();break;case "Alt":c||(c=n);za?F(!1,56,"Alt"):F(!0,56,"Alt");za=!za;a();break;case "Shift":f||(f=n);Ka?F(!1,42,"Shift"):
F(!0,42,"Shift");Ka=!Ka;a();break;case "...":if(n=Va(q.pcKey,"pc_key_more"))n.style.display="block"==n.style.display?"none":"block";break;case "Start":J="Ctrl+Esc";default:p.writeKeyComb(J),Y.resetModifier()}}var d=null,c=null,f=null,g={ctrl:!1,alt:!1,shift:!1};this.release=function(){g=null};this.setStickyKey=function(n){g=n};this.setVisibility=function(n){if(n){if(va=Date.now(),n=q.pcKey)n.style.display="block",n.style.top=window.pageYOffset+"px",ja&&(ja.setValue("`\t`"),ja.select())}else if(va=
0,n=q.pcKey)n=hi5.$("shortcuts"),n&&n.checked||(m.style.display="none")};this.resetModifier=function(){za&&!g.alt&&(za=!1,F(!1,56,"Alt"));ia&&!g.ctrl&&(ia=!1,F(!1,29,"Control"));Ka&&!g.shift&&(Ka=!1,F(!1,42,"Shift"));a()};var m=q.pcKey;if(m){var k=m.getElementsByTagName("span"),u=k.length,e=D.isFirefox?"mousedown":"touchstart";"ontouchstart"in window||(navigator.pointerEnabled?e="pointerdown":navigator.msPointerEnabled&&(e="MSPointerDown"));for(var h=0;h<u;h++){var t=k[h];t.className="button";t.addEventListener(e,
b,!1);"mousedown"!=e&&t.addEventListener("mousedown",b,!1)}m.style.position="absolute"}};this.setStickyKey=function(a){Y.setStickyKey(a)};var ic=hi5.$("shortcuts");ic&&ic.addEventListener("change",function(a){Y.setVisibility(a.target.checked)});this.setKeysVisibility=function(a){Y&&Y.setVisibility(a)};this.setDirectory=function(a){var b=hi5.$("parentPath");b&&"."!=a&&(b.currentDir=a)};this.refreshFiles=function(a){a?(ya(".",null),(a=document.getElementById("__sv_folder__"))&&!a.onclick&&P.mkdirs&&
(a.onclick=function(){var b=document.getElementById("__sv_folder_name_");b&&b.value&&(P.mkdirs(b.value),ya(".",null),b.value="")})):ha&&ha.visible()?ya(".",ha):Ob(null)};this.showConnectonInfo=function(){var a=x.getAppInfo(),b=hi5.$("numericId");b&&(b.innerHTML=a.numericId);if(b=hi5.$("connectingTo"))b.innerHTML=a.server;if(b=hi5.$("joinLink"))if(b.href=b.innerHTML=a.joinLink,b=document.getElementById("shareSession"))navigator.share?b.onclick=function(d){navigator.share({url:a.joinLink})}:b.style.display=
"none";b=new hi5.ui.Lightbox(hi5.$("appinfo"));b.show();A&&(A.element.oncontextmenu=null,A.element.onselectstart=null);b.onclose=Kb;b=hi5.$("btnTwoFA");hi5.$("twofainfo")&&b&&(a.twoFAEnabled||a.twoFAQR?b.onclick=function(){p.showTwoFAQR()}:b.disabled=!0);if(b=hi5.$("attachPrinter"))b.disabled=!x.getAgentStatus||1!=x.getAgentStatus()};this.setupTwoFA=function(a){};this.processLink=function(a){function b(f){window.open(a);f.target.parentNode.removeChild(f.target)}if(p.beforeOpenLink)return p.beforeOpenLink(a);
if(!p.toolbar)return!1;clearTimeout(hc);var d=p.toolbar,c=d.getButton("_svLinkInfo");c?c.onclick=b:(c=d.addButton(w.img.link?w.img.link:"link.png",b),c.id="_svLinkInfo");c.title=a;d.startFade();hc=setTimeout(function(){p.toolbar&&p.toolbar.removeButton("_svLinkInfo")},1E4);return!0};this.setUnicode=function(a){A&&(!a&&Z&&(D.isiOS||D.isAndroid)&&(a=!0),svGlobal.logger.info("Unicode:"+a),R.onkeydown=R.onkeyup=a?tc:Ub,R.ontextinput=a?vc:null,R.unicode=a)&&(R.oncomposition=uc)};this.forceScancode=function(a){Xb=
a};this.setTouchRemoting=function(a){!0===a?(Da=new kc(p,l),svGlobal.logger.info("touch remoting"),__svi18n.info.touchremoting&&p.showMessage(__svi18n.info.touchremoting)):Da=new Eb(p)};this.setClipboard=function(a,b,d){(oa=a)?(Fa=void 0==b?!0:b,Ab=void 0==d?!0:d,y.init()):Ab=Fa=!1;Ma=a?!D.isChromeApp&&!w.copyDialog&&!w.directClipAccess&&!D.isIE:!1};this.setJoinMode=function(a){x.setJoinMode(a)};this.requestControl=function(){x.requestControl()};this.repaint=function(a,b,d,c){z.isMultiMon?(a<z.left&&
(a=z.left),b<z.top&&(b=z.top),d>z.right&&(d=z.right),c>z.bottom&&(c=z.bottom),a<=z.right&&b<=z.bottom&&(a=ma.refresh(a,b,d,c,Ba))&&M.putImageData(a.imgData,a.left-z.left,a.top-z.top,0,0,a.width,a.height)):(a=ma.refresh(a,b,d,c,Ba))&&M.putImageData(a.imgData,a.left,a.top,0,0,a.width,a.height)};this.running=function(){return Bb};this.run=function(a,b,d,c){function f(g){g.target.removeEventListener("click",f,!1);x.send("884")}Bb=!0;T.converMacCtrl=!1!==b;T.mapCmdToCtrl=!1!==c;I.noKeyStuck=!!d;!T.mapCmdToCtrl&&
D.isMacOS&&C();Fb(2052==a||1028==a);cc.clearAll();3758162961!=a&&3758162962!=a||!A||A.setContentEditable("false");T.setLayout(a);a=-1!=[99997,99998,99999].indexOf(a);void 0==w.closeOnDisconn&&(w.closeOnDisconn=!!window.opener&&!D.isChromeApp);w.disableScoll||window.scrollTo(0,0);Pb();pc();b=A.element;xa||(Da=new Eb(p),Aa=new qa(b),Aa.ontouch=sc,Aa.onmousedown=lb,Aa.onmousemove=mb,Aa.onmouseup=nb,b.addEventListener("mouseleave",cb,!1),b.addEventListener("mouseenter",cb,!1),ba(b,yc,!1),b.addEventListener("paste",
y.onPaste,!1),oa&&Ma&&Fa&&(b.addEventListener("copy",y.onCopy,!1),b.addEventListener("cut",y.onCopy,!1)));!1!==w.autoFocus&&B(b);p.setUnicode(a);this.drawText(__svi18n.wait);if(p.onstart)p.onstart(l);b.addEventListener("click",f,!1);Ra&&(db=requestAnimationFrame(Qb));A.adjust();w.disableScoll||window.scrollTo(0,0)};var ub=(w.animation||42)|0;D.isIE&&(ub*=2);this.setFPS=function(a){ub=1E3/a|0};this.moveCursorBy=this.movCursorBy=Rb;this.moveCursor=function(a,b,d,c,f,g){a-=z.left;b-=z.top;0>a||0>b||
a>=W||b>=X||(r||Oa(w.cursorNameOnly),r.__visible||r.__setVisible(!0),r.scrX=a,r.scrY=b,r.moveCursor(a+z.offX,b+z.offY,c,f,g),V&&!d&&x.sendInput("82"+a+"\t"+b),z.x=a,z.y=b)};this.switchSoftKeyboard=vb;this.isSoftKeyboardOn=function(){return La};var jc=hi5.$("svTouchInput");jc&&jc.addEventListener("click",function(){vb()},!1);this.touchstart=function(a){switch(a.pointes){case 1:ra?(r||Oa(w.cursorNameOnly),wb("touchstart",a.screenX,a.screenY,!a.flick)):a.flick&&!Ga()||Sa(a.x,a.y,0);break;case 2:eb=a.screenX,
Ia=a.screenY}};this.touchmove=function(a){switch(a.pointes){case 1:ra?wb("touchmove",a.screenX,a.screenY,!a.flick):(!a.flick||Ga())&&Zb(a.x,a.y);break;case 2:19<Math.abs(a.screenY-Ia)&&(ac(a.x,a.y,0<a.screenY-Ia?0:1),eb=a.screenX,Ia=a.screenY)}};this.touchend=function(a){switch(a.pointes){case 1:ra?wb("touchend",a.screenX,a.screenY,!a.flick):(Ha(a.x,a.y,!0),a.flick&&!Ga()||Ua(a.x,a.y,0));break;case 2:if(!a.moved){var b=ra?r.scrX:a.x;a=ra?r.scrY:a.y;Ha(b,a);Sa(b,a,2);Ua(b,a,2)}break;case 3:if(a.gesture)switch(a.gesture){case "OPEN":F(!0,
219);F(!0,200);F(!1,200);F(!1,219);break;case "CLOSE":F(!0,219);F(!0,208);F(!1,208);F(!1,219);break;case "LEFT":F(!0,56);F(!0,1);F(!1,1);F(!1,56);break;case "RIGHT":F(!0,42);F(!0,56);F(!0,1);F(!1,1);F(!1,56);F(!1,42);break;case "UP":F(!0,42);F(!0,219);pa(!0,77,50);pa(!1,77,50);F(!1,219);F(!1,42);break;case "DOWN":F(!0,219),pa(!0,77,50),pa(!1,77,50),F(!1,219)}else vb()}};this.flick=function(a){switch(a.from){case 4:x.sendInput("840\t209");x.sendInput("8449152\t209");break;case 2:x.sendInput("840\t201"),
x.sendInput("8449152\t201")}};this.longpress=function(a){ra&&(a.pointes=2);switch(a.pointes){case 1:var b=a.x;a=a.y;Ha(b,a);Sa(b,a,2);Ua(b,a,2);break;case 2:r&&(Sa(r.scrX,r.scrY,2,1),Ua(r.scrX,r.scrY,2,1))}};this.redirectTouches=function(a){if(V){for(var b=a.length,d,c="90"+b,f=0;f<b;f++)d=a[f],c=c+"\t"+d.contactId+";"+d.contactFlags+";"+Math.floor(d.x/ea)+";"+Math.floor(d.y/la);x.send(c)}};var fb=0;this.setIgnorePaste=function(a){fa=a};this.processClipReq=function(a,b){if(!oa)return x.send("881ERROR\t"),
!0;var d=y.clipData;b||(b=wc);return d||fa?(b(d,a),!0):y.accessClip(function(c){b(c,a)},a)};var gb=D.isIE?new function(){var a;this.sendCtrlVLater=function(){a=setTimeout(hb,333)};this.cancelCtrlV=function(){clearTimeout(a)};return this}:null;this.getMousePosition=function(){return z};this.writeKeyComb=function(a){x.writeKeyComb(a)};this.setCursor=function(a){a&&!w.disableCursor&&(ka=a,r&&r.setCursor(a),r&&Ta&&!a.system&&(r.__setVisible(!0),Ha(z.x,z.y,!0)),xa||(a.result||(a.result=w.cursorNameOnly?
"none":zc(a)),A?A.element.style.cursor=a.result:l.style.cursor=a.result))};this.setVisible=function(a,b){var d=a?"visible":"hidden";"number"==typeof b?setTimeout(function(){l.style.visibility=d},b):l.style.visibility=d};this.initWhiteboard=function(a,b){var d=l.parentNode,c=d.querySelector('canvas[name="svWhiteboard"]');c||(c=document.createElement("canvas"),c.setAttribute("name","svWhiteboard"),c.width=a||W,c.height=b||X,c.style.zIndex=80,a=A.element,c.style.position=a.style.position,c.style.left=
a.style.left,c.style.top=a.style.top,d.appendChild(c));return c};this.removeWhiteboard=function(){var a=l.parentNode,b=a.querySelector('canvas[name="svWhiteboard"]');b&&a.removeChild(b)};this.requestFullscreen=function(a){document.fullscreenElement?(document.exitFullscreen(),document.removeEventListener("fullscreenchange",bc,!1)):(!1!==a&&document.addEventListener("fullscreenchange",bc,!1),document.body.requestFullscreen())};this.requestUsbDevices=function(a,b){var d=[],c=document.getElementById("usbPicker"),
f=document.getElementById("addUSB"),g=document.getElementById("selectedUSB");f.onclick=function(){navigator.usb.requestDevice(a).then(function(k){d.find(function(u){return u.serialNumber==k.serialNumber&&u.vendorId==k.vendorId&&u.productId==k.productId})||k.open().then(function(){d.push(k);var u=document.createElement("option");u.innerHTML=k.productName||"Unknown USB device";g.appendChild(u);k.close()}).catch(function(u){hi5.notifications.notify("Failed to open "+k.productName+" Error:"+u)})})};var m=
new hi5.ui.Lightbox(c);m.onclose=function(){f.onclick=null;g.length=0;b(d)};document.getElementById("frmUsbPicker").onsubmit=function(k){k.preventDefault();m.dismiss();return!1};m.show()}}svGlobal.LocalInterface||(svGlobal.LocalInterface=LocalInterface);
svGlobal.rdpFile={loadRdpFile:function(l,q){var v=q.elements,B=l.split("\r\n");2>B.length&&(B=l.split("\n"));if(2>B.length)return!1;l=hi5.$("gateway");var E=l.value;q.reset();l.value=E;q=0;for(l=B.length;q<l;q++){var C=B[q];E=C.indexOf(":");var O=C.substring(0,E);C=C.substring(E+3);O=O.toLowerCase();switch(O){case "full address":E=C.indexOf(":");0<E?(v.server.value=C.substring(0,E),v.port.value=C.substring(E+1)):v.server.value=C;break;case "username":v.user.value=C;break;case "domain":v.domain.value=
C;break;case "connect to console":v.useConsole.checked="0"!=C;break;case "desktopwidth":v.width.value=C;break;case "desktopheight":v.height.value=C;break;case "session bpp":v.server_bpp.value=C;break;case "audiomode":v.playSound.value=C;break;case "alternate shell":0<C.length&&(v.command.value=C,hi5.$("app").checked||(hi5.$("shell").checked=!0));break;case "shell working directory":v.directory=C;break;case "redirectclipboard":v.mapClipboard.checked="0"!=C;break;case "redirectprinters":v.mapPrinter.checked=
"0"!=C;break;case "server port":0<C.length&&(v.port.value=C);break;case "disable wallpaper":v.background.checked="0"==C;break;case "disable themes":v.styles.checked="0"==C;break;case "disable menu anims":v.animation.checked="0"==C;break;case "disable full window drag":v.contents.checked="0"==C;break;case "allow font smoothing":v.smoothfont.checked="0"!=C;break;case "allow desktop composition":v.composition.checked="0"!=C;break;case "bitmapcachepersistenable":v.bitmap.checked="0"!=C;break;case "remoteapplicationprogram":v.exe.value=
C;break;case "remoteapplicationcmdline":v.args.value=C;break;case "remoteapplicationmode":hi5.$("app").checked="1"==C;break;case "loadbalanceinfo":v.loadBalanceInfo.value=C}}return!0},handleFiles:function(l,q){if(1!=l.length)hi5.notifications.notify({msg:"Please one file only"});else{var v=l[0];l=v.name;var B=l.length;if(4<B&&".rdp"==l.substring(B-4).toLowerCase()){var E=new FileReader,C=!1;E.onload=function(O){!(O=O.target.result)||svGlobal.rdpFile.loadRdpFile(O,q)||C||(C=!0,E.readAsText(v))};E.readAsText(v,
"UTF-16LE")}else hi5.notifications.notify({msg:"Sorry, Please .rdp file only"})}}};
function initDragDrop(l,q){function v(C){svGlobal.rdpFile.handleFiles(C.target.files,q)}if("FileReader"in window){var B=l.style.backgroundColor,E=hi5.$("rdpfile");E&&E.addEventListener("change",v,!1);l.addEventListener("dragover",function(C){cancelDefault(C);l.style.backgroundColor="yellow"},!1);l.addEventListener("dragleave",function(C){cancelDefault(C);l.style.backgroundColor=B},!1);l.addEventListener("drop",function(C){cancelDefault(C);l.style.backgroundColor=B;svGlobal.rdpFile.handleFiles(C.dataTransfer.files,
q)},!1)}}svGlobal.util.initDragDrop=initDragDrop;
svGlobal.util.initMapDisk=svGlobal.util.MapDisk=function(l,q,v){function B(O){cancelDefault(O);q&&("0.6"!=l.style.opacity&&(l.style.opacity="0.6"),l.style.backgroundColor="yellow")}function E(O){cancelDefault(O);q&&(l.style.opacity=l.__oldOpacity,l.style.backgroundColor=l.__oldColor)}function C(O){cancelDefault(O);if(q){l.style.opacity=l.__oldOpacity;l.style.backgroundColor=l.__oldColor;var ba=hi5.file.getEntries(O);!ba.length||"file:"==location.protocol&&!hi5.browser.isElectron&&hi5.browser.isChrome?
q.addFiles?q.addFiles(O.dataTransfer.files,v):q.addFile(O.dataTransfer.files[0]):hi5.file.getFilesFromEntries(ba,function(qa){q.addFiles?q.addFiles(qa,v):q.addFile(qa[0])})}}"FileReader"in window&&(l.__oldColor=l.style.backgroundColor,l.__oldOpacity=l.style.opacity,l.addEventListener("dragover",B,!1),l.addEventListener("dragleave",E,!1),l.addEventListener("drop",C,!1),this.release=function(){l.removeEventListener("dragover",B,!1);l.removeEventListener("dragleave",E,!1);l.removeEventListener("drop",
C,!1);l=q=null})};
svGlobal.util.getServerArgs=function(l){var q=window.opener;if(!l)try{q&&q.__sparkUser&&q.__sparkUser.server&&(l=q.__sparkUser.server),!l&&q.sparkServer&&(l=q.sparkServer)}catch(v){}l?(q=l.rdp||l.vnc||l.ssh||l.telnet||null)&&!l.server&&(q.gateway=l.gateway,q.session=l.session,q.account=l.account,q.server=l.id,q.displayName=l.displayName,q.shadowing=l.shadowing,q.user=q.username||"",q.pwd=q.password||"",q.useConsole=q.console||!1,q.server_bpp=q.color,q.legacyMode=q.leagacyMode||q.legacyMode||!1,q.exe=
q.remoteProgram||"",q.args=q.remoteArgs||"",q.startProgram=0<q.exe.length?"app":q.command&&0<q.command.length?"shell":"noapp",l.keyboard&&(q.keyboard=l.keyboard),l=q):l=hi5.browser.cookie2Obj();return l};(function(){function l(q){q=document.getElementsByClassName("ver");for(var v=q.length,B=0;B<v;B++)q[B].innerHTML=svGlobal.version;window.removeEventListener("load",l,!1)}window.addEventListener("load",l,!1)})();svGlobal.gatewayError=function(l,q){(l=__svi18n.errorCode["S"+l])?q&&(l+="; "+q):l=q;hi5.notifications.notify(l)};
svGlobal.ui={initMonitors:function(l){if(!("getScreenDetails"in window&&screen.isExtended))return!1;window.getScreenDetails().then(function(q){q.screens.forEach(function(v,B){var E=document.createElement("div"),C=document.createElement("input");C.type="checkbox";C.value=B;var O=document.createElement("label");B=B+": "+v.width+" x "+v.height+"; ("+v.left+","+v.top+")";v==q.currentScreen&&(B+=" *");O.innerHTML=B;C.onclick=function(){if(C.checked){svGlobal.monitors=svGlobal.monitors||[];var ba=q.screens[parseInt(C.value)],
qa=window.open("monitor.html","","left="+ba.left+",top="+ba.top+",width="+ba.width+",height="+ba.height+",fullscreen=yes,directories=no,location=no,menubar=no,resizable=no,scroolbars=no,status=no,toolbar=no");qa.moveTo(ba.left,ba.top);qa.resizeTo(ba.width,ba.height);qa.document.body.requestFullscreen().catch(function(Ga){svGlobal.logger.info(Ga)});svGlobal.monitors.push(qa)}};E.appendChild(C);E.appendChild(O);l.appendChild(E)})}).catch(function(q){hi5.notifications.notify("Failed to get screen details."+
q)});return!0}};svGlobal.logger.info("ver:"+svGlobal.version);(1>window.devicePixelRatio||1<window.devicePixelRatio&&2>window.devicePixelRatio)&&svGlobal.logger.info("Please make sure the zoom level of your browser is 100%");
