var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(g,l,p){if(null==g)throw new TypeError("The 'this' value for String.prototype."+p+" must not be null or undefined");if(l instanceof RegExp)throw new TypeError("First argument to String.prototype."+p+" must not be a regular expression");return g+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(g,l,p){if(g==Array.prototype||g==Object.prototype)return g;g[l]=p.value;return g};
$jscomp.getGlobal=function(g){g=["object"==typeof globalThis&&globalThis,g,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var l=0;l<g.length;++l){var p=g[l];if(p&&p.Math==Math)return p}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(g,l){var p=$jscomp.propertyToPolyfillSymbol[l];if(null==p)return g[l];p=g[p];return void 0!==p?p:g[l]};$jscomp.polyfill=function(g,l,p,E){l&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(g,l,p,E):$jscomp.polyfillUnisolated(g,l,p,E))};
$jscomp.polyfillUnisolated=function(g,l,p,E){p=$jscomp.global;g=g.split(".");for(E=0;E<g.length-1;E++){var I=g[E];if(!(I in p))return;p=p[I]}g=g[g.length-1];E=p[g];l=l(E);l!=E&&null!=l&&$jscomp.defineProperty(p,g,{configurable:!0,writable:!0,value:l})};
$jscomp.polyfillIsolated=function(g,l,p,E){var I=g.split(".");g=1===I.length;E=I[0];E=!g&&E in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var ba=0;ba<I.length-1;ba++){var ka=I[ba];if(!(ka in E))return;E=E[ka]}I=I[I.length-1];p=$jscomp.IS_SYMBOL_NATIVE&&"es6"===p?E[I]:null;l=l(p);null!=l&&(g?$jscomp.defineProperty($jscomp.polyfills,I,{configurable:!0,writable:!0,value:l}):l!==p&&($jscomp.propertyToPolyfillSymbol[I]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(I):$jscomp.POLYFILL_PREFIX+
I,I=$jscomp.propertyToPolyfillSymbol[I],$jscomp.defineProperty(E,I,{configurable:!0,writable:!0,value:l})))};$jscomp.polyfill("String.prototype.startsWith",function(g){return g?g:function(l,p){var E=$jscomp.checkStringArgs(this,l,"startsWith");l+="";var I=E.length,ba=l.length;p=Math.max(0,Math.min(p|0,E.length));for(var ka=0;ka<ba&&p<I;)if(E[p++]!=l[ka++])return!1;return ka>=ba}},"es6","es3");var svManager={getInstance:function(){var g=window.$telnet;return g&&g.running&&g.running()?g:null}};
function connvertServer(g){var l={};l.id=g.id;l.server=g.id;l.displayName=g.displayName||g.id;if(g=g.vnc)for(var p in g)l[p]=g[p];return l}
svGlobal.TELNET=function(g,l,p){function E(a,b){var e=[],c=null,d=new hi5.graphic.Rectangle(0,0,0,0),A="Uint8ClampedArray"in window;this.width=a;this.height=b;var f=!1,G=this;this.pause=function(m){f=m};this.release=function(){e=c=G=null};this.isPaused=function(){return f};this.setContext=function(m){m!=c&&(c||!m||m.createImageData(1,1).data.buffer||(A=!1),c=m)};this.getContext=function(){return c};this.resize=function(m,q){for(var u=0;u<q;u++)e[u]=new Uint32Array(m);G.width=a=m;G.height=b=q};G.resize(a,
b);this.getBuffer=function(){return e};this.setRGB=function(m,q,u){e[q][m]=u|4278190080};this.getRGB=function(m,q){return e[q][m]};this.setRGBs=function(m,q,u,x,H,B,J){u=m+u;x=q+x;for(var C=e,F,N=q;N<x;N++,B+=J){var fa=B;F=C[N];for(q=m;q<u;q++)F[q]=H[fa++]}};this.moveArea=function(m,q,u,x,H,B){if(0<B){H=m+H;B=q+B;var J=e,C;for(C=x-1;0<=C;C--){var F=J[B+C];var N=J[q+C];for(x=0;x<u;x++)F[H+x]=N[m+x]}}else if(0>B)for(H=m+H,B=q+B,J=e,F=0;F<x;F++){N=J[B+F];var fa=J[q+F];for(C=0;C<u;C++)N[H+C]=fa[m+C]}else if(0<
H)for(H=m+H,B=q+B,J=e,--u;0<=u;u--)for(F=H+u,N=m+u,C=0;C<x;C++)J[B+C][F]=J[q+C][N];else for(H=m+H,B=q+B,J=e,C=0;C<u;C++)for(N=H+C,fa=m+C,F=0;F<x;F++)J[B+F][N]=J[q+F][fa]};this.getRGBs=function(m,q,u,x){var H=_Uint32Array(u*x);H[0]=0;var B=e;u=m+u;x=q+x;for(var J=0,C=q;C<x;C++)for(q=m;q<u;q++)H[J++]=B[C][q];return H};this.repaint=function(m,q,u,x){if(c){0>m&&(u+=m,m=0);0>q&&(x+=q,q=0);m+u>a&&(u=a-m);q+x>b&&(x=b-q);var H=c.createImageData(u,x),B=H.data;u=m+u;x=q+x;var J=0,C=e;if(A){B=new Uint32Array(B.buffer);
for(var F,N=q;N<x;N++)for(F=m;F<u;F++)B[J++]=C[N][F]}else for(N=q;N<x;N++)for(F=m;F<u;F++){var fa=C[N][F];var wa=J<<2;B[wa]=fa&255;B[wa+1]=fa>>8&255;B[wa+2]=fa>>16&255;B[wa+3]=255;J++}c.putImageData(H,m,q)}};this.postPaint=function(m,q,u,x){0<d.width?d.union(m,q,u,x):(d.x=m,d.y=q,d.width=u,d.height=x)};this.commitPaint=function(){0<d.width&&(this.repaint(d.x,d.y,d.width,d.height),d.width=0)};this.fillRect=function(m,q,u,x,H){var B=e;u=m+u;x=q+x;for(var J=q;J<x;J++)for(q=m;q<u;q++)B[J][q]=H}}function I(a,
b){ca?ca.resize(a,b):ca=new E(a,b);return ca}function ba(){var a=g.indexOf("://"),b=g.substring(a+3);a=b.indexOf("/");0<a&&(b=b.substring(0,a));return location.protocol+"//"+b}function ka(a){return xa?hi5.browser.httpGet(ba()+"/CLIP?s="+xa+"&t="+(new Date).getTime(),!1):""}function ya(a){return"on"==a||"true"==a||1==a}function Ra(a,b,e){this.need=a;this.handler=b;this.repeat=e||1}function cb(){if(!Q){Sa();if(Ea)w=Ea;else{var a=hi5.tool.replaceQuery(g,"pwd","x");hi5.browser.binaryWS()&&(a+="&binary=on");
var b=window.opener;if(b){var e=null;try{e=b.__sparkUser}catch(c){}e&&(b=e.account,e=e.session,b&&(a+="&account="+b),e&&(a+="&session="+e))}a=h.modifyURL(a+("&pasteCap="+(hi5.browser.isChrome&&hi5.browser.isDesktop?3:0)));(e=hi5.browser.cookie.get("__SV_TOKEN_A"))&&(a+="&__SV_TOKEN_A="+encodeURIComponent(e));w=new WebSocket(a,"telnet");w.binaryType="arraybuffer"}W.ws=w;svGlobal.logger.info(g);w.onopen=db;void 0!=r.recording&&"on"==r.recording&&eb(r);w.onmessage=function(c){c=c.data;if("string"!=typeof c){var d=
new Uint8Array(c);null!=da&&da.add(new RecordingObj(d,0,c.byteLength));qa.set(d,0,c.byteLength);qa.handle()}else{var A=parseInt(c.substring(0,2),16);d=c.substring(2);switch(A){case 15:JSON.parse(d);if(h){if(h.onready)h.onready();if(h.onloggedin)h.onloggedin()}break;case 26:c=JSON.parse(d);if(c.name){svGlobal.logger.info("msg="+d);if(h.onerror)h.onerror(c);d=__svi18n.errorCode["S"+c.name]||"";d+=c.message||c.msg;h.showMessage(d)}else 0<svGlobal.log&&console.erro("No error code for message:"+d);break;
case 27:0!=O.drawLicense&&(K.drawLicense(d),Fa(r.fontSize));break;case 56:c=JSON.parse(d);xa=c.session;c.server=h.server;if(d=hi5.$("joinSelect"))d.value=c.joinMode;if(d=hi5.$("requestControl"))d.disabled=c.hasControl;d=fb("jointelnet.html")+"?id="+c.numericId;d=h.modifyURL(d);var f=c.webAddress;f&&0<f.length&&(A=f.indexOf("://"),f=f.substring(A+3),A=f.indexOf("/"),0<A&&(f=f.substring(0,A)),f.toLowerCase()!=location.host.toLowerCase()&&(d+="&gateway="+f));c.joinLink=d;h.sessionInfo.appInfo=c;c.ver&&
c.ver!=svGlobal.version&&svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+c.ver);if(h.onsessionstart)h.onsessionstart(h.sessionInfo);break;case 59:c=hi5.Base64.dec(d,0);Ga=c[3]<<24|c[2]<<16|c[1]<<8|c[0];Ga&64&&h.showMessage(__svi18n.info.recording);K.setFeature(Ga);break;case 61:c=JSON.parse(d);switch(c.type){case 0:r.fontSize=parseInt(c.fontSize);l=c.width;p=c.height;Sa();K.setAutoScale(!0);za(l+M,p+M);c.server&&(h.server=c.server,h.setTitle&&(document.title=r.displayName||h.server));Ta=
c.length;if(h.onopened)h.onopened(c);break;case 1:c=c.duration;if(h.onprogress)h.onprogress(c,Ta);break;case 2:2==c.status?Q=!0:(d=0==c.status,ca.pause(d),c.warn&&h.showMessage(d?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed))}break;case 62:gb(d);break;default:svGlobal.logger.warn("@TODO:"+c+"\n")}}};w.onclose=Aa;w.onerror=hb;za(l+M,p+M)}}function eb(a){da=new RecordingManager;da.setHeader({name:"rec",width:a.width,height:a.height,color:a.fontSize,namesuffix:".telnetv",filetag:"TELV",duration:0})}
function ib(a,b){var e=0,c=!1;this.width=a;this.interval=b;var d=0;this.start=function(){c||(c=!0,e=setInterval(function(){if(K&&Q){var A=K.getThumbnail(a);A&&A.length!=d&&(w.send("8E7"+A),d=A.length)}},b))};this.stop=function(){clearInterval(e)}}function jb(a,b){!Z||Z.width==a&&Z.interval==b||(Z.stop(),Z=null);Z||(Z=new ib(a,b));Z.start()}function gb(a){var b=parseInt(a.substring(0,1),16),e=a.substring(1);a=!1;var c=h.sessionInfo.appInfo;switch(b){case 1:var d=JSON.parse(e);h.onsessionjoin&&(a=h.onsessionjoin(d));
if(a)break;h.showMessage(__svi18n.info.joinsession.applyArgs([d.numericId,d.__ip,d.name]));break;case 2:d=JSON.parse(e);h.onsessionexit&&(a=h.onsessionexit(d));if(a)break;h.showMessage(__svi18n.info.exitsession.applyArgs([d.numericId,d.__ip,d.name]));break;case 3:d=JSON.parse(e);c.joinMode!=d.mode&&(c.joinMode=d.mode,b=hi5.$("joinSelect"))&&(b.value=d.mode);if(c.hasControl)break;K.setReadOnly(!1);if(b=hi5.$("requestControl"))b.disabled=!0;h.ongivecontrol&&(a=h.ongivecontrol());if(a)break;h.showMessage(__svi18n.info.givecontrol);
break;case 4:K.setReadOnly(!0);c.hasControl=!1;if(b=hi5.$("requestControl"))b.disabled=!1;h.ontakebackcontrol&&(a=h.ontakebackcontrol());if(a)break;h.showMessage(__svi18n.info.nocontrol);break;case 5:d=JSON.parse(e);h.onrequirecontrol&&(a=h.onrequirecontrol(d));if(a)break;a=__svi18n.info.title.applyArgs([d.name,d.numericId,d.__ip]);h.showMessage({title:a,msg:__svi18n.info.recontrol,cbYes:function(){h.giveControl(d.numericId);this.destroy()},cbNo:function(){h.refuseControl(d.numericId);this.destroy()}});
break;case 6:K.setTouchRemoting(!0);break;case 7:d=JSON.parse(e);d.cols&&d.rows&&(a=z*d.cols+2*M,b=n*d.rows+2*M,ca=I(a,b),za(a,b));break;case 8:d=JSON.parse(e);if(h.onrequestcredential&&h.onrequestcredential(d))break;K.requestCredential(d);break;case 9:d=JSON.parse(e);0<d.interval&&0<d.width?jb(d.width,d.interval):Z&&(Z.stop(),Z=null);break;case 11:d=JSON.parse(e),h.onrequirejoin&&(a=h.onrequirejoin(d)),a||(a=__svi18n.info.title.applyArgs([d.name,d.numericId,d.__ip]),h.showMessage({title:a,msg:__svi18n.info.reqjoin,
cbYes:function(){h.allowJoin(d.numericId,!0);this.destroy()},cbNo:function(){h.allowJoin(d.numericId,!1);this.destroy()}}))}}function fb(a){var b=O.page&&O.page.join||"";if(b.startsWith("http://")||b.startsWith("https://"))return b;if(b.startsWith("/"))return location.origin+b;var e=location.href,c=e.lastIndexOf("/");if(b)return e.substring(0,c+1)+b;b=ba();e.toLowerCase().startsWith(b.toLowerCase())&&(b=e.substring(0,c));return b+"/"+a}function db(a){svGlobal.logger.info("opened...");Q=!0;w.send("87"+
navigator.userAgent);if(h.onopen)h.onopen()}function hb(a){svGlobal.logger.warn(a)}function Aa(a){svGlobal.logger.warn("closed ...");ha&&(ha.style.display="none");Ha=Q=!1;if(h&&h.onclose)h.onclose();try{null!=da&&(da.exit(),da=null),K&&K.close(),la&&la.visible()&&(la.dismiss(),la=null)}catch(b){}qa&&(qa.release(),qa=null);ia=k=null;w&&(w.onopen=null,w.onmessage=null,w.onclose=null,w=w.onerror=null);h=K=W=null;window&&window.$telnet&&(window.$telnet=null);null!=da&&(da.exit(),da=null)}function Fa(a,
b){b||(b=X);k.font=a+"px "+b;z=k.measureText("X").width;oa=parseInt(p/n);S=parseInt(l/z);Ia(parseInt(p/n))}function Ia(a,b){b&&(ja=b);a&&(ea=a,Ba=(ea-1)*n+D);Ua=1==ja&&ea==Math.floor(p/n)}function za(a,b){var e=a-M,c=b-M,d=Math.floor(c/n),A=Math.floor(e/z),f=null;Q&&(f=k.getImageData(0,0,Math.min(A*z+M,S*z+M),Math.min(d*n+M,oa*n+M)));l=e;p=c;K.setSize(a,b);Fa(r.fontSize);Ja();f&&k.putImageData(f,0,0);oa=d;S=A;Ia(Math.floor(p/n))}function Sa(){ha||(Ja(),v=y,t=D,10>r.fontSize&&(r.fontSize=10),12>=r.fontSize?
(n=r.fontSize+6,va=2):13<=r.fontSize&&18>r.fontSize?(n=r.fontSize+8,va=2):19<=r.fontSize&&25>r.fontSize?(n=r.fontSize+12,va=3):25<=r.fontSize&&(n=r.fontSize+16,va=4),Fa(r.fontSize),ha=document.getElementById("cursorID"),ha.style.display="block",ha.style.width=z+"px",ha.style.height=n+"px",Ha=!0)}function Ja(){k.fillStyle=R;k.fillRect(0,0,ia.width,ia.height);k.fillStyle=T}function Va(a){if(0!=L||Ka[a])""!=aa&&La(aa),kb(a);else if(Ma){var b=U[a]||"";aa=""!=b?aa+b:aa+String.fromCharCode(a)}else aa=127<
a&&256>a?aa+U[a]:aa+String.fromCharCode(a)}function Na(a){for(;;){var b=a.getByte();if(255==b&&(b=a.getByte(),240==b))break}}function ra(a,b,e){w.send("D5"+a+"\t"+b+"\t"+(1==e?1:0));251==a?Oa(b):252==a?Oa(b):253==a?Pa(b):254==a&&Pa(b)}function Oa(a){return 39>=a&&0<=a&&lb[a-0]}function Pa(a){return 39>=a&&0<=a&&mb[a-0]}function kb(a){switch(a){case 0:case 24:return L=0,!1;case 26:return L=0,!1;case 5:return!1;case 7:return!1;case 8:return v-=z,v<y&&(v=y),P(),!1;case 9:var b=(v-y)/z/8;b=parseInt(1*
b)+1;v=8*b*z+y;v>=S*z&&(v=y,t+=n,sa("\n"));P();return!1;case 13:return v=y,t>D+(ea-1)*n&&(t=D+(ea-1)*n),P(),!1;case 10:case 11:case 12:return Wa(),!1;case 15:return!1;case 14:return!1;case 17:case 19:return!1;case 27:return ma="",L=27,!1;default:if(128<=a&&159>=a)return!1}switch(L){case 0:return!0;case 27:if("\\"==a)return!1;if(32<=a&&47>=a)return ma+=String.fromCharCode(a),!1;if(32<=a&&126>=a||160<=a){null==ma&&(ma="");switch(a){case 48:"("==ma&&(Ma=!0);break;case 65:t-=n;P();break;case 66:"("==
ma&&(Ma=!1);break;case "C":v+=z;P();break;case 68:""==ma&&Xa(1);P();break;case 72:v=y;t+=n;break;case 77:""==ma&&Ya(1);break;case "P":L=0;L=144;break;case "Y":L=161;break;case "c":L=0;break;case 91:na="";L=0;L=155;break;case 93:L=0;L=157;break;case "^":L=0,L=158}27==L&&(L=0);return!1}return!0;case 155:if(48<=a&&63>=a||32<=a&&47>=a)return na+=String.fromCharCode(a),!1;if(32<=a&&126>=a||160<=a){b=null;null==na&&(na="");""!=na&&(b=na.split(";"));switch(a){case 65:a=null!=b&&1<=b.length?parseInt(b[0]):
1;t-=a*n;t<D&&(t=D);P();break;case 66:a=null!=b&&1<=b.length?parseInt(b[0]):1;var e=t;t+=a*n;a=(t-e)/n;sa("\n",0==a?1:a);P();break;case 67:b=null!=b&&1<=b.length?parseInt(b[0]):1;v+=b*z;P();break;case 68:b=null!=b&&1<=b.length?parseInt(b[0]):1;v-=b*z;v<y&&(v=y);P();break;case 69:a=null!=b&&1<=b.length?parseInt(b[0]):1;e=t;t+=a*n;a=(t-e)/n;sa("\n",0==a?1:a);v=y;P();break;case 70:a=null!=b&&1<=b.length?parseInt(b[0]):1;t-=a*n;t<D&&(t=D);v=y;P();break;case 72:case 102:null!=b?(1<=b.length&&(a=parseInt(b[0]),
e=t,t=D+(a-1)*n,a=(t-e)/n,sa("\n",0==a?1:a)),2<=b.length&&(b=parseInt(b[1])-1,v=y+b*z)):""==na&&(v=y,t=D);break;case 73:b=1<=b.length?parseInt(b[0]):1;v=y+8*b*z;break;case 74:null!=b&&1<=b.length?(b=parseInt(b[0]),1==b?(k.fillStyle=R,k.fillRect(y,D,S*z,t-chart_height-D),k.fillRect(y,t,t-y,chart_height),k.fillStyle=T):2==b&&(Ja(),v=y,t=D)):(k.fillStyle=R,k.fillRect(v,t,S*z-v+y,oa*n-t+D),k.fillStyle=T);break;case 75:null!=b&&1<=b.length?(b=parseInt(b[0]),1==b?Qa(y,v):2==b&&Qa(y,l+M),P()):Qa(v,l+M);
break;case 76:null!=b&&1<=b.length&&(a=parseInt(b[0]),Ya(a),P());break;case 77:null!=b&&1<=b.length&&(a=parseInt(b[0]),Xa(a),P());break;case 80:b=null!=b&&1<=b.length?parseInt(b[0]):1;b=k.getImageData(v+b*z,t,l+M-v-b*z,n);k.fillStyle=R;k.fillRect(v,t,l+M-v,n);k.putImageData(b,v,t);k.fillStyle=T;P();break;case 88:b=null!=b&&1<=b.length?parseInt(b[0]):1;k.fillStyle=R;k.fillRect(v,t,b*z,n);k.fillStyle=T;break;case 109:if(null==b||0==b.length)k.font="normal "+r.fontSize+"px "+X,T=r.fgColor||V[7],R=r.bgColor||
V[0];else{a=b.length;for(var c=0;c<a;c++)switch(e=1*b[c],e){case 0:k.font="normal "+r.fontSize+"px "+X;R=V[0];T=V[7];break;case 1:k.font="bold "+r.fontSize+"px "+X;break;case 4:break;case 5:k.font="italic "+r.fontSize+"px "+X;break;case 7:k.font="normal "+r.fontSize+"px "+X;R=V[7];T=V[0];break;case 22:k.font="normal "+r.fontSize+"px "+X;R=V[0];T=V[7];break;case 24:break;case 25:k.font="italic "+r.fontSize+"px "+X;break;case 27:k.font="normal "+r.fontSize+"px "+X;R=V[7];T=V[0];break;default:30<=b[c]&&
39>=b[c]?T=V[b[c]-30+1]:40<=b[c]&&49>=b[c]&&(R=V[b[c]-40+1])}}break;case 114:null!=b&&2<=b.length&&(a=parseInt(b[0]),b=parseInt(b[1]),Ia(b,a))}L=0;return!1}return!0;case 144:case 157:case 158:case 159:return 48<=a&&63>=a||32<=a&&47>=a?!1:32<=a&&126>=a||160<=a?(L=160,!1):!0;case 160:return 32<=a&&126>=a||160<=a?!1:!0;case 161:return L=162,!1;case 162:return L=0,!1;default:return L=0,!1}}function Qa(a,b){k.fillStyle=R;k.fillRect(a,t,b-a,n);k.fillStyle=T}function Ya(a){var b=k.getImageData(y,D+(ja-1)*
n,S*z,(ea-ja-a+1)*n);k.fillStyle=R;k.fillRect(y,D+(ja-1)*n,S*z,n*a);k.putImageData(b,y,D+(ja+a-1)*n);k.fillStyle=T}function Xa(a){var b=k.getImageData(y,(ja+a-1)*n+D,S*z,(ea-ja-a+1)*n);k.fillStyle=R;k.fillRect(y,(ea-a)*n+D,S*z,a*n);k.putImageData(b,y,(ja-1)*n+D);k.fillStyle=T}function Wa(){t+=n;sa("\n");P();Za()}function Za(){v>=S*z&&(v=y,t+=n);if(t>Ba){for(;t>Ba;)t-=n;P();if(Ua){var a=ia.height-(D+n);k.drawImage(ia,0,D+n,ia.width,a,0,D,ia.width,a);k.fillStyle=R;k.fillRect(0,Ba,ia.width,n)}else a=
k.getImageData(y,D+n,S*z,(ea-1)*n),k.fillStyle=R,k.fillRect(y,D,S*z,ea*n),k.putImageData(a,y,D);k.fillStyle=T}}function La(a){var b=a.length,e=((v-y)/z|0)+b-S;0<e?(b-=e,$a(a.substring(0,b),b),Za(),La(a.substring(b))):($a(a,b),"--More--"==a.trim()&&Wa())}function $a(a,b){t+n>p&&(t=(oa-1)*n+D);k.fillStyle=R;k.fillRect(v,t,z*b,n);k.fillStyle=T;k.fillText(a,v,t+n-3*va);v+=k.measureText(a).width;sa(a);P();aa=""}function P(){ha.style.top=t+"px";ha.style.left=v+"px"}function nb(a){if(Q)return(a=a.getData("text/plain"))?
(a=a.replace(/\r\n/g,"\n"),ta(a),!0):!1}function ob(){la&&ua&&!la.visible()&&(ua.value=pa,la.show(),K&&K.setIgnorePaste(!1),setTimeout(function(){ua.scrollTop=ua.scrollHeight;ua.disabled=!1},10))}function sa(a,b){if(la){if(b)for(var e=0;e<b;e++)pa+=a;else pa+=a;1E5<pa.length&&(pa=pa.substring(4E4))}}function ta(a){if(a){var b=a.length+1,e=new Uint8Array(b);e[0]=147;for(var c=1;c<b;c++)e[c]=a.charCodeAt(c-1);w.send(e.buffer)}}sessionStorage&&sessionStorage.clear();var ua=document.getElementById("copytextarea"),
la=ua?new hi5.Lightbox(document.getElementById("copydialog")):null,pa="";this.displayMsg=!0;this.reconnectTimes=0;this.setTitle=this.openLink=!0;this.mode=0;var Ea="object"==typeof g?g:null,ab="object"==typeof g||0<g.indexOf("/PLAY?");ab?(this.mode=1,Ea&&(g=""),g+="&touchpad=on"):0<g.indexOf("/JOIN?")&&(this.mode=2,this.reconnectOnResize=!1);hi5.appcfg||(hi5.appcfg={img:{},toolbar:{fadable:!0},displayMsg:!0});var O=hi5.appcfg;this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:!0,trueColor:!0};
var xa="",K=null,Q=!1,Ha=!1,Ga=0,M=5,da=null;window.$telnet=this;O.copyDialog=!0;for(var U=[],Y=0;127>Y;Y++)U[Y]=String.fromCharCode(Y);U[106]="+";U[107]="+";U[108]="+";U[109]="+";U[110]="+";U[113]="_";U[116]="+";U[117]="+";U[118]="+";U[119]="+";U[120]="|";(function(){for(var a={128:199,129:252,130:233,131:226,132:228,133:224,134:229,135:231,136:234,137:235,138:232,139:239,140:238,141:236,142:196,143:197,144:201,145:230,146:198,147:244,148:246,149:242,150:251,151:249,152:255,153:214,154:220,155:162,
156:163,157:165,158:8359,159:402,160:225,161:237,162:243,163:250,164:241,165:209,166:170,167:186,168:191,169:8976,170:172,171:189,172:188,173:161,174:171,175:187,176:9617,177:9618,178:9619,179:9474,180:9508,181:9569,182:9570,183:9558,184:9557,185:9571,186:9553,187:9559,188:9565,189:9564,190:9563,191:9488,192:9492,193:9524,194:9516,195:9500,196:9472,197:9532,198:9566,199:9567,200:9562,201:9556,202:9577,203:9574,204:9568,205:9552,206:9580,207:9575,208:9576,209:9572,210:9573,211:9561,212:9560,213:9554,
214:9555,215:9579,216:9578,217:9496,218:9484,219:9608,220:9604,221:9612,222:9616,223:9600,224:945,225:223,226:915,227:960,228:931,229:963,230:181,231:964,232:934,233:920,234:937,235:948,236:8734,237:966,238:949,239:8745,240:8801,241:177,242:8805,243:8804,244:8992,245:8993,246:247,247:8776,248:176,249:8729,250:183,251:8730,252:8319,253:178,254:9632,255:160},b=128;256>b;b++)U[b]=String.fromCharCode(a[b])})();var mb=[!0,!0,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,
!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1],lb=[!0,!1,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!0,!1,!1,!1,!1,!1,!1,!0,!0,!1,!1,!1,!1,!1,!1,!1,!1],Ka=Array(256),Ca=[0,5,7,8,9,10,11,12,13,14,15,17,19,24,26,27,127,132,133,136,141,142,143,144,146,155,156,157,158,159];for(Y=0;256>Y;Y++)Ka[Y]=!1;for(Y=0;Y<Ca.length;Y++)Ka[Ca[Y]]=!0;var qa=new function(a){var b=0,e=0,c=new Uint8Array(a),d=this,A=new Ra(0,null,0);this.release=function(){d=c=A=null};this.getHandler=function(){return A};
this.getData=function(){return c};this.getPosition=function(){return b};this.setPosition=function(f){b=f};this.getEnd=function(){return e};this.set=function(f,G,m){c=f;b=G;e=m};this.handle=function(){A.handler(d,A)};this.setHandler=function(f){f&&1>f.need&&svGlobal.logger.warn("need < 1");(A=f)&&e-b>=f.need&&f.handler(d,f)};this.getByte=function(){return c[b++]};this.peekByte=function(){return c[b]};this.getBE32=function(){return c[b++]<<24|c[b++]<<16|c[b++]<<8|c[b++]};this.getBE16=function(){return c[b++]<<
8|c[b++]};this.skip=function(f){b+=f};this.skipBack=function(f){b-=f};this.getBytes=function(f,G){if(G)for(var m=0;m<f;m++)G[m]=c[b++];else return G=b,b+=f,c.subarray(G,b)};this.copyToByteArray=function(f,G,m,q){hi5.Arrays.arraycopy(c,m,f,G,q)}}(4194304);this.setLinks=function(a){};this.running=function(){return Q};this.getHistory=function(){return pa};this.mapCmdToCtrl=!0;var h=this,w=null,r=hi5.tool.queryToObj(g.substring(g.indexOf("?")+1));l||(l=window.innerWidth);l-=M;r.width=l;g+="&width="+l;
p||(p=window.innerHeight);p-=M;r.height=p;g+="&height="+p;r.fontSize?r.fontSize=parseInt(r.fontSize,10):(r.fontSize=13,g+="&fontSize=13");this.server=r.server;this.port=r.port?parseInt(r.port,10):23;this.loadbalanceToken=O.loadbalanceTokenName?O.loadbalanceTokenName+"="+hi5.tool.uuid():"";this.modifyURL=function(a){h.loadbalanceToken&&(a+="&"+h.loadbalanceToken);return a};var V="black red green yellow blue magenta cyan white gray violet".split(" "),ca=I(l,p),k=ca.getContext(),ia,W=new function(){this.ws=
null;this.setJoinMode=h.setJoinMode;this.requestControl=h.requestControl;this.writeKeyComb=h.writeKeyComb;this.localLockFlags=0;this.checkLockFlags=!0;this.getAppMode=function(){return h.mode};this.send=function(b){"891"!=b&&Q&&this.ws.send(b)};this.sendInput=function(b){h.writeRawInput(b);if(h.onactivity)h.onactivity(b)};var a=null;this.getAppInfo=function(){return h.sessionInfo.appInfo};this.onresize=function(b){if(b=b.target.svSurface){b=b.getFreeSpace();var e=b.width,c=b.height;hi5.browser.isTouch||
hi5.browser.isOpera||!Q||(a&&(clearTimeout(a),a=null),a=setTimeout(function(){za(e,c);w.send("D9"+S+"\t"+oa)},200))}};this.onorientationchange=function(b){};this.getClipData=ka;this.onfocus=function(b){};this.fileCallback=[];this.getShareFiles=function(b,e){loggedin&&(this.ws.send("3A5"+b),this.fileCallback.push(e))};this.notifyFiles=function(b){for(var e=this.fileCallback,c=0,d=e.length;c<d;c++)e[c](b)};this.getFile=function(b){window.open(h.getFileUrl(b))};this.removeFile=function(b){uploadMgr&&
uploadMgr.fileService.remove(b)};this.getFileLink=function(b){return ba()+"/DOWNLOAD?s="+xa+"&f="+b};this.getGateway=function(){return g};this.reconnect=function(b,e,c){};this.sendKeyboardSyncFlags=function(b){return Q?(this.remoteLockFlags=this.localLockFlags=b,!0):!1}};void 0!=O.displayMsg?this.displayMsg=O.displayMsg:O.displayMsg=this.displayMsg;void 0!=O.reconnectTimes&&(this.reconnectTimes=O.reconnectTimes);void 0!=O.openLink&&(this.openLink=O.openLink);void 0!=O.setTitle&&(this.setTitle=O.setTitle);
"boolean"==typeof O.useWSS&&(g=(O.useWSS?"wss":"ws")+g.substring(g.indexOf("://")));this.getURL=function(){return g};this.setJoinMode=function(a){Q&&w.send("8E1"+a)};this.refuseControl=function(a){Q&&w.send("8E3"+a)};this.giveControl=function(a){Q&&w.send("8E4"+a)};this.requestControl=function(){Q&&w.send("8E2")};this.play=function(){w.send("F3")};this.pause=function(){w.send("F2")};this.scan=function(a){w.send("F4"+(a?"1":"0"))};this.seek=function(a){K&&Q&&(w.send("F4"+(a?"1":"0")+"\t"+(a/K.getScale().x|
0)),ca.pause(!0))};this.allowJoin=function(a,b){w.send("8EA"+a+"\t"+(b?1:0))};var Z=null,Ta=0;this.run=function(){cb()};this.hide=function(){K&&("block"==document.getElementById("cursorID").style.display&&(document.getElementById("cursorID").style.display="none"),K.hide())};this.showMessage=function(a,b){h.displayMsg&&a&&(K?K.showMessage(a,b):("string"==typeof a&&(a={msg:a,timeout:b||0}),hi5.notifications.notify(a)))};this.close=function(){if(w&&Q)try{w.send("85"),w.close()}catch(a){}else Aa()};hi5.browser.isChromeApp?
chrome.runtime.onSuspend.addListener(Aa):window.addEventListener("unload",Aa,!1);var bb=!1,ha=null,y=M=5,D=5,v=0,t=0,X=r.fontFamily||r.fontName||"Courier New";0<X.indexOf(" ")&&(X='"'+X+'"');var T=r.fgColor||V[7],R=r.bgColor||V[0],L=0,na="",ma="",z=0,n=18,va=0,aa="",Ma=!1,oa=0,S=0,ja=1,ea=24,Ba=0,Ua=!0;Ca=new Ra(1024,function(a){for(var b=!0,e;b;){e=a.getByte();if(0>e)break;if(255==e)a:{var c=a,d=c.getByte();switch(d){case 255:Va(d);break;case 254:case 253:case 252:case 251:e=c.getByte();c=d;253!=
c||Oa(e)?251!=c||Pa(e)?254==c?ra(252,e,!1):252==c?ra(254,e,!1):253==c?(ra(251,e,!1),31==e?w.send("D9"+S+"\t"+oa):12==e&&w.send("D7")):251==c&&ra(253,e,!1):ra(254,e,!0):ra(252,e,!0);break;case 250:e=c.getByte();switch(e){case 24:e=c.getByte();Na(c);if(1!=e)break;w.send("DA");break;case 32:e=c.getByte();Na(c);if(1!=e)break;w.send("DC");break;default:Na(c)}break;default:break a}bb||(bb=!0,w.send("D0"))}else Va(e);a.getPosition()>=a.getEnd()&&(""!=aa&&La(aa),b=!1)}});qa.setHandler(Ca);this.addSurface=
function(a){K=a;ab&&a.setPlayerMode();ca.setContext(K.context);k=ca.getContext();ia=k.canvas;a.setAutoScale(0<h.mode);a.setSize(l+M,p+M);a.setController(W);a.setFastCopy(ya(r.fastCopy));a.setTouchpad(ya(r.touchpad));a.setClipboard(ya(r.mapClipboard));var b=void 0!=r.cmdToCtrl?ya(r.cmdToCtrl):void 0!=O.cmdToCtrl?O.cmdToCtrl:h.mapCmdToCtrl;a.run(99997,!1,!0,b);a.onclipdata=nb};this.writeText=ta;this.writeScancode=function(a,b){ta(Da.process(a,b,0))};var pb={" ":57,space:57,pageup:201,pagedown:209,end:207,
home:199,left:203,up:200,right:205,down:208,printscreen:183,insert:210,del:211,"delete":211,altgr:184,windows:219,windowsright:220,context:221,esc:1,backspace:14,tab:15,enter:28,meta:29,command:29,ctrl:29,shift:42,alt:56,capslock:58,f1:59,f2:60,f3:61,f4:62,f5:63,f6:64,f7:65,f8:66,f9:67,f10:68,f11:87,f12:88,numlock:69,scrolllock:70,add:78};this.writeKeyComb=function(a){a=a.split("+");var b=a.length;if(0!=b)for(var e=null,c=0;c<b;c++){var d=a[c];""==d&&""==e&&(d="Add");if(""!=d){e=d;var A=pb[e.toLowerCase()];
A?h.writeScancode(!0,A):console.log("Invalid key:"+e)}e=d}};this.writeRawInput=function(a){if(Ha){var b=parseInt(a.substring(0,2),16);a=a.substring(2).split("\t");switch(b){case 128:2==a[2]&&ob();return;case 129:return;case 130:return;case 131:return;case 132:b=parseInt(a[1]);a=0==a[0];ta(Da.process(a,b,0));return;case 139:b=parseInt(a[1]);a=0==a[0];ta(Da.process(a,b,1));return;case 134:ta(Da.process(!0,a[0],3));return}svGlobal.logger.warn("Unknowncode: "+a[1]+" type:"+b)}};var Da=new function(a,
b,e){var c=!1,d=!1,A=!1;this.process=function(f,G,m){if(3==m)return G;if(0==m){switch(G){case 29:case 157:return c=f,"";case 56:case 184:return d=f,"";case 42:case 54:return A=f,""}if(f){switch(G){case 28:f="\r\n";break;case 200:f="\u001b[A";break;case 208:f="\u001b[B";break;case 205:f="\u001b[C";break;case 203:f="\u001b[D";break;case 59:f="\u001bOP";break;case 60:f="\u001bOQ";break;case 61:f="\u001bOR";break;case 62:f="\u001bOS";break;case 63:f="\u001b[15~";break;case 64:f="\u001b[17~";break;case 65:f=
"\u001b[18~";break;case 66:f="\u001b[19~";break;case 67:f="\u001b[20~";break;case 68:f="\u001b[21~";break;case 87:f="\u001b[23~";break;case 88:f="\u001b[24~";break;case 15:f="\t";break;case 209:f="\u001b[6~";break;case 201:f="\u001b[5~";break;case 199:f="\u001b[H";break;case 207:f="\u001b[F";break;case 14:f=A?"\b":"\u007f";break;case 211:f="\u001b[3~";break;case 197:f="\u00ff\u00f3";break;case 210:f="\u001b[2~";break;case 1:f="\u001b";break;case 55:f="*";break;case 71:f=W.localLockFlags&2?"7":"\u001b[H";
break;case 72:f=W.localLockFlags&2?"8":"\u001b[A";break;case 73:f=W.localLockFlags&2?"9":"\u001b[5~";break;case 74:f="-";break;case 75:f=W.localLockFlags&2?"4":"\u001b[D";break;case 76:f="5";break;case 77:f=W.localLockFlags&2?"6":"\u001b[C";break;case 78:f="+";break;case 79:f=W.localLockFlags&2?"1":"\u001b[F";break;case 80:f=W.localLockFlags&2?"2":"\u001b[B";break;case 81:f=W.localLockFlags&2?"3":"\u001b[6~";break;case 82:f=W.localLockFlags&2?"0":"\u001b[2~";break;case 83:f=W.localLockFlags&2?".":
"\u001b[3~";break;case 156:f="\r\n";break;case 181:f="/";break;default:return console.log("Invalid code:"+G),""}d&&(f="\u001b"+f);return f}return""}if(1==m&&c){if(64<G&&91>G)return String.fromCharCode(G-64);switch(G){case 54:return"\u001e";case 219:return"\u001b";case 220:return"\u001c";case 221:return"\u001d";case 32:return"\x00";case 192:return"\u001e";case 191:return"\u001f";default:return console.log("Invalid key code:"+G),""}}if(d)return"\u001b"+String.fromCharCode(G).toLowerCase()}}};
