var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(e,p,t){if(null==e)throw new TypeError("The 'this' value for String.prototype."+t+" must not be null or undefined");if(p instanceof RegExp)throw new TypeError("First argument to String.prototype."+t+" must not be a regular expression");return e+""};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(e,p,t){e!=Array.prototype&&e!=Object.prototype&&(e[p]=t.value)};
$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(e,p,t,Q){if(p){t=$jscomp.global;e=e.split(".");for(Q=0;Q<e.length-1;Q++){var U=e[Q];U in t||(t[U]={});t=t[U]}e=e[e.length-1];Q=t[e];p=p(Q);p!=Q&&null!=p&&$jscomp.defineProperty(t,e,{configurable:!0,writable:!0,value:p})}};
$jscomp.polyfill("String.prototype.startsWith",function(e){return e?e:function(e,t){var p=$jscomp.checkStringArgs(this,e,"startsWith");e+="";for(var U=p.length,ba=e.length,ia=Math.max(0,Math.min(t|0,p.length)),V=0;V<ba&&ia<U;)if(p[ia++]!=e[V++])return!1;return V>=ba}},"es6-impl","es3");var svManager={getInstance:function(){var e=window.$telnet;return e&&e.running&&e.running()?e:null}};
function connvertServer(e){var p={};p.id=e.id;p.server=e.id;p.displayName=e.displayName||e.id;if(e=e.vnc)for(var t in e)p[t]=e[t];return p}
svGlobal.TELNET=function(e,p,t){function Q(a,b){var c=[],f=null,d=new hi5.graphic.Rectangle(0,0,0,0),h="Uint8ClampedArray"in window;this.width=a;this.height=b;var m=!1,e=this;this.pause=function(a){m=a};this.release=function(){c=f=e=null};this.isPaused=function(){return m};this.setContext=function(a){a!=f&&(f||!a||a.createImageData(1,1).data.buffer||(h=!1),f=a)};this.getContext=function(){return f};this.resize=function(f,d){for(var m=0;m<d;m++)c[m]=new Uint32Array(f);e.width=a=f;e.height=b=d};e.resize(a,
b);this.getBuffer=function(){return c};this.setRGB=function(a,b,f){c[b][a]=f|4278190080};this.getRGB=function(a,b){return c[b][a]};this.setRGBs=function(a,b,f,d,m,h,e){f=a+f;d=b+d;for(var g=c,k,l=b;l<d;l++,h+=e){var n=h;k=g[l];for(b=a;b<f;b++)k[b]=m[n++]}};this.moveArea=function(a,b,f,d,m,h){if(0<h){m=a+m;h=b+h;var e=c,g;for(g=d-1;0<=g;g--){var k=e[h+g];var l=e[b+g];for(d=0;d<f;d++)k[m+d]=l[a+d]}}else if(0>h){m=a+m;h=b+h;var e=c;for(k=0;k<d;k++){l=e[h+k];var n=e[b+k];for(g=0;g<f;g++)l[m+g]=n[a+g]}}else if(0<
m)for(m=a+m,h=b+h,e=c,--f;0<=f;f--)for(k=m+f,l=a+f,g=0;g<d;g++)e[h+g][k]=e[b+g][l];else for(m=a+m,h=b+h,e=c,g=0;g<f;g++)for(l=m+g,n=a+g,k=0;k<d;k++)e[h+k][l]=e[b+k][n]};this.getRGBs=function(a,b,f,d){var m=_Uint32Array(f*d);m[0]=0;var h=c;f=a+f;d=b+d;for(var e=0,g=b;g<d;g++)for(b=a;b<f;b++)m[e++]=h[g][b];return m};this.repaint=function(d,m,g,e){if(f){0>d&&(g+=d,d=0);0>m&&(e+=m,m=0);d+g>a&&(g=a-d);m+e>b&&(e=b-m);var k=f.createImageData(g,e),l=k.data;g=d+g;e=m+e;var n=0,r=c;if(h)for(var l=new Uint32Array(l.buffer),
p,q=m;q<e;q++)for(p=d;p<g;p++)l[n++]=r[q][p];else for(var t,u,q=m;q<e;q++)for(p=d;p<g;p++)t=r[q][p],u=n<<2,l[u]=t&255,l[u+1]=t>>8&255,l[u+2]=t>>16&255,l[u+3]=255,n++;f.putImageData(k,d,m)}};this.postPaint=function(a,b,f,m){0<d.width?d.union(a,b,f,m):(d.x=a,d.y=b,d.width=f,d.height=m)};this.commitPaint=function(){0<d.width&&(this.repaint(d.x,d.y,d.width,d.height),d.width=0)};this.fillRect=function(a,b,f,d,m){var g=c;f=a+f;d=b+d;for(var e=b;e<d;e++)for(b=a;b<f;b++)g[e][b]=m}}function U(a,b){N?N.resize(a,
b):N=new Q(a,b);return N}function ba(){var a=e.indexOf("://"),b=e.substring(a+3),a=b.indexOf("/");0<a&&(b=b.substring(0,a));return location.protocol+"//"+b}function ia(a){return ja?hi5.browser.httpGet(ba()+"/CLIP?s="+ja+"&t="+(new Date).getTime(),!1):""}function V(a){return"on"==a||"true"==a||1==a}function Ca(a,b,c){this.need=a;this.handler=b;this.repeat=c||1}function Oa(){if(!C){Da();if(pa)q=pa;else{var a=hi5.tool.replaceQuery(e,"pwd","x");hi5.browser.binaryWS()&&(a+="&binary=on");var b=window.opener;
if(b){var c=null;try{c=b.__sparkUser}catch(f){}c&&(b=c.account,c=c.session,b&&(a+="&account="+b),c&&(a+="&session="+c))}a=h.modifyURL(a+("&pasteCap="+(hi5.browser.isChrome&&hi5.browser.isDesktop?3:0)));(c=hi5.browser.cookie.get("__SV_TOKEN_A"))&&(a+="&__SV_TOKEN_A="+encodeURIComponent(c));q=new WebSocket(a,"telnet");q.binaryType="arraybuffer"}I.ws=q;svGlobal.logger.info(e);q.onopen=Pa;void 0!=l.recording&&"on"==l.recording&&Qa(l);q.onmessage=function(a){a=a.data;if("string"!=typeof a){var b=new Uint8Array(a);
null!=O&&O.add(new RecordingObj(b,0,a.byteLength));ca.set(b,0,a.byteLength);ca.handle()}else{var c=parseInt(a.substring(0,2),16),b=a.substring(2);switch(c){case 15:JSON.parse(b);if(h){if(h.onready)h.onready();if(h.onloggedin)h.onloggedin()}break;case 26:a=JSON.parse(b);if(a.name){svGlobal.logger.info("msg="+b);if(h.onerror)h.onerror(a);b=__svi18n.errorCode["S"+a.name]||"";b+=a.message||a.msg;h.showMessage(b)}else 0<svGlobal.log&&console.erro("No error code for message:"+b);break;case 27:0!=A.drawLicense&&
(x.drawLicense(b),qa(l.fontSize));break;case 56:a=JSON.parse(b);ja=a.session;a.server=h.server;if(b=hi5.$("joinSelect"))b.value=a.joinMode;if(b=hi5.$("requestControl"))b.disabled=a.hasControl;var b=Ra("jointelnet.html")+"?id="+a.numericId,b=h.modifyURL(b),m=a.webAddress;m&&0<m.length&&(c=m.indexOf("://"),m=m.substring(c+3),c=m.indexOf("/"),0<c&&(m=m.substring(0,c)),m.toLowerCase()!=location.host.toLowerCase()&&(b+="&gateway="+m));a.joinLink=b;h.sessionInfo.appInfo=a;a.ver&&a.ver!=svGlobal.version&&
svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+a.ver);if(h.onsessionstart)h.onsessionstart(h.sessionInfo);break;case 59:a=hi5.Base64.dec(b,0);ra=a[3]<<24|a[2]<<16|a[1]<<8|a[0];ra&64&&h.showMessage(__svi18n.info.recording);x.setFeature(ra);break;case 61:a=JSON.parse(b);switch(a.type){case 0:l.fontSize=parseInt(a.fontSize);p=a.width;t=a.height;Da();x.setAutoScale(!0);ka(p+z,t+z);a.server&&(h.server=a.server,h.setTitle&&(document.title=l.displayName||h.server));Ea=a.length;if(h.onopened)h.onopened(a);
break;case 1:a=a.duration;if(h.onprogress)h.onprogress(a,Ea);break;case 2:2==a.status?C=!0:(b=0==a.status,N.pause(b),a.warn&&h.showMessage(b?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed))}break;case 62:Sa(b);break;default:svGlobal.logger.warn("@TODO:"+a+"\n")}}};q.onclose=la;q.onerror=Ta;ka(p+z,t+z)}}function Qa(a){O=new RecordingManager;O.setHeader({name:"rec",width:a.width,height:a.height,color:a.fontSize,namesuffix:".telnetv",filetag:"TELV",duration:0})}function Ua(a,b){var c=0,f=!1;
this.width=a;this.interval=b;var d=0;this.start=function(){f||(f=!0,c=setInterval(function(){if(x&&C){var b=x.getThumbnail(a);b&&b.length!=d&&(q.send("8E7"+b),d=b.length)}},b))};this.stop=function(){clearInterval(c)}}function Va(a,b){!L||L.width==a&&L.interval==b||(L.stop(),L=null);L||(L=new Ua(a,b));L.start()}function Sa(a){var b=parseInt(a.substring(0,1),16),c=a.substring(1);a=!1;var f=h.sessionInfo.appInfo;switch(b){case 1:var d=JSON.parse(c);h.onsessionjoin&&(a=h.onsessionjoin(d));if(a)break;
h.showMessage(__svi18n.info.joinsession.applyArgs([d.numericId,d.__ip,d.name]));break;case 2:d=JSON.parse(c);h.onsessionexit&&(a=h.onsessionexit(d));if(a)break;h.showMessage(__svi18n.info.exitsession.applyArgs([d.numericId,d.__ip,d.name]));break;case 3:d=JSON.parse(c);f.joinMode!=d.mode&&(f.joinMode=d.mode,b=hi5.$("joinSelect"))&&(b.value=d.mode);if(f.hasControl)break;x.setReadOnly(!1);if(b=hi5.$("requestControl"))b.disabled=!0;h.ongivecontrol&&(a=h.ongivecontrol());if(a)break;h.showMessage(__svi18n.info.givecontrol);
break;case 4:x.setReadOnly(!0);f.hasControl=!1;if(b=hi5.$("requestControl"))b.disabled=!1;h.ontakebackcontrol&&(a=h.ontakebackcontrol());if(a)break;h.showMessage(__svi18n.info.nocontrol);break;case 5:d=JSON.parse(c);h.onrequirecontrol&&(a=h.onrequirecontrol(d));if(a)break;a=__svi18n.info.title.applyArgs([d.name,d.numericId,d.__ip]);h.showMessage({title:a,msg:__svi18n.info.recontrol,cbYes:function(){h.giveControl(d.numericId);this.destroy()},cbNo:function(){h.refuseControl(d.numericId);this.destroy()}});
break;case 6:x.setTouchRemoting(!0);break;case 7:d=JSON.parse(c);d.cols&&d.rows&&(a=v*d.cols+2*z,b=k*d.rows+2*z,N=U(a,b),ka(a,b));break;case 8:d=JSON.parse(c);if(h.onrequestcredential&&h.onrequestcredential(d))break;x.requestCredential(d);break;case 9:d=JSON.parse(c);0<d.interval&&0<d.width?Va(d.width,d.interval):L&&(L.stop(),L=null);break;case 11:d=JSON.parse(c),h.onrequirejoin&&(a=h.onrequirejoin(d)),a||(a=__svi18n.info.title.applyArgs([d.name,d.numericId,d.__ip]),h.showMessage({title:a,msg:__svi18n.info.reqjoin,
cbYes:function(){h.allowJoin(d.numericId,!0);this.destroy()},cbNo:function(){h.allowJoin(d.numericId,!1);this.destroy()}}))}}function Ra(a){var b=A.page&&A.page.join||"";if(b.startsWith("http://")||b.startsWith("https://"))return b;if(b.startsWith("/"))return location.origin+b;var c=location.href,f=c.lastIndexOf("/");if(b)return c.substring(0,f+1)+b;b=ba();c.toLowerCase().startsWith(b.toLowerCase())&&(b=c.substring(0,f));return b+"/"+a}function Pa(a){svGlobal.logger.info("opened...");C=!0;q.send("87"+
navigator.userAgent);if(h.onopen)h.onopen()}function Ta(a){svGlobal.logger.warn(a)}function la(a){svGlobal.logger.warn("closed ...");R&&(R.style.display="none");sa=C=!1;if(h&&h.onclose)h.onclose();try{null!=O&&(O.exit(),O=null),x&&x.close(),W&&W.visible()&&(W.dismiss(),W=null)}catch(b){}ca&&(ca.release(),ca=null);S=g=null;q&&(q.onopen=null,q.onmessage=null,q.onclose=null,q=q.onerror=null);h=x=I=null;window&&window.$telnet&&(window.$telnet=null);null!=O&&(O.exit(),O=null)}function qa(a,b){b||(b=J);
g.font=a+"px "+b;v=g.measureText("X").width;Z=parseInt(t/k);E=parseInt(p/v);ta(parseInt(t/k))}function ta(a,b){b&&(T=b);a&&(P=a,ma=(P-1)*k+w);Fa=1==T&&P==Math.floor(t/k)}function ka(a,b){var c=a-z,f=b-z,d=Math.floor(f/k),e=Math.floor(c/v),m=null;C&&(m=g.getImageData(0,0,Math.min(e*v+z,E*v+z),Math.min(d*k+z,Z*k+z)));p=c;t=f;x.setSize(a,b);qa(l.fontSize);ua();m&&g.putImageData(m,0,0);Z=d;E=e;ta(Math.floor(t/k))}function Da(){R||(ua(),r=u,n=w,10>l.fontSize&&(l.fontSize=10),12>=l.fontSize?(k=l.fontSize+
6,ha=2):13<=l.fontSize&&18>l.fontSize?(k=l.fontSize+8,ha=2):19<=l.fontSize&&25>l.fontSize?(k=l.fontSize+12,ha=3):25<=l.fontSize&&(k=l.fontSize+16,ha=4),qa(l.fontSize),R=document.getElementById("cursorID"),R.style.display="block",R.style.width=v+"px",R.style.height=k+"px",sa=!0)}function ua(){g.fillStyle=D;g.fillRect(0,0,S.width,S.height);g.fillStyle=F}function Ga(a){if(0!=y||va[a])""!=M&&wa(M),Wa(a);else if(xa){var b=G[a]||"";M=""!=b?M+b:M+String.fromCharCode(a)}else M=127<a&&256>a?M+G[a]:M+String.fromCharCode(a)}
function ya(a){for(;;){var b=a.getByte();if(255==b&&(b=a.getByte(),240==b))break}}function da(a,b,c){q.send("D5"+a+"\t"+b+"\t"+(1==c?1:0));251==a?za(b):252==a?za(b):253==a?Aa(b):254==a&&Aa(b)}function za(a){return 39>=a&&0<=a&&Xa[a-0]}function Aa(a){return 39>=a&&0<=a&&Ya[a-0]}function Wa(a){switch(a){case 0:case 24:return y=0,!1;case 26:return y=0,!1;case 5:return!1;case 7:return!1;case 8:return r-=v,r<u&&(r=u),B(),!1;case 9:var b=(r-u)/v/8,b=parseInt(1*b)+1;r=8*b*v+u;r>=E*v&&(r=u,n+=k,ea("\n"));
B();return!1;case 13:return r=u,n>w+(P-1)*k&&(n=w+(P-1)*k),B(),!1;case 10:case 11:case 12:return Ha(),!1;case 15:return!1;case 14:return!1;case 17:case 19:return!1;case 27:return X="",y=27,!1;default:if(128<=a&&159>=a)return!1}switch(y){case 0:return!0;case 27:if("\\"==a)return!1;if(32<=a&&47>=a)return X+=String.fromCharCode(a),!1;if(32<=a&&126>=a||160<=a){null==X&&(X="");switch(a){case 48:"("==X&&(xa=!0);break;case 65:n-=k;B();break;case 66:"("==X&&(xa=!1);break;case "C":r+=v;B();break;case 68:""==
X&&Ia(1);B();break;case 72:r=u;n+=k;break;case 77:""==X&&Ja(1);break;case "P":y=0;y=144;break;case "Y":y=161;break;case "c":y=0;break;case 91:Y="";y=0;y=155;break;case 93:y=0;y=157;break;case "^":y=0,y=158}27==y&&(y=0);return!1}return!0;case 155:if(48<=a&&63>=a||32<=a&&47>=a)return Y+=String.fromCharCode(a),!1;if(32<=a&&126>=a||160<=a){b=null;null==Y&&(Y="");""!=Y&&(b=Y.split(";"));switch(a){case 65:var c=null!=b&&1<=b.length?parseInt(b[0]):1;n-=c*k;n<w&&(n=w);B();break;case 66:c=null!=b&&1<=b.length?
parseInt(b[0]):1;a=n;n+=c*k;a=(n-a)/k;ea("\n",0==a?1:a);B();break;case 67:b=null!=b&&1<=b.length?parseInt(b[0]):1;r+=b*v;B();break;case 68:b=null!=b&&1<=b.length?parseInt(b[0]):1;r-=b*v;r<u&&(r=u);B();break;case 69:c=null!=b&&1<=b.length?parseInt(b[0]):1;a=n;n+=c*k;a=(n-a)/k;ea("\n",0==a?1:a);r=u;B();break;case 70:c=null!=b&&1<=b.length?parseInt(b[0]):1;n-=c*k;n<w&&(n=w);r=u;B();break;case 72:case 102:null!=b?(1<=b.length&&(c=parseInt(b[0]),a=n,n=w+(c-1)*k,a=(n-a)/k,ea("\n",0==a?1:a)),2<=b.length&&
(b=parseInt(b[1])-1,r=u+b*v)):""==Y&&(r=u,n=w);break;case 73:b=1<=b.length?parseInt(b[0]):1;r=u+8*b*v;break;case 74:null!=b&&1<=b.length?(b=parseInt(b[0]),1==b?(g.fillStyle=D,g.fillRect(u,w,E*v,n-chart_height-w),g.fillRect(u,n,n-u,chart_height),g.fillStyle=F):2==b&&(ua(),r=u,n=w)):(g.fillStyle=D,g.fillRect(r,n,E*v-r+u,Z*k-n+w),g.fillStyle=F);break;case 75:null!=b&&1<=b.length?(b=parseInt(b[0]),1==b?Ba(u,r):2==b&&Ba(u,p+z),B()):Ba(r,p+z);break;case 76:null!=b&&1<=b.length&&(c=parseInt(b[0]),Ja(c),
B());break;case 77:null!=b&&1<=b.length&&(c=parseInt(b[0]),Ia(c),B());break;case 80:b=null!=b&&1<=b.length?parseInt(b[0]):1;b=g.getImageData(r+b*v,n,p+z-r-b*v,k);g.fillStyle=D;g.fillRect(r,n,p+z-r,k);g.putImageData(b,r,n);g.fillStyle=F;B();break;case 88:b=null!=b&&1<=b.length?parseInt(b[0]):1;g.fillStyle=D;g.fillRect(r,n,b*v,k);g.fillStyle=F;break;case 109:if(null==b||0==b.length)g.font="normal "+l.fontSize+"px "+J,F=l.fgColor||H[7],D=l.bgColor||H[0];else{a=b.length;for(var f=0;f<a;f++)switch(c=1*
b[f],c){case 0:g.font="normal "+l.fontSize+"px "+J;D=H[0];F=H[7];break;case 1:g.font="bold "+l.fontSize+"px "+J;break;case 4:break;case 5:g.font="italic "+l.fontSize+"px "+J;break;case 7:g.font="normal "+l.fontSize+"px "+J;D=H[7];F=H[0];break;case 22:g.font="normal "+l.fontSize+"px "+J;D=H[0];F=H[7];break;case 24:break;case 25:g.font="italic "+l.fontSize+"px "+J;break;case 27:g.font="normal "+l.fontSize+"px "+J;D=H[7];F=H[0];break;default:30<=b[f]&&39>=b[f]?F=H[b[f]-30+1]:40<=b[f]&&49>=b[f]&&(D=H[b[f]-
40+1])}}break;case 114:null!=b&&2<=b.length&&(a=parseInt(b[0]),b=parseInt(b[1]),ta(b,a))}y=0;return!1}return!0;case 144:case 157:case 158:case 159:return 48<=a&&63>=a||32<=a&&47>=a?!1:32<=a&&126>=a||160<=a?(y=160,!1):!0;case 160:return 32<=a&&126>=a||160<=a?!1:!0;case 161:return y=162,!1;case 162:return y=0,!1;default:return y=0,!1}}function Ba(a,b){g.fillStyle=D;g.fillRect(a,n,b-a,k);g.fillStyle=F}function Ja(a){var b=g.getImageData(u,w+(T-1)*k,E*v,(P-T-a+1)*k);g.fillStyle=D;g.fillRect(u,w+(T-1)*
k,E*v,k*a);g.putImageData(b,u,w+(T+a-1)*k);g.fillStyle=F}function Ia(a){var b=g.getImageData(u,(T+a-1)*k+w,E*v,(P-T-a+1)*k);g.fillStyle=D;g.fillRect(u,(P-a)*k+w,E*v,a*k);g.putImageData(b,u,(T-1)*k+w);g.fillStyle=F}function Ha(){n+=k;ea("\n");B();Ka()}function Ka(){r>=E*v&&(r=u,n+=k);if(n>ma){for(;n>ma;)n-=k;B();if(Fa){var a=S.height-(w+k);g.drawImage(S,0,w+k,S.width,a,0,w,S.width,a);g.fillStyle=D;g.fillRect(0,ma,S.width,k)}else a=g.getImageData(u,w+k,E*v,(P-1)*k),g.fillStyle=D,g.fillRect(u,w,E*v,
P*k),g.putImageData(a,u,w);g.fillStyle=F}}function wa(a){var b=a.length,c=((r-u)/v|0)+b-E;0<c?(b-=c,La(a.substring(0,b),b),Ka(),wa(a.substring(b))):(La(a,b),"--More--"==a.trim()&&Ha())}function La(a,b){n+k>t&&(n=(Z-1)*k+w);g.fillStyle=D;g.fillRect(r,n,v*b,k);g.fillStyle=F;g.fillText(a,r,n+k-3*ha);r+=g.measureText(a).width;ea(a);B();M=""}function B(){R.style.top=n+"px";R.style.left=r+"px"}function Za(a){if(C)return(a=a.getData("text/plain"))?(a=a.replace(/\r\n/g,"\n"),fa(a),!0):!1}function $a(){W&&
ga&&!W.visible()&&(ga.value=aa,W.show(),x&&x.setIgnorePaste(!1),setTimeout(function(){ga.scrollTop=ga.scrollHeight;ga.disabled=!1},10))}function ea(a,b){if(W){if(b)for(var c=0;c<b;c++)aa+=a;else aa+=a;1E5<aa.length&&(aa=aa.substring(4E4))}}function fa(a){if(a){var b=a.length+1,c=new Uint8Array(b);c[0]=147;for(var f=1;f<b;f++)c[f]=a.charCodeAt(f-1);q.send(c.buffer)}}sessionStorage&&sessionStorage.clear();var ga=document.getElementById("copytextarea"),W=ga?new hi5.Lightbox(document.getElementById("copydialog")):
null,aa="";this.displayMsg=!0;this.reconnectTimes=0;this.setTitle=this.openLink=!0;this.mode=0;var pa="object"==typeof e?e:null,Ma="object"==typeof e||0<e.indexOf("/PLAY?");Ma?(this.mode=1,pa&&(e=""),e+="&touchpad=on"):0<e.indexOf("/JOIN?")&&(this.mode=2,this.reconnectOnResize=!1);hi5.appcfg||(hi5.appcfg={img:{},toolbar:{fadable:!0},displayMsg:!0});var A=hi5.appcfg;this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:!0,trueColor:!0};var ja="",x=null,C=!1,sa=!1,ra=0,z=5,O=null;window.$telnet=
this;A.copyDialog=!0;for(var G=[],K=0;127>K;K++)G[K]=String.fromCharCode(K);G[106]="+";G[107]="+";G[108]="+";G[109]="+";G[110]="+";G[113]="_";G[116]="+";G[117]="+";G[118]="+";G[119]="+";G[120]="|";(function(){for(var a={128:199,129:252,130:233,131:226,132:228,133:224,134:229,135:231,136:234,137:235,138:232,139:239,140:238,141:236,142:196,143:197,144:201,145:230,146:198,147:244,148:246,149:242,150:251,151:249,152:255,153:214,154:220,155:162,156:163,157:165,158:8359,159:402,160:225,161:237,162:243,
163:250,164:241,165:209,166:170,167:186,168:191,169:8976,170:172,171:189,172:188,173:161,174:171,175:187,176:9617,177:9618,178:9619,179:9474,180:9508,181:9569,182:9570,183:9558,184:9557,185:9571,186:9553,187:9559,188:9565,189:9564,190:9563,191:9488,192:9492,193:9524,194:9516,195:9500,196:9472,197:9532,198:9566,199:9567,200:9562,201:9556,202:9577,203:9574,204:9568,205:9552,206:9580,207:9575,208:9576,209:9572,210:9573,211:9561,212:9560,213:9554,214:9555,215:9579,216:9578,217:9496,218:9484,219:9608,
220:9604,221:9612,222:9616,223:9600,224:945,225:223,226:915,227:960,228:931,229:963,230:181,231:964,232:934,233:920,234:937,235:948,236:8734,237:966,238:949,239:8745,240:8801,241:177,242:8805,243:8804,244:8992,245:8993,246:247,247:8776,248:176,249:8729,250:183,251:8730,252:8319,253:178,254:9632,255:160},b=128;256>b;b++)G[b]=String.fromCharCode(a[b])})();for(var Ya=[!0,!0,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1],Xa=[!0,!1,
!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!0,!1,!1,!1,!1,!1,!1,!0,!0,!1,!1,!1,!1,!1,!1,!1,!1],va=Array(256),na=[0,5,7,8,9,10,11,12,13,14,15,17,19,24,26,27,127,132,133,136,141,142,143,144,146,155,156,157,158,159],K=0;256>K;K++)va[K]=!1;for(K=0;K<na.length;K++)va[na[K]]=!0;var ca=new function(a){var b=0,c=0,f=new Uint8Array(a),d=this,e=new Ca(0,null,0);this.release=function(){d=f=e=null};this.getHandler=function(){return e};this.getData=function(){return f};this.getPosition=
function(){return b};this.setPosition=function(a){b=a};this.getEnd=function(){return c};this.set=function(a,d,e){f=a;b=d;c=e};this.handle=function(){e.handler(d,e)};this.setHandler=function(a){a&&1>a.need&&svGlobal.logger.warn("need < 1");(e=a)&&c-b>=a.need&&a.handler(d,a)};this.getByte=function(){return f[b++]};this.peekByte=function(){return f[b]};this.getBE32=function(){return f[b++]<<24|f[b++]<<16|f[b++]<<8|f[b++]};this.getBE16=function(){return f[b++]<<8|f[b++]};this.skip=function(a){b+=a};this.skipBack=
function(a){b-=a};this.getBytes=function(a,c){if(c)for(var d=0;d<a;d++)c[d]=f[b++];else return d=b,b+=a,f.subarray(d,b)};this.copyToByteArray=function(a,b,c,d){hi5.Arrays.arraycopy(f,c,a,b,d)}}(4194304);this.setLinks=function(a){};this.running=function(){return C};this.getHistory=function(){return aa};this.mapCmdToCtrl=!0;var h=this,q=null,l=hi5.tool.queryToObj(e.substring(e.indexOf("?")+1));p||(p=window.innerWidth);p-=z;l.width=p;e+="&width="+p;t||(t=window.innerHeight);t-=z;l.height=t;e+="&height="+
t;l.fontSize?l.fontSize=parseInt(l.fontSize,10):(l.fontSize=13,e+="&fontSize=13");this.server=l.server;this.port=l.port?parseInt(l.port,10):23;this.loadbalanceToken=A.loadbalanceTokenName?A.loadbalanceTokenName+"="+hi5.tool.uuid():"";this.modifyURL=function(a){h.loadbalanceToken&&(a+="&"+h.loadbalanceToken);return a};var H="black red green yellow blue magenta cyan white gray violet".split(" "),N=U(p,t),g=N.getContext(),S,I=new function(){this.ws=null;this.setJoinMode=h.setJoinMode;this.requestControl=
h.requestControl;this.writeKeyComb=h.writeKeyComb;this.localLockFlags=0;this.checkLockFlags=!0;this.getAppMode=function(){return h.mode};this.send=function(a){"891"!=a&&C&&this.ws.send(a)};this.sendInput=function(a){h.writeRawInput(a);if(h.onactivity)h.onactivity(a)};var a=null;this.getAppInfo=function(){return h.sessionInfo.appInfo};this.onresize=function(b){if(b=b.target.svSurface){b=b.getFreeSpace();var c=b.width,f=b.height;hi5.browser.isTouch||hi5.browser.isOpera||!C||(a&&(clearTimeout(a),a=null),
a=setTimeout(function(){ka(c,f);q.send("D9"+E+"\t"+Z)},200))}};this.onorientationchange=function(a){};this.getClipData=ia;this.onfocus=function(a){};this.fileCallback=[];this.getShareFiles=function(a,c){loggedin&&(this.ws.send("3A5"+a),this.fileCallback.push(c))};this.notifyFiles=function(a){for(var b=this.fileCallback,f=0,d=b.length;f<d;f++)b[f](a)};this.getFile=function(a){window.open(h.getFileUrl(a))};this.removeFile=function(a){uploadMgr&&uploadMgr.fileService.remove(a)};this.getFileLink=function(a){return ba()+
"/DOWNLOAD?s="+ja+"&f="+a};this.getGateway=function(){return e};this.reconnect=function(a,c,f){};this.sendKeyboardSyncFlags=function(a){return C?(this.remoteLockFlags=this.localLockFlags=a,!0):!1}};void 0!=A.displayMsg?this.displayMsg=A.displayMsg:A.displayMsg=this.displayMsg;void 0!=A.reconnectTimes&&(this.reconnectTimes=A.reconnectTimes);void 0!=A.openLink&&(this.openLink=A.openLink);void 0!=A.setTitle&&(this.setTitle=A.setTitle);"boolean"==typeof A.useWSS&&(e=(A.useWSS?"wss":"ws")+e.substring(e.indexOf("://")));
this.getURL=function(){return e};this.setJoinMode=function(a){C&&q.send("8E1"+a)};this.refuseControl=function(a){C&&q.send("8E3"+a)};this.giveControl=function(a){C&&q.send("8E4"+a)};this.requestControl=function(){C&&q.send("8E2")};this.play=function(){q.send("F3")};this.pause=function(){q.send("F2")};this.scan=function(a){q.send("F4"+(a?"1":"0"))};this.seek=function(a){x&&C&&(q.send("F4"+(a?"1":"0")+"\t"+(a/x.getScale().x|0)),N.pause(!0))};this.allowJoin=function(a,b){q.send("8EA"+a+"\t"+(b?1:0))};
var L=null,Ea=0;this.run=function(){Oa()};this.hide=function(){x&&("block"==document.getElementById("cursorID").style.display&&(document.getElementById("cursorID").style.display="none"),x.hide())};this.showMessage=function(a,b){h.displayMsg&&a&&(x?x.showMessage(a,b):("string"==typeof a&&(a={msg:a,timeout:b||0}),hi5.notifications.notify(a)))};this.close=function(){if(q&&C)try{q.send("85"),q.close()}catch(a){}else la()};hi5.browser.isChromeApp?chrome.runtime.onSuspend.addListener(la):window.addEventListener("unload",
la,!1);var Na=!1,R=null,u=z=5,w=5,r=0,n=0,J=l.fontFamily||l.fontName||"Courier New";0<J.indexOf(" ")&&(J='"'+J+'"');var F=l.fgColor||H[7],D=l.bgColor||H[0],y=0,Y="",X="",v=0,k=18,ha=0,M="",xa=!1,Z=0,E=0,T=1,P=24,ma=0,Fa=!0,na=new Ca(1024,function(a){for(var b=!0,c;b;){c=a.getByte();if(0>c)break;if(255==c)a:{var f=a,d=f.getByte();switch(d){case 255:Ga(d);break;case 254:case 253:case 252:case 251:c=f.getByte();f=d;253!=f||za(c)?251!=f||Aa(c)?254==f?da(252,c,!1):252==f?da(254,c,!1):253==f?(da(251,c,
!1),31==c?q.send("D9"+E+"\t"+Z):12==c&&q.send("D7")):251==f&&da(253,c,!1):da(254,c,!0):da(252,c,!0);break;case 250:c=f.getByte();switch(c){case 24:c=f.getByte();ya(f);if(1!=c)break;q.send("DA");break;case 32:c=f.getByte();ya(f);if(1!=c)break;q.send("DC");break;default:ya(f)}break;default:break a}Na||(Na=!0,q.send("D0"))}else Ga(c);a.getPosition()>=a.getEnd()&&(""!=M&&wa(M),b=!1)}});ca.setHandler(na);this.addSurface=function(a){x=a;Ma&&a.setPlayerMode();N.setContext(x.context);g=N.getContext();S=g.canvas;
a.forceTextArea=!0;a.setAutoScale(0<h.mode);a.setSize(p+z,t+z);a.setController(I);a.setFastCopy(V(l.fastCopy));a.setTouchpad(V(l.touchpad));a.setClipboard(V(l.mapClipboard));var b=void 0!=l.cmdToCtrl?V(l.cmdToCtrl):void 0!=A.cmdToCtrl?A.cmdToCtrl:h.mapCmdToCtrl;a.run(99997,!1,!0,b);a.onclipdata=Za};this.writeText=fa;this.writeScancode=function(a,b){fa(oa.process(a,b,0))};var ab={" ":57,space:57,pageup:201,pagedown:209,end:207,home:199,left:203,up:200,right:205,down:208,printscreen:183,insert:210,
del:211,"delete":211,altgr:184,windows:219,windowsright:220,context:221,esc:1,backspace:14,tab:15,enter:28,meta:29,command:29,ctrl:29,shift:42,alt:56,capslock:58,f1:59,f2:60,f3:61,f4:62,f5:63,f6:64,f7:65,f8:66,f9:67,f10:68,f11:87,f12:88,numlock:69,scrolllock:70,add:78};this.writeKeyComb=function(a){a=a.split("+");var b=a.length;if(0!=b)for(var c=null,f=0;f<b;f++){var d=a[f];""==d&&""==c&&(d="Add");if(""!=d){var c=d,e=ab[c.toLowerCase()];e?h.writeScancode(!0,e):console.log("Invalid key:"+c)}c=d}};
this.writeRawInput=function(a){if(sa){var b=parseInt(a.substring(0,2),16);a=a.substring(2).split("\t");switch(b){case 128:2==a[2]&&$a();return;case 129:return;case 130:return;case 131:return;case 132:b=parseInt(a[1]);a=0==a[0];fa(oa.process(a,b,0));return;case 139:b=parseInt(a[1]);a=0==a[0];fa(oa.process(a,b,1));return;case 134:fa(oa.process(!0,a[0],3));return}svGlobal.logger.warn("Unknowncode: "+a[1]+" type:"+b)}};var oa=new function(a,b,c){var f=!1,d=!1,e=!1;this.process=function(a,b,c){if(3==c)return b;
if(0==c){switch(b){case 29:case 157:return f=a,"";case 56:case 184:return d=a,"";case 42:case 54:return e=a,""}if(a){switch(b){case 28:a="\r\n";break;case 200:a="\u001b[A";break;case 208:a="\u001b[B";break;case 205:a="\u001b[C";break;case 203:a="\u001b[D";break;case 59:a="\u001bOP";break;case 60:a="\u001bOQ";break;case 61:a="\u001bOR";break;case 62:a="\u001bOS";break;case 63:a="\u001b[15~";break;case 64:a="\u001b[17~";break;case 65:a="\u001b[18~";break;case 66:a="\u001b[19~";break;case 67:a="\u001b[20~";
break;case 68:a="\u001b[21~";break;case 87:a="\u001b[23~";break;case 88:a="\u001b[24~";break;case 15:a="\t";break;case 209:a="\u001b[6~";break;case 201:a="\u001b[5~";break;case 199:a="\u001b[H";break;case 207:a="\u001b[F";break;case 14:a=e?"\b":"\u007f";break;case 211:a="\u001b[3~";break;case 197:a="\u00ff\u00f3";break;case 210:a="\u001b[2~";break;case 1:a="\u001b";break;case 55:a="*";break;case 71:a=I.localLockFlags&2?"7":"\u001b[H";break;case 72:a=I.localLockFlags&2?"8":"\u001b[A";break;case 73:a=
I.localLockFlags&2?"9":"\u001b[5~";break;case 74:a="-";break;case 75:a=I.localLockFlags&2?"4":"\u001b[D";break;case 76:a="5";break;case 77:a=I.localLockFlags&2?"6":"\u001b[C";break;case 78:a="+";break;case 79:a=I.localLockFlags&2?"1":"\u001b[F";break;case 80:a=I.localLockFlags&2?"2":"\u001b[B";break;case 81:a=I.localLockFlags&2?"3":"\u001b[6~";break;case 82:a=I.localLockFlags&2?"0":"\u001b[2~";break;case 83:a=I.localLockFlags&2?".":"\u001b[3~";break;case 156:a="\r\n";break;case 181:a="/";break;default:return console.log("Invalid code:"+
b),""}d&&(a="\u001b"+a);return a}return""}if(1==c&&f){if(64<b&&91>b)return String.fromCharCode(b-64);switch(b){case 54:return"\u001e";case 219:return"\u001b";case 220:return"\u001c";case 221:return"\u001d";case 32:return"\x00";case 192:return"\u001e";case 191:return"\u001f";default:return console.log("Invalid key code:"+b),""}}if(d)return"\u001b"+String.fromCharCode(b).toLowerCase()}}};
