var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(h,l,p){if(null==h)throw new TypeError("The 'this' value for String.prototype."+p+" must not be null or undefined");if(l instanceof RegExp)throw new TypeError("First argument to String.prototype."+p+" must not be a regular expression");return h+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(h,l,p){if(h==Array.prototype||h==Object.prototype)return h;h[l]=p.value;return h};
$jscomp.getGlobal=function(h){h=["object"==typeof globalThis&&globalThis,h,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var l=0;l<h.length;++l){var p=h[l];if(p&&p.Math==Math)return p}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(h,l){var p=$jscomp.propertyToPolyfillSymbol[l];if(null==p)return h[l];p=h[p];return void 0!==p?p:h[l]};$jscomp.polyfill=function(h,l,p,D){l&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(h,l,p,D):$jscomp.polyfillUnisolated(h,l,p,D))};
$jscomp.polyfillUnisolated=function(h,l,p,D){p=$jscomp.global;h=h.split(".");for(D=0;D<h.length-1;D++){var L=h[D];if(!(L in p))return;p=p[L]}h=h[h.length-1];D=p[h];l=l(D);l!=D&&null!=l&&$jscomp.defineProperty(p,h,{configurable:!0,writable:!0,value:l})};
$jscomp.polyfillIsolated=function(h,l,p,D){var L=h.split(".");h=1===L.length;D=L[0];D=!h&&D in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var da=0;da<L.length-1;da++){var Z=L[da];if(!(Z in D))return;D=D[Z]}L=L[L.length-1];p=$jscomp.IS_SYMBOL_NATIVE&&"es6"===p?D[L]:null;l=l(p);null!=l&&(h?$jscomp.defineProperty($jscomp.polyfills,L,{configurable:!0,writable:!0,value:l}):l!==p&&($jscomp.propertyToPolyfillSymbol[L]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(L):$jscomp.POLYFILL_PREFIX+
L,L=$jscomp.propertyToPolyfillSymbol[L],$jscomp.defineProperty(D,L,{configurable:!0,writable:!0,value:l})))};$jscomp.polyfill("String.prototype.startsWith",function(h){return h?h:function(l,p){var D=$jscomp.checkStringArgs(this,l,"startsWith");l+="";var L=D.length,da=l.length;p=Math.max(0,Math.min(p|0,D.length));for(var Z=0;Z<da&&p<L;)if(D[p++]!=l[Z++])return!1;return Z>=da}},"es6","es3");var svManager={getInstance:function(){var h=window.$telnet;return h&&h.running&&h.running()?h:null}};
function connvertServer(h){var l={};l.id=h.id;l.server=h.id;l.displayName=h.displayName||h.id;if(h=h.vnc)for(var p in h)l[p]=h[p];return l}
svGlobal.TELNET=function(h,l,p){function D(b){f.loadbalanceToken||(E.randomAppId&&(b=hi5.tool.uuid()),f.loadbalanceToken=E.loadbalanceTokenName?E.loadbalanceTokenName+"="+b:"")}function L(b,a){var c=[],d=null,e=new hi5.graphic.Rectangle(0,0,0,0),F="Uint8ClampedArray"in window;this.width=b;this.height=a;var g=!1,H=this;this.pause=function(m){g=m};this.release=function(){c=d=H=null};this.isPaused=function(){return g};this.setContext=function(m){m!=d&&(d||!m||m.createImageData(1,1).data.buffer||(F=!1),
d=m)};this.getContext=function(){return d};this.resize=function(m,r){for(var u=0;u<r;u++)c[u]=new Uint32Array(m);H.width=b=m;H.height=a=r};H.resize(b,a);this.getBuffer=function(){return c};this.setRGB=function(m,r,u){c[r][m]=u|4278190080};this.getRGB=function(m,r){return c[r][m]};this.setRGBs=function(m,r,u,x,I,A,K){u=m+u;x=r+x;for(var B=c,G,O=r;O<x;O++,A+=K){var ea=A;G=B[O];for(r=m;r<u;r++)G[r]=I[ea++]}};this.moveArea=function(m,r,u,x,I,A){if(0<A){I=m+I;A=r+A;var K=c,B;for(B=x-1;0<=B;B--){var G=
K[A+B];var O=K[r+B];for(x=0;x<u;x++)G[I+x]=O[m+x]}}else if(0>A)for(I=m+I,A=r+A,K=c,G=0;G<x;G++){O=K[A+G];var ea=K[r+G];for(B=0;B<u;B++)O[I+B]=ea[m+B]}else if(0<I)for(I=m+I,A=r+A,K=c,--u;0<=u;u--)for(G=I+u,O=m+u,B=0;B<x;B++)K[A+B][G]=K[r+B][O];else for(I=m+I,A=r+A,K=c,B=0;B<u;B++)for(O=I+B,ea=m+B,G=0;G<x;G++)K[A+G][O]=K[r+G][ea]};this.getRGBs=function(m,r,u,x){var I=new Uint32Array(u*x);I[0]=0;var A=c;u=m+u;x=r+x;for(var K=0,B=r;B<x;B++)for(r=m;r<u;r++)I[K++]=A[B][r];return I};this.repaint=function(m,
r,u,x){if(d){0>m&&(u+=m,m=0);0>r&&(x+=r,r=0);m+u>b&&(u=b-m);r+x>a&&(x=a-r);var I=d.createImageData(u,x),A=I.data;u=m+u;x=r+x;var K=0,B=c;if(F){A=new Uint32Array(A.buffer);for(var G,O=r;O<x;O++)for(G=m;G<u;G++)A[K++]=B[O][G]}else for(O=r;O<x;O++)for(G=m;G<u;G++){var ea=B[O][G];var Ba=K<<2;A[Ba]=ea&255;A[Ba+1]=ea>>8&255;A[Ba+2]=ea>>16&255;A[Ba+3]=255;K++}d.putImageData(I,m,r)}};this.postPaint=function(m,r,u,x){0<e.width?e.union(m,r,u,x):(e.x=m,e.y=r,e.width=u,e.height=x)};this.commitPaint=function(){0<
e.width&&(this.repaint(e.x,e.y,e.width,e.height),e.width=0)};this.fillRect=function(m,r,u,x,I){var A=c;u=m+u;x=r+x;for(var K=r;K<x;K++)for(r=m;r<u;r++)A[K][r]=I}}function da(b,a){aa?aa.resize(b,a):aa=new L(b,a);return aa}function Z(){var b=h.indexOf("://"),a=h.substring(b+3);b=a.indexOf("/");0<b&&(a=a.substring(0,b));return location.protocol+"//"+a}function kb(b){return Ca?hi5.browser.httpGet(Z()+"/CLIP?s="+Ca+"&t="+(new Date).getTime(),!1):""}function wa(b){return"on"==b||"true"==b||1==b}function Ua(){return q.displayName||
q.server||q.symlink||q.id||"undefined"}function Va(b,a,c){this.need=b;this.handler=a;this.repeat=c||1}function lb(){if(!Q){Wa();if(Ha)v=Ha;else{var b=f.getRuntimeURL(!0);v=f.oncreatewebsocket?f.oncreatewebsocket(b):new WebSocket(b,"telnet");v.binaryType="arraybuffer"}W.ws=v;svGlobal.logger.info(h);v.onopen=mb;void 0!=q.recording&&"on"==q.recording&&nb(q);v.onmessage=function(a){a=a.data;if("string"!=typeof a){var c=new Uint8Array(a);null!=ba&&ba.add(new RecordingObj(c,0,a.byteLength));sa.set(c,0,
a.byteLength);sa.handle()}else{var d=parseInt(a.substring(0,2),16);c=a.substring(2);switch(d){case 0:a=f.getRuntimeURL(!1);a=a.substring(a.indexOf("?")+1);v.send("00"+a);break;case 15:JSON.parse(c);if(f){if(f.onready)f.onready();if(f.onloggedin)f.onloggedin();E.pingInterval&&f.startPing(E.pingInterval)}break;case 26:a=JSON.parse(c);if(a.name){svGlobal.logger.info("msg="+c);if(f.onerror)f.onerror(a);c=__svi18n.errorCode["S"+a.name]||"";c+=a.message||a.msg;f.showMessage(c)}else 0<svGlobal.log&&console.erro("No error code for message:"+
c);break;case 27:0!=E.drawLicense&&(J.drawLicense(c),Ia(q.fontSize));break;case 56:a=JSON.parse(c);Ca=a.session;D(a.appId);a.server||(a.server=Ua());if(c=hi5.$("joinSelect"))c.value=a.joinMode;if(c=hi5.$("requestControl"))c.disabled=a.hasControl;c=ob("jointelnet.html")+"?id="+a.numericId;c=f.modifyURL(c);var e=a.webAddress;e&&0<e.length&&(d=e.indexOf("://"),e=e.substring(d+3),d=e.indexOf("/"),0<d&&(e=e.substring(0,d)),e.toLowerCase()!=location.host.toLowerCase()&&(c+="&gateway="+e));a.joinLink=c;
f.sessionInfo.appInfo=a;a.ver&&a.ver!=svGlobal.version&&svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+a.ver);if(f.onsessionstart)f.onsessionstart(f.sessionInfo);break;case 59:a=hi5.Base64.dec(c,0);Ja=a[3]<<24|a[2]<<16|a[1]<<8|a[0];Ja&64&&f.showMessage(__svi18n.info.recording);J.setFeature(Ja);break;case 61:a=JSON.parse(c);switch(a.type){case 0:q.fontSize=parseInt(a.fontSize);l=a.width;p=a.height;Wa();J.setAutoScale(!0);Da(l+N,p+N);a.server&&(f.server=a.server,c=Ua(),f.setTitle&&(document.title=
c));Xa=a.length;if(f.onopened)f.onopened(a);break;case 1:a=a.duration;if(f.onprogress)f.onprogress(a,Xa);break;case 2:2==a.status?Q=!0:(c=0==a.status,aa.pause(c),a.warn&&f.showMessage(c?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed))}break;case 62:pb(c);break;default:svGlobal.logger.warn("@TODO:"+a+"\n")}}};v.onclose=Ea;v.onerror=qb;Da(l+N,p+N)}}function nb(b){ba=new RecordingManager;ba.setHeader({name:"rec",width:b.width,height:b.height,color:b.fontSize,namesuffix:".telnetv",filetag:"TELV",
duration:0})}function rb(b,a){var c=0,d=!1;this.width=b;this.interval=a;var e=0;this.start=function(){d||(d=!0,c=setInterval(function(){if(J&&Q){var F=J.getThumbnail(b);F&&F.length!=e&&(v.send("8E7"+F),e=F.length)}},a))};this.stop=function(){clearInterval(c)}}function sb(b,a){!Y||Y.width==b&&Y.interval==a||(Y.stop(),Y=null);Y||(Y=new rb(b,a));Y.start()}function pb(b){var a=parseInt(b.substring(0,1),16),c=b.substring(1);b=!1;var d=f.sessionInfo.appInfo;switch(a){case 1:var e=JSON.parse(c);f.onsessionjoin&&
(b=f.onsessionjoin(e));if(b)break;f.showMessage(__svi18n.info.joinsession.applyArgs([e.numericId,e.__ip,e.name]));break;case 2:e=JSON.parse(c);f.onsessionexit&&(b=f.onsessionexit(e));if(b)break;f.showMessage(__svi18n.info.exitsession.applyArgs([e.numericId,e.__ip,e.name]));break;case 3:e=JSON.parse(c);d.joinMode!=e.mode&&(d.joinMode=e.mode,a=hi5.$("joinSelect"))&&(a.value=e.mode);if(d.hasControl)break;J.setReadOnly(!1);if(a=hi5.$("requestControl"))a.disabled=!0;f.ongivecontrol&&(b=f.ongivecontrol());
if(b)break;f.showMessage(__svi18n.info.givecontrol);break;case 4:J.setReadOnly(!0);d.hasControl=!1;if(a=hi5.$("requestControl"))a.disabled=!1;f.ontakebackcontrol&&(b=f.ontakebackcontrol());if(b)break;f.showMessage(__svi18n.info.nocontrol);break;case 5:e=JSON.parse(c);f.onrequirecontrol&&(b=f.onrequirecontrol(e));if(b)break;b=__svi18n.info.title.applyArgs([e.name,e.numericId,e.__ip]);f.showMessage({title:b,msg:__svi18n.info.recontrol,cbYes:function(){f.giveControl(e.numericId);this.destroy()},cbNo:function(){f.refuseControl(e.numericId);
this.destroy()}});break;case 6:J.setTouchRemoting(!0);break;case 7:e=JSON.parse(c);e.cols&&e.rows&&(b=z*e.cols+2*N,a=n*e.rows+2*N,aa=da(b,a),Da(b,a));break;case 8:e=JSON.parse(c);if(f.onrequestcredential&&f.onrequestcredential(e))break;J.requestCredential(e);break;case 9:e=JSON.parse(c);0<e.interval&&0<e.width?sb(e.width,e.interval):Y&&(Y.stop(),Y=null);break;case 11:e=JSON.parse(c),f.onrequirejoin&&(b=f.onrequirejoin(e)),b||(b=__svi18n.info.title.applyArgs([e.name,e.numericId,e.__ip]),f.showMessage({title:b,
msg:__svi18n.info.reqjoin,cbYes:function(){f.allowJoin(e.numericId,!0);this.destroy()},cbNo:function(){f.allowJoin(e.numericId,!1);this.destroy()}}))}}function ob(b){var a=E.page&&E.page.join||"";if(a.startsWith("http://")||a.startsWith("https://"))return a;if(a.startsWith("/"))return location.origin+a;var c=location.href,d=c.lastIndexOf("/");if(a)return c.substring(0,d+1)+a;a=Z();c.toLowerCase().startsWith(a.toLowerCase())&&(a=c.substring(0,d));return a+"/"+b}function mb(b){svGlobal.logger.info("opened...");
Q=!0;v.send("87"+navigator.userAgent);if(f.onopen)f.onopen()}function qb(b){svGlobal.logger.warn(b)}function Ea(b){svGlobal.logger.warn("closed ...");fa&&(fa.style.display="none");xa=Q=!1;if(f)if(f.onclose)f.onclose();else if(hi5.appcfg&&hi5.appcfg.returnUrl){window.location.href=hi5.appcfg.returnUrl;return}try{null!=ba&&(ba.exit(),ba=null),J&&J.close(),ka&&ka.visible()&&(ka.dismiss(),ka=null)}catch(a){}sa&&(sa.release(),sa=null);ha=k=null;v&&(v.onopen=null,v.onmessage=null,v.onclose=null,v=v.onerror=
null);f=J=W=null;window&&window.$telnet&&(window.$telnet=null);null!=ba&&(ba.exit(),ba=null)}function Ia(b,a){a||(a=X);k.font=b+"px "+a;z=k.measureText("X").width;pa=parseInt(p/n);S=parseInt(l/z);Ka(parseInt(p/n))}function Ka(b,a){a&&(ia=a);b&&(ca=b,Fa=(ca-1)*n+C);Ya=1==ia&&ca==Math.floor(p/n)}function Da(b,a){var c=b-N,d=a-N,e=Math.floor(d/n),F=Math.floor(c/z),g=null;Q&&(g=k.getImageData(0,0,Math.min(F*z+N,S*z+N),Math.min(e*n+N,pa*n+N)));l=c;p=d;J.setSize(b,a);Ia(q.fontSize);La();g&&k.putImageData(g,
0,0);pa=e;S=F;Ka(Math.floor(p/n))}function Wa(){fa||(La(),w=y,t=C,10>q.fontSize&&(q.fontSize=10),12>=q.fontSize?(n=q.fontSize+6,ya=2):13<=q.fontSize&&18>q.fontSize?(n=q.fontSize+8,ya=2):19<=q.fontSize&&25>q.fontSize?(n=q.fontSize+12,ya=3):25<=q.fontSize&&(n=q.fontSize+16,ya=4),Ia(q.fontSize),fa=document.getElementById("cursorID"),fa.style.display="block",fa.style.width=z+"px",fa.style.height=n+"px",xa=!0)}function La(){k.fillStyle=R;k.fillRect(0,0,ha.width,ha.height);k.fillStyle=T}function Za(b,a){var c=
a.getPosition(),d="",e=a.getEnd(),F=a.getData();switch(b>>4){case 0:case 1:case 2:case 3:case 4:case 5:case 6:case 7:d+=String.fromCharCode(b);break;case 12:case 13:if(c<e)d+=String.fromCharCode((b&31)<<6|F[c++]&63);else return a.needMore=!0,d;break;case 14:if(1<e-c)d+=String.fromCharCode((b&15)<<12|(F[c++]&63)<<6|(F[c++]&63)<<0);else return a.needMore=!0,d}a.setPosition(c);return d}function $a(b,a){if(0!=M||Ma[b])""!=ja&&Na(ja),tb(b);else if(Oa){var c=U[b]||"";ja=""!=c?ja+c:ja+Za(b,a)}else ja+=Za(b,
a)}function Pa(b){for(;;){var a=b.getByte();if(255==a&&(a=b.getByte(),240==a))break}}function ta(b,a,c){v.send("D5"+b+"\t"+a+"\t"+(1==c?1:0));251==b?Qa(a):252==b?Qa(a):253==b?Ra(a):254==b&&Ra(a)}function Qa(b){return 39>=b&&0<=b&&ub[b-0]}function Ra(b){return 39>=b&&0<=b&&vb[b-0]}function tb(b){switch(b){case 0:case 24:return M=0,!1;case 26:return M=0,!1;case 5:return!1;case 7:return!1;case 8:return w-=z,w<y&&(w=y),P(),!1;case 9:var a=(w-y)/z/8;a=parseInt(1*a)+1;w=8*a*z+y;w>=S*z&&(w=y,t+=n,ua("\n"));
P();return!1;case 13:return w=y,t>C+(ca-1)*n&&(t=C+(ca-1)*n),P(),!1;case 10:case 11:case 12:return ab(),!1;case 15:return!1;case 14:return!1;case 17:case 19:return!1;case 27:return la="",M=27,!1;default:if(128<=b&&159>=b)return!1}switch(M){case 0:return!0;case 27:if("\\"==b)return!1;if(32<=b&&47>=b)return la+=String.fromCharCode(b),!1;if(32<=b&&126>=b||160<=b){null==la&&(la="");switch(b){case 48:"("==la&&(Oa=!0);break;case 65:t-=n;P();break;case 66:"("==la&&(Oa=!1);break;case "C":w+=z;P();break;case 68:""==
la&&bb(1);P();break;case 72:w=y;t+=n;break;case 77:""==la&&cb(1);break;case "P":M=0;M=144;break;case "Y":M=161;break;case "c":M=0;break;case 91:ma="";M=0;M=155;break;case 93:M=0;M=157;break;case "^":M=0,M=158}27==M&&(M=0);return!1}return!0;case 155:if(48<=b&&63>=b||32<=b&&47>=b)return ma+=String.fromCharCode(b),!1;if(32<=b&&126>=b||160<=b){a=null;null==ma&&(ma="");""!=ma&&(a=ma.split(";"));switch(b){case 65:b=null!=a&&1<=a.length?parseInt(a[0]):1;t-=b*n;t<C&&(t=C);P();break;case 66:b=null!=a&&1<=
a.length?parseInt(a[0]):1;var c=t;t+=b*n;b=(t-c)/n;ua("\n",0==b?1:b);P();break;case 67:a=null!=a&&1<=a.length?parseInt(a[0]):1;w+=a*z;P();break;case 68:a=null!=a&&1<=a.length?parseInt(a[0]):1;w-=a*z;w<y&&(w=y);P();break;case 69:b=null!=a&&1<=a.length?parseInt(a[0]):1;c=t;t+=b*n;b=(t-c)/n;ua("\n",0==b?1:b);w=y;P();break;case 70:b=null!=a&&1<=a.length?parseInt(a[0]):1;t-=b*n;t<C&&(t=C);w=y;P();break;case 72:case 102:null!=a?(1<=a.length&&(b=parseInt(a[0]),c=t,t=C+(b-1)*n,b=(t-c)/n,ua("\n",0==b?1:b)),
2<=a.length&&(a=parseInt(a[1])-1,w=y+a*z)):""==ma&&(w=y,t=C);break;case 73:a=1<=a.length?parseInt(a[0]):1;w=y+8*a*z;break;case 74:null!=a&&1<=a.length?(a=parseInt(a[0]),1==a?(k.fillStyle=R,k.fillRect(y,C,S*z,t-chart_height-C),k.fillRect(y,t,t-y,chart_height),k.fillStyle=T):2==a&&(La(),w=y,t=C)):(k.fillStyle=R,k.fillRect(w,t,S*z-w+y,pa*n-t+C),k.fillStyle=T);break;case 75:null!=a&&1<=a.length?(a=parseInt(a[0]),1==a?Sa(y,w):2==a&&Sa(y,l+N),P()):Sa(w,l+N);break;case 76:null!=a&&1<=a.length&&(b=parseInt(a[0]),
cb(b),P());break;case 77:null!=a&&1<=a.length&&(b=parseInt(a[0]),bb(b),P());break;case 80:a=null!=a&&1<=a.length?parseInt(a[0]):1;a=k.getImageData(w+a*z,t,l+N-w-a*z,n);k.fillStyle=R;k.fillRect(w,t,l+N-w,n);k.putImageData(a,w,t);k.fillStyle=T;P();break;case 88:a=null!=a&&1<=a.length?parseInt(a[0]):1;k.fillStyle=R;k.fillRect(w,t,a*z,n);k.fillStyle=T;break;case 109:if(null==a||0==a.length)k.font="normal "+q.fontSize+"px "+X,T=q.fgColor||V[7],R=q.bgColor||V[0];else{b=a.length;for(var d=0;d<b;d++)switch(c=
1*a[d],c){case 0:k.font="normal "+q.fontSize+"px "+X;R=V[0];T=V[7];break;case 1:k.font="bold "+q.fontSize+"px "+X;break;case 4:break;case 5:k.font="italic "+q.fontSize+"px "+X;break;case 7:k.font="normal "+q.fontSize+"px "+X;R=V[7];T=V[0];break;case 22:k.font="normal "+q.fontSize+"px "+X;R=V[0];T=V[7];break;case 24:break;case 25:k.font="italic "+q.fontSize+"px "+X;break;case 27:k.font="normal "+q.fontSize+"px "+X;R=V[7];T=V[0];break;default:30<=a[d]&&39>=a[d]?T=V[a[d]-30+1]:40<=a[d]&&49>=a[d]&&(R=
V[a[d]-40+1])}}break;case 114:null!=a&&2<=a.length&&(b=parseInt(a[0]),a=parseInt(a[1]),Ka(a,b))}M=0;return!1}return!0;case 144:case 157:case 158:case 159:return 48<=b&&63>=b||32<=b&&47>=b?!1:32<=b&&126>=b||160<=b?(M=160,!1):!0;case 160:return 32<=b&&126>=b||160<=b?!1:!0;case 161:return M=162,!1;case 162:return M=0,!1;default:return M=0,!1}}function Sa(b,a){k.fillStyle=R;k.fillRect(b,t,a-b,n);k.fillStyle=T}function cb(b){var a=k.getImageData(y,C+(ia-1)*n,S*z,(ca-ia-b+1)*n);k.fillStyle=R;k.fillRect(y,
C+(ia-1)*n,S*z,n*b);k.putImageData(a,y,C+(ia+b-1)*n);k.fillStyle=T}function bb(b){var a=k.getImageData(y,(ia+b-1)*n+C,S*z,(ca-ia-b+1)*n);k.fillStyle=R;k.fillRect(y,(ca-b)*n+C,S*z,b*n);k.putImageData(a,y,(ia-1)*n+C);k.fillStyle=T}function ab(){t+=n;ua("\n");P();db()}function db(){w>=S*z&&(w=y,t+=n);if(t>Fa){for(;t>Fa;)t-=n;P();if(Ya){var b=ha.height-(C+n);k.drawImage(ha,0,C+n,ha.width,b,0,C,ha.width,b);k.fillStyle=R;k.fillRect(0,Fa,ha.width,n)}else b=k.getImageData(y,C+n,S*z,(ca-1)*n),k.fillStyle=
R,k.fillRect(y,C,S*z,ca*n),k.putImageData(b,y,C);k.fillStyle=T}}function Na(b){var a=b.length,c=((w-y)/z|0)+a-S;0<c?(a-=c,eb(b.substring(0,a),a),db(),Na(b.substring(a))):(eb(b,a),"--More--"==b.trim()&&ab())}function eb(b,a){t+n>p&&(t=(pa-1)*n+C);k.fillStyle=R;k.fillRect(w,t,z*a,n);k.fillStyle=T;k.fillText(b,w,t+n-3*ya);w+=k.measureText(b).width;ua(b);P();ja=""}function P(){fa.style.top=t+"px";fa.style.left=w+"px"}function fb(b){if(Q&&za)return(b=b.getData("text/plain"))?(b=b.replace(/\r\n/g,"\n"),
va(b),!0):!1}function gb(){ka&&na&&!ka.visible()&&(na.value=qa,ka.show(),J&&J.setIgnorePaste(!1),setTimeout(function(){na.scrollTop=na.scrollHeight;na.disabled=!1},10))}function ua(b,a){if(ka){if(a)for(var c=0;c<a;c++)qa+=b;else qa+=b;1E5<qa.length&&(qa=qa.substring(4E4))}}function va(b){if(b){var a=b.length+1,c=new Uint8Array(a);c[0]=147;for(var d=1;d<a;d++)c[d]=b.charCodeAt(d-1);v.send(c.buffer)}}function wb(b,a){b&&"text/plain"==a?fb(b):f.showMessage("Please use Ctrl+V or browser's Edit menu")}
sessionStorage&&sessionStorage.clear();var ra=null,q=hi5.tool.queryToObj(h.substring(h.indexOf("?")+1)),za=wa(q.mapClipboard),na=za?document.getElementById("copytextarea"):null;na&&(na.value="");var ka=na?new hi5.Lightbox(document.getElementById("copydialog")):null,qa="";this.displayMsg=!0;this.reconnectTimes=0;this.setTitle=this.openLink=!0;this.mode=0;var Ha="object"==typeof h?h:null,hb="object"==typeof h||0<h.indexOf("/PLAY?");hb?(this.mode=1,Ha&&(h=""),h+="&touchpad=on"):0<h.indexOf("/JOIN?")&&
(this.mode=2,this.reconnectOnResize=!1);hi5.appcfg||(hi5.appcfg={img:{},toolbar:{fadable:!0},displayMsg:!0});var E=hi5.appcfg;this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:!0,trueColor:!0};var Ca="",J=null,Q=!1,xa=!1,Ja=0,N=5,ba=null;window.$telnet=this;E.copyDialog=!0;for(var U=[],oa=0;127>oa;oa++)U[oa]=String.fromCharCode(oa);U[106]="+";U[107]="+";U[108]="+";U[109]="+";U[110]="+";U[113]="_";U[116]="+";U[117]="+";U[118]="+";U[119]="+";U[120]="|";(function(){for(var b={128:199,
129:252,130:233,131:226,132:228,133:224,134:229,135:231,136:234,137:235,138:232,139:239,140:238,141:236,142:196,143:197,144:201,145:230,146:198,147:244,148:246,149:242,150:251,151:249,152:255,153:214,154:220,155:162,156:163,157:165,158:8359,159:402,160:225,161:237,162:243,163:250,164:241,165:209,166:170,167:186,168:191,169:8976,170:172,171:189,172:188,173:161,174:171,175:187,176:9617,177:9618,178:9619,179:9474,180:9508,181:9569,182:9570,183:9558,184:9557,185:9571,186:9553,187:9559,188:9565,189:9564,
190:9563,191:9488,192:9492,193:9524,194:9516,195:9500,196:9472,197:9532,198:9566,199:9567,200:9562,201:9556,202:9577,203:9574,204:9568,205:9552,206:9580,207:9575,208:9576,209:9572,210:9573,211:9561,212:9560,213:9554,214:9555,215:9579,216:9578,217:9496,218:9484,219:9608,220:9604,221:9612,222:9616,223:9600,224:945,225:223,226:915,227:960,228:931,229:963,230:181,231:964,232:934,233:920,234:937,235:948,236:8734,237:966,238:949,239:8745,240:8801,241:177,242:8805,243:8804,244:8992,245:8993,246:247,247:8776,
248:176,249:8729,250:183,251:8730,252:8319,253:178,254:9632,255:160},a=128;256>a;a++)U[a]=String.fromCharCode(b[a])})();var vb=[!0,!0,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1],ub=[!0,!1,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!0,!1,!1,!1,!1,!1,!1,!0,!0,!1,!1,!1,!1,!1,!1,!1,!1],Ma=Array(256),ib=[0,5,7,8,9,10,11,12,13,14,15,17,19,24,26,27,127,132,133,136,141,142,143,144,146,155,156,157,158,159];for(oa=
0;256>oa;oa++)Ma[oa]=!1;for(var Ta=0;Ta<ib.length;Ta++)Ma[ib[Ta]]=!0;var sa=new function(b){var a=0,c=0,d=new Uint8Array(b),e=this,F=new Va(0,null,0);this.needMore=!1;this.release=function(){e=d=F=null};this.getHandler=function(){return F};this.getData=function(){return d};this.getPosition=function(){return a};this.setPosition=function(g){a=g};this.getEnd=function(){return c};this.set=function(g,H,m){d=g;a=H;c=m};this.handle=function(){F.handler(e,F)};this.setHandler=function(g){g&&1>g.need&&svGlobal.logger.warn("need < 1");
(F=g)&&c-a>=g.need&&g.handler(e,g)};this.getByte=function(){return d[a++]};this.peekByte=function(){return d[a]};this.getBE32=function(){return d[a++]<<24|d[a++]<<16|d[a++]<<8|d[a++]};this.getBE16=function(){return d[a++]<<8|d[a++]};this.skip=function(g){a+=g};this.skipBack=function(g){a-=g};this.getBytes=function(g,H){if(H)for(var m=0;m<g;m++)H[m]=d[a++];else return H=a,a+=g,d.subarray(H,a)};this.copyToByteArray=function(g,H,m,r){hi5.Arrays.arraycopy(d,m,g,H,r)}}(4194304);this.setLinks=function(b){};
this.running=function(){return Q};this.getHistory=function(){return qa};this.mapCmdToCtrl=!0;var f=this,v=null;l||(l=window.innerWidth);l-=N;q.width=l;h+="&width="+l;p||(p=window.innerHeight);p-=N;q.height=p;h+="&height="+p;q.fontSize?q.fontSize=parseInt(q.fontSize,10):(q.fontSize=13,h+="&fontSize=13");this.server=q.server;this.port=q.port?parseInt(q.port,10):23;this.loadbalanceToken="";E.loadbalanceTokenName&&q[E.loadbalanceTokenName]&&D(q[E.loadbalanceTokenName]);this.modifyURL=function(b){f.loadbalanceToken&&
(b+="&"+f.loadbalanceToken);return b};var V="black red green yellow blue magenta cyan white gray violet".split(" "),aa=da(l,p),k=aa.getContext(),ha,W=new function(){this.ws=null;this.setJoinMode=f.setJoinMode;this.requestControl=f.requestControl;this.writeKeyComb=f.writeKeyComb;this.localLockFlags=0;this.checkLockFlags=!0;this.getAppMode=function(){return f.mode};this.send=function(a){"891"!=a&&Q&&this.ws.send(a)};this.sendInput=function(a){f.writeRawInput(a);if(f.onactivity)f.onactivity(a)};var b=
null;this.getAppInfo=function(){return f.sessionInfo.appInfo};this.onresize=function(a){if(a=a.target.svSurface){a=a.getFreeSpace();var c=a.width,d=a.height;hi5.browser.isTouch||hi5.browser.isOpera||!Q||(b&&(clearTimeout(b),b=null),b=setTimeout(function(){Da(c,d);v.send("D9"+S+"\t"+pa)},200))}};this.onorientationchange=function(a){};this.getClipData=kb;this.onfocus=function(a){};this.fileCallback=[];this.getShareFiles=function(a,c){loggedin&&(this.ws.send("3A5"+a),this.fileCallback.push(c))};this.notifyFiles=
function(a){for(var c=this.fileCallback,d=0,e=c.length;d<e;d++)c[d](a)};this.getFile=function(a){window.open(f.getFileUrl(a))};this.removeFile=function(a){uploadMgr&&uploadMgr.fileService.remove(a)};this.getFileLink=function(a){return Z()+"/DOWNLOAD?s="+Ca+"&f="+a};this.getGateway=function(){return h};this.reconnect=function(a,c,d){};this.sendKeyboardSyncFlags=function(a){return Q?(this.remoteLockFlags=this.localLockFlags=a,!0):!1}};void 0!=E.displayMsg?this.displayMsg=E.displayMsg:E.displayMsg=this.displayMsg;
void 0!=E.reconnectTimes&&(this.reconnectTimes=E.reconnectTimes);void 0!=E.openLink&&(this.openLink=E.openLink);void 0!=E.setTitle&&(this.setTitle=E.setTitle);"boolean"==typeof E.useWSS&&(h=(E.useWSS?"wss":"ws")+h.substring(h.indexOf("://")));this.getURL=function(){return h};this.getRuntimeURL=function(b){var a=hi5.tool.replaceQuery(h,"pwd","x");a+="&binary=on";var c=window.opener;if(c){var d=null;try{d=c.__sparkUser}catch(e){}d&&(c=d.account,d=d.session,c&&(a+="&account="+c),d&&(a+="&session="+d))}a+=
"&pasteCap="+(hi5.browser.isChrome&&hi5.browser.isDesktop?3:0);b&&0==f.mode&&E.wsPost&&(a=h.substring(0,h.indexOf("?"))+"?_METHOD=post");a=f.modifyURL(a);(b=hi5.browser.cookie.get("__SV_TOKEN_A"))&&(a+="&__SV_TOKEN_A="+encodeURIComponent(b));return a};this.setJoinMode=function(b){Q&&v.send("8E1"+b)};this.refuseControl=function(b){Q&&v.send("8E3"+b)};this.giveControl=function(b){Q&&v.send("8E4"+b)};this.requestControl=function(){Q&&v.send("8E2")};this.play=function(){v.send("F3")};this.pause=function(){v.send("F2")};
this.scan=function(b){v.send("F4"+(b?"1":"0"))};this.seek=function(b){J&&Q&&(v.send("F4"+(b?"1":"0")+"\t"+(b/J.getScale().x|0)),aa.pause(!0))};this.allowJoin=function(b,a){v.send("8EA"+b+"\t"+(a?1:0))};var Y=null,Xa=0;this.run=function(){lb()};this.hide=function(){J&&("block"==document.getElementById("cursorID").style.display&&(document.getElementById("cursorID").style.display="none"),J.hide())};this.showMessage=function(b,a){f.displayMsg&&b&&(J?J.showMessage(b,a):("string"==typeof b&&(b={msg:b,timeout:a||
0}),hi5.notifications.notify(b)))};this.close=function(){if(v&&Q)try{v.send("85"),v.close()}catch(b){}else Ea()};hi5.browser.isChromeApp?chrome.runtime.onSuspend.addListener(Ea):window.addEventListener("unload",Ea,!1);var jb=!1,fa=null,y=N=5,C=5,w=0,t=0,X=q.fontFamily||q.fontName||"Courier New";0<X.indexOf(" ")&&(X='"'+X+'"');var T=q.fgColor||V[7],R=q.bgColor||V[0],M=0,ma="",la="",z=0,n=18,ya=0,ja="",Oa=!1,pa=0,S=0,ia=1,ca=24,Fa=0,Ya=!0,xb=new Va(1024,function(b){var a=!0;for(b.needMore=!1;a;){var c=
b.getByte();if(0>c)break;if(255==c)a:{var d=b,e=d.getByte();switch(e){case 255:$a(e,d);break;case 254:case 253:case 252:case 251:c=d.getByte();d=e;253!=d||Qa(c)?251!=d||Ra(c)?254==d?ta(252,c,!1):252==d?ta(254,c,!1):253==d?(ta(251,c,!1),31==c?v.send("D9"+S+"\t"+pa):12==c&&v.send("D7")):251==d&&ta(253,c,!1):ta(254,c,!0):ta(252,c,!0);break;case 250:c=d.getByte();switch(c){case 24:c=d.getByte();Pa(d);if(1!=c)break;v.send("DA");break;case 32:c=d.getByte();Pa(d);if(1!=c)break;v.send("DC");break;default:Pa(d)}break;
default:break a}jb||(jb=!0,v.send("D0"))}else $a(c,b);b.getPosition()>=b.getEnd()&&(""!=ja&&Na(ja),a=!1)}});sa.setHandler(xb);var Aa=document.getElementById("svHistory");za?Aa&&(Aa.onclick=gb):Aa&&Aa.parentNode.removeChild(Aa);this.showHistory=gb;this.addSurface=function(b){J=b;hb&&b.setPlayerMode();aa.setContext(J.context);k=aa.getContext();ha=k.canvas;b.setAutoScale(0<f.mode);b.setSize(l+N,p+N);b.setController(W);b.setFastCopy(wa(q.fastCopy));b.setTouchpad(wa(q.touchpad));b.setClipboard(wa(q.mapClipboard));
var a=void 0!=q.cmdToCtrl?wa(q.cmdToCtrl):void 0!=E.cmdToCtrl?E.cmdToCtrl:f.mapCmdToCtrl;b.run(99997,!1,!0,a);za&&(b.onclipdata=fb)};this.sendPing=function(b){b=new Uint8Array(2);b[0]=146;v.send(b.buffer)};this.startPing=function(b){ra||(ra=new hi5.tool.ResponseMonitor(function(){xa&&f.sendPing()},function(){xa&&ra.check(1)}));ra.setInterval(b,b);setTimeout(function(){ra.check()},1E3*b)};this.stopPing=function(){ra&&ra.stop()};this.writeText=va;this.writeScancode=function(b,a){va(Ga.process(b,a,0))};
var yb={" ":57,space:57,pageup:201,pagedown:209,end:207,home:199,left:203,up:200,right:205,down:208,printscreen:183,insert:210,del:211,"delete":211,altgr:184,windows:219,windowsright:220,context:221,esc:1,backspace:14,tab:15,enter:28,meta:29,command:29,ctrl:29,shift:42,alt:56,capslock:58,f1:59,f2:60,f3:61,f4:62,f5:63,f6:64,f7:65,f8:66,f9:67,f10:68,f11:87,f12:88,numlock:69,scrolllock:70,add:78};this.writeKeyComb=function(b){b=b.split("+");var a=b.length;if(0!=a)for(var c=null,d=0;d<a;d++){var e=b[d];
""==e&&""==c&&(e="Add");if(""!=e){c=e;var F=yb[c.toLowerCase()];F?f.writeScancode(!0,F):console.log("Invalid key:"+c)}c=e}};this.writeRawInput=function(b){if(xa){var a=parseInt(b.substring(0,2),16);b=b.substring(2).split("\t");switch(a){case 128:2==b[2]&&za&&J.processClipReq("text/plain",wb);return;case 129:return;case 130:return;case 131:return;case 132:a=parseInt(b[1]);b=0==b[0];va(Ga.process(b,a,0));return;case 139:a=parseInt(b[1]);b=0==b[0];va(Ga.process(b,a,1));return;case 134:va(Ga.process(!0,
b[0],3));return}svGlobal.logger.warn("Unknowncode: "+b[1]+" type:"+a)}};var Ga=new function(b,a,c){var d=!1,e=!1,F=!1;this.process=function(g,H,m){if(3==m)return H;if(0==m){switch(H){case 29:case 157:return d=g,"";case 56:case 184:return e=g,"";case 42:case 54:return F=g,""}if(g){switch(H){case 28:g="\r\n";break;case 200:g="\u001b[A";break;case 208:g="\u001b[B";break;case 205:g="\u001b[C";break;case 203:g="\u001b[D";break;case 59:g="\u001bOP";break;case 60:g="\u001bOQ";break;case 61:g="\u001bOR";
break;case 62:g="\u001bOS";break;case 63:g="\u001b[15~";break;case 64:g="\u001b[17~";break;case 65:g="\u001b[18~";break;case 66:g="\u001b[19~";break;case 67:g="\u001b[20~";break;case 68:g="\u001b[21~";break;case 87:g="\u001b[23~";break;case 88:g="\u001b[24~";break;case 15:g="\t";break;case 209:g="\u001b[6~";break;case 201:g="\u001b[5~";break;case 199:g="\u001b[H";break;case 207:g="\u001b[F";break;case 14:g=F?"\b":"\u007f";break;case 211:g="\u001b[3~";break;case 197:g="\u00ff\u00f3";break;case 210:g=
"\u001b[2~";break;case 1:g="\u001b";break;case 55:g="*";break;case 71:g=W.localLockFlags&2?"7":"\u001b[H";break;case 72:g=W.localLockFlags&2?"8":"\u001b[A";break;case 73:g=W.localLockFlags&2?"9":"\u001b[5~";break;case 74:g="-";break;case 75:g=W.localLockFlags&2?"4":"\u001b[D";break;case 76:g="5";break;case 77:g=W.localLockFlags&2?"6":"\u001b[C";break;case 78:g="+";break;case 79:g=W.localLockFlags&2?"1":"\u001b[F";break;case 80:g=W.localLockFlags&2?"2":"\u001b[B";break;case 81:g=W.localLockFlags&2?
"3":"\u001b[6~";break;case 82:g=W.localLockFlags&2?"0":"\u001b[2~";break;case 83:g=W.localLockFlags&2?".":"\u001b[3~";break;case 156:g="\r\n";break;case 181:g="/";break;default:return console.log("Invalid code:"+H),""}e&&(g="\u001b"+g);return g}return""}if(1==m&&d){if(64<H&&91>H)return String.fromCharCode(H-64);switch(H){case 54:return"\u001e";case 219:return"\u001b";case 220:return"\u001c";case 221:return"\u001d";case 32:return"\x00";case 192:return"\u001e";case 191:return"\u001f";default:return console.log("Invalid key code:"+
H),""}}if(e)return"\u001b"+String.fromCharCode(H).toLowerCase()}}};
